= Phase 1 - Prerequisites
:page-platform: Server 4.9, Server Admin
:experimental:
:page-description: A guide to installing CircleCI Server 4.9 in an air-gapped environment. Requirements, images and Helm charts.

The guides in this section walk you through the steps required to install CircleCI Server in an air-gapped environment.

[#required-components]
== Required components for air-gapped installation
The following table shows an overview of the prerequisites required to run an air-gapped CircleCI Server installation. These items must be present in your air-gapped environment in order to move forward with the installation.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Component
| Used for

| Container registry
| Hosting CircleCI Server images for Kubernetes

| A Kubernetes cluster
| Running CircleCI Server

| An object storage system (MinIO)
| Object and artifact storage

| GitHub Enterprise
| Source of code for CircleCI Server to build

| Nomad Virtual Machines
| Machines for running Nomad

|===

[#copy-images]
== 1. Copy images

CircleCI Server is deployed into a Kubernetes cluster using a Helm chart. You will need to copy the latest images and charts from CircleCI into your virtual environment. All images referenced in the CircleCI Helm chart must be accessible within your air-gapped environment.

[#login-to-acr]
=== a. Log in to CircleCI Server container registry
Access to the images you need for your installation requires you to use a username and token, which will be provided by CircleCI. Access the link:https://support.circleci.com/[CircleCI support portal] for more information.

[,bash]
----
docker login cciserver.azurecr.io --username <your-circleci-provided-username> --password <your-circleci-provided-token>
----

=== b. Download all images required for this release
Download all images required for the release of CircleCI Server to your local machine. This list contains all required images for the Helm installation, the CircleCI Agent, and the Reality Check testing tool.

. Download the script to a convenient location:
+
[,bash]
----
curl -fsSL https://raw.githubusercontent.com/CircleCI-Public/server-scripts/main/air-gap/extract-images-from-helm-chart.sh -o extract-images-from-helm-chart.sh
----

. Fetch the Helm chart for inspection:
+
[,bash,subs=attributes+]
----
helm fetch oci://cciserver.azurecr.io/circleci-server --version {serverversion49} --untar
----

. Extract images to `images.txt`:
+
[,bash]
----
bash ./extract-images-from-helm-chart.sh ./circleci-server images.txt
----

. Pull all images to your local machine:
+
[,bash]
----
while read -r image; do docker pull "$image"; done < images.txt
----

[#copy-all-images]
=== c. Copy all images to your air-gapped environment
Copy all downloaded images to the container registry in your air-gapped environment.

[#copy-charts]
== 2. Copy charts
Copy the CircleCI Server Helm chart to your air-gapped environment.

[#download-helm-chart]
=== a. Download the latest CircleCI Server Helm chart
Download the latest CircleCI Server Helm chart to the current directory.

[,bash]
----
helm registry login cciserver.azurecr.io
helm pull oci://cciserver.azurecr.io/circleci-server -d ./
----

[#upload-helm-chart]
=== b. Copy the Helm chart to your air-gapped environment
Copy the downloaded `.tgz` Helm chart to your air-gapped environment.

[#next-steps]
== Next steps

Once the steps on this page are complete, go to the xref:phase-2-configure-object-storage.adoc[Phase 2 - Configure Object Storage] guide.
