== Step 2: Create a Service

In Vamp, a service is a microservice. You can create up to six services with the Quick Start Guide.

=== Name

Enter a unique name for your service. This name is displayed wherever your application is used, including external notifications like Slack.

=== Description

Enter a description (optional).

=== Type

Choose a service type. Vamp supports two types of service: _API-based services_ and _message-based services_.

// Looks as though message-based services aren't currently supported. This option is greyed out.

API-based services exposes a REST-based or GraphQL-based API and can be released progressively using traffic shaping.

Message-based services either do not expose an API, or expose an API using a message system like NATS. This type of service cannot be progressively released.

=== API-based Services Type

An API-based service can be either headed or headless. A managed Kubernetes Service will be created for a headed service using the specified container port. Only headed services can be released progressively.

=== Container Port

Enter your container port number, for example _5000_.

NOTE: Vamp currently supports only one network port per service.
Your container can expose multiple network ports, but Vamp will only create a Kubernetes Service for the chosen port.

There are several ways to find the container port for your service:

* In Dockerfile, look for an `EXPOSE instruction`.
* From a running Docker container, use the `docker port <container-id | container-name>` command.
* For a Kubernetes deployment, look for the `containerPort` value in your YAML file.

=== Workload Type

Vamp supports two types of Kubernetes workload: Deployments and StatefulSets.

// Looks as though StatefulSets aren't supported. This option is greyed out.

=== App Label

Vamp discovers new versions of your service using Kubernetes labels. Each Kubernetes workload released by Vamp needs to include an _app_ label set. This label is used to locate all the instances of your service for an application.

The value for the app label must be unique and is normally the name of the service.

=== Version Label

Vamp uses the _version_ label to distinguish between versions of your service. This label is also used to decide which release policy to apply when releasing a new version of your service. You can either use the default _version_, or enter your own label here.

When you have finished entering the details for your service, either click **Next** or click **Save & Add another service** if you want to create additional services.

You will see a pop up message to confirm that your service has been created.

NOTE: You can create a total of six services in the Quick Start Guide.