== Step 1: Create an Application

In Vamp, an application is a collection of microservices that share a single Kubernetes namespace.

=== Name

Enter a unique name for your application. This name is displayed wherever your application is used, including external notifications like Slack.

=== Description

Enter a description (optional).

=== Cluster

Select your cluster name from the list, or add a new one by clicking **Create New Cluster** at the bottom of the list. If your applications are distributed across multiple clusters, you can add additional clusters.

=== Namespace

Enter the namespace where your microservices will run.

=== Ingress Controller

Select your Ingress Controller. Vamp supports NGINX and Contour. If your application does not expose any services, choose _NO INGRESS_.

NOTE: We recommend you use Contour, as it allows a richer set of release policies.

Once you have finished adding the details for your application, click **Next** in the bottom left-hand corner. You will see a pop up message to confirm that your application has been created.