---
contentTags:
  platform:
  - Cloud
---
= Set up a release integration - Open preview
:page-layout: classic-docs
:page-liquid:
:page-description: Tutorial outlining how to set up a new CircleCI release integration.
:icons: font
:experimental:

NOTE: CircleCI releases is currently in **open preview**

Visualise and control releases to your Kubernetes cluster with CircleCI release integrations. The steps outlined on this page guide you to set up a release integration.

[#introduction]
== Introduction

In this tutorial you will set up an integration between CircleCI and your Kubernetes cluster. Once configured, release status can be reported to the CircleCI web app, and commands from CircleCI can be #mapped to your release ???# to enable you to:

* Restore a version
* Scale a version
* Restart a version
* Retry a release (if using Argo Rollouts)
* Promote a release (if using Argo Rollouts)
* Cancel a release (if using Argo Rollouts)

[#prerequisites]
== Prerequisites

In order to set up a release integration with CircleCI you will need to ensure the following prerequisites are fulfilled:

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free].
* A code repository building on CircleCI.
* You must be an **org admin**. For full details of roles and permissions for GitLab and GitHub App integrations, see the xref:../roles-and-permissions-overview.adoc#[Roles and permissions overview]. If your integration is through Bitbucket or the GitHub OAuth app, you will need to be an org admin in Bitbucket/GitHub respectively. To find out which GitHub integration you have, see the xref:../github-apps-integration.adoc#[GitHub App integration] page.
* A Kubernetes .... #Not sure of the specifics here - they need a Kubernetes cluster to which they are deploying something? Or should we say a Kubernetes Deployment?#

CircleCI supports Kubernetes, Helm, and Argo Rollouts. The supported versions are listed below:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|System
|Supported versions

|Kubernetes
a| 1.28.0 +
1.27.0

|Helm (optional)
a| 3.12.0 +
3.11.0

|Argo Rollouts (optional)
a| 1.6.0 +
1.5.0
|===


NOTE: Prerequisites might not be the same for every user, or it might not be possible to outline every prerequisite given the different systems/environments that different orgs/teams/users may use.

Prerequisites may include things like:

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free].
* A code repository you want to build on CircleCI.

== 1. The first step

The main body of the tutorial should be broken into logical steps with headings for each step. The steps should guide the reader through setting up and using the feature. Write the section headings with an active voice to show what will be done. The reader should ideally be able to read the page table of contents and understand what they will achieve and how.

[#the-second-step]
== 2. The second step

Each main step in the tutorial should be under its own level 2 (`==`) heading, using the numbered list format.

[#conclusion]
== Conclusion

In this tutorial you have integrated your Kubernetes cluster with CircleCI. You can now #link to command how to guides#

[#next-steps]
== Next steps

// Here you can inlude links to other pages in docs or the blog etc. where the reader should head next.
* xref:../benefits-of-circleci#[Benefits of CircleCI]
* xref:../concepts#[CircleCI concepts]
