//== Command line installation: pre-steps

// Display the following step for machine runner installation only as container runner is not yet available on server
ifdef::machine[]
NOTE: If you are installing **self-hosted runners for server**, the CircleCI CLI needs to be configured using your server API key. Run `circleci setup` to configure the CLI and access the option to supply a new API token if required.
endif::[]

To install self-hosted runners, you need to create a namespace and resource class, and a resource class token. You need to be an organization admin to complete this process.

You can view your installed runners on the inventory page in the link:https://app.circleci.com/[web app] by selecting *Runners* from the sidebar.

. Create a namespace for your organization's self-hosted runners. *Each organization can only create a single namespace*. We suggest using a lowercase representation of your CircleCI organization's account name. If you already use orbs, this namespace is the same namespace orbs use.
+
Use the following command to create a namespace if your organization does not already have a namespace:
+
[source,console]
$ circleci namespace create <name> --org-id <your-organization-id>

. Create a resource class for your runner using the following command:
+
[source,console]
$ circleci runner resource-class create <namespace>/<resource-class> <description> --generate-token
+
Make sure to replace `<namespace>` and `<resource-class>` with your org namespace and desired resource class name, respectively. You can add a description but this is optional.
+
Resource class names must follow specific naming conventions.
+
** The *namespace* can contain lowercase letters, numbers, underscores, and dashes.
** The *resource class name* can contain uppercase and lowercase letters, numbers, colons, underscores, dashes, and plus signs.
+
The resource class token is returned after the runner resource class is successfully created.
+
CAUTION: The token is only displayed once, so be sure to store it safely.
