---

version:
- Cloud
- Server v3.x
- Server v2.x
---
= Bitbucket Integration
:page-layout: classic-docs
:page-liquid:
:page-description: This document provides an overview of using Bitbucket with CircleCI.
:icons: font
:toc: macro

:toc-title:

toc::[]

[#overview]
== 概要

To use CircleCI with Bitbucket you need to connect your Bitbucket account. When you add a project to CircleCI, the following settings are added to the repository using the permissions you gave CircleCI when you signed up:

- A deploy key that is used to check out your project from Bitbucket.
- A service hook (or "push hook") that is used to notify CircleCI when you push to Bitbucket.

CircleCI のデフォルトでは、プッシュ フックでビルドが行われます。 したがって、リポジトリのすべてのプッシュ フックに対してビルドがトリガーされます。また、プッシュはビルドをトリガーする最も一般的なケースです。

あまり一般的ではありませんが、CircleCI は以下の場合にもフックを使用します。

- CircleCI processes PR hooks (pull request hooks) to store PR information for the CircleCI app. If the **Only build pull requests** setting is enabled within CircleCI, CircleCI will only trigger builds when a PR is opened, or when there is a push to a branch for which there is an existing PR. これが設定されている場合でも、プロジェクトのデフォルトのブランチへのすべてのプッシュは、常にビルドされます。
- If the **Build forked pull requests** setting is enabled in CircleCI, CircleCI will trigger builds in response to PRs created from forked repos.

These settings can be found in each project's individual **Project Settings** section of the CircleCI web app.

It is possible to edit the webhooks in Bitbucket to restrict events that trigger a build. Web フックの設定を編集することで、CircleCI に送信されるフックを変更できますが、ビルドをトリガーするフックの種類は変更されません。 CircleCI will always build push hooks, and build on PR hooks (depending on settings), but if you remove push hooks from the webhook settings, CircleCI will not build.

Refer to the https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html[Atlassian Manage Webhooks document] for details.

Refer to the CircleCI documentation on <<workflows#using-contexts-and-filtering-in-your-workflows,Workflow filters>> for information on how to build tag pushes.

NOTE: **Bitbucket personal orgs:**
CircleCI expects that your personal/default organization matches your Bitbucket username. Bitbucket now supports renaming your personal workspace to differ from your username, however, this is not currently supported by CircleCI. CircleCI を使って個人ワークスペースでプロジェクトをビルドしている場合は、ワークスペースの名前がユーザー名と一致していることを確認してください。

[#permissions-overview]
== 権限の概要

CircleCI requests the following permissions from Bitbucket, as defined in the https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Scopes[Bitbucket permissions model].

**Read Permission**

- ユーザーのメールアドレスを取得する

**Write Permissions**

- ユーザーのリポジトリ リストを取得する
- ユーザー アカウントへの SSH 鍵の追加

**Admin Permissions**, needed for setting up a project

- リポジトリにデプロイ キーを追加する
- リポジトリにサービス フックを追加する

NOTE: CircleCI only asks for permissions that are absolutely necessary. However, CircleCI is constrained by the specific permissions Bitbucket chooses to supply.

If you feel strongly about reducing the number of permissions CircleCI uses, consider contacting Bitbucket to communicate your concerns.

[#connect-a-bitbucket-account]
== Connect a Bitbucket account

In the https://app.circleci.com/[CircleCI web app], select the organization you want to connect to Bitbucket and navigate to the **User Settings** by clicking on the user icon on the bottom of sidebar. Here you will be able to select Bitbucket. Once connected, you should see any existing projects populate on your dashboard, and you can choose which projects to follow.

Next you will need to set up the necessary permissions to run your projects on CircleCI.

[#deploy-keys-and-user-keys]
== Deploy keys and user keys

**What is a deploy key?**

When you add a new project, CircleCI creates a deployment key on Bitbucket for your project. A deploy key is an SSH key-pair, one public, one private.  Bitbucket stores the public key, and CircleCI stores the private key. デプロイ キーは、CircleCI に単一のリポジトリへのアクセス権を提供します。 CircleCI によるリポジトリへのプッシュを防止するには、このデプロイ キーを読み取り専用に設定します。

**What is a user key?**

A user key is user-specific an SSH key-pair. Bitbucket stores the public key, and CircleCI stores the private key. 秘密鍵を持っていると、プロジェクトへの「Git」アクセスの目的で、そのユーザーとして行動することができます。

現在、Bitbucket は、ユーザー キーを作成する API を CircleCI に提供していません。 However, it is still possible to create a user key by following the workaround in the section below.

[#create-a-bitbucket-user-key]
=== Create a Bitbucket user key

1. CircleCI アプリケーションで、プロジェクトの設定に移動します。
1. Navigate to the **SSH Keys** page and scroll down to the **User Key** section.
1. Right-click the **Add User Key** button and select the **Inspect** option to open the browser inspector.
1. In the browser inspector, select the **Network** tab, and clear the console.
1. Click **Add User Key** and confirm the user is a machine user by clicking **Confirm User** in the modal. _Please note that creating a machine user is strongly advised, though not mandatory_.
1. フィルターボックスで、checkout と入力します。 This will help you locate the `checkout-key`. Click the `checkout-key` with a 201 status, then select the **Preview** tab. and copy the `public_key` (without the quotes) to your clipboard.
1. Add the key to Bitbucket by following Bitbucket's guide on https://support.atlassian.com/bitbucket-cloud/docs/set-up-an-ssh-key/[setting up SSH keys].

This SSH user key will have a "PREFERRED" label. If the project also has a deploy key, the SSH user key will be used first.

[#how-are-private-keys-used]
=== How are private keys used?

When CircleCI builds your project, the private key is installed into the `.ssh` directory and SSH is subsequently configured to communicate with your version control provider. したがって、秘密鍵は以下の用途で使用されます。

- メインプロジェクトのチェックアウト
- Checking out any Bitbucket-hosted submodules
- Checking out any Bitbucket-hosted private dependencies
- Git の自動マージ、タグ付けなど

Private keys are also used to <<#enable-your-project-to-check-out-additional-private-repositories,enable your project to check out additional private repositories>>.

[#user-key-security]
=== ユーザーキーのセキュリティ

CircleCI は、紐づけたユーザーキー (SSH Keys) を第三者に公開することはありません。

The private keys of the checkout key-pairs CircleCI generates never leave the CircleCI systems (only the public key is transmitted to Bitbucket) and are safely encrypted in storage. しかし、これらはビルド コンテナにインストールされるため、CircleCI で実行されるすべてのコードによって読み取ることができます。 同様に、SSH 鍵を使用できる開発者は、この鍵に直接アクセスできます。

SSH 鍵は信頼するユーザーとのみ共有してください。 Bitbucket collaborators on projects employing user keys can access your repositories, therefore, only entrust a user key to someone with whom you would entrust your source code.

[#user-key-access-related-error-messages]
=== ユーザーキー アクセスに関するエラー メッセージ

ユーザーキーを追加する際に表示されがちなエラーを挙げています。

**Python**: During the `pip install` step:

```
ERROR: Repository not found.
```

**Ruby**: During the `bundle install` step:

```
Permission denied (publickey).
```

[#add-a-circleci-config-file]
== .circleci/config.yml ファイルの追加

After the necessary permissions have been set up, the next step is adding a `.circleci/config.yml` file to the projects you would like to use with CircleCI. Add a `.circleci` directory to a repository you want to connect to CircleCI. Inside that directory, add a `config.yml` file.

After you create and commit a `.circleci/config.yml` file to your Bitbucket repository, CircleCI immediately checks your code out and runs your first job along with any configured tests.

CircleCI runs your tests on a clean container every time so that your tests are fresh each time you push code, and so that your code is never accessible to other users. Watch your tests update in real-time on https://circleci.com/dashboard[your dashboard]. You can also get status updates through email notifications, or look for the status badges that appear on Bitbucket. Integrated statuses also appear on the pull request screen, to show that all tests have passed.

See the <<config-intro#,Configuration Tutorial>> page for a configuration walkthrough.

[#enable-your-project-to-check-out-additional-private-repositories]
== プロジェクトで追加のプライベートリポジトリのチェックアウトを有効にする

If your testing process refers to multiple repositories, CircleCI will need a Bitbucket user key in addition to the deploy key because each deploy key is valid for only _one_ repository while a Bitbucket user key has access to _all_ of your Bitbucket repositories.

Provide CircleCI with a Bitbucket user key in your project's **Project Settings** > **SSH keys**. Scroll down the page to **User Key** and click **Authorize with Bitbucket**. CircleCI creates and associates this new SSH key with your Bitbucket user account for access to all your repositories.

[#best-practices-for-keys]
== キーのベストプラクティス

- 可能な限り、デプロイキーを使用します。
- リポジトリへのユーザーアクセスを取り消す場合、デプロイキーまたはユーザーキーを交換する必要があります。
1. After revoking the user’s access in Bitbucket, delete keys in Bitbucket.
1. CircleCI プロジェクトでキーを削除します。
1. CircleCI プロジェクトでキーを再生成します。
- 開発者自身が所有する以上のアクセス権を必要とするリポジトリのビルドに、開発者がユーザー キーを使用してアクセスできないようにします。

[#establish-the-authenticity-of-an-ssh-host]
== Establish the authenticity of an SSH host

When using SSH keys to checkout repositories, it may be necessary to add the fingerprints for bitbucket to a "known hosts" file (`~/.ssh/known_hosts`) so that the executor can verify that the host it is connecting to is authentic. The `checkout` job step does this automatically, so you will need to run the following commands if you opt to use a custom checkout command:

```shell
mkdir -p ~/.ssh

echo 'bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
' >> ~/.ssh/known_hosts
```

SSH keys for servers can be fetched by running `ssh-keyscan <host>`, then adding the key that is prefixed with `ssh-rsa` to the `known_hosts` file of your job. たとえば、以下のようになります。

```shell
➜  ~ ssh-keyscan bitbucket.com
# bitbucket.com:22 SSH-2.0-babeld-2e9d163d
bitbucket.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# bitbucket.com:22 SSH-2.0-babeld-2e9d163d
# bitbucket.com:22 SSH-2.0-babeld-2e9d163d
➜  ~ ✗
```

以下のコマンドを実行すると、キーを known_hosts に追加できます。

```shell
ssh-keyscan bitbucket.com >> ~/.ssh/known_hosts
```

[#rename-orgs-and-repositories]
== Rename orgs and repositories

If you find you need to rename an organization or repository that you have previously hooked up to CircleCI, the best practice is to follow these steps:

1. Rename organization/repository in Bitbucket.
1. Head to the CircleCI application, using the new organization/repository name, for example, `app.circleci.com/pipelines/bitbucket/<new-org-name>/<project-name>`.
1. CircleCI のプラン、プロジェクト、各種設定が正しく引き継がれていることを確認します。
1. You are then free to create a new organization/repository with the previously-used name in Bitbucket, if desired.

NOTE: If these steps are not followed, you might lose access to your organization or repository settings, including **environment variables** and **contexts**.

[#next-steps]
== 次のステップ

- <<config-intro#,Configuration Tutorial>>
- <<hello-world#,Hello World>>