---

version:
- クラウド
---
= CircleCI コンフィグ SDK
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI コンフィグ SDK は、CircleCI コンフィグ YAML を生成するための JavaScript パッケージライブラリです。
:icons: font
:toc: macro

:toc-title:

[#overview]
== 概要

link:https://circleci-public.github.io/circleci-config-sdk-ts[CircleCI コンフィグ SDK] は、CircleCI YAML 設定ファイルを生成するための (TypeScript とも互換性のある) JavaScript パッケージライブラリです。 この SDK は次の目的で使用します。

* YAML 設定ファイルの記述を置き換える
* 静的な YAML 設定ファイルを生成する
* 設定を JavaScript パッケージとしてモジュラー化して管理する
* CircleCI の <<using-dynamic-configuration#, 動的な設定>> を促進する
* CLI ツールとの統合や、ブラウザベースの操作を実現する

For example, generating a static configuration file can be useful for CLI tools where you want to create a CircleCI configuration, or browser-based tooling, such as a link:https://github.com/CircleCI-Public/visual-config-editor/[visual config editor].

Components created with the CircleCI Config SDK can be packaged and distributed as Node packages.

[#install-the-sdk]
== SDK のインストール

Install the CircleCI Config SDK with NPM or Yarn, and include it in your project via Node.js or the browser.

NPM のインストール:

```bash
$ npm i @circleci/circleci-config-sdk
```

Yarn のインストール:

```bash
yarn add @circleci/circleci-config-sdk
```

Node.js での使用

```javascript
import CircleCI from '@circleci/circleci-config-sdk';
```

ブラウザでの使用:

```javascript
const CircleCI = require('@circleci/circleci-config-sdk');
```

Visit the SDK page to view a link:https://circleci-public.github.io/circleci-config-sdk-ts/#example[full example] of generating a CircleCI configuration.

== Contribute

The CircleCI Config SDK is open source, and contributions are welcome. Visit the link:https://github.com/CircleCI-Public/circleci-config-sdk-ts/blob/main/CONTRIBUTING.md[contributing guide] to view the guidelines and release process.