---

description: CircleCI 設定ファイルのポリシー管理機能のオープンプレビュー
contentTags:
  platform:
  - クラウド
---
= 設定ファイルのポリシーに関するリファレンス
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

NOTE: 設定ファイルのポリシー管理機能が **Scale** プランでご利用いただけるようになました。現在 **オープンプレビュー** であり、 この機能のすべての側面が変更される可能性があります。

このリファレンスのページでは、ポリシーを記述する際に役立つ _ヘルパー_ や CircleCI 固有の機能を紹介します。 これらのヘルパーを使用すると、よりクリーンで定型句の少ないポリシーを作成できます。

`circle-policy-agent` パッケージには、設定ファイルのポリシーの一般的なユースケースで使用される組み込み関数が含まれています。 `policy-service` 、 `circle-cli` 、または `circle-policy-agent` により評価されたポリシーはすべて、これらの関数にアクセスできます。 これはつまり、`circleci.config` というパッケージ名は予約されているということです。

[#circleci-rego-helpers]
== CircleCI Rego のヘルパー

[#jobs]
=== `jobs`

`jobs` は、指定された CircleCI 設定ファイル内のジョブを含む Rego オブジェクトです。 ジョブに関連付けられているポリシーで使用できます。

[#definition-jobs]
==== 定義

[source,rego]
----
jobs = []string
----

`jobs` オブジェクトの例

[source,json]
----
[
    "job-a",
    "job-b",
    "job-c"
]
----

[#usage-jobs]
==== 使用法

[source,rego]
----
package org

policy_name["example"]

import future.keywords
import data.circleci.config

jobs := config.jobs
----

[#require-jobs]
=== `require_jobs`

この機能では、コンフィグファイルにジョブ名に基づきジョブを含める必要があります。 必要なジョブのリストにある各ジョブは、設定ファイル内の少なくとも 1 つのワークフローに含まれていなければなりません。

[#definition-require-jobs]
==== 定義

[source,rego]
----
require_jobs([string])
returns { string }
----

[#usage-require-jobs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_jobs = config.require_jobs(["security-check", "vulnerability-scan"])

enable_rule["require_security_jobs"]

hard_fail["require_security_jobs"]
----

[#orbs]
=== `orbs`

`orbs` は、指定された設定ファイル内の Orb やバージョンを含んだ Rego オブジェクトです。 Orb に関連付けられているポリシーで使用できます。

[#definition-orbs]
==== 定義

[source,rego]
----
orbs[string] = string
----

`orbs` オブジェクトの例

[source,json]
----
{
    "circleci/security": "1.2.3",
    "circleci/foo": "3.2.1"
}
----

[#usage-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

my_orbs := config.orbs
----

[#require-orbs]
=== `require_orbs`

この機能では、コンフィグファイルに Orb 名に基づき Orb を含める必要があります。 Orb リストにはバージョンは含めないでください。

[#definition-require-orbs]
==== 定義

[source,rego]
----
require_orbs([string])
returns { string: string }
----

[#usage-require-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_orbs = config.require_orbs(["circleci/security", "foo/bar"])

enable_rule["require_security_orbs"]

hard_fail["require_security_orbs"]
----

[#require-orbs-version]
=== `require_orbs_version`

この機能では、ポリシーに Orb 名とバージョンに基づき Orb を含める必要があります。

[#definition-require-orbs-version]
==== 定義

[source,rego]
----
require_orbs_version([string])
returns { string: string }
----

[#usage-require-orbs-version]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_orbs_versioned = config.require_orbs_version(["circleci/security@1.2.3", "foo/bar@4.5.6"])

enable_rule["require_orbs_versioned"]

hard_fail["require_orbs_versioned"]
----

[#ban-orbs]
=== `ban_orbs`

この機能は、設定に Orb 名に基づく Orb が含まれている場合、ポリシー違反となります。 Orb リストにはバージョンは含めないでください。

[#definition-ban-orbs]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs = config.ban_orbs(["evilcorp/evil"])

enable_rule["ban_orbs"]

hard_fail["ban_orbs"]
----

[#ban-orbs-version]
=== `ban_orbs_version`

この関数は、設定に Orb 名とバージョンに基づく Orb が含まれている場合、ポリシー違反となります。

[#definition-ban-orbs-version]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs-version]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs_versioned = config.ban_orbs_version(["evilcorp/evil@1.2.3", "foo/bar@4.5.6"])

enable_rule["ban_orbs_versioned"]

hard_fail["ban_orbs_versioned"]
----

[#resource-class-by-project]
=== `resource_class_by_project`

この関数はリソースクラスからプロジェクト ID セットへのマッピングを受け入れます。 マッピングで定義されたリソースクラスは、関連付けられたプロジェクト用に予約されます。 マッピングに含まれていないリソースクラスはすべてのプロジェクトで使用できます。

[#definition-resource-class-by-project]
==== 定義

```rego
resource_class_by_project({
  "$RESOURCE_CLASS": {$PROJECT_IDS...},
  ...
})
returns { ...reasons: string }
```

[#usage-resource-class-by-project]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["example"]

check_resource_class = config.resource_class_by_project({
  "large": {"$PROJECT_UUID_A","$PROJECT_UUID_B"},
})

enable_rule["check_resource_class"]

hard_fail["check_resource_class"]
----