---

description: Open preview of config policies for CircleCI. Reference page for function helpers.
contentTags:
  platform:
  - Cloud
---
= Config policy reference
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

NOTE: The config policies feature is available on the **Scale** plan and is currently in **open preview**.

CAUTION: While the config policies feature is in **open preview**, a service failure will result in build configurations **not** being evaluated against policies. This should be taken into consideration before using config policies for compliance purposes.

このリファレンスのページでは、ポリシーを記述する際に役立つ _ヘルパー_ や CircleCI 固有の関数を紹介します。 これらのヘルパーを使用すると、よりクリーンで定型句の少ないポリシーを作成できます。

`circle-policy-agent` パッケージには、設定ファイルのポリシーの一般的なユースケースで使用される組み込み関数が含まれています。 `policy-service` 、 `circle-cli` 、または `circle-policy-agent` により評価されたポリシーはすべて、これらの関数にアクセスできます。 これはつまり、`circleci.config` というパッケージ名は予約されているということです。

[#circleci-rego-helpers]
== CircleCI Rego のヘルパー

[#orbs]
=== `orbs`

`orbs` は、指定された設定ファイル内の Orb やバージョンを含んだ Rego オブジェクトです。 Orb に関連付けられているポリシーで使用できます。

[#definition-orbs]
==== 定義

[source,rego]
----
orbs[string] = string
----

`orbs` オブジェクトの例

[source,json]
----
{
    "circleci/security": "1.2.3",
    "circleci/foo": "3.2.1"
}
----

[#usage-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

my_orbs := config.orbs
----

[#ban-orbs]
=== `ban_orbs`

この関数を使用する場合、設定ファイルに Orb 名に基づく Orb が含まれていると、ポリシー違反になります。 Orb リストにはバージョンは含めないでください。

[#definition-ban-orbs]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs = config.ban_orbs(["evilcorp/evil"])

enable_rule["ban_orbs"]

hard_fail["ban_orbs"]
----

[#ban-orbs-version]
=== `ban_orbs_version`

この関数を使用する場合、設定に Orb 名とバージョンに基づく Orb が含まれていると、ポリシー違反になります。

[#definition-ban-orbs-version]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs-version]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs_versioned = config.ban_orbs_version(["evilcorp/evil@1.2.3", "foo/bar@4.5.6"])

enable_rule["ban_orbs_versioned"]

hard_fail["ban_orbs_versioned"]
----

[#resource-class-by-project]
=== `resource_class_by_project`

この関数はリソースクラスからプロジェクト ID セットへのマッピングを受け入れます。 マッピングで定義されたリソースクラスは、関連付けられたプロジェクト用に予約されます。 マッピングに含まれていないリソースクラスはすべてのプロジェクトで使用できます。

[#definition-resource-class-by-project]
==== 定義

```rego
resource_class_by_project({
  "$RESOURCE_CLASS": {$PROJECT_IDS...},
  ...
})
returns { ...reasons: string }
```

[#usage-resource-class-by-project]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["example"]

check_resource_class = config.resource_class_by_project({
  "large": {"$PROJECT_UUID_A","$PROJECT_UUID_B"},
})

enable_rule["check_resource_class"]

hard_fail["check_resource_class"]
----

[#contexts-allowed-by-project-ids]
=== `contexts_allowed_by_project_ids`

This function accepts project ids (`PROJECTS`) and
context names (`ALLOWED_CONTEXTS`) as one of the following types:

* 文字列
* set of strings
* array of strings

It prevents the usage of **any** context **not in** `ALLOWED_CONTEXTS` for **all** projects that are **in** `PROJECTS`.

[#definition-contexts-allowed-by-project-ids]
==== 定義

[source,rego]
----
contexts_allowed_by_project_ids(
  PROJECTS: string | Array<string> | Set<string>
  ALLOWED_CONTEXTS: string | Array<string> | Set<string>
)
returns reason <type string>
----

[#usage-contexts-allowed-by-project-ids]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["a_unique_policy_name"]

rule_contexts_allowed_by_project_ids = config.contexts_allowed_by_project_ids(
  ["${PROJECT_1_UUID}","${PROJECT_2_UUID}"],
  ["${ALLOWED_CONTEXT_NAME_1}","${ALLOWED_CONTEXT_NAME_2}"]
)

enable_rule["rule_contexts_allowed_by_project_ids"]

hard_fail["rule_contexts_allowed_by_project_ids"]
----

[#contexts-blocked-by-project-ids]
=== `contexts_blocked_by_project_ids`

This function accepts project IDs (`PROJECTS`) and
context names (`BLOCKED_CONTEXTS`) as one of the following types:

* 文字列
* set of strings
* array of strings

It blocks the usage of **any** context **in** `BLOCKED_CONTEXTS` for **all** projects **in** `PROJECTS`.

[#definition-contexts-blocked-by-project-ids]
==== 定義

[source,rego]
----
contexts_blocked_by_project_ids(
  PROJECTS: string | Array<string> | Set<string>
  BLOCKED_CONTEXTS: string | Array<string> | Set<string>
)
returns reason: string
----

[#usage-contexts-blocked-by-project-ids]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["a_unique_policy_name"]

rule_contexts_blocked_by_project_ids = config.contexts_blocked_by_project_ids(
  ["${PROJECT_1_UUID}","${PROJECT_2_UUID}"],
  ["${BLOCKED_CONTEXT_1}","${BLOCKED_CONTEXT_2}"]
)

enable_rule["rule_contexts_blocked_by_project_ids"]

hard_fail["rule_contexts_blocked_by_project_ids"]
----

[#contexts-reserved-by-project-ids]
=== `contexts_reserved_by_project_ids`

This function accepts project ids (`PROJECTS`) and
context names (`RESERVED_CONTEXTS`) as one of the following types:

* 文字列
* set of strings
* array-of-strings

It blocks the usage of **any** context **in** `RESERVED_CONTEXTS` for **all** projects **not in** `PROJECTS`.

[#definition-contexts-reserved-by-project-ids]
==== 定義

[source,rego]
----
contexts_reserved_by_project_ids(
  PROJECTS: string | Array<string> | Set<string>
  RESERVED_CONTEXTS: string | Array<string> | Set<string>
)
returns reason: string
----

[#usage-contexts-reserved-by-project-ids]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["a_unique_policy_name"]

rule_contexts_reserved_by_project_ids = config.contexts_reserved_by_project_ids(
  ["${PROJECT_1_UUID}","${PROJECT_2_UUID}"],
  ["${RESERVED_CONTEXT_1}","${RESERVED_CONTEXT_2}"]
)

enable_rule["rule_contexts_reserved_by_project_ids"]

hard_fail["rule_contexts_reserved_by_project_ids"]
----

[#contexts-reserved-by-branches]
=== `contexts_reserved_by_branches`

This function accepts VCS branch names (`BRANCHES`) and
context names (`RESERVED_CONTEXTS`) as one of the following types:

* 文字列
* set-of-strings
* array-of-strings

Branch names **not in** `BRANCHES` are **not** allowed to use the contexts **in** `RESERVED_CONTEXTS`, however, other contexts may be used.

[#definition-contexts-reserved-by-branches]
==== 定義

[source,rego]
----
contexts_reserved_by_branches(
  BRANCHES: string | Array<string> | Set<string>
  CONTEXT_LIST: string | Array<string> | Set<string>
)
returns reason: string
----

[#usage-contexts-reserved-by-branches]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["a_unique_policy_name"]

rule_contexts_reserved_by_branches = config.contexts_reserved_by_branches(
   ["${BRANCH_1}, "${BRANCH_2}", "${BRANCH_3}"]",
  ["${RESERVED_CONTEXT_1}","${RESERVED_CONTEXT_2}"]
)

enable_rule["rule_contexts_reserved_by_branches"]

hard_fail["rule_contexts_reserved_by_branches"]
----