---

description: CircleCI 設定ファイルのポリシー管理機能のオープンプレビュー
contentTags:
  platform:
  - クラウド
---
= 設定ファイルのポリシーのリファレンス
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

NOTE: 設定ファイルのポリシー管理機能が **Scale** プランでご利用いただけるようになました。現在 **オープンプレビュー** であり、 この機能のすべての側面が変更される可能性があります。

このリファレンスのページでは、ポリシーを記述する際に役立つ _ヘルパー_ や CircleCI 固有の機能を紹介します。 これらのヘルパーにより、よりクリーンで定型句の少ないポリシーが作成できます。

`circle-policy-agent` パッケージには、設定ファイルのポリシーの一般的なユースケースで使用される組み込み関数が含まれています。
 All policies evaluated by the `policy-service`, the `circle-cli`, or the `circle-policy-agent`
will be able to access these functions. This also means the package name `circleci.config` is
reserved.

[#circleci-rego-helpers]
== CircleCI rego helpers

[#jobs]
=== `jobs`

`jobs` is a Rego object containing jobs that are present in the given CircleCI config file. It
can be utilized by policies related to jobs.

[#definition-jobs]
==== 定義

[source,rego]
----
jobs = []string
----

Example `jobs` object:

[source,json]
----
[
    "job-a",
    "job-b",
    "job-c"
]
----

[#usage-jobs]
==== 使用法

[source,rego]
----
package org

policy_name["example"]

import future.keywords
import data.circleci.config

jobs := config.jobs
----

[#require-jobs]
=== `require_jobs`

This function requires a config to contain jobs based on the job names. Each job in the list of
required jobs must be in at least one workflow within the config.

[#definition-require-jobs]
==== 定義

[source,rego]
----
require_jobs([string])
returns { string }
----

[#usage-require-jobs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_jobs = config.require_jobs(["security-check", "vulnerability-scan"])

enable_rule["require_security_jobs"]

hard_fail["require_security_jobs"]
----

[#orbs]
=== `orb`

`orbs` is a Rego object containing orbs and versions present in the given config file. It
can be utilized by policies related to orbs.

[#definition-orbs]
==== 定義

[source,rego]
----
orbs[string] = string
----

Example `orbs` object:

[source,json]
----
{
    "circleci/security": "1.2.3",
    "circleci/foo": "3.2.1"
}
----

[#usage-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

my_orbs := config.orbs
----

[#require-orbs]
=== `require_orbs`

This function requires a config to contain orbs based on the orb names. Versions should not
be included in the provided list of orbs.

[#definition-require-orbs]
==== 定義

[source,rego]
----
require_orbs([string])
returns { string: string }
----

[#usage-require-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_orbs = config.require_orbs(["circleci/security", "foo/bar"])

enable_rule["require_security_orbs"]

hard_fail["require_security_orbs"]
----

[#require-orbs-version]
=== `require_orbs_version`

This function requires a policy to contain orbs based on the orb name and version.

[#definition-require-orbs-version]
==== 定義

[source,rego]
----
require_orbs_version([string])
returns { string: string }
----

[#usage-require-orbs-version]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_orbs_versioned = config.require_orbs_version(["circleci/security@1.2.3", "foo/bar@4.5.6"])

enable_rule["require_orbs_versioned"]

hard_fail["require_orbs_versioned"]
----

[#ban-orbs]
=== `ban_orbs`

This function violates a policy if a config includes orbs based on the orb name. Versions should not
be included in the provided list of orbs.

[#definition-ban-orbs]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs = config.ban_orbs(["evilcorp/evil"])

enable_rule["ban_orbs"]

hard_fail["ban_orbs"]
----

[#ban-orbs-version]
=== `ban_orbs_version`

This function violates a policy if a config includes orbs based on the orb name and version.

[#definition-ban-orbs-version]
==== 定義

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs-version]
==== 使用法

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs_versioned = config.ban_orbs_version(["evilcorp/evil@1.2.3", "foo/bar@4.5.6"])

enable_rule["ban_orbs_versioned"]

hard_fail["ban_orbs_versioned"]
----

[#resource-class-by-project]
=== `resource_class_by_project`

This function accepts a resource class to project IDs set mapping. The resource classes defined in the
mapping will be reserved for its associated projects. Resource classes not included in the mapping will
still be available for use by any project.

[#definition-resource-class-by-project]
==== 定義

```rego
resource_class_by_project({
  "$RESOURCE_CLASS": {$PROJECT_IDS...},
  ...
})
returns { ...reasons: string }
```

[#usage-resource-class-by-project]
==== 使用法

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["example"]

check_resource_class = config.resource_class_by_project({
  "large": {"$PROJECT_UUID_A","$PROJECT_UUID_B"},
})

enable_rule["check_resource_class"]

hard_fail["check_resource_class"]
----