---

contentTags:
  platform:
  - クラウド
---
= コンテナランナーのインストール (Kubernetes)
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI コンテナランナーのインストール手順
:icons: font
:experimental:
:container:

CircleCI のコンテナランナーをインストールする方法についてこのドキュメントでわかりやすく説明します。

// {% include snippets/runner-platform-prerequisites.adoc %}

[#prerequisites]
== Orb 開発キット

{% include snippets/runner/ja/container-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== 前提条件

{% include snippets/runner/ja/container-runner-prereq.adoc %}

[#create-namespace-and-resource-class]
== セルフホストランナーの利用条件 ネームスペースとリソースクラスの作成

[.tab.container-runner.Web_app_installation]
--
{% include snippets/ja/runner/install-with-web-app-steps.adoc %}
--

[.tab.container-runner.CLI_installation]
--
{% include snippets/ja/runner/install-with-cli-steps.adoc %}
--

[#container-runner-installation]
== 1. ネームスペースとリソースクラスの作成

. 以下のコマンドを実行して、コンテナランナー Helm のレポジトリを追加します：
+
[source,shell]
----
helm repo add container-agent https://packagecloud.io/circleci/container-agent/helm
----
. 次に以下を実行します：
+
[source,shell]
----
helm repo update
----
. 次に、以下のコマンドを実行し、`circleci` Kubernetes namespaceを作成します：
+
[source,shell]
----
kubectl create namespace circleci
----
. `values.yaml` ファイルという以下を含むファイルを作成します。
+
```yaml
agent:
  resourceClasses:
    namespace/my-rc:
      token: <resource_class_token>
```
. 最後に、以下のコマンドを実行します：
+
[source,shell]
----
helm install container-agent container-agent/container-agent -n circleci -f values.yaml
----

[#container-runner-configuration-example]
== 2.

クラスタにコンテナランナーをインストールしたら、Docker Executor を使ってインストールを検証する CircleCI ジョブを作成し、トリガーします。 コンテナランナーを使って実行する特定のジョブについて、以下のフィールドを設定する必要があります。

* `image:`
* `resource_class: <namespace>/<resource-class>`

以下は、ジョブ設定のシンプルなコード例です (`cimg/base:2021.11` は、よく使用される CircleCI の Docker イメージです)。

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: <namespace>/<resource-class>
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
```

CAUTION: <<building-docker-images#,setup_remote_docker>> を使用する既存のジョブは **使用しないでください** (詳細は以下の <<container-runner#building-container-images,コンテナイメージのビルド>> のセクションを参照)。

[#troubleshooting]
== コンテナランナーの設定例

クラスタにコンテナランナーをインストールしたら、Docker Executor を使ってインストールを検証する CircleCI ジョブを作成し、トリガーします。

[#additional-resources]
== トラブルシューティング

- xref:container-runner.adoc[コンテナランナーのリファレンスガイド]
- xref:runner-concepts.adoc[セルフホストランナーのコンセプト]
- xref:runner-faqs.adoc[セルフホストランナーについてよく寄せられるご質問]