---

contentTags:
  platform:
  - クラウド
---
= コンテナランナーのインストール (Kubernetes)
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI コンテナランナーのインストール手順
:icons: font
:toc: macro

:toc-title:
:container:

{% include snippets/ja/runner-platform-prerequisites.adoc %}

// {% include snippets/runner-platform-prerequisites.adoc %}

[#prerequisites]
== コンテナランナーの設定例

クラスタにコンテナランナーをインストールしたら、Docker Executor を使ってインストールを検証する CircleCI ジョブを作成し、トリガーします。

[#self-hosted-runner-terms-agreement]
== トラブルシューティング

セルフホストランナーのトラブルシューティングガイドの <<troubleshoot-self-hosted-runner#troubleshoot-container-runner,コンテナランナーのトラブルシューティングのセクション>> を参照してください。

[#create-namespace-and-resource-class]
== 関連リソース Create namespace and resource class

[.tab.container-runner.Web_app_installation]
--
{% include snippets/runner/install-with-web-app-steps.adoc %}
--

[.tab.container-runner.CLI_installation]
--
{% include snippets/runner/install-with-cli-steps.adoc %}
--

[#container-runner-installation]
== 2. Container runner installation

. Add the container runner Helm repo by running the following command:
+
[source,shell]
----
helm repo add container-agent https://packagecloud.io/circleci/container-agent/helm
----
. Next, run the following:
+
[source,shell]
----
helm repo update
----
. Then, run the following command to create the `circleci` Kubernetes namespace:
+
[source,shell]
----
kubectl create namespace circleci
----
. `values.yaml` ファイルという以下を含むファイルを作成します。
+
```yaml
agent:
  resourceClasses:
    namespace/my-rc:
      token: <resource_class_token>
```
. Finally, run the following command:
+
[source,shell]
----
helm install container-agent container-agent/container-agent -n circleci -f values.yaml
----

[#container-runner-configuration-example]
== コンテナランナーの設定例

クラスタにコンテナランナーをインストールしたら、Docker Executor を使ってインストールを検証する CircleCI ジョブを作成し、トリガーします。 The fields you must set for a specific job to run using your container runners are:

* `image:`
* `resource_class: <namespace>/<resource-class>`

Simple example of how you could set up a job (`cimg/base:2021.11` is a commonly used CircleCI Docker image):

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: <namespace>/<resource-class>
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
```

CAUTION: <<building-docker-images#,setup_remote_docker>> を使用する既存のジョブは **使用しないでください** (詳細は以下の <<container-runner#building-container-images,コンテナイメージのビルド>> のセクションを参照)。

[#troubleshooting]
== トラブルシューティング

セルフホストランナーのトラブルシューティングガイドの <<troubleshoot-self-hosted-runner#troubleshoot-container-runner,コンテナランナーのトラブルシューティングのセクション>> を参照してください。

[#additional-resources]
== 関連リソース

- xref:container-runner.adoc[コンテナランナーのリファレンスガイド]
- xref:runner-concepts.adoc[セルフホストランナーのコンセプト]
- xref:runner-faqs.adoc[セルフホストランナーについてよく寄せられるご質問]