---

description: CircleCI プロジェクト設定における設定ファイルのポリシー管理
contentTags:
  platform:
  - Cloud
---
= Create and manage config policies
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

NOTE: 設定ファイルのポリシー管理機能が **Scale** プランでご利用いただけるようになりました。現在 **オープンプレビュー** であり、 すべての側面において今後変更される可能性があります。

CAUTION: 設定ファイルのポリシー管理機能がオープンプレビュー段階の間は、コンプライアンスの用途には **使用しないでください**。 **オープンプレビュー** の間は本機能を使用できない期間が発生する可能性があります。その間、構築した設定ファイルのポリシーに対する評価が **行われない** 場合があります。

Follow the how-to guides on this page to learn how to perform various config policy management processes.

[#config-policy-management-enablement]
== 組織のポリシー評価を有効・無効にする

組織のパイプライン設定にポリシーの評価を適用するかどうかは、 `--enabled` フラグを使って制御できます。

* To **enable** policy evaluation run the following command. This sets `--enabled` to `true`, which means project configurations **will** be evaluated against your organization's policies when pipelines are triggered.:
+
[source,shell]
----
circleci policy settings --enabled=true --owner-id <your-organization-ID>
----
+
以下のように出力されます。
+
[source,shell]
----
{
  "enabled": true
}
----
* To **disable** policy evaluation run the following command. This sets `--enabled` to `false`, which means project configurations **will not** be evaluated against your organization's policies when pipelines are triggered.:
+
[source,shell]
----
circleci policy settings --enabled=false --owner-id <your-organization-ID>
----
+
以下のように出力されます。
+
[source,shell]
----
{
  "enabled": false
}
----

{% include snippets/ja/find-organization-id.adoc %}

[#create-a-policy]
== Create a policy

CAUTION: 設定ファイルのポリシー管理で CLI を使用する前に、ご使用の CLI がトークンで認証されており、更新されていることをご確認ください。 詳細については、 link:/docs/local-cli[ローカルの CLI のインストール] のページをご覧ください。

以下の手順に従って、CircleCI 設定ファイルの `version` が `2.1` 以上であることを確認するポリシーを作成します。

. 組織の設定ファイルのポリシー管理機能を有効にします。
+
[source,shell]
----
circleci policy settings --enabled=true --owner-id <your-organization-ID>
----
+
以下のように出力されます。
+
[source,shell]
----
{
  "enabled": true
}
----
. Create an empty directory to store your policies. 例えば以下のようになります。
+
[source,shell]
----
mkdir ./config-policies
----
. Inside your new directory create a Rego file for your new policy. Call it: `version.rego`.
. 以下の内容を `version.rego` に追加します。
+
[source,rego]
----
# All policies start with the org package definition
package org

policy_name["example"]

# signal to circleci that check_version is enabled and must be included when making a decision
enable_rule["check_version"]

# signal to circleci that check_version is a hard_failure condition and that builds should be
# stopped if this rule is not satisfied.
hard_fail["check_version"]

# define check version
check_version = reason {
    not input.version # check the case where version is not in the input
    reason := "version must be defined"
} {
    not is_number(input.version) # check that version is number
    reason := "version must be a number"
} {
    not input.version >= 2.1 # check that version is at least 2.1
    reason := sprintf("version must be at least 2.1 but got %v", [input.version])
}
----
. 組織にポリシーをアップロードします。
+
[source,shell]
----
circleci policy push ./config-policies --owner-id <your-organization-ID>
----
+
これで、組織内でパイプラインがトリガーされる際、このポリシーに対してプロジェクトの `.circleci/config.yml` が検証されるようになりました。

[#update-a-policy]
=== ポリシーの更新

既存のポリシーに変更を加える方法を説明するために、上記のポリシーの作成中に間違ってしまったとします。 You realize that some project configurations in your organization are using CircleCI config version `2.0`, and you want your policy to reflect this.

. Change the last check of your rule definition in your `version.rego` file to:
+
[source,rego]
----
{
    not input.version >= 2.0 # check that version is at least 2.0
    reason := sprintf("version must be at least 2.0 but got %v", [input.version])
}
----
. この更新されたポリシーファイルを含むポリシーディレクトリを CLI を使ってプッシュします (差分を検証し、プロンプトが表示されたら yes を選択します)。
+
[source,shell]
----
circleci policy push ./config-policies --owner-id <your-organization-ID>
----

[#manage-policies-with-your-vcs]
== VCS を使ったポリシーの管理

CircleCI のポリシーは、ポリシーのディレクトリを CLI を介して CircleCI にプッシュして管理します。 推奨されるポリシーディレクトリの管理方法は、組織の VCS のレポジトリにポリシーディレクトリを保存することです。 これは、CircleCI の内部でポリシーを管理する方法です。
 Pushing a policy bundle is done by triggering a CircleCI pipeline.

ポリシーのプッシュにボットアカウントを作成し、関連付けられている CircleCI パーソナル API トークンを使って認証することを推奨します。 最大限のセキュリティを確保するには、トークンを環境変数としてコンテキスト内に保存し、そのコンテキストをポリシーの管理を担当するグループに制限する必要があります 詳細については、link:/docs/contexts[コンテキストの使用] のページを参照してください。

[set-up-a-config-policy-management-ci-pipeline]
=== 設定ファイルのポリシー管理用 CI パイプラインのセットアップ

. VCS にポリシーを管理するためのレポジトリをセットアップします。
. Create a directory in your new repo for your Rego policy files, for example:
+
[source,shell]
----
mkdir ./config-policies
----
. Create a `.circleci/config.yml` file for your new policies repository, and copy and paste the config example below. このサンプルでは、`main` ブランチのコミット時に CircleCI にポリシーをプッシュし、他のすべてのブランチへのコミット時のポリシーバンドルにおける差分を表示します。
+
[NOTE]
====
The context for each job is shown as `<my-context>`. This context name is arbitrary, but it must be active and declare the following environment variables:

* `CIRCLECI_CLI_TOKEN` with the value of a personal API token to authenticate the CLI
* `ORG_ID` with the value of the organization ID
====
+
[source,yaml]
----
version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.9 # Use orb to make the `circleci-cli/default` executor available for running jobs

workflows:
  main-workflow:
    jobs:
      - diff-policy-bundle:
          context: <my-context>
          filters:
            branches:
              ignore: main # on all branches other than main
      - push-policy-bundle:
          context: <my-context>
          filters:
            branches:
              only: main # only on the main branch

jobs:
  diff-policy-bundle:
    executor: circleci-cli/default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Diff policy bundle
          command: circleci policy diff ./config --owner-id $ORG_ID # show a diff of the policy bundle

  push-policy-bundle:
    executor: circleci-cli/default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Push policy bundle
          command: circleci policy push ./config --no-prompt --owner-id $ORG_ID # push the policy bundle to CircleCI
----