---

categories: [how-to]
contentTags:
  platform:
  - クラウド
---
= クレジットの使用
:description: CircleCI クレジットベースプランシステムについて.
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI クレジットベースプランシステムについて
:icons: font
:experimental:

このドキュメントでは、 CircleCI のクレジットに関する利用可能なリソースを見つける方法について説明します。

[#overview]
== インサイト スナップショットバッジの概要

クレジットは CircleCI の Free プラン、Performance プラン、Scale プラン、Server プランで使用されます。 各プランで主要な CI/CD 機能を提供しており、一部のプランではニーズに応じたカスタマイズオプションもご利用いただけます。


チームに最適なプランを検討する際は、以下のような要素を考慮する必要があります。

- チームのユーザー数
- 必要なサポートのレベル (無料の Community サポート、Standard サポート、Premium サポート)
- 複数のマシンタイプやリソースクラスの利用の要否
- セルフホストランナー数の制限の有無

詳細は、xref:plan-overview#[料金プラン]の概要のページをご覧ください。各プランでご利用いただける機能の詳細については、各プランのページをご覧ください。

- xref:plan-free#[Free プラン]
- xref:plan-performance#[Performance プラン]
- xref:plan-scale#[Scale プラン]
- xref:plan-server#[Server プラン]

マシンタイプ別、リソースクラス別の消費クレジットについては、link:https://circleci.com/ja/pricing/[料金プラン] のページもご確認ください。

[#managing-credit-usage]
== 概要

クレジットは CircleCI の Free プラン、Performance プラン、Scale プラン、Server プランで使用されます。 各プランで主要な CI/CD 機能を提供しており、一部のプランではニーズに応じたカスタマイズオプションもご利用いただけます。


[#open-source-credit-usage]
== クレジット使用量の管理

また、ネットワークとストレージの使用状況を適切に管理することで、毎月のクレジット使用量を削減することができます。 ネットワークとストレージ使用状況の管理の詳細については、 xref:persist-data#[データの永続化]のページを参照してください。  使用できるオープンソースクレジットの量や制限は、UI 画面上では確認できません。

Free プランで macOS でビルドを行っている組織にも、毎月 25,000 クレジットが無料で付与され、macOS オープンソース プロジェクトのビルドに利用できます。 ご希望の方は、mailto:billing@circleci.com[billing@circleci.com]までお問い合わせください。

[#troubleshooting-job-is-queued]
== オープンソースプロジェクトでのクレジット使用

Free プランをご利用の組織には、毎月 400,000 クレジットが無料で付与され、Linux コンピューティングでのオープンソースプロジェクトのビルドに利用できます。 この特典を受けるには、Free プランを利用し、リポジトリをパブリックにする必要があります。 使用できるオープンソースクレジットの量や制限は、UI 画面上では確認できません。

Free プランで macOS でビルドを行っている組織にも、毎月 25,000 クレジットが無料で付与され、macOS オープンソース プロジェクトのビルドに利用できます。 ご希望の方は、mailto:billing@circleci.com[billing@circleci.com]までお問い合わせください。

[#questions-and-comments]
== ジョブが「Queued」または「Preparing」の場合、料金は請求されますか？

いいえ。 ジョブが "queued (キューイング中)"と通知された場合、ジョブがプランや同時実行の制限により待機状態になっていることを意味しています。

[#billing-faqs]
== ご意見・ご質問

include::../_includes/snippets/faq/ja/billing-faq-snip.adoc[]