---

contentTags:
  platform:
  - クラウド
---
= macOS の専有ホスト
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI's dedicated host resource class offering for macOS users.
:icons: font
:toc: macro
:toc-title:

この専有ホストリソースクラスは、Xcode IDE を使って iOS、iPadOS、macOS、WatchOS 、および tvOS アプリケーションの開発、ビルド、テスト、署名を行なうお客様にご利用いただけます。 この専有リソースにより、隔離された環境が提供され、セキュリティーが強化されます。

このリソースクラスの貸し出しは 24 時間以上で、 Intel ベースの Mac ハードウェア上で動作します。

専有ホストリソースの識別子は、`macos.x86.metal.gen1` で、他の macOS リソースクラスと同じ Xcode イメージをサポートしています (Xcode 10.3 を除く)。 すべてのバージョンのリストは 「iOS のテスト」の https://circleci.com/docs/ja/using-macos/#supported-xcode-versions[サポートされている Xcode のバージョンのセクション] をご覧ください。

[#pricing-and-specs]
== 料金と仕様

[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
|クラス
|vCPU
|RAM
|トータルストレージ
|料金

|`macos.x86.metal.gen1`
|12
|32GB
|200 GB
|1 分あたり 100 クレジット (24 時間〜)
|===

デフォルトで、各アカウントに最大１つの専有ホストが付与されています。 最大数を増やしたい場合は https://support.circleci.com/hc/ja/requests/new[CircleCI サポートチーム] 、またはアカウント担当者にご連絡ください。

専有ホストが付与されると、最低 24 時間〜そのホストに排他的にアクセスすることができます。 ジョブが実行されたときに専有ホストがすでに使用されている場合、専有ホストの制限を増やしていない限り、ジョブはホストが使用可能になるまでキューイングします。

[#support-xcode-versions]
== サポートされている Xcode のバージョン

include::../_includes/ja/snippets/xcode-metal.adoc[]

[#known-limitations]
== 既知の制限

- 現在このリソースクラスでは、テストの分割や並列実行はサポートしていません。
- このホストはジョブ間で削除され、それには 現在 5 分から 45 分かかります。 このスクラビングプロセスの影響を最小限に抑えるために、複数の専有ホストを同時に実行することをお勧めします。 制限値を上げるには、サポートチームまたはアカウント担当者にご連絡ください。

[#example-configuration-file-using-macos-dedicated-host-resources]
== macOS 専有ホストリソースを使ったサンプル設定ファイル

```yaml
# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1 # indicate your selected version of Xcode
    resource_class: macos.x86.metal.gen1 # dedicated host, with 24-hour billing
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
```

[#dedicated-hosts-macos-faqs]
== FAQ

include::../_includes/snippets/faq/ja/dedicated-hosts-macos-faq-snip.adoc[]