---

version:
- クラウド
---
= macOS の専有ホスト
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI's dedicated host resource class offering for macOS users.
:icons: font
:toc: macro
:toc-title:

The dedicated host resource class is available for those developing, building, testing, and signing iOS, iPadOS, macOS, WatchOS, and tvOS applications using the Xcode IDE. この専有リソースにより、隔離された環境が提供され、セキュリティーが強化されます。

このリソースクラスの貸し出しは 24 時間以上で、 Intel ベースの Mac ハードウェア上で動作します。

専有ホストリソースの識別子は、`macos.x86.metal.gen1` で、他の macOS リソースクラスと同じ Xcode イメージをサポートしています (Xcode 10.3 を除く)。 Refer to the https://circleci.com/docs/2.0/using-macos/#supported-xcode-versions[Supported Xcode versions section] of the Testing iOS page for the full list of versions.

[#pricing-and-specs]
== 料金と仕様

[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
|クラス
|vCPU
|RAM
|トータルストレージ
|料金

|`macos.x86.metal.gen1`
|12
|32GB
|200 GB
|1 分あたり 100 クレジット (24 時間〜)
|===

デフォルトで、各アカウントに最大１つの専有ホストが付与されています。 最大数を増やしたい場合は https://support.circleci.com/hc/ja/requests/new[CircleCI サポートチーム] 、またはアカウント担当者にご連絡ください。

専有ホストが付与されると、最低 24 時間〜そのホストに排他的にアクセスすることができます。 ジョブが実行されたときに専有ホストがすでに使用されている場合、専有ホストの制限を増やしていない限り、ジョブはホストが使用可能になるまでキューイングします。

[#known-limitations]
== 既知の制限

- 現在このリソースクラスでは、テストの分割や並列実行はサポートしていません。
- このホストはジョブ間で削除され、それには 現在 5 分から 45 分かかります。 このスクラビングプロセスの影響を最小限に抑えるために、複数の専有ホストを同時に実行することをお勧めします。 制限値を上げるには、サポートチームまたはアカウント担当者にご連絡ください。

[#example-configuration-file-using-macos-dedicated-host-resources]
== macOS 専有ホストリソースを使ったサンプル設定ファイル

```yaml
# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.5.1 # indicate our selected version of Xcode
    resource_class: macos.x86.metal.gen1 # dedicated host, with 24-hour billing
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
```

[#faq]
== よくあるご質問

質問: 専有ホストは CircleCI の他の macOS リソースとはどう違いますか？

回答: 他のリソースは隔離された仮想マシン上で実行されます。つまり複数のユーザーが同じホストで仮想マシンを使用できるということです。 専有ホストでは、ホスト全体に排他的なアクセスが可能で、他のユーザーとリソースを共有することはありません。

質問: なぜ最低 24 時間〜なのですか？

回答: Apple は、2020 年 11 月に Big Sur のリリースに伴い「 https://www.apple.com/legal/sla/docs/macOSBigSur.pdf[updated end-user license agreement (EULA)]」をリリースしました。 

NOTE: 本サービスを利用することにより、お客様は、Apple ソフトウェア使用許諾契約の条項および Apple ソフトウェアにプレインストールされているソフトウェア (Apple の Xcode 開発者向けソフトウェア、およびその他の Apple または他社ソフトウェアを含むがこれに限定されない) に適用される条件を確認し、これに拘束されることに同意したことを表明し、保証するものとします