---

description: "This is document provides examples of deploying to Azure Container Registry"
version:
- Cloud
- Server v3.x
- Server v2.x
---
= Deploy to Azure Container Registry
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

This page describes a simple deployment to the Azure Container Registry (ACR) using the CircleCI ACR orb and `version 2.1` configuration.

{% include snippets/ja/env-var-or-context.adoc %}

For detailed information about the Azure ACR orb, including all options, refer to the link:https://circleci.com/developer/orbs/orb/circleci/azure-acr[CircleCI ACR Orb Reference] page.

1. ユーザーまたはサービスプリンシパルのログインが必要かどうかにかかわらず、CircleCI にユーザー名、パスワード、およびテナントの環境変数を指定する必要があります。 For user logins use env var names as follows: `AZURE_USERNAME`, `AZURE_PASSWORD` and `AZURE_TENANT`. For service principal logins use: `AZURE_SP`, `AZURE_SP_PASSWORD` and `AZURE_SP_TENANT`.
1. Use the orb's `build-and-push-image` job to build your image and deploy it to ACR. Note the use of workflows to deploy only if the current branch is `main`.
+
```yaml
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

orbs:
    azure-acr: circleci/azure-acr@x.y.z # Use the Azure ACR orb in your config

workflows:
    build-deploy:
    jobs:
        - azure/build-and-push-image:
            dockerfile: <name-of-your-dockerfile> # defaults to `Dockerfile`
            path: <path-to-your-dockerfile> # Defaults to working directory
            login-server-name: <your-login-server-name> # e.g. {yourregistryname}.azure.io
            registry-name: <your-ACR-registry-name>
            repo: <URI-to-your-login-server-name>
            filters:
            branches:
                only: main # Only deploys when the commit is on the Main branch
```

If pushing to your repository is required, see the "Deployment Keys" section of the <<github-integration#user-keys-and-deploy-keys,GitHub>> or <<bitbucket-integration#deploy-keys-and-user-keys,Bitbucket>> instructions. 次に、production ブランチを使用するように Azure Web App を設定します。