---

description: This document provides examples of publishing to the NPM registry.
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Publish to NPM registry
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

In this how-to guide, you will learn how to configure CircleCI to publish to the NPM registry.

[#introduction]
== はじめに

パッケージを npm レジストリにパブリッシュするように CircleCI をセットアップすると、プロジェクトのコラボレーターは、一貫性のある予測可能な方法で新しいパッケージのバージョンを簡単にリリースできるようになります。

[#obtain-the-npm-authToken]
== 1.  Obtain the npm authToken

パッケージのパブリッシュに使用するアカウント用に npm authToken を取得します。 そのためには、まず npm にログインします (`npm login`)。 これで、authToken が `~/.npmrc` ファイルに保存されます。 以下の行を探します。

```shell
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```

この場合、authToken は `00000000-0000-0000-0000-000000000000` です。

[#set-npm-token]
== 2.  Set NPM token

Go to your xref:environment-variables#setting-environment-variables-for-all-commands-without-adding-them-to-git[project settings], and set the `NPM_TOKEN` variable to the obtained authToken.

[#configure-circleci]
== 3.  CircleCI を構成する

authToken を `~/.npmrc` に追加するように CircleCI を構成し、バージョンが指定されたタグにのみ `npm publish` を実行します。

```yaml
version: 2.1

jobs:
    publish:
    docker:
        - image: <docker-image-name-tag>
            auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
        - checkout
        - run:
            name: Publish to NPM
            command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
    tagged-build:
    jobs:
        - publish:
            filters:
            tags:
                only: /v[0-9]+(\.[0-9]+)*/
```

[#create-new-version]
== 4. Create a new version

新しいバージョンを npm にパブリッシュするには、以下に示すように `npm version` を実行して新しいバージョンを作成します。

```shell
npm version 10.0.1
```

これで、`package.json` ファイルが更新され、タグ付きの Git コミットが作成されます。 次に、タグ付きのコミットをプッシュします。

```shell
git push --follow-tags
```

[#publish]
== 5. Publish

テストが完了すると、パッケージが npm に自動的にパブリッシュされます。