---

categories: [platforms]
version:
- クラウド
- Server v3.x
---
= Android アプリケーションのデプロイ
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI で Android アプリをデプロイする方法
:icons: font
:toc: macro

:toc-title:

[#overview]
== 概要

このチュートリアルでは、CircleCI で link:https://fastlane.tools/[fastlane] を使って Android アプリを自動的にデプロイする方法を説明します。

ここのチュートリアルに沿って実行するには、以下を準備する必要があります。

- link:https://gradle.org/[Gradle] を使ってビルドした Android プロジェクト
- CircleCI での Android プロジェクトのセットアップ。 CircleCI で初めてプロジェクトをセットアップする場合は、 <<getting-started#,クイックスタートガイド>> で詳細をご確認ください。
- fastlame のインストールと Google Developers のサービスアカウントの認証情報を使った Google Play ストアへのアクセスの許可。 fastlane をインストール、セットアップ、及び設定する方法は、 link:https://docs.fastlane.tools/getting-started/android/setup/[Fastlane Android のセットアップに関するドキュメント] の手順をご覧ください。

NOTE: fastlane のセットアップでは、Google Developers のサービスアカウントから認証情報ファイルをダウンロードします。 このチュートリアルは、このファイルが `fastlane` フォルダに `api.json` として保存されていることを前提としています。

このチュートリアルでは Android Orb を使ってデプロイする方法も説明します。 このチュートリアルでは Android Orb を熟知している必要はありませんが、CircleCI Orb を初めて使用する場合は、 <<orb-intro#,Orb の概要>> をお読みになることを推奨します。 または、このチュートリアルでは Orb を使わずにプロジェクトをデプロイする方法も紹介します。

[#configure-fastlane-for-deployment-to-google-play-store]
== 1. fastlane を Google Play ストアにデプロイするための設定

. `fastlane` ディレクトリに移動し、`fastfile` を開きます。 このファイルは fastlane で実行可能なタスクの設定に使います。 ファイルを開くと、4 つのブロックに分かれています。
- `before_all`: ここではレーンが実行される前に実施すべき手順を指定します。
- `lane`: ここでは、Play ストアへのデプロイなど実施する実際のタスクを定義します。 お好きな数のレーンを定義できます。
- `after_all`: 実行したレーンが成功した場合にこのブロックを呼び出します。
- `error`: このブロックは他のすべてのブロックでエラーが発生した場合に呼び出されます。
. Fastfile には、リリースビルドを生成し Play Store にデプロイする `playstore` レーンが含まれています。 このレーンを変更します。 fastfile では、 `playstore` レーンを以下のよう更新します。
+
```
lane :playstore do
    gradle(task: "bundle")
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )
  end
```
+
このレーンは `gradle bundle` を実行し、`app-release.aab` (Android アプリバンドル) を生成し、このバンドルを Google Play コンソールのプロジェクトの内部トラックにデプロイします。

[#prepare-your-app-for-deployment]
== 2. Prepare your app for deployment

Next, you will make some updates to your app to prepare it for deployment. You will have to add a release signing config to your app-module `build.gradle` file. This enables Fastlane to use the same keystore you used in generating earlier releases of your app to also generate subsequent releases.

. Add the `signingConfigs` snippet to your app-module `build.gradle`:
+
```
android {
  signingConfigs {
        release {
            keyAlias keyStoreProperties['releaseKeyAlias']
            keyPassword keyStoreProperties['releaseKeyPassword']
            storeFile file(keyStoreProperties['releaseKeyStore'])
            storePassword keyStoreProperties['releaseStorePassword']
        }
      }
    ...
  }
```
+
NOTE: For this tutorial, you will be generating a `keystore` and `keystore.properties` at runtime. You can replace the fields with your actual passwords and information for local deployment, but we strongly advise to *not* upload these credentials to a remote repository. If you need help generating a keystore for your application, you may refer to the link:https://developer.android.com/studio/publish/app-signing#generate-key[Android user guide].
. Update the `buildTypes` section of the `build.gradle` file like so:
+
```
buildTypes {
    release {
        signingConfig signingConfigs.release
        ...
    }
}
```
+
With this, you have configured the app to use a specific keystore. Next, you will create functions in your `build.gradle` file to help you generate build numbers for your app versions.
. Add the following snippet just before the `android` section of your app-module `build.gradle` file:
+
```
ext.versionMajor = 1
ext.versionMinor = 0
ext.versionPatch = 1
ext.versionClassifier = null
ext.isSnapShot = false
ext.minSdkVersion = 21

private Integer generateVersionCode() {
    return ext.minSdkVersion * 10000000 + ext.versionMajor * 10000 +
            ext.versionMinor * 100 + ext.versionPatch
}

private String generateVersionName() {
    String versionName = "${ext.versionMajor}.${ext.versionMinor}.${ext.versionPatch}"

    if (ext.versionClassifier == null) {
        if (ext.isSnapShot) {
            ext.versionClassifier = "SNAPSHOT"
        }
    }

    if (ext.versionClassifier != null) {
        versionName += "-" + ext.versionClassifer
    }

    return versionName
}
```
+
In this snippet, you added variables that hold your app version values. You then added two methods, `generateVersionCode` and `generateVersionName` to generate the version code and version name based on how the app version value changes. This helps to give your app a unique and progressive way of generating your version code when you modify your app versions.
+
Note that you will need to update at least one parameter of the version for every deployment. Fastlane fails if a version code is reused.
. Update these properties in the `defaultConfig` section of the `build.gradle` file like so:

```
defaultConfig {
    versionName generateVersionName()
    versionCode generateVersionCode()
    // ... Leave others as is

}
```

Now your android app is able to be bundled and deployed on your local machine.

[#set-up-circleci-deployment]
== 3. Set up CircleCI Deployment

. You need to convert your keystore to base64 to safely access it in CircleCI. You can do this conversion in the terminal using the following command:
+
```shell
$ base64 your_key_store
```
+
Save the output somewhere easily accessible for the next step.
. Next, you need to set <<env-vars#,environment variables>> for deployment through CircleCI.
+
Open your Android project in the app.circleci.com[CircleCI web app] and select *Project Settings*. Navigate to *Environment Variables* and add the following variables:
- `$BASE64_KEYSTORE` - Your base64 keystore, generated in the previous step
- `$GOOGLE_PLAY_KEY` - The contents of your `api.json` file, generated from the Fastlane install before starting this tutorial
- `$RELEASE_KEY_ALIAS` - Your key alias
- `$RELEASE_KEY_PASSWORD` - Your key password
- `$RELEASE_STORE_PASSWORD` - Your keystore password
. Add the following snippet to your `build.gradle` file. This allows you to import your keystore properties from a `keystore.properties` that will be generated at runtime.
+
```
def keyStorePropertiesFile = rootProject.file("keystore.properties")
def keyStoreProperties = new Properties()
keyStoreProperties.load(new FileInputStream(keyStorePropertiesFile))

android {
...
}
```
+
[NOTE]
====
You can also create a `keystore.properties` file in your project directory for local bundling and deployment, if you wish. Do *not* push this file or your keystore to a remote repository.

Use the following snippet to create this file:

```
releaseKeyAlias=YourKeyAlias
releaseKeyPassword=YourKeyPassword
releaseKeyStore=YourKeyStorePath
releaseStorePassword=YourKeyStorePassword
```
====

Now, you need to configure `.circleci/config.yml` to decrypt your keystore, generate `keystore.properties`, and create the Google Play API key at runtime.

If you have not already done so, create a `.circleci` folder in the root of your project repository. この `.circleci` フォルダーに `config.yml` ファイルを作成します。

[#set-up-config-with-the-android-orb]
== 4a. Set up config with the Android orb

Using the Android orb gives you two options for deploying to the Google Play Store. You can either use the deploy-to-play-store job from the orb, or run each command individually in a job.

[#use-the-deploy-to-play-store-job]
=== i. Use the deploy-to-play-store job

To deploy using the deploy-to-play-store job you just need to add `android/deploy-to-play-store` to your list of jobs in your workflow.

If you set your environment variables as shown earlier in this tutorial, then you should not need to set the following parameters, as the default values take the same environment value names:

- `base64-keystore`
- `release-key-alias`
- `release-key-password`
- `release-store-password`
- `google-play-key`

The following snippet an example with each parameter set as its default value.

```yaml
workflows:
  deploy:
    jobs:
      - android/deploy-to-play-store:
                executor:
                  name: android/android-docker
                  tag: "2022.0.7"
                base64-keystore: BASE64_KEYSTORE
                release-key-alias: RELEASE_KEY_ALIAS
                release-key-password: RELEASE_KEY_PASSWORD
                release-keystore: ./keystore
                release-store-password: RELEASE_STORE_PASSWORD
                keystore-properties-working-directory: '.'
                google-play-key: GOOGLE_PLAY_KEY
                lane-name: deploy
                fastlane-working-directory: '.'
```

NOTE: The executor has no default value and must be set in the config.

[#run-each-command-individually]
=== ii. Run each command individually

To run each command individually in your workflow, you will need to add the following commands:

- `decode-keystore`
- `create-keystore-properties`
- `create-google-play-key`
- `fastlane-deploy`

Additionally, you need to run either `npm install` or `yarn install` using the Node orb.

As with the deploy-to-play-store approach, you will not need to set the parameters `base64-keystore`, `release-key-alias`, `release-key-password`, `release-store-password`, and `google-play-key`, if you had created environment variables as outlined earlier in this tutorial.

Below is an example config of this approach:

```yaml
orbs:
  android: circleci/android@3.0.0
  node: circleci/node@5.0.2
jobs:
  test-fastlane:
      docker:
        - image: cimg/android:2022.07
      resource_class: large
      steps:
        - checkout
        - node/install:
            install-yarn: false
            node-version: "16.13.0"
        - run: npm install
        - android/decode-keystore:
            keystore-location: android/app/keystore
        - android/create-keystore-properties:
            working-directory: android
        - android/create-google-play-key:
            working-directory: android
        - android/fastlane-deploy:
            working-directory: android
            lane-name: internal
```

[#set-up-config-without-the-android-orb]
== 4b. Set up config without the Android Orb

. Add the following command to your deployment job in `.circleci/config.yml` to decrypt your keystore from the base64 environment variable set earlier (`$BASE64_KEYSTORE`).
+
```yaml
run:
  name: Decode Android key store
  command: echo $BASE64_KEYSTORE | base64 -d | tee keystore android/app/keystore > /dev/null
```
. Next, you need to generate a `keystore.properties` file in order to publish your work to the Google Play Store.
+
To do so, you need to create another environment variable named `$RELEASE_KEYSTORE`, that points to the location of the decrypted keystore.
+
Add the following command to your deployment job:
+
```yaml
run:
  name: Create keystore.properties
  command: cd android && printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' \
  $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > keystore.properties
```
. Finally, you need to create your Google Play API key from your `api.json` You have already saved the value with an environment variable `$GOOGLE_PLAY_KEY`, so you can refer to this variable and write the api.json file at runtime, instead of uploading it to a remote repository.
+
Add the following command to the job:
+
```yaml
run:
  name: Create Google Play key
  command: echo $GOOGLE_PLAY_KEY > google-play-key.json
```
. To now deploy your app, you need to add your fastlane steps. To do this you only need to add a command that runs `fastlane my_deployment_lane`; in this case, the command looks like this:
+
```yaml
run: fastlane playstore
```
+
NOTE: You may need to install Fastlane on the image you are running your pipeline on. To do this, run `sudo gem install fastlane`.
+
Fastlane recommends using Bundler in this step. If you choose to use Bundler, you will need to add another step to install Bundler:
+
```
run: sudo gem install fastlane
```
+
Then, replace the `run: fastlane playstore` step with `run: bundle exec fastlane playstore`.

[#next-steps]
== 次のステップ

- A <<deploy-ios-applications#,guide to deploying iOS apps>> is also available.
- Visit the xref:deployment-overview.adoc[Deployment overview] for a general introduction on deployment with CircleCI, as well as examples for specific deployment targets such as Google Cloud Platform, AWS, and Heroku.