---

redirect_from:
  - /deployment/
  - /deployments/
  - /deployment-examples/
  - /deployment-integrations/
version:
- Cloud
- Server v3.x
- Server v2.x
---
= Deployment overview
:page-layout: classic-docs
:page-liquid:
:page-description: Learn the basics of CircleCI deployment.
:icons: font
:toc: macro

:toc-title:

Deployment with CircleCI is just the same as any other job configuration. ジョブを作成し、どんなターゲットに対してもデプロイできるように設定します。 このドキュメントでは、導入プロセスの概要に加えて、ベストプラクティスや最適化戦略を紹介します。

toc::[]

[#discrete]
== 概要

ソフトウェア・アプリケーションの開発およびテストが完了したら、デプロイし、対象ユーザーが利用できるようにする必要があります。 CircleCIは、ほぼすべてのターゲットにデプロイすることができ、QA/テスト、機能管理、およびブルーグリーンデプロイやカナリアデプロイなどのデプロイ戦略を行うための他のサービスとの統合を簡単に設定することができます。 Quickly and easily customize your configuration to match your requirements, whether a fully automated process or elements of manual approval are required.

[#the-basics-of-deployment]
== The basics of deployment

* **Deployment job**: To deploy your application, add a <<jobs-steps#jobs-overview,job>> to your `.circleci/config.yml` file and configure the job to run the steps you require. Visit the other pages in the deployment section of the documentation for example configurations for common deployment targets.
* **Deployment parameters**: You may need to add environment variables and SSH keys to fulfill your deployment steps. Environment variables can be added to the project itself via the CircleCI web app (follow links below for detailed instructions), or defined within your configuration.
** プロジェクトレベルを追加 <<env-vars#setting-an-environment-variable-in-a-project,環境変数>>
** プロジェクトレベル <<add-ssh-key#,SSH キー>>
* **Manual approval**: If your deployment strategy requires a manual approval step, you can include a <<workflows#holding-a-workflow-for-a-manual-approval,hold/approve>> job within your workflow. A manual approval button will then be available from the workflows map in the CircleCI web app.

[#using-orbs-to-simplify-deployment]
== Orb を使ってデプロイを簡素化する

CircleCI offers packages of reusable configuration known as <<orb-intro#,orbs>>. Orbs are available for many common deployment targets, which can help you to simplify and streamline your configuration. Check out the full range of available orbs in the link:https://circleci.com/developer/orbs[Orbs Registry]. シンプルなデプロイパイプラインであれば、Orb を使うことで最小限の設定のみで必要な結果を得ることができます。

例として、 https://circleci.com/developer/orbs/orb/circleci/aws-code-deploy[AWS CodeDeploy Orb] を考えてみましょう。 この Orb にはあらかじめ `deploy` ジョブが設定されており、Orb スタンザを追加して Orb が起動したら、 `aws-code-deploy/deploy` の一行で設定に含めることができます。 以下の例ように、簡単にデプロイすることができます。

```yaml
version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@x.y
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: myApplication
          bundle-bucket: myApplicationS3Bucket
          bundle-key: myS3BucketKey
          deployment-group: myDeploymentGroup
          service-role-arn: myDeploymentGroupRoleARN
```

Orb は内部で、 `aws-code-deploy/deploy` ジョブの宣言により設定された指定パラメーターを使用して、アプリケーションの作成、バンドル、デプロイを行います。

[#next-steps]
== 次のステップ

* <<deploy-to-artifactory#,Deploy to Artifactory>>
* <<deploy-to-aws#,Deploy to AWS>>
* <<deploy-to-azure-container-registry#,Deploy to Azure Container Registry>>
* <<deploy-to-capistrano#,Deploy to Capistrano>>
* <<deploy-to-cloud-foundry#,Deploy to Cloud Foundry>>
* <<deploy-to-firebase#,Deploy to Firebase>>
* <<deploy-to-google-cloud-platform#,Deploy to Google Cloud Platform>>
* <<deploy-to-heroku#,Deploy to Heroku>>
* <<deploy-ios-applications#,Deploy iOS applications>>
* <<deploy-to-npm-registry#,Deploy to NPM registry>>
* <<deploy-over-ssh#,Deploy over SSH>>
* <<authorize-google-cloud-sdk#,Authorize Google Cloud SDK>>
* <<publish-packages-to-packagecloud#,Publish packages to packagecloud>>

Also head to the link:https://circleci.com/developer/orbs[Orbs Registry] to see if there is an orb for your deployment target to help keep your configuration simple. お探しの Orb がない場合は、<<orb-author-intro#,Orb のオーサリング>> をご検討ください！