---

description: "このドキュメントでは、Heroku へのデプロイの例を示します"
version:
- クラウド
- Server v3.x
- Server v2.x
---
= Heroku へのデプロイ
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

link:https://www.heroku.com/[Heroku] は、クラウドでアプリケーションをホスティングするための一般的なプラットフォームです。 アプリケーションを Heroku にデプロイするように CircleCI を設定するには、以下の手順を行います。

== Heroku Orb を使用したデプロイ

1. Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。
1. Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。 {% include snippets/ja/env-var-or-context.adoc %}
1. link:https://circleci.com/developer/orbs/orb/circleci/heroku[Heroku Orb] を使って設定を簡単にします。 `deploy-via-git` により、Heroku CLI のプライマリコンテナへのインストール、定義した任意のデプロイ前のステップの実行、アプリケーションの実行、そして定義した任意のデプロイ後のステップの実行が行われます。 パラメーターとオプションの詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[Orb レジストリ] の Heroku Orb ページを参照してください。
+
```yaml
version: 2.1

orbs:
    heroku: circleci/heroku@x.y # Use the Heroku orb in your config

workflows:
    heroku_deploy:
    jobs:
        - build
        - heroku/deploy-via-git:
            requires:
            - build # only run deploy-via-git job if the build job has completed
            filters:
            branches:
                only: main # only run deploy-via-git job on main branch
```

Heroku Orb の詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[CircleCI Heroku Orb] を参照してください。

== 2.0 設定を使った Heroku のデプロイ

1. Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。
1. Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。 {% include snippets/ja/env-var-or-context.md %}
1. `.circleci/config.yml` で、デプロイジョブを作成して <<executor-intro#,Executor タイプ>> を追加します。
1. デプロイジョブにステップを追加し、コードをチェックアウトしデプロイします。 デプロイしたいブランチを指定します。この例では、main ブランチを指定し、`git push` コマンドを使ってデプロイします。
+
```yaml
version: 2

jobs:
    build:
    ...
    deploy:
    docker:
        - image: <docker-image-name-tag>
        auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
        - checkout
        - run:
            name: Deploy Main to Heroku
            command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
    version: 2
    build-deploy:
    jobs:
        - build
        - deploy:
            requires:
            - build # only run deploy-via-git job if the build job has completed
            filters:
            branches:
                only: main # only run deploy-via-git job on main branch
```

NOTE: Heroku では、デプロイまたは自動デプロイで、デプロイの前に渡す CI を待機するオプションが提供されます。 詳細については、 link:https://devcenter.heroku.com/articles/github-integration#automatic-deploys[Heroku のドキュメント] を参照してください。