---

description: このドキュメントでは、SSH 経由でデプロイするためのコード例を紹介します。
contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= SSH 経由でのデプロイ
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このノウハウガイドでは、SSH経由でアプリケーションをデプロイするためのCircleCIの設定方法について説明します。

[# add-ssh-key-target]
== 1.  Add SSH key for target

Add the SSH key for the target to which you are deploying (these instructions are for cloud, server v3.x, and server v4.x).

. In a terminal, generate the key with `ssh-keygen -t ed25519 -C "your_email@example.com"`. See link:https://www.ssh.com/ssh/keygen/[Secure Shell documentation] for additional details.
. In the CircleCI application, go to your project's settings by clicking the the **Project Settings** button (top-right on the **Pipelines** page of the project).
. On the **Project Settings** page, click on **SSH Keys**.
. Scroll down to the **Additional SSH Keys** section.
. Click the **Add SSH Key** button.
. In the **Hostname** field, enter the key's associated host (for example, `git.heroku.com`). ホスト名を指定しない場合は、どのホストに対しても同じキーが使われます。
. In the **Private Key** field, paste the SSH key you are adding.
. Click the **Add SSH Key** button.

For additional context, see the xref:add-ssh-key#[Adding an SSH Key to CircleCI] page.

[#ssh-username-and-hostname]
== 2.  Add the SSH username and hostname

ビルド VM の SSH ユーザー名と SSH ホスト名を環境変数として追加します。 For instructions, see the xref:set-environment-variable#set-an-environment-variable-in-a-project[Set an environment variable in a project] page. 以下の例では、これらの変数はそれぞれ `SSH_USER` および `SSH_HOST` として定義されています。

[#create-deploy-job]
== 3.  Create a deploy job

`.circleci/config.yml` で `deploy` ジョブを作成し、main ブランチをデプロイするためのコマンドを追加します。

```yaml
version: 2.1

jobs:
    build:
    #...
    deploy:
    machine:
        enabled: true
    steps:
        - run:
            name: Deploy Over SSH
            command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
    build-and-deploy:
    jobs:
        - build
        - deploy:
            requires:
            - build # only deploy once build job has completed
            filters:
            branches:
                only: main # only deploy on the main branch
```