---

description: This is document provides examples of deploying to Heroku.
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Deploy to Heroku
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

In this how-to guide, you will learn how to configure CircleCI to deploy to Heroku.

[#introduction]
== はじめに

link:https://www.heroku.com/[Heroku] は、クラウドでアプリケーションをホスティングするための一般的なプラットフォームです。 アプリケーションを Heroku にデプロイするように CircleCI を設定するには、以下の手順を行います。

== Heroku Orb を使用したデプロイ

[#create-account]
=== 1.  Create an account

Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。

[#create-env-vars]
=== 2.  Create environment variables

Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。 {% include snippets/ja/env-var-or-context.adoc %}

[#deploy-with-orb]
=== 3.  Heroku Orb を使用したデプロイ

Use the link:https://circleci.com/developer/orbs/orb/circleci/heroku[Heroku orb] to keep your configuration simple. `deploy-via-git` により、Heroku CLI のプライマリコンテナへのインストール、定義した任意のデプロイ前のステップの実行、アプリケーションの実行、そして定義した任意のデプロイ後のステップの実行が行われます。 パラメーターとオプションの詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[Orb レジストリ] の Heroku Orb ページを参照してください。

{% include snippets/ja/add-version-number.adoc %}

```yaml
version: 2.1
orbs:
  heroku: circleci/heroku@x.y
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: your-database-migration-command #example of a post-deployment step
          pre-steps:
            - run: command-that-run-before-deploying #example of a pre-deployment step

```

Heroku Orb の詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[CircleCI Heroku Orb] を参照してください。

== 2.0 設定を使った Heroku のデプロイ

[#create-account-2]
=== 1.  Create an account

Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。

[#create-env-vars-2]
=== 2.  Create environment variables

Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。 {% include snippets/ja/env-var-or-context.adoc %}

[#create-deploy-job]
=== 3.  Create deploy job

In your `.circleci/config.yml`, create a `deploy` job and add an xref:executor-intro#[executor type].

[#add-steps-deploy-job]
=== 4. Add steps to your deploy job

Add `steps` to your `deploy` job to checkout and deploy your code. You can specify which branch you would like to deploy. The example below specifies the main branch, and deploys using a `git push` command.

```yaml
version: 2

jobs:
    build:
    ...
```

NOTE: Heroku では、デプロイまたは自動デプロイで、デプロイの前に渡す CI を待機するオプションが提供されます。 詳細については、 link:https://devcenter.heroku.com/articles/github-integration#automatic-deploys[Heroku のドキュメント] を参照してください。