---

description: このドキュメントでは、Heroku にデプロイするためのコード例を紹介します。
contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= Heroku へのデプロイ
:page-layout: classic-docs

:icons: font
:toc: macro
:toc-title:

このノウハウガイドでは、HerokuにデプロイするためのCircleCIの設定方法を学びます。

[#introduction]
== はじめに

link:https://www.heroku.com/[Heroku] は、クラウドでアプリケーションをホスティングするための一般的なプラットフォームです。 アプリケーションを Heroku にデプロイするように CircleCI を設定するには、以下の手順を行います。

== Heroku Orb を使用したデプロイ

[#create-account]
=== 1.  アカウントの作成

Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。

[#create-env-vars]
=== 2.  環境変数の作成

Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。

include::../_includes/snippets/ja/env-var-or-context.adoc[]

[#deploy-with-orb]
=== 3.  Heroku Orb を使用したデプロイ

link:https://circleci.com/developer/orbs/orb/circleci/heroku[Heroku Orb] を使って設定を簡単にします。 `deploy-via-git` により、Heroku CLI のプライマリコンテナへのインストール、定義した任意のデプロイ前のステップの実行、アプリケーションの実行、そして定義した任意のデプロイ後のステップの実行が行われます。 パラメーターとオプションの詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[Orb レジストリ] の Heroku Orb ページを参照してください。

include::../_includes/snippets/ja/add-version-number.adoc[]

```yaml
version: 2.1
orbs:
  heroku: circleci/heroku@x.y
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: your-database-migration-command #example of a post-deployment step
          pre-steps:
            - run: command-that-run-before-deploying #example of a pre-deployment step

```

Heroku Orb の詳細については、 link:https://circleci.com/developer/ja/orbs/orb/circleci/heroku[CircleCI Heroku Orb] を参照してください。

== 2.0 設定を使った Heroku のデプロイ

[#create-account-2]
=== 1.  アカウントの作成

Heroku アカウントを作成し、 link:https://devcenter.heroku.com/start[Heroku の Web ページ] に記載された手順に従って、選択した言語でプロジェクトをセットアップします。

[#create-env-vars-2]
=== 2.  環境変数の作成

Heroku アプリケーションの名前と Heroku API キーを、それぞれ環境変数 `HEROKU_APP_NAME` と `HEROKU_API_KEY` として追加します。 include::../_includes/snippets/ja/xcode-silicon-vm.adoc[]

[#create-deploy-job]
=== 3.  デプロイジョブの作成

`.circleci/config.yml` で、デプロイジョブを作成して xref:executor-intro#[Executor タイプ] を追加します。

[#add-steps-deploy-job]
=== 4. デプロイジョブに手順を追加

デプロイジョブに `steps` を追加し、コードをチェックアウトし `deploy` します。 デプロイしたいブランチを指定します。 この例では、main ブランチを指定し、`git push` コマンドを使ってデプロイします。

```yaml
version: 2

jobs:
    build:
    ...
```

NOTE: Heroku では、デプロイまたは自動デプロイで、デプロイの前に渡す CI を待機するオプションが提供されます。 詳細については、 link:https://devcenter.heroku.com/articles/github-integration#automatic-deploys[Heroku のドキュメント] を参照してください。