---
version:
- Server v2.x
- サーバー管理者
---
= Docker Hub プルスルーミラーの設定
:page-layout: classic-docs
:page-liquid:
:page-description: Docker Hub プルスルーレジストリミラーの設定方法を説明します。
:icons: font
:toc: macro
:toc-title:

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。

ここでは、Docker Hub プルスルーレジストリミラーを設定する方法について説明します。

toc::[]

== 概要

https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/[2020 年 11 月 1 日]より、Docker Hub で匿名ユーザーに対する発信元 IP に基づいたプル回数制限が導入されます。 運用中のサービスでの混乱を避けるために、Docker Hub から認証付きでプル操作を行うようにすることをお勧めします。 認証は設定ファイルで行えます (https://circleci.com/ja/docs/2.0/private-images/[Docker の認証付きプルの使用]を参照)。

または、Docker Hub アカウントの認証情報を使って事前に設定した Docker Hub プルスルーレジストリミラーをセットアップするという方法もあります。 プルスルーレジストリミラーを使用すると、設定ファイルを何度も変更するよりも作業がシンプルになる場合があります。 また、Docker Hub への通信が減るため、パフォーマンスがさらに向上することも期待できます。

このセットアップには、以下の 3 つの手順があります。まず、プルスルーキャッシュレジストリを設定し、次にこのレジストリをミラーとして使用するよう Nomad クライアントを設定します。最後に、Machine Executor やリモート Docker ジョブでこのレジストリをミラーとして使用するよう VM サービスを設定します。

NOTE: サービスマシンは、ミラーを使用するように設定する必要はありません。 サービスマシンは、Docker イメージを定期的にプルせず (初期セットアップ時とアップグレード処理時のみ) 、ほとんどのイメージが Replicated からプルされます。 そのため、レート制限に達することはほとんどありません。

== プルスルーキャッシュレジストリの設定

ここでは、Docker Hub のミラーおよびリバースプロキシとして機能するプルスルーキャッシュレジストリの設定について説明します。 プルスルーキャッシュレジストリには 2 つのオプションがあり、HTTP を使用した設定が簡単な基本的なものと、HTTPS を使用したよりセキュアなものがあります。 どちらもほとんどのケースに対応できますが、よりセキュアなオプションが必要なケースもあります。

=== 前提条件: Docker Hub アカウントの設定


プルスルーキャッシュレジストリを設定する前に、*Docker Hub アカウントを設定します*。 このアカウントは、プルスルーキャッシュレジストリが Docker Hub で認証する際に使用します。

WARNING: 専用アカウントを設定することをお勧めします。 このアカウントでアクセスできるリソースには、お客様の CircleCI サーバーを使用するすべてのエンドユーザーがアクセスできるようになります。 *このアカウントが Docker Hub に_プライベート_イメージを登録している場合*、お客様の CircleCI サーバーを利用するすべてのユーザーがそのプライベートイメージにアクセスできるようになるため、専用アカウントの設定が特に重要になります。

NOTE: 無料アカウントも使用できますが、有料アカウントを設定すると回数制限を気にせずに使用できるためお勧めです。有料アカウントの場合は、無制限にイメージをプルできます。 詳細は、https://www.docker.com/pricing を参照してください。

=== 基本的なプルスルーキャッシュレジストリ (Docker Hub の HTTP プロキシ) の設定

. Docker がインストールされた*独立した Linux サーバーを設定します* 。
+
このレジストリを独立したサーバー (CircleCI 環境外のサーバー) として設定し、このキャッシュサーバーの負荷が他の CircleCI Server のサービスに影響を与えないようにします。
+
例えば、このサーバーの IP アドレスを `192.0.2.1` とし、設定するレジストリの URL は、`http://192.0.2.1` とします。 この URL は後で Nomad クライアントと VM サービスを設定する際に必要になります。

. 以下のコマンドを実行して、*レジストリを起動* します。
+
NOTE: `DOCKER_HUB_USERNAME` は Docker Hub アカウントのユーザー名に、`DOCKER_HUB_ACCESS_TOKEN` は https://hub.docker.com/settings/security で取得したアクセストークンにそれぞれ置き換えてください。
+
[source,bash]
----
sudo docker run \
  -d \
  -p 80:5000 \
  --restart=always \
  --name=through-cache \
  -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" \
  -e REGISTRY_PROXY_USERNAME=DOCKER_HUB_USERNAME \
  -e REGISTRY_PROXY_PASSWORD=DOCKER_HUB_ACCESS_TOKEN \
  registry
----

. 最後に、TCP ポート 80 (つまり HTTP) が開いていて アクセス可能であることを確認します。 セキュリティーを強化するために、Nomad クライアントと `machine` とリモート Docker Engine の VM にのみポートを開くことをお勧めします。
+
たとえば AWS では、セキュリティグループと OS レベルのファイアウォールの両方が Nomad クライアントからの接続を HTTP 経由で受け入れるように正しく設定されていることを確認する必要があります。

=== セキュアなプルスルーキャッシュレジストリ (Docker Hub の HTTPS プロキシ) の設定

特定の状況下で (特に `machine` Executor とリモート Docker Engine で https://docs.docker.com/develop/develop-images/build_enhancements/[BuildKit] を有効にしている場合)、プルスルーキャッシュレジストは HTTPS を使用して接続を受け入れる必要があります。  ここでは、HTTPS 接続をリッスンするプルスルーキャッシュの設定について説明します。

. Docker がインストールされた*独立した Linux サーバーを設定します* 。
+
このレジストリを独立したサーバー (CircleCI 環境外のサーバー) として設定し、このキャッシュサーバーの負荷が他の CircleCI Server のサービスに影響を与えないようにします。
+
NOTE: *このサーバーはホストネームでアクセスできるようにする必要があります*。 つまり、ホスト名 (`your-mirror.example.com` とします) がこのサーバーの IP アドレスに正しく解決されるように、DNS を設定する必要があります。 In this guide we assume that the URL for the registry we are setting up is `\https://your-mirror.example.com` (be aware that the URL scheme is `http**_s_**`, not `http`). この URL は後で Nomad クライアントと VM サービスを設定する際に必要になります。

. *`your-mirror.example.com` の TLS 証明書を取得し*、*TLS 証明書とプライベートキーをサーバーの `/root/tls`* に置きます。
+
NOTE: このガイドでは、自己署名証明書ではなく、既知の CA が発行した証明書を取得することを想定しています。 自己署名証明書の使用はまだテストされていません。

. 以下のコマンドを実行して、*レジストリを起動* します。
+
[NOTE]
====
`DOCKER_HUB_USERNAME` は Docker Hub アカウントのユーザー名に、`DOCKER_HUB_ACCESS_TOKEN` は https://hub.docker.com/settings/security で取得したアクセストークンにそれぞれ置き換えてください。

`fullchain.pem` は証明書のファイル名に、`privkey.pem` はプライベートキーのファイル名にそれぞれ置き換えてください。 *ここで指定する証明書は、リーフからルートへの証明書パスの追跡が可能な正確にチェーンされた証明書である必要があります*。
====
+
[source,bash]
----
sudo docker run \
  -d \
  -p 443:5000 \
  --restart=always \
  --name=through-cache-secure \
  -v /root/tls:/data/tls \
  -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" \
  -e REGISTRY_PROXY_USERNAME=DOCKER_HUB_USERNAME \
  -e REGISTRY_PROXY_PASSWORD=DOCKER_HUB_ACCESS_TOKEN \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/data/tls/fullchain.pem \
  -e REGISTRY_HTTP_TLS_KEY=/data/tls/privkey.pem \
  registry
----

. Finally, *make sure that the TCP port 443 (i.e. HTTPS) is open and accessible*. セキュリティーを強化するために、Nomad クライアントと `machine` とリモート Docker Engine の VM にのみポートを開くことをお勧めします。
+
たとえば AWS では、セキュリティグループと OS レベルのファイアウォールの両方が `machine`/`setup_remote_docker` ジョブの Nomad クライアントと VM からの接続をHTTPS 経由で 受け入れるように正しく設定されていることを確認する必要があります。

==== TLS 証明書の更新プラン

TLS 証明書は定期的な更新が必要です。 証明書の更新に必要な手順は以下のとおりです。

. `/root/tls` の証明書とプライベートキーを更新する。

. `docker restart through-cache-secure` を実行する。

技術的には、この処理は自動化できます。 たとえば、証明書に Let's Encrypt を使用している場合、`certbot renew` と上記手順を実行する cron タスクをセットアップできます。

== プルスルーキャッシュレジストリを使用するように Nomad クライアントを設定する (Nomad クライアントごとに実行)

. 以下のコマンドを実行して、*Docker デーモンの `registry-mirrors` オプションを指定* します。
+
NOTE: Replace `\http://192.0.2.1.or.https.your-mirror.example.com` with the URL of your pull through cache registry accordingly.
+
[source,bash]
----
https://docs.docker.com/registry/recipes/mirror/ (レジストリのミラー
の構成方法、英語)
----

. *Docker デーモンをリロード* して、設定を適用します。
+
`sudo systemctl restart docker.service`

== マシン/リモート Docker VM でプルスルーキャッシュレジストリを使用するように VM サービスを設定する

サービスマシンで、以下の手順を実行します。

. 以下のコマンドを実行して、*カスタマイズファイル用のディレクトリを作成します*。
+
`sudo mkdir -p /etc/circleconfig/vm-service`

. vm-service でロードするように、*カスタマイズスクリプト*を挿入します。 *下記のスクリプトを `/etc/circleconfig/vm-service/customizations` に追加します*。
+
NOTE: Replace `\http://192.0.2.1.or.https.your-mirror.example.com` in `DOCKER_MIRROR_HOSTNAME` variable with the URL of your pull through cache registry accordingly.
+
WARNING: このカスタマイズは 2.19.0 以降のバージョンでのみ可能です。

+
[source,bash]
----
export JAVA_OPTS='-cp /resources:/service/app.jar'
export DOCKER_MIRROR_HOSTNAME="http://192.0.2.1.or.https.your-mirror.example.com"

mkdir -p /resources/ec2
cat > /resources/ec2/linux_cloud_init.yaml << EOD
#cloud-config
system_info:
  default_user:
    name: "%1\$s"
ssh_authorized_keys:
  - "%2\$s"
runcmd:
  - bash -c 'if [ ! -f /etc/docker/daemon.json ]; then mkdir -p /etc/docker; echo "{}" > /etc/docker/daemon.json; fi'
  - bash -c 'cat <<< \$(jq ".\"registry-mirrors\" = [\"$DOCKER_MIRROR_HOSTNAME\"]" /etc/docker/daemon.json) > /etc/docker/daemon.json'
  - systemctl restart docker.service
EOD
----

. *VM サービス*を再起動して、カスタマイズした内容を反映します。
+
`sudo docker restart vm-service`

== 設定した内容のテスト

=== 明示的な認証なしでプライベートイメージを使用する

キャッシュレジストリの Docker ID にプライベートイメージがある場合、エンドユーザーの明示的な認証なしでアクセスできるはずです。

下記は、アクセスをテストするためのサンプル設定ファイルです。キャッシュレジストリで Docker ID　`yourmachineaccount` を使用し、プライベートイメージ `yourmachineaccount/private-image-with-docker-client` があると想定します。

[source,yaml]
----
version: 2

jobs:
  remote-docker:
    docker:
      - image: yourmachineaccount/private-image-with-docker-client # A copy of library/docker
    steps:
      - setup_remote_docker
      - run: docker pull yourmachineaccount/private-image-with-docker-client

  machine:
    machine: true
    steps:
      - run: docker pull yourmachineaccount/private-image-with-docker-client

workflows:
  version: 2
----

=== キャッシュレジストリのログの確認

`sudo docker logs through-cache` (セキュアなレジストリを設定した場合は、`sudo docker logs through-cache-secure`) を実行すると、キャッシュレジストリからログ出力を確認できます。 If it is operational, there should be messages that the registry is responding to the requests for manifests and blobs with HTTP status code `200`.

== 設定を元に戻すには

=== Disarm Nomad Clients

Follow the steps below on _each_ Nomad client.

. *`/etc/docker/daemon.json` の `registry-mirrors` オプションを削除* します。
+
[source,bash]
----
sudo bash -c 'cat <<< $(jq "del(.\"registry-mirrors\")" /etc/docker/daemon.json) > /etc/docker/daemon.json'
----

. Run `sudo systemctl restart docker.service` to apply the change.

=== Disarm VM Service

サービスマシンで、以下の手順を実行します。

. *Void the `JAVA_OPTS` environment variable* by running the command below.
+
`echo 'unset JAVA_OPTS' | sudo tee -a /etc/circleconfig/vm-service/customizations`

. Run `sudo docker restart vm-service` to apply the change.

== 関連資料

* https://docs.docker.com/registry/recipes/mirror/[How to configure a pull through cache mirror]
* https://hub.docker.com/_/registry[Official Docker Registry Docker image]
* https://docs.docker.com/registry/configuration/[How to configure official Docker Registry]
