---

version:
- Server v2.x
- Server Admin
---
= Setting Up Docker Hub Pull Through Mirror
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to configure a Docker Hub pull through registry mirror.
:icons: font
:toc: macro

:toc-title:

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。

ここでは、Docker Hub のレジストリのミラーを設定する方法について説明します。

toc::[]

[#overview]
== 概要

Starting https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/[November 1, 2020], Docker Hub will impose rate limits for anonymous pulls based on the originating IP. 運用中のサービスでの混乱を避けるために、Docker Hub から認証付きでプル操作を行うようにすることをお勧めします。 You can authenticate using build config (see https://circleci.com/docs/2.0/private-images/[Using Docker Authenticated Pulls]).

あるいは、Docker Hub アカウントの資格情報をあらかじめ構成した Docker Hub のレジストリのミラーをセットアップするという方法もあります。 レジストリのミラーを使用すると、場合によっては多数の設定ファイルを変更するよりも簡単に対応できます。 また、Docker Hub への通信が減るため、パフォーマンスの更なる向上も期待できます。

Nomad クライアントがレジストリのミラーを使用するように設定する (Nomad クライアント「ごと」に実行)

NOTE: サービスマシンには、ミラーを使用するように設定する必要はありません。 サービスマシンは、Docker イメージを定期的にプルせず (初期セットアップ時とアップグレード処理時のみ) 、ほとんどのイメージが Replicated からプルされます。 そのため、レート制限に達することはほとんどありません。

[#set-up-a-pull-through-cache-registry]
== プルスルーキャッシュレジストリの設定

ここでは、Docker Hub のミラーおよびリバースプロキシとして機能するプルスルーキャッシュレジストリの設定について説明します。 プルスルーキャッシュレジストリには 2 つのオプションがあり、HTTP を使用した設定が簡単な基本的なものと、HTTPS を使用したよりセキュアなものがあります。 どちらもほとんどのケースに対応できますが、よりセキュアなオプションが必要になるケースもあります。

[#prerequisites-set-up-docker-hub-account]
=== 前提条件: Docker Hub アカウントの設定


Before setting up a pull through cache registry, you need to *set up a Docker Hub account*. これは、レジストリのミラーから Docker Hub にアクセスする際に使用します。

WARNING: 専用アカウントを設定することをお勧めします。 このアカウントでアクセスできるリソースには、お客様の CircleCI サーバーを使用するすべてのエンドユーザーがアクセスできます。 This is especially important *if the account has _private_ images registered on Docker Hub*, as these private images will become accessible by all users of your CircleCI server installation.

NOTE: 無料のアカウントも使用できますが、有料アカウントを設定すると回数制限を気にせずに使用できるのでお勧めです。有料アカウントの場合、無制限にイメージをプルできます。 See also: https://www.docker.com/pricing.

[#set-up-an-elementary-pull-through-cache-registry]
=== 基本的なプルスルーキャッシュレジストリ (Docker Hub の HTTP プロキシ) の設定

. *Set up an independent Linux server* that has Docker installed.
+
このレジストリを独立したサーバー (CircleCI 環境外のサーバー) として設定し、このキャッシュサーバーの負荷が他の CircleCI Server のサービスに影響を与えないようにします。
+
Assuming that the IP address for this server is `192.0.2.1`, the URL for the registry to set up is `http://192.0.2.1`. この URL は後で Nomad クライアントと VM サービスを設定する際に必要になります。
. Run the command below to *start the registry*.
+
NOTE: Replace `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN` with the username for the Docker Hub account and the access token you obtained through https://hub.docker.com/settings/security, respectively.
+
[source,bash]
----
sudo docker run -d -p 80:5000 --restart=always --name=through-cache -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" -e REGISTRY_PROXY_USERNAME=DOCKER_HUB_USERNAME -e REGISTRY_PROXY_PASSWORD=DOCKER_HUB_ACCESS_TOKEN registry
----
. TCP ポート 80 (HTTP) が開いていてアクセス可能であることを確認します。 アクセス可能であることを確認します。 For better security, we recommend that you only open the port to Nomad clients and VMs for `machine` executors and remote docker engines.
+
たとえば AWS では、セキュリティ グループと OS レベルのファイアウォールの両方が HTTP 経由で Nomad クライアントからの接続を受け付けるように正しく設定されていることを確認する必要があります。

[#set-up-a-secure-pull-through-cache-registry]
=== セキュアなプルスルーキャッシュレジストリ (Docker Hub の HTTPS プロキシ) の設定

Under certain circumstances (especially when you are enabling https://docs.docker.com/develop/develop-images/build_enhancements/[BuildKit] on `machine` executors and remote Docker engines), your pull through cache registry needs to accept connections over HTTPS. ここでは、HTTPS 接続をリッスンするプルスルーキャッシュの設定方法を紹介します。

. *Set up an independent Linux server* that has Docker installed.
+
このレジストリを独立したサーバー (CircleCI 環境外のサーバー) として設定し、このキャッシュサーバーの負荷が他の CircleCI Server のサービスに影響を与えないようにします。
+
NOTE: *The server needs to be accessible by its hostname*. Namely, you must configure DNS accordingly so that the hostname (assume `your-mirror.example.com`) resolves to the IP address of the server correctly. In this guide we assume that the URL for the registry we are setting up is `\https://your-mirror.example.com` (be aware that the URL scheme is `http**_s_**`, not `http`). この URL は後で Nomad クライアントと VM サービスを設定する際に必要になります。
. *Obtain a TLS certificate for `your-mirror.example.com`* and *put the certificate and the private key into `/root/tls`* of the server.
+
NOTE: このガイドでは、自己署名証明書ではなく、既知の CA が発行した証明書を取得することを想定しています。 自己署名証明書の使用はまだテストされていません。
. Run the command below to *start the registry*.
+
[NOTE]
====
Replace `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN` with the username for the Docker Hub account and the access token you obtained through https://hub.docker.com/settings/security, respectively.

Replace `fullchain.pem` and `privkey.pem` with the filenames of your certificate and private key, respectively. *The certificate specified there must be correctly chained enough for tracing the certification path from the leaf to the root*.
====
+
[source,bash]
----
sudo bash -c 'cat &lt;&lt;&lt; $(jq ".¥"registry-mirrors¥" = [¥"http://192.0.2.1¥"]" /etc/docker/daemon.json) &gt; /etc/docker/daemon.json'
----
. Finally, *make sure that the TCP port 443 (i.e. HTTPS) is open and accessible*. For better security, we recommend you to open the port only to Nomad clients and VMs for `machine` executors and remote docker engines.
+
On AWS, for example, you will need to make sure that both Security Groups and the firewall at the OS level are configured correctly to accept connections from Nomad clients and VMs for `machine`/`setup_remote_docker` jobs over HTTPS.

[#plan-for-renewal-of-TLS-certificates]
==== TLS 証明書の更新プラン

TLS 証明書は定期的な更新が必要です。 証明書の更新に必要な手順は以下のとおりです。

. Update the certificate and the private key in `/root/tls`.
. Run `docker restart through-cache-secure`.

技術的には、この処理は自動化できます。 For example, if you are using Let's Encrypt for your certificates, you can setup a cron task that executes `certbot renew` and the steps above.

[#configure-nomad-clients-to-use-the-pull-through-cache-registry]
== Configure Nomad clients to use the pull through cache registry (run for _each_ Nomad client)

. Run the command below to *configure the `registry-mirrors` option for the Docker daemon*.
+
NOTE: Replace `\http://192.0.2.1.or.https.your-mirror.example.com` with the URL of your pull through cache registry accordingly.
+
[source,bash]
----
sudo bash -c 'cat <<< $(jq ".\"registry-mirrors\" = [\"http://192.0.2.1.or.https.your-mirror.example.com\"]" /etc/docker/daemon.json) > /etc/docker/daemon.json'
----
. *Reload Docker daemon* to apply the configuration.
+
`sudo systemctl restart docker.service`

[#configure-vm-service-to-let-machine-remote-docker-vms-use-the-pull-through-cache-registry]
== マシン/リモート Docker VM でプルスルーキャッシュレジストリを使用するように VM サービスを設定する

サービスマシンで、以下の手順を実行します。

. Run the command below to *create a directory for your customization files*.
+
`sudo mkdir -p /etc/circleconfig/vm-service`
. *Populate a customization script* to be loaded by vm-service. *Add the script below to `/etc/circleconfig/vm-service/customizations`*.
+
NOTE: Replace `\http://192.0.2.1.or.https.your-mirror.example.com` in `DOCKER_MIRROR_HOSTNAME` variable with the URL of your pull through cache registry accordingly.
+
WARNING: このカスタマイズは 2.19.0 以降のバージョンでのみ可能です。
+
[source,bash]
----
export JAVA_OPTS='-cp /resources:/service/app.jar'
export DOCKER_MIRROR_HOSTNAME="http://192.0.2.1.or.https.your-mirror.example.com"

mkdir -p /resources/ec2
cat > /resources/ec2/linux_cloud_init.yaml << EOD
#cloud-config
system_info:
  default_user:
    name: "%1\$s"
ssh_authorized_keys:
  - "%2\$s"
runcmd:
  - bash -c 'if [ ! -f /etc/docker/daemon.json ]; then mkdir -p /etc/docker; echo "{}" > /etc/docker/daemon.json; fi'
  - bash -c 'cat <<< \$(jq ".\"registry-mirrors\" = [\"$DOCKER_MIRROR_HOSTNAME\"]" /etc/docker/daemon.json) > /etc/docker/daemon.json'
  - systemctl restart docker.service
EOD
----
. *Restart VM Service* to apply the customization.
+
`sudo docker restart vm-service`

[#testing-your-setup]
== 設定した内容のテスト

[#use-private-images-without-explicit-authentication]
=== 明示的な認証なしでプライベートイメージを使用する

キャッシュレジストリの Docker ID にプライベートイメージがある場合、エンドユーザーの明示的な認証なしでアクセスできるはずです。

Below is a sample config to test the access (assume that the cache registry uses Docker ID `yourmachineaccount`, and there is a private image `yourmachineaccount/private-image-with-docker-client`):

[source,yaml]
----
version: 2

jobs:
  remote-docker:
    docker:
      - image: yourmachineaccount/private-image-with-docker-client # A copy of library/docker
    steps:
      - setup_remote_docker
      - run: docker pull yourmachineaccount/private-image-with-docker-client

  machine:
    machine: true
    steps:
      - run: docker pull yourmachineaccount/private-image-with-docker-client

workflows:
  version: 2
----

[#check-logs-on-the-cache-registry]
=== キャッシュレジストリのログの確認

By running `sudo docker logs through-cache` (or `sudo docker logs through-cache-secure` if you have set up a secure registry) you can see log outputs from your cache registry. If it is operational, there should be messages that the registry is responding to the requests for manifests and blobs with HTTP status code `200`.

[#reverting-the-setup]
== 設定を元に戻すには

[#disarm-nomad-clients]
=== Nomad クライアントの設定を解除する

Follow the steps below on _each_ Nomad client.

. *Remove `registry-mirrors` option in `/etc/docker/daemon.json`* by running the command below.
+
[source,bash]
----
sudo bash -c 'cat <<< $(jq "del(.\"registry-mirrors\")" /etc/docker/daemon.json) > /etc/docker/daemon.json'
----
. Run `sudo systemctl restart docker.service` to apply the change.

[#disarm-vm-service]
=== VM サービスの設定を解除する

サービスマシンで、以下の手順を実行します。

. *Void the `JAVA_OPTS` environment variable* by running the command below.
+
`echo 'unset JAVA_OPTS' | sudo tee -a /etc/circleconfig/vm-service/customizations`

. Run `sudo docker restart vm-service` to apply the change.

[#next-steps]
== 次のステップ

* https://docs.docker.com/registry/recipes/mirror/[How to configure a pull through cache mirror]
* https://hub.docker.com/_/registry[Official Docker Registry Docker image]
* https://docs.docker.com/registry/configuration/[How to configure official Docker Registry]