---

version:
- クラウド
- Server v3.x
---
= サンプルとガイドの概要
:page-layout: classic-docs
:page-liquid:
:page-description: サンプルを使った CircleCI 学習リソース
:icons: font
:toc: macro

:toc-title:

ここでは、CircleCI の最もよく使われいてるプログラミング言語で記述されたアプリ、フレームワーク、プラットフォームのビルド、テスト、デプロイ方法を学ぶための一連のサンプルを紹介します。

CircleCI の利用が初めてのお客様は、最初のパイプラインを成功させるための <<getting-started#,クイックスタートガイド>> を参照してください。

Docker コンテナや Linux VM のような特定の実行環境でパイプラインジョブを追加する場合のサンプルは、<<hello-world#,Hello World>> ドキュメントを参照して下さい。

[#languages]
== 言語ガイド

さまざまな言語でデモアプリケーションを作成しているので、サンプルにより学習できます。 以下に挙げた各言語については、関連ガイドと GitHub のパブリックリポジトリを公開しています。

{% include snippets/ja/language-guides.adoc %}

[#platforms]
== プラットフォームガイド

お使いのプラットフォームに関連するチュートリアルを使用して、<<configuration-reference#,`.circleci/config.yml`>> でどのようなカスタマイズが可能かをご確認ください。

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|プラットフォームガイド
|説明

|<<project-walkthrough#,Linux プロジェクトのチュートリアル>>
|Flask を使用した Python プロジェクトを CircleCI 2.0 でビルドするためのセットアップについて、詳しく説明しています。

|<<hello-world-macos#example-application,macOS プロジェクトのチュートリアル>>
|CircleCI での macOS プロジェクトの設定

|<<ios-tutorial#,iOS プロジェクトのチュートリアル>>

|CircleCI での iOS プロジェクトの設定

|<<hello-world-windows#example-application,Windows プロジェクトのチュートリアル>>
|CircleCI 2.0 で .NET プロジェクトをセットアップする例をご紹介しています。
|===

[#next-steps]
== 次のステップ

- 同時実行ワークフロー、順次実行ワークフロー、ファンイン/ ファンアウトワークフロー、1 つの設定ファイルで Linux と iOS をビルドするためのサンプルについては、<<sample-config#,config.yml のサンプルファイル>> をお読み下さい。