---

contentTags:
  platform:
  - クラウド
---
= CircleCI のユーザー登録
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI 導入の第一歩.
:icons: font
:toc: macro

:toc-title:

CircleCI で最初のビルドを実行するには、link:https://circleci.com/signup/[ユーザー登録] のページに移動してください。 GitHub、 Bitbucket、 または GitLab アカウントで登録するか、後ほどメールアドレスを使ってコードに接続します。

[#vcs-signup]
== GitHub または Bitbucket のアカウントでの登録

. link:https://circleci.com/auth/vcs-connect?connection=Github[**GitHub で登録**] または link:https://circleci.com/auth/vcs-connect?connection=Bitbucket[**Bitbucket で登録**] のいずれかをクリックすると、認証プロセスが開始され、CircleCI がお客様のコードにアクセスできるようになります。
+
NOTE: GitHub を使用している場合、CircleCI を制限するオプションがあり、プライベートリポジトリへのアクセスを制限することができます。 Sign Up ボタンの横にあるドロップダウンメニューを使ってリストから **Public Repos Only** を選択します。
. GitHub または Bitbucket のユーザー名とパスワードを入力し、二要素認証を有効にしている場合はもう 1 つの認証要素を入力し、**ログイン** をクリックします。
. **Authorize Application** または同等のボタンをクリックします。 CircleCI パイプラインのダッシュボードにリダイレクトされます。
. CircleCI アプリケーションの **Project** ページから、プロジェクトコードのビルドを開始します。

[#gitlab-signup]
== GitLab アカウントでの登録

[.tab.signup.New_to_CircleCI]
--
. link:https://circleci.com/signup/[**GitLab で登録**] をクリックします。
. メールアドレスを入力し、CicrcleCI アカウント用の安全なパスワードを設定します。 入力したメールアドレスに確認メールが送信されます
. GitLab リポジトリから新しいプロジェクトを作成するオプション画面が表示されます。
 画面の指示に従って GitLab アカウントと連携します。 リポジトリを選択し、新しいプロジェクトを作成すると、CircleCI Web アプリのダッシュボードにリダイレクトされます。
--

[.tab.signup.Existing_CircleCI_users]
--
**新しい組織を作成する**

.  link:https://app.circleci.com/[CircleCI Web アプリ] にログインします。
. ご自身の組織名をクリックし、画面左上で組織切り替えメニューを開きます。 **Create New Organization** を選択します。
. GitLab.com オプションの隣にある **Connect** をクリックします。 GitLab アカウントの承認、プロジェクトの作成、および GitLab アカウントからのリポジトリの接続についての説明が表示されます。 その後、組織のダッシュボードに自動的に移動します。

この新しい組織で、組織内のユーザーと GitLab プロジェクトを管理することができます。 組織のプランは、最初は Free プランになります。 後で他のプランにアップグレードできます。 この料金プランは、以前ご自身のアカウントで設定された GitHub または Bitbucket での組織とは無関係です。
--

NOTE: GitLab と CircleCI の連携に関する詳細は link:/docs/gitlab-integration[GitLab と Saas の連携についてのページ] を参照してください。

[#email-signup]
== メールアドレスでの登録

. link:https://circleci.com/signup/[**メールアドレスで登録**] をクリックします。
. メールアドレスを入力し、CicrcleCI アカウント用の安全なパスワードを設定します。 入力したメールアドレスに確認メールが送信されます
. コードには接続せず、メールアドレスでの登録のみを行いたい場合は **Cancel** をクリックしします。 お客様の役割とエンジニアリング組織に最も当てはまる質問への回答画面が表示されます。
. 現時点ではコードに接続したくない場合は、CircleCI アプリ内のサンプルプロジェクトを参照してください。 CircleCI 上の一般的なオープンソースプロジェクトビルド (link:https://app.circleci.com/pipelines/github/facebook/react[React by Facebook])、または弊社独自のサンプルプロジェクト (link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-javascript-cfd/[JavaScript サンプルアプリ]) や (link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-python-cfd/[Python サンプルアプリ]) をご覧いただけます。

You will be able to start exploring features such as [pipelines]({{site.baseurl}}/pipelines/) and [workflows]({{site.baseurl}}/workflows). The **Dashboard**, **Projects**, **Organization Settings**, and **Plan** pages are not available until you connect your code.

When you are ready, you can connect to your GitHub, BitBucket, or GitLab accounts from the CircleCI web app.

[#terms]
== 利用規約

By signing up, you are agreeing to our link:https://circleci.com/terms-of-service/[SaaS Agreement] and link:https://circleci.com/privacy/[Privacy Policy]. CircleCI では、サービスの改善を目的として、お客様のアカウントデータへの読み取りアクセスまたは書き込みアクセスの許可をお願いする場合があります。 GitHub アカウントをお持ちで、プライベートプロジェクトへのアクセスの共有を希望されない場合は、パブリックリポジトリを選択してください。 Protected by reCAPTCHA, Google link:https://policies.google.com/privacy?hl=en[Privacy Policy] and link:https://policies.google.com/terms?hl=en[Terms of Service] apply.

[#next-steps]
== 次のステップ

* Go to the link:/docs/hello-world[Hello World] page to learn the basics of setting up projects, switching orgs, and the link:/docs/configuration-reference[`.circleci/config.yml`] file that determines your execution environment and automates your tests.
* Read the link:/docs/concepts[Concepts] page for an overview of foundational CircleCI concepts such as pipelines, executors and images, workflows, and jobs.