---

version:
- クラウド
- Server v3.x
---

= 用語集

:page-layout: classic-docs
:page-liquid:
:page-description: A glossary of terms used for the CircleCI product.
:icons: font
:toc: macro
:toc-title:

== 認証

ホストされた CircleCI プロジェクトの認証は、VCS または Google OAuth によって処理されます。 Sessions last for 14 days. See the <<gh-bb-integration/#permissions-overview,Permissions Overview>> section of the VCS Integration document for additional details.

User authentication may use LDAP for an instance of the CircleCI application that is installed on your private server or cloud. See the <<authentication#,Authentication>> document for setup instructions.

== CircleCI Administrator

The first user to log into a private installation of CircleCI. Administrators have the ability to add and remove users.

== コンテナ

A container is a running instance of an image.

== Context

<<contexts#,Contexts>> provide a mechanism for securing and sharing environment variables across projects. 環境変数は、名前と値のペアとして定義され、実行時に挿入されます。 After a context has been created, you can use the context key in the workflows section of a project `.circleci/config.yml` file to give any job(s) access to the environment variables associated with the context.

== Docker レイヤーキャッシュ

The CircleCI Docker Layer Caching feature allows builds to reuse Docker image layers from previous builds. Image layers are stored in separate volumes in the cloud, and are not shared between projects. Layers may only be used by builds from the same project. For additional information about how the secure environment is created, see the <<docker-layer-caching#,Docker Layer Caching>> and <<building-docker-images#,Running Docker Commands>> documents.

== 環境変数

<<env-vars#,Environment variables>> store customer data that is used by a project. Only project administrators and owners are allowed to view or modify environment variables. The values are transmitted using secure protocols, for example, HTTPS and SSH, encrypted at rest, and hashed/salted to prevent CircleCI employees from viewing them.

== Executor 型

<<executor-types#,Executor Types>> define the underlying technology to run a job. Can be either `docker` to run your job inside a Docker container with a specified image, or `machine` to run your job inside a full virtual machine.

== イメージ

イメージは、実行コンテナを作成するための指示を含むパッケージ化されたシステムです。 The primary container is defined by the first image listed in a `.circleci/config.yml` file. ここで、Docker または Machine Executor を使用してジョブのコマンドが実行されます。 Visit the https://circleci.com/developer/images[CircleCI Developer Hub] to see available convenience and machine images.

== Job Space

All the containers being run by an <<#executor,executor>> for the current job.

== ジョブ

<<jobs-steps#,Jobs>> are collections of steps, which run commands/scripts as required. Each job must declare an executor that is either docker, machine, windows, or macos.

== Orb

<<orb-concepts#,Orbs>> are reusable snippets of code that help automate repeated processes, accelerate project setup, and make it easy to integrate with third-party tools. Visit the https://circleci.com/developer/orbs[Orbs Registry] on the CircleCI Developer Hub to search for orbs to help simplify your config.

== オーナー

The owner of the team's VCS organization.

== パイプライン

A <<pipelines#,CircleCI pipeline>> is the full set of processes you run when you trigger work on your projects. パイプラインには、ジョブを管理するワークフローが含まれます。 Pipelines are defined in your project '.circleci/config.yml.' file. _Pipelines are not available on CircleCI server v2.x._

== Primary Container

The first image listed in `.circleci/config.yml`. ここで、Docker executor を使用してジョブのコマンドが実行されます。

== Project Administrator

The user who adds a repository in the VCS to CircleCI as a project.

== プロジェクト

A CircleCI project shares the name of the code repository for which it automates workflows, tests, and deployment. It is visible on the **Projects** page of the https://app.circleci.com/[CircleCI web app] and must be added with the **Set Up Project** button. After a project is added, it is possible to configure settings, contexts, environment variables, and team members who may follow the project. Following a project enables you to subscribe to email notifications for the project's build status, and adds the project to your CircleCI dashboard.

== Remote Docker

A feature that enables building, running, and pushing images to Docker registries from within a Docker <<#executor,executor>> job. Visit the <<building-docker-images#,Runner Docker Commands>> page to learn more.

== Step

A step is a collection of executable commands. Visit the <<sample-config#,Sample Configuration>> page to learn more.

== ユーザー

An individual user within an organization. CircleCI ユーザーとは、ユーザー名とパスワードを使用して CircleCI プラットフォームにログインできる人を指します。 Users must be added to a VCS organization to view or follow associated CircleCI projects. Users may **not** view project data that is stored in environment variables.

== ワークフロー

<<workflows#,Workflows>> define a list of jobs and their run order. ジョブは、並列実行、順次実行、スケジュールに基づいて実行、あるいは承認ジョブを使用して手動ゲートで実行することができます。

== Workspace

A <<workspaces#,workspace>> is a workflows-aware storage mechanism. ワークスペースには、ダウンストリームジョブで必要になる可能性がある、ジョブ固有のデータが保存されます。