---

version:
- クラウド
- Server v3.x
---

= 用語集

:page-layout: classic-docs
:page-liquid:
:page-description: A glossary of terms used for the CircleCI product.
:icons: font
:toc: macro

:toc-title:

== 認証

ホストされたアプリケーションを使った CircleCI プロジェクトの認証は、VCS または Google OAuth によって処理されます。 セッションは 14 日間続きます。 詳細については、VCS との連携に関するドキュメントの <<gh-bb-integration#permissions-overview,権限の概要>> のセクションを参照してください。

ユーザー認証には、プライベートサーバーまたはクラウドにインストールされている CircleCI アプリケーションのインスタンスの LDAP を使用できます。 セットアップ方法は、<<authentication#,認証>> をご覧ください。

== CircleCI 管理者

CircleCI のプライベートインストール環境に最初にログインしたユーザーです。 管理者はユーザーを追加および削除できます。

== コンテナ

コンテナはイメージの実行インスタンスです。

== コンテキスト

<<contexts#,コンテキスト>> は、環境変数を保護し、プロジェクト間で共有するためのメカニズムを提供します。 環境変数は、名前と値のペアとして定義され、実行時に挿入されます。 コンテキストを作成したら、`.circleci/config.yml` ファイルのワークフローセクションで context</code> キーを使って、任意のジョブに当該コンテキストに関連付けられた環境変数へのアクセス権を付与することができます。

== Docker レイヤーキャッシュ

CircleCI Docker レイヤーキャッシュ機能により、以前のビルドの Docker イメージレイヤーを再利用することができます。 イメージレイヤーはクラウド内で別々のボリュームに保存され、プロジェクト間で共有されません。 同じプロジェクトのビルドのみレイヤーを共有することができます。 セキュアな環境の構築方法の詳細については、<<docker-layer-caching#,Docker レイヤーキャッシュ>> と <<building-docker-images#,Docker コマンドの実行>> を参照してください。

== 環境変数

<<env-vars#,環境変数>> は、プロジェクトで使用される顧客データを保存します。 環境変数の閲覧や変更ができるのは、プロジェクトの管理者とオーナーのみです。 値は HTTPS や SSH などのセキュアなプロトコルを使って送信され、保存時には暗号化され、CircleCI のスタッフが閲覧できないようにハッシュおよびソルトされます

== Executor 型

<<executor-types#,Executor 型>> によりジョブの実行の基盤テクノロジーが定義されます。 Can be either `docker` to run your job inside a Docker container with a specified image, or `machine` to run your job inside a full virtual machine.

== イメージ

イメージは、実行コンテナを作成するための指示を含むパッケージ化されたシステムです。 The primary container is defined by the first image listed in a `.circleci/config.yml` file. ここで、Docker または Machine Executor を使用してジョブのコマンドが実行されます。 Visit the https://circleci.com/developer/images[CircleCI Developer Hub] to see available convenience and machine images.

== Job Space

All the containers being run by an <<#executor,executor>> for the current job.

== ジョブ

<<jobs-steps#,Jobs>> are collections of steps, which run commands/scripts as required. Each job must declare an executor that is either docker, machine, windows, or macos.

== Orb

<<orb-concepts#,Orbs>> are reusable snippets of code that help automate repeated processes, accelerate project setup, and make it easy to integrate with third-party tools. Visit the https://circleci.com/developer/orbs[Orbs Registry] on the CircleCI Developer Hub to search for orbs to help simplify your config.

== オーナー

The owner of the team's VCS organization.

== パイプライン

A <<pipelines#,CircleCI pipeline>> is the full set of processes you run when you trigger work on your projects. パイプラインには、ジョブを管理するワークフローが含まれます。 Pipelines are defined in your project '.circleci/config.yml.' file. _Pipelines are not available on CircleCI server v2.x._

== Primary Container

The first image listed in `.circleci/config.yml`. ここで、Docker executor を使用してジョブのコマンドが実行されます。

== Project Administrator

The user who adds a repository in the VCS to CircleCI as a project.

== プロジェクト

A CircleCI project shares the name of the code repository for which it automates workflows, tests, and deployment. It is visible on the **Projects** page of the https://app.circleci.com/[CircleCI web app] and must be added with the **Set Up Project** button. After a project is added, it is possible to configure settings, contexts, environment variables, and team members who may follow the project. Following a project enables you to subscribe to email notifications for the project's build status, and adds the project to your CircleCI dashboard.

== Remote Docker

A feature that enables building, running, and pushing images to Docker registries from within a Docker <<#executor,executor>> job. Visit the <<building-docker-images#,Runner Docker Commands>> page to learn more.

== ステップ

A step is a collection of executable commands. Visit the <<sample-config#,Sample Configuration>> page to learn more.

== ユーザー

An individual user within an organization. CircleCI ユーザーとは、ユーザー名とパスワードを使用して CircleCI プラットフォームにログインできる人を指します。 Users must be added to a VCS organization to view or follow associated CircleCI projects. Users may **not** view project data that is stored in environment variables.

== ワークフロー

<<workflows#,Workflows>> define a list of jobs and their run order. ジョブは、並列実行、順次実行、スケジュールに基づいて実行、あるいは承認ジョブを使用して手動ゲートで実行することができます。

== Workspace

A <<workspaces#,workspace>> is a workflows-aware storage mechanism. ワークスペースには、ダウンストリームジョブで必要になる可能性がある、ジョブ固有のデータが保存されます。