---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= 用語集
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CircleCI で使われる用語をわかりやすく解説しています。
:icons: font
:experimental:

[#circleci-administrator]
== CircleCI 管理者

CircleCI のプライベートインストール環境に最初にログインしたユーザーです。 管理者はユーザーを追加および削除できます。

[#container]
== CircleCI 管理者

CircleCI のプライベートインストール環境に最初にログインしたユーザーです。

== コンテナ

コンテナとは、イメージの実行インスタンスを指します。 環境変数は、名前と値のペアとして定義され、実行時に挿入されます。 コンテキストを作成したら、`.circleci/config.yml` ファイルのワークフローセクションで context キーを使い、任意のジョブにそのコンテキストに関連付けられた環境変数へのアクセス権を付与することができます。

[#docker-layer-caching]
== コンテキスト

<<contexts#,コンテキスト>> は、環境変数を保護し、プロジェクト間で共有するためのメカニズムを提供します。 環境変数は、名前と値のペアとして定義され、実行時に挿入されます。 コンテキストを作成したら、`.circleci/config.yml` ファイルのワークフローセクションで context キーを使い、任意のジョブにそのコンテキストに関連付けられた環境変数へのアクセス権を付与することができます。 セキュアな環境の構築方法の詳細については、<<docker-layer-caching#,Docker レイヤーキャッシュ>> と <<building-docker-images#,Docker コマンドの実行>> を参照してください。 詳細については、xref:docker-layer-caching#[Docker レイヤーキャッシュ] と xref:building-docker-images#[Docker コマンドの実行] を参照してください。

[#environment-variables]
== Docker レイヤーキャッシュ

CircleCI Docker レイヤーキャッシュ機能により、以前のビルドの Docker イメージレイヤーを再利用することができます。 DLCを活用してワークフローを高速化することをおすすめします。 Dockerイメージを構築するように設定されたジョブは、次回以降の実行時に短時間で実行されます。

[#executor]
== 環境変数

<<env-vars#,環境変数>> は、プロジェクトで使用されるデータを保存します。 環境変数の閲覧や変更ができるのは、プロジェクトの管理者とオーナーのみです。

[#image]
== Executor

<<executor-intro#,Executor>> により、ジョブの実行の基盤テクノロジーが定義されます。 Docker コンテナ内で指定したイメージを使ってジョブを実行する `docker` か、完全にバーチャルなマシン内でジョブを実行する `machine` のどちらかになります。 ここで、Docker または Machine Executor を使用してジョブのコマンドが実行されます。 ご利用いただける CircleCI イメージとマシンイメージは、 https://circleci.com/developer/images[CircleCI Developer Hub] でご確認ください。

[#job-space]
== イメージ

イメージは、実行コンテナを作成するための指示を含むパッケージ化されたシステムです。

[#job]
== ジョブスペース

現在のジョブの <<#executor,Executor>> が実行するすべてのコンテナを指します。 各ジョブでは、Docker、マシン、Windows、macOS のいずれかの Executor を宣言する必要があります。

[#orbs]
== ジョブ

<<jobs-steps#,ジョブ>> は、必要に応じてコマンドやスクリプトを実行するステップの集まりです。 各ジョブでは、Docker、マシン、Windows、macOS のいずれかの Executor を宣言する必要があります。

[#owner]
== Orb

<<orb-concepts#,Orb>> は、再利用可能なコードスニペットです。Orb を使用すると、繰り返しのプロセスを自動化でき、手早くプロジェクトをセットアップできます。サードパーティ製ツールとの連携も容易になります。

[#pipeline]
== オーナー

チームの VCS 組織のオーナーを指します。 パイプラインには、ジョブを管理するワークフローが含まれます。 パイプラインはプロジェクトの '.circleci/config.yml.'  ファイルで定義されます。

[#primary-container]
== パイプライン

<<pipelines#,CircleCI パイプライン>> とは、プロジェクトで作業をトリガーする際に実行する一連のプロセスすべてを指します。 パイプラインには、ジョブを管理するワークフローが含まれます。

[#project-administrator]
== プライマリコンテナ

`.circleci/config.yml` で最初にリストされているイメージです。

[#project]
== プロジェクト管理者

VCS 内のリポジトリをプロジェクトとして CircleCI に追加するユーザーです。 プロジェクトは、 https://app.circleci.com/[CircleCI Web アプリ] の **Projects** のページに表示され、**Set Up Project** ボタンで追加されます。 プロジェクトが追加されたら、構成、コンテキスト、環境変数、そしてそのプロジェクトをフォローできるチームメンバーを設定できます。 プロジェクトをフォローすると、プロジェクトのビルドステータスに関するメール通知を受信し、CircleCI ダッシュボードにプロジェクトを追加できます。

[#remote-docker]
== プロジェクト

CircleCI プロジェクトは、ワークフロー、テスト、およびデプロイを自動化する対象のコードリポジトリの名前を共有します。 プロジェクトは、 https://app.circleci.com/[CircleCI Web アプリ] の **Projects** のページに表示され、**Set Up Project** ボタンで追加されます。

[#resource-class]
== リモート Docker

Docker レジストリへのイメージのビルド、実行、イメージのプッシュを、Docker <<#executor,Executor>> ジョブ内から実行できるようにする機能です。 詳細については、<<building-docker-images#,Docker コマンドの実行手順>> を参照してください。 詳細については、link:/docs/resource-class-overview[リソースクラスの概要] のページをご覧ください。

[#step]
== リソースクラス

ジョブのコンピューティングリソースのサイズを指定する設定オプションです。 セルフホストランナーのプールを識別し、ジョブがそのプールのセルフホストランナーで実行されるように設定するためのラベルとしても使用されます。

[#user]
== ステップ

ステップとは、実行可能なコマンドの集まりです。 詳細については、<<sample-config#,サンプル設定ファイル>> を参照してください。 関連する CircleCI プロジェクトを表示およびフォローするには、そのユーザーが VCS 組織に追加されている必要があります。 ユーザーは、環境変数に保存されているプロジェクトデータを表示することは **できません**。

[#workflow]
== ユーザー

組織内の個人ユーザーを指します。 CircleCI ユーザーとは、ユーザー名とパスワードを使用して CircleCI プラットフォームにログインできる人を指します。

[#workspace]
== ワークフロー

<<workflows#,ワークフロー>> は、ジョブのリストとその実行順序を定義します。 ジョブは、同時実行、順次実行、スケジュール実行、あるいは承認ジョブを使用した手動ゲートによる実行が可能です。