---
version:
- Server v2.x
- サーバー管理者
---
= インストールの概要
:page-layout: classic-docs
:page-liquid:
:page-description: Terraform を使って Amazon Web Services (AWS) 上に CircleCI Server v2.x をインストールするためのシステム要件と手順およびプラン情報
:icons: font
:toc: macro
:toc-title:

ここでは、Terraform を使って Amazon Web Services (AWS) 上に CircleCI Server v2.x をインストールするためのシステム要件と手順およびプラン情報について概説します。

Refer to the <<v.2.19-overview#, What's New>> page for full details of what's new and fixed in this release.

If you are looking to update an existing installation, see our guide to <<updating-server#upgrading-a-server-installation, Upgrading a Server Installation>>.

toc::[]

== サポート パッケージ

CircleCI server may be installed without a support package, on AWS, using the examples and instructions in this document. Alternatively, if you do decide to go ahead with a support package, there are a number of benefits, as detailed below:

=== Non-AWS Platform Support

With a Platinum CircleCI support package it is possible to install and configure CircleCI on Azure or any other platform used in your organization. まずは、https://support.circleci.com/hc/ja/requests/new[CircleCI サポート]またはお客様のアカウント担当者にお問い合わせください。

=== 外部処理化

With a Platinum support agreement, it is possible to improve performance and resilience by configuring the following services to run externally to the Services machine:

- PostgreSQL
- MongoDB
- Vault
- RabbitMQ
- Redis
- Nomad

Contact https://support.circleci.com/hc/en-us/requests/new[CircleCI support] or your account representative to evaluate your installation against the current requirements for running external services.
