---

version:
- Server v2.x
- サーバー管理者
---

= インストールガイド

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。
:page-layout: classic-docs
:page-liquid:
:page-description: This guide provides planning information, system requirements and step-by-step instructions for installing CircleCI server v2.x on Amazon Web Services (AWS) with Terraform.
:icons: font
:toc: macro

:toc-title:

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。

ここでは、Terraform を使って Amazon Web Services (AWS) 上に CircleCI Server v2.x をインストールするためのシステム要件と手順およびプラン情報について概説します。

Refer to the <<v.2.19-overview#,What's New>> page for full details of what's new and fixed in this release.

If you are looking to update an existing installation, see our guide to <<updating-server#upgrading-a-server-installation,Upgrading a Server Installation>>.

toc::[]

== サポートパッケージ

サポートパッケージ契約をしていなくても、本ドキュメントの例と指示に沿って AWS に CircleCI v2. をインストールすることは可能です。 しかし、サポートパッケージにお申し込みいただくと、下記のような数多くのメリットがあります。

=== AWS 以外のプラットフォームのサポート

Premium サポートパッケージでは、Azure などお客様の組織でお使いのすべてのプラットフォームに  CircleCI をインストールおよび設定することが可能です。 Contact https://support.circleci.com/hc/en-us/requests/new[CircleCI support] or your account representative to get started.

=== 外部処理化

Premium サポートをご契約いただくと、 下記サービスを Services マシンの外部で実行するように設定することで、パフォーマンスと復旧能力を向上させることができます。

- PostgreSQL
- MongoDB
- Vault
- RabbitMQ
- Redis
- [Nomad]

Contact https://support.circleci.com/hc/en-us/requests/new[CircleCI support] or your account representative to evaluate your installation against the current requirements for running external services.
