---
version:
- Server v2.x
- サーバー管理者
---

= インストールガイド
:page-layout: classic-docs
:page-liquid:
:page-description: ここでは、Terraform を使って Amazon Web Services (AWS) 上に CircleCI Server v2.x をインストールするためのシステム要件と手順およびプラン情報について概説します。
:icons: font
:toc: macro
:toc-title:

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。

ここでは、Terraform を使って Amazon Web Services (AWS) 上に CircleCI Server v2.x をインストールするためのシステム要件と手順およびプラン情報について概説します。

このリリースに関する詳細は、 <<v.2.19-overview#,What's New>> のページを参照してください。

インストール済み CircleCI Server の更新に関しては、 <<updating-server#upgrading-a-server-installation,CircleCI Server のアップグレード>> を参照してください。

toc::[]

== サポートパッケージ

サポートパッケージ契約をしていなくても、本ドキュメントの例と指示に沿って AWS に CircleCI v2. をインストールすることは可能です。 しかし、サポートパッケージにお申し込みいただくと、下記のような数多くのメリットがあります。

=== AWS 以外のプラットフォームのサポート

Premium サポートパッケージでは、Azure などお客様の組織でお使いのすべてのプラットフォームに  CircleCI をインストールおよび設定することが可能です。 まずは、 https://support.circleci.com/hc/ja/requests/new[CircleCI サポート] またはお客様のアカウント担当者にお問い合わせください。

=== 外部処理化

Premium サポートをご契約いただくと、 下記サービスを Services マシンの外部で実行するように設定することで、パフォーマンスと復旧能力を向上させることができます。

- PostgreSQL
- MongoDB
- Vault
- RabbitMQ
- Redis
- Nomad

https://support.circleci.com/hc/ja/requests/new[CircleCI サポート] またはお客様のアカウント担当者にお問い合わせいただき、お客様の CircleCI Server が外部サービスを実行するための最新要件を満たしているかをご確認ください。
