---

categories: [configuration]
redirect_from: /2.0/config-overview/
redirect_from: /2.0/writing-yaml/
version:
- クラウド
- Server v3.x
---
= YAML 設定ファイルの概要
:page-layout: classic-docs
:page-liquid:
:page-description: YAML で書かれた CircleCI 設定ファイルの概要
:icons: font
:toc: macro

:toc-title:

CircleCI とプロジェクトを接続する上で重要なのは、`.circleci` ディレクトリで実行される `config.yaml` ファイル (または `config.yml`) です。 CircleCI の設定ファイルは、人間が理解しやすいプログラミング言語用のデータシリアライズ形式である https://yaml.org/[YAML] で記述されています。 YAML は、JSON の厳密な上位版なので、JSON でできることはすべて YAML でもできます。 CircleCI YAML 設定ファイルは、大半がキーと値のペアとネストされたキーと値のペアで構成されます。

最もベーシックな設定ファイルには、CircleCI のバージョン、実行環境、実行するジョブを記述する必要があります。

[#circleci-version]
== CircleCI のバージョン

`.circleci/config.yaml` ファイルには、まず任意の CircleCI のバージョンを記載します。 クラウド版 CircleCI や新しいバージョンのサーバーは、CircleCI `2.1` を使用する必要があります。

```yaml
# CircleCI configuration file

version: 2.1
```

CAUTION: `version: 2.0` を使用したサンプルが記載されている場合がありますが、 CircleCI `2.0` のサポートは既に終了しており、旧版の CircleCI Server、<<install-overview#,Server v2>> でのみ使用されています。

[#execution-environment]
== 実行環境

次に、実行するジョブとそのジョブを実行する実行環境を設定ファイルに記述する必要があります。 CircleCI は下記の実行環境をサポートしています。

- Docker
- Linux VM (仮想マシン)
- macOS
- Windows
- GPU
- Arm

設定ファイルの実行環境ごとに制限があります。 <<executor-intro#,実行環境の概要>> のページを参照して、各実行環境に関する幅広い情報をご確認ください。

下記の `.circleci/config.yaml` では、Docker 実行環境をジョブ `build` に追加します。

```yaml
# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/base:2022.05
```

`jobs` は、新しいコンテナまたは仮想マシン内で 1 単位として実行される step の集まりです。 このサンプルでは、`jobs` が Docker コンテナ内にビルドされています。このコンテナは、ネストされたキーペアを使用して設定ファイル内に設定されています。 `docker` により、ビルド済み CircleCI Docker イメージ、 `cimg/base` (Ubuntu Docker イメージ) を呼び出します。 このサンプルのイメージには、Docker と CircleCI のビルドのオペレーションに必要な最低限のツールが含まれています。

イメージは、Docker または Machine Executor のいずれかが使用します。 サンプルでは、Ubuntu 環境をスピンアップする Docker **CircleCI イメージ** を使用しています。 macOS を実行環境として使用した場合は、代わりに **machine image** を使用できます。これにより、下記サンプルのように Xcode がプリインストールされた専用の仮想マシンがスピンアップされます。

```yaml
# CircleCI configuration file
version: 2.1

jobs:
  build:
    macos:
      xcode: 13.3.0
```

キーと値のペアが同じ構文をフォローしていないことにご注意ください。 各実行環境の設定は少しづつ異なります。 実行環境に関するドキュメントを参照するか、CircleCI Developer Hub で https://circleci.com/developer/images?imageType=docker[CircleCI イメージ] や https://circleci.com/developer/images?imageType=machine[マシンイメージ]、その構文をご覧ください。

Developer Hub にはご利用いただける CircleCI https://circleci.com/developer/ja/orbs[Orb] のリストがあります。 Orb は、共有可能な設定パッケージで、ビルドを簡易化するためにご使用いただけます。 <<slack-orb-tutorial#,Slack Orb のチュートリアル>> のページを参照し、最も頻繁に使用されている Orb を設定する方法をご確認下さい。

[#circleci-jobs]
== CircleCI ジョブとワークフロー

最後に、ベーシックな CircleCI 設定ファイルに必要なものは、実際に実行するジョブです。 ジョブは、ワークフローを使ってオーケストレーションされます。ワークフローとは、一連のジョブと実行順序を定義するルールです。 Docker 設定ファイルのサンプルを使って、ジョブにステップを追加できます。 ステップとは Docker コンテナ内で実行するコマンドのリストです。

```yaml
# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
        - run: echo "Say hello to YAML!"
```

この非常にベーシックなサンプルでは、1 つのジョブ、`build` のみを実行しており、つまりバックグラウンドでも 1 つのワークフローのみが実行されているということを意味します。 If a second job is added, `workflows` will need to be defined explicitly, to orchestrate the run order. Job names can be updated to reflect the job when `workflows` is added. If there is only one job defined, the job must be named `build`, as in the example above.

A second job, and `workflows` defining run order, is shown in the example below.

```yaml
# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"
  # Job two with a unique name
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye
```

If you have a CircleCI account, you can create a new project and add these examples to a `.circleci/config.yaml` file. You can see the strings printed out in the job's build pipeline in the CircleCI web UI.

YAML can be quite picky about indentations. You can use a http://yaml-online-parser.appspot.com/[YAML checker] to parse your YAML and make sure it is valid.

If you would like a more complex configuration tutorial, visit the <<config-intro#,Configuration Tutorial>> page. Before starting this tutorial, you should already have a CircleCI account set up, as you will follow along in the CircleCI web UI. You can also find a variety of configuration examples on the <<sample-config#, Sample Configuration>> page.

[#fun-with-yaml]
== Fun with YAML

Below are some fun examples of other YAML syntax that might become handy as you create more complex configuration files.

[#multi-line-strings]
=== 複数行の文字列

If the value is a multi-line string, use the `>` character, followed by any number of lines. 長いコマンドを記述する場合に特に便利です。

```yaml
haiku: >
  Please consider me
  As one who loved poetry
  Oh, and persimmons.
```

**Note**: Quotes are not necessary when using multiline strings.

[#sequences]
=== シーケンス

Keys and values are not restricted to https://softwareengineering.stackexchange.com/questions/238033/what-does-it-mean-when-data-is-scalar[scalars]. スカラーをシーケンスにマップすることもできます。

```yaml
scalar:
  - never
  - gonna
  - give
  - you
  - up
```

シーケンス内の項目をキー・値のペアで記述することもできます。

```yaml
simulation:
  - within: "a simulation"
  - without:
      a_glitch: "in the matrix"
```

**Note**: Remember to properly indent a key-value pair when it is the value of an item in a sequence.

[#anchors-and-aliases]
=== アンカーとエイリアス

To https://en.wikipedia.org/wiki/Don%27t_repeat_yourself[DRY] up your `.circleci/config.yaml`, use anchors and aliases. Anchors are identified by an `&` character, and aliases by an `*` character.

```yaml
song:
  - &name Al
  - You
  - can
  - call
  - me
  - *name
```

上記のリストを YAML パーサーで読み取ると、次のようなリテラル出力が得られます。

```yaml
song:
  - Al
  - You
  - can
  - call
  - me
  - Al
```

[#merging-maps]
=== マップのマージ

Anchors and aliases work for scalar values, but to save maps or sequences, use `<<` to inject the alias.

```yaml
default: &default
  school: hogwarts

harry:
  <<: *default
  house: gryffindor

draco:
  <<: *default
  house: slytherin
```

複数のマップをマージすることもできます。

```yaml
name: &harry_name
  first_name: Harry
  last_name: Potter

address: &harry_address
  street: 4, Privet Drive
  district: Little Whinging
  county: Surrey
  country: England

harry_data:
  <<: [*harry_name, *harry_address]
```

**Note**: As mentioned in https://github.com/yaml/yaml/issues/35[a YAML repository issue], it is possible to merge maps, but not sequences (also called arrays or lists). For a more complex example, see https://gist.github.com/bowsersenior/979804[this gist].