---

version:
- クラウド
- Server 3.x
---
= TeamCity からの移行
:page-layout: classic-docs
:page-liquid:
:description: TeamCity から CircleCI に移行する方法を解説します。
:source-highlighter: pygments.rb
:icons: font
:toc: macro

:toc-title:

このドキュメントでは、TeamCity から CircleCI に移行する方法を概説します。

[#quick-start]
== クイックスタート

CircleCI と TeamCity ではセットアップや設定が様々な点で異なります。 CircleCI をより快適にお試しいただくために、まず以下の内容を行うことをお勧めします。

. **このドキュメントを読んで（少なくとも閲覧して）**、コンセプトの違いを明確にしてください。
. **Quickly build and run a simple https://circleci.com/docs/hello-world/#section=getting-started[Hello World job] in any repository**. この設定により、YAMLセットアップのシンプルさ、実行環境とその中で実行するステップの両方を定義する方法が分かります。 CircleCI のすべてのジョブは、このフォーマットを共有しています。
. **Once you understand the config, modify the executor and the individual steps to meet your needs.** For example, a https://circleci.com/docs/language-ruby/[Rails project] may use a Ruby container image and run `bundler` commands. Consult our <<examples-and-guides-overview#,Examples and Guides Overview>> for various examples in different languages and frameworks.
. **After finishing one job, setup your other jobs on CircleCI and then https://circleci.com/docs/workflows/[configure a workflow]**. これにより、ビルド チェーンを実質的に移行します。
. **Next, https://circleci.com/docs/optimizations/[optimize your jobs] with advanced features** to see how much faster your builds could run on the CircleCI platform.
. **Throughout this process, consult the https://circleci.com/docs/configuration-reference/#section=configuration[Configuration Reference]** for a list of all available configuration on the CircleCI platform.

[#why-migrate-to-circleci]
== CircleCI に移行する理由

CircleCI は、パフォーマンスと開発者の生産性の向上のために開発された最新の CI/CD ツールです。 With a flexible system for configuration, you can define complex workflows and jobs for your application's specific needs.

**Configuration As Code**:: The majority of CircleCI's configuration is done via YAML. メンテナンスが容易で、習得も簡単ですし、CI/CD パイプラインを他のソースコードと同様に追跡することが可能です。
**Auto-Scaling Architecture**:: すべての実行環境は、設定に応じて動的に作成され、タスクの完了時に終了します。 1つのジョブから数百のジョブまで、手間や追加費用をかけずに同時に実行することができます。
**Flexibility**:: CircleCIはベンダーやツールを選びません。 CircleCI の設定では、API を持つあらゆるプラットフォームやクラウドプロバイダーとの統合が可能です。 See our https://circleci.com/integrations/[integrations page] for existing partnerships. Dependencies and libraries can be installed ad-hoc in your job, and we offer https://circleci.com/docs/caching/[dependency caching] to speed up subsequent builds.
**Shareable, Reusable Configuration**:: Steps, execution environments, and jobs can be templated, parameterized, shared, and reused across different projects and teams using https://circleci.com/docs/orb-intro/#section=configuration[CircleCI orbs]. Take advantage of the https://circleci.com/developer/orbs[numerous integrations and orbs] already written for you.

その他にも、CircleCI ソリューションを特徴づける様々な機能があります。 https://circleci.com/signup/[Sign up for a free account today] and try us out, or if you are interested in CircleCI for your team, https://circleci.com/talk-to-us/?source-button=MigratingFromGithubActionsDoc[contact our sales team] to set up a trial.

[#concepts]
== コンセプト

[#high-level-differences]
=== ハイレベルな相違点

* CircleCIとTeamCityは、プロジェクトのコンセプトを共有しています。
* TeamCity's Build Configurations are equivalent to https://circleci.com/docs/concepts/#jobs[CircleCI's jobs], which are atomic elements of work consisting of many steps or commands to achieve a goal (e.g. run unit tests).
* TeamCity は伝統的にほとんどのビルドの設定に UI を使用してきました。 Kotlin Script による設定は最近の新しい機能です。 CircleCI では、パイプライン機能の設定の大部分で YAML を使用しています。

[.table.table-striped.table-migrating-page.table-no-background]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
|TeamCity _settings.kts_ |Equivalent CircleCI _config.yml_

a|[source, kotlin]
----
import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script

version: "2019.2"

project {
  buildType(HelloWorld)
}

object HelloWorld: BuildType({
  name = "Hello World"
  steps {
    script {
      scriptContent = "echo 'Hello World!'"
    }
  }
})
----
|[source, yaml]
----
version: 2.1
workflows:
  hello-workflow:
    jobs:
      - hello-job

jobs:
  # ジョブを定義します。
  hello-job:
    # 環境を定義します。
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照

    # ジョブのステップを定義します。
    steps:
      - checkout
      - run: echo "Hello World!"
----
|===

[.table.table-striped.cf.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|TeamCity _settings.kts_

a|[source, kotlin]
----
import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script

version: "2019.2"

project {
  buildType(HelloWorld)
}

object HelloWorld: BuildType({
  name = "Hello World"
  steps {
    script {
      scriptContent = "echo 'Hello World!'"
    }
  }
})
----
|===

[.table.table-striped.cf.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|Equivalent CircleCI _config.yml_

a|[source, yaml]
----
version: 2.1
workflows:
  hello-workflow:
    jobs:
      - hello-job

jobs:
  # ジョブを定義します。
  hello-job:
    # 環境を定義します。
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照

    # ジョブのステップを定義します。
    steps:
      - checkout
      - run: echo "Hello World!"
----
|===

* Instead of Build Chains, CircleCI has https://circleci.com/docs/workflows/[Workflows], which define dependencies and flow between jobs.
* A https://circleci.com/docs/pipelines/[Pipeline] refers to all configuration, workflows, and jobs for a project. このマルチレイヤー構造により、強力な柔軟性と異なるワークロードに対する懸念の分離を可能にします。

[.table.table-striped.table-migrating-page.table-no-background]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
|TeamCityのビルドチェーン |同等の CircleCI のワークフロー

a|[source, kotlin]
----
project {
  sequence {
    build(Compile)
    parallel {
        build(Test1)
        build(Test2)
    }
    build(Package)
    build(Publish)
  }
}

/* BuildType definitions assumed
----
|[source, yaml]
----
version: 2.1
workflows:
  build-deploy:
    jobs:
      - Compile
      - Test1:
          requires:
            - Compile
      - Test2:
          requires:
            - Compile
      - Package:
          requires:
            - Test1
            - Test2
      - Publish:
          requires:
            - Package

# 想定されるジョブの定義
----
|===

[.table.table-striped.cf.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|TeamCityのビルドチェーン

a|[source, kotlin]
----
project {
  sequence {
    build(Compile)
    parallel {
        build(Test1)
        build(Test2)
    }
    build(Package)
    build(Publish)
  }
}

/* BuildType definitions assumed

----
|===

[.table.table-striped.cf.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|同等の CircleCI のワークフロー

a|[source, yaml]
----
version: 2.1
workflows:
  build-deploy:
    jobs:
      - Compile
      - Test1:
          requires:
            - Compile
      - Test2:
          requires:
            - Compile
      - Package:
          requires:
            - Test1
            - Test2
      - Publish:
          requires:
            - Package

# 想定されるジョブの定義
----
|===

For more information on CircleCI Concepts, visit our https://circleci.com/docs/concepts/[Concepts] and https://circleci.com/docs/pipelines/#section=pipelines[Pipelines] documentation pages.

== 設定ファイル

=== 環境

TeamCity では、必要なOSとツールがインストールされたビルドエージェントと、それに対応するビルド設定をセットアップする必要があります。 CircleCI では、すべてのジョブ設定に Executor が定義されており、CircleCI がそのエージェントのスピンアップを代行します。 See our list of https://circleci.com/docs/executor-intro/[available executors].

..circleci/config.yml
[source,yaml]
----
version: 2.1
jobs:
  my-mac-job:
    # Executor の定義
    macos:
      xcode: "12.5.1"

    # ステップの定義
    steps:
      - checkout
      # ...など
----

=== 手順

TeamCity では、定義されたランナータイプ（Visual Studio、Maven、Gradleなど）のリストからビルドステップを選択します。 CircleCI では、ステップの定義では、ターミナルやコマンド プロンプトで実行するコマンドを柔軟に取り入れることができます。

また、この柔軟性により、あらゆる言語、フレームワーク、ツールに対応したステップが可能になります。 For example, a https://circleci.com/docs/language-ruby/[Rails project] may use a Ruby container and run `bundler` commands. A https://circleci.com/docs/language-javascript/[Node.js project] may use a node container and `npm` commands. Visit our <<examples-and-guides-overview#,Examples and Guides Overview>> for various language and framework examples.

[.table.table-striped.table-migrating-page.table-no-background]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
|TeamCityのステップ |同等の CircleCI のステップ

a|[source, kotlin]
----
project {
  parallel {
    build(Gradle) # Assume agent configured
    build(Maven)  # Assume agent configured
  }
}

object Gradle: BuildType({
  name = "Gradle"

  steps {
    gradle {
      tasks = "clean build"
    }
  }
})

object Maven: BuildType({
  name = "Maven"

  steps {
    maven {
      goals = "clean package"
    }
  }
})
----
|[source, yaml]
----
version: 2.1
workflows:
  parallel-workflow:
    jobs:
      - Gradle
      - Maven

jobs:
  Gradle:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します
    steps:
      - checkout # ソースコードをチェックアウトします
      - run:
          name: Clean and Build
          command: ./gradlew clean build

  Maven:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します
    steps:
      - checkout # ソースコードをチェックアウトします
      - run:
          name: Clean and Package
          command: mvn clean package
----
|===

[.table.table-striped.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|TeamCityのステップ

a|[source, kotlin]
----
project {
  parallel {
    build(Gradle) # Assume agent configured
    build(Maven)  # Assume agent configured
  }
}

object Gradle: BuildType({
  name = "Gradle"

  steps {
    gradle {
      tasks = "clean build"
    }
  }
})

object Maven: BuildType({
  name = "Maven"

  steps {
    maven {
      goals = "clean package"
    }
  }
})
----
|===

[.table.table-striped.table-migrate-mobile]
[cols=1*, options="header", stripes=even]
[cols="100%"]
|===
|同等の CircleCI のステップ

a|[source, yaml]
----
version: 2.1
workflows:
  parallel-workflow:
    jobs:
      - Gradle
      - Maven

jobs:
  Gradle:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します
    steps:
      - checkout # ソースコードをチェックアウトします
      - run:
          name: Clean and Build
          command: ./gradlew clean build

  Maven:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します
    steps:
      - checkout # ソースコードをチェックアウトします
      - run:
          name: Clean and Package
          command: mvn clean package
----
|===

[#build-templates-meta-runners]
=== ビルド済みのテンプレート/メタランナー

CircleCI's equivalent of Meta-Runners and Build Templates is orbs, which are templatizable, shareable configuration. Read more about them in our https://circleci.com/docs/orb-intro/#section=configuration[orbs documentation].

[#complex-builds]
=== 複雑なビルド

より大規模で複雑なビルドについては、CircleCI のプラットフォームに慣れるまで、段階的に移行することをお勧めします。 以下の順番での移行をお勧めします。

. シェルスクリプトや Docker-compose ファイルの実行
. https://circleci.com/docs/ja/workflows/[ワークフロー]
. https://circleci.com/docs/ja/artifacts/[アーティファクト]
. https://circleci.com/docs/ja/caching/[キャッシュ]
. https://circleci.com/docs/ja/triggers/#section=jobs[トリガー]
. https://circleci.com/docs/ja/optimizations/#section=projects[パフォーマンスオプション]

[#resources]
=== 関連資料

* For more configuration examples on CircleCI, visit our https://circleci.com/docs/example-configs/#section=configuration[Example Projects] page.
* For support, submit a ticket to our https://support.circleci.com/hc/en-us[Support Forum].