---

version:
- クラウド
- Server v3.x
- Server v2.x
---
= CircleCI への移行
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CI/CD パイプラインを CircleCI に移行するために必要な手順を概説します。
:icons: font
:toc: macro

:toc-title:

移行プロセスを開始する前に、CircleCI の基本的な仕組みを理解しておくと便利です。

以下の資料を参考にしてください。

- https://circleci.com/continuous-integration/[継続的インテグレーションの基礎]

- <<concepts#,CircleCI のコンセプト>>
- <<hello-world#,CircleCI の Hello World>>
- <<getting-started#,各手順のチュートリアル>>

- <<about-circleci#,CircleCI について>>

CircleCI Academy の https://academy.circleci.com/arm-course?access_code=public-2021[移行コース]を受講すると、CircleCI への移行についてさらに詳しく学ぶことができます。

NOTE: Premium サポートや Advanced サポートをご利用のお客様は、customersuccess@circleci.com にアクセスし、ガントチャートやカスタムトレーニングなどを含む、よりカスタマイズされた移行プランをご確認ください。

[#project-migration-methodology]
== プロジェクトの移行方法

プロジェクトの CircleCI への移行は下記のように段階的に実行できます。これについては後ほど詳しく説明します。

- <<assessment-phase>>
- <<planning-phase>>

- <<preparation-phase>>
- <<testing-phase>>
- <<migration-phase>>

[#migration-timelines]
=== 移行までの時間

少数のスクリプトやテストの実行のみが必要なシンプルなプロジェクトを移行する場合、概算で以下の時間がかかります。

- プロジェクト 1 個 < 1 週間
- プロジェクト 5 個< 〜 3 週間
- プロジェクト 10 個:〜 1 ヶ月


大規模なテストスイートの移行や大きなワークフローが含まれる複雑なプロジェクトでは、すべての段階が完了するまでに概算で以下の時間がかかります。

- プロジェクト 1 個< 〜 5 週間
- プロジェクト 5 個:〜 4 ヶ月

- プロジェクト 10 個:〜 9 ヶ月以上


[#assessment-phase]
== 評価段階

現在の状況を把握し、CircleCI の機能と現在の CI ツールの機能の違いを理解します。

この段階における検討事項:

- 例えば、Jenkins プラグインの代わりに <<orbs-intro,#Orb>> 
- CircleCI YAML <<configuration-reference#,設定のリファレンス>>
- <<executor-intro#,実行環境>>

- <<collect-test-data#,テスト>>

[#planning-phase]
== 計画段階

バージョン管理システム (VCS) の組織が CircleCI アカウントとリンクされており、プランが適用されていることを確認して下さい。 <<first-steps#,CircleCI への登録と使用>> に記載されている  VCS 認証情報を使ってログインします。

サーバー製品をご使用の場合は、トライアルライセンスが提供されていること、および https://circleci.com/docs/ja/2.0/server-3-install-prerequisites/[こちら]の説明に従ってすべての前提条件が満たされていることを確認してください。

[#preparation-phase]
== 準備段階

[#prep-your-team]
=== チームの準備

計画と予定されるスケジュールが決まったら、関係者や影響を受けるチームに移行の詳細を通知します。これにより、ユーザーは作業の中断を最小限に留めてスムーズに開始できます。 チームが通知を受けて変更に備えられるよう、いつ、どのくらいの頻度で更新を通知するかの通知スケジュールを設定することを推奨します。

[#build-your-runbook-and-timeline]
=== 実行手順とスケジュールの作成

実行手順や各手順のチェックリストを作成し、以下について説明します。

* 何をいつ行う必要があるか
* Supporting instructions
* 各タスクのオーナーのリスト
* 各手順の所要時間

どの手順が互いに依存し、どの手順がブロッカーになる可能性があるかを文書化します。 実行手順の最後に、ロールバックが必要な場合に備えて、オーナーと一緒にリスク低減プランを含めます。

[#testing-phase]
== テスト段階

この段階では以下を行います。

* テスト実行し、すべて順調であることを確認します。
* 移行にかかる時間を把握します。
* 本番環境への移行の前に問題を明らかにします。

[#test-migration]
=== テスト移行

Do a migration of a smaller, non-mission-critical project as a first step to minimize impact and build confidence in the migration process.

[#user-acceptance-testing]
=== User acceptance testing

Part of the test migration is conducting User Acceptance Testing (UAT) so your end users can ensure that the project works on CircleCI as expected. Through this process you can uncover any issues that will impact your end users and help your teams prepare to work with CircleCI.

[#communicate-your-plan]
=== Communicate your plan

With final timelines and owners in place, communicate the official plan to your organization. Things to include in your communications are:

- When the migration will occur
- Details of downtime users can expect
- Ask end users to avoid changing anything during the transition
- Detail what will happen to the current CI solution after migrating, for example, will it still be accessible or readable?
- Details of what CircleCI onboarding materials are available

Keep in mind that there may be issues that occur during the migration that you need to troubleshoot, so call out an adjustment period to your end users to get everything cleaned up and working as planned.

[#migration-phase]
== 移行段階

In this phase you will resolve any last-minute issues, run your project migration, and move your users and data over to CircleCI. Be sure you have completed the plan, prep and test phases before beginning this phase.

[#next-steps]
== 次のステップ

以下の各ドキュメントでは、CI/CD パイプラインの CircleCI への移行で役立つガイドやヒントを紹介しています。

* <<migrating-from-aws#,Migrating from AWS>>
* <<migrating-from-azuredevops#,Migrating from Azure DevOps>>
* <<migrating-from-buildkite#,Migrating from Buildkite>>
* <<migrating-from-gitlab#,Migrating from GitLab>>
* <<migrating-from-github#,Migrating from Github Actions>>
* <<migrating-from-jenkins#,Migrating from Jenkins>> (You may also find the <<jenkins-converter#,CircleCI Jenkins Converter guide>> helpful)
* <<migrating-from-teamcity#,Migrating from TeamCity>>
* <<migrating-from-travis#,Migrating from Travis CI>>