---
version:
- クラウド
- Server 3.x
---
= Azure DevOps からの移行
:page-layout: classic-docs
:page-liquid:
:page-description: Azure DevOps から CircleCI への移行方法について解説します。
:icons: font
:toc: macro
:toc-title:

このドキュメントでは、Azure DevOps から CircleCI に移行する方法を概説します。

NOTE: **ImagineX Consulting からのヒント**

[#source-control-setup]
== ソースコントロールの設定
Azure DevOps のGit レポジトリや TFVC レポジトリを使用している場合は、まずソースコードを GitHub または BitBucket に移行する必要があります。 Azure DevOps の Git リポジトリについては、下記のリンクより GitHub や BitBucket にインポートする方法をご確認ください。

* https://help.github.com/en/articles/importing-a-repository-with-github-importer[GitHub]
* https://help.github.com/en/articles/importing-a-repository-with-github-importer[Bitbucket]

TFVC リポジトリの場合は、git-tfs ツールの使用をお勧めします。 以下は git-tfs ツールおよび使用方法へのリンクです。

* https://github.com/git-tfs/git-tfs[git-tfs 移行ツール]
* https://github.com/git-tfs/git-tfs/blob/master/doc/usecases/migrate_tfs_to_git.md[git-tfs を使った移行手順]

[#github-enterprise]
=== GitHub Enterprise

以下は、GitHub のコマンドラインツールを使って GitHub Enterprise にコードをインポートするための手順です。

. GitHub Enterprise のインスタンスに空のリポジトリを作成します。
. Create a bare clone of your external repository on your local machine, fetching all remote tags (refs/tags/\*) and copying all remote branch heads (refs/heads/\*) directly to their corresponding local branch heads.
+
```shell
git clone https://external-host.com/extuser/repo.git --bare
```
. ローカルクローンに、GitHub Enterprise リポジトリをリモートリファレンスとして追加します。
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. すべてのローカルリファレンス（refs/*）を、リモートの GitHub Enterprise リポジトリにプッシュします。
+
```shell
git push enterprise --mirror
```

他の Azure DevOps のアーティファクトをエクスポートする必要がある場合は、ほぼすべてのデータを Excel のスプレッドシートにダウンロードすることができます。 https://docs.microsoft.com/en-us/azure/devops/organizations/projects/save-project-data?view=azure-devops[プロジェクト データ]に関する Azure DevOps のドキュメントをご覧ください。

コードを GitHub または BitBucket にインポートしたら、 https://circleci.com/docs/getting-started/[入門ガイド]に従って CircleCI 上でのプロジェクト作成を開始することができます。

[#build-configuration]
== ビルドの設定

Azure DevOps Pipelines や TFS Build and Release を使用している場合は、ビルドの設定を移行する必要があります。 Azure DevOps Pipelines では、ソースコードリポジトリのルートディレクトリにある `azure-pipelines.yml` というファイルでビルド設定が定義されています。 TFS Build and Release の場合は Web インターフェイスで行われ、json ファイルにエクスポートすることができます。 どちらの場合もビルドの実行にシェルスクリプトを使用していれば、CircleCI でそのスクリプトを再利用することができます。

まず、CircleCI のビルド設定ファイルを作成します。 ソースコードリポジトリのルートディレクトリに、`.circleci` というフォルダを作成し、その中に`config.yml`という名前のファイルを作成します。 次に、こちらの CircleCI のドキュメントに沿って、`.config.yml` ファイルの設定方法を確認します。

Azure DevOps Pipelines と CircleCI の設定は異なります。 ビルドステップを変換する際は、Azure DevOps と CircleCI の両方のリファレンスドキュメントを並べて開いておくことをお勧めします。

* https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema[Azure DevOps YML のリファレンスドキュメント]

* https://circleci.com/docs/configuration-reference/[CircleCI YML のリファレンスドキュメント]

[#configuration-comparison]
== 設定の比較

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
| Azure DevOps | CircleCI

2+| 1つのビルドステップを実行するジョブの定義

a|
[source, yaml]
----
jobs:
  - job: job1
    steps:
      - script: chmod +x ./script.sh
      - script: ./script.sh
----

a|
[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"

----

2+| ジョブに使用する Docker イメージの指定

a|
[source, yaml]
----
jobs:
  - job: job1
    container:
      image: node:10
----

a|
[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します。
----

2+| マルチステージのビルドパイプラインの定義: ジョブ 1 と ジョブ 2 を同時に実行します。 完了すると、ジョブ 3 を実行します。 ジョブ 3 が完了すると、ジョブ 4 を実行します。

a|
[source, yaml]
----
stages:
  - stage: build
    jobs:
    - job: job1
      steps:
        - script: make build dependencies
    - job: job2
      steps:
        - script: make build artifacts
  - stage: test
    jobs:
    - job: job3
      steps:
        - script: make test
  - stage: deploy
    jobs:
    - job: job4
      steps:
        - script: make deploy
----

a|
[source, yaml]
----
version: 2
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  version: 2
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----

2+| マルチプラットフォームでのジョブの実行:  Azure DevOps では、プールと要求によりビルドランナーを識別します。 CircleCI では、Docker、Linux、MacOS用の Executor を提供しています。

a|
[source, yaml]
----
jobs:
  - job: ubuntuJob
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: echo "Hello, $USER!"
  - job: osxJob
    pool:
      vmImage: macOS-10.14
    steps:
      - script: echo "Hello, $USER!"


----

a|
[source, yaml]
----
jobs:
  ubuntuJob:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osxJob:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----
|===

より大規模で複雑なビルドについては、CircleCI のプラットフォームに慣れるまで、段階的に移行することをお勧めします。 以下の順番での移行をお勧めします。

. シェルスクリプトやDocker-composeファイルの実行
. https://circleci.com/docs/workflows/[ワークフロー]
. https://circleci.com/docs/artifacts/[アーティファクト]
. https://circleci.com/docs/caching/[キャッシュ]
. https://circleci.com/docs/triggers/#section=jobs[トリガー]
. https://circleci.com/docs/optimizations/#section=projects[パフォーマンス オプション]
