---

version:
- クラウド
- Server v3.x
- Server v2.x
---
= CircleCI への移行
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CI/CD パイプラインを CircleCI に移行するために必要な手順を概説します。
:icons: font
:toc: macro

:toc-title:

移行プロセスを開始する前に、CircleCI の基本的な仕組みを理解しておくと便利です。

以下の資料を参考にしてください。

- https://circleci.com/continuous-integration/[継続的インテグレーションの基礎]

- <<concepts#,CircleCI のコンセプト>>
- <<hello-world#,CircleCI の Hello World>>
- <<getting-started#,各手順のチュートリアル>>

- <<about-circleci#,CircleCI について>>

CircleCI Academy の https://academy.circleci.com/arm-course?access_code=public-2021[移行コース]を受講すると、CircleCI への移行についてさらに詳しく学ぶことができます。

NOTE: Premium サポートや Advanced サポートをご利用のお客様は、customersuccess@circleci.com にアクセスし、ガントチャートやカスタムトレーニングなどを含む、よりカスタマイズされた移行プランをご確認ください。

[#project-migration-methodology]
== プロジェクトの移行方法

Projects can be migrated to CircleCI using the following phases, which are expanded upon in the sections below:

- <<assessment-phase>>
- <<planning-phase>>
- <<preparation-phase>>
- <<testing-phase>>
- <<migration-phase>>

[#migration-timelines]
=== Migration timelines

If you are migrating a simple project in which you just need to run a few scripts and tests, the timeline would be roughly:

- 1 project: < 1 week
- 5 projects: ~3 weeks
- 10 projects: ~1 month

For complex projects with a large-scale test suite migration and large workflows, the migration timeline for completing all phases would be roughly:

- 1 project: ~5 weeks
- 5 projects: ~4 months
- 10 projects: ~9 months+

[#assessment-phase]
== Assessment phase

Take stock of the current landscape, and understand the differences between CircleCI functionality and that of your current CI tool.

Some things consider during this phase:

- <<orbs-intro,#Orbs>> as an alternative to, for example, Jenkins Plugins
- CircleCI YAML <<configuration-reference#,Configuration Reference>>
- <<executor-intro#,Execution Environments>>
- <<collect-test-data#,Testing>>

[#planning-phase]
== Planning phase

Ensure that your VCS org is linked to your CircleCI account and that your plan is applied. Log in using your VCS credentials as described on the <<first-steps#,Sign Up and Try CircleCI>> page.

If using the Server product, ensure that you have been provided with your trial license and that all prerequisites are met as described https://circleci.com/docs/2.0/server-3-install-prerequisites/[here].

[#preparation-phase]
== Preparation phase

[#prep-your-team]
=== Prep your team

With your plan and estimated timelines in place, start socializing the details of your migration with stakeholders, and teams who will be impacted, so your users can get started smoothly with minimal disruption to their work. It is best to establish a communications cadence for when, and how often, you will be communicating updates so teams are informed and prepared for the change.

[#build-your-runbook-and-timeline]
=== Build your runbook and timeline

Put together a runbook or step-by-step checklist to cover:

* What needs to happen when
* Supporting instructions
* List of owners for each task
* How long each step will take

Document which steps are dependent on each other, and which have the potential to become blockers. At the end of your runbook, include a mitigation plan with owners in case you need to roll anything back.

[#testing-phase]
== Testing phase

In this phase you will:

* Do a test run and make sure everything is in order
* Figure out how long the migration will take
* Uncover any issues before the production migration

[#test-migration]
=== Test migration

Do a migration of a smaller, non-mission-critical project as a first step to minimize impact and build confidence in the migration process.

[#user-acceptance-testing]
=== User acceptance testing

Part of the test migration is conducting User Acceptance Testing (UAT) so your end users can ensure that the project works on CircleCI as expected. Through this process you can uncover any issues that will impact your end users and help your teams prepare to work with CircleCI.

[#communicate-your-plan]
=== Communicate your plan

With final timelines and owners in place, communicate the official plan to your organization. Things to include in your communications are:

- When the migration will occur
- Details of downtime users can expect
- Ask end users to avoid changing anything during the transition
- Detail what will happen to the current CI solution after migrating, for example, will it still be accessible or readable?
- Details of what CircleCI onboarding materials are available

Keep in mind that there may be issues that occur during the migration that you need to troubleshoot, so call out an adjustment period to your end users to get everything cleaned up and working as planned.

[#migration-phase]
== Migration phase

In this phase you will resolve any last-minute issues, run your project migration, and move your users and data over to CircleCI. Be sure you have completed the plan, prep and test phases before beginning this phase.

[#next-steps]
== 次のステップ

以下の各ドキュメントでは、CI/CD パイプラインの CircleCI への移行で役立つガイドやヒントを紹介しています。

* <<migrating-from-aws#,Migrating from AWS>>
* <<migrating-from-azuredevops#,Migrating from Azure DevOps>>
* <<migrating-from-buildkite#,Migrating from Buildkite>>
* <<migrating-from-gitlab#,Migrating from GitLab>>
* <<migrating-from-github#,Migrating from Github Actions>>
* <<migrating-from-jenkins#,Migrating from Jenkins>> (You may also find the <<jenkins-converter#,CircleCI Jenkins Converter guide>> helpful)
* <<migrating-from-teamcity#,Migrating from TeamCity>>
* <<migrating-from-travis#,Migrating from Travis CI>>