---
version:
- Cloud
- Server 3.x
---
= Migrate from Buildkite
:page-layout: classic-docs
:page-liquid:
:page-description: An overview of how to migrate from Buildkite to CircleCI.
:icons: font
:toc: macro
:toc-title:

このドキュメントでは、Buildkite から CircleCI に移行する方法を概説します。

NOTE: **ImagineX Consulting からのヒント**

[#source-control-setup]
== ソースコントロールの設定
まず、ソースコードが GitHub または BitBucket に置かれていることを確認してください。 コードのインポート方法の詳細については、以下をご参照ください。

* https://help.github.com/en/articles/importing-a-repository-with-github-importer[GitHub]
* https://help.github.com/en/articles/importing-a-repository-with-github-importer[Bitbucket]

[#github-enterprise]
=== GitHub Enterprise

以下は、GitHub のコマンドラインツールを使って GitHub Enterprise にコードをインポートするための手順です。

. GitHub Enterprise のインスタンスに空のリポジトリを作成します。
. Create a bare clone of your external repository on your local machine, fetching all remote tags (refs/tags/\*) and copying all remote branch heads (refs/heads/\*) directly to their corresponding local branch heads.
+
```shell
git clone https://external-host.com/extuser/repo.git --bare
```
. ローカルクローンに、GitHub Enterprise リポジトリをリモートリファレンスとして追加します。
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. すべてのローカルリファレンス（refs/*）を、リモートの GitHub Enterprise リポジトリにプッシュします。
+
```shell
git push enterprise --mirror
```

コードを GitHub または BitBucket にインポートしたら、 https://circleci.com/docs/getting-started/[入門ガイド]に従って CircleCI 上でのプロジェクト作成を開始することができます。

[#build-configuration]
== ビルドの設定

次に、ビルドの設定を移行する必要があります。 Buildkite では、ビルドの設定は、Web インターフェイスで定義するか、ソースコードリポジトリのルートディレクトリにある `.pipeline.yml` というファイルで定義します。 ビルドの実行にシェルスクリプトを使用している場合は、CircleCI でそのスクリプトを再利用することができます。

まず、CircleCI のビルド設定ファイルを作成します。 ソースコードリポジトリのルートディレクトリに、.circleci というフォルダを作成し、その中に config.yml という名前のファイルを作成します。 次に、こちらの CircleCI のドキュメントに沿って、 .config.yml ファイルの設定方法を確認します。

Buildkiteと CircleCI の設定は異なります。 ビルドステップを変換する際は、Buildkite と CircleCI の両方のリファレンスドキュメントを並べて開いておくことをお勧めします。

* https://buildkite.com/docs/pipelines/defining-steps[Buildkite パイプラインのリファレンスドキュメント]

* https://circleci.com/docs/configuration-reference/[CircleCI YML のリファレンスドキュメント]

[#configuration-comparison]
== 設定の比較

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
| Buildkite | CircleCI

2+| 1つのビルドステップを実行するジョブの定義

a|
[source, yaml]
----
steps:
  - command: 'execute-script-for-job1.sh'
----

a|
[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"

----

2+| ジョブに使用する Docker イメージの指定

a|
[source, yaml]
----
steps:
  - label: 'job1'
    plugins:
      - docker#v3.2.0:
          image: 'node:10'

----

a|
[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数を参照します。

----

2+| マルチステージのビルドパイプラインの定義: ジョブ 1 と ジョブ 2 を同時に実行します。 完了すると、ジョブ 3 を実行します。 ジョブ 3 が完了すると、ジョブ 4 を実行します。

a|
[source, yaml]
----
steps:
  - label: 'job1'
    command: 'make build dependencies'

  - label: 'job2'
    command: 'make build artifacts'

  - wait

  - label: 'job3'
    command: 'make test'

  - wait

  - label: 'job4'
    command: 'make deploy'
----

a|
[source, yaml]
----
version: 2
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  version: 2
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----

2+| マルチプラットフォームでのジョブの実行:  Buildkite では、タグを使ってビルドエージェントを識別します。 CircleCI では、Docker、Linux、MacOS用の Executor を提供しています。

a|
[source, yaml]
----
steps:
  - label: 'ubuntuJob'
    agents:
      ubuntu: '16.04'
    command: 'echo "Hello, $USER!"'

  - label: 'osxJob'
    agents:
      osx: 'true'
    command: 'echo "Hello, $USER!"'

----

a|
[source, yaml]
----
jobs:
  ubuntuJob:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osxJob:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----
|===

より大規模で複雑なビルドについては、CircleCI のプラットフォームに慣れるまで、段階的に移行することをお勧めします。 以下の順番での移行をお勧めします。

. シェルスクリプトやDocker-composeファイルの実行
. https://circleci.com/docs/workflows/[ワークフロー]
. https://circleci.com/docs/artifacts/[アーティファクト]
. https://circleci.com/docs/caching/[キャッシュ]
. https://circleci.com/docs/triggers/#section=jobs[トリガー]
. https://circleci.com/docs/optimizations/#section=projects[パフォーマンス オプション]
