---

contentTags:
  platform:
  - クラウド
  - Server 3.x
---
= Buildkite からの移行
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、Buildkite から CircleCI に移行する方法をわかりやすく解説します。
:icons: font
:experimental:

このドキュメントでは、Buildkite から CircleCI に移行する方法を概説します。

NOTE: **ImagineX Consulting からのヒント**

[#source-control-setup]
== ソースコントロールの設定

First you will need to ensure your source code is located in either to GitHub, Bitbucket or GitLab. コードのインポート方法の詳細については、以下をご参照ください。

* link:https://help.github.com/en/articles/importing-a-repository-with-github-importer[GitHub]
* link:https://support.atlassian.com/bitbucket-cloud/docs/import-a-repository[Bitbucket]
* link:https://docs.gitlab.com/ee/user/project/import/repo_by_url.html[GitLab]

[#github-enterprise]
=== GitHub Enterprise

以下は、GitHub のコマンドラインツールを使って GitHub Enterprise にコードをインポートするための手順です。

. GitHub Enterprise のインスタンスに空のリポジトリを作成します。
. ローカルマシンに外部リポジトリのベアクローンを作成し、すべてのリモートタグ (refs/tags/\*) をフェッチし、すべてのリモートブランチヘッド (refs/heads/\*) を対応するローカルブランチヘッドに直接コピーします。
+
```shell
git clone https://external-host.com/extuser/repo.git --bare
```
. ローカルクローンに、GitHub Enterprise リポジトリをリモートリファレンスとして追加します。
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. すべてのローカルリファレンス（refs/*）を、リモートの GitHub Enterprise リポジトリにプッシュします。
+
```shell
git push enterprise --mirror
```

Once you have imported your code into GitHub, Bitbucket or GitLab, you can start creating a project in CircleCI using the xref:getting-started#[Getting Started guide].

[#build-configuration]
== ソースコントロールの設定

まず、ソースコードが GitHub または Bitbucket に置かれていることを確認してください。 コードのインポート方法の詳細については、以下をご参照ください。 ビルドの実行にシェルスクリプトを使用している場合は、CircleCI でそのスクリプトを再利用することができます。

まず、CircleCI のビルド設定ファイルを作成します。 ソースコードリポジトリのルートディレクトリに、.circleci というフォルダを作成し、その中に config.yml という名前のファイルを作成します。 次に、こちらの CircleCI のドキュメントに沿って、 .config.yml ファイルの設定方法を確認します。

Buildkiteと CircleCI の設定は異なります。 ビルドステップを変換する際は、Buildkite と CircleCI の両方のリファレンスドキュメントを並べて開いておくことをお勧めします。

* link:https://buildkite.com/docs/pipelines/defining-steps[Buildkite Pipeline Reference]
* xref:configuration-reference#[CircleCI YML Reference]

[#configuration-comparison]
== ビルドの設定

次に、ビルドの設定を移行する必要があります。

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
|Buildkite |CircleCI

2+|1つのビルドステップを実行するジョブの定義

a|[source, yaml]
----
steps:
  - command: 'execute-script-for-job1.sh'
----
|[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"
----

2+|ジョブに使用する Docker イメージの指定

a|[source, yaml]
----
steps:
  - label: 'job1'
    plugins:
      - docker#v3.2.0:
          image: 'node:10'

----
|[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10

----

2+|マルチステージのビルドパイプラインの定義: ジョブ 1 と ジョブ 2 を同時に実行します。 完了すると、ジョブ 3 を実行します。 ジョブ 3 が完了すると、ジョブ 4 を実行します。

a|[source, yaml]
----
steps:
  - label: 'job1'
    command: 'make build dependencies'

  - label: 'job2'
    command: 'make build artifacts'

  - wait

  - label: 'job3'
    command: 'make test'

  - wait

  - label: 'job4'
    command: 'make deploy'
----
|[source, yaml]
----
version: 2.1
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----

2+|マルチプラットフォームでのジョブの実行:  Buildkite では、タグを使ってビルドエージェントを識別します。 CircleCI では、Docker、Linux、MacOS用の Executor を提供しています。

a|[source, yaml]
----
steps:
  - label: 'ubuntuJob'
    agents:
      ubuntu: '16.04'
    command: 'echo "Hello, $USER!"'

  - label: 'osxJob'
    agents:
      osx: 'true'
    command: 'echo "Hello, $USER!"'

----
|[source, yaml]
----
jobs:
  ubuntuJob:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osxJob:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----
|===

Buildkiteと CircleCI の設定は異なります。 ビルドステップを変換する際は、Buildkite と CircleCI の両方のリファレンスドキュメントを並べて開いておくことをお勧めします。

. シェルスクリプトや Docker Compose ファイルの実行
. link:https://circleci.com/docs/workflows/[Workflows]
. link:https://circleci.com/docs/artifacts/[Artifacts]
. link:https://circleci.com/docs/caching/[Caching]
. link:https://circleci.com/docs/triggers/#section=jobs[Triggers]
. link:https://circleci.com/docs/optimizations/#section=projects[Performance options]