---

version:
- クラウド
- Server 3
---


= GitLab からの移行

:page-layout: classic-docs
:page-liquid:
:page-description: An overview of how to migrate from GitLab to CircleCI.
:icons: font
:toc: macro

:toc-title:

このドキュメントでは、GitLab から CircleCI に移行する方法を概説します。

NOTE: **Tips provided by ImagineX Consulting**

[#source-control-setup]
== ソースコントロールの設定

If you are using GitLab's SCM, you will first need to migrate your source code to GitHub or BitBucket. コードのインポート方法の詳細については、以下をご参照ください。

* https://help.github.com/en/articles/importing-a-repository-with-github-importer[Import into GitHub]
* https://confluence.atlassian.com/get-started-with-bitbucket/import-a-repository-861178561.html[Import into BitBucket]

[#github-enterprise]
=== GitHub Enterprise

以下は、Git のコマンドラインツールを使って GitHub Enterprise にコードをインポートするための手順です。

. GitHub Enterprise のインスタンスに空のリポジトリを作成します。
. Create a bare clone of your GitLab.com repository on your local machine, fetching all remote tags (refs/tags/\*) and copying all remote branch heads (refs/heads/\*) directly to their corresponding local branch heads:
+
```shell
git clone git@gitlab.com:[owner]/[repo-name].git --bare
```
. ローカルクローンに、GitHub Enterprise リポジトリをリモートリファレンスとして追加します。
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. すべてのローカルリファレンス（refs/\*）を、リモートの GitHub Enterprise リポジトリにプッシュします。
+
```shell
git push enterprise --mirror
```

If you need to export other GitLab artifacts, follow the GitLab documentation on https://docs.gitlab.com/ee/user/project/settings/import_export.html#exporting-a-project-and-its-data[exporting a project].

Once you have imported your code into GitHub or BitBucket, you can start creating a project in CircleCI using the https://circleci.com/docs/2.0/getting-started/[Getting Started guide].

[#build-configuration]
== ビルドの設定

If you are using GitLab's CI/CD, you will need to migrate your build configuration. On GitLab, the build configuration is defined in a file called `.gitlab-ci.yml` in the root directory of your source code repository. ビルドの実行にシェルスクリプトを使用している場合は、CircleCI でそのスクリプトを再利用することができます。

まず、CircleCI のビルド設定ファイルを作成します。 In the root directory of your source code repository, create a folder named `.circleci` and create a file in that folder named `config.yml`. Next, follow the CircleCI documentation https://circleci.com/docs/2.0/config-intro/[here] to learn how to configure the `.config.yml` file.

GitLab と CircleCI の設定は異なります。 ビルドステップを変換する際は、GitLabと CircleCI の両方のリファレンスドキュメントを並べて開いておくことをお勧めします。

* https://docs.gitlab.com/ee/ci/yaml/[GitLab YML Reference]
* https://circleci.com/docs/2.0/configuration-reference/[CircleCI YML Reference]

[#configuration-comparison]
== 設定の比較

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
|GitLab |CircleCI

2+|1つのビルドステップを実行するジョブの定義

a|[source, yaml]
----
job1:
  script: "execute-script-for-job1"
----
|[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"

----

2+|ジョブに使用するDocker イメージの指定

a|[source, yaml]
----
job1:
  image: node:10
----
|[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10
----

2+|マルチステージのビルドパイプラインの定義: ジョブ 1 と ジョブ 2 を同時に実行します。 完了すると、ジョブ 3 を実行します。 ジョブ 3 が完了すると、ジョブ 4 を実行します。

a|[source, yaml]
----
job1:
  stage: build
  script: make build dependencies

job2:
  stage: build
  script: make build artifacts

job3:
  stage: test
  script: make test

job4:
  stage: deploy
  script: make deploy

stages:
  - build
  - test
  - deploy
----
|[source, yaml]
----
version: 2
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  version: 2
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----

2+|マルチプラットフォームでのジョブの実行:  GitLab では、タグを使ってビルドエージェントを識別します。 CircleCI では主要な OS と Docker はすべてサポートしており、設定で明示的に定義する必要があります。 See our https://circleci.com/docs/2.0/executor-intro/#section=configuration[execution environments documentation] for more information.

a|[source, yaml]
----
ubuntu job:
  tags:
    - ubuntu
  script:
    - echo "Hello, $USER!"

osx job:
  tags:
    - osx
  script:
    - echo "Hello, $USER!"
----
|[source, yaml]
----
jobs:
  ubuntu-job:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osx-job:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----

2+|依存関係のキャッシュ

a|[source, yaml]
----
image: node:latest

# ジョブ間のキャッシュモジュールです。
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

test_async:
  script:
    - node ./specs/start.js
----
|[source, yaml]
----
{% raw %}
jobs:
  test_async:
    steps:
      - restore_cache:
          key: source-v1-{{ checksum "package.json" }}
      - checkout
      - run: npm install
      - save_cache:
          key: source-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: node ./specs/start.js
{% endraw %}
----
|===

より大規模で複雑なビルドについては、CircleCI のプラットフォームに慣れるまで、段階的に移行することをお勧めします。 以下の順番での移行をお勧めします。

. https://circleci.com/docs/2.0/executor-intro/[Pick your executor]
. https://circleci.com/docs/2.0/configuration-reference/#checkout[Checkout code]
. https://circleci.com/docs/2.0/env-vars/[Environment variables] and https://circleci.com/docs/2.0/contexts/[Contexts]
. Install dependencies, also see https://circleci.com/docs/2.0/caching/[Cache dependencies]
. https://circleci.com/docs/2.0/configuration-reference/#docker[Service containers]
. テストコマンドの実行
. https://circleci.com/docs/2.0/custom-images/[Custom convenience images]
. https://circleci.com/docs/2.0/configuration-reference/#resource_class[Resource classes]
. https://circleci.com/docs/2.0/workflows/[Workflows]
. https://circleci.com/docs/2.0/collect-test-data/[Test results] / test splitting / https://circleci.com/docs/2.0/parallelism-faster-jobs/[parallelism]
. https://circleci.com/docs/2.0/artifacts/[Artifacts]