---

contentTags:
  platform:
  - クラウド
  - Server v2.x
  - Server v3.x
  - Server v4.x
---
= deploy から run への移行
:page-layout: classic-docs
:page-liquid:
:page-description: 廃止予定の deploy ステップから run への移行方法
:icons: font
:toc: macro

:toc-title:

[#introduction]
== はじめに

廃止予定の `deploy` ステップ_ が使用されている設定ファイルは、変更する必要があります_。ジョブで xref:parallelism-faster-jobs#[parallelism(並列処理)] が使われているかどうかに関わらず、`deploy` ステップの _すべての_ インスタンスを削除する必要があります。

- *ジョブの並列実行が 1 つの場合*: `deploy` キーを xref:configuration-reference#run[`run`] キーに変更します。 移行に必要な処理はこれだけです。
- *ジョブの並列実行が  2 つ以上の場合*: ジョブで並列実行を 2 つ以上使用している場合、`deploy` ステップは直接置き換えられません。 1 つのワークフローで、test ジョブと deploy ジョブの 2 つのジョブを別々に作成することを推奨します。 test ジョブではテストが並列で実行され、deploy ジョブは test ジョブに依存します。 test ジョブには並列実行が 2 つ以上含まれ、deploy ジョブでは以前の `deploy` ステップのコマンドが `run` に置き換えられ、並列処理は行われません。 下記の例をご覧ください。

== 並列処理が 2 つ以上の場合

以下は、並列処理を 2 つ以上含む設定ファイルで、廃止予定の `deploy` ステップを置き換える場合の例です。

CAUTION: 1 つ目の例のコードは廃止予定です。 コピーしないでください。

```yml
# Example of deprecated syntax, do not copy
version: 2.1
jobs:
  deploy-step-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parallelism: 3
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Write random data"
          command: openssl rand -hex 4 > rand_${CIRCLE_NODE_INDEX}.txt
      - run:
          name: "Emulate doing things"
          command: |
            if [[ "$CIRCLE_NODE_INDEX" != "0" ]]; then
              sleep 30
            fi
      - deploy: #deprecated deploy step, do not copy
          command: |
            echo "this is a deploy step which needs data from the rand"
            cat rand_*.txt

workflows:
  deploy-step-workflow:
    jobs:
      - deploy-step-job
```

完全に外部リソースに依存している場合 (たとえば、Docker コンテナがレジストリにプッシュされるなど)、上記の `deploy` ステップをジョブとして抽出できます。これを実行するには `doing-things-job` を完了させる必要があります。 `doing-things-job` が並列実行を 3 つ使い、`deploy-step-job` が実際のデプロイを行います。 以下の例を参照してください。

```yml
version: 2.1
jobs:
  doing-things-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parallelism: 3
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Write random data"
          command: openssl rand -hex 4 > rand_${CIRCLE_NODE_INDEX}.txt
      - run:
          name: "Emulate doing things"
          command: |
            if [[ "$CIRCLE_NODE_INDEX" != "0" ]]; then
              sleep 30
            fi
  # create a new job with the deploy step in it
  deploy-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: # change "deploy" to "run"
          command: |
            echo "this is a deploy step"

workflows:
  deploy-step-workflow:
    jobs:
      - doing-things-job
      # add your new job and make it depend on the
      # "doing-things-job"
      - deploy-job:
          requires:
            - doing-things-job
```

[#using-workspaces]
=== ワークスペースの使用

`deploy-job` で `doing-things-job` からのファイルが必要な場合は、xref:workspaces#[ワークスペース] を使用します。 これにより、2 つのジョブでファイルを共用でき、`deploy-job` がファイルにアクセスできるようになります。 以下の例を参照してください。

```yml
version: 2.1
jobs:
  doing-things-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parallelism: 3
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Write random data"
          command: openssl rand -hex 4 > rand_${CIRCLE_NODE_INDEX}.txt
      - run:
          name: "Emulate doing things"
          command: |
            if [[ "$CIRCLE_NODE_INDEX" != "0" ]]; then
              sleep 30
            fi
      # save the files your deploy step needs
      - persist_to_workspace:
          root: .     # relative path to our working directory
          paths:      # file globs which will be persisted to the workspace
           - rand_*

  deploy-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      # attach the files you persisted in the doing-things-job
      - attach_workspace:
          at: . # relative path to our working directory
      - run:
          command: |
            echo "this is a deploy step"

workflows:
  deploy-step-workflow:
    jobs:
      - doing-things-job
      - deploy-job:
          requires:
            - doing-things-job
```

この例では "fan-in" ワークフロー (詳細は xref:workflows#fan-outfan-in-workflow-example[ワークフロー] を参照) を効果的に使用しています。

WARNING: 廃止予定の `deploy` ステップのサポートは最終的に終了します。 お客様が設定ファイルを移行するための時間を十分に取る予定です。