---

version:
- クラウド
---
= ジョブでの OpenID Connect トークンの使用
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to use OpenID Connect ID tokens for access to compatible cloud services.
:icons: font
:toc: macro
:toc-title:

コンテキストを使用するジョブでは、環境変数で OpenID Connect ID トークンを提供します。 ジョブは、CircleCI に保存されている長期認証情報を使用せずに、このトークンを使って互換性のあるクラウドサービスにアクセスすることができます。

toc::[]

== OpenID Connect ID トークンの使用

1 つ以上のコンテキストを使用する CircleCI ジョブでは、環境変数「CIRCLE_OIDC_TOKEN」で OpenID Connect ID トークンを使用することができます。

`context` キーを `circleci/config.yml` ファイルの <<configuration-reference/#workflows,workflows>> セクションに追加して、<<contexts/#creating-and-using-a-context,context to a job>> を追加します。

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - my-context

== クラウドサービスの設定

お客様のクラウドサービスのドキュメントで ID プロバイダーの追加方法を確認してください。 たとえば、AWS の場合は、https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html[Creating OpenID Connect (OIDC) identity providers]、Google Cloud Platform の場合は、https://cloud.google.com/iam/docs/configuring-workload-identity-federation#oidc[Configuring workload identity federation] を参照してください。

https://openid.net/specs/openid-connect-core-1_0.html#Terminology[OpenID プロバイダー] は、組織一意のものです。 URL は、`\https://oidc.circleci.com/org/<organization-id>` で、`<organization-id>`  は、お客様の組織を代表する組織 ID (UUID) です。

お客様の組織 ID は、https://app.circleci.com/ [CircleCI Webアプリ] で  **Organization Settings > Contexts** に移動し、ページ上部で **Organization ID** を探します。

The OpenID Connect ID tokens issued by CircleCI have a fixed audience (see `aud` in the table below), which is also the organization ID.

== Format of the OpenID Connect ID token

The OpenID Connect ID token contains the following standard https://openid.net/specs/openid-connect-core-1_0.html#IDToken[claims]:

[%autowidth]
[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|Claims
|説明

|`iss`
|The issuer. The issuer is specific to the CircleCI organization in which the job is being run. Its value is `"https://oidc.circleci.com/org/<organization-id>"`, a    string, where `<organization-id>` is a UUID identifying the current job's project's organization.

|`sub`
|The subject. This identifies who is running the CircleCI job and where. Its value is `"org/<organization-id>/project/<project-id>/user/<user-id>"`, a string, where `<organization-id>`, `<project-id>`, and `<user-id>` are UUIDs that identify the CircleCI organization, project, and user, respectively. The user is the CircleCI user that caused this job to run.

|`aud`
|The audience. Currently, this is a fixed value `"<organization-id>"`, a string containing a UUID that identifies the job's project's organization.

|`iat`
|The time of issuance. This is the time the token was created, which is shortly before the job starts.

|`exp`
|The expiration time. Its value is one hour after the time of issuance.
|===

The OpenID Connect ID token also contains some https://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims[additional claims] with extra metadata about the job:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|Additional claims
|メタデータ

|`oidc.circleci.com/project-id`
|The ID of the project in which the job is running. Its value is a string containing a UUID identifying the CircleCI project.

|`oidc.circleci.com/context-ids`
|An array of strings containing UUIDs that identify the context(s) used in the job. Currently, just one context is supported.
|===