---

version:
- クラウド
---
= CircleCI Free プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Free plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:
:orbs:

このドキュメントでは、開発者の皆様にご利用いただいける Free プランについてご案内します。

[#free-plan]
== Free プラン

従来の CircleCI のコンテナベースプランと同様に、従量課金制でも無料の Freeプランをご用意しています。 この Free プランでも CircleCI の多くの主要機能を利用して生産性、効率、速度を高めることが可能です。

従量課金制の Free プランでは、さまざまなリソースクラスに対して毎月一定のクレジットが提供され、ビルドの設定や実行環境に基づきご自身でカスタマイズしていただけます。 この組み合わせでは、1 分あたりの消費クレジット数が少なく、ユーザーのシート数に制限はありません。

Free プランのユーザー数に制限はなく、何人でも CircleCI 上でビルドおよび開発をしていただけます。 組織内またはオープンソースで、異なるチームやグループで複数のプロジェクトの共同作業を行うことにより、スピードや生産性、そして効率を向上させられます。 使用できるネットワークとストレージは一定なため、ユーザー数の制限がない分、クレジットの割り当てを適切に管理する必要があります。

下記は Free プランでご利用いただける機能です。 クレジット数、含まれるリソースクラス、主要機能、サポートについての詳細は、 https://circleci.com/ja/pricing/[料金設定]のページを参照してください。 CPU、メモリ、ネットワークとストレージ、および実行環境におけるコンピューティングタイプのクレジットの使用量の詳細については https://circleci.com/ja/product/features/resource-classes/[リソースクラスの機能]のページを参照してください。

[#available-resource-classes]
=== 利用可能なリソースクラス

Docker、 Linux、 Windows、および macOS のさまざまなリソースクラスをご使用いただけます。 柔軟性の高い選択肢により、適切なコンピューティングリソースを選択することが可能です。 これらの Executor に関する例や詳細は、<<executor-intro#,Executors and Images>> のページをご覧ください。

{% include snippets/ja/features-of-circleci.adoc %}

[#support]
=== サポート

Scale プランでは、 https://discuss.circleci.com/[コミュニティフォーラム]、 https://support.circleci.com/hc/ja[サポートポータル]、および https://support.circleci.com/hc/ja/requests/new[チケットベースのグローバル サポート] もご利用いただけます。