---

version:
- Server v2.x
- Server v3.x
---
= CircleCI Server プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Server plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:
:concurrency:
:orbs:

このドキュメントでは、開発者の皆様にご利用いただいける Server プランについてご案内します。

== Server  プラン

CircleCI Server は、コンプライアンスやセキュリティ上のニーズからファイアウォール内やプライベートクラウド、データセンターでの運用が求められる企業向けのオンプレミス型 CI/CD プラットフォームです。 詳細については <<server-3-overview#,Server documentation>>をご覧ください。

Server プランにはカスタムクレジットオプションがあり、CircleCI のすべてのリソースクラスでお客様のビルド設定や実行環境に応じて1ヶ月単位でご利用いただけます。

Server プランでは、他のプランに加えて下記のようなアップブレード機能をご利用いただけます。

=== ユーザーシート数のカスタマイズ

必要に応じてアクティブユーザー数をカスタマイズすることが可能です。

=== サポートオプションの追加

拡張版の SLA、アカウントチーム、トレーニングおよびオンボーディングオプションによるすべての追加サポートをサポートパッケージのアドオンにより拡張することが可能です。 Server プランでは、[community forums](https://discuss.circleci.com/)、[support portal](https://support.circleci.com/hc/en-us)、および [global ticket-based system](https://support.circleci.com/hc/en-us/requests/new) もご利用いただけます。

== CircleCI の機能

上記のアップグレード機能に加え、Server プランでは下記の機能もご利用いただけます。 クレジット数、含まれるリソースクラス、主要機能、サポートについての詳細は [料金設定](https://circleci.com/ja/pricing/)のページを参照してください。 CPU、メモリ、ネットワークとストレージ、および実行環境におけるコンピューティングタイプのクレジットの使用量の詳細については、[リソースクラスの機能](https://circleci.com/ja/product/features/resource-classes/)のページを参照してください。 以下の機能はすべてのプランでご利用いただけます。

{% include snippets/features-of-circleci.adoc %}