---

contentTags:
  platform:
  - Server v4.x
  - Server v3.x
  - Server v2.x
---
= CircleCI Server プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Server plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:
:concurrency:
:orbs:

このドキュメントでは、開発者の皆様にご利用いただいける Server プランについてご案内します。

[#server-plan]
== Server  プラン

CircleCI Server は、コンプライアンスやセキュリティ上のニーズからファイアウォール内やプライベートクラウド、データセンターでの運用が求められる企業向けのオンプレミス型 CI/CD プラットフォームです。 Please see the xref:server/overview/circleci-server-v4-overview#[Server documentation] for more information.

Server プランにはカスタムクレジットオプションがあり、CircleCI のすべてのリソースクラスでお客様のビルド設定や実行環境に応じて1ヶ月単位でご利用いただけます。

Server プランでは、他のプランに加えて下記のようなアップブレード機能をご利用いただけます。

[#custom-user-seat-count]
=== ユーザーシート数のカスタマイズ

必要に応じてアクティブユーザー数をカスタマイズすることが可能です。

[#custom-storage-retention]
=== ストレージ保存期間のカスタマイズ

The link:https://app.circleci.com/[CircleCI web app] allows for the customization of the storage retention periods of artifact, workspace, and cache objects. これにより、それぞれのオブジェクトタイプの保存方法をお客様のプロジェクトに最適な方法に設定することができます。 ストレージ保存期間を短くすると、月々のコストを下げることができます。

[#additional-support-options]
=== サポートオプションの追加

拡張版の SLA、アカウントチーム、トレーニングおよびオンボーディングオプションによるすべての追加サポートをサポートパッケージのアドオンにより拡張することが可能です。 The Server plan also has access to the link:https://discuss.circleci.com/[community forums], link:https://support.circleci.com/hc/en-us[support portal], and our link:https://support.circleci.com/hc/en-us/requests/new[global ticket-based system].

[#circleci-features]
== CircleCI の機能

上記のアップグレード機能に加え、Server プランでは下記の機能もご利用いただけます。 Refer to the link:https://circleci.com/pricing/[Pricing] page for more detailed information on credit amounts, included resource classes, key features, and support. Refer to the link:https://circleci.com/product/features/resource-classes/[Resource class features] page for details on CPU, memory, network and storage, and credit usage for compute type/execution environment. 以下の機能はすべてのプランでご利用いただけます。

{% include snippets/ja/features-of-circleci.adoc %}