---

contentTags:
  platform:
  - クラウド
---
= CircleCI Free プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Free plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:
:orbs:

このドキュメントでは、開発者の皆様にご利用いただいける Free プランについてご案内します。

[#free-plan]
== Free プラン

With the Free plan, you can take advantage of a large number of premium features that will allow your team to be more productive, efficient, and fast.

The Free plan offers a set amount of credits across a variety of resource classes, per month, which you can customize depending on your build configuration and execution environment. この組み合わせでは、1 分あたりの消費クレジット数が少なく、ユーザーのシート数に制限はありません。

Free プランのユーザー数に制限はなく、何人でも CircleCI 上でビルドおよび開発をしていただけます。 組織内またはオープンソースで、異なるチームやグループで複数のプロジェクトの共同作業を行うことにより、スピードや生産性、そして効率を向上させられます。 使用できるネットワークとストレージは一定なため、ユーザー数の制限がない分、クレジットの割り当てを適切に管理する必要があります。

下記は Free プランでご利用いただける機能です。 Refer to the link:https://circleci.com/pricing/[Pricing] page for more detailed information on credit amounts, included resource classes, key features, and support. Refer to the link:https://circleci.com/product/features/resource-classes/[Resource class features] page for details on CPU, memory, network and storage, and credit usage for compute type on execution environments.

[#available-resource-classes]
=== 利用可能なリソースクラス

Docker、 Linux、 Windows、および macOS のさまざまなリソースクラスをご使用いただけます。 柔軟性の高い選択肢により、適切なコンピューティングリソースを選択することが可能です。 To view examples, or find more information about these executors, please refer to the xref:executor-intro#[Executors and Images] page.

{% include snippets/ja/features-of-circleci.adoc %}

[#support]
=== サポート

Support is available through the link:https://discuss.circleci.com/[community forums], link:https://support.circleci.com/hc/en-us[support portal], and our link:https://support.circleci.com/hc/en-us/requests/new[global ticket-based system].