---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
  - Server v2.x
---
= CircleCI 料金プランの概要
:page-layout: classic-docs
:page-liquid:
:page-description: This document is an introduction to the plans CircleCI offers to developers.
:icons: font
:toc: macro
:toc-title:

このドキュメントでは、開発者の皆様に向けた CircleCI の料金プランについてご案内します。

[#overview]
== 概要

The CircleCI credit-based usage plans enable you to only pay for what you use, while also providing flexibility in customizing and scaling your team's link:https://circleci.com/continuous-integration/#what-is-continuous-integration[CI/CD] solution. クレジットは、秒単位で消費され、分単位のレートは選択したビルドの設定によって異なります。

チームに最適なプランを検討する際は、以下のような要素を考慮する必要があります。

- チームのユーザー数
- 必要なサポートのレベル (無料の Community サポート、Standard サポート、Premium サポート)
- 複数のマシンタイプやリソースクラスの利用の要否
- セルフホストランナー数の制限の有無

Let us look at how a team might use credits. チームが複数のグループに分かれ、それぞれ異なるプロジェクトを進めているとします。 大規模なプロジェクトもあれば、CI/CD の設定で割り当てるリソースが少なくて済む小規模なプロジェクトもあります。 クレジットベースプランでは、リソースを最大化する必要があるマシンと利用時間をピンポイントで指定することが可能です。

たとえば、大きな resource_class (CPU 4基、 メモリ 8 GB) を使用して 1 分あたりのクレジット数を増やし、大規模なプロジェクトのビルドを高速化することができます。一方、小規模なプロジェクトでコードのリリース頻度が低い場合や、ビルド時間を重視しない場合は、小さな resource_class (CPU 1基、 メモリ 2 GB) を使用できます。

このセクションでは、開発者の皆様のCI/CD のニーズに対して各プランで提供される内容を説明します。 Consider also taking a moment to look at the CircleCI link:https://circleci.com/pricing/[Pricing] page to learn about how credits are distributed across different machine types.

[#our-plans]
== 料金プラン

下記ページから各料金プランの内容をご覧ください。

- xref:plan-free#[Free Plan]
- xref:plan-performance#[Performance Plan]
- xref:plan-scale#[Scale Plan]
- xref:plan-server#[Server Plan]

[#configuring-your-credit-plan]
== クレジットベースプランの設定

To set up a Free or Performance plan, go to **Plan > Plan Overview** in the CircleCI link:https://app.circleci.com/[web application]. お客様のニーズに最適なプランを選択します。 To set up a Scale or Server plan, link:https://circleci.com/talk-to-us/[contact us].

[#managing-credit-usage]
== クレジット使用量の管理

重複するアーティファクトのアップロードの排除などにより最適化し、クレジット消費を抑えることが可能です。 また、ネットワークとストレージの使用状況を適切に管理することで、毎月のクレジット使用量を削減することができます。 If you would like to find out more about managing network and storage usage, please see the xref:persist-data#[Persisting data] page.