---

contentTags:
  platform:
  - クラウド
---
= CircleCI Scale プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Scale plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:

このドキュメントでは、開発者の皆様にご利用いただいける Scale プランについてご案内します。

[#scale-plan]
== Scale プラン

Scale プランでは、お客様のチームやビジネスに合わせた拡張や幅広いカスタマイズが可能です。 Scale プランにはカスタムクレジットオプションがあり、 CircleCI のすべてのリソースクラスでお客様のビルド設定や実行環境に応じて 1ヶ月単位でご利用いただけます。 このプランでは CircleCI が提供する最大量のネットワークおよびストレージをご利用いただけます。

Scaleプランでは、Free プランや Performanceプランに加えて以下の様々な機能をご利用いただけます。

[#access-to-ip-ranges]
=== IP アドレスの範囲機能の利用

IP アドレスの範囲機能により、制限された環境へのアクセスを IP アドレスに基づいて設定することができます。 この機能を有効にしたジョブのトラフィックは、ジョブの実行の際は指定したいずれかの IP アドレスを使用するようになります (この IP アドレスの範囲機能は Performance プランでも Scale プランでも同じです)。

For more information about this features, please refer to the xref:ip-ranges#[IP ranges] page.

[#access-to-all-resource-classes]
=== すべてのリソースクラスの利用

Docker、 Linux、 Windows、および macOS 上ですべてのマシンサイズをご利用いただけます。 コンピューティングタイプや実行環境別の追加リソースクラスを使用すると、CPU およびメモリの上限を拡大することが可能です。

For more information about these resources, please refer to the the xref:executor-intro#[Executors and images] page.

[#custom-concurrency]
=== 同時実行数のカスタマイズ

同時に実行する必要があるジョブの数をカスタマイズすることができます。 このカスタマイズ機能はすべてのビルド設定および実行環境において利用できます。 詳細については<<#concurrency,同時実行>>のページをご覧ください。

[#custom-user-seat-count]
=== ユーザーシート数のカスタマイズ

必要に応じてアクティブユーザー数をカスタマイズすることが可能です。

[#unlimited-self-hosted-runners]
=== 無制限のセルフホストランナー数

使用可能なセルフホストランナー数に制限がないため、お客様のインフラストラクチャ上でより多くのジョブを実行することができます。詳細は下記のセルフホストランナーのページをご覧ください。 詳細は<<#self-hosted-runners,セルフホストランナー>> のページをご覧ください。

[#custom-storage-retention]
=== ストレージ保存期間のカスタマイズ

The link:https://app.circleci.com/[CircleCI web app] allows for the customization of the storage retention periods of artifact, workspace, and cache objects. これにより、それぞれのオブジェクトタイプの保存方法をお客様のプロジェクトに最適な方法に設定することができます。 ストレージ保存期間を短くすると、月々のコストを下げることができます。

[#additional-support-options]
=== サポートオプションの追加

拡張版の SLA、アカウントチーム、トレーニングおよびオンボーディングオプションによるすべての追加サポートをサポートパッケージのアドオンにより拡張することが可能です。 The Scale plan also has access to the link:https://discuss.circleci.com/[community forums], link:https://support.circleci.com/hc/en-us[support portal], and our link:https://support.circleci.com/hc/en-us/requests/new[global ticket-based system].

[#circleci-features]
== CircleCI の機能

上記のアップグレード機能に加え、Scale プランでは下記の機能もご利用いただけます。 Refer to the link:https://circleci.com/pricing/[Pricing] page for more detailed information on credit amounts, included resource classes, key features, and support. Refer to the link:https://circleci.com/product/features/resource-classes/[Resource class features] page for details on CPU, memory, network and storage, and credit usage for compute type/execution environment. 以下の機能はすべてのプランでご利用いただけます。

{% include snippets/ja/features-of-circleci.adoc %}