---

version:
- クラウド
---
= CircleCI Performance プラン
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Performance plan available to developers on CircleCI.
:icons: font
:toc: macro
:toc-title:
:orbs:

このドキュメントでは、開発者の皆様にご利用いただいける Performance プランについてご案内します。

[#performance-plan]
== Performance プラン

Performance プランでは、さまざまなリソースクラスに対して毎月一定のクレジットが提供され、ビルドの設定や実行環境に基づきご自身でカスタマイズしていただけます。

ご利用いただけるネットワーク使用量が増えるだけでなく、Free プランに加えて下記のような様々な機能をご利用いただけます。

[#access-to-ip-ranges]
=== IP アドレスの範囲機能の利用

IP アドレスの範囲機能により、制限された環境へのアクセスを IP アドレスに基づいて設定することができます。 この機能を有効にしたジョブのトラフィックは、ジョブの実行の際は指定したいずれかの IP アドレスを使用するようになります。

この機能に関する詳細は、<<ip-ranges#,IP アドレスの範囲>> のページをご覧ください。

[#additional-resource-classes]
=== 追加のリソースクラス

Docker、 Linux、 Windows、および macOS 上で大きなマシンサイズのご利用が可能です。 コンピューティングタイプや実行環境別の追加リソースクラスを使用すると、CPU およびメモリの上限を拡大することが可能です。

これらのリソースに関する詳細は、<<executor-intro#,Executors と イメージ>> のページをご覧ください。

[#less-queuing-with-more-concurrency]
=== 同時実行数の増加によるキューイングの削減

<<#concurrency,同時実行>>のセクションで説明するように、ワークフロー内でより多くのジョブを同時に実行することができます。

[#scalable-user-seat-count]
=== 拡張可能なユーザーシート数

プランには一定のアクティブユーザ数が含まれています。 クレジットを使用して、ユーザーを追加することができます。 クレジットが足りない場合は、追加ユーザ分のクレジットを月単位で購入できます。 このプロセスにより、ビルドアクティビティに合わせてクレジットパッケージを拡張することが可能です。

[#additional-self-hosted-runners]
=== セルフホストランナーの追加

セルフホストランナーの数が大幅に増え、お客様のインフラストラクチャ上でより多くのジョブを実行することができます。 詳細は<<#self-hosted-runners,セルフホストランナー>> のページをご覧ください。

[#custom-storage-retention]
=== ストレージ保存期間のカスタマイズ

https://app.circleci.com/[CircleCI Web アプリ]では、アーティファクト、ワークスペース、キャッシュプロジェクトのストレージ保存期間のカスタマイズが可能です。 これにより、それぞれのオブジェクトタイプの保存方法をお客様のプロジェクトに最適な方法に設定することができます。 ストレージ保存期間を短くすると、月々のコストを下げることができます。

[#additional-support-options]
=== サポートオプションの追加

SLA を介した追加サポート(利用時間と日数の制限あり) の利用やサポートパッケージのアドオンが可能です。 Performance プランでは、 https://discuss.circleci.com/[コミュニティフォーラム]、 https://support.circleci.com/hc/ja[サポートポータル]、および 
 https://support.circleci.com/hc/ja/requests/new[チケットベースのグローバルサポート] もご利用いただけます。

[#circleci-features]
== CircleCI の機能

上記のアップグレード機能に加え、Performance プランでは下記の機能もご利用いただけます。 クレジット数、含まれるリソースクラス、主要機能、サポートについての詳細は https://circleci.com/ja/pricing/[料金設定]のページを参照してください。 CPU、メモリ、ネットワークとストレージ、および実行環境におけるコンピューティングタイプのクレジットの使用量の詳細については https://circleci.com/ja/product/features/resource-classes/[リソースクラスの機能]のページを参照してください。 以下の機能はすべてのプランでご利用いただけます。

{% include snippets/ja/features-of-circleci.adoc %}