---
version:
- Cloud
- Server v2.x
- Server v3.x
---
= Using Docker Authenticated Pulls
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

ここでは、Docker レジストリのプロバイダーでイメージのプルを認証する方法について説明します。

プルを認証することで、プライベートの Docker イメージにアクセスできるようになります。  お使いのレジストリ プロバイダーによっては、レート制限が引き上げられる可能性もあります。

CircleCI has partnered with Docker to ensure that our users can continue to access Docker Hub without rate limits. As of November 1st 2020, with few exceptions, you should not be impacted by any rate limits when pulling images from Docker Hub through CircleCI. However, these rate limits may go into effect for CircleCI users in the future. That’s why we’re encouraging you and your team to add Docker Hub authentication to your CircleCI configuration and consider upgrading your Docker Hub plan, as appropriate, to prevent any impact from rate limits in the future.

toc::[]

## Docker Executor

For the https://circleci.com/docs/2.0/executor-types/#using-docker[Docker executor], specify a username and password in
the `auth` field of your https://circleci.com/docs/2.0/configuration-reference[config.yml] file. To protect the password,
place it in a https://circleci.com/docs/2.0/contexts/[context], or use a per-project Environment Variable.

NOTE: Server 2.x customers may instead set up a Docker Hub pull through a xref:docker-hub-pull-through-mirror.adoc[registry mirror].
Pulls through Docker Hub registry mirrors are not yet available on Server 3.x.

NOTE: Contexts are the more flexible option.  CircleCI は複数のコンテキストをサポートしており、シークレットをモジュール化したり、ジョブが必要なものだけにアクセスできるようにしたりするのにとても便利です。

この例では、既存の `build-env-vars` コンテキストを肥大化させずに、build ジョブに Docker 認証情報の `docker-hub-creds` コンテキストへのアクセスを付与します。

[source,yaml]
----
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: acme-private/private-image:321
        auth:
          username: mydockerhub-user  # 文字列リテラル値を指定します
          password: $DOCKERHUB_PASSWORD  # または、プロジェクトの環境変数を参照するように指定します
----

You can also use images from a private repository like https://cloud.google.com/container-registry[gcr.io] or
https://quay.io[quay.io]. Make sure to supply the full registry/image URL for the `image` key, and use the appropriate
username/password for the `auth` key. 例えば下記のようにします。

[source,yaml]
----
- image: quay.io/project/image:tag
  auth:
    username: $QUAY_USERNAME
    password: $QUAY_PASSWORD
----


## Machine executor (with Docker orb)

または、以下のように `machine` Executor を使用する方法もあります。

[source,yaml]
----
version: 2.1
orbs:
  docker: circleci/docker@1.4.0

workflows:
  my-workflow:
    jobs:
      - machine-job:
          context:
            - build-env-vars
            - docker-hub-creds

jobs:
  machine-job:
    machine: true
    steps:
      - docker/check:
          docker-username: DOCKERHUB_LOGIN  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: DOCKERHUB_PASSWORD  # DOCKER_PASSWORD is the default value
      - docker/pull:
          images: 'circleci/node:latest'
----


## Machine executor (with Docker CLI)

or with the CLI:

[source,yaml]
----
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/my_app
    steps:
      # Docker と docker-compose がプリインストールされています
      - checkout

      # プライベート Docker イメージを使用して固有の所有 DB を開始します
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker run -d --name db company/proprietary-db:1.2.3
----

## AWS ECR

CircleCI now supports pulling private images from Amazon's ECR service.

TIP: You can pull your private images from ECR repositories in any regions. However, for the best experience, we strongly
recommend you make a copy of your image in `us-east-1` region, and specify that `us-east-1` image for the Docker executor.
Our job execution infrastructure is in the `us-east-1` region so using `us-east-1` images speeds up the process of spinning
up your environment.

以下のいずれかの方法で、ECR のプライベート イメージを使用できるようになります。

1. CircleCI 標準のプライベート環境変数を使用して、AWS 認証情報を設定する
2. `aws_auth` を使用して、`.circleci/config.yml` に AWS 認証情報を指定する

[source,yaml]
----
version: 2
jobs:
  build:
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: AKIAQWERVA  # 文字列リテラル値を指定します
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY  # または、プロジェクトの UI 環境変数を参照するように指定します
----

Both options are virtually the same, however, the second option enables you to specify the variable name you want for the
credentials. これは、インフラストラクチャごとに異なる AWS 認証情報を持っている場合に便利です。 For example,
let's say your SaaS app runs the speedier tests and deploys to staging infrastructure on every commit while for Git tag
pushes, we run the full-blown test suite before deploying to production:

[source,yaml]
----
version: 2
jobs:
  build:
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_STAGING
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_STAGING
    steps:
      - run:
          name: "Every Day Tests"
          command: "testing...."
      - run:
          name: "Deploy to Staging Infrastructure"
          command: "something something darkside.... cli"
  deploy:
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_PRODUCTION
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_PRODUCTION
    steps:
      - run:
          name: "Full Test Suite"
          command: "testing...."
      - run:
          name: "Deploy to Production Infrastructure"
          command: "something something darkside.... cli"

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
----

## See also

* https://circleci.com/docs/2.0/configuration-reference[リファレンス]
