---
contentTags: 
  platform:
  - Server v2.x
  - Server Admin
---
= Setting Up HTTP Proxies
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to configure CircleCI server to use an HTTP proxy.
:icons: font
:toc: macro
:toc-title:

WARNING: CircleCI Server version 2.x は、リリースのサポートが終了しています。 リリースがサポートされているバージョンへのアップグレードについては、お客様のアカウントチームにご相談ください。

This section describes how to configure CircleCI to use an HTTP proxy.

toc::[]

== 概要

Amazon を通してプロキシを設定する場合は、読み進める前に以下の AWS ドキュメントをご確認ください。

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html#cli-configure-proxy-ec2[HTTP プロキシを使用する]

特に Services マシンについては、内部リクエストに対するプロキシの適用を避けてください。 To add these to the `NO_PROXY` rules, run:

```bash
export NO_PROXY=<services_box_ip>
```

In an ideal case, traffic to S3 will not be proxied, and will instead be bypassed by adding `s3.amazonaws.com,*.s3.amazonaws.com` to the `NO_PROXY` rule.

これらの命令は、未認証の HTTP プロキシが `10.0.0.33:3128`、Services マシンが `10.0.1.238` であり、GitHub Enterprise ホストとして `ghe.example.com` を使用することを想定しています。

CAUTION: The following proxy instructions must be completed **before** installing CircleCI on fresh VMs or instances. You must also configure JVM OPTs again as described below.

== Services マシンのプロキシ設定

Services マシンには多数のコンポーネントがあり、以下のネットワーク呼び出しを行う必要があります。

* *外部ネットワーク呼び出し* - Replicated は、CircleCI の管理コンソール用に使用しているベンダーサービスです。 CircleCI requires Replicated to make an outside call to validate the license, check for updates, and download upgrades. また Replicated は、Docker をダウンロードしてローカルマシンにインストールし、Docker コンテナを使用して S3 バケットの作成と設定を行います。 GitHub Enterprise may or may not be behind the proxy, but github.com will need to go through the proxy.
* **内部ネットワーク呼び出し**
** S3 トラフィックが HTTP プロキシを経由する必要がある場合、CircleCI はプロキシ設定をコンテナに渡す必要があります。
** Services マシン上の CircleCI インスタンスは Docker コンテナで実行されるため、すべての機能を維持するにはプロキシ設定をコンテナに渡す必要があります。

=== Services マシンのプロキシサポートの設定

For a static installation, not on AWS, SSH into the Services machine and run the following code snippet with your proxy address:

```bash
echo '{"HttpProxy": "http://<proxy-ip:port>"}' | sudo tee /etc/replicated.conf
(cat <<'EOF'
export HTTP_PROXY=<proxy-ip:port>
export HTTPS_PROXY=<proxy-ip:port>
EOF
) | sudo tee -a /etc/circle-installation-customizations

systemctl restart replicated\*
```

If you run in Amazon's EC2 service then you'll need to include `169.254.169.254` EC2 services as shown below:

```bash
echo '{"HttpProxy": "http://<proxy-ip:port>"}' | sudo tee /etc/replicated.conf
(cat <<EOF
export HTTP_PROXY=<proxy-ip:port>
export HTTPS_PROXY=<proxy-ip:port>
export NO_PROXY=169.254.169.254,<circleci-service-ip>,127.0.0.1,localhost,ghe.example.com
export JVM_OPTS="-Dhttp.proxyHost=<proxy-ip> -Dhttp.proxyPort=<proxy-port> -Dhttps.proxyHost=<proxy-ip> -Dhttps.proxyPort=<proxy-port> -Dhttp.nonProxyHosts=169.254.169.254|<circleci-service-ip>|127.0.0.1|localhost|ghe.example.com"
EOF
) | sudo tee -a /etc/circle-installation-customizations

systemctl restart replicated\*
```

NOTE: NOTE: If the proxy requires user authentication, you will need to add user authentication information into <proxy-ip> like below:

```bash
export HTTP_PROXY=http://<userid>:<password>@<proxy-ip>:<port>
export HTTPS_PROXY=https://<userid>:<password>@<proxy-ip>:<port>
```

NOTE: The above is not handled by by our enterprise-setup script and will need to be added to the user data for the Services Machine startup or done manually.

// not quite clear what is meant by this note... what's user data in this context?
// If the customer wants to apply the above setting automatically, they need to add them into ServiceBox's user data.
//  User data is a script, and the metadata of the EC2 instances, which is executed at lunchtime of an EC2 instance.
// https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts
// https://github.com/circleci/enterprise-setup/blob/master/templates/services_user_data.tpl

<<<
=== コーポレートプロキシ

WARNING: When our instructions ask if you use a proxy, you will also be prompted to input the address. It is **very important** that you input the proxy in the following format: `<protocol>://<ip>:<port>`. If you miss any part, then `apt-get` won't work correctly and the packages won't download.

=== Nomad クライアントの設定

==== External Network Calls

CircleCI uses `curl`  and `awscli` scripts to download initialization scripts, along with jars from Amazon S3. Both `curl` and `awscli` respect environment settings, but if you have allowed traffic from Amazon S3 you should not have any problems.

==== 内部ネットワーク呼び出し

* CircleCI JVM
** 他の Nomad クライアントマシンまたは Services マシンへの接続は、HTTP プロキシから除外する必要があります。
** GitHub Enterprise への接続は、HTTP プロキシから除外する必要があります。

* The following contains parts that may be impacted due to a proxy configuration:
** http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[Amazon EC2 metadata]. このデータに対しては、プロキシ設定を行うべきでは*ありません*。  プロキシ設定を行うと、マシンの設定が不適切になります。
** Amazon S3 traffic — note S3 discussion above
** Amazon EC2 API - EC2 API traffic may need to be proxied.  プロキシ設定が誤っている場合、ログに多数の障害 (タイムアウト障害) が記録されますが、CircleCI の機能が停止することはありません。

=== Nomad クライアントのプロキシ設定

* If you are installing CircleCI server on AWS using Terraform, you should add the below to your Nomad client launch configuration – these instructions should be added to `/etc/environment`.
* If you are using Docker refer to the https://docs.docker.com/engine/admin/systemd/#/http-proxy[Docker HTTP Proxy Instructions] documentation.
* If you are running a static installation, add the following to the server before installation:
+

```bash
#!/bin/bash

(cat <<EOF
HTTP_PROXY=<proxy-ip:port>
HTTPS_PROXY=<proxy-ip:port>
NO_PROXY=169.254.169.254,<circleci-service-ip>,127.0.0.1,localhost,ghe.example.com
JVM_OPTS="-Dhttp.proxyHost=<ip> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<proxy-ip> -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=169.254.169.254|<circleci-service-ip>|127.0.0.1|localhost|ghe.example.com"
EOF) | sudo tee -a /etc/environment

set -a
. /etc/environment
```
+
If your containers need to use a proxy server you will need to set the following schedulerer environment variables: `DOCKER_HTTP_PROXY`, `DOCKER_HTTPS_PROXY`, `NO_PROXY`, corresponding to those listed in https://docs.docker.com/network/proxy/[the Docker instructions]. This will ensure your containers have outbound/proxy access. For more information on creating configuration overrides, see the <<customizations#service-configuration-overrides, Customizations Guide>>.

=== トラブルシューティング

==== Can't access the Management Console
If you cannot access the CircleCI Management Console, but the Services machine seems to be running, try to SSH tunnel into the machine by running the following, substituting your proxy address and the IP address of your Services machine:

```bash
ssh -L 8800:<address you want to proxy through>:8800 ubuntu@<ip_of_services_machine>
```

==== REPL time out
If you experience a timeout when connecting to the REPL, you will need to allow access, through your corporate proxy, to the domains of any Clojure library repositories that are required to download dependencies for running the REPL.
```bash
sudo su
docker exec -it frontend /bin/bash
lein repl :connect 6005
```

Refer to the error output for guidance on which repositories need to be granted access. The list will be different for each corporate proxy, but following is an example list:

- repo1.maven.org
- build.clojure.org
- clojars.org
- repo.clojars.org

== データの永続化
Contact  https://support.circleci.com/hc/en-us[CircleCI Support] to discuss externalizing services for data persistence.
// Refer to the "Adding External Services to CircleCI Server v2.17" document for instructions to configure your installation for data persistence.

// <!--but this is an internal doc... should this say 'contact support for guidance on configuring for data persistance?-->
