---

version:
- Cloud
- Server
---
= Rename organizations and repositories
:page-layout: classic-docs
:page-liquid:
:page-description: This how-to guide goes over changing the names of organizations and repositories.
:icons: font
:toc: macro

:toc-title:

If you need to rename an organization or repository that you have previously connected to CircleCI, best practice is to follow the steps listed below. If you do not follow this process, it is possible you may lose access to your organization or repository settings, including **environment variables** and **contexts**.

[#rename-organizations-and-repositories]
== Steps to rename organizations and repositories

1. Rename organization or repository in your VCS
1. Go to the CircleCI web app using the new org/repo name, for example: `app.circleci.com/pipelines/<VCS>/<new-org-name>/<project-name>`
1. Confirm that your plan, projects, and settings have been transferred successfully
1. If desired, you are now free to create a new org/repo with the previously-used name in your VCS

[#see-also]
== 関連項目

* xref:contexts.adoc[Contexts]
* xref:env-vars.adoc[Environment variables]