---

version:
- Cloud
- Server v3.x
---
= Available CircleCI self-hosted runner platforms
:page-layout: classic-docs
:page-liquid:
:page-description: Find information on which platforms runner is supported on.
:icons: font
:toc: macro
:toc-title:

toc::[]

== Available CircleCI self-hosted runner platforms

CircleCI self-hosted runners are available on multiple platforms. サポート レベルは、次の 2 つのカテゴリに分かれます。

* <<Supported>>
* <<Preview>>

=== サポート対象

*Supported* Level platforms ensure that CircleCI self-hosted runners are both built and tested on their respective systems.

With a *Supported* platform, users receive the following:

* ドキュメントとベスト プラクティス
* サポート: CircleCI カスタマー エンジニアによる、アドバンスト サポートで規定されている通常のサービス レベル アグリーメント (SLA) の範囲内の問題解決支援

*Supported* CircleCI self-hosted runners are available on the following platforms:

* Ubuntu 18.04 以降 (x86_64 または ARM64)
* RHEL8-x86_64
* Intel + macOS
* macOS 11.2 以降 (Apple M1)
* Docker (x86_64)
* Kubernetes (x86_64)
* Windows Server 2019, 2016 (x86_64)

=== プレビュー

On *Preview* Level platforms, CircleCI self-hosted runners are currently in development, thus testing is not complete.

With a *Preview* platform, users receive the following:

* A full integration that is a work-in-progress -- thus, some manual configuration may be required to install, configure, and deploy
* 試作段階のドキュメントとベスト プラクティス
* Support: CircleCI Customer Engineers will provide assistance and guidance on best practices for installing, configuring, and operating CircleCI self-hosted runners
** Users are encouraged to provide feedback in order to rapidly improve the CircleCI self-hosted runner user experience and meet its necessary criteria as a *Supported* platform

*Preview* CircleCI self-hosted runners are available on the following platforms:

* 上記以外の Linux ディストリビューション - RHEL、SUSE、Debian など (x86_64 または ARM64)
* Kubernetes (ARM64)

NOTE: Given the active development of Preview CircleCI self-hosted runners, please https://circleci.com/contact/[contact us] if you
have questions around support for your environment and use-case(s). We also invite you to https://circleci.canny.io/cloud-feature-requests[share feedback]
and contribute to our https://discuss.circleci.com/t/self-hosted-runners-are-here/38159[runner discuss page] to help
prioritize development efforts from our team!