---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= マシンランナーの Windows へのインストール
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CircleCI セルフホストランナーの Windows へのインストール手順をわかりやすくご紹介しています。
:icons: font
:experimental:
:machine:
:windows:

{% include snippets/ja/runner-1.0-deprecation-post-brownout.adoc %}

{% include snippets/ja/runner-1.0-deprecation-first.adoc %} 以下のインストール方法は、Windows Server 2019 と Windows Server 2016 の両方について、Datacenter エディションでテスト済みです。 デスクトップエクスペリエンスとリモートデスクトップサービスを備えたその他のサーバー SKU でも動作するはずです。

このページでは、CircleCI のマシンランナーを Windows にインストールする方法を説明します。

以下のページでは、マシンランナーと、その依存関係 (Chocolatey、Git、Gzip など) を Windows サーバーにインストールする手順を説明します。

セットアップ中、CircleCI ジョブを実行する新しいローカル管理者ユーザーを作成します。 そのため、Windows サーバーで、ローカルユーザーを作成し、そのユーザーのリモートログオンを許可できる必要があります。 セルフホストランナーインスタンスは、ドメインコントローラーとして動作している Windows サーバーでは実行できません。*

[#prerequisites]
== Orb 開発キット

{% include snippets/runner/ja/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== 前提条件

{% include snippets/runner/ja/machine-runner-prereq.adoc %}

[#create-namespace-and-resource-class]
== セルフホストランナーの利用条件 ネームスペースとリソースクラスの作成

[.tab.machine-runner.Web_app_installation]
--
{% include snippets/ja/runner/install-with-web-app-steps.adoc %}
--

[.tab.machine-runner.CLI_installation]
--
{% include snippets/ja/runner/install-with-cli-steps.adoc %}
--

[#set-launch-agent-version]
== 1. ネームスペースとリソースクラスの作成

NOTE: CircleCI クラウド用の Windows マシンランナーをインストールする場合は、xref:#installation-steps[次のステップ]に進んでください。

{% include snippets/runner/ja/launch-agent-download.adoc %}

[#installation-steps]
== 2. 起動エージェントのバージョンを設定する（サーバーのみ）

. GitHub から https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Install-CircleCIRunner.ps1` スクリプト] をダウンロードし、アクセスしやすい場所に配置します。
. PowerShell を管理者として開き、スクリプトファイルを配置したディレクトリに移動します。
. 以下を PowerShell で実行します。
+
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
./Install-CircleCIRunner.ps1
```
+
PowerShell インターフェイスにインストール結果が出力されます。
. インストール中、マシンランナー (`launch-agent-config.yaml`) の設定ファイルが Notepad で開かれます。 必要な情報をファイルに記入してください (xref:runner-config-reference.adoc[セルフホストランナーの設定ファイルのリファレンス]を参照)。 設定ファイルはインストールディレクトリ (デフォルトは `C:\Program Files\CircleCI`) にあります。

{% include snippets/runner/ja/launch-agent-download.adoc %}

{% include snippets/ja/machine-runner-example.adoc %}

[#uninstall-reinstall-steps]
== 3.

マシンランナーをアンインストールすると、システムの再インストールの準備をします。

. GitHub から https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Uninstall-CircleCIRunner.ps1` script] をダウンロードし、アクセスしやすい場所に配置します。
. PowerShell を管理者として開き、スクリプトファイルを配置したディレクトリに移動します。
. 以下を PowerShell で実行します。
+
```
./Uninstall-CircleCIRunner.ps1
```

[#continuous-mode-vs.-single-task-mode-for-windows-self-hosted-runners]
== アンインストール・再インストール手順

マシンランナーをアンインストールすると、システムの再インストールの準備をします。 Windows マシンランナーの場合、これが **推奨モード** です。

Windows マシンランナーは、`continuous` モードで実行することも *可能* ですが、その場合、クリーンなジョブ環境が保証されません。  ジョブが期待どおりに実行されず、失敗する可能性があります。

[#troubleshooting]
== Windows セルフホストランナーの Continuous モードと Single task モード

Windows マシンランナーは、デフォルトでは、セルフホストランナーがジョブの実行に使用する基盤テクノロジーの信頼性を高めるために、 <<runner-config-reference#runner-mode,Single task モード>> で実行されます。