---

description: CircleCI セルフホストランナーをスケールする方法
contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= セルフホストランナーのスケーリング
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

[#introduction]
== はじめに

CircleCI セルフホストランナーの固定のコンピューティングフリートを保持するには、ジョブがキューに入る率に応じてワークロードが変動するため、不要なコストが発生する可能性があります。 このコストを削減するために、必要に応じてコンピューティングフリートをスケーリングできます。

link:https://circleci.com/blog/autoscale-self-hosted-runners-aws/[CircleCI ブログ] より、AWS AutoScaling グループを使ってセルフホストランナーをスケーリングするためのサンプルを使ったチュートリアルをご覧いただけます。

[#container-runner]
== コンテナランナー

Kubernetes でコンテナランナーを使用している場合、キューに入る作業量が増えると、Pod が自動的にスピンアップします。  これらの Pod は一時的な Pod であり、ジョブの実行が完了すると破棄されます。  Pod は作業に合わせて自動的にスケーリングされますが、Kubernetes クラスタの基盤となるコンピューティングはスケーリングされません。

[#scaling-data]
== データのスケーリング

マシンランナーやコンテナランナー用の Kubernetes クラスタをスケールするためのソリューションをセットアップする際に役立つ API エンドポイントが複数あります。

* <<runner-api#get-apiv2runnertasks, 未処理のタスク>>
* <<runner-api#get-apiv2runnertasksrunning, 実行中のタスク>>
* <<runner-api#get-apiv2runner,リソースクラスのリスト>>

スケーリングソリューションにより、上記のエンドポイントを使って実行可能な待機タスクの合計数を計算することができます。 タスクデータエンドポイントのスコープは 1 つのリソースクラスにスコープされるため、使用可能なすべてのリソースクラスを照会し、実行中のタスクの合計数を取得することが重要です。

If you're using machine runners, you can devise a scaling solution to add more machine runners to the resource class that has more pending work.

NOTE: You will also need to be aware of your plan's concurrency limit to avoid starting compute which cannot be used. This can be found on the CircleCI link:https://circleci.com/pricing/[Plans page].

[#agent-configuration]
== Agent configuration for machine runner

There are some machine runner configuration settings which can be used by your scaling solution, particularly to assist resource cleanup when the demand drops:

* <<runner-config-reference#runner-mode,ランナーモード>>
** Choosing `single-task` mode will cause machine runner to shut down after a single task. This is useful if using completely ephemeral compute as the resources can be automatically recycled upon machine runner exit.
** Choosing `continuous` mode will cause the machine runner to poll for new tasks after completing a task. Your scaling solution will need to monitor the task workload and actively shutdown unused machine runners.
* <<runner-config-reference#runner-idle_timeout,ランナーのアイドル状態のタイムアウト>>
** 需要が低い期間のリソースの自動リサイクルに、妥当なタイムアウトを設定することができます。