---
version:
- Cloud
- Server v3.x
---
= CircleCI ランナーのインストール
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

== 前提条件

インストール プロセスでは、システムに以下のユーティリティをインストール済みであることを前提としています。

* <<local-cli#installation, CircleCI CLI>>
* curl (macOS ではデフォルトでインストール済み)
* sha256sum (Linux では apt または yum により coreutils の一部としてインストール、macOS では brew によりインストール)
* バージョン 235 以降の systemd (Linux のみ)
* sepolicy (RHEL 8 のみ)
* rpmbuild (RHEL 8 のみ)
* ユーザーの作成権限および /opt 以下のディレクトリの作成権限

ジョブを実行するには、マシンに次のツールを用意する必要があります。

* tar
* gzip
* coreutils (Linux のみ)
* git (推奨。ただし任意)

== 認証

NOTE: 以下のコマンドを実行できるのは、組織のオーナーまたは管理者だけです。

認証のために、下記手順を実行して名前空間と認証トークンを作成する必要があります。

. 組織のランナー リソース用の名前空間を作成します。
+
NOTE: 作成できる名前空間は、組織ごとに 1 つだけです。 Orb を既に使用中の場合、この名前空間は Orb で使用しているのと同じものになります。 
+ 
次のコマンドを実行します。 
+
```
circleci namespace create <name> <vcs-type> <org-name>
```
+
For example, if your GitHub URL is `\https://github.com/circleci`, then use: `circleci namespace create my-namespace github circleci`.
. 次のコマンドを実行して、名前空間内にランナー用のリソース クラスを作成します。
+ 
NOTE: リソース クラスを作成するコマンドには、新しく作成した名前空間が必要です。
+
```
circleci runner resource-class create <name>/<resource-class> <description> --generate-token
``` 
+
例: `circleci runner resource-class create my-namespace/my-resource-class my-description`
+
NOTE: リソース クラスとトークンを作成するには、VCS プロバイダーの組織管理者権限を持っている必要があります。
+
CAUTION: トークンを再取得することはできませんので、必ず安全な場所に保管してください。

== インストール

=== ローンチ エージェント バイナリのダウンロードとチェックサムの検証
[[download]]
ローンチ エージェントは次のスクリプトでインストールできます。このスクリプトでは、ベースのインストール場所に `opt/circleci` を指定しています。

まず、インストール対象のプラットフォームに応じて、次のいずれかの変数を設定します。

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| インストール対象
| 変数

| Linux x86_64
| `platform=linux/amd64`

| Linux ARM64
| `platform=linux/arm64`

| macOS x86_64
| `platform=darwin/amd64`

| macOS M1
| `platform=darwin/arm64`
|===

次に、`circleci-launch-agent` バージョンを設定します。 クラウド版 CircleCI のランナーは、サポートされている最新バージョンに自動的に更新されます。 CircleCI Server の場合、特定のランナー バージョンの相互運用性は検証されていますが、ランナーは自動更新されません。 CircleCI Server 用の `circleci-launch-agent` バージョンについては、<<runner-for-server-compatibility, こちらの表>>を参照してください。

クラウド版 CircleCI の場合、以下を実行します。
```bash
export base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
export agent_version=$(curl "${base_url}/release.txt")
```

For server v3.1.0 and up, run the following, substituting `<launch-agent-version>` with the correct launch agent version for the version of server you are running (see <<runner-for-server-compatibility>> to find the correct version):
```bash
export agent_version="<launch-agent-version>"
```

最後に、次のスクリプトを実行して、バイナリをダウンロードして検証し、インストールします。
```bash
# ランナー ディレクトリのセットアップ
prefix=/opt/circleci
sudo mkdir -p "$prefix/workdir"

# ローンチ エージェントのダウンロード
echo "Using CircleCI Launch Agent version $agent_version"
echo "Downloading and verifying CircleCI Launch Agent Binary"
base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
curl -sSL "$base_url/$agent_version/checksums.txt" -o checksums.txt
file="$(grep -F "$platform" checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')"
mkdir -p "$platform"
echo "Downloading CircleCI Launch Agent: $file"
curl --compressed -L "$base_url/$agent_version/$file" -o "$file"

# ダウンロードの検証
echo "Verifying CircleCI Launch Agent download"
grep "$file" checksums.txt | sha256sum --check && chmod +x "$file"; sudo cp "$file" "$prefix/circleci-launch-agent" || echo "Invalid checksum for CircleCI Launch Agent, please try download again"
```

=== プラットフォームごとのインストール方法

次のセクションでは、プラットフォーム別のインストール方法を説明します。

* xref:runner-installation-linux.adoc[Linux]
* xref:runner-installation-mac.adoc[macOS]
* xref:runner-installation-windows.adoc[Windows]
* xref:runner-installation-docker.adoc[Docker]
* xref:runner-on-kubernetes.adoc[Kubernetes]

他のプラットフォームに関する詳細は、「xref:runner-overview.adoc#available-circleci-runner-platforms[利用可能な CircleCI ランナー プラットフォーム]」を参照してください。

== CircleCI Server とランナーの互換性
_CircleCI ランナーは CircleCI Server v3.1.0 以上で使用できます。_

CircleCI Server のマイナー バージョンはそれぞれ、特定バージョンの `circleci-launch-agent` と互換性があります。 以下の表に、CircleCI Server バージョンごとに、ランナーのインストール時に使用できる `circleci-launch-agent` のバージョンを示します。

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| CircleCI Server のバージョン  
| ローンチ エージェントのバージョン

| 3.0             
| ランナーはサポートされていません

| 3.1            
| 1.0.11147-881b608

| 3.2
| 1.0.19813-e9e1cd9
|===

== 関連リソース

- https://github.com/CircleCI-Public/runner-preview-docs/[Docker Hub 上の CircleCI ランナー イメージ (英語)]
- https://github.com/CircleCI-Public/circleci-runner-docker[GitHub 上の CircleCI ランナー イメージ (英語)]
- https://circleci.com/docs/ja/[CircleCI ドキュメント (CircleCI 公式ドキュメントをまとめた Web サイト)]
- https://docs.docker.com/[Docker ドキュメント (英語)]
