---

description: CircleCI ランナーをスケーリングする方法
version:
- クラウド
- Server v3.x
---
= ランナーのスケーリング
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

== はじめに

CircleCI ランナー用に固定のコンピューティングフリートを保持するには、ジョブがキューに入る率に応じてワークロードが変動するため、不要なコストが発生する可能性があります。 このコストを削減するために、コンピューティングフリートを需要に応じてスケーリングすることができます。

== データのスケーリング

下記は、データをスケールするためのソリューションのセットアップに役立つ API エンドポイントです。

* <<runner-api#get-apiv2runnertasks, 未処理のタスク>>
* <<runner-api#get-apiv2runnertasksrunning, 実行中のタスク>>
* <<runner-api#get-apiv2runner,リソースクラスのリスト>>

スケーリングソリューションにより上記のエンドポイントを使って実行可能な待機タスクの合計数を計算することができます。 タスクデータエンドポイントのスコープは 1つのリソースクラスにスコープされるため、使用可能なすべてのリソースクラスを照会して、実行中のタスクの合計数を取得することが重要です。

それにより、新しいクレームエージェントを追加するリソースクラスを自由に決定できます。 リソースクラス間でのタスクの分配は、CircleCI が行う受信ワークロードと内部ディスパッチにより決まります。

**注:** 使用できないコンピューティングを開始してしまわないよう、プランの同時実行制限にも注意する必要があります。 これは CircleCI の https://circleci.com/pricing/[料金プランのページ]でご確認いただけます。 Scale プランと Custom プランのお客様は、この件に関してはサポートチームにご連絡ください。

== エージェントの設定

お客様のスケーリングソリューションが特に需要が減った際にリソースのクリーンアップをサポートするために使う `launch-agent` 設定があります。

* <<runner-config-reference#runner-mode,ランナーモード>>
** `single-task` モードを選択すると、`launch-agent` は一つのタスクが終わるとシャットダウンします。 これは、`launch-agent` の終了時にリソースが自動的にリサイクルされるため、完全に一時的なコンピューティングを使用する場合に便利です。
** `continuous` モードを選択すると、`launch-agent` はタスクの終了後に新しいタスクをポーリングします。 スケーリングソリューションはタスクのワークロードを監視し、使用していない `launch-agents` を積極的にシャットダウンする必要があります。
* <<runner-config-reference#runner-idle_timeout,Runner Idle Timeout>>
** Setting a reasonable timeout can be used for automatic resource recycling during periods of lower demand.