---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= マシンランナーの Windows へのインストール
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CircleCI セルフホストランナーの Windows へのインストール手順をわかりやすくご紹介しています。
:icons: font
:toc: macro

:toc-title:
:machine:
:windows:

{% include snippets/ja/runner-platform-prerequisites.adoc %}

This page describes how to install CircleCI's machine runner on Windows. This has been tested for Windows Server 2019 and Windows Server 2016, both in Datacenter Edition. Other Server SKUs with Desktop Experience and Remote Desktop Services should also work.

以下のページでは、マシンランナーと、その依存関係 (Chocolatey、Git、Gzip など) を Windows サーバーにインストールする手順を説明します。

セットアップ中、CircleCI ジョブを実行する新しいローカル管理者ユーザーを作成します。 そのため、Windows サーバーで、ローカルユーザーを作成し、そのユーザーのリモートログオンを許可できる必要があります。

*また、このセットアップをドメイン環境で行う際には、Windows サーバーがドメインメンバーである必要があります。 セルフホストランナーインスタンスは、ドメインコントローラーとして動作している Windows サーバーでは実行できません。*

[#prerequisites]
== インストール手順

{% include snippets/runner/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== アンインストール・再インストール手順

マシンランナーをアンインストールすると、システムの再インストールの準備をします。

[#create-namespace-and-resource-class]
== Windows セルフホストランナーの Continuous モードと Single task モード Create namespace and resource class

[.tab.machine-runner.Web_app_installation]
--
{% include snippets/runner/install-with-web-app-steps.adoc %}
--

[.tab.machine-runner.CLI_installation]
--
{% include snippets/runner/install-with-cli-steps.adoc %}
--

[#set-launch-agent-version]
== トラブルシューティング Set launch agent version (server only)

NOTE: If you are installing the Windows machine runner for CircleCI cloud, skip ahead to the xref:#installation-steps[next step].

{% include snippets/runner/launch-agent-download.adoc %}

[#installation-steps]
== 3. Machine runner installation on Windows

. Download the https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Install-CircleCIRunner.ps1` script] from GitHub to an easily accessible location.
. Open PowerShell as an administrator and navigate to the directory where you placed the script file.
. Run the following in your PowerShell:
+
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
./Install-CircleCIRunner.ps1
```
+
The installation will be output into your PowerShell interface.
. As part of the installation, the configuration file for the machine runner (`launch-agent-config.yaml`) will open in Notepad. Please fill the file out with the requested information (see xref:runner-config-reference.adoc[Self-hosted Runner Configuration Reference]). The configuration file is located in the installation directory, `C:\Program Files\CircleCI`, by default.

After setup completes, the machine runner starts automatically and begins looking for jobs to process.

{% include snippets/machine-runner-example.adoc %}

[#uninstall-reinstall-steps]
== Uninstall / reinstall steps

Uninstalling machine runners will prepare the system for installation again.

. Download the https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Uninstall-CircleCIRunner.ps1` script] from GitHub to an easily accessible location.
. Open PowerShell as an administrator and navigate to the directory where you placed the script file.
. Run the following in your PowerShell:
+
```
./Uninstall-CircleCIRunner.ps1
```

[#continuous-mode-vs.-single-task-mode-for-windows-self-hosted-runners]
== Continuous mode vs. single task mode for Windows self-hosted runners

By default, Windows machine runners run in <<runner-config-reference#runner-mode,single task mode>> in order to ensure high reliablity of the underlying technology that the self-hosted runner uses to execute jobs. This is the **recommended mode** for Windows machine runners.

A Windows machine runner *can* be run in `continuous` mode, however, doing so eliminates the guarantee of a clean job environment.  This may translate into jobs not executing as expected and failing.

[#troubleshooting]
== Troubleshooting

Refer to the <<troubleshoot-self-hosted-runner#troubleshoot-machine-runner,Troubleshoot Machine Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running machine runner on Windows.