---
version:
- Cloud
- Server v3.x
---
= ランナーの設定方法
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

== ランナーの設定方法

ローンチ エージェントの設定や、ローンチ エージェントとサーバーの通信方法およびタスク エージェントの起動方法の設定は、YAML ファイルを使用して行います。

設定ファイルの形式は次のとおりです。下記で説明する各種パラメーターを使用します。

```yaml
api:
  auth_token: AUTH_TOKEN
runner:
  name: RUNNER_NAME
```

NOTE: ローンチ エージェントは、環境変数を使って設定することもできます。 環境変数が設定されている場合、YAMLファイルよりも優先されます。

=== api.auth_token
`$LAUNCH_AGENT_API_AUTH_TOKEN`

This is a token used to identify the launch agent to CircleCI and can be generated by the xref:local-cli.adoc[CircleCI CLI]. 既存のトークンは複数のインストール環境で共用できますが、このトークンでは特定の `resource_class` しか指定できません。

=== api.url
`$LAUNCH_AGENT_API_URL`

This is a fully qualified URL used by runner to communicate with CircleCI. This variable is only required for runners installed for the 3.2 or later version of server.

例

```yaml
api:
  url: https://circleci.example.com
```

=== runner.name
`$LAUNCH_AGENT_RUNNER_NAME`

`RUNNER_NAME` には、このローンチ エージェントに割り当てる一意の名前を設定します。 CircleCI UI でのステータスやジョブ結果の確認時にランナーを特定できるよう、名前にはマシンのホスト名を使用することをお勧めします。

=== logging.file
`$LAUNCH_AGENT_LOGGING_FILE`

This controls the file where the launch agent and task agent logs will go. See xref:runner-overview.adoc#circleci-runner-operation[CircleCI runner operation] for more information on the launch-agent and the task-agent.

例

```yaml
logging:
  file: /Library/Logs/com.circleci.runner.log
```

=== runner.command_prefix
`$LAUNCH_AGENT_RUNNER_COMMAND_PREFIX`

This prefix takes a YAML list of arguments and enables you to customize how the task agent process is launched. ここでカスタム スクリプトを使用すると、タスク ランナーの前後で任意のコマンドを実行できます。 指定した引数が実行され、完了時にスクリプトから正しい終了コードが返されるよう特に注意してください。

例

```yaml
runner:
  command_prefix: ["sudo", "-niHu", "USERNAME", "--"]
```

=== runner.working_directory
`$LAUNCH_AGENT_RUNNER_WORK_DIR`

This directory takes a fully qualified path and allows you to control the default working directory used by each job. If the directory already exists, the task agent will need permissions to write to the directory. 設定したディレクトリが存在しない場合は、タスク エージェントにそのディレクトリの作成権限を付与する必要があります。 設定値に `%s` を含めた場合、この変数はジョブごとに異なる値で置き換えられます。 Note that these directories will not automatically be removed.

例

```yaml
runner:
  working_directory: /opt/circleci/workdir
```

=== runner.cleanup_working_directory
`$LAUNCH_AGENT_RUNNER_CLEANUP_WORK_DIR`

This flag enables you to control the working directory cleanup after each job.

値の例:

* `true`
* `false`

NOTE: デフォルト値は `false` です。

例

```yaml
runner:
  cleanup_working_directory: true
```

=== runner.mode
`$LAUNCH_AGENT_RUNNER_MODE`

This parameter allows you to specify whether you want to terminate this runner instance upon completion of a job (`single-task`) or to continuously poll for new available jobs (`continuous`).

値の例:

* `continuous`
* `single-task`

NOTE: The default value is `continuous`.

例

```yaml
runner:
  mode: continuous
```

=== runner.max_run_time
`$LAUNCH_AGENT_RUNNER_MAX_RUN_TIME`

この値を設定することで、タスク エージェントの各ジョブについてデフォルトの最大実行時間を上書きできます。 Note that the value is a string with the following unit identifiers `h`, `m` or `s` for hour, minute, and seconds respectively:

以下に有効な例を示します。

* `72h` - 3 日間
* `1h30m` - 1 時間 30 分
* `30s` - 30 秒
* `50m` - 50 分
* `1h30m20s` - An overly specific (yet still valid) duration

NOTE: デフォルト値は 5 時間です。

例

```yaml
runner:
  max_run_time: 5h
```


==== ジョブ タイムアウトとドレイン タイムアウトをカスタマイズする

If you would like to customize the job timeout setting, you can “drain” the job by sending the launch agent a termination (TERM) signal, which then causes the launch agent to attempt to gracefully shutdown. When this TERM signal is received, the launch agent enters “draining” mode, preventing the launch agent from accepting any new jobs, but still allowing any current active job to be completed. At the end of “draining,” the launch agent then signals the task agent to cancel any active job (by sending it a TERM signal).

NOTE: If the task agent does not exit a brief period after the TERM, the launch agent will manually kill it by sending it a KILL signal.

ドレインは、次の 2 つのうちいずれかの条件で終了します。

* The task has been in the draining state for longer than the configured `max_run_time`
* An additional TERM signal is received by the launch agent during “draining”

=== runner.idle_timeout
`$LAUNCH_AGENT_RUNNER_IDLE_TIMEOUT`

このタイムアウトにより、指定された時間内にタスクが要求されなかった場合に、ローンチエージェントを終了させることができます。 The value is a string with the following unit identifiers: `h`, `m` or `s` for hours, minutes, and seconds respectively (e.g., `5m` is 5 minutes).

NOTE: デフォルトでは、非アクティブな状態によりタイムアウトすることはありません。

例

```yaml
runner:
  idle_timeout: 1h
```

=== runner.ssh.advertise_addr
`$LAUNCH_AGENT_RUNNER_SSH_ADVERTISE_ADDR`

This parameter enables the “Rerun job with SSH” feature. Before enabling this feature, there are <<#considerations-before-enabling-ssh-debugging, *important considerations that should be made*>>.

The address is of the form `*host:port*` and is displayed in the “Enable SSH” and “Wait for SSH” sections for a job that is rerun.

NOTE: While the presence of the `runner.ssh.advertise_addr` variable enables the “Rerun job with SSH” feature, the value it holds is for publishing purposes only in the web UI. このアドレスは、ランナーがインストールされているマシンの実際のホストとポートに一致する必要はなく、プロキシ設定であっても構いません。

例

```yaml
runner:
  ssh:
    advertise_addr: HOSTNAME:54782
```

==== SSH デバッグを有効にする前に注意すべき事項

Task agent runs an embedded SSH server and agent on a dedicated port when the “Rerun job with SSH” option is activated. この機能は、ランナーがインストールされているシステム上の他の SSH サーバーやエージェントには影響しません。

* SSH サーバーが使用するホストポートは、現在、`*54782*`に固定されています。 このポートがブロックされておらず、SSH 接続が可能であることを確認してください。 同じホストに複数のローンチエージェントがインストールされていると、ポートの競合が発生する場合があります。
* The SSH server will inherit the same user privileges and associated access authorizations as the task agent, defined by the <<#runner-command_prefix, runner.command_prefix parameter>>.
* SSH サーバーは公開鍵認証に設定されます。 Anyone with permission to initiate a job can rerun it with SSH. However, only the user who initiated the rerun will have their SSH public keys added to the server for the duration of the SSH session.
* SSH でジョブを再実行すると、キャンセルされない限り、SSH サーバーに接続されていると *2時間* 、接続されない場合は *10分間* 、ジョブがオープンな状態になります。 この状態では、ジョブは組織の同時実行制限に反することになり、タスクエージェントは他のジョブを処理できなくなります。 そのため、デバッグが終了したら、SSH の再実行ジョブを明示的に（Web UI または CLI を通じて）キャンセルすることをお勧めします。
