---
version:
- Cloud
- Server v3.x
---
= CircleCI Self-hosted Runner Installation on macOS
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This page describes how to install CircleCI self-hosted runner on macOS.

{% include snippets/ja/runner-platform-prerequisites.adoc %}

toc::[]

== Create a CircleCI self-hosted runner configuration

CircleCI ランナーを実行するユーザーを選択します。 以下の手順では、選択するユーザーを `USERNAME` としています。 The `USERNAME` refers to the user on the machine that the agent will be installed on, _not_ the CircleCI account username.

下記のテンプレートを、大文字で記載されたパラメーターを適切な値で置き換えて完成させます。 完成したら、`launch-agent-config.yaml` として保存します。

```yaml
api:
  auth_token: AUTH_TOKEN
  # CircleCI Server の場合 url に CircleCI Server のホスト名を設定します。 例:
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  command_prefix : ["sudo", "-niHu", "USERNAME", "--"]
  working_directory: /tmp/%s
  cleanup_working_directory: true

logging:
  file: /Library/Logs/com.circleci.runner.log
```

== Install the CircleCI self-hosted runner configuration

Create a directory as `root` to hold the CircleCI self-hosted runner configuration:

```shell
sudo mkdir -p '/Library/Preferences/com.circleci.runner'
```

Copy the previously created `launch-agent-config.yaml` into the directory and change its permissions to `600`:

```shell
sudo cp "launch-agent-config.yaml" "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

```shell
sudo chmod 600 "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

== Create and install the `launchd .plist`

Create a `com.circleci.runner.plist` file. Please note that if you choose to create the file with Vim, you will likely need to prefix `sudo` to the command. The path to the file should be the following: `/Library/LaunchDaemons/com.circleci.runner.plist`, owned by `root`, with permissions `644`.

```shell
sudo chown root: /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chmod 644 /Library/LaunchDaemons/com.circleci.runner.plist
```

Copy the following to the new `/Library/LaunchDaemons/com.circleci.runner.plist` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.circleci.runner</string>

        <key>Program</key>
        <string>/opt/circleci/circleci-launch-agent</string>

        <key>ProgramArguments</key>
        <array>
            <string>circleci-launch-agent</string>
            <string>--config</string>
            <string>/Library/Preferences/com.circleci.runner/launch-agent-config.yaml</string>
        </array>

        <key>RunAtLoad</key>
        <true/>

        <!-- ランナーは実行状態を維持する必要があります -->
        <key>KeepAlive</key>
        <true/>

        <!-- ランナーによるリソースの使用が macOS で制限されないようにする設定です-->
        <key>ProcessType</key>
        <string>Interactive</string>

        <!-- 失敗時または更新後にランナーを再起動する頻度を増やします -->
        <key>ThrottleInterval</key>
        <integer>3</integer>

        <!-- ランナーがシャットダウンするまで 10 分間待機します (ランナー自体はタスクが完了するまで待機します) -->
        <key>ExitTimeOut</key>
        <integer>600</integer>

        <!-- ログの出力とローテーションの設定はランナー固有のものを使用します -->
        <key>StandardOutPath</key>
        <string>/dev/null</string>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
    </dict>
</plist>
```

== `launchd` サービスを有効にする

これで、サービスをロードできます。

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

NOTE: 2 回目以降に有効化の手順を実行する場合、次の手順で既存サービスをアンロードする必要があります。
```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

{% include snippets/runner-config-reference.adoc %}

== サービスの実行状態を確認する

Open the pre-installed macOS application *Console*. In this application, you can view the logs for the CircleCI agent under *Log Reports*. Look for the logs called `com.circleci.runner.log` in the list. You can also find this file by navigating to *Library > Logs*.