---

description: Learn how to scale CircleCI self-hosted runners.
version:
- Cloud
- Server v3.x
---
= Scaling Self-hosted Runners
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

== はじめに

Maintaining a fixed compute fleet for CircleCI self-hosted runners can incur unnecessary costs as the workload can fluctuate depending on the rate at which jobs are queued. このコストを削減するために、コンピューティングフリートを需要に応じてスケールすることができます。

== データのスケーリング

データをスケールするためのソリューションのセットアップに役立つ API エンドポイントは複数あります。

* <<runner-api#get-apiv2runnertasks, 未処理のタスク>>
* <<runner-api#get-apiv2runnertasksrunning, 実行中のタスク>>
* <<runner-api#get-apiv2runner,リソースクラスのリスト>>

スケーリングソリューションにより、上記のエンドポイントを使って実行可能な待機タスクの合計数を計算することができます。 タスクデータエンドポイントのスコープは 1つのリソースクラスにスコープされるため、使用可能なすべてのリソースクラスを照会して、実行中のタスクの合計数を取得することが重要です。

そうすることで、新しいクレームエージェントを追加するリソースクラスを自由に決定できます。 リソースクラス間でのタスクの分配は、CircleCI が行う受信ワークロードと内部ディスパッチによって決まります。

**注:** 使用できないコンピューティングを開始してしまわないよう、プランの同時実行制限にも注意する必要があります。 これは CircleCI の https://circleci.com/ja/pricing/[料金プランのページ]でご確認いただけます。 Scale プランと Custom プランのお客様は、サポートチームに連絡をしてこの情報を確認してください。

== エージェントの設定

需要が減った際にリソースのクリーンアップをサポートするためにスケーリングソリューションが使用する `launch-agent` の設定はいくつかあります。

* <<runner-config-reference#runner-mode,ランナーモード>>
** `single-task` モードを選択すると、`launch-agent` は一つのタスクが終わるとシャットダウンします。 このモードは、`launch-agent` の終了時にリソースが自動的にリサイクルされるので、完全に一時的なコンピューティングを使用する場合に便利です。
** `continuous` モードを選択すると、`launch-agent` はタスクの終了後に新しいタスクをポーリングします。 スケーリングソリューションはタスクのワークロードを監視し、使用していない `launch-agents` を積極的にシャットダウンする必要があります。
* <<runner-config-reference#runner-idle_timeout,ランナーのアイドル状態のタイムアウト>>
** 需要が低い期間のリソースの自動リサイクルに、妥当なタイムアウトを設定することができます。