---

version:
- クラウド
- Server v4.x
- Server v3.x
---
= ランナーのコンセプト
:page-layout: classic-docs
:page-liquid:
:page-description: Conceptual Overview for CircleCI's self-hosted runner.
:icons: font
:toc: macro
:toc-title:

toc::[]

[#namespaces-and-resource-classes]
== 名前空間とリソースクラス

セルフホストランナーには名前空間とリソースクラスの両方が必要です。

**名前空間** は、CircleCI 組織が要求する一意の識別子です。 各組織が要求できる一意の名前空間は 1 つだけで、後から変更することはできません。 通常、選択される名前空間は VCS の組織名を小文字で表したものです (推奨)。

**リソースクラス** は、CircleCI ジョブとそのジョブを処理するために識別されたランナーのタイプを一致させるためのラベルです。 リソースクラスの最初の部分は組織の名前空間です。 たとえば、 `circleci/documentation` などです。 リソースクラスは、セルフホストランナーのインストールプロセスを実行する際に作成されます。

リソースクラスを使用すると、セルフホストランナーのプールを特定して、特定の場所にジョブを送信するように設定できます。 たとえば、macOS を実行する複数のマシンと Linux を実行する複数のマシンがある場合、ぞれぞれに対して、 `orgname/macOS` と `orgname/linux` のリソースクラスを作成することができます。 `.circleci/config.yml` のジョブレベルでは、リソースクラスに基づいて、ジョブの送信先となるセルフホストランナーのリソースを関連付けることができます。

オプションで、リソースクラスに説明をつけることもできます。

すでに <<orb-intro#, Orb>> を使用されているお客様は、既存の名前空間があるのでこ注意ください。 セルフホストランナーの名前空間は、Orb で使用しているのと同じ名前空間です。 名前空間を変更する必要がある場合は、 https://support.circleci.com/hc/ja[サポート] にお問い合わせください。

[#task-agent]
== Task-agent

The task-agent handles running a task retrieved and configured by the container runner or machine runner. Task-agents run with the same privileges as `circleci`.

[#container-agent]
== Container-agent

The container-agent gets installed with container runner. Container-agent polls CircleCI for jobs, spins up ephemeral pods with an injected task-agent, and executes each job within each pod. The pods are torn down after the jobs have completed.

[#launch-agent]
== Launch-agent

The launch-agent manages gathering the information required to run a task with machine runner (defined as a parallel run of a job) while also downloading and launching the task-agent process.

The system has been designed to allow admins to configure the task-agent to run with a lower level of privileges than the launch-agent. Any user who is able to execute a job will be able to gain the same privileges as the task-agent. The launch-agent will run as `root`, but the task-agent will run as `circleci`.

[#self-hosted-runner-concurrency]
== セルフホストランナーの同時実行

Rather than limit the total number of registered self-hosted runners, CircleCI's self-hosted runners are limited by the total number of self-hosted runner jobs (tasks) across your organization.

[#public-repositories]
== パブリックリポジトリ

CircleCI's self-hosted runners are not recommended for use with public projects that have the **Build forked pull requests** setting enabled. このようなパブリックプロジェクトでは、他のユーザーがリポジトリをフォークし、コードをコミットしてプルリクエストを作成できるため、悪意のあるアクターによってマシンに変更が加えられたり、マシンでコードが実行されたりする可能性があります。 Untrusted jobs running on your CircleCI's self-hosted runner pose significant security risks for your machine and network environment, especially if your machine persists its environment between jobs. これには次のようなリスクが含まれます。

* 悪意のあるプログラムがマシンで実行される。
* マシンのセルフホストランナーサンドボックスの外部で操作が行われる。
* マシンのネットワーク環境に外部からアクセスされる。
* 不要なデータや危険なデータがマシンに保持される。

NOTE: デフォルトでは、各組織が要求できる名前空間は 1 つに制限されています。 これは、名前の占有や名前空間のノイズを制限するためのポリシーです。 名前空間を変更する必要がある場合は、 https://support.circleci.com/hc/ja[サポート] にお問い合わせください。