---
version:
- クラウド
- Server v3.x
---
= CircleCI セルフホストランナーに関してよく寄せられるご質問 
:page-layout: classic-docs
:page-liquid:
:page-description: ここでは、CircleCI セルフホストランナーに関してよく寄せられるご質問に回答します。 
:icons: font
:toc: macro
:toc-title:

このページでは、CircleCI セルフホストランナーに関してよく寄せられるご質問に回答します。

toc::[]

== CircleCI セルフホストランナーのセキュリティモデルは、どのようになっていますか。

CircleCI セルフホストランナーをインストールする際に、ジョブを実行するユーザーを選択できます。 このユーザーにジョブの実行に必要な権限のみを付与するかどうかは、お客様の判断でお決めいただけます。

CAUTION: ジョブに Docker デーモンへのアクセスを許可することは、ユーザーにマシンへの root アクセスを許可するのと同じことです。

== ジョブに必要な依存関係をインストールする方法を教えてください。

依存関係をインストールする方法は、主に 2 つあります。

* 必要な依存関係のインストールをジョブに許可する

これは最も柔軟性が高い方法ですが、ツールを全体にインストール、または重複しない方法で (作業ディレクトリなどに) ツールをインストールできる権限をジョブに付与する必要があります。

* 依存関係をセルフホストランナーマシンにプリインストールする

この方法は最も安全な方法ですが、ジョブの依存関係が変わった場合、セルフホストランナーマシンの再設定が必要になります。

== どのような接続が必要ですか。

ジョブの取得と実行の際に CircleCI に接続するために、`runner.circleci.com` と `circleci-binary-releases.s3.amazonaws.com` へのアウトバウンド HTTPS 接続が必要です。

NOTE: セルフホストランナーにインバウンド接続は必要ありません。 それ以外では、ジョブの内容に応じた接続が必要になります。

CAUTION: チェックアウト ステップでは、VCS プロバイダーへのアクセスが必要です。 キャッシュ、ワークスペース、アーティファクトを使用する場合は、`circle-production-customer-artifacts.s3.amazonaws.com` へのアウトバウンド HTTPS 接続が必要になります。

== CircleCI セルフホストランナーを使用する場合、キャッシュ、ワークスペース、アーティファクトはどのように機能しますか。

キャッシュ、ワークスペース、アーティファクトは、ジョブ間でデータを永続化し、ビルドを迅速化するために導入できる方法です。 キャッシュ、ワークスペース、アーティファクトは、S3 の AWS us-east-1 リージョンに保存されます。 セルフホストランナーが別のリージョンでセットアップされている場合、パフォーマンスが低下する可能性があります。

これらの概念の詳細については、下記をご覧ください。

* <<caching#, キャッシュ>>
* <<workspaces#, ワークスペース>>
* <<artifacts#, アーティファクト>>

You can also find out more on the <<persist-data#, Persisting Data>> page.

アーティファクトのストレージを自社で完全に管理したい場合は、組み込みのステップを使用せず、ご希望のストレージバックエンドに直接アーティファクトをアップロードすることをお勧めします。

== ジョブ間の状態管理に関するベストプラクティスを教えてください。

セルフホストランナー自体には、この点に関する厳格な決まりはありません。 セルフホストランナーは、ジョブごとに専用の作業ディレクトリを作成し、後で削除するように設定できますが、これは必須ではありません。 デフォルトでは、作業ディレクトリの外にファイルを配置することも制限されていません。

一般的には、再現性が高まるよう、ジョブが状態に依存することは最小限に抑えることをお勧めします。 そのためには、前のジョブの結果に依存せずに確実にジョブが実行されるように、ジョブの最初にクリーンにするステップを配置するのが効果的です。

CAUTION: ホスト上に保持されるキャッシュをジョブ間で利用すると、ビルド時間の短縮を期待できますが、一方で、再現性は低下します。 また、長期的には、ディスク容量を使い果たす可能性もあります。 その結果、これにより課金対象の使用量が増える場合があります。

== 1 つのホスト上で複数のランナーを実行することはできますか。

はい、できます。 `launch-agent` の複数のレプリカを、それぞれに一意の名前を設定して実行すれば、1 つのホスト上で必要な数のランナー (言い換えると、必要な数のジョブ) を実行できます。 ただし、同時に実行したときに競合が発生しないように、ジョブが相互に十分に分離されるよう特に注意してください。

== セルフホストランナーのリソースクラスを削除することはできますか？

Yes, self-hosted runner resource classes can be deleted through the <<local-cli#, CLI>>. このアクションは取り消すことができないため、永遠に削除したいリソースクラスかどうかを確認してください。

リソースクラスを削除する前に、そのリソースクラスに関連付けられているトークンを削除する必要があります。

```bash
circleci runner token delete <token-id>

```

トークンを削除したら、リソースクラスを削除することができます。

```bash
circleci runner resource-class delete <resource-class>

```

== OSS プロジェクトのメンバーのジョブで、その人が組織のメンバーではない場合、組織のセルフホストランナーを使用できますか。

使用できません。ランナーのリソースクラスを所有する組織に関連付けられていないジョブでそのランナーのリソースクラスを使用することはできません。 組織の一部である OSS プロジェクトのメンバーのみがその組織のセルフホストランナーを使うことができます。
