---
version:
- Cloud
- Server v3.x
---
= Docker への CircleCI ランナーインストール
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このページでは、CircleCI ランナーを Docker にインストールする方法を説明します。 

NOTE: 必須要件や認証方法についてはxref:runner-installation.adoc[CircleCI ランナーのインストール] のページご確認ください。

toc::[]

== 追加の必須要件

ホストには、Docker をインストールしておく必要があります。 `runner` コンテナは、起動するとすぐにジョブの実行を試みます。 コンテナは停止されるまで、他のジョブの実行用に再利用され続けます。

ホスト上で並列実行できるコンテナの数は、ホストで利用可能なリソースおよびジョブのパフォーマンス要件によって異なります。

== CircleCI ランナーのイメージを拡張した Dockerfile を作成する

次の例では、ベース イメージ上に python3 をインストールします。

`Dockerfile.runner.extended`

```
FROM circleci/runner:launch-agent
RUN apt-get update; \
    apt-get install --no-install-recommends -y \
        python3
```

== Docker イメージをビルドする

```bash
docker build --file ./Dockerfile.runner.extended .
```

== Docker コンテナを起動する

NOTE: 環境変数の値は `docker` コマンドに紐付けられないので、`ps` 出力ではこれらの環境変数は表示されません。

```bash
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> docker run --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

コンテナは、起動するとすぐにジョブの実行を試みます。

=== サーバー上で Docker コンテナを起動する

サーバー上で Docker コンテナを起動する場合、  `--env` フラグを使って `agent_version` の環境変数を渡す必要があります。

``` bash
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> docker run --env agent_version --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>

```

== Docker コンテナを停止する

``` bash
docker stop <container-name>
```

== Docke コンテナを削除する

同じ名前のコンテナを再作成する場合など、停止したランナーコンテナをシステムから完全に削除する必要がある場合があります。


``` bash
docker stop <container-name>; docker rm <container-name>;
```
