---

description: CircleCI セルフホストランナーをスケールする方法
contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= セルフホストランナーのスケーリング
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

[#introduction]
== はじめに

CircleCI セルフホストランナーの固定のコンピューティングフリートを保持するには、ジョブがキューに入る率に応じてワークロードが変動するため、不要なコストが発生する可能性があります。 このコストを削減するために、必要に応じてコンピューティングフリートをスケーリングできます。

link:https://circleci.com/blog/autoscale-self-hosted-runners-aws/[CircleCI ブログ] より、AWS AutoScaling グループを使ってマシンランナーをスケーリングするためのサンプルを使ったチュートリアルをご覧いただけます。

[#container-runner]
== コンテナランナー

Kubernetes でコンテナランナーを使用している場合、キューに入る作業量が増えると、Pod が自動的にスピンアップします。  これらの Pod は一時的な Pod であり、ジョブの実行が完了すると破棄されます。  Pod は作業に合わせて自動的にスケーリングされますが、Kubernetes クラスタの基盤となるコンピューティングはスケーリングされません。

[#scaling-data]
== データのスケーリング

マシンランナーやコンテナランナー用の Kubernetes クラスタをスケールするためのソリューションをセットアップする際に役立つ API エンドポイントが複数あります。

* <<runner-api#get-apiv2runnertasks, 未処理のタスク>>
* <<runner-api#get-apiv2runnertasksrunning, 実行中のタスク>>
* <<runner-api#get-apiv2runner,リソースクラスのリスト>>

スケーリングソリューションにより、上記のエンドポイントを使って実行可能な待機タスクの合計数を計算することができます。 タスクデータエンドポイントのスコープは 1 つのリソースクラスにスコープされるため、使用可能なすべてのリソースクラスを照会し、実行中のタスクの合計数を取得することが重要です。

マシンランナーをご使用の場合は、スケーリングソリューションを使って、保留中の作業が多いリソースクラスにマシンランナーを追加できます。

NOTE: 同時実行数の制限を超えるコンピューティングを開始してしまわないよう、プランの同時実行制限にも注意する必要があります。 これは CircleCI の link:https://circleci.com/ja/pricing/[料金プランのページ] でご確認いただけます。

[#agent-configuration]
== マシンランナーのエージェントの設定

スケーリングソリューションで使用できるマシンランナーの設定がいくつかあります。特に、需要が減少した場合にリソースのクリーンアップをサポートできます。

* <<runner-config-reference#runner-mode,ランナーモード>>
** `single-task` モードを選択すると、マシンランナーは 1 つのタスクが終わるとシャットダウンします。 このモードは、マシンランナーの終了時にリソースが自動的にリサイクルされるので、完全に一時的なコンピューティングを使用する場合に便利です。
** `continuous` モードを選択すると、マシンランナーはタスクの終了後に新しいタスクをポーリングします。 スケーリングソリューションにより、タスクのワークロードを監視し、使用していない マシンランナーを積極的にシャットダウンする必要があります。
* <<runner-config-reference#runner-idle_timeout,ランナーのアイドル状態のタイムアウト>>
** 需要が低い期間のリソースの自動リサイクルに、妥当なタイムアウトを設定することができます。