---
version:
- Cloud
- Server v3.x
---
= CircleCI Self-hosted Runner Installation on Windows
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This page describes how to install CircleCI self-hosted runners on Windows. 以下のインストール方法は、Windows Server 2019 と Windows Server 2016 の両方について、Datacenter エディションでテスト済みです。 Other Server SKUs with Desktop Experience and Remote Desktop Services should also work.

{% include snippets/ja/runner-platform-prerequisites.adoc %}

toc::[]

With this procedure, you install CircleCI launch agent and its dependencies, for example, Chocolatey, Git and Gzip, on your Windows Server.

セットアップ中、CircleCI ジョブを実行する新しいローカル管理者ユーザーを作成します。 そのため、Windows Server で、ローカル ユーザーを作成して、そのユーザーのリモート ログオンを許可できる必要があります。

*また、このセットアップをドメイン環境で行う際には、Windows Server はドメイン メンバーである必要があります。 The self-hosted runner instance cannot run on a Windows Server operating as a domain controller.*

== インストール手順

. GitHub から https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Install-CircleCIRunner.ps1` スクリプト]をダウンロードし、アクセスしやすい場所に配置します。 

. PowerShell を管理者として開き、スクリプト ファイルを配置したディレクトリに移動します。

. 以下を PowerShell で実行します。
+
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
./Install-CircleCIRunner.ps1
```
+
PowerShell インターフェイスにインストール結果が出力されます。

. As part of the installation, the configuration file for the self-hosted runner (`launch-agent-config.yaml`) will open in Notepad. Please fill the file out with the requested information (see xref:runner-config-reference.adoc[Self-hosted Runner Configuration Reference]). The configuration file is located in the installation directory, `C:\Program Files\CircleCI`, by default.

After setup completes, the launch agent starts automatically and begins looking for jobs to process.

{% include snippets/ja/runner-config-reference.adoc %}

== Uninstall / Reinstall Steps

Uninstalling CircleCI self-hosted runners will prepare the system for installation again.

. Download the https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Uninstall-CircleCIRunner.ps1` script] from GitHub to an easily accessible location.
. PowerShell を管理者として開き、スクリプト ファイルを配置したディレクトリに移動します。

. 以下を PowerShell で実行します。
+
```
./Uninstall-CircleCIRunner.ps1
```