---
version:
- Cloud
- Server v3.x
---
= CircleCI Self-hosted Runner Installation on Linux
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

This page describes how to install CircleCI self-hosted runner on Linux.

{% include snippets/ja/runner-platform-prerequisites.adoc %}

== Create the CircleCI self-hosted runner configuration

Create a `launch-agent-config.yaml` file. 

```shell
sudo touch /opt/circleci/launch-agent-config.yaml
```

Copy and paste into the newly created file the recommended CircleCI self-hosted runner configuration for Linux:

```yaml
api:
  auth_token: AUTH_TOKEN
  # CircleCI Server の場合 url に CircleCI Server のホスト名を設定します。 For example,
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  command_prefix: ["sudo", "-niHu", "USERNAME", "--"]
  working_directory: /opt/circleci/workdir/%s
  cleanup_working_directory: true
```

Replace `AUTH_TOKEN` with the resource class token created in the xref:runner-installation.adoc#authentication[Authentication] step. Replace `RUNNER_NAME` with the name you would like for your self-hosted runner. `RUNNER_NAME` is unique to the the machine that is installing the runner. `RUNNER_NAME` can be any value you would like, and it does not need to include any part of your namespace or resource class name. `USERNAME` is the user on your machine that you want to run the runner launch agent. This is not your CircleCI account username, but the user on the machine that the agent will be installed on.

== Install the CircleCI self-hosted runner configuration

作成した設定ファイルを `/opt/circleci/launch-agent-config.yaml` として保存し、所有者を `root` に、パーミッションを `600` に設定します。

```shell
sudo chown root: /opt/circleci/launch-agent-config.yaml
```

```shell
sudo chmod 600 /opt/circleci/launch-agent-config.yaml
```

== Create the USERNAME user & working directory

これらはタスク エージェントの実行時に使用されます。 以下のコマンドは、他のユーザーを作成する権限を持ったユーザーとして実行する必要があります (例: `root`)。 GECOS については、https://en.wikipedia.org/wiki/Gecos_field[Wiki ページ]を参照してください。

=== Ubuntu/Debian

```shell
id -u USERNAME &>/dev/null || sudo adduser --disabled-password --gecos GECOS USERNAME

sudo mkdir -p /opt/circleci/workdir
sudo chown -R USERNAME /opt/circleci/workdir
```

Consider running the following additional command if you would like to use certified orbs that work on Cloud on your self-hosted runner, without errors. Note that this enables code to execute root commands on your machine, and changes to the system may persist after the job is run.

```shell
echo "USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
```

=== CentOS/RHEL

```shell
id -u USERNAME &>/dev/null || sudo adduser -c GECOS USERNAME

sudo mkdir -p /opt/circleci/workdir
sudo chown -R USERNAME /opt/circleci/workdir
```

Consider running the following additional command if you would like to use certified orbs that work on Cloud on your self-hosted runner, without errors. Note that this enables code to execute root commands on your machine, and changes to the system may persist after the job is run.

```shell
echo "circleci ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
```

== SELinux ポリシーを構成する (RHEL 8)

An SELinux policy is required for self-hosted runner to accept and launch jobs on RHEL 8 systems (earlier versions of RHEL are unsupported). Note that this policy does not add any permissions to the ones that may be required by individual jobs on this self-hosted runner install.

`/opt/circleci/policy` というディレクトリを作成し、最初のポリシー モジュールを生成します。

```shell
sudo mkdir -p /opt/circleci/policy

# まだインストールしていない場合 sepolicy と rpmbuild をインストールする
sudo yum install -y policycoreutils-devel
sudo yum install -y rpm-build

sudo sepolicy generate --path /opt/circleci/policy --init /opt/circleci/circleci-launch-agent
```

次の Type Enforcement ファイル https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/rhel8-install/circleci_launch_agent.te[`circleci_launch_agent.te`] をダウンロードして、ポリシーをインストールします。

```shell
sudo curl https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/rhel8-install/circleci_launch_agent.te --output /opt/circleci/policy/circleci_launch_agent.te

sudo /opt/circleci/policy/circleci_launch_agent.sh
```

{% include snippets/ja/runner-config-reference.adoc %}

=== サービスを起動する

When the CircleCI self-hosted runner service starts, it will immediately attempt to start running jobs, so it should be fully configured before the first start of the service.

```shell
systemctl start circleci.service
```

=== サービスの実行状態を確認する

`systemctl` コマンドで表示されるシステム レポートの `status` フィールドで、簡単な実行状態を確認できます。 このフィールドには、CircleCI API との接続状態に応じて、*Healthy (正常)* または *Unhealthy (異常)* と表示されます。

エージェントの状態は、次のコマンドを実行して確認できます。

```shell
systemctl status circleci.service --no-pager
```

このコマンドの出力は次のようになります。

```
circleci.service - CircleCI Runner
   Loaded: loaded (/opt/circleci/circleci.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-29 14:33:31 UTC; 18min ago
 Main PID: 5592 (circleci-launch)
   Status: "Healthy"
    Tasks: 8 (limit: 2287)
   CGroup: /system.slice/circleci.service
           └─5592 /opt/circleci/circleci-launch-agent --config /opt/circleci/launch-agent-config.yaml
```

また、次のコマンドを実行してシステムのログを確認することもできます。

```shell
journalctl -u circleci
```

== Optional Step

=== `systemd` ユニットを有効にする

You will need to have https://systemd.io/[systemd] version 235+ installed for this optional step.

 `/opt/circleci/circleci.service` を所有者を `root` にして作成し、アクセス許可を `755` に設定します。

```shell
sudo chown root: /opt/circleci/circleci.service
```

```shell
sudo chmod 755 /opt/circleci/circleci.service
```

`TimeoutStopSec` のデフォルト値は 5 時間ですが、タスクの総実行時間よりも大きい値を指定する必要があります。

If you want to configure the CircleCI self-hosted runner installation to start on boot, it is important to note that the launch agent will attempt to consume and start jobs as soon as it starts, so it should be configured appropriately before starting. ローンチ エージェントはサービスとして設定可能であり、次のスクリプトで `systemd` により管理できます。

```
[Unit]
Description=CircleCI Runner
After=network.target
[Service]
ExecStart=/opt/circleci/circleci-launch-agent --config /opt/circleci/launch-agent-config.yaml
Restart=always
User=root
NotifyAccess=exec
TimeoutStopSec=18300
[Install]
WantedBy = multi-user.target
```

NOTE: Unlike the task agent, which uses the environment of the `circleci` user, the launch agent will need to have any required environment variables (e.g., proxy settings) explicitly defined in the unit configuration file. These can be set by `Environment=` or `EnvironmentFile=`. https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment[Please visit the `systemd` documentation for more information].

次に、下記コマンドによりサービスを有効化します。

```shell
systemctl enable /opt/circleci/circleci.service
```
