---
contentTags:
  platform:
  - クラウド
  - Server v4.0 - v4.7
---
= マシンランナーの macOS へのインストール
:page-layout: classic-docs

:page-description: このドキュメントでは、CircleCI セルフホストランナーを macOS にインストールする方法を説明します。
:icons: font
:toc: macro
:toc-title:
:macos:

このページでは、macOS に CircleCI のマシンランナーをインストールする方法を説明します。

[#prerequisites]
== 前提条件

{% include snippets/runner/ja/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== セルフホストランナーの利用条件

include::../_includes/snippets/runner/ja/terms.adoc[]

[#create-namespace-and-resource-class]
== 1. ネームスペースとリソースクラスの作成

[.tab.machine-runner.Web_app_installation]
--
{% include snippets/runner/ja/install-with-web-app-steps.adoc %}
--
[.tab.machine-runner.CLI_installation]
--
{% include snippets/runner/ja/install-with-cli-steps.adoc %}

--


[#download-the-launch-agent-script]
== 2. launch-agent スクリプトをダウンロードし、バイナリをインストールする。

{% include snippets/runner/ja/launch-agent-download.adoc %}

[#create-a-circleci-self-hosted-runner-configuration]
== 3. CircleCI セルフホストランナー設定ファイルを作成する

CircleCI エージェントを実行するユーザーを選択します。 そのディレクトリの所有権を `USERNAME` に変更します。 `USERNAME` は、エージェントがインストールされるマシンのユーザーのことであり、CircleCI アカウントのユーザー名では_ありません_。

大文字で記載されたさまざまなパラメーターを適切な値に置き換えて、下記のテンプレートを完成させます。 完成したら、このテンプレートを `launch-agent-config.yaml` として保存します。

```yaml
api:
  auth_token: AUTH_TOKEN
  # On server, set url to the hostname of your server installation. For example,
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  command_prefix : ["sudo", "-niHu", "USERNAME", "--"]
  working_directory: /var/opt/circleci/workdir
  cleanup_working_directory: true

logging:
  file: /Library/Logs/com.circleci.runner.log
```

- Replace `AUTH_TOKEN` with the resource class token created in the xref:runner-installation#circleci-web-app-installation.adoc[set up process].
- `RUNNER_NAME` を任意のセルフホストランナー名に置き換えます。 `RUNNER_NAME` は、ランナーをインストールするマシン一意の名前です。 `RUNNER_NAME` には、任意の値を設定でき、名前空間やリソースクラス名を含む必要はありません。 CircleCI Web アプリでステータスやジョブ結果を確認する際にエージェントを特定できるよう、名前にはマシンのホスト名を使用することをお勧めします。 The only special characters accepted in RUNNER_NAME are `. () - _`.

[#update-workdir-ownership]
== 4. 作業ディレクトリのアクセス許可を更新する

CircleCI エージェントに、作業ディレクトリが格納されているディレクトリへの書き込みアクセス許可を付与する必要があります。 そのディレクトリの所有権を `USERNAME` に変更します。

```shell
sudo chown USERNAME /var/opt/circleci
```

[#install-the-circleci-self-hosted-runner-configuration]
== 5. セルフホストランナー設定ファイルをインストールする

CircleCI のセルフホストランナー設定ファイルの保存ディレクトリを `root` として作成します。

```shell
sudo mkdir -p '/Library/Preferences/com.circleci.runner'
```

先程作成した `launch-agent-config.yaml` をディレクトリにコピーし、権限を`600` に変更します。

```shell
sudo cp "launch-agent-config.yaml" "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

```shell
sudo chmod 600 "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

[#create-and-install-the-launchd-plist]
== 6. `launchd .plist` を作成しインストールする

`com.circleci.runner.plist` ファイルを、パス `/Library/LaunchDaemons/com.circleci.runner.plist`、所有者 `root`、アクセス許可 `644` で作成します。 次のコマンドを使用します。

```shell
sudo touch /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chown root: /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chmod 644 /Library/LaunchDaemons/com.circleci.runner.plist
```

下記を新しく作成した `/Library/LaunchDaemons/com.circleci.runner.plist` ファイルにコピーします。

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.circleci.runner</string>

        <key>Program</key>
        <string>/opt/circleci/circleci-launch-agent</string>

        <key>ProgramArguments</key>
        <array>
            <string>circleci-launch-agent</string>
            <string>--config</string>
            <string>/Library/Preferences/com.circleci.runner/launch-agent-config.yaml</string>
        </array>

        <key>RunAtLoad</key>
        <true/>

        <!-- The agent needs to run at all times -->
        <key>KeepAlive</key>
        <true/>

        <!-- This prevents macOS from limiting the resource usage of the agent -->
        <key>ProcessType</key>
        <string>Interactive</string>

        <!-- Increase the frequency of restarting the agent on failure, or post-update -->
        <key>ThrottleInterval</key>
        <integer>3</integer>

        <!-- Wait for 10 minutes for the agent to shut down (the agent itself waits for tasks to complete) -->
        <key>ExitTimeOut</key>
        <integer>600</integer>

        <!-- The agent uses its own logging and rotation to file -->
        <key>StandardOutPath</key>
        <string>/dev/null</string>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
    </dict>
</plist>
```

[#enable-the-launchd-service]
== 7. `launchd` サービスを有効にする

これで、サービスをロードできます。

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

NOTE: これまでに有効化手順を実行したことがある場合は、下記コマンドで既存サービスをアンロードしてください。 アンロード後、上記コマンドにより新しいサービスをロードできます。

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#verify-the-service-is-running]
== 8. サービスの実行状態を確認する

プリインストールされている macOS アプリケーション、 *コンソール* を開きます。 このアプリケーションでは、 *ログレポート* で CircleCI エージェントのログを閲覧することができます。 リストから `com.circleci.runner.log` というログを探します。 このファイルは、 *Library > Logs* に移動しても見つけられます。

{% include snippets/ja/machine-runner-example.adoc %}

[#troubleshooting]
== トラブルシューティング

Refer to the <<troubleshoot-self-hosted-runner#troubleshoot-machine-runner, Troubleshoot Machine Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running machine runner on macOS.
