---
version:
- Cloud
---
= CircleCI ランナー API
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

CircleCI ランナー API の外部向けエンドポイント一覧を紹介します。

toc::[]

== Authentication Methods

The CircleCI runner API contains different authentication methods. Each authentication method may be used in different endpoints for different purposes. Also one endpoint may accept multiple authentication methods.

=== Circle-Token (個人認証)

This authentication method is based on personal tokens and follows the same rules for CircleCI v2 API.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Name
| Description

| circle-token header
| Header that contains the `circle-token` used to authenticate the user.

| http basic auth username
| The token can be provided using the Basic scheme, where username should be set as the `circle-token` and the password should be left blank.
|===

=== Browser Session Authentication

Ring-session sent through a cookie on the request. This authentication allows users that are already logged into circleci.com to access certain endpoints seamlessly.

=== Launch Token

This token is the same one used in the launch-agent setup.

==== Supported methods

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Name
| Description

| http bearer auth
| The token that should be provided using the Bearer scheme.
|===

== Endpoints

=== GET /api/v2/runner

Lists the available runners based on the specified parameters. It is mandatory to use one parameter to filter results.

==== Authentication Methods

* Circle-Token (個人認証)
* ブラウザー セッション認証
+ この認証方法では、circleci.com に既にログインしているユーザーが circleci.com/api/v2/runner でエンドポイントにアクセスできます。
* ローンチ トークン

===== Request

[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
| 名前
| 型
| 入力
| 必須
| 説明

| resource-class
| string
| クエリ
| 省略可
| 指定したリソース クラスでランナーの一覧を絞り込みます。

| namespace
| string
| クエリ
| 省略可
| 指定した名前空間でランナーの一覧を絞り込みます。
|===

== Examples

```sh
curl -X GET https://runner.circleci.com/api/v2/runner?resource-class=test-namespace/test-resource \
    -H 'Circle-Token: secret-token'
```

```sh
curl -X GET https://runner.circleci.com/api/v2/runner?namespace=test-namespace \
    -H 'Circle-Token: secret-token'
```

=== Response

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| Status
| Description
| Format

|200
|エージェントの一覧
|JSON
|===

=== Response Schema

[.table.table-striped]
[cols=4*, options="header", stripes=even]
|===
| 名前
| 型
| 必須
| 説明

|items
|[object]
|true
|array containing the runners

|resource_class
|string
|必須
|ランナーのリソース クラス

|hostname
|string
|必須
|ランナーのホスト名

|name
|string
|必須
|ランナー名

|first_connected
|string (date-time)
|true
|first time the runner was connected

|last_connected
|string (date-time)
|true
|last time the runner was connected

|last_used
|string (date-time)
|true
|last time the runner was used to run a job

|version
|string
|必須
|実行中のローンチ エージェントのバージョン
|===

== Example

```sh
{
    "items": [
        {
            "resource_class": "test-namespace/test-resource",
            "hostname": "bobby",
            "name": "bobby-sue",
            "first_connected": "2020-05-15T00:00:00Z",
            "last_connected": "2020-05-16T00:00:00Z",
            "last_used": "2020-05-17T00:00:00Z",
            "version": "5.4.3.2.1"
        }
    ]
}
```


=== GET /api/v2/runner/tasks

Get the number of unclaimed tasks for a given resource class.

==== Authentication Methods

* Circle-Token (個人認証)
* ブラウザー セッション認証
+ この認証方法では、circleci.com に既にログインしているユーザーが circleci.com/api/v2/runner でエンドポイントにアクセスできます。
* ローンチ トークン

===== Request

[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
| 名前
| 型
| 入力
| 必須
| 説明

| resource-class
| string
| クエリ
| 必須
| 指定したリソース クラスでタスクを絞り込みます。
|===

== Examples

```sh
curl -X GET https://runner.circleci.com/api/v2/runner/tasks?resource-class=test-namespace/test-resource \
    -H 'Circle-Token: secret-token'
```

=== Response

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| Status
| Description
| Format

|200
|Number of unclaimed tasks
|JSON
|===

=== Response Schema

[.table.table-striped]
[cols=4*, options="header", stripes=even]
|===
| 名前
| 型
| 必須
| 説明

|unclaimed_task_count
|int
|true
|number of unclaimed tasks
|===

== Example

```json
{
    "unclaimed_task_count": 42
}
```

