---

version:
-クラウド
- Server v3.x
---
= CLI でのセルフホストランナーのインストール
:page-layout: classic-docs
:page-liquid:
:page-description: Linux、macOS、Docker、および Windows プラットフォームへの CircleCI セルフホストランナーのインストール方法について説明します。
:icons: font
:toc: macro

:toc-title:

ここでは、CLI でセルフホストランナーをインストールする方法を説明します。

++++
<section style="
    background-color: #d9edf7;
    border: 1px solid #bce8f1;
    border-radius: 4px;
    color: #31708f;
    padding: 15px;
    margin: 20px 0;
">
   セルフホストランナーは、<a href="https://app.circleci.com/" target="_blank">CircleCI Web アプリ</a>で直接インストールできるようになりました！
 このオプションを UI で使用できるようにするには、 <a href="#self-hosted-runer-terms -agreement">ランナーの条件</a> に同意する必要があります。
</section>
++++

toc::[]

== 前提条件

ジョブのインストールや実行には、ルートアクセスが必要です。また、システムに以下のユーティリティとツールをインストールする必要があります。

* <<local-cli#,CircleCI CLI>>:   **サーバー用のランナー** をインストールする場合は、サーバー API キーを使って CircleCI CLI を設定する必要があります。 `circleci setup` を実行してCLI を設定し、必要に応じて新しい API トークンを提供するオプションにアクセスします。
* https://www.gnu.org/software/coreutils/[coreutils] (Linux のみ)
* https://curl.se/[curl] (macOS はデフォルトでインストール済み)
* sha256sum (プリインストールされていない場合):
- macOS の場合は、 `brew install coreutils` (https://brew.sh/[Homebrew] が必要)
- `Ubuntu/Debain の場合は、`sudo apt install coreutils`
- Red Hat の場合は、`sudo yum install coreutils` 
* https://www.gnu.org/software/tar/[tar]

* https://www.gnu.org/software/gzip/[gzip]
* sepolicy (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] のみ)
* rpmbuild (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] のみ)


== セルフホストランナーの利用条件

CLI でセルフホストランナーをインストールし、使用する場合は、https://circleci.com/legal/ja/runner-terms/[CircleCI ランナーの条件] に同意したものとみなされます。

== コマンドラインのインストール

NOTE:  **サーバー用のセルフホストランナー** をインストールする場合は、サーバー API キーを使って CircleCI CLI を設定する必要があります。 `circleci setup` を実行して CLI を設定し、必要に応じて新しい API トークンを提供するオプションにアクセスします。

セルフホストランナーをインストールのためには、下記手順を実行して名前空間と認証トークンを作成する必要があります。 リソースクラスとトークンを作成するには、VCS プロバイダーの組織管理者である必要があります。

お客様のランナーは、インベントリのページの左のナビゲーションバーで *Self-Hosted Runners* をクリックするとご覧いただけます。

. 組織のセルフホストランナーの名前空間を作成します。 CircleCI は組織名に基づき名前空間を自動作成するのでご注意ください。 使用する名前空間であることを確認してください。  *作成できる名前空間は、各組織 1 つのみです。*  CircleCI の組織のアカウント名を小文字で使用することを推奨します。 Orb を既に使用中の場合は、Orb で使用しているのと同じ名前空間にします。
+
名前空間の作成がエラーになる場合は、既存の名前空間があるか確認し、既存の名前空間を使用して下記の手順 2 から実行します。
+
下記のコマンドを使って名前空間を作成します。
+
circleci namespace create <namespace> <vcs-type> <org-name>
+
例えば、組織の GitHub URL が `\https://github.com/circleci-org` の場合、`circleci namespace create my-namespace github circleci-org` を使います。
. 次のコマンドを実行して、セルフホストランナーの名前空間用のリソースクラスを作成します。
+
circleci runner resource-class create <namespace>/<resource-class> <description> --generate-token
+
*リソースクラスを作成するコマンドには名前空間が必要です。*
+
CAUTION: トークンを再取得することはできませんので、必ず安全な場所に保管してください。

*Linux、macOS、サーバーをご使用のお客様は、下記の指示に従ってください。* それ以外のお客様は、 <<#platform-specific-instructions,プラットフォーム別のインストール>> までスキップします。 

=== Linux、macOS、サーバーの続き

下記の手順に移る前に、 必ず <<#command-line-installation, コマンドラインのインストール>> を完了してください。

. 下記のスクリプトをプロジェクトのルートに `download-launch-agent.sh` として保存します。　 このスクリプトの実行 (次の手順を参照) によりローンチ エージェントバイナリがダウンロードされる場合は、チェックサムを確認し、 `circleci-launch-agent` バージョンを設定してください。
+
クラウド版 CircleCI のセルフホストランナーは、サポートされている最新バージョンに自動的に更新されます。 サーバーの場合、特定のセルフホストランナーバージョンの相互運用性は検証されていますが、セルフホストランナーは自動更新されません。
+
#!/usr/bin/env sh

set -eu pipefail

echo "Installing CircleCI Runner for ${platform}"

base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
if [ -z ${agent_version+x} ]; then
  agent_version=$(curl "${base_url}/release.txt")
fi

# Set up runner directory
echo "Setting up CircleCI Runner directory"
prefix=/opt/circleci
sudo mkdir -p "${prefix}/workdir"

# Downloading launch agent
echo "Using CircleCI Launch Agent version ${agent_version}"
echo "Downloading and verifying CircleCI Launch Agent Binary"
curl -sSL "${base_url}/${agent_version}/checksums.txt" -o checksums.txt
file="$(grep -F "${platform}" checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')"
mkdir -p "${platform}"
echo "Downloading CircleCI Launch Agent: ${file}"
curl --compressed -L "${base_url}/${agent_version}/${file}" -o "${file}"

# Verifying download
echo "Verifying CircleCI Launch Agent download"
grep "${file}" checksums.txt | sha256sum --check && chmod +x "${file}"
sudo cp "${file}" "${prefix}/circleci-launch-agent" || echo "Invalid checksum for CircleCI Launch Agent, please try download again"
. プラットフォームを設定して、 `download-launch-agent.sh` スクリプトを実行し、バイナリをダウンロード、確認、インストールしてください。 **cloud** を使用している場合は、下記の表でプラットフォームの変数を見つけます。
+
[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|インストール対象
|変数

|Linux x86_64
|`platform=linux/amd64`

|Linux ARM64
|`platform=linux/arm64`

|macOS x86_64
|`platform=darwin/amd64`

|macOS M1
|`platform=darwin/arm64`
|===
+
例えば **クラウド** の場合、macOS M1のプラットフォームを設定し、 `download-launch-agent.sh` スクリプトを実行するには、下記を実行します。
+
export platform=darwin/arm64 && sh ./download-launch-agent.sh

+
 *Server v3.1.0 以降* の場合は、下記の表で実行しているサーバーのバージョンに互換性のあるローンチエージェントのバージョンを見つけます。
+
[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|CircleCI Server のバージョン
|ローンチエージェントのバージョン

|3.0
|ランナーはサポートされていません

|3.1
|1.0.11147-881b608

|3.2
|1.0.19813-e9e1cd9

|3.3
|1.0.29477-605777e

|3.4
|1.0.33818-051c2fc
|===
+
`<launch-agent-version>` をサーバー用のローンチエージェントバージョンに置き換え、下記を実行します。
+
export agent_version="<launch-agent-version>" && sh ./download-launch-agent.sh
+
**Note:** Once your runner is successfully set up, you can delete the `download-launch-agent.sh` file.
. Continue with the platform-specific instructions in the next section.

=== プラットフォームごとのインストール方法

Please continue with the platform-specific installation instructions below. This should be done only after you have created your namespace and resource class, and run the `download-launch-agent.sh` script from the previous section.

* xref:runner-installation-linux.adoc[Linux]
* xref:runner-installation-mac.adoc[macOS]
* xref:runner-installation-windows.adoc[Windows]
* xref:runner-installation-docker.adoc[Docker]
* xref:runner-on-kubernetes.adoc[Kubernetes]

For other platforms, see the <<runner-supported-platforms#,Available CircleCI self-hosted runner platforms>> page for more information.

{% include snippets/runner-config-reference.adoc %}

== Self-hosted runners for server compatibility

_CircleCI runner is available from server v3.1.0_

Each minor version of server is compatible with a specific version of `circleci-launch-agent`. The table below lists which version of `circleci-launch-agent` to use when installing self-hosted runners, depending on your version of server.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|CircleCI Server のバージョン
|ローンチ エージェントのバージョン

|3.0
|ランナーはサポートされていません

|3.1
|1.0.11147-881b608

|3.2
|1.0.19813-e9e1cd9

|3.3
|1.0.29477-605777e

|3.4
|1.0.33818-051c2fc
|===

== 関連リソース

- https://hub.docker.com/r/circleci/runner[CircleCI Runner Image on Docker Hub]
- https://github.com/CircleCI-Public/circleci-runner-docker[CircleCI Runner Image on Github]
- https://circleci.com/docs/[CircleCI Docs - The official CircleCI Documentation website]
- https://docs.docker.com/[Docker Docs]