---
version:
- Server v3.x
---
= サーバー上での CircleCI ランナーのアップグレード
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:


ここでは、CircleCI Server 上で CircleCI ランナーを更新する方法を説明します。

toc::[]

== CircleCI Server とランナーの互換性

xref:runner-installation.adoc#runner-for-server-compatibility[サーバーとの互換性リスト]を参照して、インストールに必要なランナーのバージョンを確認してください。

== サーバー上のランナーのアップグレード

クラウド版の CircleCI とは異なり、CircleCI Server は`circleci-launch-agent`を自動的に更新しないため、手動による操作が必要です。 以下では、さまざまな環境で CircleCI Server のランナーをアップグレードする方法を詳しく説明します。

=== コンテナ化された環境におけるランナーのアップグレード

ここでは、Kurbernetes や Docker のコンテナ化された環境でランナーをアップグレードする方法について詳しく説明します。

==== Kubernetes ランナーのアップグレード

xref:runner-on-kubernetes.adoc[Kubernetes のインストールガイド]を参照してください。

==== Docker ランナーのアップグレード

. 現在実行中のすべてのランナーコンテナを停止します。
+
```shell
docker stop <container-name>
```
. ランナーのコンテナを削除します。
+
```shell
docker stop <container-name>; docker rm <container-name>;
```
. 新しいランナーの Docker コンテナを起動します。
+
```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> docker run --env agent_version --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```
+
NOTE: サーバー上で Docker コンテナを起動する場合、 `--env`  フラグを使って `agent_version` の環境変数を渡す必要があります。

=== コンテナ化されていない環境におけるランナーのアップグレード

コンテナ化されていない環境では、`circleci-launch-agent`バイナリを手動で更新するプロセスは 3 つのステップに分けられます。 各ステップの詳細を以下で説明します。

. 既存の `circleci-launch-agent` バイナリを新しいバージョンに置き換える
. 現在実行中の `circleci-launch-agent` プロセスを停止する
. 新バージョンの `circleci-launch-agent` バイナリを起動する

==== 1. 既存の `circleci-launch-agent` バイナリを新しいバージョンに置き換える

xref:runner-installation.adoc#download-the-launch-agent-binary-and-verify-the-checksum[ローンチエージェント バイナリのダウンロード]と同じ手順で、 `agent_version` の環境変数をxref:runner-installation.adoc#runner-for-server-compatibility[サーバーとランナーの互換性リスト]に記載されている正しいバージョンに更新します。

```shell
export agent_version="<launch-agent-version>"
```

Then, following the xref:runner-installation.adoc#platform-specific-instructions[platform specific installation instructions], replace the old binary with the newly updated version that was just downloaded.

==== 2. 現在実行中のローンチエージェントを停止する

新しく更新されたバイナリを開始する前に現在実行中の `circleci-launch-agent` プロセスを停止する必要があります。 以下にプラットフォーム別の停止方法を説明します。

===== Linux のローンチエージェントの停止

次のコマンドを実行します。

```shell
sudo systemctl stop circleci.service
sudo systemctl disable circleci.service
```

=====  Mac のローンチエージェントの停止

次のコマンドを実行します。

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

===== Windows のローンチエージェントの停止

次のコマンドを実行します。

``` powershell
Stop-ScheduledTask -TaskName "CircleCI Launch Agent"

```

==== 3. 新しいランナー ローンチエージェントを起動する

以下にプラットフォーム別の起動方法を説明します。

===== Linux での起動

次のコマンドを実行します。

```shell
sudo systemctl reload circleci.service
sudo systemctl enable circleci.service
sudo systemctl start circleci.service
```

===== Macでの起動

次のコマンドを実行します。

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

===== Windows での起動

次のコマンドを実行します。

``` powershell
Start-ScheduledTask -TaskName "CircleCI Launch Agent"
```

=== 関連リソース
- xref:runner-installation.adoc[CircleCI ランナーのインストール]
- xref:runner-on-kubernetes.adoc[Kubernetes のインストール手順]


