---

version:
- Cloud
- Server v4.x
- Server v3.x
---
= CircleCI's machine runner installation with Docker
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

This page describes how to install CircleCI's machine runner with the Docker executor. If you are looking to set up self-hosted runners in a private Kubernetes cluster, please visit the <<container-runner#,Container runner>> page.

[#new-recommended-method-container-runner]
== New recommended method (container runner)

CircleCI has a new <<container-runner#,container runner>> in open preview which is the recommended approach for running containerized jobs on self-hosted runners. Container runner offers the ability to seamlessly define, publish, and use custom Docker images during job execution, as well as the ability to easily manage dependencies or libraries through custom Docker images instead of enumerating dependencies as part of `steps` in the `.circleci/config.yml` file.

[#machine-approach-with-docker]
== Machine-based approach with Docker

If you cannot use the container runner linked above, you can use a machine runner and install Docker with the instructions below.

{% include snippets/ja/runner-platform-prerequisites.adoc %}

[#additional-prerequisites]
=== 追加の必須要件

Docker をホストにインストールしておく必要があります。 `runner` コンテナは、起動するとすぐにジョブの実行を試みます。 コンテナは、停止されるまで他のジョブの実行用に再利用され続けます。

ホスト上で並列実行できるコンテナの数は、ホストで利用可能なリソースおよびジョブのパフォーマンス要件によって異なります。

[#create-a-dockerfile-that-extends-the-machine-runner-image]
=== Create a Dockerfile that extends the machine runner image

`Dockerfile.runner.extended` ファイルを作成します。 次の例では、ベースイメージ上に python3 をインストールします。

```dockerfile
FROM circleci/runner:launch-agent
RUN sudo apt-get update; \
    sudo apt-get install --no-install-recommends -y \
        python3
```

[#build-the-docker-image]
=== Docker イメージをビルドする

```shell
docker build --file ./Dockerfile.runner.extended .
```

[#start-the-docker-container]
=== Docker コンテナを起動する

NOTE: 環境変数の値は  `docker` コマンドに紐付けられないので、`ps` 出力ではこれらの環境変数は表示されません。

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> docker run --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

コンテナは、起動するとすぐにジョブの実行を試みます。

[#start-the-docker-container-on-server]
==== サーバー上で Docker コンテナを起動する

サーバー上で Docker コンテナを起動する場合、`--env` フラグを使って `agent_version`と `LAUNCH_AGENT_API_URL` の環境変数を渡す必要があります。

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> LAUNCH_AGENT_API_URL=<server_host_name> docker run --env agent_version --env LAUNCH_AGENT_API_URL --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

[#stopping-the-docker-container]
=== Docker コンテナを停止する

```shell
docker stop <container-name>
```

[#remove-the-docker-container]
=== Docker コンテナを削除する

In some cases you might need to fully remove a stopped machine runner container from the system, such as when recreating a container using the same name.

```shell
docker stop <container-name>; docker rm <container-name>;
```