---

version:
- Cloud
- Server v4.x
- Server v3.x
---
= CircleCI Self-hosted Runner Installation with Docker
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

このページでは マシン実行環境で CircleCI セルフホストランナーと Docker でインストールする方法を紹介します。

NOTE: CircleCI has a more scalable, container-friendly <<container-runner#,container runner>> in open preview.  これは、セルフホストの CI ジョブに対して任意のコンテナを実行するためのより直感的な方法です。

{% include snippets/ja/runner-platform-prerequisites.adoc %}

toc::[]

[#additional-prerequisites]
== 追加の必須要件

Docker をホストにインストールしておく必要があります。 Once the `runner` container is started, the container will immediately attempt to start running jobs. コンテナは、停止されるまで他のジョブの実行用に再利用され続けます。

The number of containers running in parallel on the host is constrained by the host's available resources and your jobs' performance requirements.

[#create-a-dockerfile-that-extends-the-circleci-self-hosted-runner-image]
== CircleCI セルフホストランナーのイメージを拡張した Dockerfile を作成する

Create a `Dockerfile.runner.extended` file. 次の例では、ベースイメージ上に python3 をインストールします。

```dockerfile
FROM circleci/runner:launch-agent
RUN sudo apt-get update; \
    sudo apt-get install --no-install-recommends -y \
        python3
```

[#build-the-docker-image]
== Docker イメージをビルドする

```shell
docker build --file ./Dockerfile.runner.extended .
```

[#start-the-docker-container]
== Docker コンテナを起動する

NOTE: The environment variable values are not available to the `docker` command, so these environment variables are not visible in `ps` output.

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> docker run --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

コンテナは、起動するとすぐにジョブの実行を試みます。

[#start-the-docker-container-on-server]
=== サーバー上で Docker コンテナを起動する

When starting the docker container on server, the `agent_version` and `LAUNCH_AGENT_API_URL` environment variables will need to be passed in using the `--env` flag.

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> LAUNCH_AGENT_API_URL=<server_host_name> docker run --env agent_version --env LAUNCH_AGENT_API_URL --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

[#stopping-the-docker-container]
== Docker コンテナを停止する

```shell
docker stop <container-name>
```

[#remove-the-docker-container]
== Docker コンテナを削除する

同じ名前のコンテナを再作成する場合など、停止したセルフホストランナーコンテナをシステムから完全に削除する必要がある場合があります。

```shell
docker stop <container-name>; docker rm <container-name>;
```