---
contentTags:
  platform:
  - Server v4.x
  - Server v3.x
---
= CircleCI Server 上での CircleCI セルフホストランナーのアップグレード
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:


ここでは、CircleCI Server 上で CircleCI *マシンランナー*を更新する方法を説明します。

toc::[]

[#self-hosted-runner-for-server-compatibility]
== マシンランナーのサーバーとの互換性

ご使用のプラットフォームに必要なランナーのバージョンは、マシンランナーの各インストールページを参照してください：

- xref:runner-installation-linux#download-the-launch-agent-script[Linux]
- xref:runner-installation-mac#download-the-launch-agent-script[macOS]
- xref:runner-installation-windows##set-launch-agent-version[Windows]

[#upgrading-self-hosted-runner-on-server]
== サーバー上のマシンランナーのアップグレード

クラウド版 CircleCI とは異なり、CircleCI Server は `circleci-launch-agent` を自動的に更新しないため、手動による操作が必要です。 以下では、さまざまな環境で CircleCI Server のマシンランナーをアップグレードする方法を詳しく説明します。

[#upgrading-self-hosted-runner-in-a-containerized-environment]
=== コンテナ化された環境におけるマシンランナーのアップグレード

ここでは、Kurbernetes や Docker のコンテナ化された環境でセルフホストランナーをアップグレードする方法について詳しく説明します。

[#upgrading-self-hosted-runner-for-kubernetes]
==== Kubernetes のマシンランナーのアップグレード

xref:runner-on-kubernetes.adoc[Kubernetes のインストールガイド]を参照してください。

[#upgrading-self-hosted-runner-for-docker]
==== Docker のマシンランナーのアップグレード

. 現在実行中のすべてのセルフホストランナーコンテナを停止する
+
```shell
docker stop <container-name>
```
. セルフホストランナーのコンテナを削除する
+
```shell
docker stop <container-name>; docker rm <container-name>;
```
. 新しいマシンランナーの Docker コンテナを起動する
+
```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> docker run --env agent_version --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```
+
NOTE: サーバー上で Docker コンテナを起動する場合、 `--env` フラグを使って `agent_version` の環境変数を渡す必要があります。

[#upgrading-self-hosted-runner-in-a-non-containerized-environment]
=== コンテナ化されていない環境におけるマシンランナーのアップグレード

コンテナ化されていない環境では、`circleci-launch-agent`バイナリを手動で更新するプロセスは 3 つのステップに分けられます。 各ステップの詳細は次のセクションで説明します。

. 既存の `circleci-launch-agent` バイナリを新しいバージョンに置き換える
. 現在実行中の `circleci-launch-agent` プロセスを停止する
. 新しいバージョンの `circleci-launch-agent` バイナリを起動する

[#replace-the-circleci-launch-agent-binary-with-the-new-version]
==== 1. 既存の `circleci-launch-agent` バイナリを新しいバージョンに置き換える

xref:runner-installation-cli.adoc#continued-for-linux-macos-and-server[ローンチエージェントバイナリのダウンロード] と同じ手順で、`agent_version` の環境変数を xref:runner-installation-cli.adoc#self-hosted-runners-for-server-compatibility[CircleCI Server 用のセルフホストランナーの互換性リスト] に記載されている正しいバージョンに更新します。

- xref:runner-installation-linux#download-the-launch-agent-script[Linux]
- xref:runner-installation-mac#download-the-launch-agent-script[macOS]

```shell
export agent_version="<launch-agent-version>" && sh ./download-launch-agent.sh
```

- xref:runner-installation-windows#installation-steps[Windows]
```powershell
$Env:agentVer = "<launch-agent-version>"
```
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
./Install-CircleCIRunner.ps1
```

[#stop-the-currently-running-machine-runner]
==== 2. 現在実行中のマシンランナーを停止する

新しく更新されたバイナリを開始する前に現在実行中の `circleci-launch-agent` プロセスを停止する必要があります。 各プラットフォームの停止方法は以下のとおりです。

[#stopping-the-machine-runner-on-linux]
===== Linux でのマシンランナーの停止

次のコマンドを実行します。

```shell
sudo systemctl stop circleci.service
sudo systemctl disable circleci.service
```

[#stopping-the-machine-runner-on-mac]
===== Mac でのマシンランナーの停止

次のコマンドを実行します。

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#stopping-the-machine-runner-on-windows]
===== Windows でのマシンランナーの停止

次のコマンドを実行します。

``` powershell
Stop-ScheduledTask -TaskName "CircleCI Launch Agent"

```

[#start-the-new-machine-runner]
==== 3. 新しいマシンランナーを起動する

各プラットフォームの起動方法は以下のとおりです。

[#starting-on-linux]
===== Linux での起動

次のコマンドを実行します。

```shell
sudo systemctl reload circleci.service
sudo systemctl enable circleci.service
sudo systemctl start circleci.service
```

[#starting-on-mac]
===== Mac での起動

次のコマンドを実行します。

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#starting-on-windows]
===== Windows での起動

次のコマンドを実行します。

``` powershell
Start-ScheduledTask -TaskName "CircleCI Launch Agent"
```

[#additional-resources]
=== 関連リソース

- xref:runner-installation-linux#[CircleCI ランナーのインストール]
- xref:runner-installation-mac#[Kubernetes のインストール手順]
- xref:runner-installation-windows#[Windows マシンランナーのインストール手順]
- xref:runner-on-kubernetes#[Kubernetes上のランナーのインストール手順]
- xref:runner-installation-docker#[Docker Executor によるマシンランナーのインストール手順]


