---
version:
- クラウド
- Server v3.x
---
= macOS への CircleCI セルフホストランナーのインストール
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このページでは、CircleCI セルフホストランナーを macOS にインストールする方法を説明します。

{% include snippets/ja/runner-platform-prerequisites.adoc %}

toc::[]

[#download-the-launch-agent-script]
== Download the launch agent script

Save the link:https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/download-launch-agent.sh[launch-agent.sh] script file to an easily accessible location. From that location, install the launch agent binary for your target platform, either x86_64, or M1 (Apple silicon):

```shell
# For macOS x86_64:
export platform=darwin/amd64 && sh ./download-launch-agent.sh

# For macOS M1:
export platform=darwin/arm64 && sh ./download-launch-agent.sh
```

After successful installation, the launch-agent.sh file can be deleted.

[#create-a-circleci-self-hosted-runner-configuration]
== CircleCI セルフホストランナー設定ファイルを作成する

You will need to choose a user to run the CircleCI agent. 以下の手順では、選択するユーザーを `USERNAME` としています。 `USERNAME` は、エージェントがインストールされるマシンのユーザーのことであり、CircleCI アカウントのユーザー名では_ありません_。

大文字で記載されたパラメーターを適切な値に置き換えて、下記のテンプレートを完成させます。 完成したら、`launch-agent-config.yaml` として保存します。

```yaml
api:
  auth_token: AUTH_TOKEN
  # CircleCI Server の場合 url に CircleCI Server のホスト名を設定します。 例:
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  command_prefix : ["sudo", "-niHu", "USERNAME", "--"]
  working_directory: /var/opt/circleci/workdir
  cleanup_working_directory: true

logging:
  file: /Library/Logs/com.circleci.runner.log
```

[#update-workdir-ownership]
== Update the Working Directory Permission

The CircleCI agent requires write permission to the directory containing the working directory. Change the ownership of that directory to `USERNAME`:

```shell
sudo chown USERNAME /var/opt/circleci
```

[#install-the-circleci-self-hosted-runner-configuration]
== CircleCI セルフホストランナー設定ファイルをインストールする

CircleCI セルフホストランナー設定ファイルの保存ディレクトリを `root` として作成します。

```shell
sudo mkdir -p '/Library/Preferences/com.circleci.runner'
```

先程作成した `launch-agent-config.yaml` をディレクトリにコピーし、権限を`600` に変更します。

```shell
sudo cp "launch-agent-config.yaml" "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

```shell
sudo chmod 600 "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"

```

[#create-and-install-the-launchd-plist]
== `launchd .plist` を作成しインストールする

Create a `com.circleci.runner.plist` file with a path of `/Library/LaunchDaemons/com.circleci.runner.plist`, owned by `root`, with permissions `644`. Use the following commands:

```shell
sudo touch /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chown root: /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chmod 644 /Library/LaunchDaemons/com.circleci.runner.plist
```

下記を新しく作成した `/Library/LaunchDaemons/com.circleci.runner.plist` ファイルにコピーします。

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.circleci.runner</string>

        <key>Program</key>
        <string>/var/opt/circleci/circleci-launch-agent</string>

        <key>ProgramArguments</key>
        <array>
            <string>circleci-launch-agent</string>
            <string>--config</string>
            <string>/Library/Preferences/com.circleci.runner/launch-agent-config.yaml</string>
        </array>

        <key>RunAtLoad</key>
        <true/>

        <!-- The agent needs to run at all times -->
        <key>KeepAlive</key>
        <true/>

        <!-- This prevents macOS from limiting the resource usage of the agent -->
        <key>ProcessType</key>
        <string>Interactive</string>

        <!-- Increase the frequency of restarting the agent on failure, or post-update -->
        <key>ThrottleInterval</key>
        <integer>3</integer>

        <!-- Wait for 10 minutes for the agent to shut down (the agent itself waits for tasks to complete) -->
        <key>ExitTimeOut</key>
        <integer>600</integer>

        <!-- The agent uses its own logging and rotation to file -->
        <key>StandardOutPath</key>
        <string>/dev/null</string>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
    </dict>
</plist>
```

[#enable-the-launchd-service]
== `launchd` サービスを有効にする

これで、サービスをロードできます。

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

NOTE: これまでに有効化手順を実行したことがある場合は、下記コマンドで既存サービスをアンロードしてください。 アンロード後、上記コマンドにより新しいサービスをロードできます。

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

{% include snippets/ja/runner-config-reference.adoc %}

[#verify-the-service-is-running]
== サービスの実行状態を確認する

プリインストールされている macOS アプリケーション、 *コンソール* を開きます。 このアプリケーションでは、 *ログレポート* で CircleCI エージェントのログを閲覧することができます。 リストから `com.circleci.runner.log` というログを探します。 このファイルは、 *ライブラリ > ログ* に移動しても見つけられます。
