---

version:
- Cloud
- Server v3.x
---
= Runner のコンセプト
 
No context
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI セルフホストランナーのコンセプトの概要
:icons: font
:toc: macro
:toc-title:

toc::[]

== 名前空間とリソースクラス

セルフホストランナーには名前空間とリソースクラスが必要です。

 **名前空間** は、CircleCI 組織が要求する一意の識別子です。 各組織が要求できる一意の名前空間は 1 つのみで、後から変更することはできません。 通常、選択される名前空間は VCS の組織名を小文字で表したものです (推奨)。

**リソースクラス** は、CircleCI ジョブとそのジョブを処理するために識別されたランナーのタイプを一致させるためのラベルです。 リソースクラスの最初の部分は組織の名前空間です。 たとえば、 `circleci/documentation`  などです。 リソースクラスは、セルフホストランナーのインストールプロセスを実行する際に作成されます。

リソースクラスを使用すると、セルフホストランナーのプールを特定して、特定の場所にジョブを送信するように設定できます。 たとえば、macOS を実行する複数のマシンと Linux を実行する複数のマシンがある場合、ぞれぞれに対して、　`orgname/macOS` と `orgname/linux` のリソースクラスを作成することができます。 `.circleci/config.yml` のジョブレベルでは、リソースクラスに基づいて、ジョブの送信先となるセルフホストランナーのリソースを関連付けることができます。

オプションで、リソースクラスに説明をつけることもできます。

すでに <<orb-intro#,orbs>> を使用されているお客様は、既存の名前空間があるのでこ注意ください。 セルフホストランナーの名前空間は、Orb で使用しているのと同じ名前空間です。 名前空間を変更する必要がある場合は、<a data-type="default" href="https://support.circleci.com/hc/ja-jp">サポートにお問い合わせください。

== ローンチ エージェントとタスクエージェント

セルフホストランナーは、ローンチエージェントとタスクエージェントという 2 つの要素で構成されます。

* ローンチエージェント (launch-agent) - タスクの実行 (1 つのジョブの並列実行) に必要な情報の収集と、タスクエージェントプロセスのダウンロードおよび起動を行います。
* タスクエージェント (task-agent) - ローンチエージェントによって取得、設定されたタスクの実行を行います。

この仕組みにより、管理者は、task-agent が launch-agent よりも低い権限レベルで実行されるように設定することができます。 ジョブの実行を許可したすべてのユーザーには、task agent と同じ権限が付与されます。 下記はこのアプローチに基づいた推奨されるデプロイです (ローンチエージェントは `root` として、タスクエージェントは `circleci` として実行されます)。

== セルフホストランナーの同時実行

スループットを向上させるために、一つのビルドプロセスを複数のステップに分割し、同時に（一度に）実行することができます。
 CircleCI では、すべてのリソースクラスのセルフホストランナーに柔軟に作業をデプロイすることができます。

CircleCI セルフホストランナーは、登録済みセルフホストランナーの総数を制限するのではなく、リソースクラス全体のセルフホストランナージョブ (タスク) の総数を制限しています。


== SSH を使用したデバッグ

CircleCI セルフホストランナーでは、デバッグのために SSHでジョブを再実行することが可能です。 Instructions on using this feature can be found at <<ssh-access-jobs#,Debugging with SSH>>.

NOTE: 「SSH でジョブを再実行する」機能は、デフォルトでは無効になっています。 To enable this feature, see xref:runner-config-reference.adoc#runner-ssh-advertise_addr[Installing the CircleCI Self-hosted Runner].

== パブリック リポジトリ

CircleCI self-hosted runners are not recommended for use with public projects that have the "Build forked pull requests" setting enabled. このようなパブリック プロジェクトでは、他のユーザーがリポジトリをフォークし、コードをコミットしてプル リクエストを作成できるため、悪意のあるアクターによってマシンに変更が加えられたり、マシンでコードが実行されたりする可能性があります。 Untrusted jobs running on your CircleCI self-hosted runner pose significant security risks for your machine and network environment, especially if your machine persists its environment between jobs. このようなリスクには、次のものがあります。

* 悪意のあるプログラムがマシンで実行される。
* Escaping the machine's self-hosted runner sandbox
* Exposing access to the machine's network environment
* 不要なデータや危険なデータがマシンに保持される。

NOTE: デフォルトでは、組織は名前空間を 1つだけ要求できるように制限されています。 これは、名前空間の占拠や紛らわしさを制限するためのポリシーです。 If you need to change your namespace, please https://support.circleci.com/hc/en-us[contact support].