---
version:
- Cloud
- Server v3.x
---
= CircleCI Self-hosted Runner FAQs
:page-layout: classic-docs
:page-liquid:
:page-description: This page answers the most frequently asked questions for the CircleCI self-hosted runner product. 
:icons: font
:toc: macro
:toc-title:

This page answers frequently asked questions for the CircleCI self-hosted runner product.

toc::[]

== What is the security model for the CircleCI self-hosted runner?

When installing CircleCI self-hosted runner, you will be able to choose the user that executes jobs. このユーザーにはジョブの実行に必要な権限だけを付与するようにご注意ください。

CAUTION: ジョブに Docker デーモンへのアクセスを許可することは、ユーザーにマシンへの root アクセスを許可することと同等です。

== ジョブに必要な依存関係をインストールする方法を教えてください。

依存関係をインストールする方法は、主に 2 つあります。

* 必要な依存関係をインストールすることをジョブに許可する

柔軟性は高くなりますが、ツールを全体にインストール、または重複しない方法で (作業ディレクトリなどに) ツールをインストールできる権限をジョブに付与する必要があります。

* Pre-install dependencies on the self-hosted runner machine

This approach is the most secure; however, this means that if the job’s dependencies change, the self-hosted runner machine must be reconfigured.

== どのような接続が必要ですか。

ジョブの取得と実行の際に CircleCI に接続するために、`runner.circleci.com` と `circleci-binary-releases.s3.amazonaws.com` へのアウトバウンド HTTPS 接続が必要です。

NOTE: No inbound connectivity is required by a self-hosted runner. それ以外では、ジョブの内容に応じた接続が必要になります。

CAUTION: チェックアウト ステップでは、VCS プロバイダーへのアクセスが必要です。 キャッシュ、ワークスペース、アーティファクトを使用する場合は、`circle-production-customer-artifacts.s3.amazonaws.com` へのアウトバウンド HTTPS 接続が必要になります。

== How do caching, workspaces, and artifacts work with CircleCI self-hosted runners?

Caches, workspaces, and artifacts are methods you can implement to help persist data between jobs, and speed up builds. Caches, workspaces, and artifacts will be stored in the AWS us-east-1 region of S3. If your self-hosted runners are not in this region, then you may see reduced performance.

Find out more about these concepts below:

* <<caching#, キャッシュ>>
* <<workspaces#, ワークスペース>>
* <<artifacts#, アーティファクト>>

You can also find out more on the <<persist-data#, Persisting Data>> page.

If you would prefer to take complete control of artifact storage, CircleCI recommends you avoid the built-in steps and upload the artifacts directly to your chosen storage backend.

== ジョブ間の状態管理に関するベストプラクティスを教えてください。

The self-hosted runner itself is unopinionated about this. Self-hosted runners can be configured to give each job a unique working directory and clean it up afterwards - but this is optional. And by default, nothing restricts the job from placing files outside of its working directory.

一般的には、再現性が高まるよう、ジョブが状態に依存することは最小限に抑えることをお勧めします。 そのためには、前のジョブの結果に依存せずに確実にジョブが実行されるように、ジョブの最初にクリーンにするステップを配置するのが効果的です。

CAUTION: ホスト上に保持されるキャッシュをジョブ間で利用すると、ビルド時間の短縮を期待できますが、一方で、再現性は低下します。 また、長期的には、ディスク容量を使い果たす可能性もあります。 As a result, this trade-off could lead to higher billable usage.

== 1 つのホスト上で複数のランナーを実行することはできますか。

はい。 `launch-agent` の複数のレプリカを、それぞれに一意の名前を設定して実行すれば、1 つのホスト上で必要な数のランナー (言い換えると、必要な数のジョブ) を実行できます。 ただし、同時に実行したときに競合が発生しないように、ジョブが相互に十分に分離されるよう特に注意してください。

== Can I delete self-hosted runner resource classes?

Yes, self-hosted runner resource classes can be deleted through the <<local-cli#, CLI>>. Please be sure you want to permanently delete the resource class, as this action cannot be undone.

Before you can delete the resource class, any tokens associated with the resource class will need to be deleted first.

```bash
circleci runner token delete <token-id>
```

Once the tokens have been deleted, you can delete the resource class.

```bash
circleci runner resource-class delete <resource-class>
```

== Can jobs on forks of my OSS project use my organization's self-hosted runners if the fork is not a part of my organization?

No, runner resource classes cannot be used by jobs that are not associated with the organization that owns the runner resource classes. Only forks of your OSS project that _are_ a part of your organization may use the organization's self-hosted runners.
