---

layout: classic-docs
short-title: Scheduled Pipelines
contentTags:
  platform:
  - Cloud
---
= Scheduled pipelines
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI プロジェクトでパイプラインをスケジュール実行する方法を説明します。
:icons: font
:toc: macro

:toc-title:

**Scheduled pipelines are currently available for GitHub and Bitbucket VCS users.** Scheduled pipelines allow you to trigger pipelines periodically based on a schedule. パイプラインのスケジュール実行では、以下のようなパイプラインのすべての機能が保持されます。

- Control the actor (yourself, or the scheduling system) associated with the pipeline, which can enable the use of xref:contexts#project-restrictions[Restricted contexts].
- Use xref:dynamic-config#[Dynamic configuration] via setup workflows.
- Modify the schedule without having to edit `.circleci/config.yml`.
- Take advantage of xref:skip-build#auto-cancelling[auto-cancelling].
- Specify xref:pipeline-variables#pipeline-parameters-in-configuration[Pipeline parameters] associated with a schedule.
- ワークフロー間などで共通するスケジュールの管理.

パイプラインのスケジュール実行は、API を使って、または CircleCI Web アプリのプロジェクト設定から設定します。

NOTE: パイプラインのスケジュール実行は、1 つのブランチに対してのみ設定できます。 2 つのブランチに対してスケジュール実行をしたい場合、2 つのスケジュールを設定する必要があります。

[#introduction]
== はじめに

Scheduled pipelines allow you to trigger pipelines periodically based on a schedule, from either the CircleCI web app or API. Schedules can range from daily, weekly, monthly, or on a very specific timetable. To set up basic scheduled pipelines, you do not need any extra configuration in your `.circleci/config.yml` file, however, more advanced usage of the feature will require extra `.circleci/config.yml` configuration (for example, workflow filtering, or using parameters).

Pipeline parameters are typed pipeline variables in the form of a string, integer, or boolean. Adding a parameter to a scheduled pipeline can be done in the web app in the triggers form while setting up a schedule. Any parameters set up in this manner must be added to your configuration file using the `parameters` key.

Scheduled pipelines are set to run by an "actor", either the CircleCI scheduling system, or a specific user (for example, yourself). The scheduling actor is important to consider if making use of restricted contexts in workflows. If the user (actor) running the workflow does not have access to the context, the workflow will fail with the `Unauthorized` status.

You can find a basic how-to guide on the xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline] page, and more advanced examples on the xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows] pages.

[#get-started-with-scheduled-pipelines]
== パイプラインのスケジュール実行機能の使い方

パイプラインのスケジュール実行機能を使うには、API を使用する方法と、CircleCI Web アプリを使用する方法があります。 それぞれの方法を下記でご紹介します。

[#use-project-settings]
=== Web アプリのプロジェクト設定を使用する

1. CircleCI Web アプリで、サイドバーにある **Projects** に移動し、プロジェクトの隣にある 省略記号 (…) をクリックします。 **Project Settings** ボタンは各プロジェクトのランディングページにもあります。
1. **Triggers** に移動します。
1. 新しいスケジュールを作成するには、**Add Trigger** をクリックします。
1. フォームに入力して新しいスケジュールを定義し、**Save Trigger** をクリックします。

The form also provides the option of adding xref:pipeline-variables#[pipeline parameters], which are typed pipeline variables that you declare at the top level of a configuration.

If you would like to manage common schedules for multiple workflows, you will need to manually set this in your `.circleci/config.yml` file. See the xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows] page for examples.

[#use-the-api]
=== API を使用する場合

プロジェクトにスケジュール化したワークフローがなく、パイプラインのスケジュール実行を試してみたい場合：

1. CCI トークンを準備します、または xref:managing-api-tokens#[API トークンの管理] のページに記載されている手順に従って新しいトークンを作成します。
1. link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[API を使用] して新しいスケジュールを作成します。 たとえば以下のようになります。

```shell
curl --location --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
--header "circle-token: <PERSONAL_API_KEY>" \
--header "Content-Type: application/json" \
--data-raw '{
    "name": "my schedule name",
    "description": "some description",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
      <additional pipeline parameters can be added here>
    },
    "timetable": {
        "per-hour": 3,
        "hours-of-day": [1,15],
        "days-of-week": ["MON", "WED"]
    }
}'
```

詳細については、link:https://circleci.com/docs/api/v2[API v2 に関するドキュメント]の **スケジュール** のセクションを参照してください。

[#migrate-scheduled-workflows-to-scheduled-pipelines]
== ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行

If you have existing scheduled workflows you need to migrate to scheduled pipelines, use the xref:migrate-scheduled-workflows-to-scheduled-pipelines#[Scheduled pipelines migration] guide.

[#scheduled-pipelines-video-tutorial]
== パイプラインのスケジュール実行のビデオチュートリアル

このビデオでは以下のシナリオに対する短いチュートリアルをご覧いただけます。

- Web アプリでスケジュールを設定する
- API を使ってスケジュールを設定する
- ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行する

<div class="video-wrapper">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/x3ruGpx6SEI" title="Scheduled pipelines tutorial" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

For the documentation for these scenarios, visit the following pages:
- xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline]
- xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows]

[#scheduled-pipelines-faqs]
== FAQ

include::../_includes/snippets/faq/scheduled-pipelines-faq-snip.adoc[]

[#next-steps]
== 次のステップ

- xref:migrate-scheduled-workflows-to-scheduled-pipelines#[Migrate scheduled workflows to scheduled pipelines]
- xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows]
- xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline]