---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
  - Server v2.x
---
= 複数のワークフローを使ったパイプラインのスケジュール実行
:page-layout: classic-docs
:page-liquid:
:page-description: 複数のワークフローにおけるパイプラインのスケジュール実行の条件を設定する方法を説明します。
:icons: font
:toc: macro

:toc-title:

[#introduction]
== はじめに

Scheduled pipelines are simply triggered pipelines, and by default, for each trigger, every workflow that has been configured will run. You can filter workflows in your `.circleci/config.yml` file with conditionals. The conditionals you set will control which workflows will run when a scheduled pipeline is triggered. These conditions can be set with built-in pipeline values, or through custom pipeline parameters. The examples below demonstrate various ways to set conditionals in your `.circleci/config.yml` file.

[#schedule-using-built-in-pipeline-values]
== Schedule using built-in pipeline values

ワークフローのフィルタリングを実装するための 1 つの方法は、パイプライン値を使用することです。 The example below uses the built-in pipeline values `pipeline.trigger_source` and `pipeline.schedule.name`. The examples use `daily_build` and `nightly_build` as the `pipeline.schedule.name`, however, the value of `pipeline.schedule.name` can be whatever you would like when using scheduled pipelines.

```yaml
version: 2.1
...
daily-run-workflow:
# run workflow only when the daily_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ daily_build, << pipeline.schedule.name >> ]
  jobs:
    - test
    - build

nightly-run-workflow:
# run workflow only when the nightly_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ nightly_build, << pipeline.schedule.name >> ]
  jobs:
    - build
    - deploy
...
```

上記の例の `when` の下の２番目の `equal` は必ずしも必要ではありません。 `pipeline.schedule.name` は、パイプラインがスケジュールによってトリガーされる場合に使用できるパイプライン値です。

スケジュールがトリガーされる時に *実行しない* ワークフローのフィルタリングを追加することもできます。

{% raw %}

```yaml
version: 2.1
...
daily-run-workflow:
# run workflow only when the daily_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ daily_build, << pipeline.schedule.name >> ]
  jobs:
    - test
    - build

nightly-run-workflow:
# do NOT run workflow if a scheduled pipeline is triggered
  when:
    not:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  jobs:
   - build
   - deploy
...
```

{% endraw %}

パイプライン値の全リストは、xref:pipeline-variables/#pipeline-values[パイプラインの値とパラメーター] でご確認ください。

[#schedule-using-pipeline-parameters]
== Schedule using pipeline parameters

下記の例では、 `run-schedule` というパラメーターが作成され、`type: boolean` および `default: false` と設定されています。 これにより、ワークフローのセクションで `when` を使っていつパイプラインを実行するかの条件を指定できます。 `when` 条件を使用する場合は、以下の例のように `when: not:` も設定する必要があります。

```yaml
version: 2.1
...
# set pipeline parameters
parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  # do not run the scheduled pipeline if build-test-deploy
  build-test-deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - test
      - build
  # run the scheduled pipeline if nightly-snapshot
  nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - build
      - deploy
...
```

この設定ファイルサンプルの全文は、GitHub 上の link:https://github.com/zmarkan/Android-Espresso-ScrollableScroll/blob/main/.circleci/config.yml[サンプルプロジェクト] をご覧ください。 パイプラインパラメーターの全リストは、xref:pipeline-variables/#pipeline-parameters-in-configuration[パイプラインの値とパラメーター] でご確認ください。

[#set-up-multiple-workflows-with-multiple-schedules]
== Set up multiple workflows with multiple schedules

The example below demonstrates three workflows scheduled with pipeline values. Two workflows will run on the same schedule (`daily_build`), and one will run on a different schedule (`weekly_build`).

```yaml
version: 2.1
...
workflows:
# run workflow only when the daily_build pipeline is triggered
  daily-run-workflow:
    when:
      equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job-one

  nightly-run-workflow:
  # run workflow only when the daily_build pipeline is triggered
    when:
      equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job-two

  weekly-run-workflow:
  # run workflow only when the weekly_build pipeline is triggered
    when:
      equal: [ weekly_build, << pipeline.schedule.name >> ]
    jobs:
      - job-three
...
```

[#next-steps]
== 次のステップ

- xref:set-a-nightly-scheduled-pipeline.adoc[パイプラインのスケジュール実行を夜間に設定する]
- xref:migrate-scheduled-workflows-to-scheduled-pipelines.adoc[ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行]