---

layout: classic-docs
short-title: Scheduled Pipelines
contentTags:
  platform:
  - クラウド
---
= パイプラインのスケジュール実行
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI プロジェクトでパイプラインをスケジュール実行する方法を説明します。
:icons: font
:toc: macro

:toc-title:

*パイプラインのスケジュール実行機能は現時点では GitHub VCS ユーザーと Bitbucket VCS ユーザーにご利用いただけます。* パイプラインのスケジュール実行機能を使うと、スケジュールに基づき定期的にパイプラインをトリガーすることができます。 パイプラインのスケジュール実行では、以下のようなパイプラインのすべての機能が保持されます。

- パイプラインに関連付けるユーザーの管理: これにより、xref:contexts#project-restrictions[制限付きコンテキスト]の使用が可能になります。
- セットアップ ワークフロー経由のxref:dynamic-config#[ダイナミックコンフィグ]の使用
- `.circleci/config.yml`. の編集が不要なスケジュール変更
- xref:skip-build#auto-cancelling[自動キャンセル機能]の利用.
- スケジュールに関連付ける xref:pipeline-variables#pipeline-parameters-in-configuration[パイプライン パラメーター]の指定。
- ワークフロー間などで共通するスケジュールの管理.

パイプラインのスケジュール実行は、API を使って、または CircleCI Web アプリのプロジェクト設定から設定します。

NOTE: パイプラインのスケジュール実行は、1 つのブランチに対してのみ設定できます。 2 つのブランチに対してスケジュール実行をしたい場合、2 つのスケジュールを設定する必要があります。

[#introduction]
== はじめに

Scheduled pipelines allow you to trigger pipelines periodically based on a schedule, from either the CircleCI web app or API. Schedules can range from daily, weekly, monthly, or on a very specific timetable. To set up basic scheduled pipelines, you do not need any extra configuration in your `.circleci/config.yml` file, however, more advanced usage of the feature will require extra `.circleci/config.yml` configuration (for example, workflow filtering, or using parameters).

Pipeline parameters are typed pipeline variables in the form of a string, integer, or boolean. Adding a parameter to a scheduled pipeline can be done in the web app in the triggers form while setting up a schedule. Any parameters set up in this manner must be added to your configuration file using the `parameters` key.

Scheduled pipelines are set to run by an "actor", either the CircleCI scheduling system, or a specific user (for example, yourself). The scheduling actor is important to consider if making use of restricted contexts in workflows. If the user (actor) running the workflow does not have access to the context, the workflow will fail with the `Unauthorized` status.

You can find a basic how-to guide on the xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline] page, and more advanced examples on the xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows] pages.

[#get-started-with-scheduled-pipelines]
== パイプラインのスケジュール実行機能の使い方

パイプラインのスケジュール実行機能を使うには、API を使用する方法と、CircleCI Web アプリを使用する方法があります。 それぞれの方法を下記でご紹介します。

[#use-project-settings]
=== Web アプリのプロジェクト設定を使用する

1. CircleCI Web アプリで、サイドバーにある **Projects** に移動し、プロジェクトの隣にある 省略記号 (…) をクリックします。 **Project Settings** ボタンは各プロジェクトのランディングページにもあります。
1. **Triggers** に移動します。
1. 新しいスケジュールを作成するには、**Add Trigger** をクリックします。
1. フォームに入力して新しいスケジュールを定義し、**Save Trigger** をクリックします。

このフォームでは、xref:pipeline-variables#[パイプラインパラメーター] を追加するオプションも指定します。これは、設定ファイルで最初に宣言した型指定されたパイプライン変数です。

複数のワークフローで共通のスケジュールを管理するには、`.circleci/config.yml` ファイルで手動で設定する必要があります。 コード例については xref:schedule-pipelines-with-multiple-workflows#[複数のワークフロー]を使ったパイプラインのスケジュール実行のページを参照してください。

[#use-the-api]
=== API を使用する場合

プロジェクトにスケジュール化したワークフローがなく、パイプラインのスケジュール実行を試してみたい場合：

1. CCI トークンを準備します、または xref:managing-api-tokens#[API トークンの管理] のページに記載されている手順に従って新しいトークンを作成します。
1. link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[API を使用] して新しいスケジュールを作成します。 たとえば以下のようになります。

```shell
curl --location --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
--header "circle-token: <PERSONAL_API_KEY>" \
--header "Content-Type: application/json" \
--data-raw '{
    "name": "my schedule name",
    "description": "some description",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
      <additional pipeline parameters can be added here>
    },
    "timetable": {
        "per-hour": 3,
        "hours-of-day": [1,15],
        "days-of-week": ["MON", "WED"]
    }
}'
```

詳細については、link:https://circleci.com/docs/api/v2[API v2 に関するドキュメント]の **スケジュール** のセクションを参照してください。

[#migrate-scheduled-workflows-to-scheduled-pipelines]
== ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行

パイプラインのスケジュール実行に移行する必要がある既存のワークフローがある場合は、xref:migrate-scheduled-workflows-to-scheduled-pipelines#[パイプラインのスケジュール実行への移行ガイド]をご覧ください。

[#scheduled-pipelines-video-tutorial]
== パイプラインのスケジュール実行のビデオチュートリアル

このビデオでは以下のシナリオに対する短いチュートリアルをご覧いただけます。

- Web アプリでスケジュールを設定する
- API を使ってスケジュールを設定する
- ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行する

<div class="video-wrapper">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/x3ruGpx6SEI" title="Scheduled pipelines tutorial" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

For the documentation for these scenarios, visit the following pages:
- xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline]
- xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows]

[#scheduled-pipelines-faqs]
== FAQ

include::../_includes/snippets/faq/scheduled-pipelines-faq-snip.adoc[]

[#next-steps]
== 次のステップ

- xref:migrate-scheduled-workflows-to-scheduled-pipelines.adoc[ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行]
- xref:schedule-pipelines-with-multiple-workflows.adoc[複数のワークフローを使ったパイプラインのスケジュール実行]
- xref:set-a-nightly-scheduled-pipeline.adoc[パイプラインのスケジュール実行を夜間に設定する]