---
version:
- Server v2.x
- Server v3.x
- Server Admin
---
= Security
:page-layout: classic-docs
:page-liquid:
:page-description: This document outlines security features built into CircleCI and related integrations.
:icons: font
:toc: macro
:toc-title:

CircleCI に組み込まれているセキュリティ機能と、関連するインテグレーションの概要について説明します。

toc::[]

== 会社概要
CircleCI では、セキュリティを最優先事項と考え、セキュリティ問題発生の防止に努めると共に、問題発生時にはすばやい対応を心掛けています。 セキュリティに関する問題が発生した場合には、CircleCI セキュリティ チームの GPG キー (ID: 0x4013DDA7、フィンガープリント: 3CD2 A48F 2071 61C0 B9B7 1AE2 6170 15B8 4013 DDA7) を使用して、security@circleci.com まで暗号化メッセージをお送りください。

== 暗号化
CircleCI uses HTTPS or SSH for all networking in and out of our service, including from the browser to our services application, from the services application to your builder fleet, from our builder fleet to your source control system, and all other points of communication. None of your code or data travels to or from CircleCI without being encrypted, unless you have code in your builds that does so at your discretion. Operators may also choose to bypass our SSL configuration or not use TLS for communicating with underlying systems.

CircleCI のソフトウェアは性質上、ユーザーのコードやそのコードが操作するあらゆるデータにアクセスできます。 CircleCI 上のすべてのジョブは、他のあらゆるビルドから独立し、インターネットやユーザー自身のネットワークからアクセスできないサンドボックス (具体的には、Docker コンテナまたはエフェメラル VM) 内で実行されます。 ビルド エージェントは、SSH によって Git からコードをプルします。 特定のテスト スイートまたはジョブ構成は、外部サービスまたはネットワーク内のインテグレーション ポイントに対して呼び出しを行うことができます。 そうした呼び出しからの応答は、ジョブにプルされ、ユーザー自身の判断でコードに使用されます。 1 つのジョブが完了すると、ジョブを実行したコンテナは廃棄され、リビルドされます。 すべての環境変数は、https://www.vaultproject.io/[HashiCorp の Vault] を使用して暗号化されます。 環境変数は、AES256-GCM96 を使用して暗号化され、CircleCI の従業員には使用できません。

== サンドボックス化
With CircleCI, you control the resources allocated to run the builds of your code. これは、ビルドが実行されるコンテナをセットアップする Builder boxes のインスタンスを介して行われます。 By their nature, build containers will pull down source code and run whatever test and deployment scripts are part of the codebase or your configuration. つまり、ビルド (または並列ビルドの一部分) ごとに専用のコンテナが 1 つずつ作成され、破棄されます。 これらのコンテナは外部から使用することはできません。 CircleCI のサービスでは、特定のビルド コンテナに直接 SSH 接続できる機能が提供されています。 When accessing a container this way, a user will have complete access to any files or processes being run inside that build container. Only provide CircleCI access to those also trusted with your source code.

== インテグレーション
CircleCI には、関連する外部のサービスやテクノロジーとのインテグレーション ポイントがいくつかあります。 The following list explains those integration points.

- **Web Sockets** We use https://pusher.com/[Pusher] client libraries for WebSocket communication between the server and the browser. However, for installs we use an internal server called Slanger, so Pusher servers have no access to your instance of CircleCI nor your source control system. This is how we, for instance, update the builds list dynamically, or show the output of a build line-by-line as it occurs. ビルド ステータスとビルド出力の行は、WebSocket サーバーを経由して送信されます (SSL なしで実行するように CircleCI を構成しない限り、SSL 上で同じ証明書を使用して行われます)。したがって、転送時には暗号化されます。

- *Replicated:* CircleCI は、http://www.replicated.com/[Replicated] を使用して、インストール ウィザード、ライセンス キー、システム監査ログ、ソフトウェアの更新など、CircleCI のメンテナンスやシステムに関する作業を管理します。 CircleCI インスタンスは、更新の有無を確認するために、Replicated サーバーと通信してライセンスキー情報やバージョン情報を送信します。 Replicated がユーザーのデータや他のシステムにアクセスすることはありません。

- *ソース管理システム:* CircleCI を使用するには、GitHub Enterprise、GitHub.com などのインスタンスとの直接接続をセットアップします。 When you set up CircleCI, you authorize the system to check out your private repositories. この権限は、GitHub アプリケーションの設定ページで、リポジトリの管理者ページから CircleCI のデプロイ キーとサービス フックを削除することで、いつでも取り消すことができます。 CircleCI ではプロジェクトを選択してビルドできますが、GitHub の権限モデルは極端なものであるため、CircleCI にはすべてのリポジトリへのアクセスが許可されるか、一切許可されないかのどちらかになります。 Your instance of CircleCI will have access to anything hosted in those git repositories and will create webhooks for a variety of events (for example, when code is pushed, when a user is added, etc.) that will call back to CircleCI, triggering one or more git commands that will pull down code to your build fleet.

- *依存関係とソースのキャッシュ:* ほとんどの CircleCI ユーザーは、Amazon VPC などのプライベート クラウド インフラストラクチャ内で S3 または同等のクラウドベースのストレージを使用して、依存関係やソースのキャッシュを格納しています。 これらのストレージ サーバーは、このようなサービス上に格納されるすべての項目の標準的なセキュリティ パラメーターの対象となります。 つまり、ほとんどの場合、ユーザーは外部からのアクセスを阻止できます。

- *アーティファクト:* アーティファクトには、S3 などのホスティングされたストレージを使用するのが一般的です。 Assuming these resources are secured per your normal policies, they are as safe from any outside intrusion as any other data you store there.

== 監査ログ
監査ログ機能は、独自のサーバーまたはプライベートクラウド上にインストールした CircleCI でのみ使用できます。

CircleCI では、監査およびフォレンジック分析の目的で、重要なイベントをログとしてシステムに記録します。 監査ログは、パフォーマンスやネットワーク メトリクスを追跡するシステム ログとは区別されます。

Complete Audit logs may be downloaded as a CSV file from the Audit Log page within the Admin section of the application. ネストされたデータを含む監査ログフィールドには JSON BLOB が含まれます。 Please note the audit log download can take a very long time to start; we recommend clicking the Download button once and leaving it to run.

*メモ：*内部挙動により、重複するイベントが監査ログに生成される場合があります。 ダウンロードしたログの `id` フィールドはイベントに固有であるため、このフィールドを使用して重複するエントリを特定できます。

=== 監査ログ イベント

// TODO: automate this from event-cataloger
The following are the system events that are logged. 定義と形式については、以下の「監査ログフィールド」セクションの `action` を参照してください。

- context.create
- context.delete
- context.env_var.delete
- context.env_var.store
- project.env_var.create
- project.env_var.delete
- project.settings.update
- user.create
- user.logged_in
- user.logged_out
- workflow.job.approve
- workflow.job.finish
- workflow.job.scheduled
- workflow.job.start


=== 監査ログ フィールド

- *action:* 実行され、イベントを生成したアクション。 ドット区切りの小文字 ASCII ワードの形式が使用され、最初に影響を受けたエンティティと最後に実行されたアクションが含まれます。 エンティティは、たとえば `workflow.job.start` のようにネストされる場合があります。
- *actor:* 対象のイベントを実行したアクター。 In most cases, this will be a CircleCI user. このデータは JSON BLOB で、`id` と `type` が必ず含まれ、多くの場合 `name` も含まれます。
- *target:* 対象のイベントで影響を受けたエンティティ インスタンス (プロジェクト、組織、アカウント、ビルドなど)。 このデータは JSON BLOB で、`id` と `type` が必ず含まれ、多くの場合 `name` も含まれます。
- *payload:* アクション固有の情報の JSON BLOB。 payload のスキーマは、同じ `action` と `version` を持つすべてのイベントで一貫していると想定されます。
- *occurred_at:* イベントが発生した UTC 日時。 時刻は、最大 9 桁の小数精度の ISO-8601 形式で表されます (例：'2017-12-21T13:50:54.474Z')。
- *metadata:* 任意のイベントに付加できるキー・値のペアのセット。 キーと値はすべて文字列です。 これを使用すると、特定の種類のイベントに情報を追加できます。
- *id:* 対象のイベントを一意に識別する UUID。 イベントのコンシューマーが、重複するデリバリーを識別できるようにします。
- *version:* イベント スキーマのバージョン。 現在、値は必ず「1」になります。 今後のバージョンでは、スキーマの変更に合わせてこの値も変更になる可能性があります。
- *scope:* ターゲットが CircleCI ドメイン モデル内のアカウントによって所有されている場合、アカウント フィールドにはアカウント名と ID が挿入されます。 このデータは JSON BLOB で、`id` と `type` が必ず含まれ、多くの場合 `name` も含まれます。
- *success:* アクションが成功したかどうかを示すフラグ。
- **request:** If this event was triggered by an external request, this data will be populated and may be used to connect events that originate from the same external request. `id` (CircleCI がこのリクエストにより割り当てた一意の ID) を含む JSON BLOB の形式で表示されます。

== CircleCI を安全に使用していただくためのチェックリスト

If you are getting started with CircleCI, there are some points you can ask your team to consider for security best practices as _users_ of CircleCI:

* Minimize the number of secrets (private keys / environment variables) your build needs and rotate secrets regularly.
  ** 組織のシークレットを定期的に (チーム メンバーが変わるときは特に) 入れ替えることが重要です。
  ** シークレットを定期的に入れ替えることで、シークレットの有効期限が設けられ、キーが漏洩した場合の潜在的なリスクを軽減できます。
  ** Ensure the secrets you _do_ use are of limited scope, with only enough permissions for the purposes of your build. Consider carefully adjudicating the role and permission systems of other platforms you use outside of CircleCI; for example, when using something such as IAM permissions on AWS, or GitHub's https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users[Machine User] feature.
* Sometimes user misuse of certain tools might accidentally print secrets to stdout which will appear in your logs. 以下の場合には注意してください。
  ** すべての環境変数を stdout に出力する `env` または `printenv` を実行する場合
  ** `echo` を使用し、コード ベースまたはシェル内のシークレットを出力する場合
  ** プログラムやデバッグ ツールがエラー時にシークレットを出力する場合
* Consult your VCS provider's permissions for your organization (if you are in an organization) and try to follow the https://en.wikipedia.org/wiki/Principle_of_least_privilege[Principle of Least Privilege].
* チーム間では制約付きコンテキストを使用し、環境変数は一部のセキュリティ グループでのみ共有します。 詳細については、https://circleci.com/docs/2.0/contexts/#restricting-a-context[コンテキストに関するドキュメント]をお読みください。
* SSH キーへのアクセス権を持つ人間は、必ず組織による監査の対象とします。
* VCS で 2 要素認証 (2FA) を必ず使用します (https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa[Github 2FA]、https://confluence.atlassian.com/bitbucket/two-step-verification-777023203.html[Bitbucket])。 ユーザーの GitHub または Bitbucket アカウントが漏れると、悪意のあるアクターによってコードがプッシュされたり、秘密が盗まれたりする危険性があります。
* If your project is open source and public, please make note of whether you want to share your environment variables. CircleCI では、プロジェクトの設定を変更して、_フォークされたバージョンのリポジトリ_に環境変数を渡すかどうかを制御できます。 これは、デフォルトでは*有効になっていません*。 You can read more about these settings and open source security in our https://circleci.com/docs/2.0/oss/#security[Open Source Projects Document].