---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Orbs
:page-layout: classic-docs
:page-liquid:
:page-description: Use this document to learn about orbs and how to manage them within CircleCI server v3.x.
:icons: font
:toc: macro
:toc-title:

This section describes how to manage orbs for an installation of server v3.x. CircleCI Server システムには、固有のローカル Orb レジストリが含まれています。 All orbs referenced in configs refer to the orbs in the server orb registry. Orb のメンテナンスはご自身で行う必要があります。 This includes copying orbs from the public registry, updating orbs that may have been previously copied, and registering your company's private orbs, if they exist.

For information on orbs and related use cases, see the https://circleci.com/docs/2.0/orb-intro/#quick-start[Orb docs].

If you are looking for information on creating an orb, see the https://circleci.com/docs/2.0/orb-author-intro/[Introduction to Authoring Orbs].

toc::[]

## Orb の管理
Orb には、https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] からアクセスします。 Orbs require your CircleCI user to be an admin. They also require a https://circleci.com/docs/2.0/managing-api-tokens/[personal API token].
Please ensure that you are using a personal API token generated _after_ your user account is made an admin.

Providing a local repository location using the `--host` option allows you to access your local server orbs, rather than public cloud orbs. For example, if your server installation is located at `\http://circleci.somehostname.com`, then you can run orb commands local to that orb repository by passing `--host \http://cirlceci.somehostname.com`.

## 利用可能な Orb の一覧表示
To list available public orbs, visit the orb directory, or run the following command:

```bash
circleci orb list
```

To list available private orbs (registered in your local server orb repository), run the following command:
```bash
circleci orb list --host <your server install domain> --token <your api token>
```

## パブリック Orb のインポート
To import a public orb to your local server orb repository, run the following command:

```bash
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```

## Fetch a public orb’s updates
ローカルの CircleCI Server Orb リポジトリに存在するパブリック Orb を新しいバージョンに更新するには、以下のコマンドを実行します。

```bash
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```

## プロキシ内での Orb の使用

Orb をインポートする際は、CLI が CircleCI サーバー環境および circleci.com と通信できる状態にある必要があります。 If you want to do this when using a server installation behind a proxy, the CLI needs to be configured to use the proxy to make those requests to `circleci.com`, rather than proxying requests to the server install. 例えば下記のようにします。

```bash
export NO_PROXY=server.example.com
export HTTPS_PROXY=http://proxy.example.com:3128
export HTTP_PROXY=http://proxy.example.com:3128
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```


