---

version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Managing Orbs
:page-layout: classic-docs
:page-liquid:
:page-description: Use this document to learn about orbs and how to manage them within CircleCI server v3.x.
:icons: font
:toc: macro

:toc-title:

ここでは Server v3.x. で Orb を管理する方法を説明します。 CircleCI Server システムには、固有のローカル Orb レジストリが含まれています。
このレジストリは、CircleCI Server からのみアクセスできます。 設定ファイルで参照された Orb はすべて、この CircleCI Server Orb レジストリに含まれる Orb を参照します。 Orb のメンテナンスはご自身で行う必要があります。 This includes copying orbs from the public registry, updating orbs that may have been previously copied, and registering your company's private orbs, if they exist.

For information on orbs and related use cases, see the https://circleci.com/docs/2.0/orb-intro/#quick-start[Orb docs].

If you are looking for information on creating an orb, see the https://circleci.com/docs/2.0/orb-author-intro/[Introduction to Authoring Orbs].

toc::[]

== Orb の管理

Orbs are accessed via the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI]. Orb を使用するには、管理者である必要があります。 They also require a https://circleci.com/docs/2.0/managing-api-tokens/[personal API token].

Please ensure that you are using a personal API token generated _after_ your user account is made an admin.

Providing a local repository location using the `--host` option allows you to access your local server orbs, rather than public cloud orbs. For example, if your server installation is located at `\http://circleci.somehostname.com`, you can run orb commands local to that orb repository by passing `--host \http://cirlceci.somehostname.com`.

== 利用可能な Orb の一覧表示

利用可能なパブリック Orb のリストを表示するには、Orb ディレクトリにアクセスするか、以下のコマンドを実行します。

```bash
circleci orb list
```

(ローカルの CircleCI Server Orb リポジトリに登録された) 利用可能なプライベート Orb のリストを表示するには、次のコマンドを実行します。

```bash
circleci orb list --host <your-server-install-domain> --token <your-api-token>
```

== パブリック Orb のインポート

パブリック Orb をローカルサーバーの Orb リポジトリにインポートするには、次のコマンドを実行します。

```bash
circleci admin import-orb <namespace>[<orb-name>[@<orb-version>]] --host <your-server-installation-domain> --token <your-api-token>
```

NOTE: 名前空間の指定のみを行うよう選択することも可能です。この場合、名前空間にあるすべての Orb の最新バージョンがインポートされます。

== パブリック Orb の更新のフェッチ

ローカルの CircleCI Server Orb リポジトリに存在するパブリック Orb を新しいバージョンに更新するには、以下のコマンドを実行します。

```bash
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```

== プロキシ内での Orb の使用

Orb をインポートする際は、CLI が CircleCI サーバー環境および circleci.com と通信できる状態にある必要があります。 If you want to do this when using a server installation behind a proxy, the CLI needs to be configured to use the proxy to make those requests to `circleci.com`, rather than proxying requests to the server install. 例えば下記のようにします。

```bash
export NO_PROXY=server.example.com
export HTTPS_PROXY=http://proxy.example.com:3128
export HTTP_PROXY=http://proxy.example.com:3128
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```