---
description: "このページでは、CircleCI Server v3.x のユーザーアカウントの管理に役立つ情報を紹介します。"
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x ユーザーアカウント
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このセクションでは、ユーザー アカウントの管理に役立つ情報を紹介します。 ユーザー アカウントの概要を確認するには、CircleCI アプリケーションの右上隅にあるプロファイルをクリックし、*[Admin (管理者)]* を選択して、[Admin Settings (管理者設定)] の [Overview (概要)] を表示します。

toc::[]

## アカウントの停止
このセクションでは、新規アカウント、アクティブなアカウント、非アクティブなアカウントを停止する方法を説明します。

### 新規アカウント

GitHub の組織に関連付けられているユーザーならだれでも、自社の CircleCI のユーザー アカウントを作成できます。 アクセス可能なユーザーを制御するため、すべての新規ユーザーを自動的に停止状態にし、管理者によるアクティブ化を必須化することができます。 この機能を使用するには、以下の手順を行います。

. CircleCI の [Admin Settings (管理者設定)] に移動します。
. [Admin Settings (管理者設定)] メニューから *[System Settings (システム設定)]* を選択します。
. *[Suspend New Users (新規ユーザーの停止)]* を *[true (有効)]* に設定します。

### アクティブなアカウント
アカウントが不要になった場合は、そのアカウントを停止することができます。 停止されたアカウントはアクティブではなくなり、ライセンス数にもカウントされません。 アカウントを停止するには、以下の手順を行います。

. CircleCI の [Admin Settings] に移動します。
. [Admin Settings] メニューから *[Users]* を選択します。
. 下へスクロールして、[Active (アクティブ)] ウィンドウまたは [Inactive (非アクティブ)] ウィンドウで、目的のアカウントを見つけます。
. アカウント名の隣にある Suspend をクリックすると、そのアカウントが Suspended (停止中) ウィンドウに表示されます。

### 非アクティブなアカウント
非アクティブなアカウントとは、CircleCI Server の管理者に承認されながらも、システムに正常にログインしていないアカウントのことです。 これらのアカウントは、利用可能な CircleCI Server のシート数にはカウントされません。

## アカウントの再アクティブ化
このセクションでは、新規アカウントや以前アクティブだったアカウントを再アクティブ化する方法を説明します。

### 新規アカウント
自動的に停止された新規アカウントをアクティブ化し、CircleCI Server に関連するユーザー アクセスを許可するには、以下の手順を行います。

. CircleCI の [Admin Settings] に移動します。
. [Admin Settings] メニューから *[Users]* を選択します。
. *[Suspended New Users (停止中の新規ユーザー)]*ウィンドウを確認します。
. アクセス権を付与するユーザー名の横にある [Activate (アクティブ化)] をクリックします。 そのアカウントが [Active] ウィンドウに表示されるようになります。

### 停止中のアカウント
停止したアカウントを再びアクティブ状態にするには、以下の手順を行います。

. CircleCI の [Admin Settings] に移動します。
. [Admin Settings] メニューから *[Users]* を選択します。
. [Suspended (停止中)] ウィンドウを表示します。
. アクセス権を付与するユーザー名の横にある [Activate (アクティブ化)] をクリックします。 そのアカウントが [Active] ウィンドウに表示されるようになります。

## GitHub 組織ごとのユーザー登録の制限
When using GitHub.com, you can limit who can register with your CircleCI install to people with some connection to your approved organizations list. この機能を使用するには、以下の手順を行います。

. Navigate to your CircleCI Admin Settings page.
. Select System Settings from the Admin Setting menu.
. Scroll down to Required Org Membership List.
. 承認する組織を入力します。 If entering more than one organization, use a comma- delimited string.