---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Load Balancers
:page-layout: classic-docs
:page-liquid:
:page-description: Use this guide to make the frontend load balancer private.
:icons: font
:toc: macro
:toc-title:

CircleCI server uses load balancers to manage network traffic entering and leaving the Kubernetes services cluster. Nomad クラスタへのトラフィックを管理するロード バランサーは 3 つあり、すべて VPC の内部ロード バランサーです。 これらは、さまざまなコンピューティング リソースへのジョブの分散を管理しています。 

The frontend load balancer manages traffic coming from developers and your VCS, including through the API, the CLI, and CircleCI app. フロントエンド ロード バランサーは、デフォルトでは公開に設定されていますが、非公開にすることも可能です。

toc::[]

== フロントエンド ロード バランサーを非公開にする

[WARNING]
==== 
*Web フック:* フロントエンド ロード バランサーを非公開にする場合、Web フックを機能させるために、以下に示す VCS に応じた条件を満たす必要があります。 

* *GitHub Enterprise* – CircleCI Server が GHE と同じ内部ネットワークにあること。 
* **GitHub.com** – set up a proxy for incoming webhooks and set it as override for the webhook host URL. この設定は、CircleCI アプリの *[Admin Settings (管理者設定)]* > *[System Settings (システム設定)]* > *[Override webhook host URL (Web フック ホスト URLのオーバーライド)]* にあります。
====

NOTE: プライベート ロード バランサー オプションは、GKE または EKS 上の CircleCI Server でのみ使用できます。

. 管理コンソールで、メニュー バーの *[Config (構成)]* を選択し、*[General Settings (全般設定)]* の下にある *[Private load balancers (プライベート ロード バランサー)]* オプションに移動します。

. *[Private load balancers (プライベート ロード バランサー)]* の横にあるチェック ボックスをオンにします。
+
NOTE: Let's Encrypt の TLS 証明書を使用している場合、このチェック ボックスは表示されません。 Let's Encrypt のチェック ボックスをオフにすると、プライベート ロード バランサーのオプションが表示されます。

If you are changing this setting after the initial deployment of CircleCI server, you may need to delete the old public load balancer so that Kubernetes will request a new load balancer with the new configuration.
