---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Metrics and Monitoring
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI server installation metrics collection and monitoring.
:icons: font
:toc: macro
:toc-title:

CPU やメモリの使用率などのメトリクス、および内部メトリクスを使用すると以下の事項が可能になります。

* インシデントや異常な動作の迅速な検出
* コンピューティング リソースの動的なスケーリング
* インフラ全体の問題をさかのぼって把握する

toc::[]

== メトリクスの収集

=== スコープ
Your CircleCI server installation collects a number of metrics and logs by default, which can be useful in monitoring the health of your system and debug issues with your installation.

NOTE: データは最大 15 日間保持されます。

NOTE: Prometheus のメトリクスの収集範囲は、CircleCI Server のみに限定されていません。 It will scrape metrics from your entire cluster by default. You may disable Prometheus from within the KOTS Admin Console config if needed.

=== Prometheus
https://prometheus.io/[Prometheus] は、Kubernetes 用の優れた監視およびアラート システムです。 Server 3.x ships with basic implementation of monitoring common performance metrics. 

=== KOTS 管理者 - メトリクス グラフ
デフォルトでは、Prometheus インスタンスは CircleCI Server と一緒にデプロイされます。 Once deployed, you may provide the address for your Prometheus instance to the KOTS Admin Console. KOTS will use this address to generate graph data for the CPU and memory usage of containers in your cluster.

The default Prometheus address is `\http://prometheus-server`

KOTS ダッシュボードの [Configure graphs (グラフの設定)] を選択します。 Then enter `\http://prometheus-server` and KOTS will generate resource usage graphs.

=== Telegraf
CircleCI Server 上で実行されるほとんどのサービスは、サーバーで実行されている https://www.influxdata.com/time-series-platform/telegraf/[Telegraf] ポッドに StatsD メトリクスを報告します。
The configuration is fully customizable, so you can forward your metrics from Telegraf to any output that is supported by Telegraf via https://docs.influxdata.com/telegraf/v1.17/plugins/#output-plugins[output plugins]. By default, it will provide a metrics endpoint for Prometheus to scrape.

=== Telegraf から Datadog へのメトリクスの転送
以下に、Telegraf から Datadog にメトリクスを出力する構成方法の例を示します。

Open the management console dashboard and select **Config** from the menu bar. *[Observability and monitoring (オブザーバビリティと監視)]* の下にある *[Custom Telegraf config (Telegraf カスタム設定)]* を見付けます。 There is an editable text window where you can configure plugins for forwarding Telegraf metrics for your server installation. To forward to Datadog, add the following code, substituting `my-secret-key` with your Datadog API key:

```
[[outputs.datadog]]
  ## "my-secret-key" を Datadog API キーに置き換える
  apikey = "my-secret-key"
```

詳細については、https://docs.influxdata.com/telegraf/v1.17/plugins/#output-plugins[Influxdata のドキュメント]を参照してください。

