---
version:
- Server v3.x
- サーバー管理
---
= CircleCI Server v3.x Operations Overview
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI サーバーの運用者に役立つメンテナンスとモニタリングに関する情報
:icons: font
:toc: macro
:toc-title:

The following guide contains information useful for CircleCI server Operators, or those responsible for ensuring CircleCI server 3.x is running properly through maintenance and monitoring.

本ページの内容は、https://circleci.com/docs/2.0/server-3-overview[CircleCI Server 3.x の概要]を先に読んでいることを前提としています。

CircleCI Server では、https://www.nomadproject.io/[Nomad スケジューラ]を使用して CI ジョブのスケジュールを設定します。 Nomad コントロール プレーンは Kubernetes 内で動作するのに対し、Nomad クライアントはクラスタ外部にプロビジョニングされます。 Nomad のクライアントは、Nomad のコントロール プレーンと出力プロセッサ、VM サービスにアクセスする必要があります。

CircleCI Server は Nomad クライアント上で Docker ジョブを実行しますが、専用の VM でジョブを実行することもできます。 These VM jobs are controlled by the Nomad clients, therefore the Nomad clients must be able to access the VM machines on port 22 for SSH and port 2376 for remote Docker jobs.

Job artifacts and outputs are sent directly from jobs in Nomad to object storage (S3, GCS, or other supported options).
Audit logs and other items from the application are also stored in object storage, so both the Kubernetes cluster and the Nomad clients will need access to object storage.

toc::[]

## 実行環境

CircleCI Server 3.x では、プライマリ ジョブ スケジューラとして Nomad を使用します。 ジョブ スケジューラ、およびクライアントとクラスタの基本的な操作方法については、https://circleci.com/docs/2.0/nomad/[Nomad クラスタの操作ガイド]を参照してください。

By default, CircleCI Nomad clients automatically provision compute resources according to the executors configured for each job in a project’s `.circleci/config.yml` file.

### Nomad クライアント
Nomad クライアントは実行後に状態を保持しないため、必要に応じてコンテナ数を増減することができます。

To ensure enough Nomad clients are running to handle all builds, track the queued builds, and then increase the number of Nomad client machines as needed to balance the load. For more on tracking metrics see the xref:server-3-operator-metrics-and-monitoring.adoc[Metrics and Monitoring] section.

ジョブのリソース クラスで必要なリソースが Nomad クライアントのインスタンス タイプで利用可能な量を超える場合、ジョブは保留状態のままになります。 Nomad クライアントのインスタンス タイプを小さいものにすればコストを削減できますが、CircleCI で使用できる Docker リソース クラスが制限されます。 https://circleci.com/docs/ja/2.0/executor-types/#available-docker-resource-classes[利用可能な Docker リソース クラス]を参照して、最適なものを判断してください。  デフォルトのインスタンス タイプでは、最大で `xlarge` リソース クラスを実行できます。

Nomad クライアントのリソースを最適に使用するためのオプションについては、https://www.nomadproject.io/docs/install/production/requirements#resources-ram-cpu-etc[Nomad ドキュメント]を参照してください。

NOTE: Nomad クライアント マシンの最大サイズは RAM 128GB/64 CPU です。 Contact your CircleCI account representative to request use of larger machines for Nomad clients.

Nomad のポート要件の詳細については、https://circleci.com/docs/2.0/server-3-install-hardening-your-cluster/?section=server-administration#nomad-clients[クラスタのハードニング]セクションをご覧ください。

### GitHub
CircleCI では、GitHub または GitHub Enterprise を ID プロバイダーとして使用しています。 また GitHub Enterprise では、https://docs.github.com/en/github-ae@latest/admin/authentication/about-identity-and-access-management-for-your-enterprise[SAML または SCIM]を使って、外部の ID プロバイダーでユーザーを管理することができます。

NOTE: CircleCI では、セットアップ後の URL やバックエンドの GitHub インスタンスの変更には対応していません。

The following table describes the ports used on machines running GitHub to communicate with the services and Nomad client instances.

--
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ソース
| ポート
| 用途

| サービス
| 22
| Git アクセス

| サービス
| 80 または 443
| API アクセス

| Nomad クライアント
| 22
| Git アクセス

| Nomad クライアント
| 80 または 443
| API アクセス
|===
--
