---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x ロードバランサー
:page-layout: classic-docs
:page-liquid:
:page-description: このページでは、フロントエンド ロードバランサーを非公開にする方法について解説しています。
:icons: font
:toc: macro
:toc-title:

CircleCI Server では、ロード バランサーを使用して Kubernetes サービス クラスタで送受信されるネットワーク トラフィックを管理しています。 Nomad クラスタへのトラフィックを管理するロード バランサーは 3 つあり、すべて VPC の内部ロード バランサーです。 これらは、さまざまなコンピューティング リソースへのジョブの分散を管理しています。 

フロントエンド ロード バランサーは、API、CLI、および CircleCI アプリなどを通じた、開発者や VCS からのトラフィックを管理しています。 フロントエンド ロード バランサーは、デフォルトでは公開に設定されていますが、非公開にすることも可能です。

== フロントエンド ロード バランサーを非公開にする

[WARNING]
==== 
**Webhooks:** If you choose to make the frontend load balancer private, the following conditions must be met, depending on your VCS, for webhooks to work: 

* *GitHub Enterprise* – CircleCI Server が GHE と同じ内部ネットワークにあること。 
* *Github.com* – 受信 Web フックのプロキシをセットアップし、Web フック ホスト URL のオーバーライドとして設定すること。 この設定は、CircleCI アプリの *[Admin Settings (管理者設定)]* > *[System Settings (システム設定)]* > *[Override webhook host URL (Web フック ホスト URLのオーバーライド)]* にあります。
====

NOTE: プライベート ロード バランサー オプションは、GKE または EKS 上の CircleCI Server でのみ使用できます。

. 管理コンソールで、メニュー バーの *[Config (構成)]* を選択し、*[General Settings (全般設定)]* の下にある *[Private load balancers (プライベート ロード バランサー)]* オプションに移動します。

. *[Private load balancers (プライベート ロード バランサー)]* の横にあるチェック ボックスをオンにします。
+
NOTE: If you are using Let's Encrypt TLS certificates, this box will not be visible as Let's Encrypt does not work with private installations. Let's Encrypt のチェック ボックスをオフにすると、プライベート ロード バランサーのオプションが表示されます。

If you are changing this setting after the initial deployment of CircleCI server, you may need to delete the old public load balancer so that Kubernetes requests a new load balancer with the new configuration.
