---
version:
- Server v3.x
- サーバー管理
---
= CircleCI Server v3.x インストール ステップ 4
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:


CircleCI Server v3.x のポストインストール ステップを開始する前に、 xref:server-3-install-prerequisites.adoc[ステップ 1 - 前提条件]、 xref:server-3-install.adoc[ステップ 2 - コアサービスのインストール] 、 xref:server-3-install-build-services.adoc[ステップ 3 - ビルドサービスのインストール]が実行済みであることを確認してください。

toc::[]

== ステップ 4: ポストインストール

=== Orb 

CircleCI Server システムには、固有のローカル Orb レジストリが含まれています。 このレジストリは、CircleCI Server からのみアクセスできます。 プロジェクト設定ファイルで参照された Orb はすべて、この _CircleCI Server_ の Orb レジストリに含まれる Orb を参照します。 Orb のメンテナンスはご自身で行う必要があります。 それには以下が含まれます。 

* パブリック レジストリからの Orb のコピー 
* 以前コピーした Orb の更新 
* 会社のプライベート Orb の登録 (存在する場合) 

詳細およびこれらのタスクを完了するための手順については、 https://circleci.com/docs/2.0/server-3-operator-orbs/[Orb on Server ガイド]を参照してください。

=== メール通知 

ビルドの通知はメールで送信されます。 KOTS の管理コンソールにアクセスします。 Get to the KOTS admin console by running the following, substituting your namespace: `kubectl kots admin-console -n <namespace>` and locate the *Email Notifications* section in *Settings* and fill in the following details to configure email notifications for your installation.

* *[Email Submission server hostname (メール送信サーバーのホスト名)] (必須)*: 送信サーバーのホスト名を指定します (例えば SendGrid の場合は smtp.sendgrid.net を使用)。

* *[Username (ユーザー名)](必須)*: 送信サーバーの認証に使用するユーザー名を指定します。 一般的には、ユーザーのメール アドレスと同一になります。

* *[Password (パスワード)](必須)*: 送信サーバーの認証に使用するパスワードを指定します。

* *[Port (ポート)](オプション)*: 送信サーバーのポートを指定します。 通常は 25 か 587 です。 メール送信にはポート 465 もよく使われますが、このポートは StartTLS ではなく暗黙的 TLS に使用することがほとんどです。 CircleCI Server では、送信の暗号化には StartTLS のみをサポートしています。 
+
NOTE: ポート 25 のアウトバウンド接続は、ほとんどのクラウド プロバイダーでブロックされます。 このポートを選択すると、通知の送信に失敗する可能性があります。
Enable StartTLS を有効にすると、メール送信が暗号化されます。 

* *[Email from address (メールの送信元アドレス)] (必須)*: メールの送信元アドレスを指定します。  

NOTE: デフォルトでは StartTLS がメールの暗号化に使用されますが、これを無効にするのは、他にトラフィックの機密性を保証できる場合のみにしてください。

*Save config (構成の保存)* ボタンをクリックし、CircleCI Server を更新して再デプロイします。

## 次に読む

* https://circleci.com/docs/2.0/server-3-install-hardening-your-cluster[クラスタのハードニング]
* https://circleci.com/docs/2.0/server-3-install-migration[CircleCI Server 3.x への移行]