---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Hardening Your Cluster
:page-layout: classic-docs
:page-liquid:
:page-description: This section provides supplemental information on hardening your Kubernetes cluster.
:icons: font
:toc: macro
:toc-title:

このセクションでは、Kubernetes クラスタのハードニングに関する補足情報を紹介します。

toc::[]

## ネットワーク トポロジ
A server installation basically runs three different type of compute instances: The Kubernetes nodes, Nomad clients, and external VMs.

これらのインスタンスは、CIDR ブロックの異なるサブネットに分けてデプロイすることを強くお勧めします。 そうすることで、システムのコンポーネント間を流れるトラフィックの制御やそれぞれの分離がしやすくなります。

通例どおり、リソースはできる限り非公開にすることが原則です。 CircleCI Server システムへのユーザー アクセスが VPN 経由に限られ、かつ NAT ゲートウェイが適切に設定されていれば、パブリック IP アドレスの割り当ては必要ありません。 そうでない場合は、少なくとも CircleCI Server Traefik ロード バランサー用にパブリック サブネットを 1 つ用意する必要があります。

ただし、この場合には、パブリック サブネットに Nomad クライアントと VM を配置して、ジョブにユーザーが SSH 接続できるようにするとともに、ネットワーク ルールでアクセス スコープを設定することもお勧めします。

現時点では、GCP はカスタムのサブネット化には対応していません。 カスタムのサブネット化は、今後の更新/リリースで使用可能になる予定です。

## ネットワーク トラフィック
This section explains the minimum requirements that are needed for a server installation to work. Depending on your workloads, you might need to add additional rules to egress for Nomad clients and VMs. Nomenclature between cloud providers differs, therefore, you will probably need to implement these rules using firewall rules and/or security groups.

表中の "外部" は、特に断りがない限り、すべての外部 IPv4 アドレスを意味します。 Depending on your particular setup, you might be able to be more specific (e.g., if you are using a proxy for all external traffic).

It is assumed that you have configured the load balancers for Nomad, vm-service and output processor to be internal load balancers. This is the default.

The rules explained here are assumed to be stateful and for TCP connections only, unless stated otherwise. ステートレス ルールを使用する場合には、下表の各項目に該当する送受信ルールをそれぞれ作成してください。

## Kubernetes ロード バランサー
Depending on your setup, your load balancers might be transparent (that is, they are not treated as a distinct layer in your networking topology). この場合には、ロード バランサーの背後にあるネットワーク トラフィックの送信先またはソースに対して、本セクションのルールを直接適用してください。 Refer to the documentation of your cloud provider to make sure you understand how to correctly apply networking security rules, given the type of load balancing you are using with your installation.

### 受信
ロード バランサーのトラフィック ルールが自動的に作成されていない場合は、次の各ポートを設定してください。

[.table.table-striped]
[cols=4*, options="header", stripes=even]
|===
| 名前
| ポート
| ソース
| 用途

| *-server-traefik
| 80
| 外部
| ユーザー インターフェイスとフロントエンド API

| *-server-traefik
| 443
| 外部
| ユーザー インターフェイスとフロントエンド API

| vm-service
| 3000
| Nomad クライアント
| Nomad クライアントとの通信

| nomad
| 4647
| Nomad クライアント
| Nomad クライアントとの通信

| output-processor
| 8585
| Nomad クライアント
| Nomad クライアントとの通信
|===

### 送信
必要な送信は、Kubernetes (K8s) ロード バランサーのポート (30000 ～ 32767) 上にある K8s ノードへの TCP トラフィックのみです。 ただし、ロード バランサーが透過的であればこの送信は必要ありません。

## コンピューティング インスタンスの共通ルール
以下のルールは、ロード バランサーを除くすべてのコンピューティング インスタンスに適用されます。

### 受信
If you want to access your instances using SSH, you will need to open port 22 for TCP connections for the instances in question.
It is recommended to scope the rule as closely as possible to allowed source IPs and/or only add such a rule when needed.

### 送信
ほとんどの環境では、インスタンスすべてに対してインターネット リソースへのアクセスを許可することになります。 This will require you to allow egress for UDP and TCP on port 53 to the DNS server within your VPC, as well as TCP ports 80 and 443 for HTTP and HTTPS traffic, respectively.
Instances building jobs (i.e. the Nomad clients and external VMs) also will likely need to pull code from your VCS using SSH (TCP port 22). SSH is also used to communicate with external VMs, so it should be allowed for all instances with the destination of the VM subnet and your VCS at the very least.

## Kubernetes ノード

### ノード間のトラフィック
デフォルトでは、K8s クラスタ内のトラフィックはネットワーク ポリシーにより制限されています。 For most purposes, this should be sufficient to regulate the traffic between pods and there is no additional requirement to reduce traffic between K8s nodes any further (i.e. it is fine to allow all traffic between K8s nodes).

クラスタ内でネットワーク ポリシーを使用するには、クラウド プロバイダーや環境設定にもよりますが、追加の手順を実行する必要があります。 以下の資料を参考にしてください。

* https://kubernetes.io/docs/concepts/services-networking/network-policies/[Kuberenetes のネットワーク ポリシーの概要]
* https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy[Google Cloud でのクラスタ ネットワーク ポリシーの作成]
* https://docs.aws.amazon.com/eks/latest/userguide/calico.html[Amazon EKS への Calico のインストール方法]

### 受信
マネージド サービスを使用している場合は、ロード バランサーおよび許可済みのポート範囲からの送信トラフィックに対して作成されているルールを確認できます。 受信側の設定では、K8s ロード バランサーの標準のポート範囲 (30000 ～ 32767) を許可するだけで十分です。 ただし、透過的なロード バランサーを使用している場合は、上記のロード バランサー用受信ルールを適用する必要があります。

### 送信

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| 送信先
| 用途

| 2376
| VM
| VM との通信

| 4647
| Nomad クライアント
| Nomad クライアントとの通信

| すべてのトラフィック
| その他のノード
| クラスタ内トラフィックの許可
|===

## Nomad クライアント
Nomad clients do not need to communicate with each other. You can block traffic between Nomad client instances completely.

### 受信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| ソース
| 用途

| 4647
| K8s ノード
| Nomad サーバーとの通信

| 64535 ～ 65535
| 外部
| SSH でのジョブ再実行機能
|===

### 送信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| 送信先
| 用途

| 2376
| VM
| VM との通信

| 3000
| VM サービスのロード バランサー
| 内部通信

| 4647
| Nomad のロード バランサー
| 内部通信

| 8585
| 出力プロセッサのロード バランサー
| 内部通信
|===

## 外部 VM
Nomad クライアントと同じく、外部 VM 同士も通信する必要はありません。

### 受信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| ソース
| 用途

| 22
| Kubernetes ノード
| 内部通信

| 22
| Nomad クライアント
| 内部通信

| 2376
| Kubernetes ノード
| 内部通信

| 2376
| Nomad クライアント
| 内部通信

| 54782
| 外部
| SSH でのジョブ再実行機能
|===

### 送信
設定が必要な送信ルールは、VCS へのインターネット アクセスと SSH 接続のみです。

ifndef::pdf[]
## 次に読む
* https://circleci.com/docs/ja/2.0/server-3-install-migration[CircleCI Server 3.x への移行]
* https://circleci.com/docs/ja/2.0/server-3-operator-overview[CircleCI Server 3.x の運用]
endif::[]
