---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Metrics and Monitoring
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI server installation metrics collection and monitoring.
:icons: font
:toc: macro
:toc-title:

CPU やメモリの使用率などのメトリクス、および内部メトリクスを使用すると以下の事項が可能になります。

* インシデントや異常な動作の迅速な検出.
* コンピューティング リソースの動的なスケーリング.
* インフラ全体の問題をさかのぼって把握する.

toc::[]

== メトリクスの収集

=== スコープ
Your CircleCI server installation collects a number of metrics and logs by default, which can be useful in monitoring the health of your system and debugging issues with your installation.

NOTE: データは最大 15 日間保持されます。

NOTE: Prometheus Server is not limited to scraping metrics from your CircleCI server install. By default, it scrapes metrics from your entire cluster. 必要に応じて、KOTS 管理者コンソールの [Config (設定)] から Prometheus を無効にできます。

=== Prometheus
https://prometheus.io/[Prometheus] は、Kubernetes 用の優れた監視およびアラート システムです。 CircleCI Server 3.x には、一般的なパフォーマンス メトリクスの監視が実装されています。

WARNING: この機能は、KOTS バージョン 1.65.0 - 1.67.0 で 破損しています。 この機能に依存している場合は、この問題が解決されるまで、KOTS のバージョンをアップグレードしないことをお勧めします。

=== KOTS 管理者 - メトリクス グラフ
デフォルトでは、Prometheus インスタンスは CircleCI Server と一緒にデプロイされます。 Once deployed, you may provide the address for your Prometheus instance to the KOTS Admin Console. KOTS uses this address to generate graph data for the CPU and memory usage of containers in your cluster.

The default Prometheus address is `\http://prometheus-server`

KOTS ダッシュボードの [Configure graphs (グラフの設定)] を選択します。 Then enter `\http://prometheus-server` and KOTS generates resource usage graphs.

=== Telegraf
Most services running on server report StatsD metrics to the https://www.influxdata.com/time-series-platform/telegraf/[Telegraf] pod running in server.
The configuration is fully customizable, so you can forward your metrics from Telegraf to any output supported by Telegraf through https://docs.influxdata.com/telegraf/v1.17/plugins/#output-plugins[output plugins]. By default, it will provide a metrics endpoint for Prometheus to scrape.

=== Telegraf から Datadog へのメトリクスの転送
以下に、Telegraf から Datadog にメトリクスを出力する構成方法の例を示します。

. Open the management console dashboard and select **Config** from the menu bar.
. *[Observability and monitoring (オブザーバビリティと監視)]* の下にある *[Custom Telegraf config (Telegraf カスタム設定)]* を見付けます。 There is an editable text window where you can configure plugins for forwarding Telegraf metrics for your server installation.
. To forward to Datadog, add the following code, substituting `my-secret-key` with your Datadog API key:
+
```
[[outputs.datadog]]
  ## "my-secret-key" を Datadog API キーに置き換える
  apikey = "my-secret-key"
```

詳細については、https://docs.influxdata.com/telegraf/v1.17/plugins/#output-plugins[Influxdata のドキュメント]を参照してください。