---
version:
- Server v3.x
- サーバー管理
---
= CircleCI Server v3.x の Orb
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このセクションでは、CircleCI Orb の概要とその管理方法を説明します。 CircleCI Server システムには、固有のローカル Orb レジストリが含まれています。 このレジストリは、CircleCI Server からのみアクセスできます。 設定ファイルで参照された Orb はすべて、この CircleCI Server Orb レジストリに含まれる Orb を参照します。 Orb のメンテナンスはご自身で行う必要があります。 具体的には、パブリック レジストリからの Orb のコピー、以前コピーした Orb の更新、会社のプライベート Orb の登録 (存在する場合) を行います。

toc::[]

## Orb の管理
Orb には、https://circleci.com/docs/ja/2.0/local-cli/[CircleCI CLI] からアクセスします。 Orb を使用するには、管理者である必要があります。 また、https://circleci.com/docs/ja/2.0/managing-api-tokens/が必要です。 `--host` オプションを使用してローカル リポジトリの場所を指定することで、パブリック クラウドの Orb ではなくローカル サーバーの Orb にアクセスできます。 For
example, if your server installation is located at `\http://circleci.somehostname.com`, then you can run orb commands
local to that orb repository by passing `--host \http://cirlceci.somehostname.com`.

## 利用可能な Orb の一覧表示
利用可能なパブリック Orb を一覧表示するには、Orb ディレクトリにアクセスするか、以下のコマンドを実行します。

[source,bash]
----
circleci orb list
----

(ローカルの CircleCI Server Orb リポジトリに登録された) 利用可能なプライベート Orb を一覧表示するには、次のコマンドを実行します。
[source,bash]
----
circleci orb list --host <your server install domain> --token <your api token>
----

## パブリック Orb のインポート
パブリック Orb をローカルの CircleCI Server Orb リポジトリにインポートするには、次のコマンドを実行します。

```bash
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```

## パブリック Orb の更新のフェッチ
ローカルの CircleCI Server Orb リポジトリに存在するパブリック Orb を新しいバージョンに更新するには、以下のコマンドを実行します。

[source,bash]
----
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
----

## プロキシ内での Orb の使用

Orb をインポートする際は、CLI が CircleCI サーバー環境および circleci.com と通信できる状態にある必要があります。 プロキシ内でサーバー環境を使用した状態で行う場合は、サーバー環境にリクエストをプロキシするのではなく、プロキシを使って`circleci.com` にリクエストを行うように CLI を設定する必要があります。 以下に、その例を示します。

```bash
export NO_PROXY=server.example.com
export HTTPS_PROXY=http://proxy.example.com:3128
export HTTP_PROXY=http://proxy.example.com:3128
circleci admin import-orb ns[orb[@version]] --host <your server installation domain> --token <your api token>
```

Orb の使用およびオーサリングに関する詳細情報については、クラウド版 CircleCI のhttps://circleci.com/docs/2.0/orb-intro/#quick-start[Orb ドキュメント]を参照してください。
