---

description: "CiecleCI Server 3.x の一般公開が開始されました。 Server 3.x includes the latest CircleCI features, such as orbs, scheduled workflows, matrix jobs, and more."
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x What's New
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

CircleCI Server 3.x の一般公開が開始されました。 最新バージョンのサーバーでは、重いワークロードの下でのスケールが可能になりました。独自の Kubernetes クラスターとプライベートネットワーク内で、CircleCI クラウドの機能を使えるようになります。

CircleCI Server 3.x では、CircleCI Orb、ワークフローのスケジュール実行、マトリックス ジョブをはじめ、CircleCI の最新機能をご利用いただけます。 既存の 2.19 から 3.x への移行をご希望のお客様は、カスタマーサクセスマネージャーまでお問い合わせください。 CircleCI Server 3.x では、毎月のパッチ リリースと四半期ごとの機能リリースを予定しています。

toc::[]

== リリース 3.4.1

=== アップグレードに関する注意事項

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* Run `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`
* KOTS 管理者コンソールからアプリをデプロイします。

=== 修正点

* Kong リソースの上限を引き上げました。 以前の制限は、一部のサーバーのインストール環境の安定性に影響を及ぼしていました。
* 特定の環境で distributor-external が実行できない不具合を修正しました。
* KOTS の設定が更新され、ACM 使用時にプライベートロードバランサーを使用できるようになりました。

=== 既知の問題

* カスタム Docker レジストリから必要に応じて CircleCI Build Agent をプルできるようになりました。 詳細についてはカスタマーサポートにお問い合わせください。
* Amazon Certificate Manager（ACM）を使って TLS 証明書を管理できるようになりました。 For more information see the https://circleci.com/docs/2.0/server-3-install/#frontend-settings[Server v3.x Installation Guide].
* Kubernetes v1.16 - v1.23 に対応しました。
* GCP 上のインストール環境で Workload Identity が使用できるようになりました。 Workload Identity は静的認証情報の代わりにご使用いただけます。 For more information see the https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[Server v3.x Installation Guide]

== リリース 3.4.0

=== アップグレードに関する注意事項

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* Run `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`
* KOTS 管理者コンソールからアプリをデプロイします。

=== 新機能

* Machine Executor 用の Android イメージの提供を開始しました。 For more information, see the https://circleci.com/docs/2.0/android-machine-image/[Using Android Images with the Machine Executor] guide.
* カスタム Docker レジストリから必要に応じて CircleCI Build Agent をプルできるようになりました。 詳細についてはカスタマーサポートにお問い合わせください。
* Amazon Certificate Manager（ACM）を使って TLS 証明書を管理できるようになりました。 For more information see the https://circleci.com/docs/2.0/server-3-install/#frontend-settings[Server v3.x Installation Guide].
* Kubernetes v1.16 - v1.23 に対応しました。
* GCP 上のインストール環境で Workload Identity が使用できるようになりました。 Workload Identity は静的認証情報の代わりにご使用いただけます。 For more information see the https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[Server v3.x Installation Guide]

=== 修正点

* CircleCI Web アプリで、ジョブページとステップ出力アクセスの動作が非常に遅くなる不具合を修正しました。
* ワークフローコンダクターポッドがクラッシュする不具合と、StatsD メトリクスの問題を修正しました。

=== 既知の問題

* KOTS バージョン 1.65.0 - 1.67.0 で Prometheus が破損しています。 この機能に依存している場合は、この問題が解決されるまで、KOTS のバージョンをアップグレードしないでください。
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、 表示されたプライベート IP にアクセスできるようにする必要があります。
* CircleCI 1.0 のビルドはサポートされていません。 1.0 のビルドを実行しようとした場合、問題の原因を示すようなフィードバックはアプリケーション上に表示されません。 If a build is run on your installation and does not show up in the
CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration
and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理画面が壊れる原因となります。

== リリース 3.3.1

=== 修正点

* サーバーがプロキシ内にインストールされている場合も、ランナーを使用できるようになりました。
* 依存関係のキャッシュが断続的に壊れる原因となっていたバグを修正しました。
* 一部のイメージから古い証明書トラストストアを削除しました。 これらが一部のサーバーにアクセスできない原因となっていることが判明しました。
* GitHub Enterprise を使用する際に、自己署名証明書またはプライベート認証機関に対応するようになりました。
* ランナーの更新に影響を与えていたバグを修正しました。
* サーバーがプロキシ内にインストールされている場合も、SSH 再実行ができるようになりました。
* Replaced deprecated GitHub API endoint for `teams`.

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。

== リリース 3.3.0

=== 新機能

* Nomad クライアントの拡張に Nomad Autoscaler が使用できるようになりました。 For more information see the https://circleci.com/docs/2.0/server-3-install-build-services/#nomad-autoscaler[execution environments installation docs].
* https://circleci.com/docs/2.0/webhooks/[Webhooks] are now available.
* インサイトダッシュボードが利用できるようになりました。
* IRSA (AWS) をオブジェクトストレージの認証キーの代わりに使用できるようになりました。
* ビルド通知を送信するメールアドレスを KOTS 管理者コンソールから設定できるようになりました。
* We have replaced https://github.com/traefik/traefik-helm-chart[Traefik] with https://github.com/Kong/charts[Kong] as our reverse proxy. しかし、アップグレードの際の中断を最小限に留めるために、Kong   が使用するサービス名への変更はしておりません。 Therefore, you will see a service named `circleci-server-traefik`, however, this service is actually for Kong.

=== 修正点

* Vault コンテナの Python を v3 にアップグレードしました。
* https://circleci.com/docs/2.0/server-3-operator-vm-service/#google-cloud-platform[Docs improvements] on using the shared VPC architecture in GCP.
* The JVM heap size has been updated so that `output-processor` can use up to 80% of the pod memory limit.

=== 既知の問題

* 変更された Let's Encrypt 証明書での GitHub Enterprise の更新はサポートされていません。
* Let's Encrypt's new root certificate `isrgrootx1` is not trusted.
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* 現在、同一の CircleCI Server アカウントで複数の組織が同じ名前のコンテキストを作ることが可能です。 これは、エラーや予期せぬ動作を引き起こす可能性があるため、お控えください。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。

== リリース 3.2.2

=== アップグレードに関する注意事項

* The https://circleci.com/docs/api/v2/#operation/rerunWorkflow[rerun workflow] endpoint now returns workflow ID rather than the message `accepted`.

=== 修正点

* TLS is terminated outside of `frontend` so the SSL server has been completely removed from the `frontend` container.
* デフォルトの証明書ロジックを KOTS から Helm に移動しました。
* Server v3.x で使用されるビルドエージェントイメージのバージョンを修正しました。 以前のイメージは、ランナーで問題が発生していました。

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、 プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* 現在、同一の CircleCI Server アカウントで複数の組織が同じ名前のコンテキストを作ることが可能です。 これは、エラーや予期せぬ動作を引き起こす可能性があるため、お控えください。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 独自の証明書を用意するか、デフォルトの証明書を使用する必要があります。

== リリース 3.2.1

=== アップグレードに関する注意事項

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

See <<Upgrade notes>> before upgrading from v3.1.x to v3.2.x.

=== 新機能

* GCP 上でご使用で、プライベート VM がサポートされるようになりました。

=== 修正点

* mTLS がデフォルトで無効になりました。
* VM の SSH タイムアウトが 10 分に延長されました。
* プライベート VM がプライベート IP を要求するようになりました。

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、 プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* 現在、同一の CircleCI Server アカウントで複数の組織が同じ名前のコンテキストを作ることが可能です。 これは、エラーや予期せぬ動作を引き起こす可能性があるため、お控えください。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 独自の証明書を用意するか、デフォルトの証明書を使用する必要があります。

== リリース 3.2.0

=== アップグレードに関する注意事項

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

サーバー 3.1.x から 3.2 へのアップグレード時には、PostgreSQL ポッドの変更のためにダウンタイムが発生します。 このアップデートにより 2つの問題が発生する可能性があり、ここではその問題について説明します。

==== PostgreSQL pod stuck in `pending`

If you find that the PostgreSQL pod is stuck in a `pending` state after upgrading, scale down the pods to 0 and then scale up again by following the steps below.

To check if your PostgreSQL pod is stuck in `pending`, use the following command:

```shell
$ kubectl get pod -l app.kubernetes.io/name=postgresql
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Pending   0          3m
```

以下のコマンドにより、データを損失することなくポッドを 0 にスケールダウンし、アプリケーションポッドを終了することができます。

```shell
kubectl scale deployment -l layer=application --replicas 0
```

Once all the application-layer pods have finished terminating, do *one* of the following:

* *either* redeploy the update from the KOTS Admin Console
* *or* run the following two commands to redeploy the pods and return server to a functional state:
+
```shell
kubectl scale deployment -l layer=application --replicas 1
```
+
Then scale `output-processor` up with the following command:
+
```shell
kubectl scale deployment output-processor --replicas 2

```

==== Traefikのポッドが指定通りに実行されない

アップグレード後に Traefik ポッドが 2 つあることに気付いた場合、新しいポッドが指定通りに実行されるように、古いポッドを見つけて削除する必要があります。

Traefik ポッドのステータスを確認するには、以下にコマンドを使用します。

```shell
$ kubectl get pod -l app=traefik
NAME                                      READY   STATUS    RESTARTS   AGE
circleci-server-traefik-9d6b86fd8-f7n2x   1/1     Running   0          24d
circleci-server-traefik-cf7d4d7f6-6mb5g   1/1     Error     0          3m
```

以下のコマンドで古い Traefik ポッドを削除します。

```shell
kubectl delete pod circleci-server-traefik-<older pod hash>
```

これにより、新しい Traefik ポッドが指定通りに実行されるようになります。

=== 新機能

* 完全なプライベートネットワーク環境でのインストールを必要とするお客様は、KOTS管理コンソールの設定画面からパブリックIPがVMに割り当てられないようにすることができます。 なお、非パブリックIPの設定を有効にした場合、実行中のジョブにSSHアクセスが必要なときは、VPCにVPNを設定するなどの回避策が必要となりますのでご注意ください。
* プロキシ経由でアウトバウンドの通信をしているお客様は、KOTS管理コンソールからプロキシの設定ができるようになりました。 Please see our documentation for specifics on https://circleci.com/docs/2.0/server-3-operator-proxy/[proxy support for server].
* マシン実行環境に新たなリソースクラス、サイズ、Executorが追加されました。 具体的には、Arm (medium, large), Linux (medium, large, X large, XX large),Windows (medium, large, XX large)が利用可能となります。
* The https://circleci.com/docs/2.0/insights/[insights API] is now available to all server customers. ビルドデータやその他のデータを活用して、チームのパフォーマンスや、ビルドやテストの健全性をより良く確認することができます。
* 管理画面を刷新し、インストール手順が更新されました。これにより、サーバーの設定や管理がより簡単になりました。
* VMサービスにカスタムLinux AMIが利用できるようになりました。
* SSL ターミネーションを無効にできるようになりました。 サーバーをファイアウォールの内側に置いている場合、これによりファイアウォールでの SSL ターミネーションが利用できます。
* 永続ボリュームのサイズを制御できるようになりました。 大規模なお客様の場合、初期の永続ボリュームのサイズがデフォルトでは小さすぎる場合がありました。 インストール時に永続ボリュームの設定を行うことができるようになり、必要なお客様にはより簡単に移行していただけます。 For further information see the https://circleci.com/docs/2.0/server-3-operator-extending-internal-volumes/[Internal Database Volume Expansion doc].
* We have added an auto-scaling example to the https://github.com/CircleCI-Public/server-terraform/blob/main/nomad-aws/main.tf[nomad client terraform].
* 「安全でない」ビルド成果物の提供可否が選択できるようになりました。 以前はこのオプションは隠されており、安全ではない可能性のあるアーティファクトはプレーンテキストとしてレンダリングされていました。 For more information see the https://circleci.com/docs/2.0/server-3-operator-build-artifacts/[Build Artifacts doc].

=== 修正点

* デフォルトの Windows Executor が記載と異なっていました。 サイズをドキュメントの記載やクラウド版に合わせて大きくしました。

=== 既知の問題

* KOTS admin configuration incorrectly selects the Nomad mTLS as `enabled` during setup. It should be set to mTLS `disabled` until after Nomad clients have been deployed.
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、 プライベートなインストールでは標準的に機能します。 しかし、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* 現在、同一の CircleCI Server アカウントで複数の組織が同じ名前のコンテキストを作ることが可能です。 これは、エラーや予期せぬ動作を引き起こす可能性があるため、お控えください。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration
and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 独自の証明書を用意するか、デフォルトの証明書を使用する必要があります。

== リリース 3.1.0

=== アップグレードに関する注意事項

IMPORTANT: With this release, the `frontend-external` load balancer has been removed. The `traefik` load balancer now handles all incoming traffic. When updating from a previous server 3.x version, you need to update the DNS record that was pointing to the `frontend-external` load balancer and point it to the `circleci-server-traefik` load balancer instead. Remember, you can retrieve the external IP address or DNS name of your Traefik load balancer by typing `kubectl get svc/circleci-server-traefik` in a terminal that has access to the cluster.

DNS レコードを更新して既存の CircleCI Server をアップグレードするには、次の手順を実施してください。

. Retrieve the external IP or DNS name for the Traefik load balancer as described, or by looking the DNS A record for `app.<your domain name>` - this should already point to your Traefik load balancer.
. Locate the DNS A record that points to the domain name of your server installation (not the one pointing to the `app.` subdomain).
. Edit the A record so that it points to the Traefik load balancer, the same as the `app.` subdomain record. DNS サービスによっては、編集結果が反映されるまで数分かかりる場合があります。

Next, from the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.1.0.

=== 新機能

* Telegraf のプラグインをサーバーに追加してカスタマイズすることにより、例えば Datadog のようなサードパーティのモニタリングソリューションを使用できるようになりました。 For more information, see the https://circleci.com/docs/2.0/server-3-operator-metrics-and-monitoring/[Metrics and Monitoring] doc.
* 完全にプライベートな環境にインストールしたいお客様のために、プライベートロードバランサーのみを使用するオプションが導入されました。 For more information, see the https://circleci.com/docs/2.0/server-3-operator-load-balancers/[Load Balancers] guide.
* Server 3.xは、ビルドの成果物、テスト結果、その他の状態をオブジェクトストレージに保管します。 S3互換のあらゆるストレージとGoogle Cloud Storageをサポートしています。 For more information, see the https://circleci.com/docs/2.0/server-3-install/[Installation guide].
* セットアップワークフローを利用した動的な設定(Dynamic Config)が、サーバーで利用できるようになりました。 For more information, see our https://circleci.com/blog/introducing-dynamic-config-via-setup-workflows/[blog post] and the https://circleci.com/docs/2.0/dynamic-config/[Dynamic Configuration docs page].
* Runnerがサーバーで利用可能となりました。 For further information, including installation steps, see the https://circleci.com/docs/2.0/runner-overview/?section=executors-and-images[Runner docs]. Runnerを使うことで、サーバーのインストール時にmacOSの実行環境を使用したり、プライベートデータセンターにサーバーを設置しているお客様がVMサービス機能を利用できるようになります。
* フロントエンドのロードバランサーが廃止され、代わりにIngressリソースとTraefik Ingressコントローラが使用されるようになりました。 これは、DNSの再設定を必要とする変更です。 See the https://circleci.com/docs/2.0/server-3-whats-new/#release-3-1-0[What's New in server docs] for further information and guidance.
* 以下のサービスが外部化できるようになりました。 For setup information, see the https://circleci.com/docs/2.0/server-3-install/[server v3.x installation guide]:
** Postgres
** MongoDB
** Vault
* バックアップ＆リストア機能が利用できるようになりました。 For more information see the https://circleci.com/docs/2.0/server-3-operator-backup-and-restore/[Backup and Restore] guide.
* クラスタのヘルスチェックと使用状況を監視するためのPrometheusがサーバにデフォルトで導入されました。 Prometheus の管理と設定は KOTS 管理者コンソールで行えます。 For further information, see the https://circleci.com/docs/2.0/server-3-operator-metrics-and-monitoring/[Metrics and Monitoring] doc.
* 2XLリソースクラスをサポートするようになりました。 大きいリソースクラスを使用する場合、Nomad クラスタもそれに合わせて十分なサイズにする必要があります。
* The lifecycle of build artifacts and test results can now be configured from the KOTS Admin Console under **Storage Object Expiry**, including the option to disable the expiration and retain artifacts and test results indefinitely.

=== 修正点

* CircleCI のサポートバンドルにシークレットが漏れる原因となっていた一連のバグを修正しました。
** サードパーティ製のバグが原因で、秘密情報を誤って部分的に書き込むケースがありました。
** PostgresSQL により標準出力にシークレットが出力されていました。
** いくつかのCircleCIサービスが秘密情報を記録していました。
* Nomad Terraform モジュールのネットワークセキュリティが強化されました。
* Terraform v0.15.0以降に対応しました。
* 最新バージョンのTerraformでサポートされている機能を使用するようにインストールスクリプトを更新しました。
* マシンの大規模なビルドが誤ったマシンタイプで実行される原因となっていたバグを修正しました。 マシンの大規模なビルドは、正しいクラス (vCPU 4 つ、15GB RAM) で実行されるようになりました。
* Vaultクライアントトークンの有効期限が切れると、コンテクストサービスが失敗するというバグを修正しました。
* Resolved a bug that was causing `legacy-notifier` to report readiness prematurely.
* すべてのサービスにおいて、JVMのヒープサイズパラメータが削除されました。 ヒープサイズは、メモリ制限の半分に設定されます。
* 以前は、再起動が必要となっていた、ネットワーク設定と証明書の変更が、Traefikによって自動的に反映されるようになりました。 これまでは、変更後に再起動が必要でした。
* CPUとメモリーの最低必要条件が変更になりました。 For the new values, see the https://circleci.com/docs/2.0/server-3-install-prerequisites/[Installation Prerequisites] doc.

=== 既知の問題

* 現在、同一の CircleCI Server アカウントで複数の組織が同じ名前のコンテキストを作ることが可能です。 これは、エラーや予期せぬ動作を引き起こす可能性があるため、お控えください。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.

== リリース 3.0.2

- 30日後にアーティファクトが消えてしまうバグを修正しました。 デフォルトの保存期間が30日に設定されていましたが、これを無制限に変更しました。 これに伴って、KOTS管理コンソールのオプションでアーティファクトの保存期間を設定できるようになりました。
- KOTS でフロントエンドの TLS 証明書を更新した後、Traefik Podを手動で再起動しなければならないバグを修正しました。 今後、最初の KOTS デプロイ後に TLS 証明書が更新されると、Traefik ポッドは自動的に再起動されます。
- Resolved a bug in `builds-service` that was causing pods to crash as a result of running out of memory.

== リリース 3.0.1

- `build_agent` `version` value updated, as the previous version was relying on a vulnerable version of PsExec.
- Due to an issue that was causing duplicated checks in GitHub, environment variables for `output-processor` were reconfigured.
- Adjusted deployment configuration for `vm-service` to handle out-of-order database migrations managed by Flyway.

ifndef::pdf[]

== 次に読む

CircleCl Server v3.x の詳しい情報については、以下をご覧ください。

* https://circleci.com/docs/2.0/server-3-overview[Server 3.x の概要]
* https://circleci.com/docs/2.0/server-3-install-prerequisites[Server 3.x Installation]
* https://circleci.com/docs/2.0/server-3-install-migration[Server 3.x への移行]
* https://circleci.com/docs/2.0/server-3-operator-overview[Server 3.x Operations]
+
endif::pdf[]