---
description: "CiecleCI Server 3.x の一般公開が開始されました。 CircleCI Server 3.x では、Orb、ワークフローのスケジュール実行、マトリックス ジョブといった CircleCI の最新機能をご利用いただけます。"
version:
- Server v3.x
- サーバー管理者
---
= CircleCI Server v3.x の What's New
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

CircleCI Server 3.x の一般公開が開始されました。 The newest version of server offers the ability to scale under heavy workloads, all within your own Kubernetes cluster and private network, while still enjoying the full CircleCI cloud experience.

CircleCI Server 3.x では、CircleCI Orb、ワークフローのスケジュール実行、マトリックス ジョブをはじめ、CircleCI の最新機能をご利用いただけます。 For existing customers interested in migrating from 2.19 to 3.x, contact your customer success manager. Server 3.x will receive monthly patch releases and quarterly feature releases.

toc::[]

== リリース 3.4.1

=== アップグレードに関する注意事項

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`を実行します。
* Deploy the app from the KOTS Admin Console

=== 修正点

* Kong resource limits have been increased. The previous limits were affecting the stability of some server installations.
* Fixed a bug that was preventing distributor-external from running in certain environments.
* The KOTS config has been updated to allow private loadbalancers when ACM is in use.

=== 既知の問題

* カスタム Docker レジストリから必要に応じて CircleCI Build Agent をプルできるようになりました。 詳細についてはカスタマーサポートにお問い合わせください。
* Amazon Certificate Manager（ACM）を使って TLS 証明書を管理できるようになりました。 詳細については、https://circleci.com/docs/2.0/server-3-install/#frontend-settings[CircleCI Server v3.x のインストールガイド]を参照してください。
* Kubernetes v1.16 - v1.23 に対応しました。
* GCP 上のインストール環境で Workload Identity が使用できるようになりました。 Workload Identity は静的認証情報の代わりにご使用いただけます。 詳細については、https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[CircleCI Server v3.x のインストールガイド]を参照してください。

== リリース 3.4.0

=== アップグレードに関する注意事項

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`を実行します。
* Deploy the app from the KOTS Admin Console

=== 新機能

* Machine Executor 用の Android イメージの提供を開始しました。 詳細については、https://circleci.com/docs/2.0/android-machine-image/[Machine Executor での Android イメージの使用]ガイドを参照してください。
* カスタム Docker レジストリから必要に応じて CircleCI Build Agent をプルできるようになりました。 詳細についてはカスタマーサポートにお問い合わせください。
* Amazon Certificate Manager（ACM）を使って TLS 証明書を管理できるようになりました。 詳細については、https://circleci.com/docs/2.0/server-3-install/#frontend-settings[CircleCI Server v3.x のインストールガイド]を参照してください。
* Kubernetes v1.16 - v1.23 に対応しました。
* GCP 上のインストール環境で Workload Identity が使用できるようになりました。 Workload Identity は静的認証情報の代わりにご使用いただけます。 詳細については、https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[CircleCI Server v3.x のインストールガイド]を参照してください。

=== 修正点

* CircleCI Web アプリで、ジョブページとステップ出力アクセスの動作が非常に遅くなる不具合を修正しました。
* ワークフローコンダクターポッドがクラッシュする不具合と、StatsD メトリクスの問題を修正しました。

=== 既知の問題

* KOTS バージョン 1.65.0 - 1.67.0 で Prometheus が破損しています。 この機能に依存している場合は、この問題が解決されるまで、KOTS のバージョンをアップグレードしないでください。
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、 表示されたプライベート IP にアクセスできるようにする必要があります。
* CircleCI 1.0 のビルドはサポートされていません。 1.0 のビルドを実行しようとした場合、問題の原因を示すようなフィードバックはアプリケーション上に表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、https://circleci.com/docs/ja/2.0/local-cli/[CircleCI CLI] を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理画面が壊れる原因となります。

== リリース 3.3.1

=== 修正点

* サーバーがプロキシ内にインストールされている場合も、ランナーを使用できるようになりました。
* 依存関係のキャッシュが断続的に壊れる原因となっていたバグを修正しました。
* 一部のイメージから古い証明書トラストストアを削除しました。 これらが一部のサーバーにアクセスできない原因となっていることが判明しました。
* GitHub Enterprise を使用する際に、自己署名証明書またはプライベート認証機関に対応するようになりました。
* ランナーの更新に影響を与えていたバグを修正しました。
* サーバーがプロキシ内にインストールされている場合も、SSH 再実行ができるようになりました。
* 廃止予定のチーム用 GitHub API エンドポイントの置き換え。

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。

== リリース 3.3.0

=== 新機能

* Nomad クライアントの拡張に Nomad Autoscaler が使用できるようになりました。 詳細については、 https://circleci.com/docs/2.0/server-3-install-build-services/#nomad-autoscaler[実行環境のインストール]を参照してください。
* https://circleci.com/docs/2.0/webhooks/[Webhook] が利用できるようになりました。
* インサイトダッシュボードが利用できるようになりました。
* IRSA (AWS) をオブジェクトストレージの認証キーの代わりに使用できるようになりました。
* ビルド通知を送信するメールアドレスを KOTS 管理者コンソールから設定できるようになりました。
* リバースプロキシを https://github.com/traefik/traefik-helm-chart[Traefik] から https://github.com/Kong/charts[Kong] に変更しました。 しかし、アップグレードの際の中断を最小限に留めるために、Kong   が使用するサービス名への変更はしておりません。 そのため、サービス名は、`circleci-server-traefik` と表示されますが、実際には Kong のサービスです。

=== 修正点

* Vault コンテナの Python を v3 にアップグレードしました。
* https://circleci.com/docs/2.0/server-3-operator-vm-service/#google-cloud-platform[GCP での共有 VPC アーキテクチャの使用に関するドキュメント]を改善しました。
* JVM のヒープサイズが更新され、`output-processor` がポッドメモリ制限の 80% まで使用できるようになりました。

=== 既知の問題

* 変更された Let's Encrypt 証明書での GitHub Enterprise の更新はサポートされていません。
* Let's Encrypt の新しいルート証明書 `isrgrootx1` は信頼できません。
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 このため、Machine Executor を使用するジョブの SSH での再試行は、プライベートなインストールでは標準的に機能しますが、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。

== リリース 3.2.2

=== アップグレードに関する注意事項

* https://circleci.com/docs/api/v2/#operation/rerunWorkflow[ワークフローの再実行] のエンドポイントは、`accepted` メッセージではなくワークフロー ID を返すようになりました。

=== 修正点

* TLS は `frontend` の外側で終了するため、`frontend` コンテナから SSL サーバーを完全に削除しました。
* Moved the default certificate logic from KOTS to Helm.
* Server v3.x で使用されるビルドエージェントイメージのバージョンを修正しました。 以前のイメージは、ランナーで問題が発生していました。

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 You need to provide your own certificates or use the default certificates provided.

== リリース 3.2.1

=== アップグレードに関する注意事項

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

See <<Upgrade notes>> before upgrading from v3.1.x to v3.2.x.

=== 新機能
* GCP 上でご使用で、プライベート VM がサポートされるようになりました。

=== 修正点
* mTLS がデフォルトで無効になりました。
* VM の SSH タイムアウトが 10 分に延長されました。
* プライベート VM がプライベート IP を要求するようになりました。

=== 既知の問題

* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 You need to provide your own certificates or use the default certificates provided.

== リリース 3.2.0

=== アップグレードに関する注意事項

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

サーバー 3.1.x から 3.2 へのアップグレード時には、PostgreSQL ポッドの変更のためにダウンタイムが発生します。 このアップデートにより 2つの問題が発生する可能性があり、ここではその問題について説明します。

==== PostgreSQL ポッドが `[Pending(保留)]`のまま
アップグレード後に PostgreSQL ポッドが `[Pending(保留)]` 状態のままである場合、ポッドを以下の手順で 0 にスケールダウンしてから、再度スケールアップしてください。

To check if your PostgreSQL pod is stuck in `pending`, use the following command:

```shell
$ kubectl get pod -l app.kubernetes.io/name=postgresql
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Pending   0          3m
```

以下のコマンドにより、データを損失することなくポッドを 0 にスケールダウンし、アプリケーションポッドを終了することができます。

```shell
kubectl scale deployment -l layer=application --replicas 0
```

Once all the application-layer pods have finished terminating, do *one* of the following:

* *either* redeploy the update from the KOTS Admin Console
* *または*、以下の 2 つのコマンドを実行して、ポッドを再デプロイし、サーバーを機能的な状態に戻します。
+
```shell
kubectl scale deployment -l layer=application --replicas 1
```
+
その後、次のコマンドで `output-processor` をスケールアップします。
+
```shell
kubectl scale deployment output-processor --replicas 2

```

==== Traefikのポッドが指定通りに実行されない
If you find that there are two Traefik pods after upgrading, you need to locate the older pod and remove it to allow the new pod to schedule correctly.

To see the status of your Traefik pod, use the following command:

```shell
$ kubectl get pod -l app=traefik
NAME                                      READY   STATUS    RESTARTS   AGE
circleci-server-traefik-9d6b86fd8-f7n2x   1/1     Running   0          24d
circleci-server-traefik-cf7d4d7f6-6mb5g   1/1     Error     0          3m
```

以下のコマンドで古い Traefik ポッドを削除します。

```shell
kubectl delete pod circleci-server-traefik-<older pod hash>
```

これにより、新しい Traefik ポッドが指定通りに実行されるようになります。

=== 新機能

* 完全なプライベートネットワーク環境でのインストールを必要とするお客様は、KOTS管理コンソールの設定画面からパブリックIPがVMに割り当てられないようにすることができます。 なお、非パブリックIPの設定を有効にした場合、実行中のジョブにSSHアクセスが必要なときは、VPCにVPNを設定するなどの回避策が必要となりますのでご注意ください。
* Customers who manage outbound traffic through a proxy can now configure proxy settings through the KOTS Admin Console. サーバーのプロキシサポートの詳細については、https://circleci.com/docs/ja/2.0/server-3-operator-proxy/[サーバー 3.xのプロキシ設定]を参照してください。
* マシン実行環境に新たなリソースクラス、サイズ、Executorが追加されました。 具体的には、Arm (medium, large), Linux (medium, large, X large, XX large),Windows (medium, large, XX large)が利用可能となります。
* https://circleci.com/docs/ja/2.0/insights/[インサイトAPI]が、すべてのサーバーのお客様にご利用いただけるようになりました。 ビルドデータやその他のデータを活用して、チームのパフォーマンスや、ビルドやテストの健全性をより良く確認することができます。
* 管理画面を刷新し、インストール手順が更新されました。これにより、サーバーの設定や管理がより簡単になりました。
* VMサービスにカスタムLinux AMIが利用できるようになりました。
* SSL ターミネーションを無効にできるようになりました。 サーバーをファイアウォールの内側に置いている場合、これによりファイアウォールでの SSL ターミネーションが利用できます。
* 永続ボリュームのサイズを制御できるようになりました。 大規模なお客様の場合、初期の永続ボリュームのサイズがデフォルトでは小さすぎる場合がありました。 インストール時に永続ボリュームの設定を行うことができるようになり、必要なお客様にはより簡単に移行していただけます。 詳細については、 https://circleci.com/docs/ja/2.0/server-3-operator-extending-internal-volumes/[内部データベースのボリューム拡張]のドキュメントを参照してください。
* https://github.com/CircleCI-Public/server-terraform/blob/main/nomad-aws/main.tf[nomad client terraform]にNomadのオートスケーリングの例を追加しました。
* 「安全でない」ビルド成果物の提供可否が選択できるようになりました。 以前はこのオプションは隠されており、安全ではない可能性のあるアーティファクトはプレーンテキストとしてレンダリングされていました。 詳細については、 https://circleci.com/docs/ja/2.0/server-3-operator-build-artifacts/[CircleCI Server v3.x ビルド アーティファクト]を参照してください。

=== 修正点

* デフォルトの Windows Executor が記載と異なっていました。 サイズをドキュメントの記載やクラウド版に合わせて大きくしました。

=== 既知の問題

* KOTS 管理者の設定では、セットアップ中 Nomad mTLS を誤って`有効`に設定します。 Nomad クライアントがデプロイされるまで、 mTLS が`無効`になっている必要があります。
* Machine Executor を使用するジョブの SSH による再試行では、プライベート IP アドレスが表示されます。 For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations. しかし、パブリックなインストールでは、VPC に VPN を使用するなどして、表示されたプライベート IP にアクセスできるようにする必要があります。
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration
and get details of the possible cause of the issue.
* プロキシ内にインストールしている場合、KOTS 管理コンソールはアップグレードされません。 プロキシ設定が削除され、KOTS 管理者コンソールが壊れる原因になります。
* サーバーがプロキシ内にインストールされている場合、ランナーは使用できません。
* Let's Encrypt の証明書を生成できません。 You need to provide your own certificates or use the default certificates provided.

== リリース 3.1.0

=== アップグレードに関する注意事項

IMPORTANT: 本リリースでは、`frontend-external` ロード バランサーが廃止されました。 今後、受信トラフィックはすべて、`traefik` ロードバランサーにより処理されます。 When updating from a previous server 3.x version, you need to update the DNS record that was pointing to the `frontend-external` load balancer and point it to the `circleci-server-traefik` load balancer instead. Remember, you can retrieve the external IP address or DNS name of your Traefik load balancer by typing `kubectl get svc/circleci-server-traefik` in a terminal that has access to the cluster.

DNS レコードを更新して既存の CircleCI Server をアップグレードするには、次の手順を実施してください。

. Retrieve the external IP or DNS name for the Traefik load balancer as described, or by looking the DNS A record for `app.<your domain name>` - this should already point to your Traefik load balancer.
. Locate the DNS A record that points to the domain name of your server installation (not the one pointing to the `app.` subdomain).
. Edit the A record so that it points to the Traefik load balancer, the same as the `app.` subdomain record. Your changes might need a couple of minutes to take effect, depending on your DNS service.

Next, from the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.1.0.

=== 新機能

* Telegraf のプラグインをサーバーに追加してカスタマイズすることにより、例えば Datadog のようなサードパーティのモニタリングソリューションを使用できるようになりました。 詳細については、https://circleci.com/docs/ja/2.0/server-3-operator-metrics-and-monitoring/[メトリクスと監視に関するページ]を参照してください。
* CircleCI Server 環境を完全にプライベート化したいというお客様のご要望に応え、使用するロード バランサーをプライベートのもののみに限定するオプションが導入されました。 For more information, see the https://circleci.com/docs/2.0/server-3-operator-load-balancers/[Load Balancers] guide.
* CircleCI Server 3.x では、オブジェクト ストレージにビルド アーティファクト、テスト結果、その他の状態をホストします。 すべての S3 互換ストレージと Google Cloud Storage がサポートされます。 設定方法について詳しくは、 https://circleci.com/docs/2.0/server-3-install/[インストールガイド] を参照してください。
* CircleCI Server でセットアップ ワークフローによるダイナミック コンフィグが利用できるようになりました。 詳細については、 https://circleci.com/blog/introducing-dynamic-config-via-setup-workflows/[ブログ記事] および https://circleci.com/docs/2.0/dynamic-config/[ダイナミックコンフィグ] を参照してください。
* CircleCI Server でランナーを利用できるようになりました。 インストール手順を含む詳細については、https://circleci.com/docs/ja/2.0/runner-overview/?section=executors-and-images[ランナーに関するページ]を参照してください。 ランナーを利用すると、CircleCI Server 環境で macOS Executor を使用できるほか、プライベート データ センターに CircleCI Server をインストールしている場合も VM サービス機能を使用できます。
* v3.0 よりフロントエンド ロード バランサーが廃止され、Ingress リソースと Traefik Ingress コントローラーに置き換えられました。 この変更に伴い、既存の DNS の再構成が必要になります。 詳細と手順については、https://circleci.com/docs/ja/2.0/server-3-whats-new/#release-3-1-0[CircleCI Server の新機能に関するページ]を参照してください。
* 次のサービスを外部化できるようになりました。 設定方法について詳しくは、https://circleci.com/docs/ja/2.0/server-3-install/[CircleCI Server v3.x のインストールに関するページ]を参照してください。
** Postgres
** MongoDB
** Vault
* バックアップと復元機能を利用できるようになりました。 詳細については、https://circleci.com/docs/ja/2.0/server-3-operator-backup-and-restore/[バックアップと復元に関するページ]を参照してください。
* クラスタのヘルス状態と使用状況のモニタリングのため、Prometheus がデフォルトで CircleCI Server と共にデプロイされるようになりました。 Prometheus can be managed and configured from the KOTS Admin Console. 詳細については、https://circleci.com/docs/ja/2.0/server-3-operator-metrics-and-monitoring/[メトリクスと監視に関するページ]を参照してください。
* 2 X-large リソース クラスがサポートされるようになりました。 The Nomad cluster needs to be large enough to account for larger resource classes.
* ビルドアーティファクトとテスト結果のライフサイクルを KOTS 管理者コンソールの *Storage Object Expiry* で設定できるようになりました。また、期限切れを無効にしてアーティファクトとテスト結果を無期限に保持するオプションも追加されました。

=== 修正点

* Resolved a collection of bugs that were leaking sensitive information into CircleCI support bundles:
  ** サードパーティのバグなどが原因で、シークレットの一部が誤って改変されていました。
  ** PostgreSQL leaking sensitive information to STDOUT.
  ** 一部の CircleCI サービスでシークレットが記録されていました。
* Tightened network security in the Nomad Terraform module.
* Terraform v0.15.0 以上がサポートされるようになりました。
* インストール スクリプトが更新され、最新バージョンの Terraform でサポートされている機能を使用できるようになりました。
* Resolved a bug that was causing machine large builds to be run on the wrong machine type. Machine large builds now correctly use four vCPUs and 16GB of RAM.
* Vault のクライアント トークンの期限切れ時に contexts-service が起動しなくなるバグを修正しました。
* 準備完了前に `legacy-notifier` から準備完了と報告されるバグを修正しました。
* すべてのサービスで、JVM ヒープ サイズに関するパラメーターが削除されました。 ヒープ サイズはメモリ上限の半分に設定されます。
* ネットワーク設定と証明書に対する変更が、Traefik で自動的に検出されるようになりました。 これまでは、変更後に再起動が必要でした。
* CPU とメモリの最小要件が変更されました。 変更後の要件については、https://circleci.com/docs/ja/2.0/server-3-install-prerequisites/[インストールの前提条件に関するページ]を参照してください。

=== 既知の問題

* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 のビルドはサポートされていません。 CircleCI 1.0 のビルドを実行した場合、ビルドが実行されない上、アプリ画面上でエラーなどが表示されません。 お使いの環境でビルドを実行しても、アプリ画面にビルドが表示されない場合は、 https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] 
を使用してプロジェクトの構成を検証し、問題の原因を調査することをおすすめします。

== リリース 3.0.2

- アーティファクトが作成から 30 日後に表示されなくなるバグを修正しました。 アーティファクトの保持期間のデフォルト設定は無期限に変更されました。 また、KOTS 管理者コンソールでこの保持期間を設定できるようになりました。
- Traefik ポッドを手動で再起動しない限り、TLS 証明書の更新が Traefik で認識されないバグを修正しました。 The Traefik pod now restarts automatically after any TLS certificate updates go into effect after the initial post-KOTS deployment.
- ポッドがメモリ不足になりクラッシュする `builds-service` のバグを修正しました。

== リリース 3.0.1

- 以前のバージョンは脆弱性のある PsExec を使用していたため、`build_agent` `version` のバージョンが更新されました。
- GitHub でのチェックが重複する問題を受け、`output-processor` の環境変数が変更されました。
- Flyway で管理される順不同のデータベース移行に対応するため、`vm-service` のデプロイ構成が変更されました。

ifndef::pdf[]
== 次に読む
CircleCl Server v3.x の詳しい情報については、以下をご覧ください。

* https://circleci.com/docs/2.0/server-3-overview[CircleCI Server 3.x の概要]
* https://circleci.com/docs/2.0/server-3-install-prerequisites[CircleCI Server 3.x のインストール]
* https://circleci.com/docs/2.0/server-3-install-migration[CircleCI Server 3.x への移行]
* https://circleci.com/docs/2.0/server-3-operator-overview[CircleCI Server 3.x の運用]
endif::pdf[]
