---
description: "CircleCI Server の VM サービスでは、Machine Executor (Linux および Windows イメージ) とリモート Docker ジョブの実行方法できます。"
version:
- Server v3.x
- サーバー管理者
---
= CircleCI Server v3.x VM サービス
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

CircleCI Server の VM サービスでは、 https://circleci.com/docs/configuration-reference/#machine[`machine`] Executor (Linux イメージおよび Windows イメージ) と https://circleci.com/docs/building-docker-images[リモート Docker] ジョブの実行方法を制御できます。

このセクションでは、VM サービスで利用可能な設定オプションについて説明します。 この設定オプションには、KOTS 管理者コンソールのダッシュボードで *Config* タブを選択することでアクセスできます。

toc::[]

NOTE: CircleCI Server のコアサービスとビルドサービスの設定と検証が完了するまで、これらのオプションはデフォルトのままにしておくことをお勧めします。 VM サービスの設定手順については、 https://circleci.com/docs/server-3-install-build-services/#eks[AWS] と https://circleci.com/docs/server-3-install-build-services/#gke[GCP]用の Server 3.x インストールガイドをご覧ください。

== VM サービスの設定
VM サービスロードバランサーのホストネームと IP アドレスを指定する必要があります。

. CircleCI Server が起動し稼働したら、下記のコマンドを実行します。
+
----
kubectl get svc/vm-service
----
. *External IP* の下に記載されているアドレスを *VM Service Load Balancer Hostname* フィールドに入力します。

オプションで VM サービスで使用するポートを変更することができます。 デフォルトは `3000`で、CircleCI サポートチームのエンジニアに変更を推奨された場合のみ変更してください。

== VM プロバイダー
下記は、AWS または GCP の VM プロバイダー用の設定オプションです。

=== AWS EC2
AWS EC2 を使う場合は、以下のフィールドに入力して VM サービスを設定する必要があります。

この時点では、VMでプライベートIPアドレスを使用する必要がある場合は、*Assign Public IPs* チェックボックスをオフにしてもかまいません。

* *[AWS Region (AWS リージョン)]* (必須): アプリケーションがホストされるリージョンを指定します。
* [*AWS Linux AMI ID*] (オプション): Linux `machine` Executor にカスタム AMI を使用する場合は、ここで AMI ID を指定します。 Linux イメージを作成するには、 https://github.com/CircleCI-Public/circleci-server-linux-image-builder[CircleCI Server Linux イメージビルダー]を使います。 このフィールドを空欄にした場合は、 <<default-aws-ami-list, デフォルトの AMI>>が使用されます。
* *[AWS Windows AMI ID]* (オプション): Windows Executor が必要な場合、その AMI ID をここに指定できます。 Windows イメージを作成するには、 https://github.com/CircleCI-Public/circleci-server-windows-image-builder[CircleCI Server Windows イメージビルダー]を使います。 Windows Executor が不要な場合は、このフィールドを空欄にします。
* *[Subnet ID (サブネット ID)]* (必須): VM のデプロイ先になるサブネット (パブリックまたはプライベート) を選択します。 なお、すべてのサブネットが同じアベイラビリティーゾーンにある必要があります。
* *[Security Group ID (セキュリティ グループ ID)]* (必須): VM にアタッチするセキュリティ グループを指定します。
+
推奨されるセキュリティ グループ構成については、 https://circleci.com/docs/ja/server-3-install-hardening-your-cluster[クラスタのハードニング] を参照してください。
* *[Number of <VM-type> VMs to keep prescaled (事前スケーリングする <VM タイプ> の VM 数)]*: デフォルトでは、このフィールドは 0 に設定されています。 この値の場合、該当するリソースタイプのインスタンスがオンデマンドで作成、プロビジョニングされます。 リソースタイプごとにインスタンスを最大 5 つまで事前割り当てできます。 インスタンスを事前に割り当てると、起動時間が短くなり、マシンと `remote_docker` のビルド速度が速くなります。
+
NOTE: ただし、事前割り当てされたインスタンスは常に実行されるため、コストが増加する可能性があります。 また、この設定値を減らす場合、変更が反映されるまで最大で 24 時間かかります。 これらのインスタンスは、必要に応じて手動で終了できます。
+
WARNING: https://circleci.com/docs/docker-layer-caching/[Docker レイヤーキャッシュ (DLC)] を使用する場合、VM サービスインスタンスをオンデマンドでスピンアップする必要があります。 これを実現する方法は 2 つあります。 *1 つは*、事前割り当てインスタンスを使用中にすること、*もう 1 つは*、リモート Docker と `machine` 用の事前割り当てインスタンスのフィールドの両方を `0` に設定することです。
+
NOTE: 事前割り当てインスタンスを使用する場合、インスタンスが動作不可能状態にならないように、それらのインスタンスを 1 日に 1 回切り替えるように cron ジョブがスケジュールされていることに注意してください。

==== 認証
以下のいずれかを実行してください。 IAM キーを選択し、以下を指定します。

* *[Access Key ID (アクセスキー ID)]* (必須): EC2 へのアクセス用の https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[AWS アクセス キー ID] を指定します。
+
NOTE: VM サービスで使用するアクセスキーとシークレットキーは、前述のオブジェクトストレージ用のポリシーとは異なることに注意してください。
* *[Secret Key (AWS IAM シークレットキー)]* (必須): EC2 へのアクセス用の https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[シークレットキー] を指定します。

または、IAM ロールを選択し、以下を指定します。

* *Role ARN* (必須) : EC2 アクセス用の https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html[サービスアカウントの Role ARN] (Amazon Resource Name) 

==== 暗号化された EBS ボリューム
AWS EC2 のダッシュボードで、Account Attributes を常に https://aws.amazon.com/jp/premiumsupport/knowledge-center/ebs-automatic-encryption/[新しい EBS ボリュームを暗号化] するように変更します。 このオプションを有効にすると、VM サービスにより作成されたすべての新しい EBS ボリュームが暗号化されるようになります。 このオプションは、リージョンごとの設定であり、CircleCI Server を実行しているリージョンで有効化する必要があります。

==== デフォルトの AWS AMI リスト

デフォルトの Server v3.x 用 AMI は Ubuntu 22.04 に基づいています。

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| リージョン
| AMI

| `us-east-1` 
| `ami-03dc54f7559144972`

| `ca-central-1`
| `ami-0575d605472840942`

| `ap-south-1` 
| `ami-047ef6196620f56ca`

| `ap-southeast-2`
| `ami-0521f8d70ef9dbd24`

| `ap-southeast-1`
| `ami-0ef0354f4eb3b7428`

| `eu-central-1`
| `ami-0a8286fff7b5ed33a`

| `eu-west-1`
| `ami-093618a1d0185f9e8`

| `eu-west-2`
| `ami-08f00d41b17d3ea0a`

| `sa-east-1`
| `ami-064b0bfe97e6ec04c`

| `us-east-2` 
| `ami-068cb131f91632f12`

| `us-west-1`
| `ami-0a4b7cf088a798be3`

| `us-west-2`
| `ami-018e05f98628cf5e5`

| `ap-northeast-1`
| `ami-06f32ec6aeecbeaa6`

| `ap-northeast-2`
| `ami-084c1abb1e8dabffd`

| `eu-west-3`
| `ami-09b3e24bccae3252f`

| `us-gov-east-1`
| `ami-0de525cac9ac9bea8`

| `us-gov-west-1` 
| `ami-02abf947586cae56b`
|===


=== Google Cloud Platform
Google Cloud Platform (GCP) を使う場合は、以下のフィールドの入力をして VM サービスを設定する必要があります。

WARNING: VM サービス専用の一意のサービスアカウントを作成することをお勧めします。 コンピューティング インスタンス管理者 (ベータ版) ロールは、VM サービスを運用するための広範な権限を持っています。 アクセス権限をより詳細に設定したい場合は、 https://cloud.google.com/compute/docs/access/iam#compute.instanceAdmin[コンピューティング インスタンス管理者 (ベータ版) ロールのドキュメント]を参照してください。

この時点では、VMでプライベートIPアドレスを使用する必要がある場合は、*Assign Public IPs* チェックボックスをオフにしてもかまいません。

* *[GCP project ID (GCP プロジェクト ID)]* (必須): クラスタが存在する GCP プロジェクトの名前を指定します。
* *[VM 用の GCP Zone (GCP ゾーン)]* (必須): `us-east1-b`などに仮想マシンインスタンスを作成する GCP ゾーンを指定します。
* *[GCP Windows イメージ]* (オプション): Windows Executor が必要な場合、その AMI ID をここに指定できます。 Windows イメージを作成するには、 https://github.com/CircleCI-Public/circleci-server-windows-image-builder[CircleCI Server Windows イメージビルダー]を使います。 Windows Executor が不要な場合は、このフィールドを空欄にします。
* *[GCP VPC Network (GCP VPC ネットワーク)]* (必須): VPC ネットワークの名前を指定します。 共有 VPC で CircleCI Server をデプロイしている場合は、名前ではなく以下のようにホストネットワークのフルネットワークエンドポイントを使用します。
+
```
https://www.googleapis.com/compute/v1/projects/<host-project>/global/networks/<network-name>
```
* *[GCP VPC Subnet (GCP VPC サブネット)]* (オプション): VPC サブネットの名前を指定します。 自動サブネット化を使用する場合は、このフィールドは空欄にします。 共有 VPC で CircleCI Server をデプロイしている場合は、名前ではなく以下のようにサブネットワークのフルネットワークエンドポイントを使用します。
+
```
https://www.googleapis.com/compute/v1/projects/<service-project>/regions/<your-region>/subnetworks/<subnetwork-name>

```

* *[GCP IAM Access Type (GCP IAM アクセスタイプ)]* (必須): 以下のいずれかを実行してください。 `GCP Service Account JSON file` を選択し、以下を指定します。

** *[GCP Service Account JSON file (GCP サービス アカウントの JSON ファイル)]* (必須): GCP IAM サービスアカウント認証情報を使用する場合は、 https://cloud.google.com/iam/docs/service-accounts[サービス アカウントの JSON ファイル] の内容をコピー & ペーストします。
+
または、`IAM Workload Identity`を選択して、以下を指定します。

** *GCP IAM Workload Identity* (必須): https://circleci.com/docs/server-3-install-build-services/#gcp-3[こちら]の 2 & 3 で作成した VM サービスアカウントのメールアドレス (`service-account-name`@`project-id`.iam.gserviceaccount.com ) をコピー & ペーストします。

* *[Number of <VM-type> VMs to keep prescaled (事前スケーリングする <VM タイプ> の VM 数)]*: デフォルトでは、このフィールドは 0 に設定されています。 この値の場合、該当するリソースタイプのインスタンスがオンデマンドで作成、プロビジョニングされます。 リソース タイプごとにインスタンスを最大 5 つまで事前割り当てできます。 インスタンスを事前に割り当てると、起動時間が短くなり、マシンと `remote_docker` のビルド速度が速くなります。
+
NOTE: ただし、事前割り当てされたインスタンスは常に実行されるため、コストが増加する可能性があります。 また、この設定値を減らす場合、変更が反映されるまで最大で 24 時間かかります。 これらのインスタンスは、必要に応じて手動で終了できます。
+
WARNING: https://circleci.com/docs/docker-layer-caching/[Docker レイヤーキャッシュ (DLC)] を使用する場合、VM サービスインスタンスをオンデマンドでスピンアップする必要があります。 これを実現する方法は 2 つあります。 *1 つは*、事前割り当てインスタンスを使用中にする、*もう 1 つは*、リモート Docker と `machine` 用の事前割り当てインスタンスのフィールドの両方を `0` に設定することです。
+
NOTE: 事前割り当てインスタンスを使用する場合、インスタンスが動作不可能状態にならないように、それらのインスタンスを 1 日に 1 回切り替えるように cron ジョブがスケジュールされていることに注意してください。
