---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x クラスタのハードニング
:page-layout: classic-docs
:page-liquid:
:page-description: ここでは、Kubernetes クラスタのハードニングに関する補足情報を紹介します。
:icons: font
:toc: macro
:toc-title:

このセクションでは、Kubernetes クラスタのハードニングに関する補足情報を紹介します。

toc::[]

## ネットワークトポロジ
CircleCI Server システムでは主に、Kubernetes ノード、Nomad クライアント、外部 VM という 3 種類のコンピューティング インスタンスを実行します。

これらのインスタンスは、CIDR ブロックの異なるサブネットに分けてデプロイすることを強くお勧めします。 This will make it easier for you to control traffic between the different components of the system and isolate them from each other.

通例どおり、リソースはできる限り非公開にすることが原則です。 If your users will access your CircleCI server installation via VPN, there is no need to assign any public IP addresses at all, as long as you have a working NAT gateway setup. そうでない場合は、 CircleCI Server Traefik ロードバランサー用にパブリックサブネットを少なくとも 1 つ用意する必要があります。

NOTE: Server v3.3.0 以降は、リバースプロキシが https://github.com/traefik/traefik-helm-chart[Traefik] から https://github.com/Kong/charts[Kong] に変更されています。 しかし、アップグレードの際の中断を最小限に留めるために、Kong   が使用するサービス名への変更はしておりません。 Although you will see a service named `circleci-server-traefik`, this service is actually for Kong.

However, in this case, it is also recommended to place Nomad clients and VMs in a public subnet to enable your users to SSH into jobs and scope access via networking rules.

現時点では、GCP はカスタムのサブネット化には対応していません。 カスタムのサブネット化は、今後の更新/リリースで使用可能になる予定です。

## ネットワークトラフィック
This section explains the minimum requirements for a server installation to work. ワークロードによっては、Nomad クライアントと VM の送信にルールを追加する必要があります。 As nomenclature between cloud providers differs, you will probably need to implement these rules using firewall rules and/or security groups.

表中の "外部" は、特に断りがない限り、すべての外部 IPv4 アドレスを意味します。 Depending on your particular setup, you might be able to be more specific (for example, if you are using a proxy for all external traffic).

なお、ここでは、Nomad、VM サービス、出力プロセッサそれぞれのロード バランサーは、すべて内部ロード バランサーにすることを前提としています。 （内部ロード バランサーがデフォルトです。）

また、下記のルールは、特別な記載のない限り、TCP 接続に対してステートフルで設定するものとします。 If you are working with stateless rules, you need to create matching ingress or egress rules for the ones listed here.

## Kubernetes ロード バランサー
お使いの環境によっては、ロード バランサーが透過的である (ネットワーク トポロジの個別のレイヤーとしては扱われない) ことがあります。 この場合には、ロード バランサーの背後にあるネットワーク トラフィックの送信先またはソースに対して、本セクションのルールを直接適用してください。 CircleCI Server システムで使用している負荷分散の種類に応じたネットワーク セキュリティ ルールの適切な適用方法については、ご利用のクラウド プロバイダーのドキュメントをご覧ください。

### 受信
ロード バランサーのトラフィック ルールが自動的に作成されていない場合は、次の各ポートを設定してください。

[.table.table-striped]
[cols=4*, options="header", stripes=even]
|===
| 名前
| ポート
| ソース
| 用途

| *-server-traefik
| 80
| 外部
| ユーザー インターフェイスとフロントエンド API

| *-server-traefik
| 443
| 外部
| ユーザー インターフェイスとフロントエンド API

| vm-service
| 3000
| Nomad クライアント
| Nomad クライアントとの通信

| nomad
| 4647
| Nomad クライアント
| Nomad クライアントとの通信

| output-processor
| 8585
| Nomad クライアント
| Nomad クライアントとの通信
|===

### 送信
The only type of egress needed is TCP traffic to the Kubernetes nodes on the Kubernetes load balancer ports (30000-32767). ただし、ロード バランサーが透過的であればこの送信は必要ありません。

## コンピューティング インスタンスの共通ルール
以下のルールは、ロード バランサーを除くすべてのコンピューティング インスタンスに適用されます。

### 受信
インスタンスに SSH でアクセスする必要がある場合は、該当するインスタンスへの TCP 接続用にポート 22 を開放してください。
ルールの範囲は、許可されたソースIPにできるだけ近いものにすること、または、必要な場合にのみそのようなルールを追加することをお勧めします。

### 送信
ほとんどの環境では、インスタンスすべてに対してインターネット リソースへのアクセスを許可することになります。 This requires you to allow egress for UDP and TCP on port 53 to the DNS server within your VPC, as well as TCP ports 80 and 443 for HTTP and HTTPS traffic, respectively.
Instances building jobs (that is, the Nomad clients and external VMs) also will likely need to pull code from your VCS using SSH (TCP port 22). SSH is also used to communicate with external VMs, so it should be allowed for all instances with the destination of the VM subnet and your VCS, at the very least.

## Kubernetes ノード

### ノード間のトラフィック
By default, the traffic within your Kuberntes cluster is regulated by networking policies. For most purposes, this should be sufficient to regulate the traffic between pods and there is no additional requirement to reduce traffic between Kubernetes nodes any further (it is fine to allow all traffic between Kubernetes nodes).

クラスタ内でネットワーク ポリシーを使用するには、クラウド プロバイダーや環境設定にもよりますが、追加の手順を実行する必要があります。 以下の資料を参考にしてください。

* https://kubernetes.io/docs/concepts/services-networking/network-policies/[Kuberenetes のネットワーク ポリシーの概要]
* https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy[Google Cloud でのクラスタ ネットワーク ポリシーの作成]
* https://docs.aws.amazon.com/eks/latest/userguide/calico.html[Amazon EKS への Calico のインストール方法]

### 受信
If you are using a managed service, you can check the rules created for the traffic coming from the load balancers and the allowed port range. The standard port range for Kubernetes load balancers (30000-32767) should be all that is needed here for ingress. If you are using transparent load balancers, you need to apply the ingress rules listed for load balancers above.

### 送信

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| 送信先
| 用途

| 2376
| VM
| VM との通信

| 4647
| Nomad クライアント
| Nomad クライアントとの通信

| すべてのトラフィック
| その他のノード
| クラスタ内トラフィックの許可
|===

## Nomad クライアント
Nomad クライアント同士は、通信する必要はありません。 Nomad クライアント インスタンス 間のトラフィックを完全にブロックできます。

### 受信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| ソース
| 用途

| 4647
| K8s ノード
| Nomad サーバーとの通信

| 64535 ～ 65535
| 外部
| SSH でのジョブ再実行機能
|===

### 送信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| 送信先
| 用途

| 2376
| VM
| VM との通信

| 3000
| VM サービスのロード バランサー
| 内部通信

| 4647
| Nomad のロード バランサー
| 内部通信

| 8585
| 出力プロセッサのロード バランサー
| 内部通信
|===

## 外部 VM
Nomad クライアントと同じく、外部 VM 同士も通信する必要はありません。

### 受信
[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| ポート
| ソース
| 用途

| 22
| Kubernetes ノード
| 内部通信

| 22
| Nomad クライアント
| 内部通信

| 2376
| Kubernetes ノード
| 内部通信

| 2376
| Nomad クライアント
| 内部通信

| 54782
| 外部
| SSH でのジョブ再実行機能
|===

### 送信
設定が必要な送信ルールは、VCS へのインターネット アクセスと SSH 接続のみです。

ifndef::pdf[]
## 次に読む
* https://circleci.com/docs/ja/2.0/server-3-install-migration[CircleCI Server 3.x への移行]
* https://circleci.com/docs/ja/2.0/server-3-operator-overview[CircleCI Server 3.x の運用]
endif::[]
