---
description:  CircleCI Server v3.x のアップグレードに必要な手順
version:
- Server v3.x
- サーバー管理者
---
= CircleCI Server v3.x のアップグレードガイド
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Upgrading your server v3.x installation requires that you have access to the Kubernetes cluster in which server is installed, and have an instance of KOTS Admin Console running. 

アップグレードをする前に、https://circleci.com/docs/2.0/server-3-operator-backup-and-restore[バックアップと復元]の設定が完了していることを確認してください。 

デプロイが成功すると UI が更新されます。 リリースノートに記載されていない限り、アップデートはローリングアップデートでありダウンタイムはありません。 

NOTE: リリースをスキップしないことをお勧めします。

== CircleCI Server v３.x のアップグレード

. Enter the KOTS Admin Console. アクセスするには、下記をご自身の CircleCI Server 名前空間に置き換えて実行します。 
+
----
kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>
----

. Log in to the Admin Console with the password you created during the installation process.

. *Snapshots* タブを選択し、お使いの環境のスナップショットを作成します。 詳細については、https://circleci.com/docs/2.0/server-3-operator-backup-and-restore/#creating-backups[バックアップと復元] ガイドを参照してください。

.  *Version History* を選択します。 先に進む前に、*Check for Updates* をクリックします。 

. 最新バージョンが表示されたら、下記のチェックリストを実行し、アップグレードしたいバージョンの *Deploy* を選択します。
+
* https://circleci.com/server/changelog/[change log] をチェックし、新しいバージョンをデプロイする前に実行しなければならないアクションがないことを確認します。 
* デプロイするバージョンの設定を確認し、他にデプロイしたい新しいフィールドや機能がないことを確認します (Deploy ボタンの横にあるギアをクリックすると、そのバージョンに固有の設定が表示されます）。 

. テスト環境でhttps://github.com/circleci/realitycheck[`reality check`] をデプロイして実行し、インストールした CircleCI Server が完全に動作していることを確認します。







