---
version:
- Server v3.x
- サーバー管理
---
= CircleCI Server v3.x の Orbs
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このセクションでは、CircleCI Orbs の概要とその管理方法を説明します。 CircleCI Server システムには、固有のローカル Orb レジストリが含まれています。 このレジストリは、CircleCI Server からのみアクセスできます。 設定ファイルで参照している Orb はすべて、この CircleCI Server Orb レジストリに含まれる Orb を参照します。 これらの Orb のメンテナンスは、CircleCI Server ユーザーが行う必要があります。具体的には、パブリック レジストリからの Orb のコピー、以前コピーした Orb の更新、会社のプライベート Orb の登録 (存在する場合) を行います。

toc::[]

## Orb の管理
Orb には、https://circleci.com/docs/ja/2.0/local-cli/[CircleCI CLI] からアクセスします。 Orb を使用するには、管理者である必要があります。 また、https://circleci.com/docs/ja/2.0/managing-api-tokens/が必要です。 `--host` オプションを使用してローカル リポジトリの場所を指定することで、パブリック クラウドの Orb ではなくローカル サーバーの Orb にアクセスできます。 たとえば、CircleCI Server の場所が `http://circleci.somehostname.com` である場合、CLI に `--host http://cirlceci.somehostname.com` を渡すと、その Orb リポジトリに対してローカルで Orb コマンドを実行できます。

## 利用可能な Orb の一覧表示
利用可能なパブリック Orb を一覧表示するには、Orb ディレクトリにアクセスするか、次のコマンドを実行します。

[source,bash]
----
circleci orb list
----

(ローカルの CircleCI Server Orb リポジトリに登録された) 利用可能なプライベート Orb を一覧表示するには、次のコマンドを実行します。
[source,bash]
----
circleci orb list --host <your server install domain> --token <your api token>
----

## パブリック Orb のインポート
パブリック Orb をローカルの CircleCI Server Orb リポジトリにインポートするには、次のコマンドを実行します。

[source,bash]
----
circleci admin import-orb ns[/orb[@version]] --host <your server installation domain> --token <your api token>
----

## パブリック Orb の更新のフェッチ
ローカルの CircleCI Server Orb リポジトリに存在するパブリック Orb を新しいバージョンに更新するには、次のコマンドを実行します。

[source,bash]
----
circleci admin import-orb ns[/orb[@version]] --host <your server installation domain> --token <your api token>
----

Orb に関する詳細情報については、クラウド版 CircleCI の https://circleci.com/docs/ja/2.0/orb-intro/#quick-start[Orb ドキュメント]を参照してください。
