---
contentTags:
  platform:
  - Server v3.x
  - サーバー管理者
---
= CircleCI Server v3.x でのトラブルシュートとサポート
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CircleCI server v3.x のインストールで問題が発生した場合の解決方法について説明します。
:icons: font
:toc: macro
:toc-title:

ここでは、CircleCI Server v3.x で問題が発生した場合の最初のトラブルシューティング手順について説明します。 以下の説明で問題を解決できなかった場合は、サポート バンドルを生成するか、CircleCI アカウント チームにお問い合わせください。

toc::[]

## KOTS 管理者コンソールの起動

KOTS 管理者コンソールを再起動するには、以下のコマンドを実行します。

[source,bash]
----
kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>
----

ブラウザーを開いて、http://localhost:8800 にアクセスし、管理者コンソールを表示します。

## サポート バンドルの生成
サポート バンドルは、発生している問題を CircleCI エンジニアが診断、修正するためのものです。 通常、サポート チケットを作成する場合、サポート バンドルを提出するように求められます。

CircleCI へのサポート依頼時に提出するサポート バンドルをダウンロードするには、管理者コンソールのメニュー バーの *[Troubleshoot]* タブを選択して、*[Analyze CircleCI Server]* をクリックします。

## Pod の管理

### Pod の準備状況とステータスの確認
NOTE: `READY` 列と `STATUS` 列を確認してください。 `STATUS` が `Running` でも、Pod ではユーザーのリクエストを処理する準備はできていません。 一部の Pod は、準備ができるまで多少の時間を要する場合があります。

[source,bash]
----
kubectl get pods -n <namespace>
NAME READY STATUS RESTARTS AGE
api-service-5c8f557548-zjbsj 1/1 Running 0 6d20h
audit-log-service-77c478f9d5-5dfzv 1/1 Running 0 6d20h
builds-service-v1-5f8568c7f5-62h8n 1/1 Running 0 6d20h
circleci-mongodb-0 1/1 Running 0 6d20h
circleci-nomad-0 1/1 Running 6 6d20h
----

ステータスが `Running` 以外の Pod だけを表示するには、`--field-selector` オプションを使用します。

[source,bash]
----
kubectl get pods --field-selector status.phase!=Running -n <namespace>
NAME READY STATUS RESTARTS AGE
nomad-server 0/1 Error 0 5d22h
----

### Pod の設定とステータスの確認
Pod の詳細な設定とステータスを確認するには、以下のコマンドを実行します。

[source,bash]
----
kubectl describe pods <pod-name> -n <namespace>
----

### Pod のログの取得
Pod のログを表示するには、以下のコマンドを実行します。

[source,bash]
----
kubectl logs <pod-name> -n <namespace>
----

### Pod の再起動
特定の Pod を再起動する最も簡単な方法は、その Pod を削除することです。 削除した Pod は、Kubernetes によって自動的に再作成されます。

[source,bash]
----
kubectl delete pod <pod-name> -n <name-space> --now
----

## ビルドのキューイングのデバッグ
ビルドのキューイングのデバッグに関する問題を解決するには、CircleCI Server 2.x の https://circleci.com/docs/ja/troubleshooting/?section=server-administration#debug-queuing-builds[トラブルシューティング] ガイドを参照してください。
