---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Application Lifecycle
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI server v3.x semantic versioning and release schedules.
:icons: font
:toc: macro
:toc-title:

CircleCI では、CircleCI ソフトウェアについてマイナー バージョン 4 つまでをサポート対象としています。 This means a minor version will receive patches for up to 12 months. 各リリースの識別と、お使いの環境にインストール済みの CircleCI Server への影響の特定が容易になるよう、CircleCI ではセマンティック バージョニングを使用しています。

## セマンティック バージョニング
バージョンナンバーは、メジャー.マイナー.パッチ とし、バージョンを上げるには、

. APIの変更に互換性がない場合はメジャーバージョンを、
. MINOR version when you add functionality in a backwards-compatible manner, and
. 後方互換性を伴うバグ修正をした場合はパッチバージョンを上げます。

プレリリースやビルドナンバーなどのラベルに関しては、メジャー.マイナー.パッチ の形式を拡張する形で利用することができます。

## リリース スケジュール
CircleCI では、毎月、バグとセキュリティ上の懸念事項に対処するパッチ修正をリリースしています。 新機能のリリースは四半期ごとです。 All releases will be posted to the change log. To stay up to date with the most recent releases, please subscribe to the https://circleci.com/server/changelog/[change log].
