---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Troubleshooting and Support
:page-layout: classic-docs
:page-liquid:
:page-description: Use this document to find troubleshooting steps if you are having problems with your CircleCI server v3.x installation.
:icons: font
:toc: macro
:toc-title:

This document describes an initial set of troubleshooting steps to take if you are experiencing problems with your CircleCI Server v3.x installation. If your issue is not addressed below, you can generate a support bundle or contact your CircleCI account team.

toc::[]

## 管理者コンソールの起動

管理者コンソールを再起動するには、以下のコマンドを実行します。

[source,bash]
----
kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>
----

ブラウザーを開いて、http://localhost:8800 にアクセスし、管理者コンソールを表示します。

## サポート バンドルの生成
サポート バンドルは、発生している問題を CircleCI エンジニアが診断、修正するためのものです。 They are typically requested when you open a ticket.

To download a support bundle for CircleCI support, select the *Troubleshoot* tab from the Admin Console menu bar, and then click *Analyze CircleCI Server*.

## Pod の管理

### Pod の準備状況とステータスの確認
注: `READY` 列と `STATUS` 列を確認してください。 Even if the `STATUS` is `Running`, pods are not ready to serve user requests. 一部の Pod は、準備ができるまで多少の時間を要する場合があります。

[source,bash]
----
kubectl get pods -n <namespace>
NAME READY STATUS RESTARTS AGE
api-service-5c8f557548-zjbsj 1/1 Running 0 6d20h
audit-log-service-77c478f9d5-5dfzv 1/1 Running 0 6d20h
builds-service-v1-5f8568c7f5-62h8n 1/1 Running 0 6d20h
circleci-mongodb-0 1/1 Running 0 6d20h
circleci-nomad-0 1/1 Running 6 6d20h
----

To show only pods with a status besides `Running`, you can use the `--field-selector` option.

[source,bash]
----
kubectl get pods --field-selector status.phase!=Running -n <namespace>
NAME READY STATUS RESTARTS AGE
nomad-server 0/1 Error 0 5d22h
----

### Pod の設定とステータスの確認
To show detailed settings and status of pods:

[source,bash]
----
kubectl describe pods <pod-name> -n <namespace>
----

### Pod のログの取得
Pod のログを表示するには、以下のコマンドを実行します。

[source,bash]
----
kubectl logs <pod-name> -n <namespace>
----

### Pod の再起動
特定の Pod を再起動する最も簡単な方法は、その Pod を削除することです。 削除した Pod は、Kubernetes によって自動的に再作成されます。

[source,bash]
----
kubectl delete pod <pod-name> -n <name-space> --now
----

## ビルドのキューイングのデバッグ
ビルドのキューイングのデバッグに関する問題を解決するには、CircleCI Server 2.x のhttps://circleci.com/docs/ja/2.0/troubleshooting/?section=server-administration#debug-queuing-builds[トラブルシューティング]ガイドを参照してください。