---

contentTags:
  platform:
  - Cloud
---
= Testing iOS applications on macOS
:page-layout: classic-docs
:page-description: macOS 上の iOS アプリケーションのテスト.
:page-liquid:
:icons: font
:toc: macro

:toc-title:

このドキュメントでは、CircleCI を使用して iOS アプリケーションのテストをセットアップおよびカスタマイズする方法について説明します。

[#overview]
== インサイト スナップショットバッジの概要

CircleCI では、 macOS 仮想マシンでの iOS プロジェクトのビルド、テスト、およびデプロイをサポートしています。 提供されている各イメージには、 Xcode と共に、 Ruby や OpenJDK などの共通のツールセットがインストールされています。 For more information about supplied images, refer to the <<supported-xcode-versions,software manifest>> for each Xcode image.

There is documentation for xref:ios-codesigning#[iOS code signing projects] and xref:hello-world-macos#[getting started on MacOS].

[#supported-xcode-versions]
== サポートされている Xcode のバージョン

[#supported-xcode-versions-intel]
=== IntelでサポートされているXcodeのバージョン

{% include snippets/xcode-intel-vm.adoc %}

[#supported-xcode-versions-silicon]
=== Supported Xcode versions for Apple silicon

{% include snippets/xcode-silicon-vm.adoc %}

For supported Xcode versions on the Dedicated Hosts resource class, please see the table in the xref:dedicated-hosts-macos#[Dedicated hosts] documentation.

[#getting-started]
== はじめよう

Select a macOS project repository you would like to build from the *Projects* page of the https://app.circleci.com/[CircleCI web app].

We highly recommend using link:https://fastlane.tools[Fastlane] to build and sign your apps in CircleCI. fastlaneを使うと、多くの場合が最小限の設定で簡単にビルド、テスト、デプロイプロセスを実行することができます。

[#setting-up-your-xcode-project]
=== Xcode プロジェクトの設定

CircleCI でプロジェクトを設定した後、 fastlane でビルドするスキームが Xcode プロジェクトで「共有」としてマークされていることを確認する必要があります。 Xcode で作成されるほとんどの新規プロジェクトでは、デフォルトのスキームはすでに「共有」としてマークされています。
 これを確認する、または既存のスキームを共有するには、次の手順を実行します。

. In Xcode, choose Product \-> Scheme \-> Manage Schemes
. 共有したいスキームの [Shared (共有する)] オプションを選択し、[Close (閉じる)] をクリックします。
. Ensure the `myproject.xcodeproj/xcshareddata/xcschemes` directory is checked into your Git repository and push the changes

単純なプロジェクトであれば、最小限の設定で実行できます。

[#using-fastlane]
== fastlane の使用

link:https://fastlane.tools/[Fastlane] is a set of tools for automating the build and deploy process of mobile apps. CicleCI上で fastlane を使用すると、ビルド、テスト、デプロイプロセスの設定や自動化が簡単に行えるため、ぜひご使用ください。 また、fastlane の使用によりビルドをローカルでも CircleCI 上でも同等に実行することができます。

[#adding-a-gemfile]
=== Gemfile の追加

It is recommended to add a `Gemfile` to your repository to make sure that the same version of Fastlane is used both locally and on CircleCI and that all dependencies are installed. Below is a sample of a simple `Gemfile`:

[source,ruby]
----
# Gemfile
source "https://rubygems.org"
gem 'fastlane'
----

After you have created a `Gemfile` locally, you will need to run `bundle install` and check both `Gemfile` and `Gemfile.lock` into your project repository.

[#setting-up-fastlane-for-use-on-circleci]
=== CircleCI 上で使用する場合の fastlane のセットアップ

When using Fastlane in your CircleCI project, we recommend adding the following to beginning of your `Fastfile`:

[source,ruby]
----
# fastlane/Fastfile

...
platform :ios do
  before_all do
    setup_circle_ci
  end
  ...
end
----

The `setup_circle_ci` Fastlane action must be in the `before_all` block to perform the following actions:

* fastlane match で使用する一時的なキーチェーンを新規作成する (詳細については、コード署名のセクションを参照してください)。
* Switch Fastlane Match to `readonly` mode to make sure CI does not create new code signing certificates or provisioning profiles.
* ログやテスト結果のパスをセットアップして、それらを収集しやすくする。

[#example-configuration-for-using-fastlane-on-circleci]
=== CircleCI で fastlane を使用する場合の設定例

以下に、CircleCI で使用できる fastlane の基本設定を示します。

[source,ruby]
----
# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end
----

上記の設定は、以下の CircleCI の設定ファイルと組み合わせて使用できます。

[source,yaml]
----
# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 14.0.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
----

The environment variable `FL_OUTPUT_DIR` is the artifact directory where FastLane logs and signed `.ipa` file should be stored. Use this to set the path in the `store_artifacts` step to automatically save logs and build artifacts from Fastlane.

[#code-signing-with-fastlane-match]
=== Fastlane Match によるコード署名

ローカルでも CircleCI 環境下でもコード署名のプロセスを簡易化し自動化できるため、iOS アプリケーションの署名には Fastlane Match のご使用をお勧めします。

For more information on how to get started with Fastlane Match, visit the xref:ios-codesigning#[iOS code signing] page.

[#using-ruby]
== Ruby の使用

当社のXcodeイメージは、複数のバージョンのRubyがインストールされた状態で出荷されています。 The versions we install are the latest stable versions of Ruby, according to link:https://www.ruby-lang.org/en/downloads/[Ruby-Lang.org downloads page], at the time the image is built. The versions of Ruby that are installed in each image, along with the default Ruby selected for that image, are listed in the software manifests of each container (see <<supported-xcode-versions,supported Xcode versions>>).

システムディレクトリに適用されるアクセス許可が制限されるため、Ruby システムを使って Gems をインストールすることは推奨しません。 一般的なルールとして、ジョブには Chruby (すべてのイメージでデフォルトとして設定) が提供する代替の Ruby を使用することを推奨します。

[#switching-rubies-with-the-macos-orb]
=== macOS Orb を使った Ruby の切り替え

Using the official macOS orb (version `2.0.0` and above) is the easiest way to switch Rubies in your jobs. どの Xcode イメージを使用していても、適切な切り替えコマンドが自動的に使用されます。

まずは、Orb を設定の一番最初に含めます。

[source,yaml]
----
# ...
orbs:
  macos: circleci/macos@2
----

Then, call the `switch-ruby` command with the version number required. たとえば、Ruby 2.6 に切り替える場合は、

[source,yaml]
----
steps:
  # ...
  - macos/switch-ruby:
      version: "3.1"
----

Replace `3.1` with the version you require from the Software Manifest file. You do not need to specify the full Ruby version, `3.1.3` for example, just the major version. そうすることで、設定を壊すことなく Ruby の新しいパッチバージョンの新しいイメージに切り替えることができます。

To switch back to the system default Ruby (the Ruby shipped by Apple with macOS), define the `version` as `system`:

[source,yaml]
----
steps:
  # ...
  - macos/switch-ruby:
      version: "system"
----

[#switching-rubies-manually]
=== 手動での Ruby の切り替え

For Xcode version `14.2` and higher, add the following to the beginning of your job.

[source,yaml]
----
steps:
  # ...
  - run:
      name: Set Ruby Version
      command: rbenv global 3.1.3 && rbenv rehash
----

Replace `3.1.3` with the version of Ruby required.

To revert back to the system Ruby, specify `system` as the Ruby version.

For Xcode versions `14.1` and lower, add the following to the beginning of your job.

[source,yaml]
----
steps:
  # ...
  - run:
      name: Set Ruby Version
      command: sed -i '' 's/^chruby.*/chruby ruby-3.1.3/g' ~/.bash_profile
----

Replace `3.1.3` with the version of Ruby required.

To revert back to the system Ruby, specify `system` as the Ruby version.

[#installing-additional-ruby-versions]
=== Ruby バージョンの追加インストール

注: Ruby バージョンを追加インストールするにはかなりの時間を要します。 デフォルトでイメージにインストールされていな特定のバージョンを使用する必要がある場合のみ行うことを推奨します。

プリインストールされていない Ruby のバージョンでジョブを実行するには、必要なバージョンの Ruby をインストールする必要があります。

For Xcode versions `14.2` and higher, this can be done with the `rbenv install` command, ensuring you pass the version of Ruby required. If a newer version of Ruby is not available, you will need to update the `ruby-build` package (`brew upgrade ruby-build`) to ensure the latest Ruby version definitions are available.

For Xcode versions `14.1` and lower, we use the link:https://github.com/postmodern/ruby-install[ruby-install] tool to install the required version. インストールが完了したら、上記の方法でバージョンを選択することができます。

[#using-custom-versions-of-cocoapods-and-other-ruby-gems]
=== カスタムバージョンの CocoaPods と他の Ruby gem の使用

ローカルで使用しているバージョンの CocoaPods を CircleCI のビルドでも使用するには、iOS プロジェクトで Gemfile を作成し、そこに CocoaPods バージョンを追加することをお勧めします。

[source,ruby]
----
source 'https://rubygems.org'

gem 'cocoapods', '= 1.3.0'
----

次に、Bundler を使用してインストールします。

{% raw %}

[source,yaml]
----
steps:
  - restore_cache:
      key: 1-gems-{{ checksum "Gemfile.lock" }}
  - run: bundle check || bundle install --path vendor/bundle --clean
  - save_cache:
      key: 1-gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
----

{% endraw %}

You can then ensure you are using those, by prefixing commands with `bundle exec`:

[source,yaml]
----
# ...
steps:
  - run: bundle exec pod install
----

[#using-nodejs]
== NodeJS の使用

Xcode イメージには少なくとも一つのバージョンの NodeJS が使用可能な状態で提供されています。

[#images-using-xcode-13-and-later]
=== Xcode 13 以降を使用したイメージ

These images have NodeJS installations managed by `nvm` and will always be supplied with the latest `current` and `lts` release as of the time the image was built Additionally, `lts` is set as the default NodeJS version.

Version information for the installed NodeJS versions can be found in <<supported-xcode-versions,the software manifests for the image>>], or by running `nvm ls` during a job.

To set the `current` version as the default:

[source,yaml]
----
# ...
steps:
  - run: nvm alias default node
----

To revert to the `lts` release:

[source,yaml]
----
# ...
steps:
  - run: nvm alias default --lts
----

特定の NodeJS をインストールし使用しするには、以下を実行します。

[source,yaml]
----
# ...
steps:
  - run: nvm install 12.22.3 && nvm alias default 12.22.3
----

These images are also compatible with the official https://circleci.com/developer/orbs/orb/circleci/node[CircleCI Node orb], which helps to manage your NodeJS installation along with caching packages.

[#images-using-xcode-125-and-earlier]
=== Xcode 12.5 以前を使用したイメージ

These images come with at least one version of NodeJS installed directly using `brew`.

Version information for the installed NodeJS versions can be found in the software manifests for the image (see <<supported-xcode-versions,supported Xcode versions>>).

These images are also compatible with the official link:https://circleci.com/developer/orbs/orb/circleci/node[CircleCI Node orb] which helps to manage your NodeJS installation, by installing `nvm`, along with caching packages.

[#using-homebrew]
== Homebrew の使用

link:http://brew.sh/[Homebrew] is pre-installed on CircleCI, so you can simply use `brew install` to add nearly any dependency you require to complete your build. 例えば下記のようにします。

[source,yaml]
----
# ...
steps:
  - run:
      name: Install cowsay
      command: brew install cowsay
  - run:
      name: cowsay hi
      command: cowsay Hi!
----

It is also possible to use the `sudo` command if necessary to perform customizations outside of Homebrew.

[#configuring-deployment]
== デプロイの設定

アプリケーションのテストと署名が完了したら、App Store Connect や TestFlight など、任意のサービスへのデプロイを設定できます。 For more information on how to deploy to various services, including example Fastlane configurations, check out the link:/docs/deploy-ios-applications/[deploying iOS apps guide].

[#troubleshooting]
== トラブルシューティング

If you are facing build failures while executing your jobs, check out our link:https://support.circleci.com/hc/en-us/categories/115001914008-Mobile[support center knowledge base] for answers to common issues.

[#next-steps]
== 次のステップ

* See the link:https://github.com/CircleCI-Public/circleci-demo-ios[`circleci-demo-ios` GitHub repository] for a full example of how to build, test, sign and deploy an iOS  project using Fastlane on CircleCI.
* See the xref:ios-codesigning#[iOS code signing] page to learn how to configure Fastlane Match for your project.