---

version:
- Cloud
- Server v3.x
- Server v2.x
---
= Troubleshooting test splitting
:page-layout: classic-docs
:page-liquid:
:page-description: Some tips and common errors to help troubleshoot your CircleCI test splitting implementation.
:icons: font
:toc: macro

:toc-title:

[#using-test-splitting-with-python-django-tests]
== Python Django テストでのテスト分割の使用

CircleCI でテスト分割を活用するには、実行するテストの一覧を渡す必要があります。 しかし、Django を使用する場合、テストの実行方法によっては、テストをグロブして渡すことができません。

独自のユースケースに合わせたテスト分割では、問題が発生することがあります。 One example of a user resolving an issue when test splitting in Python Django did not perform correctly can be found in the following Discuss post, which can be found link:https://discuss.circleci.com/t/python-django-tests-not-being-split-correctly/36624[here].

以下に、この例を使用してテスト分割を行う簡単な例を示します。

[source,yaml]
----
- run:
    command: |
      # get test files while ignoring __init__ files
      TESTFILES=$(circleci tests glob "catalog/tests/*.py" | sed 's/\S\+__init__.py//g')
      echo $TESTFILES | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
      cat circleci_test_files.txt
      TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
      # massage filepaths into format manage.py test accepts
      TESTFILES=$(echo $TESTFILES | tr "/" "." | sed 's/\.py$//g')
      echo $TESTFILES
      pipenv run python manage.py test --verbosity=2 $TESTFILES
----

[#using-test-splitting-with-pytest]
== その他のテスト分割方法

pytest で複数のコンテナにテストを分割しようとすると、以下のいずれかのエラーが発生することがあります。

[source,shell]
----
No timing found for "tests/commands/__init__.py"
No timing found for "tests/commands/test_1.py"
No timing found for "tests/commands/test_2.py"
----

これらのエラーのいずれかが返された場合は、以下に示すような多少の調整が必要です。

[#are-you-setting-a-custom-working-directory?]
=== カスタムの working_directory を設定している場合

この場合は、テストメタデータの XML ファイルに保存するファイルパスを調整してみてください。 Alternatively, if you are able to, try working out of the standard working directory we set for a container to see if that helps (you can do this by removing any instances of `working_directory` in your test run job).

[#where-does-your-pytest-ini-live]
=== Where does your `pytest.ini` live?

テスト分割を正しく行うには、ルートディレクトリでテストを実行する必要があります。 If your tests are not being run in the root directory, you may need to run the following command before you test the `run` command:

[source,shell]
----
cp -f .circleci/resources/pytest_build_config.ini pytest.ini
----

The `.circleci/resources/pytest_build_config.ini` path may need to be replaced to point to where it's located in your project.

[#are-you-setting-the-junit-family-in-your-pytest-ini]
=== pytest.ini に junit_family を設定している場合

Check to see if you have something like `junit_family=legacy` set in your pytest.ini file. For more information on how to set `junit_family`, refer to the following page, which can be found link:https://docs.pytest.org/en/stable/_modules/_pytest/junitxml.html[here]. 上記ページの該当箇所は、"families" で検索すると確認できます。

CAUTION: A breaking change was introduced in pytest 6.1 the `junit_family` xml format changed `to xunit2`, which does not include filenames. This means that `--split-by=timings` will not work unless you specify `xunit1`. For more information see the link:https://docs.pytest.org/en/stable/changelog.html#id137[pytest changelog].

[#example-project-that-correctly-splits-by-timing]
=== タイミング基準で正しく分割するサンプルプロジェクト

The example below is from the link:https://github.com/CircleCI-Public/sample-python-cfd[`sample-python-cfd` project] and shows an implementation of test splitting:

```yml
version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test:
    parallelism: 2
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: テストの実行
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "openapi_server/**/test_*.py" | circleci tests split --split-by=timings)
            mkdir -p test-results
            pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  sample:
    jobs:
      - build-and-test
```

[#video-troubleshooting-globbing]
=== ビデオ: グロブのトラブルシューティング

NOTE: To follow along with the commands in the video below you will need to be <<ssh-access-jobs#,`SSH-ed into a job`>>.

++++
<iframe width="854" height="480" src="https://www.youtube.com/embed/fq-on5AUinE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++

[#other-ways-to-split-tests]
== その他のテスト分割方法

一部のサードパーティのアプリケーションやライブラリでも、テストスイートの分割がサポートされています。 これらのアプリケーションは、CircleCI では開発およびサポートが行われていません。 CircleCI でこれらのアプリケーションを使用して問題が発生した場合は、オーナーに確認してください。 If you're unable to resolve the issue you can search and ask on our forum, link:https://discuss.circleci.com/[Discuss].

* **link:https://knapsackpro.com[Knapsack Pro]** - Enables allocating tests
dynamically across parallel CI nodes, allowing your test suite exection to run
faster. See link:https://docs.knapsackpro.com/2018/improve-circleci-parallelisation-for-rspec-minitest-cypress[CI build time graph examples].
* **link:https://github.com/previousnext/phpunit-finder)[phpunit-finder]** - This is
a helper CLI tool that queries `phpunit.xml` files to get a list of test
filenames and print them. テストを分割して CI ツールのタイミングに基づいて並列に実行する場合に、このツールを使用すると便利です。
* **link:https://golang.org/cmd/go/#hdr-List_packages_or_modules[go list]** - Use the built-in Go command `go list ./...` to glob Golang packages. これにより、パッケージ テストを複数のコンテナに分割できます。
+
[souce,shell]
----
go test -v $(go list ./... | circleci tests split)
----

[#next-steps]
== 次のステップ

* <<collect-test-data#,Collecting Test Data>>
* <<insights-tests#,Test Insights>>