---

description: CircleCI プロジェクト設定の設定ファイルのポリシー管理
contentTags:
  platform:
  - クラウド
---
= CLI を使った設定ファイルとポリシーの作成
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

NOTE: 設定ファイルのポリシー管理機能が **Scale** プランでご利用いただけるようになりました。現在 **オープンプレビュー** であり、 すべての側面において、今後変更される可能性があります。

CAUTION: 設定ファイルのポリシー管理で CLI を使用する前に、ご使用の CLI がトークンで認証されており、更新されていることをご確認ください。 詳細については、 link:/docs/local-cli[ローカルの CLI のインストール] のページをご覧ください。

[#develop-configs]
== 設定ファイルの作成

CircleCI 設定ファイル用のポリシーにより、違反を検出し、組織のポリシーを遵守していないビルドを停止することができます。 しかし、これにより `.circleci/config.yml` ファイルのローカルでの作成に問題が生じます。  `config.yml` を変更すると、パイプラインがブロックされてしまう場合があります。 それにより開発スピードが遅くなり、フラストレーションになります。

それを低減するために、CircleCI CLI を使って CI パイプラインの外でローカルに組織のポリシーに対して `config.yml` を実行を実行することができます。 設定ファイルが遵守しているかどうかについてすぐにフィードバックを受け取ることができます。

以下のコマンドは、指定した設定ファイルの内容が組織のポリシーを遵守しているかどうかの判定をリクエストします。 コマンドは、ステータスを含む CircleCI の _判定_ と生じた可能性があるすべての違反を返します。

判定コマンドの例:

[source,shell]
----
circleci policy decide --owner-id $ORG_ID --input $PATH_TO_CONFIG
----

CircleCI の判定の例:

[source,json]
----
{
    "status": "HARD_FAIL",
    "hard_failures": [
        {
            "rule": "custom_rule",
            "reason": "custom failure message"
        }
    ],
    "soft_failures": [
        {
            "rule": "other_rule",
            "reason": "other failure message"
        }
    ]
}

----

[#develop-policies]
== ポリシーの作成

The CLI provides a language-agnostic way of evaluating local policies against arbitrary config inputs. This is the recommended
way of developing and testing policies. It is similar to the previous command except that it provides a path to the local policies directory.

The policy files (*.rego) present in the given policy directory (searched recursively) will form the policy bundle.

[source,shell]
----
circleci policy decide --input $PATH_TO_CONFIG $PATH_TO_POLICY_DIR
----

Policies that use `data.meta...` values like `branch` or `project_id` should also provide a JSON file mocking those values with `--metafile $PATH_TO_JSON`

It is recommended that you build a test suite of policy/config combinations and run them locally, or in CI, before pushing them to your organization's active policies.

[#get-policy-decision-audit-logs]
== Get policy decision audit logs

Audit logs provide documentary evidence for a policy decision being performed at a certain point of time.
Audit logs include the inputs which influenced the decision, as well as the outcome of the decision.

The CLI provides a `policy logs` command to fetch the policy decision logs for your organization.

Following is the output of this command when run with `--help` flag:

[source,shell]
----
circleci policy logs --help

# Returns the following:
Get policy (decision) logs


Usage:
  circleci policy logs [flags]

Examples:
policy logs  --owner-id 462d67f8-b232-4da4-a7de-0c86dd667d3f --after 2022/03/14 --out output.json

Flags:
      --after string        filter decision logs triggered AFTER this datetime
      --before string       filter decision logs triggered BEFORE this datetime
      --branch string       filter decision logs based on branch name
      --context string      policy context (default "config")
  -h, --help                help for logs
      --out string          specify output file name
      --owner-id string     the id of the policy's owner
      --project-id string   filter decision logs based on project-id
      --status string       filter decision logs based on their status

----

[#input]
=== 入力

* The organization ID information is required, which can be provided with `--owner-id` flag.
* The command accepts the following filters for logs: `--after`, `--before`, `--branch`, `--status`, and `--project-id`. These filters are optional. Also, any combination of filters can be used to suit your auditing needs.

[#output]
=== 出力

* Stdout: By default, the decision logs are printed as a list of logs to the standard output.
* File: Output can be written to a file (instead of stdout). This can be done by providing the file path using `--out` flag.