---

contentTags:
  platform:
  - Cloud
---
= Using the macOS execution environment
:page-layout: classic-docs
:page-description: "Learn how to configure a your jobs to run in the macOS execution environment."
:page-liquid:
:icons: font
:toc: macro

:toc-title:

macOS 実行環境は iOS と macOS の開発用に提供されるもので、これを使用して macOS および iOS アプリケーションのテスト、ビルド、デプロイを CircleCI 上で行えます。 macOS Executor は、macOS 環境でジョブを実行し、iPhone、iPad、Apple Watch、および Apple TV の各シミュレーターへのアクセスを提供します。

You can use the macOS execution environment to run your xref:jobs-steps#[jobs] in a macOS environment on a virtual machine (VM). You can access the macOS execution environment by using the `macos` executor and specifying an Xcode version:

[source,yaml]
----
jobs:
  build:
    macos:
      xcode: 14.2.0

    steps:
      # Commands will execute in macOS container
      # with Xcode 14.2.0 installed
      - run: xcodebuild -version
----

[#supported-xcode-versions]
== サポートされている Xcode のバージョン

[#supported-xcode-versions-intel]
=== IntelでサポートされているXcodeのバージョン

{% include snippets/xcode-intel-vm.adoc %}

[#supported-xcode-versions-silicon]
=== Supported Xcode versions for Apple silicon

{% include snippets/xcode-silicon-vm.adoc %}

For supported Xcode versions on the Dedicated Hosts resource class, please see the table in the [Dedicated hosts](/docs/dedicated-hosts-macos) documentation.

[#available-resource-classes]
== 利用可能なリソースクラス

{% include snippets/ja/macos-resource-table.adoc %}

[source,yaml]
----
jobs:
  build:
    macos:
      xcode: "14.2.0"
    resource_class: macos.x86.medium.gen2
----

[#using-the-macos-executor]
== macOS Executor のイメージ更新サイクル

Each `macos` job is run in a fresh virtual machine, using a specified version of macOS. CircleCI では、Apple から新しい安定版 (またはベータ版) バージョンの Xcode がリリースされるたびに、新しいイメージをビルドしてデプロイします。 ほとんどの場合、ビルドイメージの内容は変更されません。 しかし、例外的に、CircleCI でコンテナの再ビルドが必要になる場合があります。 CircleCI's goal is to keep your execution environment stable, and to allow you to opt-in to newer macOS environments by setting the `xcode` key in your `.circleci/config.yml` file.

弊社では、実行環境を可能な限り最新の状態に保つために、各イメージに含まれる macOS のバージョンを定期的に更新しています。 When a new major version of macOS is released, CircleCI will update once the new major version of Xcode reaches the `xx.2` release. これにより、実行環境の安定性が保たれます。

CircleCI will announce the availability of new macOS containers, including Xcode betas, in the announcements section of our link:https://discuss.circleci.com/c/announcements[Discuss site].

[#beta-image-support]
=== ベータ版イメージのサポート

CircleCI では、開発者の皆様が Xcode の次の安定版がリリースされる前にアプリのテストを行えるよう、Xcode のベータ版を macOS Executor で可能な限り早期にご利用いただけるよう尽力しています。

ベータ版イメージについては、CircleCI の安定版イメージ (更新されない) とは異なり、GM (安定版) イメージがリリースされ更新が停止するまでは、新規リリースのたびに既存のベータイメージが上書きされます。

現在ベータ版となっているバージョンの Xcode イメージを使用している場合、Apple が新しい Xcode ベータ版をリリースした際に、最小限の通知によりそのイメージに変更が加えられる場合があります。 これには、CircleCI では制御できない Xcode および関連ツールに互換性を損なう変更が含まれる場合があります。

To read about CircleCI's customer support policy regarding beta images, please check out the following link:https://support.circleci.com/hc/en-us/articles/360046930351-What-is-CircleCI-s-Xcode-Beta-Image-Support-Policy-[support center article].

[#apple-silicon-support]
=== Apple シリコンのサポート

Running or testing Apple silicon apps natively can be done on our silicon-based Macs or by using xref:runner-overview#available-self-hosted-runner-platforms[CircleCI runner].

It is also possible to build Apple silicon/universal binaries using Xcode `12.0.0` and higher, as Apple provides both the Intel (`x86_64`) and Apple silicon (`arm64`) toolchains in this release. Cross-compiling Apple silicon binaries on Intel hosts has an additional overhead, and, as a result, compilation times will be longer than native compilation for Intel.

[#xcode-cross-compilation]
== Xcode のクロスコンパイル

[#universal-binaries]
=== ユニバーサルバイナリ

Xcode currently supports the creation of universal binaries which can be run on both `x86_64` and `ARM64` CPU architectures without needing to ship separate executables. This is supported only under Xcode `12.2`+, although older Xcode versions can still be used to compile separate `x86_64` and `ARM64` executables.

[#extract-unwanted-architectures]
=== 不要なアーキテクチャの抽出

By default, Xcode `12.2`+ will create universal binaries, compiling to a single executable that supports both `x86_64` and `ARM64` based CPUs. If you need to remove an instruction set, you can do so by using the `lipo` utility.

Assuming that you want to create a standalone `x86_64` binary from a universal binary called `circleci-demo-macos`, you can do so by running the command:

[source,shell]
----
lipo -extract x86_64 circleci-demo-macos.app/Contents/MacOS/circleci-demo-macos -output circleci-demo-macos-x86_64
----

以下により抽出したバイナリのサポートアーキテクチャを確認できます。

[source,shell]
----
lipo -info circleci-demo-macos-x86_64
----

 これにより、以下が出力されます。

[source,shell]
----
Architectures in the fat file: circleci-demo-macos-x86_64 are: x86_64
----

[#cross-compiled-binaries]
=== バイナリのクロスコンパイル

While universal binaries are only supported under Xcode `12.2`+, you can still cross compile binaries for architectures other than the architecture of the machine being used to build the binary. For `xcodebuild` the process is relatively straightforward. To build `ARM64` binaries, prepend the `xcodebuild` command with `ARCHS=ARM64 ONLY_ACTIVE_ARCH=NO` such that it reads `xcodebuild ARCHS=ARM64 ONLY_ACTIVE_ARCH=NO ...`. For the `x86_64` architecture simply change `ARCHS` to `x86_64`.

[#optimization-and-best-practices]
== 最適化とベストプラクティス

[#pre-start-the-simulator]
=== シミュレーターの事前起動

アプリケーションをビルドする前に iOS シミュレーターをあらかじめ起動して、シミュレーターの稼働が遅れないようにします。 こうすることで、ビルド中にシミュレーターのタイムアウトが発生する回数を全般的に減らすことができます。

To pre-start the simulator, add the macOS orb (version `2.0.0` or higher) to your config:

[source,yaml]
----
orbs:
  macos: circleci/macos@2
----

Then call the `preboot-simulator` command, as shown in the example below:

[source,yaml]
----
steps:
  - macos/preboot-simulator:
      version: "15.0"
      platform: "iOS"
      device: "iPhone 13 Pro Max"
----

シミュレータがバックグラウンドで起動するまでの最大時間を確保するために、このコマンドをジョブの初期段階に配置することをお勧めします。

If you require an iPhone simulator that is paired with an Apple Watch simulator, use the `preboot-paired-simulator` command in the macOS orb:

[source,yaml]
----
steps:
  - macos/preboot-paired-simulator:
      iphone-device: "iPhone 13"
      iphone-version: "15.0"
      watch-device: "Apple Watch Series 7 - 45mm"
      watch-version: "8.0"
----

NOTE: シミュレーターの起動には数分、ペアのシミュレーターの起動にはそれ以上かかる場合があります。 During this time, any calls to commands such as `xcrun simctl list` may appear to hang while the simulator is booting up.

[#collecting-ios-simulator-crash-reports]
=== iOS シミュレーターのクラッシュレポートの収集

Often if your `scan` step fails, for example, due to a test runner timeout, it is likely that your app has crashed during the test run. このような場合、クラッシュレポートを収集することでクラッシュの正確な原因を診断することができます。 クラッシュレポートをアーティファクトとしてアップロードする方法は以下の通りです。

[source,yaml]
----
steps:
  # ...
  - store_artifacts:
    path: ~/Library/Logs/DiagnosticReports
----

[#optimizing-fastlane]
=== fastlane の最適化

By default, Fastlane Scan generates test output reports in `html` and `junit` formats. If your tests are taking a long time and you do not need these reports, consider disabling them by altering the `output_type` parameter as described in the link:https://docs.fastlane.tools/actions/run_tests/#parameters[fastlane docs].

[#optimizing-cocoapods]
=== CocoaPods の最適化

基本的なセットアップ手順に加えて、Specs リポジトリ全体をクローンするのではなく、CDN を利用できる CocoaPods 1.8 以降のバージョンを使用することをお勧めします。 そうすることで、ポッドをすばやくインストールできるようになり、ビルド時間が短縮されます。 If you are using Cocoapods 1.7 or older, consider upgrading to 1.8 or newer as this change allows for much faster job execution of the `pod install` step.

実行するには Podfile ファイルの先頭行を次のように記述します。

[source,shell]
----
source 'https://cdn.cocoapods.org/'
----

If upgrading from Cocoapods 1.7 or older, ensure the **Fetch CocoaPods Specs** step is removed from your CircleCI configuration, and ensure the following line is removed from your Podfile:

[source,shell]
----
source 'https://github.com/CocoaPods/Specs.git'
----

CocoaPods を最新の安定版に更新するには、以下のコマンドで Ruby gem を更新します。

[source,shell]
----
sudo gem install cocoapods
----

A further recommendation is to check your link:http://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control[Pods directory into source control]. そうすることで、決定論的で再現可能なビルドを実現できます。

WARNING: CocoaPods 1.8 のリリース以降、CocoaPods Spec リポジトリ用に提供した以前の S3 ミラーは整備も更新もされていません。 既存のジョブへの障害を防ぐために利用可能な状態ではありますが、上記の CDN 方式に変更することをお勧めします。

[#optimizing-homebrew]
=== Homebrew の最適化

デフォルトでは、Homebrew はすべての操作の開始時に更新の有無を確認します。 As Homebrew has a fairly frequent release cycle, this means that any step which calls `brew` can take some extra time to complete.

ビルドのスピード、または Homebrew の新たな更新によるバグが問題であれば、自動更新を無効にすることができます。 それにより、1 つのジョブにつき最大で平均 2-5 分短縮することができます。

To disable this feature, define the `HOMEBREW_NO_AUTO_UPDATE` environment variable within your job:

[source,yaml]
----
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install wget
----

[#supported-build-and-test-tools]
== サポートされているビルドおよびテストのツール

CircleCI では、macOS Executor を使って iOS のビルドやテストに関するほぼすべての戦略に合わせてビルドをカスタマイズできます。

[#common-test-tools]
=== 一般的なテストツール

以下のテストツールは、CircleCI で有効に機能することが確認されています。

* link:https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/01-introduction.html[XCTest]
* link:https://github.com/kiwi-bdd/Kiwi[Kiwi]
* link:https://github.com/kif-framework/KIF[KIF]
* link:http://appium.io/[Appium]

[#react-native-projects]
=== React Native プロジェクト

React Native projects can be built on CircleCI using `macos` and `docker` executor types. For an example of configuring a React Native project, please see link:https://github.com/CircleCI-Public/circleci-demo-react-native[our demo React Native application]

[#using-multiple-executor-types-macos-docker]
== 複数の Executor タイプ (macOS + Docker) の使用

It is possible to use multiple xref:executor-intro#[executor types] in the same workflow. 下記の例では、iOS プロジェクトの各プッシュは macOS でビルドされ、デプロイイメージは Docker で実行されます。

[source,yaml]
----
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WebTests

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

  deploy-snapshot:
    docker:
      - image: cimg/deploy:2022.08
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Do the things"

workflows:
  build-test-lint:
    jobs:
      - deploy-snapshot
      - build-and-test
----

[#next-steps]
== 次のステップ

Get started with xref:hello-world-macos#[Configuring a Simple macOS Application on CircleCI].