---
description: このドキュメントでは、CircleCI Server v2.19. の機能や注意事項についてまとめています。 アップグレードの要件、注意事項、ベストプラクティス、および既知の問題をご確認ください。
version:
- Server v2.x
- サーバー管理者
---
= CircleCI Server v2.19.x の新機能
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

このドキュメントでは、CircleCI Server v2.19 の機能や注意事項についてまとめています。 パッチリリースを含むすべての変更の一覧は、https://circleci.com/server/changelog[更新履歴]でご確認ください。 For a step by step guide to **upgrading** your CircleCI server installation to v2.19.x, see our <<updating-server#nomad-launch-configuration, upgrade guide>>.

NOTE: CircleCI Server v2.x の更新は、2022 年 3 月に終了します。 CircleCI Server v2.x をご利用のお客様へのサポートは、引き続きご提供いたします。

## アップグレードの要件

WARNING: ルート以外のパスにスコープ設定された IAM ロールを使用している場合は、2.19.3 にアップグレードする前に、出力プロセッサカスタマイズスクリプトで`OUTPUT_PROCESSOR_USE_NAIVE_ROLE_MAPPING` 環境変数の設定を解除する必要があります。 カスタマイズスクリプトの使用に関する詳細は、https://circleci.com/docs/2.0/customizations/#service-configuration-overrides[カスタマイズガイド]を参照してください。

WARNING: For AWS installs, *before upgrading* to v2.19, follow <<update-nomad-clients#important, this guide>> to update your nomad launch configuration.

WARNING: If you are upgrading from pre v2.18.x, and have at any time changed your CircleCI organization name, there is a <<updating-server#org-rename-script, script>> that *must* be run before starting the upgrade process. v2.18.x を既に実行している場合は、このスクリプトは既に実行されています。

## 注意事項とベストプラクティス

* Services マシンには最低 32 GB の RAM が必要になりました。 
* v2.18 では Redis の設定を一部変更しました。 Redis を外部処理化している場合は、設定を更新する必要があります。 2.18 以前のバージョンから 2.19 へのアップグレードの場合は、担当のカスタマーサクセスマネージャーまでお問い合わせください。
* 対応する Postgres バージョンを変更したため、postgreSQL v9.5.16 以降が必要です。 PostgreSQL を外部処理化している場合は、バージョン 2.17.x で更新してから、2.19 にアップグレードしてください。

## 既知の問題

* ストレージドライバーの設定で `NONE` が選択されている静的な(AWS 以外の) 環境では、テストはファイル名およびファイルサイズによってのみ分割することが可能です。 タイミングデータによりテストを分割しようとすると、静的インスタンスは自動的にファイル名で分割します。

* *インストール環境に HTTP プロキシを使用している場合は、v2.19.02 以降のバージョンにアップグレードしてください*。 ジョブステップのログや Docker コマンドのカスタマイズにより 2.19.2 以前のバージョンでは CircleCI Server の HTTP プロキシの設定と互換性がないという問題がありました。

* CircleCI Server に最初にアクセスしたユーザーに、管理者アクセス権が付与されます。 現在、LDAP 認証を使用しているとこれが実行できないという既知の問題があります。 回避するにはhttps://circleci.com/docs/2.0/authentication#grant-admin-access-to-user[こちらのガイド]に従ってください。

* ネットワーク設定をデフォルトから変更している場合、SSH を使用したビルドの検査が可能であることを確認するために以下のステップを実行する必要がある場合があります。
** Nomad クライアントマシンの場合は、 `/etc/circleci/public-ipv4`を作成します。
** このファイルには、Nomad クライアントのパブリック IP アドレス (該当するアドレスがある場合)、 またはプライベート IP アドレスを記載してください。
+
TIP: CircleCI Server 環境における SSH 再実行についての詳細は、https://circleci.com/docs/2.0/ssh-server/[CircleCI Serverでの SSH 再実行のアーキテクチャ]ガイドを参照してください。

* 下記記載の暗号スイートの変更により、v2.19.02 よりクラシックロードバランサは使用できなくなりました。 https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-ssl-security-policy.html[クラシックロードバランサ]からのリクエストは受け付けなくなったため、https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html[ネットワークロードバランサー (NLB)] または https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html[アプリケーションロードバランサ (ALB)] に移行する必要があります。

## v2 19.14 の新機能

* exim イメージのセキュリティパッチ。
廃止予定のチーム用 GitHub API エンドポイントが置き換えられました。

## v2 19.13 の新機能

* 各種セキュリティおよび脆弱性対応パッチ

## v2 19.12 の新機能

* 自動スケーリングにおけるバージョン 1.0 用ビルダーの正しいシャットダウンを行うためのサポートを削除
  ** これにより Python 2 のセキュリティ脆弱性による影響が軽減されます。

## v2 19.11 の新機能

* 一つの設定ファイルで 50 エイリアスまでしか使えなかったバグを修正しました。

## v2 19.10 の新機能

* go -git で「git checkout」 が 失敗する原因となっていたバグを修正しました。
* picard dispatcher の YAML パーサーのバグを修正し、 `config-str` が 50 を超える YAML エイリアスを持てるようになりました。
* S3 保持ポリシーにより古いジョブのテスト結果が削除されるバグを修正しました。
* 「順序が正しくない」コミットステータスの可能性が減少しました。
* 全体的なセキュリティーのアップデート

## v2 19.09 の新機能

* Docker Executor の認証パスワードで、英数字以外の文字をより適切に処理できるようになりました。 `auth`キーの下の Docker ID パスワードフィールド</a>で、 `~` と `?` の使用を妨げていたバグを修正しました。
* 全体的なセキュリティーのアップデート

## v2 19.08 の新機能

* 静的なインストール環境においてストレージドライバーの設定で`NONE`が選択されている場合に、並列処理に失敗する原因となっていたバグを修正しました。

## V2 19.07 の新機能

* Docker Exdecutor の中国地域 ECR イメージへの認証を妨げていたバグを修正しました。

* `fileserverd` サービスの起動から再帰的な `chown` を削除しました。 これにより、使用量が多いインスタンスでは、起動プロセスに時間がかかったり、起動がブロックされる場合がありました。

## v2 19.06 の新機能

* ワークフローのステータスが GitHub で誤った順序で表示される原因となっていたバグを修正しました。

* CPU の使用と遅延を大幅に削減する、 ` workflows-conductor ` のパフォマンスが改善されました

* IAM ユーザーを介して `us-east-1` 以外の S3 ストレージ領域を使用できないバグを修正しました。

* SMTP パスワードのフォーマットタイプが修正され、セットアップ時にマスキングされるようになりました。

## v2 19.05 の新機能

* サービスマシンがクラッシュした場合や VM サービスインスタンスが手動で終了した場合に、 VM データベースが誤った状態になることがあるバグを修正しました。

## v2 19.04 の新機能

* サービスマシンのログが作成される前にバンドル作成がタイムアウトする原因となっていたバグを修正し、Replicated のログのみを残しました。

* `circle.s3.connection_pool.*` の下の S3 接続プールメトリックがテスト結果サービスに追加され、このサービスに関する問題のデバッグがしやすくなりました。

* ワークフローサービスの欠けていた環境変数が追加されました。 これらの環境変数がないことにより、ワークフローが実行されるたびに過剰なスタックトレースが発生していました。 これにより、ログのローテーションが過剰になります。

* GitHub ステータスの更新に失敗する原因となっていたバグを修正しました。 プロジェクトに壊れた認証トークンを持つユーザーがいる場合にこのバグが発生したお客様がいます。

## v2 19.03 の新機能

* 廃止された GitHub.com API のエンドポイント`GET applications/%s/tokens/%s`を削除しました。

* サーバー環境において分散トレーシングがデフォルトで有効化されました。 トレースはサポートバンドルでサーバーの問題を解決する能力を向上するために使用されます。 サンプリングレートのトレースオプションは、Replicated の管理コンソールに表示されますが、CircleCI サポートから要求された場合にのみ、デフォルトから変更してください。

* ストレージドライバーを "none" (S3 以外) に設定すると、`restore_cache` が動作しない問題が修正されました。

* AWS AssumeRole がサブフォルダにあると、`output_processor`サービスが AWS AssumeRole を使用できない問題が修正されました。 この問題は、サブフォルダの使用が強制されるセキュリティポリシーを持つお客様に影響を与えていました。また、アーティファクトを保存できない、またはタイミングベースのテスト分割を使用できないという現象もありました。

* `vm-service`、`domain-service`、`permissions-service`  `federations-service`の各サービスで、`JVM_HEAP_SIZE`  環境変数を使用して JVM ヒープサイズを変更できるようになりました。

## v2 19.02 の新機能

* LDAP のログインフローにおいて、`GET` パラメーターとして送信するのではなく、匿名フォームを使って LDAP 認証状態を `POST` するようになりました。  以前は、LDAP を使ってユーザーを認証すると、ユーザー名とパスワードが`GET`リクエスト内のクエリパラメーターの一部としてプレーンテキストに送信されていました。 リクエストが HTTPS を介して行われると、リクエストログなどにユーザ名とパスワードが残っていましたが、 現在は修正されました。 

* Optimizely と Zendesk がサーバーのリリースイメージから削除されました。

* `CIRCLE_ADMIN_SERVER_HTTP_THREADS` や `CIRCLE_PUBLIC_FACING_SERVER_HTTP_THREADS`を高すぎる値に設定すると、フロントエンドコンテナの起動が妨げられる問題が修正されました。

* Due to changes in the GitHub API we have removed the use of `?client_id=x&client_secret=y` for GitHub, and GHE versions 2.17 and later.

* DLC を使用していると VM のスピンアップに断続的に失敗する原因となっていた問題が修正されました。

* Docker コンテナのプロキシ設定のカスタマイズを妨げていた問題が修正されました。 詳細は、https://circleci.com/docs/2.0/proxy/#nomad-client-proxy-setup[Nomad クライアントのプロキシ]とhttps://circleci.com/docs/2.0/customizations/#service-configuration-overrides[サービス設定のオーバーライド]のガイドを参照してください。

* ジョブコンテナにプロキシ設定が使われていると、成功したビルドのジョブステップが記録されないバグが修正されました。

* レガシー TLS バージョン 1.0 および 1.1 を削除し、1.2 および 1.3 TLS を有効にして、次の暗号スイートを指定しました
**  ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384

* Fixed a `statsd` configuration issue that meant some services were not emitting Telegraf metrics.

## What's New in v2.19.01

* Fixed a bug that was preventing some customers from upgrading due to a schema change in one of our library dependencies.

* Fixed a bug that was preventing some customers from inspecting builds via SSH due to a logic change in our build agent.

## What's New in v2.19

* You can now customize resource classes for your installation to provide developers with https://circleci.com/docs/2.0/optimizations#resource-class[CPU/RAM options] for the Jobs they configure. For more information https://circleci.com/docs/2.0/customizations#resource-classes[see our guide to customizing resource classes in server v2.19].

* CircleCI Server installations on AWS can now be https://github.com/circleci/enterprise-setup#configuration[configured to work on GovCloud].

* The image used to run the RabbitMQ server has been updated to fix vulnerabilities.
