---

description: A list of all built-in variables for your CircleCI projects.
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
  - Server v2.x
---
= Project values and variables
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

// :contentTags: {"platform"=>["Cloud", "Server v4.x", "Server v3.x", "Server v2.x"]}

// :description: A list of all built-in variables for your CircleCI projects.

このページでは、CircleCI プロジェクトで使用できる定義済みの値について説明します。

[#built-in-environment-variables]
== 定義済み環境変数

下記の定義済み環境変数は、すべての CircleCI プロジェクトで使用できます。 環境変数はジョブレベルで設定されます。 一つのジョブのコンテキスト内では使用できますが、パイプラインレベルでは存在しないため、パイプラインレベルまたはワークフローレベルのロジックには使用できません。

NOTE: You cannot use a built-in environment variable to define another environment variable. Instead, you must use a `run` step to export the new environment variables using `BASH_ENV`. For more details, see link:set-environment-variable#set-an-environment-variable-in-a-shell-command[Setting an Environment Variable in a Shell Command].

{% include snippets/ja/built-in-env-vars.adoc %}

[#pipeline-values]
== パイプライン値

パイプライン値は、すべてのパイプライン設定で事前に宣言することなく使用できます。 パイプライン値はパイプラインレベルで設定されます。 ワークフローやジョブの実行時ではなく、コンパイル時に挿入されます。

{% include snippets/ja/pipeline-values.adoc %}

たとえば以下のようになります。

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: ~/main
    steps:
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL
```

When using the above method to set the variables in the `environment` key, note that if the pipeline variable is empty it will be set to `<nil>`. If you need an empty string instead, link:set-environment-variable#set-an-environment-variable-in-a-shell-command[set the variable in a shell command].