---
contentTags:
  platform:
    - Server v4.4
    - Server Admin
---
= CircleCI server v4.4 release notes
:page-layout: classic-docs
:page-liquid:
:page-description: Details of the new features included in each CircleCI server v4.4 release.
:icons: font
:toc: macro
:toc-title:

[#overview]
== Overview

The v4.4 release introduces the following feature enhancements:

* xref:../../../openid-connect-tokens#[OpenID connect tokens]: CircleCI provides OpenID Connect ID (OIDC) tokens in environment variables. A job can be configured to use these tokens to access compatible cloud services without long-lived credentials being stored in CircleCI.
* link:https://circleci.com/changelog/machine-runner-3-0-released/[Machine runner 3.0]: Improved setup, usability and maintainability.
* xref:../../../container-runner-installation#enable-rerun-job-with-ssh[Rerun job with SSH option for container runners], in open preview.

For a full list of fixes, changes, new features and known issues, follow the links to individual change log posts below.

[#migration]
== Migrate

NOTE: The migration process for v3.x to v4.x requires that you install v4.0.x first before moving to subsequent releases. For existing customers interested in migrating from v3.x to v4.x, contact your customer success manager.

Find information about migration in the following guides:

* xref:../../installation/migrate-from-server-3-to-server-4#[Migrate from server v3 to v4 guide]
* xref:../../installation/migrate-from-server-2-to-server-4#[Migrate from server v2 to v4 guide]

[#upgrade]
== Upgrade
For upgrade steps see the xref:../installation/upgrade-server#[Upgrade server v4.4 guide].

[#release-4-4-1]
== Release 4.4.1

[#changelog-4-4-1]
=== Changelog

For full details of this release see the link:https://circleci.com/server/changelog/#server-release-4-4-1/[changelog].

[#release-4-4-0]
== Release 4.4.0

[#changelog-4-4-0]
=== Changelog

For full details of this release see the link:https://circleci.com/server/changelog/#server-release-4-4-0[changelog].
