---
description: "CircleCI Server’s VM service controls how machine executor (Linux and Windows images) and Remote Docker jobs are run."
version:
- Server v4.x
- Server Admin
---
= Manage virtual machines with VM Service
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

VM service controls how https://circleci.com/docs/2.0/configuration-reference/#machine[`machine`] executor and https://circleci.com/docs/2.0/building-docker-images[Remote Docker] jobs are run.

This section describes the available configuration options for VM service. Refer to the default `values.yaml` file for details on how to pre-scale virtual machines.

toc::[]

CAUTION: We recommend that you leave these options at their defaults until you have successfully configured and verified the core and build services of your server installation. Steps to set up VM service are provided in the installation guide for https://circleci.com/docs/2.0/server/installation/phase-3-execution-environments/#aws[AWS] and https://circleci.com/docs/2.0/server/installation/phase-3-execution-environments/#gcp[GCP].

WARNING: If https://circleci.com/docs/2.0/docker-layer-caching/[Docker Layer Caching (DLC)] is used, VM Service instances need to be spun up on demand. For this to happen, **either** ensure any preallocated instances are in use, **or** set both remote Docker and `machine` preallocated instance fields to `0`.

CAUTION: When using preallocated instances be aware that a cron job is scheduled to cycle through these instances once per day to ensure they do not end up in an unworkable state.

[#vm-provider]
== VM provider
The following configuration options are for the VM provider: either AWS or GCP.

[#aws]
=== AWS
There is a section in your `values.yaml` file that configures VM Service to work with AWS EC2. During installation you will have set up a security group and authentication. See the link:/docs/server/installation/phase-3-execution-environments/#aws-vm-service[Installation Phase 3 - Execution Environments] page for more information.

The informaiton in this section describes post-installation configuration options for VM service.

==== Windows image

==== Alternative Linux VM image

==== Instance preallocation

[#default-aws-ami-lists]
==== Default AWS AMI lists

The default AMIs for server v4.x are based on Ubuntu 22.04.

===== x86 AMI list

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Region
| AMI

| `us-east-1` 
| `ami-03dc54f7559144972`

| `ca-central-1`
| `ami-0575d605472840942`

| `ap-south-1` 
| `ami-047ef6196620f56ca`

| `ap-southeast-2`
| `ami-0521f8d70ef9dbd24`

| `ap-southeast-1`
| `ami-0ef0354f4eb3b7428`

| `eu-central-1`
| `ami-0a8286fff7b5ed33a`

| `eu-west-1`
| `ami-093618a1d0185f9e8`

| `eu-west-2`
| `ami-08f00d41b17d3ea0a`

| `sa-east-1`
| `ami-064b0bfe97e6ec04c`

| `us-east-2` 
| `ami-068cb131f91632f12`

| `us-west-1`
| `ami-0a4b7cf088a798be3`

| `us-west-2`
| `ami-018e05f98628cf5e5`

| `ap-northeast-1`
| `ami-06f32ec6aeecbeaa6`

| `ap-northeast-2`
| `ami-084c1abb1e8dabffd`

| `eu-west-3`
| `ami-09b3e24bccae3252f`

| `us-gov-east-1`
| `ami-0de525cac9ac9bea8`

| `us-gov-west-1` 
| `ami-02abf947586cae56b`
|===

[#arm-ami-list]
===== Arm AMI list

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Region
| AMI

|`us-east-1`
|`ami-0b11ce74f44e45578`

|`ca-central-1`
|`ami-07400e987dd82901d`

|`ap-south-1`
|`ami-072fe819d7b94b095`

|`ap-southeast-2`
|`ami-0510826f7f3a83b3e`

|`ap-southeast-1`
|`ami-0e5b703665f3e4517`

|`eu-central-1`
|`ami-045ea67b0f35ef1ef`

|`eu-west-1`
|`ami-044ac39c87438d89d`

|`eu-west-2`
|`ami-0a399817fbbb240e4`

|`sa-east-1`
|`ami-0ebc0e64fb943e191`

|`us-east-2`
|`ami-01f7dc2f8590b1611`

|`us-west-1`
|`ami-085fb1dd323aa02c7`

|`us-west-2`
|`ami-0e5ea38c131f05c8f`

|`ap-northeast-1`
|`ami-02c8fac0dbbbad74f`

|`ap-northeast-2`
|`ami-022e2eacee7328cca`

|`us-gov-east-1`
|`ami-0bb797dcfa52ce04d`

|`us-gov-west-1`
|`ami-0ab175883ff460b17`
|===

[#gcp]
=== GCP
There is a section in your `values.yaml` file that configures VM Service to work with GCP. During installation you will have set up a security group and authentication. See the link:/docs/server/installation/phase-3-execution-environments/#aws-vm-service[Installation Phase 3 - Execution Environments] page for more information. 

The informaiton in this section describes post-installation configuration options for VM service.

==== Windows image

==== Alternative Linux VM image

==== Instance preallocation