= Installing and Using Docker Compose
:page-platform: Cloud, Server v4+
:page-description: How to enable Docker Compose in your primary container
:experimental:

This page describes how to use Docker Compose in your CircleCI pipelines.

If you are new to Docker Compose, you can review the link:https://docs.docker.com/compose/[official Docker Compose overview], or checking out the link:https://docs.docker.com/compose/gettingstarted/[Getting Started guide].

[#using-docker-compose-with-machine-executor]
== Using Docker Compose with machine executor

If you want to use Docker Compose to manage a multi-container setup with a Docker Compose file, use the `machine` key in your `.circleci/config.yml` file and use `docker compose` as you would normally (see Linux VM execution environment documentation xref:using-linuxvm.adoc[here] for more details). That is, if you have a Docker Compose file that shares local directories with a container, this will work as expected.

[#using-docker-compose-with-docker-executor]
== Using Docker Compose with Docker executor

Using the `docker` execution environment combined with `setup_remote_docker` enables you to run Docker commands similarly to how you run Docker commands in a machine execution environment. However, volume mounting and port forwarding do *not* work the same way when using the `docker` execution environment. When using the `docker` execution environment with `setup_remote_docker`, a job's commands are executed in a container that has access to an external Docker daemon. Therefore, to use the Docker CLI or Docker Compose, you must move data around. Mounting can typically be solved by making content available in a Docker volume. It is possible to load data into a Docker volume by using `docker cp` to get the data from the CLI host into a location running on the Docker host.

== Install Docker Compose

The Docker Compose utility is xref:circleci-images#pre-installed-tools[pre-installed in the CircleCI convenience
images] and machine executor images.

If you are using the Docker executor and *are not* using a convenience image, you can install Docker Compose into your xref:reference:ROOT:glossary.adoc#primary-container[primary container] during the job execution and use the xref:building-docker-images.adoc[Remote Docker Environment], as follows:

[,yml]
----
      - run:
          name: Install Docker Compose
          command: |
            # Add Docker's official GPG key:
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc

            # Add the repository to Apt sources:
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install docker-ce-cli docker-buildx-plugin docker-compose-plugin

      - setup_remote_docker #activate the remote docker environment
----

If you are constructing your own Docker images, consider reading the
xref:custom-images.adoc[custom Docker images page].

Once you have Docker Compose installed, you can use it to build images and run containers:

[,yml]
----
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker compose build
----

Or to run the whole system:

[,yml]
----
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker compose up -d
----

Or to also verify if a service is running for example:

[,yml]
----
      - run:
          name: Start Docker Compose and verify service(s)
          command: |
            # Setting the Docker Compose project name to "circleci-demo-docker" means
            # the names of our services' containers would be prefixed with "circleci-demo-docker".
            docker compose --project circleci-demo-docker up -d

            # In this example, we have a "contacts" service, and
            # we are trying to check, via `dockerize`, if the service is ready.
            docker container run --network container:circleci-demo-docker_contacts_1 \
              docker.io/jwilder/dockerize \
              -wait http://localhost:8080/healthcheck \
              -wait-retry-interval 2s \
              -timeout 20s
----

[#example-project]
== Example project

See the link:https://github.com/circleci/cci-demo-docker/tree/docker-compose[Example Docker Compose Project] on GitHub for a demonstration and use the link:https://github.com/circleci/cci-demo-docker/blob/docker-compose/.circleci/config.yml[full configuration file] as a template for your own projects.

The primary container runs in a separate environment from Remote Docker and the two cannot communicate directly. To interact with a running service, run a container in the service's network.

[#limitations]
== Limitations

Using `docker compose` with the `macos` executor is not supported.
See link:https://support.circleci.com/hc/en-us/articles/360045029591-Can-I-use-Docker-within-the-macOS-executor-[our support article for more information].

[#see-also]
== See also

xref:building-docker-images.adoc[Running Docker Commands]
