= CircleCI remote Docker images support policy
:page-platform: Cloud, Server v4+
:page-description: CircleCI remote Docker images release, update, and deprecation policy
:experimental:

[#overview]
== Overview

This document outlines the xref:building-docker-images.adoc[CircleCI remote Docker image] release, update, and deprecation policy. This policy applies to all CircleCI remote Docker images built for the remote Docker feature (`setup_remote_docker`).

[#release-policy]
== Release policy

The CircleCI remote Docker images are based on our Linux VM images with Docker installed.
This setup enables the execution of Docker commands within jobs using the Docker executor in a remote environment.

We aim to support the latest three versions of the Docker Engine that are classified as within Security Support status.

Remote Docker images will be updated when a patch version is released upstream. Tags will be redirected to the updated images automatically as described in the xref:#tagging[tagging] section of this document. We will announce these releases on our link:https://discuss.circleci.com/[Discuss Forum].

[#tagging]
== Tagging

We support various tags for the remote Docker environment to allow you to choose the type of remote Docker environment you require.

For the latest major version of Docker:

- `default`: This image is the current stable image. Jobs will default to this if no tag is specified.

- `edge`: This tag is reserved for previews of new releases, which will initially point to this tag. The tag may include incremental updates relative to the current quarterly image release, which may change without notice, and is not recommended for production CI workloads.

For the previous major version of Docker, we support a single tag following the format of `dockerXX`, for example, `docker27` for Docker 27. This tag will point to the latest patch version of the major release, and will be updated if any patch versions are issued upstream. We recommend using the default version.

[#critical-cve-patches]
== Critical CVE patches

When critical CVEs are disclosed around the operating system or software stack of this image, we will investigate the impact this has on the image within the CircleCI execution environment. If customers are impacted by these CVEs we will push a patch fix to the released image(s), this image will supersede the original image. These patches will not include major OS updates. Patches will contain only patch OS updates.

[#bug-reports-issues-and-prs]
== Bug reports, issues, and PRs

You can file a link:https://support.circleci.com/hc/en-us/requests/new[support ticket] with CircleCI Support for any issues or bugs found with the remote Docker images. Our support team will be able to escalate issues internally to the correct engineering team and provide updates on the issue.

[#image-lifespan-eol]
== Image lifespan / EOL

Image lifespan will generally follow the support status of Docker Engine by Docker. Once a new major version of Docker is released, we will begin the deprecation process of the oldest version that we support and schedule it to be removed. This allows us to maintain three versions of Docker Engine effectively.

Current Deprecation:

[cols="1,2", options="header"]
|===
| Version
| Support

| Docker 25
| `docker25` tag is maintained for Docker 25 support

| Docker 26
| `docker26` tag is maintained for Docker 26 support

| Docker 27
| Set to `default` and `edge` tags. `docker27` tag is maintained for Docker 27 as default tag as well.
|===

Example: When Docker 28 is released:

We have delayed upgrading to Docker 28 because early releases introduced networking changes that caused instability in some environments.
Rather than risk disruption for our customers, we chose to stay on the stable and supported 27.x line while monitoring the maturity of 28.
With the release of 28.3.3, the previous issues appear to have been resolved.
We are now preparing to validate and roll out the upgrade to ensure a smooth transition.

[cols="1,2", options="header"]
|===
| Version
| Support

| Docker 25
| Deprecated and removed

| Docker 26
| `docker26` tag kept until next cycle

| Docker 27
| Moved from `default` and `edge` tags to `docker27` tag only

| Docker 28
| Set to `default` and `edge` tags. With `docker28` tag for pinning Docker version.
|===


When an image is selected for deprecation and removal, we will create an announcement on our Discuss forum and along with additional outreach where possible.

We will also plan brownouts to ensure users are aware of the approaching removal of deprecated images. Generally, we will aim to start an EOL process within 3 months of a new version release

[#exceptions]
== Exceptions

​​At any time, we reserve the right to work outside of the information in this document if the circumstances require. In the event that we are required to make an exception to the policy, we will aim to provide as much notice and clarity as possible. In these cases, an announcement will be posted on our Discuss Forum, along with additional outreach, such as an email notice, where possible.
