= Using the Arm VM execution environment
:page-platform: Cloud, Server v4+
:page-description: Learn how to configure a your jobs to run in the Arm VM execution environment.
:experimental:

You can access the Arm VM (virtual machine) execution environment for a job by using the machine executor and specifying a Linux virtual machine image that includes Arm resources. You then specify an Arm resource class.

[tabs]
====
Cloud::
+
--
[,yaml]
----
# .circleci/config.yml
jobs:
  my-job:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
----
--
Server::
+
--
[,yaml]
----
# .circleci/config.yml
jobs:
  my-job:
    machine:
      image: arm-default
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
----
--
====

[#available-resource-classes]
== Available resource classes

The following Arm resources are available as part of the xref:reference:ROOT:configuration-reference.adoc#available-linux-machine-images-cloud[`machine` executor]:

include::ROOT:partial$execution-resources/arm-resource-table.adoc[]

For pricing and plans information, see the link:https://circleci.com/product/features/resource-classes/[resource class pricing overview].

[#view-resource-usage]
=== View resource usage

include::ROOT:partial$execution-resources/resource-class-view.adoc[]

== Images with Arm support

Use the `machine` executor with a current Ubuntu LTS image that includes Arm. Match the Linux VM images listed in the xref:reference:ROOT:configuration-reference.adoc#available-linux-machine-images-cloud[Configuration Reference]:

* `ubuntu-2604:current`
* `ubuntu-2404:current`
* `ubuntu-2204:current`

For dated tags and image contents, see the link:https://circleci.com/developer/images?imageType=machine[CircleCI Developer Hub]. For image update announcements, see link:https://discuss.circleci.com/c/ecosystem/circleci-images/64[CircleCI Discuss].

Do not start new configurations on Ubuntu 20.04 (`ubuntu-2004`). That series is outside the xref:linux-vm-support-policy.adoc[Linux VM Images Support Policy] Gen2 set (22.04, 24.04, and 26.04).

[#limitations]
== Limitations

* Only 64-bit `arm64` architectures are supported.
* In CircleCI Server, Arm resources are only available when using the EC2 provider for VM service or machine provisioner. No Arm instances are available in GCP.
* If you run into issues with orbs, or if there is software you require that is not available in the image, link:https://circleci.canny.io/cloud-feature-requests[submit a feature request].

[#m1-mac-support]
=== M1 Mac support

Docker images built on M1 Macs, are by default, not compatible with the CircleCI standard platform. The `spin up environment` job in your pipelines will give you a green tick, but you will see the following message in the response:

[,shell]
----
WARNING: docker image ghcr.io/{your_username}/runner-test:latest targets wrong architecture (found arm64 but need [amd64 i386 386])
----

If you build an image on an M1 you need to specify `docker build --platform linux/amd64` as the default builds `arm64`.

[#arm-on-docker]
== Arm on Docker

For further information on using Arm with the Docker execution environment, see the xref:using-docker.adoc#arm[Using the Docker Execution Environment] page.
