version: 2.1

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false
  param3:
    type: boolean
    default: false
  param4:
    type: boolean
    default: true

jobs:
  test:
    docker:
      - image: cimg/node:19.0.1
    steps:
      - checkout
      - when:
          condition:
            and:
              - or:
                - and:
                  - equal: [ main, << pipeline.git.branch >> ]
                  - equal: [ false, << pipeline.parameters.param1 >> ]
                - not: << pipeline.parameters.param3 >>
              - or:
                - equal: [ false, << pipeline.parameters.param3 >> ]
                - or: [ << pipeline.parameters.param1 >>, << pipeline.parameters.param2 >> ]  
# The output of the nested logic statement will depend on the values of the pipeline parameters. This step will only run if the condition evaluates as true.
          steps:
            - run: echo "The condition evaluated as true"
