= Deploy over SSH
:page-platform: Cloud, Server v4+
:page-description: Learn how to deploy your application over SSH using CircleCI.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy your application over SSH.

[# add-ssh-key-target]
== 1. Add SSH key for target

Add the SSH key for the target to which you are deploying (these instructions are for cloud, server v3.x, and server v4.x).

. In a terminal, generate the key with `ssh-keygen -t ed25519 -C "your_email@example.com"`. See link:https://www.ssh.com/ssh/keygen/[Secure Shell documentation] for additional details.

. In the CircleCI application, go to your project's settings by clicking the **Project Settings** button (top-right on the **Pipelines** page of the project).

. On the **Project Settings** page, click on **SSH Keys**.

. Scroll down to the **Additional SSH Keys** section.

. Select **Add SSH Key**.

. In the **Hostname** field, enter the key's associated host (for example, `git.heroku.com`). If you do not specify a hostname, the key will be used for all hosts.

. In the **Private Key** field, paste the SSH key you are adding.

. Select **Add SSH Key**.

For additional context, see the xref:integration:add-ssh-key.adoc[Adding an SSH Key to CircleCI] page.

[#ssh-username-and-hostname]
== 2. Add the SSH username and hostname

Add the SSH username and SSH hostname of your build VM as environment variables. For instructions, see the xref:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[Set an environment variable in a project] page. In this example, these variables are defined as `SSH_USER` and `SSH_HOST`, respectively.

[#create-deploy-job]
== 3. Create a deploy job

In your `.circleci/config.yml`, create a `deploy` job and add a command to deploy the main branch.

```yaml
version: 2.1

jobs:
  build:
  #...
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
```

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

Deploy markers provide a way to track and manage your SSH deployments in the CircleCI web app. When you add deploy markers to your deployment job, you can view a timeline of all deployments, track their status, and enable rollback and deploy pipelines.

You have two options for setting up deploy markers:

* *In-app setup*: Use the guided setup in the CircleCI web app when configuring a xref:set-up-rollbacks.adoc[rollback pipeline] or xref:set-up-deploys.adoc[deploy pipeline]. The setup will walk you through adding deploy markers to your configuration. If you are using GitHub and have the CircleCI GitHub app installed, you can use AI to generate the deploy marker configuration automatically.

* *Manual setup*: Add deploy marker commands directly to your `.circleci/config.yml` file by following the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

Both approaches will enable you to track deployment history and manage rollbacks directly from the CircleCI web app.
