=  Deploy to Google Cloud Platform
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Google Cloud Platform.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to Google Cloud Platform.

[#introduction]
== Introduction

Before deploying to Google Cloud Platform, you will need to authorize the Google Cloud SDK and set default configuration settings. Refer to the xref:integration:authorize-google-cloud-sdk.adoc[Authorizing the Google Cloud SDK] page for full details.

In addition to the orbs described below, CircleCI has created an GCP convenience image focusing on, link:https://circleci.com/developer/images/image/cimg/gcp[deployment: `cimg/gcp`].

[#using-google-cloud-orbs]
== Using Google Cloud orbs

Several Google Cloud orbs are available in the link:https://circleci.com/developer/orbs[CircleCI Orbs Registry]. Use the orbs to simplify your deployments. For example, the link:https://circleci.com/developer/orbs/orb/circleci/gcp-gke#usage-publish-and-rollout-image[Google Kubernetes Engine (GKE) orb] has a pre-built job to build and publish a Docker image, and roll the image out to a GKE cluster, as follows:

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1

orbs:
  gke: circleci/gcp-gke@x.y.z # Use the GCP GKE orb in your config

workflows:
  main:
    jobs:
      - gke/publish-and-rollout-image:
          cluster: <your-GKE-cluster> # name of GKE cluster to be created
          container: <your-K8-container-name> # name of your Kubernetes container
          deployment: <your-K8-deployment-name> # name of your Kubernetes deployment
          image: <your-image> # name of your Docker image
          tag: $CIRCLE_SHA1 # Docker image tag - optional
```

[#deployment-to-gke-with-2-configuration]
== Deployment to GKE without orbs

In the following example, if the `build-job` passes and the current branch is `main`, CircleCI runs the deployment job.

```yml
version: 2.1

jobs:
  # build job omitted for brevity
  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy Main to GKE
          command: |
            # Push Docker image to registry, update K8s deployment to use new image - `gcloud` command handles authentication and push all at once
            sudo /opt/google-cloud-sdk/bin/gcloud docker push us.gcr.io/${PROJECT_NAME}/hello
            # The new image is now available in GCR for the GCP infrastructure to access, next, change permissions:
            sudo chown -R ubuntu:ubuntu /home/ubuntu/.kube
            # Use `kubectl` to find the line that specifies the image to use for our container, replace with image tag of the new image.
            # The K8s deployment intelligently upgrades the cluster by shutting down old containers and starting up-to-date ones.
            kubectl patch deployment docker-hello-google -p '{"spec":{"template":{"spec":{"containers":[{"name":"docker-hello-google","image":"us.gcr.io/circle-ctl-test/hello:'"$CIRCLE_SHA1"'"}]}}}}'

workflows:
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job # Only deploy once the build job has completed
          filters:
            branches:
              only: main # Only deploy on the main branch
```

For another example, see our link:https://github.com/CircleCI-Public/circleci-demo-k8s-gcp-hello-app[CircleCI Google Cloud deployment example project].

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Google Cloud Platform deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers work with all GCP deployment types including GKE, Cloud Run, and App Engine.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-gcp-deployment]
=== Add deploy markers to your GCP deployment

To add deploy markers to your GCP deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup for a GKE deployment:

[source,yaml]
----
jobs:
  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Plan deployment
          command: |
            circleci run release plan gke-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production" \
              --component-name="my-gcp-app"
      - run:
          name: Deploy Main to GKE
          command: |
            sudo /opt/google-cloud-sdk/bin/gcloud docker push us.gcr.io/${PROJECT_NAME}/hello
            sudo chown -R ubuntu:ubuntu /home/ubuntu/.kube
            kubectl patch deployment docker-hello-google -p '{"spec":{"template":{"spec":{"containers":[{"name":"docker-hello-google","image":"us.gcr.io/circle-ctl-test/hello:'"$CIRCLE_SHA1"'"}]}}}}'
      - run:
          name: Update deployment status
          command: circleci run release update gke-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update gke-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update gke-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your GCP deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your GCP application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Google Cloud Platform deployments.
