= Deploy to npm registry
:page-platform: Cloud, Server v4+
:page-description: Learn how to deploy packages to the npm registry using CircleCI.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to publish to the npm registry.

[#introduction]
== Introduction

Setting up CircleCI to publish packages to the npm registry enabling project collaborators to release new package versions in a consistent and predictable way.

[#obtain-the-npm-authToken]
== 1. Get the npm `authToken`

Get the npm `authToken` for the account that you wish to use to publish the package. You can do this by logging in to npm (`npm login`). This will save the `authToken` to the `~/.npmrc` file. Look for the following line:

```shell
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```

In this case, the `authToken` is `00000000-0000-0000-0000-000000000000`.

[#set-npm-token]
== 2. Set npm token
Go to your xref:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[project settings], and set the `NPM_TOKEN` variable to the obtained `authToken`.

[#configure-circleci]
== 3. Configure CircleCI

Configure CircleCI to add the `authToken` to `~/.npmrc`, run `npm publish` and only for versioned tags:

```yaml
version: 2.1

jobs:
  publish:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
```

[#create-new-version]
== 4. Create a new version

When you want to publish a new version to npm, run `npm version` to create a new version:

```shell
npm version 10.0.1
```

This will update the `package.json` file and creates a tagged Git commit. Next, push the commit with tags:

```shell
git push --follow-tags
```
[#publish]
== 5. Publish

If tests passed, CircleCI will publish the package to npm automatically.

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your npm registry deployment, you can add deploy markers to track and manage your package publications in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-npm-deployment]
=== Add deploy markers to your npm deployment

To add deploy markers to your npm deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  publish:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            VERSION=$(node -p "require('./package.json').version")
            circleci run release plan npm-deploy \
              --target-version="$VERSION" \
              --environment-name="production" \
              --component-name="my-npm-package"
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
      - run:
          name: Update deployment status
          command: circleci run release update npm-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update npm-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update npm-deploy --status=FAILED
          when: on_fail

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your npm registry deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your npm package
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your npm package publications.
