= Deploy to Artifactory
:page-platform: Cloud, Server v4+
:page-description: How to upload artifacts to Artifactory in CircleCI
:experimental:

In this how-to guide, you will learn how to upload artifacts to Artifactory in CircleCI.

[#introduction]
== Introduction

Artifactory has documentation explaining how to use their link:https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API[REST API].

Below are some sample projects showing how to best use CircleCI and Artifactory together. Ensure that you have created your repository before starting this example, otherwise CircleCI will not have a place to store your dependencies.

[#artifactory-plugins]
== Artifactory plugins

Popular tools like Maven and Gradle have Artifactory plugins, and can deploy to Artifactory using their respective deploy commands.

* link:https://jfrog.com/help/r/jfrog-integrations-documentation/ecosystem-integration-maven-artifactory-plugin[Deploying with Maven]
* link:https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin[Deploying with Gradle]

[#jfrog-cli]
== JFrog CLI

If you want to use the link:https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli[JFrog CLI], you can install it by following the steps below.

[#add-jfrog-to-your-configuration]
=== 1. Add JFrog to your configuration

You can install JFrog CLI in one of a few ways. Refer to the link:https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/install#installation[JFrog documentation]. for the method best suited for your pipeline.

For example, if using Node, add the following to your `.circleci/config.yml`:

[,yml]
----
- run:
    name: Install jFrog CLI
    command: npm install -g jfrog-cli-v2-jf
----

[#configure-credentials]
=== 2. Configure credentials

Now you need to configure JFrog to use CircleCI credentials securely. CircleCI configures the client to use `$ARTIFACTORY_URL`, along with `$ARTIFACTORY_USER` and `$ARTIFACTORY_APIKEY`. These can be entered under `+Project Settings->Environment Variables+`. Configure the CLI to use these settings:

[,yml]
----
- run: ./jf config add <named_server_config> --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_APIKEY --interactive=false
----

[#upload-jar-files]
=== 3. Upload JAR files (optional)

If you would like to upload JAR files use the following example:

[,yml]
----
command: |
  ./jf mvnc \
    --server-id-resolve <server_id> \
    --server-id-deploy <server_id> \
    --repo-resolve-releases libs-release \
    --repo-resolve-snapshots libs-snapshot \
    --repo-deploy-releases release-candidates \
    --repo-deploy-snapshots snapshots \
    --include-patterns "*.jar, *.pom, *.xml"

  ./jf mvn clean install
----


[#upload-war-files]
=== 4. Upload WAR files (optional)

If you would like to upload WAR files use the following example:

[,yml]
----
command: |
  ./jf mvnc \
    --server-id-resolve <server_id> \
    --server-id-deploy <server_id> \
    --repo-resolve-releases libs-release \
    --repo-resolve-snapshots libs-snapshot \
    --repo-deploy-releases release-candidates \
    --repo-deploy-snapshots snapshots \
    --include-patterns "*.war"

  ./jf mvn clean install
----

[#full-configuration-example]
== Full configuration example

The full `.circleci/config.yml` file would look something like the following:

include::ROOT:partial$notes/docker-auth.adoc[]

[,yml]
----
version: 2.1
jobs:
  create-build-package:
    docker:
      - image: cimg/openjdk:17.0.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io/v2-jf | sh
      - run:
          name: Configure JFrog Creds
          command: |
            ./jf c add <server_id> \
              --artifactory-url $ARTIFACTORY_URL \
              --user $ARTIFACTORY_USER \
              --password $ARTIFACTORY_APIKEY \
              --interactive=false
      - run:
          name: Maven Build
          command: |
            ./jf mvnc \
              --server-id-resolve <server_id> \
              --server-id-deploy <server_id> \
              --repo-resolve-releases libs-release \
              --repo-resolve-snapshots libs-snapshot \
              --repo-deploy-releases release-candidates \
              --repo-deploy-snapshots snapshots \
              --include-patterns "*.jar, *.pom, *.xml"

            ./jf mvn clean install

workflows:
  build:
    jobs:
      - create-build-package:
          context: artifactory
----

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Artifactory deployment, you can add deploy markers to track and manage your artifact uploads in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-artifactory-deployment]
=== Add deploy markers to your Artifactory deployment

To add deploy markers to your Artifactory deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  create-build-package:
    docker:
      - image: cimg/openjdk:17.0.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan artifactory-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production" \
              --component-name="my-artifact"
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io/v2-jf | sh
      - run:
          name: Configure JFrog Creds
          command: |
            ./jf c add <server_id> \
              --artifactory-url $ARTIFACTORY_URL \
              --user $ARTIFACTORY_USER \
              --password $ARTIFACTORY_APIKEY \
              --interactive=false
      - run:
          name: Maven Build and Deploy
          command: |
            ./jf mvnc \
              --server-id-resolve <server_id> \
              --server-id-deploy <server_id> \
              --repo-resolve-releases libs-release \
              --repo-resolve-snapshots libs-snapshot \
              --repo-deploy-releases release-candidates \
              --repo-deploy-snapshots snapshots \
              --include-patterns "*.jar, *.pom, *.xml"
            ./jf mvn clean install
      - run:
          name: Update deployment status
          command: circleci run release update artifactory-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update artifactory-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update artifactory-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your Artifactory deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your artifacts
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Artifactory deployments.

[#see-also]
== See also

* xref:optimize:artifacts.adoc[Storing and Accessing Artifacts]
* link:https://circleci.com/circleci-and-jfrog/[CircleCI and JFrog]
