= Deploy to npm registry
:page-platform: Cloud, Server v4+
:page-description: Learn how to deploy packages to the npm registry using CircleCI.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to publish to the npm registry.

[#introduction]
== Introduction

Setting up CircleCI to publish packages to the npm registry enabling project collaborators to release new package versions in a consistent and predictable way.

[#obtain-the-npm-authToken]
== 1. Get the npm `authToken`

Get the npm `authToken` for the account that you wish to use to publish the package. You can do this by logging in to npm (`npm login`). This will save the `authToken` to the `~/.npmrc` file. Look for the following line:

```shell
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```

In this case, the `authToken` is `00000000-0000-0000-0000-000000000000`.

[#set-npm-token]
== 2. Set npm token
Go to your xref:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[project settings], and set the `NPM_TOKEN` variable to the obtained `authToken`.

[#configure-circleci]
== 3. Configure CircleCI

Configure CircleCI to add the `authToken` to `~/.npmrc`, run `npm publish` and only for versioned tags:

```yaml
version: 2.1

jobs:
  publish:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
```

[#create-new-version]
== 4. Create a new version

When you want to publish a new version to npm, run `npm version` to create a new version:

```shell
npm version 10.0.1
```

This will update the `package.json` file and creates a tagged Git commit. Next, push the commit with tags:

```shell
git push --follow-tags
```
[#publish]
== 5. Publish

If tests passed, CircleCI will publish the package to npm automatically.

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

Deploy markers provide a way to track and manage your npm package publications in the CircleCI web app. When you add deploy markers to your deployment job, you can view a timeline of all deployments, track their status, and enable rollback and deploy pipelines.

You have two options for setting up deploy markers:

* *In-app setup*: Use the guided setup in the CircleCI web app when configuring a xref:set-up-rollbacks.adoc[rollback pipeline] or xref:set-up-deploys.adoc[deploy pipeline]. The setup will walk you through adding deploy markers to your configuration. If you are using GitHub and have the CircleCI GitHub app installed, you can use AI to generate the deploy marker configuration automatically.

* *Manual setup*: Add deploy marker commands directly to your `.circleci/config.yml` file by following the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

Both approaches will enable you to track deployment history and manage rollbacks directly from the CircleCI web app.
