= Deploy to Capistrano
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Capistrano.
:experimental:

This how-to guide covers an example CircleCI configuration to deploy to Capistrano.

[#introduction]
== Introduction

This page provides a configuration example for deployment to Capistrano. Once your project is set up to use Capistrano, you can run link:https://github.com/capistrano/capistrano/blob/master/README.md#command-line-usage[deployment commands] within your CircleCI job as required.

[#configuration-example]
== Configuration example

```yaml
version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job # Only run deploy job once build job has completed
          filters:
            branches:
              only: main # Only run deploy job when commit is on the main branch

jobs:
  #  build and test jobs go here - not included for brevity
  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy if tests pass and branch is Main
          command: bundle exec cap production deploy
```

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Capistrano deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-capistrano-deployment]
=== Add deploy markers to your Capistrano deployment

To add deploy markers to your Capistrano deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan capistrano-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production"
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy if tests pass and branch is Main
          command: bundle exec cap production deploy
      - run:
          name: Update deployment status
          command: circleci run release update capistrano-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update capistrano-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update capistrano-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your Capistrano deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Capistrano deployments.
