= Deploy to Azure Container Registry
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Azure Container Registry.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to Azure Container Registry.

[#introduction]
== Introduction

This page describes a simple deployment to the Azure Container Registry (ACR) using the CircleCI ACR orb and `version 2.1` configuration.

include::ROOT:partial$tips/env-var-or-context.adoc[]

In addition to the orb described below, CircleCI has created an Azure convenience image focusing on link:https://circleci.com/developer/images/image/cimg/azure[deployment: `cimg/azure`].


For detailed information about the Azure ACR orb, including all options, refer to the link:https://circleci.com/developer/orbs/orb/circleci/azure-acr[CircleCI ACR Orb Reference] page.

[#provide-env-vars]
== 1. Provide environment variables to CircleCI

Whether your require a user or service principal login, you will need to provide environment variables for username, password and tenant to CircleCI. For user logins use environment variable names as follows:

* `AZURE_USERNAME`
* `AZURE_PASSWORD`
* `AZURE_TENANT`

For service principal logins use:

* `AZURE_SP`
* `AZURE_SP_PASSWORD`
* `AZURE_SP_TENANT`

[#deploy-to-acr]
== 2. Deploy to ACR

Use the orb's `build-and-push-image` job to build your image and deploy it to ACR. Note the use of workflows to deploy only if the current branch is `main`.

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

orbs:
  azure-acr: circleci/azure-acr@0.2.2 # Use the Azure ACR orb in your config

workflows:
  build-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          dockerfile: <name-of-your-dockerfile> # defaults to `Dockerfile`
          path: <path-to-your-dockerfile> # Defaults to working directory
          login-server-name: <your-login-server-name> # e.g. {yourregistryname}.azure.io
          registry-name: <your-ACR-registry-name>
          repo: <URI-to-your-login-server-name>
          filters:
            branches:
              only: main # Only deploys when the commit is on the `main` branch
```

If pushing to your repository is required, see the xref:permissions-authentication:users-organizations-and-integrations-guide.adoc#enable-project-to-check-out-additional-private-repositories[Users, Organizations, and Integrations Guide]. Then, configure the Azure Web App to use your production branch.

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Azure Container Registry deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-azure-deployment]
=== Add deploy markers to your Azure deployment

To add deploy markers to your Azure Container Registry deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.2

jobs:
  deploy-with-markers:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan azure-acr-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production" \
              --component-name="my-azure-app"
      - azure-acr/build-and-push-image:
          dockerfile: <name-of-your-dockerfile>
          path: <path-to-your-dockerfile>
          login-server-name: <your-login-server-name>
          registry-name: <your-ACR-registry-name>
          repo: <URI-to-your-login-server-name>
      - run:
          name: Update deployment status
          command: circleci run release update azure-acr-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update azure-acr-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update azure-acr-deploy --status=FAILED
          when: on_fail

workflows:
  build-deploy:
    jobs:
      - deploy-with-markers:
          filters:
            branches:
              only: main
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your Azure Container Registry deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your Azure application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Azure Container Registry deployments.
