= Deploy to Heroku
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Heroku.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to Heroku.

[#introduction]
== Introduction

link:https://www.heroku.com/[Heroku] is a popular platform for hosting applications in the cloud. To configure CircleCI to deploy your application to Heroku, follow the steps below.

== Using the Heroku orb

[#create-account]
=== 1. Create an account

Create a Heroku account and follow the link:https://devcenter.heroku.com/start[Getting Started on Heroku] documentation to set up a project in your chosen language.

[#create-env-vars]
=== 2. Create environment variables

Add the name of your Heroku application and your Heroku API key as environment variables as `HEROKU_APP_NAME` and `HEROKU_API_KEY`, respectively.

include::ROOT:partial$tips/env-var-or-context.adoc[]

[#deploy-with-orb]
=== 3. Deploy with the Heroku orb

Use the link:https://circleci.com/developer/orbs/orb/circleci/heroku[Heroku orb] to keep your configuration simple. The `deploy-via-git` installs the Heroku CLI in the primary container, runs any pre deployment steps you define, deploys your application, then runs any post-deployment steps you define. See the Heroku orb page in the link:https://circleci.com/developer/orbs/orb/circleci/heroku[orbs registry] for full details of parameters and options:

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1
orbs:
  heroku: circleci/heroku@x.y
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: your-database-migration-command #example of a post-deployment step
          pre-steps:
            - run: command-that-run-before-deploying #example of a pre-deployment step

```

For more detailed information about these Heroku orbs, refer to the link:https://circleci.com/developer/orbs/orb/circleci/heroku[CircleCI Heroku Orb].

== Deploy without the Heroku orb

[#create-account-2]
=== 1. Create an account

Create a Heroku account and follow the link:https://devcenter.heroku.com/start[Getting Started on Heroku] documentation to set up a project in your chosen language.

[#create-env-vars-2]
=== 2. Create environment variables

Add the name of your Heroku application and your Heroku API key as environment variables as `HEROKU_APP_NAME` and `HEROKU_API_KEY`, respectively.

include::ROOT:partial$tips/env-var-or-context.adoc[]

[#create-deploy-job]
=== 3. Create deploy job

In your `.circleci/config.yml`, create a `deploy` job and add an xref:execution-managed:executor-intro.adoc[executor type].

[#add-steps-deploy-job]
=== 4. Add steps to your deploy job

Add `steps` to your `deploy` job to checkout and deploy your code. You can specify which branch you would like to deploy. The example below specifies the main branch, and deploys using a `git push` command.

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      # Additional steps omitted for brevity
  deploy:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: main # only run deploy-via-git job on main branch
```

NOTE: Heroku provides the option "Wait for CI to pass before deploy" under deploy / automatic deploys. See the link:https://devcenter.heroku.com/articles/github-integration#automatic-deploys[Heroku documentation] for details.

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Heroku deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-heroku-deployment]
=== Add deploy markers to your Heroku deployment

To add deploy markers to your Heroku deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  deploy:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan heroku-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production"
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
      - run:
          name: Update deployment status
          command: circleci run release update heroku-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update heroku-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update heroku-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your Heroku deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your Heroku application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Heroku deployments.
