= Deploy over SSH
:page-platform: Cloud, Server v4+
:page-description: Learn how to deploy your application over SSH using CircleCI.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy your application over SSH.

[# add-ssh-key-target]
== 1. Add SSH key for target

Add the SSH key for the target to which you are deploying (these instructions are for cloud, server v3.x, and server v4.x).

. In a terminal, generate the key with `ssh-keygen -t ed25519 -C "your_email@example.com"`. See link:https://www.ssh.com/ssh/keygen/[Secure Shell documentation] for additional details.

. In the CircleCI application, go to your project's settings by clicking the **Project Settings** button (top-right on the **Pipelines** page of the project).

. On the **Project Settings** page, click on **SSH Keys**.

. Scroll down to the **Additional SSH Keys** section.

. Select **Add SSH Key**.

. In the **Hostname** field, enter the key's associated host (for example, `git.heroku.com`). If you do not specify a hostname, the key will be used for all hosts.

. In the **Private Key** field, paste the SSH key you are adding.

. Select **Add SSH Key**.

For additional context, see the xref:integration:add-ssh-key.adoc[Adding an SSH Key to CircleCI] page.

[#ssh-username-and-hostname]
== 2. Add the SSH username and hostname

Add the SSH username and SSH hostname of your build VM as environment variables. For instructions, see the xref:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[Set an environment variable in a project] page. In this example, these variables are defined as `SSH_USER` and `SSH_HOST`, respectively.

[#create-deploy-job]
== 3. Create a deploy job

In your `.circleci/config.yml`, create a `deploy` job and add a command to deploy the main branch.

```yaml
version: 2.1

jobs:
  build:
  #...
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
```

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your SSH deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-ssh-deployment]
=== Add deploy markers to your SSH deployment

To add deploy markers to your SSH deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan ssh-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production" \
              --component-name="my-app"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
      - run:
          name: Update deployment status
          command: circleci run release update ssh-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update ssh-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update ssh-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your SSH deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your SSH deployments.
