= Deploy to Firebase
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Firebase.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to Firebase.

[#introduction]
== Introduction

This page provides a configuration for deployment to Firebase. In order to deploy to Firebase you will need to add `firebase-tools` to your project's `devDependencies` since attempting to install `firebase-tools` globally in CircleCI will not work.

[#install-firebase-tools]
== 1. Install tools

[source,shell]
----
npm install --save-dev firebase-tools
----

[#authenticate-with-a-service-account]
== 2. Authenticate with a service account

If you have not already done so, link:https://cloud.google.com/iam/docs/service-accounts-create[create a Google Cloud service account] with the appropriate access for the deploy job.

Then, link:https://cloud.google.com/docs/authentication/provide-credentials-adc#wlif-key[create a service account key]. You may store the key file contents in your project's environment variables (in this guide, we name the project environment variable `$SA_KEY`). Refer to the xref:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[Set an environment variable in a project] guide for instructions. CircleCI will use this credential to authenticate with Firebase.

include::ROOT:partial$tips/env-var-or-context.adoc[]

NOTE: Review the link:https://cloud.google.com/iam/docs/best-practices-for-managing-service-account-keys[Google IAM documentation] for best practices in managing service account keys.

[#add-token-to-project-env-vars]
== 3. Declare environment variable inside `run` step

. Inside a `run` step, output the value of the environment variable, that is, the contents of the service account key file, to a JSON file.

. Set the JSON file path as the value of an environment variable `$GOOGLE_APPLICATION_CREDENTIALS` xref:security:env-vars.adoc#order-of-precedence[declared in the shell]. Then, run the Firebase deploy command.

[source,yaml]
----
    - run:
        name: Deploy on Firebase
        command: |
          echo $SA_KEY > credentials.json
          GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy
----

To learn more about how Google finds application credentials, refer to the link:https://cloud.google.com/docs/authentication/application-default-credentials#GAC[documentation for Google Cloud authentication].

[#deploy-example]
== Deploy example

The following example shows how you can add a Firebase deploy job to your project's `.circleci/config.yml` file. This snippet assumes you already have a job to build your application, called `build-job`, and introduces a deployment workflow that only runs the deployment job once the build job has completed **and** you are on the main branch.

[source,yaml]
----
version: 2.1

jobs:
  build-job:
    docker: # Specify executor for running build-job - this example uses a Docker container
      - image: <docker-image-name-tag> # Specify docker image to use
    steps:
      # steps omitted for brevity

  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy on Firebase
          command: |
            echo $SA_KEY > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy

workflows:
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main

----

[#google-cloud-functions]
== Google Cloud Functions

If you are using Google Cloud Functions with Firebase, instruct CircleCI to navigate to the folder where the Google Cloud Functions are held (in this case 'functions') and run `npm install` by adding the below to `.circleci/config.yml`:

[source,yaml]
----
    - run: cd functions && npm install
----

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your Firebase deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-firebase-deployment]
=== Add deploy markers to your Firebase deployment

To add deploy markers to your Firebase deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup:

[source,yaml]
----
jobs:
  deploy-job:
    docker:
      - image: <docker-image-name-tag>
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan firebase-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production"
      - run:
          name: Deploy on Firebase
          command: |
            echo $SA_KEY > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy
      - run:
          name: Update deployment status
          command: circleci run release update firebase-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update firebase-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update firebase-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your Firebase deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your Firebase application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your Firebase deployments.
