= Deploy to AWS
:page-platform: Cloud, Server v4+
:page-description: This is document provides examples of deploying to Amazon Web Services.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to Amazon Web Services.

[#introduction]
== Introduction

This page covers deployment to S3, ECR/ECS (Elastic Container Registry/Elastic Container Service), as well as application deployment using AWS Code Deploy.

For more detailed information about the AWS S3, ECS, ECR, and CodeDeploy orbs, refer to the following orb registry pages:

* link:https://circleci.com/developer/orbs/orb/circleci/aws-s3[AWS S3]
* link:https://circleci.com/developer/orbs/orb/circleci/aws-ecr[AWS ECR]
* link:https://circleci.com/developer/orbs/orb/circleci/aws-ecs[AWS ECS]
* link:https://circleci.com/developer/orbs/orb/circleci/aws-code-deploy[AWS CodeDeploy]

In addition to the orb described below, CircleCI has created an AWS convenience image focusing link:https://circleci.com/developer/images/image/cimg/aws[deployment: `cimg/aws`].

[#deploy-to-s3-using-the-aws-s3-orb]
== Deploy to S3 using the AWS S3 orb

For detailed information about the AWS S3 orb, refer to the link:https://circleci.com/developer/orbs/orb/circleci/aws-s3[CircleCI AWS S3 Orb Reference] page. This section details the use of the AWS S3 orb and `version: 2.1` configuration for simple deployment, below we will look at the same example without orbs and using `version: 2` configuration.

[#create-iam-user]
=== 1. Create IAM user

For security best practice, create a new link:https://aws.amazon.com/iam/details/manage-users/[IAM user] specifically for CircleCI.

[#add-aws-access-keys]
=== 2. Add AWS access keys

Add your link:https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys[AWS access keys] to CircleCI – store your Access Key ID in a variable called `AWS_ACCESS_KEY_ID` and your Secret Access Key in a variable called `AWS_SECRET_ACCESS_KEY`.

[#deploy-using-orb]
=== 3. Deploy using orb

Use the orb's `sync` command to deploy. Note the use of workflows to deploy only if the `build` job passes and the current branch is `main`.

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@4.1.0 # use the AWS S3 orb in your configuration

workflows: # Define a Workflow running the build job, then the deploy job
  build-deploy: # Make a workflow to build and deploy your project
    jobs:
      - build
      - deploy:
          requires:
            - build # Only run deploy job once the build job has completed
          filters:
            branches:
              only: main # Only deploy when the commit is on the Main branch

jobs: # Define the build and deploy jobs
  build:
    docker: # Use the Docker executor for the build job
      - image: <image-name-and-tag> # Specify the Docker image to use for the build job
    steps:
      - checkout # build job steps omitted for brevity
  deploy:
    docker: # Use the Docker executor for the deploy job
      - image: <image-name-and-tag>  # Specify the Docker image to use for the deploy job
    steps:
      - checkout
      - aws-s3/sync:
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
```

[#deploy-to-aws-s3-without-orbs]
== Deploy to S3 without orbs

[#create-iam-user-2]
=== 1. Create IAM user

For security best practice, create a new link:https://aws.amazon.com/iam/details/manage-users/[IAM user] specifically for CircleCI.

[#add-aws-access-keys-2]
=== 2. Add AWS access keys

Add your link:https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys[AWS access keys] to CircleCI – store your Access Key ID in a variable called `AWS_ACCESS_KEY_ID` and your Secret Access Key in a variable called `AWS_SECRET_ACCESS_KEY`.

[#create-deploy-job]
=== 3. Create deploy job

In your `.circleci/config.yml` file, create a new `deploy` job. In the `deploy` job, add a step to install `awscli` in your primary container.

[#install-awscli]
=== 4. Install the AWS CLI

Install `awscli` in your primary container by following the link:https://docs.aws.amazon.com/cli/latest/userguide/installing.html[AWS CLI documentation].

[#deploy-awscli]
=== 5. Deploy with the AWS CLI

link:https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-using.html[Use the AWS CLI] to deploy your application to S3 or perform other AWS operations. Note the use of workflows to deploy only if the build job passes and the current branch is `main`.

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1

workflows: # Define a Workflow running the build job, then the deploy job
    build-deploy:
    jobs:
        - build
        - deploy:
            requires:
            - build
            filters:
            branches:
                only: main # Only deploys when the commit is on the Main branch

jobs:
    build:
    docker: # Specify executor for running build job - this example uses a Docker container
        - image: <docker-image-name-tag> # Specify docker image to use
    ... # build job steps omitted for brevity
    deploy:
    docker: # Specify executor for running deploy job
        - image: <docker-image-name-tag> # Specify docker image to use
    steps:
        - run: # Install the AWS CLI if it is not already included in the docker image
            name: Install awscli
            command: sudo pip install awscli
        - run: # Deploy to S3 using the sync command
            name: Deploy to S3
            command: aws s3 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>
```

For a complete list of AWS CLI commands and options, see the link:https://docs.aws.amazon.com/cli/latest/reference/[AWS CLI Command Reference].

[#deploy-docker-image-to-aws-ecr]
== Deploy Docker image to AWS ECR

The AWS ECR orb enables you to log into AWS, build, and then push a Docker image to AWS Elastic Container Registry with minimal config. See the link:https://circleci.com/developer/orbs/orb/circleci/aws-ecr[orb registry page] for a full list of parameters, jobs, commands and options.

Using the `build_and_push_image` job (shown below) requires the following environment variables to be set: `AWS_ECR_ACCOUNT_URL`, `ACCESS_KEY_ID`, `SECRET_ACCESS_KEY`, `AWS_DEFAULT_REGION`.

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.7 # Use the AWS ECR orb in your configuration
  aws-cli: circleci/aws-cli@5.1.2 # Use the AWS CLI orb in your configuration

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image: # Use the pre-defined `build-and-push-image` job
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          dockerfile: <my-Docker-file>
          path: <path-to-my-Docker-file>
          profile_name: <my-profile-name>
          repo: <my-ECR-repo>
          tag: <my-ECR-repo-tag> # default - latest
```

[#update-an-aws-ecs-instance]
== Update an AWS ECS instance

Use the link:https://circleci.com/developer/orbs/orb/circleci/aws-ecr[AWS ECR] and link:https://circleci.com/developer/orbs/orb/circleci/aws-ecs[ECS] orbs to update an existing AWS ECS instance.

Using the `build-and-push-image` job (shown below) requires the following environment variables to be set: `OIDC-USER`, `AWS__DEFAULT_REGION`, `MY_APP_PREFIX`.

include::ROOT:partial$tips/add-version-number.adoc[]

```yaml
version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@5.1.2
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-ecs: circleci/aws-ecs@6.0.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: arn:aws:iam::123456789012:role/VALID_OIDC_ECR_ROLE
          profile_name: OIDC-USER
          repo: MY_APP_PREFIX
          tag: CIRCLE_SHA1 # This is a built-in environment variable
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: arn:aws:iam::123456789012:role/VALID_OIDC_ECS_ROLE
          cluster: MY_APP_PREFIX-cluster
          container_image_name_updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: MY_APP_PREFIX-service
          profile_name: OIDC-USER
          requires:
            - aws-ecr/build_and_push_image

```

[#aws-codedeploy]
== AWS CodeDeploy

The link:https://circleci.com/developer/orbs/orb/circleci/aws-code-deploy[AWS CodeDeploy] orb enables you to run deployments through AWS CodeDeploy. See the example in the developer hub to get started.

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your AWS deployment, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers work with all AWS deployment types including S3, ECR, ECS, and CodeDeploy.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-aws-deployment]
=== Add deploy markers to your AWS deployment

To add deploy markers to your AWS deployment job, add the `circleci run release` commands to your deployment workflow. The following example shows a basic deployment marker setup for an S3 deployment:

[source,yaml]
----
jobs:
  deploy:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Plan deployment
          command: |
            circleci run release plan aws-s3-deploy \
              --target-version="${CIRCLE_SHA1:0:7}" \
              --environment-name="production" \
              --component-name="my-app"
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>
      - run:
          name: Update deployment status
          command: circleci run release update aws-s3-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update aws-s3-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update aws-s3-deploy --status=FAILED
          when: on_fail
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your AWS deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your AWS application
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your AWS deployments across all services including S3, ECR, ECS, and CodeDeploy.
