= Deploy service update to AWS ECS
:page-platform: Cloud, Server v4+
:page-description: A how to guide for deploying changes to AWS ECS using CircleCI orbs.
:experimental:

In this how-to guide, you will learn how to configure CircleCI to deploy to AWS ECS using CircleCI orbs.

[#introduction]
== Introduction

The Amazon Elastic Container Service (ECS) is a scalable container orchestration service that enables you to support Docker containers and allows you to run and scale containerized applications on AWS. By using Amazon ECS, you will be able to use this service without installing and configuring your own container orchestration software, thereby eliminating the complexity of your deployment and ensuring you have a simple and optimized container deployment on the CircleCI platform. This guide shows you how to deploy software changes to Amazon ECS using CircleCI orbs.

[#set-environment-variables]
== 1. Set environment variables

The following environment variables need to be set. For more information on how to set environment variables, refer to the xref:security:set-environment-variable.adoc[Set an environment variable] page. You can also use a xref:security:contexts.adoc[context]:

* `AWS_ECR_ACCOUNT_URL`
* `MY_APP_PREFIX`
* `AWS_REGION`
* `AWS_ACCESS_KEY_ID`

NOTE: the `CIRCLE_SHA1` variable used in this example is built-in, so it is always available.

[#specify-a-version]
== 2. Specify a version

Every CircleCI `config.yml` starts with the version key. This key is used to issue warnings about breaking changes.

[source,yaml]
----
version: 2.1
----

NOTE: `2.1` is the latest CircleCI version, and it ensures you have access to all our latest features and improvements.

[#use-orbs]
== 3. Use orbs

In this example you will need to use three orbs in your configuration. Add them at the start of your `.circleci/config.yaml`, as follows:

[source,yaml]
----
orbs:
  aws-ecr: circleci/aws-ecr@9.3.5 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@6.0.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@5.1.1 # use the AWS CLI orb
----

TIP: When using orbs, it is a good idea to check the link:https://circleci.com/developer/orbs[Orb Registry] to ensure you are using the most recent version, or the version that fits best with your project.

[#create-workflow]
== 4. Create workflow

A workflow is a set of rules for defining a collection of jobs and their run order. Workflows support complex job orchestration using a set of configuration keys to help you resolve failures sooner. Inside the workflow, you define the jobs you want to run. CircleCI will run this workflow on every commit. Learn more about xref:reference:ROOT:configuration-reference.adoc#workflows[workflow configuration].

[source,yaml]
----
workflows:
  build-and-deploy: # this can be any name you choose
----

[#build-push-and-deploy-a-service-update]]
== 5. Build, push and deploy a service update

To configure an link:https://docs.aws.amazon.com/AmazonECS/latest/developerguide/update-service.html[AWS service update] to deploy a newly built image from AWS ECR, you can use orbs to keep your configuration as simple as possible:

* The `build_and_push_image` job from the ECR orb to build and push an updated image to ECR
* The `deploy_service_update` from the ECS orb to deploy your service update

[source,yaml]
----
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image: # orb built-in job
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy_service_update: # orb built-in job
          requires:
            - aws-ecr/build_and_push_image
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container_image_name_updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
----

For a full list of usage options and orb elements see the link:https://circleci.com/developer/orbs/orb/circleci/aws-ecs[AWS-ECS orb page] in the CircleCI orbs registry.

[#verify-the-deployment]
== 6. Verify the deployment

Once you have updated the Amazon ECS service, you can verify the update was correctly applied. To keep your config as simple as possible, use the AWS CLI and ECS orbs. This time, rather than using an orb's built-in job to perform the required process, commands from the orbs are used as steps in a newly-defined job named `verify-deployment`.

[source,yaml]
----
jobs:
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          aws_secret_access_key: AWS_DEFAULT_REGION
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition ${MY_APP_PREFIX}-service \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            "$BASH_ENV"
      - aws-ecs/verify_revision_is_deployed:
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          task_definition_arn: '${TASK_DEFINITION_ARN}'
----

This section illustrates how you can use the orb to install and configure the AWS CLI, retrieve the link:https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html[task definition] that was previously deployed, and then _verify_ the revision has been deployed using the `verify-revision-is-deployed` command from the `AWS-ECS` orb.

[#add-verification-job-to-the-workflow]
== 7. Add verification job to the workflow

Now that we have our verification job, `verify-deployment`, we can add it to our `build-and-deploy` workflow and ensure it runs sequentially, after the build and deploy jobs using the `requires` key.

[source,yaml]
----
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image: # orb built-in job
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy_service_update: # orb built-in job
          requires:
            - aws-ecr/build_and_push_image
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container_image_name_updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      - verify-deployment:
          requires:
            - aws-ecs/deploy_service_update
----

[#full-config]
== Full config.yml

[source,yaml]
----
version: 2.1 # 2.1 config required to use orbs

orbs:
  aws-ecr: circleci/aws-ecr@9.3.5 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@6.0.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@5.1.1 # use the AWS CLI orb

jobs:
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          aws_secret_access_key: AWS_DEFAULT_REGION
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition ${MY_APP_PREFIX}-service \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            "$BASH_ENV"
      - aws-ecs/verify_revision_is_deployed:
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          task_definition_arn: '${TASK_DEFINITION_ARN}'

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image: # orb built-in job
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
      - aws-ecs/deploy_service_update: # orb built-in job
          requires:
            - aws-ecr/build_and_push_image
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container_image_name_updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      - verify-deployment:
          requires:
            - aws-ecs/deploy_service_update
----

[#track-deployments-with-deploy-markers]
== Track your deployments with deploy markers

After setting up your AWS ECS service updates, you can add deploy markers to track and manage your deployments in the CircleCI web app. Deploy markers provide visibility into your deployment history and enable rollback capabilities.

[#what-are-deploy-markers]
=== What are deploy markers

Deploy markers are a lightweight way to log your deployments in CircleCI. When you add deploy markers to your configuration, you can:

* View a timeline of all deployments in the CircleCI web app
* Track deployment status (pending, running, success, or failed)
* Roll back to previous versions using rollback pipelines
* Trigger deployments directly from the CircleCI web app using deploy pipelines

[#add-deploy-markers-to-your-ecs-deployment]
=== Add deploy markers to your ECS deployment

To add deploy markers to your AWS ECS deployment job, you can create a custom job that wraps the deploy_service_update orb job with deploy marker commands. The following example shows how to integrate deploy markers:

[source,yaml]
----
jobs:
  deploy-with-markers:
    executor: aws-cli/default
    steps:
      - run:
          name: Plan deployment
          command: |
            circleci run release plan ecs-service-deploy \
              --target-version="${CIRCLE_SHA1}" \
              --environment-name="production" \
              --component-name="${MY_APP_PREFIX}-service"
      - aws-cli/setup:
          role_arn: arn:aws:iam::123456789012
      - aws-ecs/deploy_service_update:
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container_image_name_updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      - run:
          name: Update deployment status
          command: circleci run release update ecs-service-deploy --status=running
      - run:
          name: Update deployment to SUCCESS
          command: circleci run release update ecs-service-deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment to FAILED
          command: circleci run release update ecs-service-deploy --status=FAILED
          when: on_fail

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
      - deploy-with-markers:
          requires:
            - aws-ecr/build_and_push_image
      - verify-deployment:
          requires:
            - deploy-with-markers
----

For complete instructions on configuring deploy markers, including status updates and advanced options, refer to the xref:configure-deploy-markers.adoc[Configure Deploy Markers] guide.

[#set-up-rollback-and-deploy-pipelines]
=== Set up rollback and deploy pipelines

Once you have deploy markers configured, you can set up rollback and deploy pipelines to manage your AWS ECS deployments directly from the CircleCI web app:

* xref:set-up-rollbacks.adoc[Set up a Rollback Pipeline] - Configure a pipeline to roll back to previous versions of your ECS service
* xref:set-up-deploys.adoc[Set up a Deploy Pipeline] - Configure a pipeline to deploy new versions from the CircleCI web app

These features provide additional control and visibility for your AWS ECS service deployments.

[#next-steps]
== Next steps

* Find more detailed information in the CircleCI orb Registry for the CircleCI link:https://circleci.com/developer/orbs/orb/circleci/aws-ecs[AWS ECS] and link:https://circleci.com/developer/orbs/orb/circleci/aws-ecr[AWS ECR] orbs.
