---
contentTags:
  platform:
    - Server v4.1
    - Server Admin
---
= Upgrading Mongo
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to upgrade Mongo up to v4.4.15 in an installation of CircleCI server.
:icons: font
:toc: macro
:toc-title:

MongoDB is the database used by CircleCI server. This page describes how to upgrade MongoDB to version `4.4.15``.

The version of Mongo shipped with CircleCI server 4.1 is `3.6.22`.

[#prerequisites]
== Prerequisites

* Ensure backups have been taken. You will need a backup of Mongodb to restore to in case anything goes wrong during the upgrade progress.
* You are prepared to modify the values.yaml.
* `helm upgrade` will work from your system to upgrade the cluster.
* Mongo root password is available.

[#upgrade]
== Upgrade

Our `values.yaml` contains the following snippet:

```yaml
mongodb:
  image:
    tag: 3.6.22-debian-9-r38
```

To begin the upgrade process, change the tag to `4.0.27-debian-9-r118`:

```yaml
mongodb:
  image:
    tag: 4.0.27-debian-9-r118
```

And then `helm upgrade` your installation. 

Once the `helm upgrade` has completed and Mongo has rolled, you will need to exec into the container (with the root password handy) to modify the compatibility version. (Be sure to replace `<password>` with your Mongo root password.)

```bash
kubectl exec -it mongodb-0 -- mongo -u root -p <password>
db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )
```

You should get a `{ "ok" : 1 }` response from Mongo. Exit out of the Mongo shell and pod.

Now change the tag to `4.2.17-debian-10-r99`:

```yaml
mongodb:
  image:
    tag: 4.2.17-debian-10-r99
```

Upgrade the cluster and exec into the new pod when it is ready:

```bash
kubectl exec -it mongodb-0 -- mongo -u root -p <password>
db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )
```

You should get `{ "ok" : 1 }` again. Exit out of the shell and pod.

Change the tag one more time to `4.4.15-debian-10-r8`:

```yaml
mongodb:
  image:
    tag: 4.4.15-debian-10-r8
```

Upgrade the cluster and again exec into the pod:

```bash
kubectl exec -it mongodb-0 -- mongo -u root -p <password>
db.adminCommand( { setFeatureCompatibilityVersion: "4.4" } )
```

Once you receive `{ "ok" : 1 }`, you have successfully upgraded your Mongo to 4.4.15.