StylesPath = styles

Vocab = Docs

MinAlertLevel = suggestion

Packages = AsciiDoc, https://github.com/ammil-industries/vale-signs-of-ai-writing/releases/latest/download/signs-of-ai-writing.zip

[asciidoctor]
# attribute = value
#
# where 'YES' enables and 'NO' disables.

[*.adoc]
BasedOnStyles = circleci-docs, Vale, AsciiDoc, signs-of-ai-writing

[**/nav.adoc]
circleci-docs.XrefTitleCase = NO
circleci-docs.ListPunctuation = NO

[**/ssh-access-jobs.adoc]
Vale.Terms = NO