files:
  - source: /jekyll/_cci2/*.md
    translation: /jekyll/_cci2_%two_letters_code%/%original_file_name%
  - source: /jekyll/_cci2/*.adoc
    translation: /jekyll/_cci2_%two_letters_code%/%original_file_name%
  - source: /jekyll/_data/sidenav.yml
    translation: /jekyll/_data/%two_letters_code%/sidenav.yml
  - source: /jekyll/_includes/edit-on-github.html
    translation: /jekyll/_includes/%two_letters_code%/edit-on-github.html
  - source: /jekyll/_includes/license-notice.html
    translation: /jekyll/_includes/%two_letters_code%/license-notice.html
