files:
  # - source: /jekyll/_data/sidenav.yml
  #   translation: /jekyll/_data/%two_letters_code%/sidenav.yml
  #   update_option: update_as_unapproved

  - source: /jekyll/_includes/edit-on-github.html
    translation: /jekyll/_includes/%two_letters_code%/edit-on-github.html
    update_option: update_as_unapproved

  - source: /jekyll/_includes/license-notice.html
    translation: /jekyll/_includes/%two_letters_code%/license-notice.html
    update_option: update_as_unapproved

  - source: /jekyll/_includes/snippets/*.md
    translation: /jekyll/_includes/snippets/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /jekyll/_includes/snippets/*.adoc
    translation: /jekyll/_includes/snippets/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved

  - source: /jekyll/_cci2/*.md
    translation: /jekyll/_cci2_%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  # - source: /jekyll/_cci2/*.adoc
  #   translation: /jekyll/_cci2_%two_letters_code%/%original_file_name%
  #   update_option: update_as_unapproved

  - source: /jekyll/_cci2/server/*.adoc
    translation: /jekyll/_cci2_%two_letters_code%/server/%original_file_name%
    update_option: update_as_unapproved

  - source: /jekyll/_cci2/server/installation/*.adoc
    translation: /jekyll/_cci2_%two_letters_code%/server/installation/%original_file_name%
    update_option: update_as_unapproved

  - source: /jekyll/_cci2/server/operator/*.adoc
    translation: /jekyll/_cci2_%two_letters_code%/server/operator/%original_file_name%
    update_option: update_as_unapproved

  - source: /jekyll/_cci2/server/overview/*.adoc
    translation: /jekyll/_cci2_%two_letters_code%/server/overview/%original_file_name%
    update_option: update_as_unapproved

  - source: /jekyll/_cci2/images/linux-vm/*.md
    translation: /jekyll/_cci2_%two_letters_code%/images/linux-vm/%original_file_name%
    update_option: update_as_unapproved
