#!/usr/bin/env bash

function rebuild {
	vagrant ssh -c "pkill -f jekyll"
	# Below helps with a VirtualBox bug (https://www.virtualbox.org/ticket/9069)
	vagrant ssh -c "sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'"
	start
}

function restart {
	stop
	start
}

function start {
	if ! vagrant status | grep -q "running"; then
		vagrant up
	fi

	# Building and serving is done separate to provide more feedback. nohup blocks errors.
	vagrant ssh -c "rm -rf /vagrant/jekyll/_site"
	echo "Building with jekyll..."
	vagrant ssh -c "jekyll build --incremental -s /vagrant/jekyll -d /vagrant/jekyll/_site"
	echo "Site built, now starting the server in the background..."
	vagrant ssh -c "nohup jekyll serve --skip-initial-build -s /vagrant/jekyll -d /vagrant/jekyll/_site --host 0.0.0.0 --detach"
	echo "Site should now be available in your browser at http://localhost:4040/docs/"
}

function stop {
	vagrant halt
}


case $1 in
	"start")
		start
		;;
	"rebuild")
		rebuild
		;;
	"restart")
		restart
		;;
	"stop")
		stop
		;;
	*)
		echo "That is not a valid subcommand."
		;;
esac
