ruby '3.1.4'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.18.0'
gem 'sprockets', '~> 3.7'
gem 'sass'
gem 'webrick'
