= Release cycle and versioning policy
:page-noindex: true
:page-platform: Server 4.8, Server Admin
:page-description: Learn about CircleCI Server 4.8 semantic versioning and release schedules.
:experimental:

CircleCI supports the two most recent versions of CircleCI Server at any time, whether the new release is a minor or major version bump. For example, if 4.9 is the current release and 5.0 ships next, then 5.0 and 4.9 become the supported pair.

New versions are released approximately every six months, though the exact timing may vary.

Each version is supported for up to 12 months, but a new release takes precedence: when a new version ships, the older of the two currently supported versions reaches end of life, regardless of how long it has been available.

For example: if 4.8 and 4.9 are the two supported versions and 4.10 is released ten months after 4.8, then 4.8 reaches end of life when 4.10 is released. The new supported pair becomes 4.9 and 4.10.

We use semantic versioning to identify releases and communicate the impact on your installation. Patch releases are published monthly as needed for bugs and security fixes.

[#semantic-versioning]
== Semantic versioning
Given a version number, MAJOR.MINOR.PATCH increment, use the:

. MAJOR version when you make incompatible API changes.
. MINOR version when you add functionality in a backwards-compatible manner.
. PATCH version when you make backwards compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

[#release-schedule]
== Release schedule
We release monthly patch fixes for bugs and security concerns. We will have twice yearly new minor or major (feature) releases. All releases will be posted to the change log. To stay up to date with the most recent releases, subscribe to the link:https://circleci.com/server/changelog/[change log].

[#end-of-support]
== End of support
With each minor or major release, in accordance with our link:https://circleci.com/legal/terms-of-service/[terms of service], we end support for previous versions of CircleCI Server. The following table provides dates for previously released versions.

CAUTION: Future dates listed here may change at any time.

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| Version | Released | End of Support

|4.8.x
|07/24/2025
|07/24/2026*

|4.7.x
|11/07/2024
|11/07/2025*

|4.6.x
|8/12/2024
|07/24/2025

|4.5.x
|4/30/2024
|4/30/2025

|4.4.x
|2/05/2024
|2/28/2025

|4.3.x
|11/07/2023
|11/30/2024

|4.2.x
|7/18/2023
|7/31/2024

|4.1.x
|3/21/2023
|3/31/2024

|4.0.x
|7/28/2022
|7/31/2023
|===
