---
contentTags:
  platform:
  - Cloud
---
= Configure your Kubernetes components - Open preview
:page-layout: classic-docs
:page-liquid:
:page-description: Tutorial outlining how to configure your Kubernetes components for visibility and control on the releases dashboard.
:icons: font
:experimental:

NOTE: CircleCI releases is currently in **open preview**

The steps outlined on this page guide you to configure your Kubernetes resources for integration with your release environment.

[#introduction]
== Introduction

In this tutorial you will configure your Kubernetes components, adding labels and annotations to enable visibility and control over your deployments, and access to the following features:

* Restore a version
* Scale a version
* Restart a version
* Retry a release (when using Argo Rollouts)
* Promote a release (when using Argo Rollouts)
* Cancel a release (when using Argo Rollouts)

[#prerequisites]
== Prerequisites

Before following the steps below, ensure the release environment has been set up successfully. Refer to the xref:set-up-a-release-environment#[Set up a release environment] page.

[#add-required-labels]
== 1. Add required labels to your Deployment/Rollout

To enable your release to show up on the releases dashboard in the CircleCI web app, add the following labels to your Kubernetes Deployment or Argo Rollout:

* Specify the `app` and `version` label in the Kubernetes object `Metadata.Labels`
* Specify the `app` and `version` label in the Kubernetes object `Spec.Template.Metadata.Labels`

For example:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-deployment
    version: 1.0.0
  name: example-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
        version: 1.0.0
----

Once you have updated your Deployment or Rollout, check the CircleCI releases dashboard and you should see your release in the timeline view.

#screenshot#

[#link-release]
== 2. Link release to deployment job trigger (optional)

You can link your release with the CircleCI _deployment_ job that triggered it. To do this, add the following annotations to your Deployment/Rollout. The method for incorporating these values and variables will depend on you config and tooling:

* `circleci.com/job-number` should be set to the `CIRCLE_BUILD_NUM` xref:../variables#built-in-environment-variables[environment variable].
* `circleci.com/pipeline-id` should be set to the `pipeline.id` xref:../variables#pipeline-values[pipeline value].
* `circleci.com/workflow-id` should be set to the `CIRCLE_WORKFLOW_ID` xref:../variables#built-in-environment-variables[environment variable].

Once these values and variables are rendered, the config will look something like:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    circleci.com/job-number: "1"
    circleci.com/pipeline-id: 88dfee99-0348-407f-b113-dbf270cad093
    circleci.com/workflow-id: 5b8c4de8-fd5f-4be2-80a4-3d0c03fc138c
----

[#configure-release-management]
== 3. Configure release management (optional)

By adding a few additional annotations to your Kubernetes objects (Deployment/Rollout), you can enable additional actions on your releases dashboard. This includes restoring, scaling, and restarting component versions. To get started, add the `circleci.com/project-id` annotation with the value found on the relevant CircleCI project settings page.

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ...
    circleci.com/project-id: 9da0c100-3295-49a4-827f-7892f3e8dc83
----

#Screenshot#

[#helm-rollback]
=== a. Use Helm rollback

CAUTION: This option is only available when using Helm to configure your Kubernetes resources.

By default the built-in logic for Kubernetes Deployments or Argo Rollouts is used for the restore version feature. If you manage your component with Helm, you can choose to use the Helm rollback strategy instead. To do so, add the `circleci.com/helm-revision-number` annotation to the Kubernetes object metadata in your Helm chart template:

{% raw %}
[,yaml]
----
annotations:
  circleci.com/helm-revision-number: {{ .Release.Revision | quote }}
----
{% endraw %}

[#operation-timeout]
=== b. Custom operation timeout

CAUTION: This option is only available when using Helm to configure your Kubernetes resources.

The `circleci.com/operation-timeout` annotation allows a custom timeout to be specified for Helm Rollback operations performed as part of a Restore Version command. Valid values are Go duration strings (for example, 5m, 10m15s). This option is available if you are using Helm to manage your Kubernetes resources.

For example,

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ...
    circleci.com/operation-timeout: 10m
----

[#opt-out-ui-based-actions]
=== c. Opt out of UI-based actions

If you would like to disable any release management features for a specific component, you can do so by adding any of the following annotations with the value `false` to the related Kubernetes Deployment or Argo Rollout.

NOTE: If an annotation is either not specified or is specified with any value _other_ than `false`, the associated feature will be **enabled**. Release management features are enabled by default unless explicitly disabled:

* `circleci.com/restore-version-enabled` toggles the Restore Version feature on the annotated Kubernetes Deployment or Argo Rollout
* `circleci.com/scale-version-enabled` toggles the Scale Version feature on the annotated Kubernetes Deployment or Argo Rollout
* `circleci.com/restart-version-enabled` toggles the Restart Version feature on the annotated Kubernetes Deployment or Argo Rollout
* `circleci.com/retry-release-enabled` toggles the Retry Release feature on the annotated Argo Rollout
* `circleci.com/promote-release-enabled` toggles the Promote Release feature on the annotated Argo Rollout
* `circleci.com/cancel-release-enabled` toggles the Cancel Release feature on the annotated Argo Rollout

In the following example, all features are explicitly disabled for the annotated Deployment:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Demo
  namespace: default
  annotations:
    circleci.com/restore-version-enabled: false
    circleci.com/scale-version-enabled: false
    circleci.com/restart-version-enabled: false
    circleci.com/retry-release-enabled: false
    circleci.com/promote-release-enabled: false
    circleci.com/cancel-release-enabled: false
----

[#example-deployment]
== Example Deployment



[#conclusion]
== Conclusion

In this tutorial you have configured your Kubernetes components for visibility and control from the CircleCI releases dashboard.

[#next-steps]
== Next steps

// Here you can inlude links to other pages in docs or the blog etc. where the reader should head next.
* xref:../benefits-of-circleci#[Benefits of CircleCI]
* xref:../concepts#[CircleCI concepts]
