---
contentTags:
  platform:
  - Cloud
---
= Configure your Kubernetes components - Open preview
:page-layout: classic-docs
:page-liquid:
:page-description: Tutorial outlining how to configure your Kubernetes components for visibility and control on the releases dashboard.
:icons: font
:experimental:

NOTE: CircleCI releases is currently in **open preview**

Visualise and control deployments to your Kubernetes cluster with CircleCI release environments. The steps outlined on this page guide you to set up a release environment and install the CircleCI release agent into your Kubernetes cluster.

[#introduction]
== Introduction

In this tutorial you will configure your Kubernetes components, adding labels and annotations to enable visibility and control over your deployments, and access to the following features:

* Restore a version
* Scale a version
* Restart a version
* Retry a release (when using Argo Rollouts)
* Promote a release (when using Argo Rollouts)
* Cancel a release (when using Argo Rollouts)

[#prerequisites]
== Prerequisites

Before following the steps below, ensure the release environment has been successfully set up. Refer to the xref:set-up-a-release-environment#[Set up a release environment] page.

[#add-required-labels]
== 1. Add required labels to your Deployment/Rollout

To enable your release to show up on the releases dashboard in the CircleCI web app, add the following labels to your Kubernetes Deployment or Argo Rollout:

* Specify the `app` and `version` label in the Kubernetes object `Metadata.Labels`
* Specify the `app` and `version` label in the Kubernetes object `Spec.Template.Metadata.Labels`

For example:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
  labels:
    app: example-deployment
    version: 1.0.0
  name: example-deployment
  namespace: default
----

#At this point could they go and check in the app to see if they see it? Or should that wait until they actually do a release?#

[#link-release]
== 2. Link release to deployment job trigger

You can link your release with the CircleCI _deployment_ job that triggered it. To do this, add the following annotations to your Deployment/Rollout. The method for incorporating these values and variables will depend on you config and tooling:

* `circleci.com/pipeline-id` should be set to the `pipeline.id` xref:../variables#pipeline-values[pipeline value].

* `circleci.com/workflow-id` should be set to the `CIRCLE_WORKFLOW_ID` xref:../variables#built-in-environment-variables[environment variable].

* `circleci.com/job-number` should be set to the `CIRCLE_BUILD_NUM` xref:../variables#built-in-environment-variables[environment variable].

Once these values and variables are rendered, the config will look something like:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    circleci.com/job-number: "1"
    circleci.com/pipeline-id: 88dfee99-0348-407f-b113-dbf270cad093
    circleci.com/workflow-id: 5b8c4de8-fd5f-4be2-80a4-3d0c03fc138c
----

[#enable-release-management]
== 3. Enable release management

#TODO#

[#conclusion]
== Conclusion

In this tutorial you have configured your Kubernetes components for visibility and control from the CircleCI releases dashboard.

[#next-steps]
== Next steps

// Here you can inlude links to other pages in docs or the blog etc. where the reader should head next.
* xref:../benefits-of-circleci#[Benefits of CircleCI]
* xref:../concepts#[CircleCI concepts]
