---
contentTags:
  platform:
  - Cloud
---
= Configure release markers
:page-layout: classic-docs
:page-liquid:
:page-description: Tutorial outlining how to configure release markers in your workflow
:icons: font
:experimental:

This tutorial shows how to add a "release marker" step to your workflow config. Release markers allow you log all new releases in one place and link back to the CI/CD pipelines that caused them, without needing to install the release agent.

[#prerequisites]
== Prerequisites

Before adding a release marker step to your workflow, you will need to create a new environment integration in the CircleCI Releases UI.

. In the CircleCI web app, select **Releases** in the sidebar.
. If this is your first environment setup, select btn:[Create your first Environment Integration]. If you already have environments set up, choose the **Environments** tab and select btn:[Create Environment Integration].
. Enter a name for your environment, and a description if you would like.
. Use the dropdown menu to choose your environment integration type, then select btn:[Next: Release Agent Setup].

NOTE: You don't need to continue with installing a release agent, but you will need to reference this environment integration name as part of your config when adding the `log release` step below.

== 1. Update workflow config

This tells CircleCI to log the release marker in the Releases UI.

. Add a `log release` step at the end of your _deployment_ job:
+
[,shell]
----
...
(existing deployment commands)
...
circleci run release log --environment-name=<some-environment-name> --component-name=<some-component-name> --target-version=<some-version-name>
----

. Substitute the placeholders above based on your application's details:
** The `environment-name` param should match the name of your environment integration created via the CircleCI UI.
** The `component-name` param should match the name of your component as displayed in the CircleCI UI.
** The `target-version` param should match the name of the version being released.
** [Optional] You can provide the following parameters if required:
*** The `namespace` param can be provided to use a value other than `default`.