---
contentTags:
  platform:
  - Cloud
---
= Set up CircleCI releases
:page-layout: classic-docs
:page-liquid:
:page-description: Tutorial outlining how to set up CircleCI releases, covering creating an environment integration, installing the release agent and creating components.
:icons: font
:experimental:

Visualise and control deployments to your Kubernetes cluster or SageMaker service with CircleCI releases. The steps outlined on this page guide you to set up CircleCI releases using the CircleCI web app onboarding process. Alternatively, once you have set up an environment integration, you can follow the guides linked below to install the release agent and configure components manually.

[#introduction]
== Introduction

In this tutorial you will set up an integration between CircleCI and your environment (Kubernetes cluster or SageMaker). Once configured, release status can be reported to the CircleCI web app, and the following commands can be executed in your cluster or service by the release agent via controls in the CircleCI UI:

* Restore a version
* Scale a version
* Restart a version
* Retry a release (when using Argo Rollouts)
* Promote a release (when using Argo Rollouts)
* Cancel a release (when using Argo Rollouts)

[#prerequisites]
== Prerequisites

Before setting up your environment integration with CircleCI, run through the following prerequisites:

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free].
* A Kubernetes cluster or Amazon SageMaker service
* A project building on CircleCI that deploys to your Kubernetes cluster or SageMaker service. See the xref:../create-project#[Create a project] page for steps.
* You must have write access to the project associated with the component being deployed. For full details of roles and permissions for GitLab and GitHub App integrations, see the xref:../roles-and-permissions-overview.adoc#[Roles and permissions overview]. If your integration is through Bitbucket or the GitHub OAuth app, you will need to be an org admin in Bitbucket/GitHub respectively. To find out which GitHub integration you have, see the xref:../github-apps-integration.adoc#[GitHub App integration] page.

The following versions of Kubernetes, Helm, and Argo Rollouts have been tested and proven to work. Older versions may work but are not guaranteed:

{% include snippets/release/supported-versions.adoc %}

== Set up releases

[.tab.environmentintegration.Kubernetes_cluster]
--
. In the CircleCI web app, select **Releases** in the sidebar.
. If this is your first environment setup, select btn:[Create your first Environment Integration]. If you already have environments set up, choose the **Environments** tab and select btn:[Create Environment Integration].
. Enter a name for your environment, and a description if you would like.
. Use the dropdown menu to choose your environment integration type, Kubernetes cluster, then select btn:[Next: Release Agent Setup].
. To install the release agent into your cluster and set up your components, follow the in-app setup steps. If you would rather continue the setup process manually, see the xref:set-up-the-release-agent#[Set up the release agent] page.

After completing all the setup steps in the app, you will have done the following:

* Set up an environment integration
* Installed the release agent into your Kubernetes cluster
* Configured your Kubernetes components.
--

[.tab.environmentintegration.Amazon_SageMaker]
--
. In the CircleCI web app, select **Releases** in the sidebar.
. If this is your first environment setup, select btn:[Create your first Environment Integration]. If you already have environments set up, choose the **Environments** tab and select btn:[Create Environment Integration].
. Enter a name for your environment, and a description if you would like.
. Use the dropdown menu to choose your environment integration type, Amazon SageMaker, then select btn:[Save and Continue].
. To get set up with CircleCI releases and Amazon SageMaker from this point, follow the steps outlined on the xref:../deploy-to-amazon-sagemaker#[Deploy to Amazon SageMaker] page.
--

[#next-steps]
== Next steps

In this tutorial you have integrated your Kubernetes cluster with CircleCI. You can now:

* xref:configure-your-kubernetes-components#[Configure your Kubernetes components].
* Learn how to xref:update-the-kubernetes-release-agent#[update the Kubernetes release agent]
