---
contentTags:
  platform:
  - Cloud
---
= Update the Kubernetes release agent
:page-layout: classic-docs
:page-liquid:
:page-description: How to update the Kubernetes release agent for integrations with CircleCI releases
:icons: font
:experimental:

Follow the steps on this page to update the release agent installed in your Kubernetes cluster.

Refer to the link:https://circleci.com/changelog/[CircleCI Change log] to find out about new release agent versioning, updates, and fixes.

[#prerequisites]
== Prerequisites

To update the Kubernetes release agent you need an operational CircleCI release environment integrated with your Kubernetes cluster. Refer to the following pages for steps:

* xref:set-up-a-release-environment#[Set up a release environment]
* xref:configure-your-kubernetes-components#[Configure your Kubernetes components]

NOTE: We have made a small but significant change in the helm installation command that you need to be aware of.
The argument name `manageNamespaces` has been corrected to `managedNamespaces`.
Please make sure to use `managedNamespaces` instead of `manageNamespaces` when installing or upgrading to the newer versions of the software. If you have any scripts or automation that includes the previous command, they need to be updated to use managedNamespaces.

[#update-steps]
== Update steps

. Update your local Helm cache:
+
[,shell]
----
helm repo update
----
. Upgrade to the new version:
+
[,shell]
----
helm upgrade --install circleci-release-agent-system release-agent/circleci-release-agent \
--set tokenSecret.token=[YOUR_CCI_INTEGRATION_TOKEN] --create-namespace \
--namespace circleci-release-agent-system \
--set managedNamespaces="{namespace1,namespace2}"
----