[#what-are-credits]
=== What are credits?

Credits are used to pay for users and usage based on machine type, size, and features such as Docker Layer Caching.

For example, the 25,000 credit package would provide 2,500 build minutes when using a Docker or Linux "medium" compute at 10 credits per minute. CircleCI provides multiple compute sizes so you can optimize builds between performance (improved developer productivity) and value.

When applicable, build time can be further reduced by using parallelism, which splits the job into multiple tests that are executed at the same time. With 2x parallelism, a build that usually runs for 2,500 minutes could be executed in 1,250 minutes, further improving developer productivity. Note that when two executors are running in parallel for 1,250 minutes each, total build time remains 2,500 minutes.

[#buy-credits-in-any-increments]
=== How do I buy credits? Can I buy in any increments?

Every month, you are charged for your selected credit package at the beginning of the month.

[#what-do-i-pay-for]
=== What do I pay for?

You can choose to pay for premium features per active user, compute, and optionally, premium support.

* Access to features, such as new machine sizes, are paid with a monthly fee of 25,000 credits per active user (not including applicable taxes).
* Compute is paid for monthly in credits for the machine size and duration you use:
 ** Credits are sold in packages of 25,000 at $15 each (not including applicable taxes).
 ** Credits rollover each month and expire after one year.
* Docker Layer Caching (DLC) is paid for with credits per usage, similar to
compute credits.

[#run-out-of-credits]
=== What happens when I run out of credits?

On the *Performance plan*, when you reach 0 credits, you will be refilled 25% of your credit subscription, with a minimum refill of 25,000 credits. For example, if your monthly package size is 100,000 credits, you will automatically be refilled 25,000 credits (at $.0006 each, not including applicable taxes) when you reach 2000 remaining credits.

If you notice that your account is receiving repeated refills, review your credit usage by logging in to the CircleCI web app > click `Plan` > click `Plan Usage`. In most cases, increasing your credit package should minimize repeat refills. You can manage your plan by clicking `Plan Overview`.

On the *Free plan*, jobs will fail to run once you have run out of credits.

[#do-credits-expire]
=== Do credits expire?

*Performance plan*: Credits expire one year after purchase. Unused credits will be forfeited when the account subscription is canceled.

[#how-do-i-pay]
=== How do I pay?

You can pay from inside the CircleCI app for monthly pricing.

[#when-do-i-pay]
=== When do I pay?

On the *Performance plan*, at the beginning of your billing cycle, you will be charged for premium support tiers and your monthly credit allocation. Any subsequent credit refills _during_ the month (such as the auto-refilling at 25% when there are 0 credits remaining) will be paid _at the time of the refill_.

[#what-is-prepaid-billing]
=== What is prepaid billing?

Prepaid billing is a payment option for customers on the Performance plan. Prepaid Billing allows you to purchase credits in bulk, pay upfront, and be able to get discounted prices for credits based on volume purchased.

[#how-can-i-get-on-prepaid-billing]
=== How can I get on prepaid billing?

All Performance plan customers can choose to get on prepaid billing through the CircleCI web app. To access this option, follow these steps:

. Select **Plan** in the web app
. Select the **Manage** tab
. Select to **Set up and switch** to get started switching to prepaid billing

[#i-still-have-credits-from-my-monthly-subscription]
=== I still have credits from my Monthly subscription, what happens if I get on prepaid billing now?

You will still have access to any balance credits that were previously purchased, and the 12 month expiry date will remain.

[#i-selected-prepaid-billing-but-i-didnt-receive-a-discount]
=== I selected prepaid billing but I didn’t receive a discount. Why?

Discounting for prepaid billing starts at a purchase volume of 5 Million credits onwards.

[#what-happens-when-i-run-out-of-all-my-prepaid-billing-credits]
=== What happens when I run out of all my prepaid billing credits?

Similar to what happens today on Performance plans, when you run out of credits your credit package will be automatically renewed at the purchase level you have selected.

[#when-will-i-be-charged-for-my-prepaid-billing-purchase]
=== When will I be charged for my prepaid billing purchase?

Upon selecting prepaid billing, your credit card will be charged immediately. Subsequently, when you run out of credits, your credit card will be charged again to provide you with a refill.

[#i-want-to-change-my-upcoming-prepaid-billing-refill]
=== I want to change my upcoming prepaid billing refill, how do I do that?

You can follow these steps:

. Select **Plan* in the web app
. Select the **Manage** tab
. Click the pencil icon in the **Credits** section to edit your auto refill rate

[#do-i-still-get-bonus-credits-and-5-free-seats]
=== Do I still get 30,000 bonus credits and 5 free seats on prepaid billing?

Yes, all prepaid billing customers still receive the benefit of 30,000 credits and 5 free user seats every month.

[#share-plans-across-organizations-billed-centrally]
=== Is there a way to share plans across organizations and have them billed centrally?

Yes, log in to the CircleCI web app > select `Plan` in the sidebar > click `Share & Transfer`.

On non-free plans, you can share your plan with free organizations for which you have admin access using the `Add Shared Organization` option. All orgs you have shared your plan with will then be listed on the Share & Transfer page and child organizations will bill all credits and other usage to the parent org.

On non-free plans, you can transfer your plan to another free organization for which you have admin access using the `Transfer Plan` option. When you transfer a paid plan to another org, your org will be downgraded to the free plan.

[#container-used-for-under-one-minute-pay-for-a-full-minute]
=== If a container is used for under one minute, do I have to pay for a full minute?

You pay to the next nearest credit. First we round up to the nearest second, and then up to the nearest credit.

[#calculate-monthly-storage-and-network-costs]
=== How do I calculate my monthly storage and network costs?

Calculate your monthly storage and network costs by finding your storage and network usage on the link:https://app.circleci.com/[CircleCI web app] by navigating to menu:Plan[Plan] Usage.

[#storage]
==== Storage

To calculate monthly storage costs from your daily usage, click on the *Storage* tab to see if your organization has accrued any overages beyond the GB-monthly allotment. Your overage (GB-Months/TB-Months) can be multiplied by 420 credits to estimate the total monthly costs. Example: 2 GB-Months overage x 420 credits = 840 credits ($.50).

[#network]
==== Network

Billing for network usage is only applicable to traffic from CircleCI to self-hosted runners. Read more on the xref:persist-data#overview-of-network-and-storage-transfer[Persisting data] page.

Your network overage GB/TB can be multiplied by 420 credits to estimate the total monthly costs. Example: 2 GB-Months overage x 420 credits = 840 credits ($.50).

[#calculate-monthly-IP-ranges-costs]
=== How do I calculate my monthly IP ranges cost?

Calculate your monthly IP ranges costs by finding your IP ranges usage on the link:https://app.circleci.com/[CircleCI app] by navigating to Plan > Plan Usage.

In addition to the *IP Ranges Usage* summary, you can navigate to the *IP Ranges* tab to find more details about your data usage. In this tab, the IP ranges usage value represents the raw number of bytes in or out of the Docker container during execution of a job with IP ranges enabled.

This number includes the job's overall network transfer _and_ any other bytes that go in or out of the Docker container. Data used to pull in the Docker image to the container before the job starts executing will _not incur usage costs_ for jobs with IP ranges enabled.

This feature will consume 450 credits from your account for each GB of data used for jobs with IP ranges enabled. You can also view job-specific details of IP ranges usage in the *Resources* tab on the *Job Details* UI page. See xref:ip-ranges#pricing[IP ranges pricing] for more information.

[#predict-monthly-IP-ranges-cost-without-enabling-feature-first]
=== How do I predict my monthly IP ranges cost without enabling the feature first?

You can view an approximation of network transfer for any Docker job (excluding Remote Docker) in the **Resources** tab on the Job Details UI page. Convert this value to GB if it is not already in GB and multiply by 450 credits to predict the approximate cost of enabling IP ranges on that Docker job.

[#per-active-user-pricing]
=== Why does CircleCI have per-active-user pricing?

Credit usage covers access to compute. We prefer to keep usage costs as low as possible to encourage frequent job runs, which is the foundation of a good CI practice. Per-active-user fees cover access to platform features and job orchestration. This includes features like dependency caching, artifact caching, and workspaces, all of which speed up build times without incurring additional compute cost.

[#what-constitutes-an-active-user]
=== What constitutes an _Active User_?

An `active user` is any user who triggers the use of compute resources on non-OSS projects. This includes activities such as:

- Commits from users that trigger builds, including PR Merge commits
- Re-running jobs in the CircleCI web application, including xref:ssh-access-jobs#[SSH debug]
- Approving xref:workflows#holding-a-workflow-for-a-manual-approval[manual jobs] (approver will be considered the actor of all downstream jobs).
- Using scheduled workflows
- Machine users

NOTE: If your project is xref:oss#[open-source] you will *not* be considered an active user.

To find a list of your Active Users, log in to the CircleCI web app, click menu:Plan[Plan Usage > Users].

[#charged-job-is-queued-or-preparing]
=== Am I charged if my job is "Queued" or "Preparing"?

No. If you are notified that a job is "queued", it indicates that your job is waiting due to a *plan* or *concurrency* limit. If your job indicates that it is "preparing", it means that CircleCI is setting up or _dispatching_ your job so that it may run.

[#other-renewal-dates]
=== What are the other renewal dates?

The first credit card charge on the day you upgrade to a paid plan or change paid plans, in addition to the following charges from CircleCI:

- On the monthly renewal date if your team is on the monthly plan.
- On the annual renewal date if your team is on the annual plan.
- On the last day of the month if your team is on the annual plan and there is an outstanding balance from adding new users or utilizing more credits.
- If you are on the Performance plan, anytime your team's credit balance drops below your preset limit, another credit purchase will be processed.

[#credit-plans-for-open-source-projects]
=== Are there credit plans for open source projects?

Open source organizations on our *Free plan* receive 400,000 free credits per month that can be spent on Linux open source projects.  Open-source credit availability and limits will not be visible in the UI.

If you build on macOS, we also offer organizations on our Free plan 25,000 free credits per month to use on macOS open source builds. To find out more, visit the CircleCI link:https://support.circleci.com/hc/en-us[support portal], which includes an Ask AI option to get you the information you need. Free credits for macOS open source builds can be used on a maximum of 2 concurrent jobs per organization.

[#discounts-for-open-source-performance-plan]
=== Can I get discounts for open source on the Performance plan?

CircleCI no longer offers discounts for open source customers on the Performance plan.

[#charge-for-docker-layer-caching]
=== Why does CircleCI charge for Docker layer caching?

Docker layer caching (DLC) reduces build times on pipelines where Docker images are built by only rebuilding Docker layers that have changed (read more on the xref:docker-layer-caching#[Docker Layer Caching] page). DLC costs 200 credits per job run.

To estimate your DLC cost, look at the jobs in your config file with Docker layer caching enabled, and the number of Docker images you are building in those jobs. There are cases where a job can be written once in a config file but the job runs multiple times in a pipeline, for example, with parallelism enabled.

Note that the benefits of Docker layer caching are only apparent on pipelines that are building Docker images, and reduces image build times by reusing the unchanged layers of the application image built during your job. If your pipeline does not include a job where Docker images are built, Docker layer caching will provide no benefit.
