= CircleCI docs style guide
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This guide is a reference for contributors to CircleCI docs. Our style guide is constantly evolving so you will probably find older documentation does not meet the requirements set out here. Use this guide to help you write new docs, and when working on existing documentation it would be great if you can make edits to help us get older documents to conform too!

== Choosing helpful headings
All headings are in sentence case. This means only the first word and proper nouns are capitalized. Jekyll automatically creates an H1 heading from the doc title, so only use H2 and greater in the body of the doc.

**Good:** CircleCI docs style guide +
**Bad:** CircleCI Docs Style Guide

Where possible, headings should begin with a verb.

**Good:** "Grooming cats" +
**Bad:** "Cats"

When referencing headings in prose, use the full heading with no quotes.

**Good:** <<headings>> +
**Bad:** "<<headings>>"

== Links
Links should explicitly name the document or section to which they are linking.

**Good:** Refer to the https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project[Setting and environment variable in a project] section of the Environment Variables document. +
**Bad:** See here for info on https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project[adding project-level environment variables]. 


