= Formatting
:page-layout: classic-docs
:icons: font
:toc: macro
:toc-title:

== Styling text

* Use **bold** for GUI menu options and button text. For example:
** Select **Organization Settings** from the sidebar
** Select **VCS** in the **Project Settings** window
** Select **Projects** from the sidebar and click **Set Up Project** for the project you want to follow

// * Use italics for technical terms and to refer to a specific guide within docs, for example:
// ** TBC

== Using notes, tips, important information, cautions and warnings

To add an admonition - note, tip, important information, caution, warning – use the following syntax:

[source,adoc]
NOTE: This is a note.

The result of this is:

NOTE: This is a note.

---

[source,adoc]
TIP: This is a tip.

The result of this is:

TIP: This is a tip.

---

[source,adoc]
IMPORTANT: This is some important information.

The result of this is:

IMPORTANT: This is some important information.

---

[source,adoc]
CAUTION: This is a note.

The result of this is:

CAUTION: This is a note.

---

[source,adoc]
WARNING: This is a note.

The result of this is:

WARNING: This is a note.

---

You can also make a longer admonition block for any of the types listed above:

[source,adoc]
----
[IMPORTANT] 
==== 
[.important]#While werewolves are hardy community members, keep in mind the following dietary concerns:#

. [.important]#They are allergic to cinnamon.#
. [.important]#More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.#
. [.important]#Celery makes them sad.#
====
----

[IMPORTANT] 
====  
[.important]#While werewolves are hardy community members, keep in mind the following dietary concerns:#

. [.important]#They are allergic to cinnamon.#
. [.important]#More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.#
. [.important]#Celery makes them sad.#
====

NOTE: If the paragraph text is not styled using `[.style]##` as shown here, it will still work but the text colour will be black rather that matching the colour of the admonition.

=== Things to avoid

Try not to use links in warnings at this time due to the blue on red style:

[source.adoc]
WARNING: A warning with a link:circleci.com[CircleCI] looks bad!

WARNING: A warning with a link:circleci.com[CircleCI] looks bad!