---

contentTags:
  platform:
  - クラウド
  - Server v4.x
  - Server v3.x
---
= 複数のワークフローを使ったパイプラインのスケジュール実行
:page-layout: classic-docs
:page-liquid:
:page-description: 複数のワークフローにおけるパイプラインのスケジュール実行の条件を設定する方法を説明します。
:icons: font
:toc: macro

:toc-title:

[#introduction]
== はじめに

スケジュール化されたパイプラインはトリガーされたパイプラインであり、デフォルトではトリガーごとに設定されているすべてのワークフローが実行されます。 `.circleci/config.yml` ファイル内のワークフローを条件によりフィルタリングすることができます。 設定した条件により、スケジュール化されたパイプラインがトリガーされる際に実行するワークフローを制御できます。 これらの条件は、定義済みパイプライン値またはカスタムのパイプラインパラメーターを使って設定することができます。 下記の各コード例では、`.circleci/config.yml` ファイルで条件を設定する様々な方法を紹介します。

[#schedule-using-built-in-pipeline-values]
== 定義済みパイプライン値を使ったスケジュール実行

ワークフローのフィルタリングを実装するための 1 つの方法は、パイプライン値を使用することです。 以下のコード例では、定義済みパイプライン値である `pipeline.trigger_source` と `pipeline.schedule.name` を使用しています。 この例では、 `pipeline.schedule.name` として `daily_build` と `nightly_build` が使用されていますが、パイプラインのスケジュール実行機能を使用する上では、`pipeline.schedule.name` にはお好きな値を使用できます。

```yaml
version: 2.1
...
daily-run-workflow:
# run workflow only when the daily_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ daily_build, << pipeline.schedule.name >> ]
  jobs:
    - test
    - build

nightly-run-workflow:
# run workflow only when the nightly_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ nightly_build, << pipeline.schedule.name >> ]
  jobs:
    - build
    - deploy
...
```

上記の例の `when` の下の２番目の `equal` は必ずしも必要ではありません。 `pipeline.schedule.name` は、パイプラインがスケジュールによってトリガーされる場合に使用できるパイプライン値です。

スケジュールがトリガーされる時に *実行しない* ワークフローのフィルタリングを追加することもできます。

{% raw %}

```yaml
version: 2.1
...
daily-run-workflow:
# run workflow only when the daily_build pipeline is triggered
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ daily_build, << pipeline.schedule.name >> ]
  jobs:
    - test
    - build

nightly-run-workflow:
# do NOT run workflow if a scheduled pipeline is triggered
  when:
    not:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  jobs:
   - build
   - deploy
...
```

{% endraw %}

パイプライン値の全リストは、xref:pipeline-variables/#pipeline-values[パイプラインの値とパラメーター] でご確認ください。

[#schedule-using-pipeline-parameters]
== パイプラインパラメーターを使ったスケジュール実行

下記の例では、 `run-schedule` というパラメーターが作成され、`type: boolean` および `default: false` と設定されています。 これにより、ワークフローのセクションで `when` を使っていつパイプラインを実行するかの条件を指定できます。 `when` 条件を使用する場合は、以下の例のように `when: not:` も設定する必要があります。

```yaml
version: 2.1
...
# set pipeline parameters
parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  # do not run the scheduled pipeline if build-test-deploy
  build-test-deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - test
      - build
  # run the scheduled pipeline if nightly-snapshot
  nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - build
      - deploy
...
```

この設定ファイルサンプルの全文は、GitHub 上の link:https://github.com/zmarkan/Android-Espresso-ScrollableScroll/blob/main/.circleci/config.yml[サンプルプロジェクト] をご覧ください。 パイプラインパラメーターの全リストは、xref:pipeline-variables/#pipeline-parameters-in-configuration[パイプラインの値とパラメーター] でご確認ください。

[#set-up-multiple-workflows-with-multiple-schedules]
== 複数のスケジュールを含む複数のワークフローの設定

以下は、複数のパイプライン値を使った 3 つのワークフローのスケジュール実行のコード例です。 2 つのワークフローが同じスケジュール (`daily_build`) で実行され、1 つは別のスケジュール (`weekly_build`) で実行されます。

```yaml
version: 2.1
...
workflows:
# run workflow only when the daily_build pipeline is triggered
  daily-run-workflow:
    when:
      equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job-one

  nightly-run-workflow:
  # run workflow only when the daily_build pipeline is triggered
    when:
      equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job-two

  weekly-run-workflow:
  # run workflow only when the weekly_build pipeline is triggered
    when:
      equal: [ weekly_build, << pipeline.schedule.name >> ]
    jobs:
      - job-three
...
```

[#next-steps]
== 次のステップ

- xref:set-a-nightly-scheduled-pipeline.adoc[パイプラインのスケジュール実行を夜間に設定する]
- xref:migrate-scheduled-workflows-to-scheduled-pipelines.adoc[ワークフローのスケジュール実行からパイプラインのスケジュール実行への移行]