---
version:
- Server v4.1
- Server Admin
---
= Additional considerations
:page-layout: classic-docs
:page-liquid:
:page-description: This page presents some items that should be considered when starting an air-gapped installation of CircleCI server
:icons: font
:toc: macro
:toc-title:

[#non-tls-docker-registry-installations]
== Non-TLS Docker Registry Installations

When configuring your air-gapped docker registry, it is recommended to use TLS certificates to encrypt traffic. If using a non-tls, or self-signed installation, the following steps additional steps will need to be taken.

On machines that access the docker registry using docker, the docker daemon config must be updated (located on linux at /etc/docker/daemon.json).

The insecure-registries section must be added to the file (if it exists), or the file must be created with the following if it doesn't. Make sure to include the full hostname and port of your registry - without including the protocol (http:// or https://).

[source, json]
----
{
      "insecure-registries":["docker.example.internal:5000"]
}
----

This file will need to be configured on the following machines:

- All Nomad nodes in the air-gapped environment
- Potentially all K3s nodes in the air-gapped environment, if using docker-backed K3s

In addition, on each K3s node, the following file must be configured at /etc/rancher/k3s/registries.yaml. Take note to include the protocol where referenced.

[source, yaml]
----
mirrors:
  "docker.example.internal:5000":
    endpoint:
      - "http://docker.example.internal:5000"
configs:
  "docker.example.internal:5000":
    tls:
      insecure_skip_verify: true
----

---



[#service-type-load-balancers-k3s]
== Service Type Load Balancers in K3s

CircleCI Server makes use of Service Type: Load Balancer kubernetes resources to listen to traffic on multiple ports. In order to function, the cluster needs to.

If using a K3s installation, MetalLB can be used to create a virtual load balancer on the K3s node, to allow ingress traffic to CircleCI Server.

https://metallb.universe.tf/installation/

Once installed, the following steps need to be followed:

A configmap resource needs to be created to create an address pool for MetalLB.

[source, yaml]
----
apiVersion: "v1"
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
    protocol: layer2
    addresses:
      - <<k3s_internal_ip_range_start>>-<<k3s_internal_ip_range_end>>
----

The address pool can be named something other than "default", but the annotations in values.yaml will need to be updated. If there is only one k3s node, the address range should have the same IP repeated (example: 10.0.0.5-10.0.0.5).


Once this configmap resource is applied to the cluster (`kubectl apply -f metallb-configmap.yaml`), the address pool name can be updated in the values.yaml for the Helm installation.

[source, yaml]
----
# Additional nginx annotations
nginx:
  annotations:
    # This example uses MetalLB as a k3s load balancer
    metallb.universe.tf/allow-shared-ip: default
----

After installing the Helm chart, the circleci-proxy service must be patched to use the internal IP of the desired k3s node to act as the load balancer (this IP should be in the range inputted in the configmap above). In the below example, we are using the IP 10.0.0.5.

[source, bash]
----
kubectl patch svc circleci-proxy  -p '{"spec": {"type": "LoadBalancer", "externalIPs":["10.0.0.5"]}}'
----

Once complete, DNS records can be created for your server installation (server.internal.example.com) and (*.server.internal.example.com) for 10.0.0.5.
