---
version:
- Server v4.x
- Server Admin
---
= Phase 1 - Copying Images & Charts
:page-layout: classic-docs
:page-liquid:
:page-description: How to copy the necessary images and charts for CircleCI Server to your air-gapped environment.
:icons: font
:toc: macro
:toc-title:

CircleCI Server is deployed into a Kubernetes cluster using a Helm chart. As such, we'll need to copy the latest images and charts from CircleCI into your virtual environment.

[#copy-images]
== Copy Images
All images referenced in the CircleCI Helm chart must be accessible within your air-gapped environment.

[#login-to-acr]
=== 1. Login to CircleCI Server container registry
These images to copy require a CircleCI provided username and token in order to pull. Please contact support@circleci.com for more information.

[source, bash]
----
docker login cciserver.azurecr.io --username <your-circleci-provided-username> --password <your-circleci-provided-token>
----


=== 2. Download all images required for this release
Download all images required for the release of CircleCI Server to your local machine. 


[source, bash]
----
IMAGE_LIST=`cat <<EOF
nginx
EOF
`
----


[source, bash]
----
echo $IMAGE_LIST | while read -r image; do docker pull $image; done
----


[#copy-all-images]
=== 3. Copy all images to your air-gapped environment
Copy all downloaded images to the docker registry in your air-gapped environment.


[#copy-charts]
== Copy Charts
Next we'll copy the CircleCI Server helm chart to your air-gapped environment.

[#download-helm-chart]
=== 1. Download the latest CircleCI Server Helm chart
Download the latest CircleCI Server helm chart to the current directory.


[source, bash]
----
helm registry login cciserver.azurecr.io
helm pull oci://cciserver.azurecr.io/circleci-server -d ./
----

[#upload-helm-chart]
=== 2. Copy the Helm chart to your air-gapped environment
Copy the downloaded .tgz chart in the current directory to your air-gapped environment.
