---
version:
- Server v4.x
- Server Admin
---
= Phase 5 - Configuring CircleCI Runner
:page-layout: classic-docs
:page-liquid:
:page-description: How to configure CircleCI Runner to run with CircleCI Server in an air-gapped environment.
:icons: font
:toc: macro
:toc-title:

[#install-circleci-cli]
== 1. Install the latest CircleCI CLI release
Retrieve and install the https://github.com/CircleCI-Public/circleci-cli/releases[latest CircleCI CLI release]. Determine the latest release, and then use the following command (substituting a different version to the one listed here if necessary):

[source,shell]
----
wget https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.22675/circleci-cli_0.1.22675_linux_amd64.tar.gz
----

[#copy-circleci-cli]
== 2. Copy the CLI .tar.gz file
Copy the CircleCI CLI `.tar.gz` file to the first machine designated to run the CircleCI runner in your air-gapped environment.

[#extract-circleci-cli]
== 3. Extract the CLI .tar.gz file
On the air-gapped machine, extract the `.tar.gz` file:

[source, bash]
----
tar -zxvf circleci-cli_0.1.22675_linux_amd64.tar.gz
----

[#cd-extracted-directory]
== 4. Descend into the extracted directory
Descend into the extracted directory.

[source, bash]
----
cd circleci-cli_0.1.22675_linux_amd64
----

[#generate-user-token]
== 5. Generate a personal API token
In the app for your CircleCI server installation, generate a personal API token.

To navigate to the page you need, use this URL format: `https://app.<airgapped-tld-of-your-circleci-server-installation>/settings/user/tokens`.

[#export-user-token]
== 6. Export the token
On the air-gapped machine, export the user token, and the air-gapped accessible URL for your CircleCI server installation, as the following environment variables:

NOTE: The `CIRCLECI_CLI_HOST` variable should *not* include the `app` subdomain of your installation that is present when visiting CircleCI server in a browser.

NOTE: Adjust the protocol from https to http as necessary for your installation in the CIRCLECI_CLI_HOST environment variable.

[source, bash]
----
export CIRCLECI_CLI_TOKEN=<generated-user-token>
export CIRCLECI_CLI_HOST=https://<airgapped-tld-of-your-circleci-server-installation>
----

[#create-namespace]
== 7. Create a runner namespace
On the air-gapped machine, run the following command to create a namespace using your GitHub Enterprise username:

[source,shell]
----
./circleci --skip-update-check namespace create <github-enterprise-username> github <github-enterprise-username>
----

[#create-resource-class]
== 8. Create a resource class
On the air-gapped machine, run the following command to create a resource class with your GitHub enterprise username:

[source,shell]
----
./circleci --skip-update-check runner resource-class create <github-enterprise-username>/default "Default Runners" --generate-token
----

[#download-release-txt-launch-agent]
== 9. Download launch agent release.txt file
On an internet-connected machine, download the `release.txt` file for the latest CircleCI launch agent:

[source, bash]
----
wget https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent/release.txt
----

[#download-launch-agent]
== 10. Download launch agent and checksum
On an internet-connected machine, using the newly downloaded `release.txt` file, download the latest release of the launch agent and its checksum:

[source, bash]
----
LATEST_RELEASE=$(cat release.txt)

# Download circleci-launch-agent
wget https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent/$LATEST_RELEASE/linux/amd64/circleci-launch-agent


# Download launch agent checksum
wget https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent/$LATEST_RELEASE/checksums.txt
----

[#copy-launch-agent]
== 10. Copy launch agent to the air-gapped machine
Verify the checksum and copy the downloaded `circleci-launch-agent` file to your air-gapped environment.

[#setup-launch-agent]
== 11. Set up CircleCI Launch Agent on runner machines
On each machine designated as a CircleCI runner, follow the https://circleci.com/docs/runner-installation-linux/[CircleCI runner setup instructions] to configure the runner.

[source, bash]
----
sudo mkdir -p /opt/circleci

# Move the launch agent from its uploaded location to /opt/circleci/ and make it executable
sudo mv circleci-launch-agent /opt/circleci/circleci-launch-agent
sudo chmod +x /opt/circleci/circleci-launch-agent

id -u circleci &>/dev/null || sudo adduser -c GECOS circleci

sudo mkdir -p /var/opt/circleci && sudo chmod 0750 /var/opt/circleci

sudo chown -R circleci /var/opt/circleci /opt/circleci/circleci-launch-agent

echo "circleci ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

sudo mkdir -p /etc/opt/circleci && sudo touch /etc/opt/circleci/launch-agent-config.yaml
----

[#next-steps]
== Next steps

Once the steps on this page are complete, go to the link:/docs/server/v4.1/air-gapped-installation/phase-6-test-your-installation/[Phase 6 - Test your installation] guide.