---
version:
- Server v4.x
- Server Admin
---
= Phase 1 - Prerequisites
:page-layout: classic-docs
:page-liquid:
:page-description: A guide to installing CircleCI server in an air-gapped environment. Requirements, images and Helm charts.
:icons: font
:toc: macro
:toc-title:

The guides in this section walk you through the steps required to install CircleCI server in an air-gapped environment.

[#required-components]
== Required components for air-gapped installation
The following is an overview of the prerequisites required to run an air-gapped CircleCI Server installation. These items must be present in your air-gapped environment in order to move forwards with the installation.

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
| Component
| Used for
| Notes

| Container registry
| Hosting CircleCI server images for Kubernetes
|

| A Kubernetes cluster
| Running CircleCI Server
|

| An object storage system (minIO)
| Object and artifact storage
|

| GitHub Enterprise
| Source of code for CircleCI Server to build
|

| Virtual Machines
| Machines for running Nomad and the CircleCI runner
|
|===

[#copy-images]
== Copy images

CircleCI server is deployed into a Kubernetes cluster using a Helm chart. You will need to copy the latest images and charts from CircleCI into your virtual environment. All images referenced in the CircleCI Helm chart must be accessible within your air-gapped environment.

[#login-to-acr]
=== 1. Log in to CircleCI server container registry
Access to the images you need for your installation requires you to use a username and token, which will be provided by CircleCI. Please contact support@circleci.com for more information.

[source, bash]
----
docker login cciserver.azurecr.io --username <your-circleci-provided-username> --password <your-circleci-provided-token>
----

=== 2. Download all images required for this release
Download all images required for the release of CircleCI server to your local machine:

[source, bash]
----
IMAGE_LIST=`cat <<EOF
nginx
EOF
`
----

[source, bash]
----
echo $IMAGE_LIST | while read -r image; do docker pull $image; done
----

[#copy-all-images]
=== 3. Copy all images to your air-gapped environment
Copy all downloaded images to the container registry in your air-gapped environment.

[#copy-charts]
== Copy charts
Copy the CircleCI server Helm chart to your air-gapped environment.

[#download-helm-chart]
=== 1. Download the latest CircleCI server Helm chart
Download the latest CircleCI Server Helm chart to the current directory.

[source, bash]
----
helm registry login cciserver.azurecr.io
helm pull oci://cciserver.azurecr.io/circleci-server -d ./
----

[#upload-helm-chart]
=== 2. Copy the Helm chart to your air-gapped environment
Copy the downloaded `.tgz` Helm chart to your air-gapped environment.

[#next-steps]
== Next steps

Once the steps on this page are complete, go to the link:/docs/server/v4.1/air-gapped-installation/phase-2-configure-object-storage/[Phase 2 - Configure object storage] guide.
