---
contentTags:
  platform:
    - Server v4.2
    - Server Admin
---
= CircleCI server v4.2 release notes
:page-layout: classic-docs
:page-liquid:
:page-description: Details of the new features included in each CircleCI server 4.2 release.
:icons: font
:toc: macro
:toc-title:

[#overview]
== Overview

The v4.2 release introduces the config policies feature to CircleCI server. Use config policies to create organization-level policies to impose rules and scopes to govern which configuration elements are required, allowed, not allowed etc. For more information see the xref:../../../config-policy-management-overview#[Config policies overview]. To use config policies CLI commands with server, append all commands shown in the docs with `--policy-base-url https://<CIRCLECI-SERVER-DOMAIN>.com`

[#migration]
== Migrate

NOTE: The migration process requires that you install v4.0.x first before moving to subsequent releases.

For existing customers interested in migrating from v3.x to v4.x, contact your customer success manager.

Find information about migration in the following guides:

* xref:../../installation/migrate-from-server-3-to-server-4#[Migrate from server v3 to v4 guide]
* xref:../../installation/migrate-from-server-2-to-server-4#[Migrate from server v2 to v4 guide]

[#upgrade]
== Upgrade
For upgrade steps see the xref:../installation/upgrade-server#[Upgrade server v4.2 guide].

CAUTION: If you are upgrading from server v4.1.x and have user-managed secrets, ensure you follow the steps in the xref:../installation/upgrade-server#[Upgrade server v4.2 guide].

[#release-4-2-4]
== Release 4.2.4

[#changelog-4-2-4]
=== Changelog

For full details of this release see the link:https://circleci.com/server/changelog/#server-release-4-2-4[changelog].


[#release-4-2-3]
== Release 4.2.3

[#changelog-4-2-3]
=== Changelog
Updates to GitHub's SSH key fingerprints
For full details of this release see the link:https://circleci.com/server/changelog/#release-4-2-3[changelog].


[#release-4-2-2]
== Release 4.2.2

[#changelog-4-2-2]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-4-1-6-and-4-2-2-release/[changelog].

[#release-4-2-1]
== Release 4.2.1

[#changelog-4-2-1]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/release-4-2-1-and-4-1-5/[changelog].

[#release-4-2-0]
== Release 4.2.0

[#changelog-4-2-0]
=== Changelog

For full details of this release see the link:https://circleci.com/server/changelog/#release-4-2-0[changelog].
