---
contentTags:
  platform:
    - Server v4.2
    - Server Admin
---
= CircleCI server v4.2 release notes
:page-layout: classic-docs
:page-liquid:
:page-description: Details of the new features included in each CircleCI server 4.2 release.
:icons: font
:toc: macro
:toc-title:

[#overview]
== Overview

The v4.2 release introduces the config policies feature to CircleCI server. Use config policies to create organization-level policies to impose rules and scopes to govern which configuration elements are required, allowed, not allowed etc. For more information see the xref:../../../config-policy-management-overview#[Config policies overview]. To use config policies CLI commands with server, append all commands shown in the docs with `--policy-base-url https://<CIRCLECI-SERVER-DOMAIN>.com`

[#upgrade]
== Upgrade
For upgrade steps see the xref:../installation/upgrade-server#[Upgrade server v4.2 guide].

CAUTION: If you are upgrading from server v4.1.x and have user-managed secrets, ensure you follow the steps in the xref:../installation/upgrade-server#[Upgrade server v4.2 guide].

[#release-4-2-6]
== Release 4.2.6

[#changelog-4-2-6]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-4-2-6[changelog].

[#release-4-2-5]
== Release 4.2.5

[#changelog-4-2-5]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-1-9-and-4-2-5[changelog].


[#release-4-2-4]
== Release 4.2.4

[#changelog-4-2-4]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-2-4[changelog].


[#release-4-2-3]
== Release 4.2.3

[#changelog-4-2-3]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-2-3[changelog].


[#release-4-2-2]
== Release 4.2.2

[#changelog-4-2-2]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-4-1-6-and-4-2-2-release/[changelog].

[#release-4-2-1]
== Release 4.2.1

[#changelog-4-2-1]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/release-4-2-1-and-4-1-5/[changelog].

[#release-4-2-0]
== Release 4.2.0

[#changelog-4-2-0]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/release-4-2-0[changelog].
