=== プライベート Orb

CircleCI Orb は、共有可能な設定パッケージであり、組織全体で様々なチームが使用できるプライベートで標準化された設定を作成していだけます。 チームやグループ間で安全に共有できるプライベート Orb を、数に制限なくご利用いただけます。

プライベート Orb に関する詳細は、<<orb-intro#private-orbs-vs-public-orbs,Orbの概要>> をご覧ください。

=== 同時実行

同時実行は、ワークフローにおいて複数のテストを同時に実行できる機能です。
 この強力な機能により、ビルド時間を削減し、フィードバックサイクルを短縮することができます。


=== セルフホストランナー

CircleCI ランナーにより、お客様のインフラを使用してジョブを実行できるため、お客様の環境をより詳細に制御することができ、さまざまなアーキテクチャでのビルドとテストを柔軟に行うことができます。

CircleCI ランナーの使用方法の詳細については、<<runner-overview#,CircleCI ランナーの概要>> を参照してください。

=== 結果の不安定なテストの検出

ワークフローの失敗による平均消費時間は約 30 分です。 不安定なテストを検出することで、ビルドやワークフローにかかる時間を大幅に短縮できます。 失敗したテストや不安定なテストのトラブルシューティングに役立つ高度なインサイトをご利用いただけます。

不安定なテストの詳細については、<<insights-tests#flaky-tests, テストインサイト>> を参照してください。

=== Docker レイヤーキャッシュ

ワークフローで常に Docker イメージを使用する開発者にとって、 Docker イメージのビルドにかかる時間の短縮は考慮すべき重要な要素です。 Docker イメージのビルドがお客様のCI/CD プロセスにおける日常作業である場合、Docker レイヤーキャッシュ(DLC) の使用をご検討ください。 DLC により、ジョブの実行に使用する実際のコンテナには影響を与えずにジョブ内で作成されるイメージレイヤーが保存されます。 Docker のパフォーマンスを活用して迅速にビルドできるよう効率化機能が設計されています。

Docker レイヤーキャッシュの詳細は、<<docker-layer-caching#,Docker レイヤーキャッシュの有効化>> を参照してください。