---
contentTags:
  platform:
    - Server v4.8
    - Server Admin
---
= Configuring external services
:page-layout: classic-docs
:page-description: This document describes how to configure the following external services for use with a CircleCI server v4.8 installation
:icons: font

This page describes how to configure external services for use with either a new CircleCI server v4.8 installation or migrating internal PostgreSQL and MongoDB data from existing CircleCI server v4.8 installation to your externalized datastores.

[#postgresql]
== PostgreSQL

[#best-practices-for-your-postgresql]
=== Best practices for PostgreSQL

NOTE: Your externalized PostgreSQL instance needs to be version 12.1 or higher.

Consider running at least two PostgreSQL replicas to allow recovery from primary failure and for backups. The table below shows the recommended specifications for PostgreSQL machines:

[.table.table-striped]
[cols=6*, options="header", stripes=even]
|===
|# of Daily Active Users
|# of PostgreSQL Replicas
|CPU
|RAM
|Disk
|NIC Speed

|<50
|2
|8 Cores
|16 GB
|100 GB
| 1 Gbps

|50 - 250
|2
|8 Cores
|16 GB
|200 GB
|1 Gbps

|250 - 1000
|3
|8 Cores
|32 GB
|500 GB
|10 Gbps

|1000 - 5000
|3
|8 Cores
|32 GB
|1 TB
|10 Gbps

|5000+
|3
|8 Cores
|32 GB
|1 TB
|10 Gbps
|===

[#migrating-from-internal-postgres]
=== Migrating from an internal PostgreSQL to an externalized source

include::../../../../_includes/snippets/server/migrate-internal-postgres-to-external.adoc[]

[#connecting-your-external-postgres]
=== Connecting your external PostgreSQL instance to CircleCI server

Once you have set up your external PostgreSQL instance, add the following to your `values.yaml` file so that your CircleCI server instance can access it.

[source,yaml]
----
postgresql:
  internal: false
  postgresqlHost: <domain> # The domain or IP address of your PostgreSQL instance
  postgresqlPort: <port> # The port of your PostgreSQL instance
----

NOTE: `postgresql.internal: false` will remove any previously deployed PostgreSQL instance deployed internally

[tab.postgres.Create_secret_yourself]
--
Create the secret and then add the following values to `values.yaml`:

[source,shell]
----
kubectl create secret generic postgresql \
  --from-literal=postgres-password=<postgres-password>
----

[source,yaml]
----
postgresql:
  ...
  auth:
    username: <username>
    existingSecret: postgresql
----
--

[tab.postgres.CircleCI_creates_secret]
--
Add the following to
the `values.yaml` file. CircleCI will create the secret automatically:

[source,yaml]
----
postgresql:
  ...
  auth:
    username: <username> # A user with the appropriate privileges to access your PostgreSQL instance.
    password: <password> # The password of the user account used to access your PostgreSQL instance.
----
--

The changes will take effect upon running `helm install/upgrade`. If you are completing a migration to an externalized PostgreSQL instance then when you perform `helm upgrade`, the scaled down pods will be scaled back to their replica numbers as defined by your `values.yaml`.


[#backing-up-postgresql]
=== Back up PostgreSQL
PostgreSQL provides official documentation for backing up and restoring your PostgreSQL 12 install, which can be found link:https://www.postgresql.org/docs/12/backup.html[here].

We strongly recommend the following:

* Take daily backups
* Keep at least 30 days of backups
* Use encrypted storage for backups as databases might contain sensitive information
* Perform a backup before each upgrade of CircleCI server

[#mongodb]
== MongoDB

NOTE: If using your own MongoDB instance, it needs to be version 3.6 or higher.

[#migrating-from-internal-mongodb]
=== Migrating from an internal MongoDB to an externalized source

include::../../../../_includes/snippets/server/migrate-internal-mongo-to-external.adoc[]

[#connecting-your-external-mongodb]
=== Connecting your external MongoDB instance to CircleCI server

Once you have configured your external MongoDB instance, add the following to your `values.yaml` file to connect your CircleCI server instance.

[source,yaml]
----
mongodb:
  internal: false
  hosts: <hostname:port> # this can be a comma-separated list of multiple hosts for sharded instances
  ssl: <ssl-enabled>
  # If using an SSL connection with custom CA or self-signed certs, set this
  # to true
  tlsInsecure: false
  # Any other options you'd like to append to the MongoDB connection string.
  # Format as query string (key=value pairs, separated by &, special characters
  # need to be URL encoded)
  options: <additional-options>
  auth:
    database: <authentication-source-database
    mechanism: SCRAM-SHA-1
----

[tab.mongo.Create_secret_yourself]
--
Create the secret and then add the following values to `values.yaml`:

[source,shell]
----
kubectl create secret generic mongodb \
--from-literal=mongodb-root-password=<root-password> \
--from-literal=mongodb-password=dontmatter
----

[source,yaml]
----
mongodb:
  ...
  auth:
    ...
    username: <username>
    existingSecret: mongodb
----
--

[tab.mongo.CircleCI_creates_secret]
--
Add the following to
the `values.yaml` file. CircleCI will create the secret automatically:

[source,yaml]
----
mongodb:
  ...
  auth:
    ...
    username: <username>
    rootPassword: <root-password>
    password: <password>
----
--

The changes will take effect upon running `helm install/upgrade`. If you are completing a migration to an externalized MongoDB instance then when you perform `helm upgrade`, the scaled down pods will be scaled back to their replica numbers as defined by your `values.yaml`.
