---
contentTags:
  platform:
    - Server v4.8
    - Server Admin
---
= Server Monitoring Stack Reference Helm Chart
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to deploy your own monitoring stack using our helm chart as a reference.
:icons: font
:toc: macro
:toc-title:


CircleCI server customers want to know what metrics are available for gaining insight into the performance of their builds. While we don't support or provide any tooling to provide observability into the running services and infrastructure CircleCI server operates in, we can share a sample of how observability can be set up using the most common tools via a helm chart package.
This is however only meant to be a reference or guide on how things could be set up and is not an officially supported product. Our reference monitoring stack currently contains samples on how to set up and configure grafana, prometheus and telegraf as well as some built-in dashboards for monitoring key service level inidicators.

You can find the link:https://github.com/CircleCI-Public/circleci-server-monitoring-reference?tab=readme-ov-file#server-monitoring-stack[reference monitoring stack on our public github] as well as more information on how you could configure it's setup.


[#included-service-level-indicators]
== Included Service Level Inidicators
Below are a list of dashboards currently included with the reference stack

=== Pipelines
==== Max Latency of Creating Pipelines
The latency of created pipelines and pipeline errors over time

==== API v2 5xx by method/route
The rate of internal server errors by method/route

=== Workflows
==== Workflow Messages Handled by Type
Sum of workflow message types over time

==== Number of handled messages


=== General Service Metrics
==== API v2 Requests Count Over Time
V2 API responses grouped by type over time

=== Orbs
==== Max Latency of Compiling Config
The latency on requests to compile orb configs

=== Insights
==== 5xx By Route
5xx errors summed by route over time on the insights API

=== Webhooks
==== Response errors
Webhook errors by type over time

=== Notifications
==== Workflows-System
Notification statuses summed by type

==== Pipelines-System IngestionError
Pipeline ingestion error rate

=== Permissions
==== Permission client calls error rate % by action excluding 4xx (expect < 0.5%)
Internal API call error rate on permissions service by request/action type

==== API Call Errors
API error responses by status

==== Failed API calls


=== Domain
==== GitHub Rate Limit Percentage
Percentage of github requests that have been rate limited

==== Timing - Providers HTTP calls, (Max, Avg)
Latency on responses from your provider (github/github enterprise)

=== Self Hosted Runner
==== Runner API - 500 HTTP Responses (Internal Server Errors)
Internal error responses from the Runner API

==== Runner Tasks - Claims (Linear Scale)
Successful Runner task claims

=== Execution
==== Task Queue Depth
Number of tasks by by execution type, excluding runner

==== Job Queue Depth
Number of jobs queued

==== Distributor External API request Errors (5xx)
Rate of internal error responses from the distributor external API

==== Distributor Internal API request Errors (5xx)
Rate of internal error responses from the distributor-internal API

==== Back Pressure
When docker job fails to provision on a nomad client, they get a backoff error which we can use to determine that the nomad clients are over burdened. Customers can use this as an indicator of why the jobs are taking so long and if they need to scale their client cluster.

==== Machine Provisioner External API Request Errors
Rate of error responses from the machine-provisioner external API

==== Output Receiver Handled Requests (non 2xx)
Non 2xx responses from  the output-receiver api

==== Output Internal Handled Requests (non 2xx)
Non 2xx responses from  the output-internal api

==== Output Public Handled Requests (non 2xx, 3xx)
Non 2xx/3xx responses from the output-public api

==== Step Receiver API request Errors (5xx)
Internal error rate for step-receiver

==== Step Internal API request Errors (5xx)
Internal error rate for the step-internal API