= Release notes
:page-platform: Server 4.10, Server Admin
:page-description: Details of the new features included in each CircleCI Server 4.10 release.
:experimental:

[#overview]
== Overview

CircleCI Server 4.10 introduces enhanced security and infrastructure management capabilities. This release adds support for configurable SSH key algorithms (RSA, ECDSA, Ed25519) to enable FIPS 140-compliant deployments and GovCloud environments. You can now delete Self-Hosted Runners resource classes directly in the web UI, customize CPU and memory resources for Nomad servers, and configure RabbitMQ memory settings. This release also includes Ubuntu 24.04 machine image support for EC2 instances.

[#upgrade]
== Upgrade

[IMPORTANT]
====
Server 4.10 requires *mongoDB 7.0* or higher and *PostgreSQL 14* or higher.

* If your MongoDB instance is not externalized then follow our xref:operator:upgrade-mongo.adoc#upgrade-mongodb-to-7[Upgrade MongoDB to 7.0 Guide] before upgrading to Server 4.10.0.

* If your PostgreSQL instance is not externalized then follow the xref:operator:upgrade-postgres.adoc[Upgrade PostgreSQL] guide before upgrading to Server 4.10.0.
====

For upgrade steps see the xref:installation:upgrade-server.adoc#[Upgrade Server 4.10 Guide].

== Release 4.10.0

For full details of this release see the link:https://circleci.com/changelog/server-release-4-10-0/[changelog].
