= Machine runner installation on macOS
:page-platform: Server v4.0 - v4.7
:page-description: Instructions on how to install CircleCI's self-hosted runner on macOS.
:experimental:
:machine:
:macos:

CAUTION: This installation method is deprecated for **CircleCI cloud** customers. Refer to the xref:install-machine-runner-3-on-linux.adoc[machine runner 3 installation guide] for the recommended steps to set up macOS self-hosted runners on CircleCI cloud.

This page describes how to install CircleCI's machine runner on macOS for **CircleCI server** customers.

[#prerequisites]
== Prerequisites

To install machine runners and run jobs, you will need to have root access, and have the following utilities and tools installed on your system:

* https://brew.sh/[Homebrew]

* https://curl.se/[curl] (installed by default on macOS)

* sha256sum (if not pre-installed):
** `brew install coreutils`

* https://www.gnu.org/software/tar/[tar]

* The xref:toolkit:local-cli.adoc[CircleCI CLI] if you wish to install runners from the command line

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

include::ROOT:partial$runner/terms.adoc[]

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

[tabs]
====
Web app installation::
+
--
include::ROOT:partial$runner/install-with-web-app-steps.adoc[]
--
CLI installation::
+
--
include::ROOT:partial$runner/install-with-cli-steps.adoc[]

--
====


[#download-the-launch-agent-script]
== 2. Download launch-agent script and install binary

include::ROOT:partial$runner/launch-agent-download.adoc[]

[#create-a-circleci-self-hosted-runner-configuration]
== 3. Create self-hosted runner configuration

You will need to choose a user to run the CircleCI agent. These instructions refer to the selected user as `USERNAME`. The `USERNAME` refers to the user on the machine that the agent will be installed on, _not_ the CircleCI account username.

Complete the template shown below, with the various capitalized parameters filled in. When complete, save the template as `launch-agent-config.yaml`.

```yaml
api:
  auth_token: AUTH_TOKEN
  # On server, set url to the hostname of your server installation. For example,
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  command_prefix : ["sudo", "-niHu", "USERNAME", "--"]
  working_directory: /var/opt/circleci/workdir
  cleanup_working_directory: true

logging:
  file: /Library/Logs/com.circleci.runner.log
```

- Replace `AUTH_TOKEN` with the resource class token created in the <<create-namespace-and-resource-class,set up process>>.
- Replace `RUNNER_NAME` with the name you would like for your self-hosted runner. `RUNNER_NAME` is unique to the machine that is installing the runner. `RUNNER_NAME` can be any value you would like, and it does not need to include any part of your namespace or resource class name. However, it is recommended to use the hostname of the machine so that it can be used to identify the agent when viewing statuses and job results in the CircleCI web app. The only special characters accepted in RUNNER_NAME are `. () - _`.

[#update-workdir-ownership]
== 4. Update working directory permission

The CircleCI agent requires write permission to the directory containing the working directory. Change the ownership of that directory to `USERNAME`:

```shell
sudo chown USERNAME /var/opt/circleci
```

[#install-the-circleci-self-hosted-runner-configuration]
== 5. Install the self-hosted runner configuration

Create a directory as `root` to hold the CircleCI's self-hosted runner configuration:

```shell
sudo mkdir -p '/Library/Preferences/com.circleci.runner'
```

Copy the previously created `launch-agent-config.yaml` into the directory and change its permissions to `600`:

```shell
sudo cp "launch-agent-config.yaml" "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

```shell
sudo chmod 600 "/Library/Preferences/com.circleci.runner/launch-agent-config.yaml"
```

[#create-and-install-the-launchd-plist]
== 6. Create and install `launchd .plist`

Create a `com.circleci.runner.plist` file with a path of `/Library/LaunchDaemons/com.circleci.runner.plist`, owned by `root`, with permissions `644`. Use the following commands:

```shell
sudo touch /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chown root: /Library/LaunchDaemons/com.circleci.runner.plist
```

```shell
sudo chmod 644 /Library/LaunchDaemons/com.circleci.runner.plist
```

Copy the following to the new `/Library/LaunchDaemons/com.circleci.runner.plist` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.circleci.runner</string>

        <key>Program</key>
        <string>/opt/circleci/circleci-launch-agent</string>

        <key>ProgramArguments</key>
        <array>
            <string>circleci-launch-agent</string>
            <string>--config</string>
            <string>/Library/Preferences/com.circleci.runner/launch-agent-config.yaml</string>
        </array>

        <key>RunAtLoad</key>
        <true/>

        <!-- The agent needs to run at all times -->
        <key>KeepAlive</key>
        <true/>

        <!-- This prevents macOS from limiting the resource usage of the agent -->
        <key>ProcessType</key>
        <string>Interactive</string>

        <!-- Increase the frequency of restarting the agent on failure, or post-update -->
        <key>ThrottleInterval</key>
        <integer>3</integer>

        <!-- Wait for 10 minutes for the agent to shut down (the agent itself waits for tasks to complete) -->
        <key>ExitTimeOut</key>
        <integer>600</integer>

        <!-- The agent uses its own logging and rotation to file -->
        <key>StandardOutPath</key>
        <string>/dev/null</string>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
    </dict>
</plist>
```

[#enable-the-launchd-service]
== 7. Enable `launchd` service

Now you can load the service:

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

NOTE: If you are following these instructions for a second time, use the command below to unload the existing service. Once the existing service is unloaded, you can load the new service with the command above.

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#verify-the-service-is-running]
== 8. Verify the service is running

Open the pre-installed macOS application *Console*. In this application, you can view the logs for the CircleCI agent under *Log Reports*. Look for the logs called `com.circleci.runner.log` in the list. You can also find this file by navigating to *Library > Logs*.

include::ROOT:partial$runner/machine-runner-example.adoc[]

[#troubleshooting]
== Troubleshooting

Refer to the <<troubleshoot-self-hosted-runner#machine-runner,Troubleshoot Machine Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running machine runner on macOS.
