url: "https://static-staging.circleci.com"
rollbar_env: development

defaults:
  - scope:
      path: ""
      type: "cci2"
    values:
      lang: "en"

  - scope:
      path: ""
      type: "cci2_ja"
    values:
      lang: "ja"

  - scope:
      path: ""
    values:
      hide: false
      search: true

  # Enable TOC by default
  - scope:
      path: ""
    values:
      toc: true

  # Disable helpful resources section by default
  - scope:
      path: ""
    values:
      suggested: false

  # Enable sitemap in staging
  - scope:
      path: ""
    values:
      sitemap: true
