= Policies
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

// Might need to divide this into separate pages

A policy is a set of rules that defines how a version of a service should be validated when it is added to an application. If the policy conditions are not met, the new version is rolled back, with minimal impact on your users' experience.

In Site Reliability Engineering (SRE) terms, a policy validates that a new version of a service complies with the SLOs defined for that service.

== Choosing a Release Policy

Vamp supports two classes of policy: _release policies_ and _validation-only policies_.

=== Release Policies

A release policy defines a set of validation rules for how Vamp objectively tests if a version of a service meets its objectives. It also defines the <<segments#,user segments>> to be targeted during the tests.

Release policies are used for services that support progressive releases using traffic shaping. 

Normally as the release progresses, increasing numbers of API requests are sent to the newly deployed version of the service. If it passes all the tests defined in the policy, then it is designated as the live version, replacing the current version.

If validation of the newly deployed version of the service fails for any reason, it is rolled back. The current version remains live and receives all API requests. The failed version no longer receives any API requests.

=== Validation-Only Policies

A validation-only policy defines the set validation rules to objectively test whether a version of a service meets its objectives.

Validation-only policies rely on calling a user-defined webhook to roll back a failed version. If the newly released version passes all the tests defined in the policy, it remains the live version. 

If validation of the newly deployed version of the service fails for any reason, Vamp calls a webhook to roll back the service to the previous version. Typically, this webhook triggers an action on a CD pipeline.

=== Setting a Default Policy

You are prompted to choose the default policy for each of your services.

=== Configuring Advanced Policies

The default policy is used when there is no specific policy set for major, minor or patch releases. If you select the Advanced option, you can set specific policies for major, minor and patch releases. 

==== Major Release
A major release is a feature release that introduces one or more breaking changes, for example, deprecating an API endpoint.

For major releases, you usually want to use a longer running policy that validates a mix of technical and business metrics.

Vamp uses the major release policy if the new version is at least one major version higher than the version that is currently live. For example, a change of semantic version from 1.2.3 to 2.0.1 is a major release.

==== Minor Release

A minor release is a feature release that introduces new functionality without changing any of the existing functionality, for example, adding an API endpoint.

For minor releases, you usually want to use a shorter running policy that validates a mix of technical and business metrics.

Vamp uses the minor release policy if the new version is at least one minor version higher than the version that is currently live. For example, a change of semantic version from 1.2.3 to 1.3.4 is a minor release.

==== Patch Release

A patch release can be a planned maintenance release to fix bugs, or an update to the versions of software libraries. A patch release can also be an emergency release to quickly address critical security or performance issues. A patch release should not add or remove functionality.

For patch releases, you usually want to use a quick running policy that validates mostly technical metrics.

Vamp uses the patch release policy if the new version is at least one patch version higher than the version that is currently live. For example, a change of semantic version from 1.2.3 to 1.2.4 is a patch release.

== Built-in Metrics

By default, Vamp includes the following metrics.

=== Kubernetes-related metrics

*Kubernetes Pod Restarts*

NOTE: Every release policy must include a condition for Kubernetes Pod restarts. 

Kubernetes Pod restarts are a good indicator of the basic performance of your service.

Kubernetes restarts a Pod if it fails its regular _liveness probe_. Kubernetes uses liveness probes to catch situations where an application is running but unable to make progress. Restarting a container in such a state can help to make the application more available, even if there are bugs.

Typically, a newly deployed version of a service will experience no restarts during a release, so you can set a low budget, for example,  fewer than two restarts per five-minute window.

==== Kubernetes Minimum Available Pods

TIP: We recommend including a condition for Kubernetes Minimum Available Pods in the first step of a multi-step release policy.

// link to release policy

The Kubernetes Minimum Available Pods metric is a good indicator of whether a newly deployed version of your service is stable enough to be released.

This metric corresponds to the generic Kubernetes _Does not have minimum availability_ message seen when a workload is deployed. This can be caused by the nodes in the cluster lacking sufficient resources to run some or all of the requested Pods. It can also be caused by a misconfiguration, for example, a missing Kubernetes Secret.

==== Available Kubernetes Pods

The _Available Kubernetes Pods_ metric can be a useful indicator of both the stability and the efficiency of your service.

Kubernetes marks a Pod as unavailable if it fails its regular readiness probe. 

If you use a Horizontal Pod Autoscaler (HPA) to manage the number of Pods, a larger than expected number of available Pods can be an indicator that your new version is using more CPU or memory than expected.

=== REST and GraphQL API Metrics

// There are some warning messages here about NGINX, linking to some GitHub issues. It looks as though those issues have been resolved. Am awaiting clarification.

==== API Success Rate

If your service exposes a REST API or GraphQL API, the API Success Rate metric indicates how many of the requests returned an error instead of the expected response.

==== API Request Duration

If your service exposes a REST API or GraphQL API, the API Request Duration metric indicates the average response time in milliseconds (ms).

== Viewing and Creating Custom Metrics

To view your current custom metrics, click _Metrics_ under the _Policies_ tab.

To create a custom metric, click *+Create Metric* in the top right-hand corner of the Metrics page.

== Viewing Policies

To view the available policies, click the _Policies_ tab.

== Creating Policies

See the <<creating-policy#,Creating Policies doc>> for more information.









