= Services
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

Under the _Services_ tab, you can view your services and the number of deployed versions for each service.

Click on the *+* sign to show the applications where each version is currently deployed and whether the instances deployed for that application are healthy.

// screenshot

== Creating a Service

To create a service, click the *+Create Service* button on the Services page.

// screenshot

{% include release-orchestration/services.adoc %}

When you have finished adding the details, click the *Create service* button. You will then see a pop-up message to confirm that you service has been created.

== Editing a Service

To edit a service, click *Details* next to the service in the list.

From here, you can also add metadata to your service, under the _Metadata_ tab.

// Need to add something on metadata!

When you have finished editing the details, click the *Update service* button. You will then see a pop-up message to confirm that you service has been updated.

== Deleting a Service

To delete a service, click *Details* next to the service in the list, then click the red *Delete service* button at the bottom of the page.

// screenshot

You will then see a pop-up message to confirm that you service has been deleted.