---
contentTags:
  platform:
    - Server v4.3
    - Server Admin
---
= Upgrade server
:page-layout: classic-docs
:page-liquid:
:page-description: "This document lists the steps required to upgrade a CircleCI server v4.3 installation."
:icons: font
:toc: macro
:toc-title:

This page describes the steps needed to upgrade your CircleCI server v4.3 installation.

A successful deployment will update the web app. Unless noted in the release notes, updates are rolling updates and there is no downtime.

NOTE: We recommend that you do not skip releases when upgrading.

NOTE: Related to new execution systems
* Docker Layer Caching (DLC)
** old docker layer caching (dlc) volumes will not be carried over and need to be wiped manually
** projects that stop using dlc wont delete final DLC cache without manual intervention
** dlc now runs through S3 and GCS instead of SSD Volumes

* Machine Jobs
** machine jobs will now run through machine provisioner
** When migrating vm-gc will need to cleanup all machines left running before it is removed. All other vm-service related
pods can be removed during migration first. If this is not followed vm-service machines will not be cleaned up without manual intervention.
This can alternatively be done by just manually cleaning up remaining vms before starting machine-provisioner.
** Machine and Remote docker jobs no longer flow through nomad and run completely in a single machine. Nomad is NOT required to run machine jobs.
** If deploying in specific zone need to specify subnetwork for gcp
** IAM users have changed names to end with machine-provisioner instead of vm-service so some users might need to be altered.

* Docker jobs
** Run through nomad, but are orchestrated through docker-provisioner

* Storage
** Excluding DLC, historical artifacts will continue to be supported in new execution system with no user changes

[#prerequisites]
== Prerequisites

* Ensure you have access to the Kubernetes cluster in which server is installed.
* Ensure you have set up xref:../operator/backup-and-restore#[Backup and Restore].
* Ensure there is a recent backup. For more information, see the xref:../opertor/backup-and-restore#creating-backups[Backup and Restore] guide.

[#upgrade-steps]
== Upgrade steps

. Check the link:https://circleci.com/server/changelog/[changelog] and make sure there are no actions you need to take before deploying a new version.

. For upgrade from 4.2:
* Remove vm_service block from values file
* Add machine_provisioner block to values file
* Add docker_provisioner block to values file
* Update vm-service IAM Policy (machine-provisioner requires slightly different permissions)

. Optionally, confirm what the update is going to do using link:https://github.com/databus23/helm-diff[Helm Diff]:
+
[source,shell]
helm diff upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD

. Perform the upgrade:
+
[source,shell]
helm upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD

. Deploy and run link:https://github.com/circleci/realitycheck[`reality check`] in your test environment to ensure your installation is fully operational.
