---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Benefits of CircleCI
:page-layout: classic-docs
:page-liquid:
:page-description: Benefits of choosing CircleCI for CI/CD
:icons: font
:experimental:


[#benefits-of-circleci]
== Benefits of CircleCI

Organizations choose CircleCI because jobs run fast and builds can be optimized for speed. CircleCI can be configured to run very complex pipelines efficiently with sophisticated xref:caching#[caching], xref:docker-layer-caching#[Docker layer caching], and xref:optimizations#resource-class[resource classes] for running on faster machines.

As a developer using CircleCI you can:

- xref:ssh-access-jobs#[SSH into any job] to debug your build issues.
- Set up xref:parallelism-faster-jobs#[parallelism] in your `.circleci/config.yml` file to run test jobs faster.
- Configure xref:caching#[caching] with two simple keys to reuse data from previous jobs in your xref:workflows#[workflow].
- Configure self-hosted xref:runner-overview#[runners] for unique platform support.
- Access xref:using-arm#[Arm VM resources] and xref:using-docker#arm[Arm on Docker].
- Use xref:orb-intro#[orbs], reusable packages of configuration, to integrate with third parties.
- Use pre-built Docker xref:circleci-images#[images] in a variety of languages.
- Use the link:https://www.circleci.com/docs/api/v2[API] to retrieve information about jobs and workflows.
- Use the xref:local-cli#[CLI] to access advanced tools locally.
- Get flaky test detection with xref:insights-tests#[test insights].

As an operator or administrator of CircleCI installed on your own servers, CircleCI provides monitoring and insights into your builds and uses link:https://www.nomadproject.io/[Nomad] for scheduling.

See the xref:server/overview/circleci-server-v4-overview#[CircleCI server overview] for server documentation.

[#pricing-options]
== Pricing options

Visit CircleCI's link:https://circleci.com/pricing[Pricing page] to view free and paid options.

You can link:https://circleci.com/signup[sign up] for free to get access to unlimited projects on CircleCI's fully-hosted cloud platform.

Organizations on the free plan are given free credits to use on open source projects. Visit the xref:oss#[Building open source projects] page for more information about free containers for public open source projects.

[#next-steps]
== Next steps

- xref:first-steps#[Sign up and try]
