---
description: Open preview of config policy management for CircleCI
version:
- Cloud
---
= Config policy reference
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

NOTE: Config policy management is available on the **Scale** plan and is currently in **open preview**. All aspects of the feature are subject to change.

This reference page lists a selection of _helpers_, or CircleCI-specific funtions that are likely to be useful for you when you are writing your policies. These helpers will lead to _cleaner_ policies with less boilerplate.

The `circle-policy-agent` package includes built-in functions for common config policy
use cases. All policies evaluated by the `policy-service`, the `circle-cli`, or the `circle-policy-agent`
will be able to access these functions. This also means the package name `circleci.config` is
reserved.

[#circleci-rego-helpers]
== CircleCI rego helpers

[#jobs]
=== `jobs`

`jobs` is a Rego object containing jobs that are present in the given CircleCI config file. It 
can be utilized by policies related to jobs.

[#definition-jobs]
==== Definition

[source,rego]
----
jobs = []string
----

Example `jobs` object:

[source,json]
----
[
    "job-a",
    "job-b",
    "job-c"
]
----

[#usage-jobs]
==== Usage

[source,rego]
----
package org

policy_name["example"]

import future.keywords
import data.circleci.config

jobs := config.jobs
----

[#require-jobs]
=== `require_jobs`

This function requires a config to contain jobs based on the job names. Each job in the list of 
required jobs must be in at least one workflow within the config.

[#definition-require-jobs]
==== Definition

[source,rego]
----
require_jobs([string])
returns { string }
----

[#usage-require-jobs]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_jobs = config.require_jobs(["security-check", "vulnerability-scan"])

enable_rule["require_security_jobs"]

hard_fail["require_security_jobs"]
----

[#orbs]
=== `orbs`

`orbs` is a `rego` object containing orbs and versions present in the given config file. It 
can be utilized by policies related to orbs.

[#definition-orbs]
==== Definition

[source,rego]
----
orbs[string] = string
----

Example `orbs` object:

[source,json]
----
{
    "circleci/security": "1.2.3",
    "circleci/foo": "3.2.1"
}
----

[#usage-orbs]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

my_orbs := config.orbs
----

[#require-orbs]
=== `require_orbs`

This function requires a config to contain orbs based on the orb names. Versions should not 
be included in the provided list of orbs.

[#definition-require-orbs]
==== Definition

[source,rego]
----
require_orbs([string])
returns { string: string }
----

[#usage-require-orbs]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_security_orbs = config.require_orbs(["circleci/security", "foo/bar"])

enable_rule["require_security_orbs"]

hard_fail["require_security_orbs"]
----

[#require-orbs-version]
=== `require_orbs_version`

This function requires a policy to contain orbs based on the orb name and version.

[#definition-require-orbs-version]
==== Definition

[source,rego]
----
require_orbs_version([string])
returns { string: string }
----

[#usage-require-orbs-version]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

require_orbs_versioned = config.require_orbs_version(["circleci/security@1.2.3", "foo/bar@4.5.6"])

enable_rule["require_orbs_versioned"]

hard_fail["require_orbs_versioned"]
----

[#ban-orbs]
=== `ban_orbs`

This function violates a policy if a config includes orbs based on the orb name. Versions should not 
be included in the provided list of orbs.

[#definition-ban-orbs]
==== Definition

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs = config.ban_orbs(["evilcorp/evil"])

enable_rule["ban_orbs"]

hard_fail["ban_orbs"]
----

[#ban-orbs-version]
=== `ban_orbs_version`

This function violates a policy if a config includes orbs based on the orb name and version.

[#definition-ban-orbs-version]
==== Definition

[source,rego]
----
ban_orbs_version([string])
returns { string: string }
----

[#usage-ban-orbs-version]
==== Usage

[source,rego]
----
package org

import data.circleci.config

policy_name["example"]

ban_orbs_versioned = config.ban_orbs_version(["evilcorp/evil@1.2.3", "foo/bar@4.5.6"])

enable_rule["ban_orbs_versioned"]

hard_fail["ban_orbs_versioned"]
----

[#resource-class-by-project]
=== `resource_class_by_project`

This function take a resource_class to project_id set mapping. The resource_classes defined in the
mapping will be reserved for its associated projects. Resource classes not included in the mapping will
still be available for use by any project.

[#definition-resource-class-by-project]
==== Definition

```rego
resource_class_by_project({
  "$RESOURCE_CLASS": {$PROJECT_IDS...},
  ...
})
returns { ...reasons: string }
```

[#usage-resource-class-by-project]
==== Usage

[source,rego]
----
package org

import future.keywords
import data.circleci.config

policy_name["example"]

check_resource_class = config.resource_class_by_project({
  "large": {"$PROJECT_UUID_A","$PROJECT_UUID_B"},
})

enable_rule["check_resource_class"]

hard_fail["check_resource_class"]
----
