---
description: Open preview of config policy management for CircleCI
version:
- Cloud
---
= Config policy reference
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

The `circle-policy-agent` package includes built-in functions for common config policy
use cases. All policies evaluated by the `policy-service`, the `circle-cli`, or the `circle-policy-agent`
will be able to access these functions. This also means the package name `circleci.config` is
reserved.

## CircleCI rego helpers

### `jobs`

`jobs` is a Rego object containing jobs that are present in the given CircleCI config file. It 
can be utilized by policies related to jobs.

#### Definition

```
jobs = []string
```

Example `jobs` object:

```json
[
    "job-a",
    "job-b",
    "job-c"
]
```

#### Usage

```rego
package org

policy_name["example"]

import future.keywords
import data.circleci.config

jobs := config.jobs
```


### `require_jobs`

This function requires a config to contain jobs based on the job names. Each job in the list of 
required jobs must be in at least one workflow within the config.

#### Definition

```rego
require_jobs([string])
returns { string }
```

#### Usage

```rego
package org

import data.circleci.config

policy_name["example"]

require_security_jobs = config.require_jobs(["security-check", "vulnerability-scan"])

enable_rule["require_security_jobs"]

hard_fail["require_security_jobs"]
```

### `orbs`

`orbs` is a Rego object containing orbs and versions present in the given config file. It 
can be utilized by policies related to orbs.

#### Definition

```rego
orbs[string] = string
```

Example `orbs` object:
```json
{
    "circleci/security": "1.2.3",
    "circleci/foo": "3.2.1"
}
```

#### Usage
{: #rego-helpers-orbs-usage }

```rego
package org

import data.circleci.config

policy_name["example"]

my_orbs := config.orbs
```


### `require_orbs`
{: #rego-helpers-require-orbs }

This function requires a config to contain orbs based on the orb names. Versions should not 
be included in the provided list of orbs.

#### Definition
{: #rego-helpers-require-orbs-definition }

```
require_orbs([string])
returns { string: string }
```

#### Usage
{: #rego-helpers-require-orbs-usage }

```rego
package org

import data.circleci.config

policy_name["example"]

require_security_orbs = config.require_orbs(["circleci/security", "foo/bar"])

enable_rule["require_security_orbs"]

hard_fail["require_security_orbs"]
```

### `require_orbs_version`
{: #rego-helpers-require-orbs-version }

This function requires a policy to contain orbs based on the orb name and version.

#### Definition
{: #rego-helpers-require-orbs-version-definition }

```
require_orbs_version([string])
returns { string: string }
```

#### Usage
{: #rego-helpers-require-orbs-version-usage }

```rego
package org

import data.circleci.config

policy_name["example"]

require_orbs_versioned = config.require_orbs_version(["circleci/security@1.2.3", "foo/bar@4.5.6"])

enable_rule["require_orbs_versioned"]

hard_fail["require_orbs_versioned"]
```

### `ban_orbs`
{: #rego-helpers-ban-orbs }

This function violates a policy if a config includes orbs based on the orb name. Versions should not 
be included in the provided list of orbs.

#### Definition
{: #rego-helpers-ban-orbs-defintion }

```rego
ban_orbs_version([string])
returns { string: string }
```

#### Usage
{: #rego-helpers-ban-orbs-usage }

```rego
package org

import data.circleci.config

policy_name["example"]

ban_orbs = config.ban_orbs(["evilcorp/evil"])

enable_rule["ban_orbs"]

hard_fail["ban_orbs"]
```

### `ban_orbs_version`
{: #rego-helpers-ban-orbs-version }

This function violates a policy if a config includes orbs based on the orb name and version.

#### Definition
{: #rego-helpers-ban-orbs-version-definition }

```rego
ban_orbs_version([string])
returns { string: string }
```

#### Usage
{: #rego-helpers-ban-orbs-version-usage }

```rego
package org

import data.circleci.config

policy_name["example"]

ban_orbs_versioned = config.ban_orbs_version(["evilcorp/evil@1.2.3", "foo/bar@4.5.6"])

enable_rule["ban_orbs_versioned"]

hard_fail["ban_orbs_versioned"]
```

### `resource_class_by_project`
{: #rego-helpers-resource-class-by-project }

This function take a resource_class to project_id set mapping. The resource_classes defined in the
mapping will be reserved for its associated projects. Resource classes not included in the mapping will
still be avaible for use by any project.

#### Definition
{: #rego-helpers-resource-class-by-project-definition }

```rego
resource_class_by_project({
  "$RESOURCE_CLASS": {$PROJECT_IDS...},
  ...
})
returns { ...reasons: string }
```

#### Usage

```rego
package org

import future.keywords
import data.circleci.config

policy_name["example"]

check_resource_class = config.resource_class_by_project({
  "large": {"$PROJECT_UUID_A","$PROJECT_UUID_B"},
})

enable_rule["check_resource_class"]

hard_fail["check_resource_class"]
```
