---
contentTags: 
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Container runner installation (Kubernetes)
:page-layout: classic-docs
:page-liquid:
:page-description: This page summarizes concurrency, and suggests ways to use concurrency to your advantage.
:icons: font
:toc: macro
:toc-title:

This page describes how to install CircleCI's container runner.

{% include snippets/runner-platform-prerequisites.adoc %}

== Installation instructions

1. Add the container runner Helm repo by running `helm repo add container-agent https://packagecloud.io/circleci/container-agent/helm`

2. Run `helm repo update`

3. Modify the `values.yaml` file with the following:
+
```yaml
agent:
  resourceClasses:
    namespace/my-rc:
      token: MY_TOKEN
```
+
4. Run `helm install container-agent circleci/container-agent -n circleci`

[#container-runner-configuration-example]
== Container runner configuration example

Once you have installed the container runner within your cluster, create and trigger a CircleCI job that uses the Docker executor to validate the installation. The fields you must set for a specific job to run using your self-hosted runners are:

* `image:`
* `resource_class: <namespace>/<resource-class>`

Simple example of how you could set up a job (`cimg/base:2021.11` is a commonly used CirlceCI Docker image):

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: <namespace>/<resource-class>
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
```

CAUTION: **Do not** use an existing job that uses <<building-docker-images#,setup_remote_docker>> (see <<container-runner#building-container-images,Building container images>> for more information).