---
contentTags:
  platform:
  - Cloud
---
= Container runner installation (Kubernetes)
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to install CircleCI's container runner.
:icons: font
:experimental:
:container:

This page describes how to install CircleCI's container runner.

// {% include snippets/runner-platform-prerequisites.adoc %}

[#prerequisites]
== Prerequisites

{% include snippets/runner/container-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

[.tab.container-runner.Web_app_installation]
--
{% include snippets/runner/install-with-web-app-steps.adoc %}
--
[.tab.container-runner.CLI_installation]
--
{% include snippets/runner/install-with-cli-steps.adoc %}
--

[#container-runner-installation]
== 2. Container runner installation

. Add the container runner Helm repo by running the following command:
+
[source,shell]
----
helm repo add container-agent https://packagecloud.io/circleci/container-agent/helm
----

. Next, run the following:
+
[source,shell]
----
helm repo update
----

. Then, run the following command to create the `circleci` Kubernetes namespace:
+
[source,shell]
----
kubectl create namespace circleci
----

. Create a file called `values.yaml` file containing the following:
+
```yaml
agent:
  resourceClasses:
    namespace/my-rc:
      token: <resource_class_token>
```

. Finally, run the following command:
+
[source,shell]
----
helm install container-agent container-agent/container-agent -n circleci -f values.yaml
----

[#container-runner-configuration-example]
== Container runner configuration example

Once you have installed the container runner within your cluster, create and trigger a CircleCI job that uses the Docker executor to validate the installation. The fields you must set for a specific job to run using your container runners are:

* `image:`
* `resource_class: <namespace>/<resource-class>`

Simple example of how you could set up a job (`cimg/base:2021.11` is a commonly used CircleCI Docker image):

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: <namespace>/<resource-class>
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
```

CAUTION: **Do not** use an existing job that uses <<building-docker-images#,setup_remote_docker>> (see <<container-runner#building-container-images,Building container images>> for more information).

[#troubleshooting]
== Troubleshooting

Refer to the <<troubleshoot-self-hosted-runner#troubleshoot-container-runner,Troubleshoot Container Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running container runner.

[#additional-resources]
== Additional resources

- xref:container-runner.adoc[Container runner reference guide]
- xref:runner-concepts.adoc[Self-hosted runner concepts]
- xref:runner-faqs.adoc[Self-hosted runner FAQ]
