---
contentTags:
  platform:
  - Cloud
---
= Dedicated hosts for macOS
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about CircleCI's dedicated host resource class offering for macOS users.
:icons: font
:experimental:

The dedicated host resource class is available for those developing, building, testing, and signing iOS, iPadOS, macOS, WatchOS, and tvOS applications using the Xcode IDE. These dedicated resources provide an isolated environment for increased security.

This resource class requires a 24-hour minimum lease and runs on Intel-based Mac hardware.

The identifier for the dedicated host resource is `macos.x86.metal.gen1`, and supports the same Xcode images as the other macOS resource classes, with the exception of Xcode 10.3. Refer to the link:https://circleci.com/docs/using-macos/#supported-xcode-versions[Supported Xcode versions section] of the Testing iOS page for the full list of versions.

[#pricing-and-specs]
== Pricing and specs

[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
| Class
| vCPUs
| RAM
| Total Storage
| Cost

| `macos.x86.metal.gen1`
| 12
| 32 GB
| 200 GB
| 100 credits per minute (24-hour minimum)
|===

Each account has a maximum of one dedicated host by default. You can increase the maximum number by contacting link:https://support.circleci.com/hc/en-us/requests/new[CircleCI support], or your account representative.

Once a dedicated host has been allocated, you have exclusive access to it for a minimum of 24 hours. If the dedicated host is already in use when a job is kicked off, the job is queued until the host becomes available, unless you have increased your dedicated host limit.

[#support-xcode-versions]
== Supported Xcode versions

include::../_includes/snippets/xcode-metal.adoc[]

[#known-limitations]
== Known limitations

- The resource class does not currently support test splitting or parallelism.
- The host gets cleaned between jobs, which can currently take 5 to 45 minutes. We recommend running more than one dedicated host concurrently to help minimize the impact of this scrubbing process. Contact support or your account representative to increase your limit.

[#example-configuration-file-using-macos-dedicated-host-resources]
== Example configuration file using macOS dedicated host resources

```yaml
# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1 # indicate your selected version of Xcode
    resource_class: macos.x86.metal.gen1 # dedicated host, with 24-hour billing
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
```

[#dedicated-hosts-macos-faqs]
== FAQs

include::../_includes/snippets/faq/dedicated-hosts-macos-faq-snip.adoc[]