---
description: This document provides examples of publishing to the NPM registry.
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Publish to npm registry
:page-layout: classic-docs
:page-liquid:
:icons: font
:experimental:

In this how-to guide, you will learn how to configure CircleCI to publish to the npm registry.

[#introduction]
== Introduction

Setting up CircleCI to publish packages to the npm registry makes it easy for project collaborators to release new package versions in a consistent and predictable way.

[#obtain-the-npm-authToken]
== 1. Get the npm `authToken`

Get the npm `authToken` for the account that you wish to use to publish the package. You can do this by logging in to npm (`npm login`). This will save the `authToken` to the `~/.npmrc` file. Look for the following line:

```shell
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```

In this case, the `authToken` is `00000000-0000-0000-0000-000000000000`.

[#set-npm-token]
== 2. Set npm token
Go to your xref:environment-variables#setting-environment-variables-for-all-commands-without-adding-them-to-git[project settings], and set the `NPM_TOKEN` variable to the obtained `authToken`.

[#configure-circleci]
== 3. Configure CircleCI

Configure CircleCI to add the `authToken` to `~/.npmrc`, run `npm publish` and only for versioned tags:

```yaml
version: 2.1

jobs:
  publish:
    docker:
      - image: <docker-image-name-tag>
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
```

[#create-new-version]
== 4. Create a new version

When you want to publish a new version to npm, run `npm version` to create a new version:

```shell
npm version 10.0.1
```

This will update the `package.json` file and creates a tagged Git commit. Next, push the commit with tags:

```shell
git push --follow-tags
```
[#publish]
== 5. Publish

If tests passed, CircleCI will publish the package to npm automatically.
