---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Deployment overview
:page-layout: classic-docs
:page-liquid:
:page-description: Learn the basics of CircleCI deployment.
:icons: font
:experimental:

[#introduction]
== Introduction

After you've developed and tested your software application, you need to deploy it to make it available to the intended audience. CircleCI can deploy your applications to virtually any target, and you can configured it to integrate with other services for QA/testing, feature management, and deployment strategies such as blue-green or canary deployment. You can quickly and easily customize your configuration to match your requirements, whether you want a fully automated process or you want to include manual approvals.

[#the-basics-of-deployment]
== The basics of deployment

Nearly every deployment includes a few key elements:

* **Deployment job**: To deploy your application, add a <<jobs-steps#jobs-overview,job>> to your `.circleci/config.yml` file and configure the job to run the steps you require. [Next steps](#next-steps) has example configurations for common deployment targets.

* **Deployment parameters**: You might need to add environment variables and SSH keys to fulfill your deployment steps. You can add environment variables to a project by using the CircleCI web app (follow links below for detailed instructions), or by defining them within your configuration.
** Add project-level <<set-environment-variable#set-an-environment-variable-in-a-project,environment variables>>
** Add project-level <<add-ssh-key#,SSH keys>>

* **Manual approval**: To require a manual approval, include a <<workflows#holding-a-workflow-for-a-manual-approval,hold/approve>> job within your workflow. A manual approval button will then be available from the workflows map in the CircleCI web app.

[#using-orbs-to-simplify-deployment]
== Using orbs to simplify deployment

CircleCI offers packages of reusable configuration known as <<orb-intro#,orbs>>. Orbs are available for many common deployment targets and they help to simplify and streamline your configuration. Check out the full range of available orbs in the link:https://circleci.com/developer/orbs[Orbs Registry]. For simple deployment pipelines, using orbs will get you the results you need with minimal configuration.

For example, consider the https://circleci.com/developer/orbs/orb/circleci/aws-code-deploy[AWS CodeDeploy orb]. This orb has a preconfigured `deploy` job, which you can include in your configuration with a single line `aws-code-deploy/deploy` once the orb has been invoked by adding the orbs stanza. For this example, deployment can be as simple as:

```yaml
version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@x.y
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: myApplication
          bundle-bucket: myApplicationS3Bucket
          bundle-key: myS3BucketKey
          deployment-group: myDeploymentGroup
          service-role-arn: myDeploymentGroupRoleARN
```

This orb creates, bundles and deploys your application using your specified parameters set under the `aws-code-deploy/deploy` job declaration.

[#using-images-to-simplify-deployment]
== Using images to simplify deployment

CircleCI offers convenience images for use with Docker that contain tools required for common deployment scenarios. Convenience images provide fast spin-up times, as well as reliability and stability. Visit these link:https://circleci.com/developer/images?imageType=docker[CircleCI Developer Hub] pages to learn more about each of the deployment convenience images.

- link:https://circleci.com/developer/images/image/cimg/deploy[cimg/deploy]
- link:https://circleci.com/developer/images/image/cimg/aws[cimg/aws]
- link:https://circleci.com/developer/images/image/cimg/azure[cimg/azure]
- link:https://circleci.com/developer/images/image/cimg/gcp[cimg/gcp]

[#next-steps]
== Next steps

* <<deploy-to-amazon-sagemaker#,Deploy to Amazon SageMaker>>
* <<deploy-android-applications#,Deploy Android applications>>
* <<deploy-to-artifactory#,Deploy to Artifactory>>
* <<deploy-to-aws#,Deploy to AWS>>
* <<deploy-service-update-to-aws-ecs#,Deploy to AWS ECS>>
* <<ecs-ecr#,Deploy to AWS ECR/ECS>>
* <<deploy-to-azure-container-registry#,Deploy to Azure Container Registry>>
* <<deploy-to-capistrano#,Deploy to Capistrano>>
* <<deploy-to-cloud-foundry#,Deploy to Cloud Foundry>>
* <<deploy-to-firebase#,Deploy to Firebase>>
* <<deploy-to-google-cloud-platform#,Deploy to Google Cloud Platform>>
* <<deploy-to-heroku#,Deploy to Heroku>>
* <<deploy-ios-applications#,Deploy iOS applications>>
* <<deploy-to-npm-registry#,Deploy to NPM registry>>
* <<deploy-over-ssh#,Deploy over SSH>>
* <<authorize-google-cloud-sdk#,Authorize Google Cloud SDK>>
* <<publish-packages-to-packagecloud#,Publish packages to packagecloud>>

Visit the link:https://circleci.com/developer/orbs[orbs registry] to see if there's an orb for your deployment target to help keep your configuration simple. If not, consider <<orb-author-intro#,authoring one>>!
