---
description: "This is document provides examples of deploying to the NPM registry"
contentTags: 
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
  - Server v2.x
---
= Deploy to NPM registry
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Setting up CircleCI to publish packages to the npm registry makes it easy for project collaborators to release new package versions in a consistent and predictable way.

1.  Obtain the npm authToken for the account that you wish to use to publish the package. You can do that by logging in to npm (`npm login`). This will save the authToken to the `~/.npmrc` file. Look for the following line:
+
```shell
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```
+
In this case, the authToken is `00000000-0000-0000-0000-000000000000`.
2.  Go to your <<environment-variables#setting-environment-variables-for-all-commands-without-adding-them-to-git,project settings>>, and set the `NPM_TOKEN` variable to the obtained authToken.
3.  Configure CircleCI to add the authToken to `~/.npmrc`, run `npm publish` and only for versioned tags:
+
```yaml
version: 2

jobs:
    publish:
    docker:
        - image: <docker-image-name-tag>
            auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
        - checkout
        - run:
            name: Publish to NPM
            command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
    version: 2
    tagged-build:
    jobs:
        - publish:
            filters:
            tags:
                only: /v[0-9]+(\.[0-9]+)*/
```
+
4.  When you want to publish a new version to npm, run `npm version` to create a new version:
+
```shell
npm version 10.0.1
```
+
This will update the `package.json` file and creates a tagged Git commit. Next, push the commit with tags:
+
```shell
git push --follow-tags
```
+
5.  If tests passed, CircleCI will publish the package to npm automatically.