---
version:
- Server v2.x
- Server Admin
---
= Setting Up Docker Hub Pull Through Mirror
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This section describes how to configure a Docker Hub pull through registry mirror.

toc::[]

== Overview

Starting https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/[November 1, 2020], Docker Hub will impose rate limits for anonymous pulls based on the originating IP. To avoid service disruption, it is recommended to authenticate Docker pulls with Docker Hub. You can authenticate using build config (see https://circleci.com/docs/2.0/private-images/[Using Docker Authenticated Pulls]).

Alternatively, you can set up a Docker Hub pull through registry mirror pre-configured with Docker Hub account credentials. Using a pull through registry mirror is potentially simpler than making many build config modifications. It may also bring additional performance improvements since network roundtrips to Docker Hub are reduced.

These setup instructions are divided into three parts: Setting up a pull through cache registry, configuring Nomad clients to use the registry as a mirror, and configuring VM Service to use the registry as a mirror in machine executors and remote Docker jobs.

== Set up a pull through cache registry

In this phase we setup a pull through cache registry, which works as a mirror and reverse proxy for Docker Hub. This section introduces two types of pull through cache registry: The elementary and easier-to-setup one using HTTP, and the securer one using HTTPS. Either of them is functional for most cases, whereas you will need a securer one in certain cases.

=== Setup an elementary pull through cache registry (HTTP proxy for Docker Hub)

. *Set up a Docker Hub account* which will be used by the pull through cache registry to access Docker Hub.
+
TIP: Setting up a paid account can be a good option to ease the rate limiting further. See also: https://www.docker.com/pricing

. *Set up an independent Linux server* that has Docker installed.
+
We set up this registry as an independent server (i.e. outside of CircleCI boxes) to avoid load on this cache registry affecting other CircleCI Server services.
+
Assuming that the IP address for this server is `192.0.2.1`, the URL for the registry to setup is `http://192.0.2.1`. The URL will be needed later to arm Nomad clients and the VM Service.

. Run the command below to *start the registry*.
+
NOTE: Replace `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN` with the username for the Docker Hub account and the access token you obtained through https://hub.docker.com/settings/security, respectively.
+
[source,bash]
----
sudo docker run \
  -d \
  -p 80:5000 \
  --restart=always \
  --name=through-cache \
  -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" \
  -e REGISTRY_PROXY_USERNAME=DOCKER_HUB_USERNAME \
  -e REGISTRY_PROXY_PASSWORD=DOCKER_HUB_ACCESS_TOKEN \
  registry
----

. Finally, make sure that the TCP port 80 (i.e. HTTP) is open and accessible. For better security, we recommend you to open the port only to Nomad clients, and VMs for `machine` executors and remote docker engines.
+
On AWS, for example, you will need to make sure that both Security Groups and the firewall at the OS level are configured correctly to accept connections from Nomad clients over HTTP.

=== Set up a secure pull through cache registry (HTTPS proxy for Docker Hub)

Under certain circumstances (especially when you are enabling https://docs.docker.com/develop/develop-images/build_enhancements/[BuildKit] on machine executors and remote docker engines), your pull through cache registry needs to accept connections over HTTPS. This is the instruction to setup a pull through cache that listens for HTTPS connections.

. *Set up a Docker Hub account* which will be used by the pull through cache registry to access Docker Hub.
+
TIP: Setting up a paid account can be a good option to ease the rate limiting further. See also: https://www.docker.com/pricing

. *Set up an independent Linux server* that has Docker installed.
+
We set up this registry as an independent server (i.e. outside of CircleCI boxes) to avoid load on this cache registry affecting other CircleCI Server services.
+
Note that **the sever needs to be accessible by its hostname**. Namely, you have to configure DNS accordingly so that the hostname (assume `your-mirror.example.com`) resolves to the IP address of the server correctly. Hereby we assume that the URL for the registry to setup is `https://your-mirror.example.com` (be aware that the URL scheme is `http**_s_**`, not `http`). The URL will be needed later to arm Nomad clients and the VM Service.

. *Obtain a TLS certificate for `your-mirror.example.com`* and *put the certificate and the private key into `/root/tls`* of the server.
+
Note that this document assumes that you are obtaining a certificate issued by a well-known CA, not a self-signed one. Use of self-signed certificates is NOT tested.

. Run the command below to *start the registry*.
+
[source,bash]
----
sudo docker run \
  -d \
  -p 443:5000 \
  --restart=always \
  --name=through-cache-secure \
  -v /root/tls:/data/tls \
  -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" \
  -e REGISTRY_PROXY_USERNAME=DOCKER_HUB_USERNAME \
  -e REGISTRY_PROXY_PASSWORD=DOCKER_HUB_ACCESS_TOKEN \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/data/tls/fullchain.pem \
  -e REGISTRY_HTTP_TLS_KEY=/data/tls/privkey.pem \
  registry
----
+
NOTE:
+
.. Replace `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN` with the username for the Docker Hub account and the access token you obtained through https://hub.docker.com/settings/security, respectively.
.. Replace `fullchain.pem` and `privkey.pem` with the filenames of your certificate and private key, respectively. *The certificate specified there must be correctly chained enough for tracing the certification path from the leaf to the root*.

. Finally, *make sure that the TCP port 443 (i.e. HTTPS) is open and accessible*. For better security, we recommend you to open the port only to Nomad clients and VMs for `machine` executors and remote docker engines.
+
On AWS, for example, you will need to make sure that both Security Groups and the firewall at the OS level are configured correctly to accept connections from Nomad clients and VMs for `machine`/`setup_remote_docker` jobs over HTTPS.

==== Plan for renewal of TLS certificates

You will need to renew TLS certificates periodically. These are the steps required to renew certificates.

. Update the certificate and the private key in `/root/tls`.

. Run `docker restart through-cache-secure`.

Technically, this can be automated. For example, if you are using Let's Encrypt for your certificates, you can setup a cron task that executes `certbot renew` and the steps above.

== Configure Nomad clients to use the pull through cache registry (run this for _each_ Nomad client)

. Run the command below to *configure the `registry-mirrors` option for the Docker daemon*.
+
NOTE: Replace `http://192.0.2.1.or.https.your-mirror.example.com` with the URL of your pull through cache registry accordingly.
+
[source,bash]
----
sudo bash -c 'cat <<< $(jq ".\"registry-mirrors\" = [\"http://192.0.2.1.or.https.your-mirror.example.com\"]" /etc/docker/daemon.json) > /etc/docker/daemon.json'
----

. *Reload Docker daemon* to apply the configuration.
+
`sudo systemctl restart docker.service`

Now you should be able to see that Docker images from Docker Hub are downloaded through the cache registry. As a side effect, you should be able to see that private images for the user, which is configured for the cache registry, can be downloaded without explicit authentications.

== Configure VM Service to let Machine/Remote Docker VMs use the Pull Through Cache Registry

Follow the steps below on your services machine.

. Run the command below to *create a directory for your customization files*.
+
`sudo mkdir -p /etc/circleconfig/vm-service`

. *Populate a customization script* to be loaded by vm-service. *Add the script below to `/etc/circleconfig/vm-service/customizations`*.
+
NOTE: Replace `http://192.0.2.1.or.https.your-mirror.example.com` in `DOCKER_MIRROR_HOSTNAME` variable with the URL of your pull through cache registry accordingly.
+
[source,bash]
----
export JAVA_OPTS='-cp /resources:/service/app.jar'
export DOCKER_MIRROR_HOSTNAME="http://192.0.2.1.or.https.your-mirror.example.com"

mkdir -p /resources/ec2
cat > /resources/ec2/linux_cloud_init.yaml << EOD
#cloud-config
system_info:
  default_user:
    name: "%1\$s"
ssh_authorized_keys:
  - "%2\$s"
runcmd:
  - bash -c 'if [ ! -f /etc/docker/daemon.json ]; then mkdir -p /etc/docker; echo "{}" > /etc/docker/daemon.json; fi'
  - bash -c 'cat <<< \$(jq ".\"registry-mirrors\" = [\"$DOCKER_MIRROR_HOSTNAME\"]" /etc/docker/daemon.json) > /etc/docker/daemon.json'
  - systemctl restart docker.service
EOD
----

. *Restart VM Service* to apply the customization.
+
`sudo docker restart vm-service`

== How to revert the setup?

=== Disarm Nomad clients

Follow the steps below on _each_ Nomad client.

. *Remove `registry-mirrors` option in `/etc/docker/daemon.json`* by running the command below.
+
[source,bash]
----
sudo bash -c 'cat <<< $(jq "del(.\"registry-mirrors\")" /etc/docker/daemon.json) > /etc/docker/daemon.json'
----

. Run `sudo systemctl restart docker.service` to apply the change.

=== Disarm VM Service

Follow the steps below on your services machine.

. *Void the `JAVA_OPTS` environment variable* by running the command below.
+
`echo 'unset JAVA_OPTS' | sudo tee -a /etc/circleconfig/vm-service/customizations`

. Run `sudo docker restart vm-service` to apply the change.

== Resources

* https://docs.docker.com/registry/recipes/mirror/ (How to configure a pull through cache mirror)
* https://hub.docker.com/_/registry (Official Docker Registry Docker image)
* https://docs.docker.com/registry/configuration/ (How to configure official Docker Registry)
