---
version:
- Cloud
- Server v3.x
---
= Examples and Guides Overview
:page-layout: classic-docs
:page-liquid:
:page-description: Resources for . 
:icons: font
:toc: macro
:toc-title:

This page provides a collection of examples to help you learn how to build, test, and deploy applications written in the most common programming languages, frameworks, and platforms on CircleCI.

[#languages]
== Language guides

We’ve created several demo applications in various languages, so you can learn by example from an app written in the same language as your application. Each language listed below has an associated guide and public repository on GitHub.

{% include snippets/language-guides.md %}

[#platforms]
== Platform guides

Use the tutorial associated with your platform to learn about the customization that is possible in a <<configuration-reference#,`.circleci/config.yml`>>.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Platform guide
| Description

| <<project-walkthrough#,Linux Project Tutorial>>
| Complete walkthrough of setting up a Python project with Flask to build with CircleCI.

| <<hello-world-macos#example-application,macOS Project Tutorial>>
| Set up a macOS project in CircleCI.

| <<ios-tutorial#,iOS Project Tutorial>>
| Set up an iOS project in CircleCI.

| <<hello-world-windows#example-application,Windows Project Tutorial>>
| Full example of setting up a .NET project in CircleCI.
|===