---
contentTags:
  platform:
  - Cloud
---
= Sign up and try CircleCI
:page-layout: classic-docs
:page-liquid:
:page-description: First step for using CircleCI.
:icons: font
:experimental:

//TODO: Check backlinks

To start building on CircleCI, go to the link:https://circleci.com/signup/[Sign Up] page. Sign up with your email address and connect your GitHub, Bitbucket, or GitLab account in the process.

- If you are **creating a new CircleCI org** for your team, follow the xref:#sign-up-and-create-an-org[Sign up and create an org] steps below. 
- If you are signing up for a CircleCI account through an **invite** from someone on your team, follow the steps in the xref:#sign-up-with-an-invite[Sign up with an invite] section.

[#vcs-integrations]
== VCS integrations

CircleCI supports GitHub, Bitbucket, and GitLab projects. If you use **GitHub** or **GitLab**, and are creating a CircleCI organization for your team, you will be setting the VCS integration type and authenticating with your VCS provider during the signup process. Team members that you invite afterwards to your CircleCI org will have to also later authenticate with the VCS provider if they are to create new projects.

If you use **Bitbucket**, every team member signing up for a new account and joining your org will authenticate with Bitbucket during the signup process.

[#sign-up-and-create-an-org]
== Sign up and create an org

If you are new to CircleCI, you will create a CircleCI organization. A CircleCI organization may correspond directly to a _personal_ CircleCI account, or more commonly, to a _shared_ account in which a team collaborates and with which multiple team members' personal CircleCI accounts can be associated. 

. To create an account for free with CircleCI, enter your email address and password on the link:https://circleci.com/signup/[Sign Up] page.

. On the next screen, respond to prompts that best describe your role and your engineering organization.

. Then, connect your code. Choose the version control system (VCS) that contains your code repositories: GitHub, GitLab.com (cloud), GitLab Self-Managed, or Bitbucket.

[#GitHub]
=== GitHub

. For GitHub, you will be taken to a screen to install the CircleCI GitHub App. In this step, you can specify exactly which repositories CircleCI can access, or opt to give CircleCI access to all repositories in your GitHub organization.

. Next, in the Create New Project page, you will set up your first project and trigger your first pipeline in CircleCI. You need an SSH key. Add the private key on this page, and add the corresponding public key as a deploy key in GitHub. Follow the instructions on the page, or refer to the xref:create-project#[Creating a Project] guide for more details.
+
If you do not want to connect to your code at this time and only wish to continue with the email signup, click btn:[Cancel]. 

. You will be taken to the dashboard in the CircleCI web app. From here, you can start to trigger pipelines, create more projects, and invite team members to your org.

** If you choose not to connect your code at this time, you can still explore some example projects within the CircleCI app. You can take a look at a popular open source project building on CircleCI (link:https://app.circleci.com/pipelines/github/facebook/react[React by Facebook]), or one of our own sample projects: a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-javascript-cfd/[sample JavaScript app], and a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-python-cfd/[sample Python app].
+
When you are ready, you can connect to your GitHub account from the CircleCI web app by xref:create-project#[creating a new project].

NOTE: The full set of documentation for integrating GitHub with CircleCI can be found on the xref:github-apps-integration#[GitHub Apps integration page].

[#gitlab]
=== GitLab

. For GitLab, connect your code from either a GitLab.com or GitLab Self-managed account. Follow the prompts to connect to your GitLab account and create a new project. You can also refer to the xref:create-project#[Creating a Project] guide for more details on this step.
+
If you do not want to connect to your code at this time and only wish to continue with the email signup, click btn:[Cancel]. 

. Once you have selected a repository and created a new CircleCI project, you will be redirected to the dashboard in the CircleCI web app. From here, you can start to trigger and run project pipelines, create more projects, and invite team members to your org.

** If you choose not to connect your code at this time, you can still explore some example projects within the CircleCI app. You can take a look at a popular open source project building on CircleCI (link:https://app.circleci.com/pipelines/github/facebook/react[React by Facebook]), or one of our own sample projects: a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-javascript-cfd/[sample JavaScript app], and a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-python-cfd/[sample Python app].
+
When you are ready, you can connect to your GitLab account from the CircleCI web app by xref:create-project#[creating a new project].

NOTE: The full set of documentation for integrating GitLab with CircleCI can be found on the xref:gitlab-integration#[GitLab integration page].

[#bitbucket]
=== Bitbucket

. For Bitbucket, you will authenticate with your Bitbucket account and connect your code.

. Once you have authenticated, you will be redirected to your organization dashboard in the CircleCI web app. From here, you can start to trigger and run project pipelines, set up more projects, and invite team members to your org.
+
For more details on setting up a project in CircleCI, read the xref:create-project#[Creating a Project] guide.

** If you choose not to connect your code at this time, you can still explore some example projects within the CircleCI app. You can take a look at a popular open source project building on CircleCI (link:https://app.circleci.com/pipelines/github/facebook/react[React by Facebook]), or one of our own sample projects: a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-javascript-cfd/[sample JavaScript app], and a link:https://app.circleci.com/pipelines/github/CircleCI-Public/sample-python-cfd/[sample Python app].
+
When you are ready, you can connect Bitbucket account from the CircleCI web app. Click your user icon in the lower left corner to open your *User Settings*. Under *Account Integrations*, click btn:[Connect] to authenticate with Bitbucket and start setting up your projects. 

NOTE: The full set of documentation for integrating Bitbucket with CircleCI can be found on the xref:bitbucket-integration#[Bitbucket integration page].

[#sign-up-with-an-invite]
== Sign up with an invite

If you are signing up using an invite from a team member, you will be _joining_ a CircleCI organization. The CircleCI organization is a _shared_ account where a team collaborates, and with which multiple team members' personal CircleCI accounts can be associated. 

[CAUTION] 
====
You must follow the link from an invite email in order to join an existing CircleCI organization. If you attempt to sign up directly from the link:https://circleci.com/signup/[Sign Up] page, you will be creating a new organization. 

If you have not received an invite, please contact your org administrator.
====

. To create an account for free with CircleCI, follow the link in your invite email and enter your email address and password. 

. On the next screen, respond to prompts that best describe your role and your engineering organization.

. Finally, you will be taken to your organization's pipelines dashboard in the CircleCI web app. From here, you can follow projects or trigger pipelines in projects to which you have access in your organization, or set up new projects.

Note that if you are setting up a project for the first time, you may need to authenticate with your VCS provider. Once you have completed a one-time authentication, you will be able to set up subsequent projects in CircleCI more quickly. Refer to the xref:create-project#[Creating a Project] guide for more information. 

The full set of documentation for integrating GitHub, Bitbucket, or GitLab projects are available as follows:

- xref:github-apps-integration#[GitHub App integration]
- xref:bitbucket-integration#[Bitbucket integration]
- xref:gitlab-integration#[GitLab integration]

////

TODO: Check backlinks
[#vcs-signup]
== Sign up with GitHub or Bitbucket


[#gitlab-signup]
== Sign up with GitLab


[#email-signup]
== Sign up with email

////

[#terms]
== Terms

By signing up, you are agreeing to our link:https://circleci.com/terms-of-service/[SaaS Agreement] and link:https://circleci.com/privacy/[Privacy Policy]. We ask for read/write access to make your experience seamless on CircleCI. If you are a GitHub user and aren’t ready to share access to your private projects, you can choose public repos instead. Protected by reCAPTCHA, Google link:https://policies.google.com/privacy?hl=en[Privacy Policy] and link:https://policies.google.com/terms?hl=en[Terms of Service] apply.

[#next-steps]
== Next steps

- Go to the xref:hello-world#[Hello World] page to learn the basics of setting up a CircleCI configuration file. 
- Read the xref:concepts#[Concepts] page for an overview of foundational CircleCI concepts such as pipelines, executors 
- Refer to the full xref:configuration-reference#[CircleCI configuration reference] for creating a `.circleci/config.yml` file, which determines your execution environment and automates your tests.
