---
version:
- Cloud
---
= GitLab Support Preview Documentation
:page-layout: classic-docs
:page-liquid:
:page-description: Learn how to integrate GitLab with CircleCI. 
:icons: font
:toc: macro
:toc-title:

== Overview

IMPORTANT: Welcome to the GitLab VCS Support Preview
This is a work in progress that we are continually iterating and improving. Please be prepared for some performance issues, errors, and unexpected changes. **At this time, we do not recommend using GitLab version control system (VCS) support on CircleCI for production of critical work.**
We appreciate your participation in the preview process and your collaboration as we work to create a seamless and stable experience.  
https://ideas.circleci.com/gitlab-vcs-experience-feedback[Give feedback]

== Step One: Sign up

=== A) New CircleCI users: Create a CircleCI account and create your first organization

. https://circleci.com/signup/[Sign up for CircleCI] via email and password.

. After you set an email and password, you will be taken to a screen with the option to connect GitLab, GitHub, or Bitbucket. Click "Connect" for GitLab. 
+
NOTE: If you do not see the option to connect GitLab, please fill out this https://circleci.com/gitlab-vcs-support/[sign-up form].
+
NOTE: If you choose to also connect your GitHub or Bitbucket accounts with your new account, your accounts will be merged based on the VCS account name that you used.

. You will be prompted to create a new organization. Enter an organization name. After you successfully create a new organization, you will be taken to the web app dashboard. Follow the steps below to create a new project.

=== B) Current CircleCI users: Create a new organization

. Log in to the CircleCI web app. 

. From the organization switcher on the top left, select "Create New Organization". 

. The next page should include a "Welcome to the GitLab VCS Support Preview" message. Enter a unique name for your new organization.

NOTE: If you do not see the welcome message, please fill out this https://circleci.com/gitlab-vcs-support/[sign-up form].

. Click **Create Organization**.

Once you successfully create a new organization, you will be taken to the organization dashboard. Follow the steps below to set up a new GitLab project.

This new organization allows you to manage users and GitLab projects within the organization. The organization will be under its own <<plan-free#,**Free plan**> to start. You can upgrade to another plan later. This pricing plan is independent of any GitHub or Bitbucket organizations you have previously set up with your account. 

NOTE: Existing CircleCI users can also opt to sign up via email and password. If you choose to connect a VCS (GitHub or Bitbucket) account that you already have with your new email/password account, your accounts will be merged based on the VCS account name that you used.

== Step two: Create a new project

. In the CircleCI web app, navigate to **Projects**, then click the **Create Project** button. 

. Enter a name for your project. 

. Under **Code Source**, you have the option to connect to GitLab via OAuth, or using an access token.
+
IMPORTANT: You will need API access and write permissions on the repository you want to set up. Within GitLab, this is the “maintainer” role or higher. If you use an access token, you need to select the `api` and `write_permissions` scopes.
+
* To connect to GitLab via OAuth, click the **Connect** button. A browser window will open and direct you to GitLab's sign-in page. Once you have authenticated in GitLab, you will be redirected back to the project setup window in CircleCI.
+
You have successfully connected to GitLab if there is a green checkmark and a note that says CircleCI will listen to your code source for changes. You should also see a dropdown list of your GitLab repositories.
+
* To connect using an access token, enter the access token in the field, and click the **Connect** button. You can use either a personal access token, or a project access token. Note that project access tokens are only available for certain GitLab subscriptions or license tiers. For more information, refer to the Personal Access Tokens and Project Access Tokens documentation on GitLab.
+
You have successfully connected to GitLab if you see the "Access token successful" note. You should also see a dropdown list of your GitLab repositories. The repositories available to set up will depend on what is associated with the personal or project access token you use.
+
. Select the repository you wish to set up, then click **Create Project**.

Behind the scenes, CircleCI is registering a webhook within your GitLab repository. You may verify this once you have successfully created the project, by navigating to your repository's Webhooks settings page. 

== Step three: Trigger a project pipeline in CircleCI

At this time, setting up a new GitLab project does not automatically trigger a pipeline. Adding or editing a CircleCI configuration within the CircleCI web app is also not currently available. 

. If you have not already done so, create a `.circleci` directory at the root of your GitLab repository, and add a `config.yml` file in that directory. 
+
NOTE: If you are new to CircleCI, you may wish to get started with our <<hello-world#echo-hello-world-on-linux#,Hello World>> example, or take a look at some of our <<sample-config#,sample configurations>>. The <<configuration-reference#,Configuring CircleCI>> document is a full reference to the keys used in a `.circleci/config.yml` file.

. Push changes to your GitLab repository. You should see a pipeline running for the project within the CircleCI web app.

== About projects

Unlike GitHub or Bitbucket projects, the GitLab support preview introduces the concept of "standalone" projects that are not specific to a VCS.

A project can have one or more **configurations** which are _pipeline definitions_ including, but not limited to, a `.circleci/config.yml` file in your repo. 

A project can have one or more **triggers**, which are events from a source of change including, but not limited to, a VCS. A trigger determines _which configuration_ it should use to start a pipeline. 

At this time both configurations and triggers are limited to GitLab.  

=== Project settings 

CAUTION: This is an area of rapid development and the current experience does not reflect the desired functionality. At this time, we recommend following the onboarding steps outlined above for new projects, and not manually configuring configurations and triggers. 

The following settings are found by clicking the **Project Settings** button within your project:

==== Configuration

Add a configuration source for your project. If you followed the steps above to connect GitLab, a GitLab configuration source has been automatically added for you. Once you define a configuration source, you can set up a trigger that points to that configuration. 

=== Triggers

Add a trigger that specifies which configuration source starts a pipeline. If you followed the steps above to connect GitLab, a trigger set with GitLab as the configuration source has been automatically added for you.

Triggers and trigger rules determine how CircleCI handles events from the source of change, in this case, GitLab. 

When a trigger is created, CircleCI registers a webhook with GitLab. Push events from GitLab are sent to CircleCI. CircleCI then uses the event data to determine if a pipeline, and if so, which pipeline, should be run. 

In addition to a configuration source, each trigger includes the webhook URL, and in this scenario, a CircleCI-created GitLab token. The webhook URL and GitLab token are used to securely register the webhook within GitLab in order to receive push events from your GitLab repo. 

For more information on project settings, refer to the <<settings#,Settings>> document. Please also note the differences in functionality for the following project settings in the GitLab preview:

* **Advanced Settings**
+
Advanced Settings allows for enabling of _dynamic configuration_ using setup workflows in CircleCI. To learn more about dynamic configuration, read the <<dynamic-config#,Dynamic Configuration>> guide.

The **Free and Open Source** setting is not currently supported, but there are plans to make this available in the future.

* **SSH Keys**
+
When creating a project, an SSH key is created which is used to checkout code from your repo. Each configuration you create generates a new SSH key to access the code in the repo associated with that configuration. At this time, only **Additional SSH Keys** are applicable to GitLab projects. More information on SSH keys, please visit the <<add-ssh-key#,Adding an SSH Key to CircleCI>> document.

== About organizations

The GitLab preview also introduces the concept of "standalone" organizations, which are not tied to a VCS. 

A standalone organization allows for managing users and projects independent of the VCS. Organizations as well as users are considered CircleCI organizations and users, with their own roles and permissions that do not rely on those defined in a VCS. 

=== Organization Settings 

To manage settings on the organization level, click the **Organization Settings** button within the CircleCI web app. 

For general information on organization settings in CircleCI, refer to the <<settings#,Settings>> document. Please also note the differences in functionality for the following project settings in the GitLab preview:

==== People 

Add or remove users, and manage user roles for the organization as well as user invites. 

NOTE: You must have at least one Org Administrator. If you try to remove the last org administrator, you will get an error. 

====== Inviting your first team members

Upon creating a new organization, you also have the option to invite team members from the dashboard. Alternatively, you may invite team members from the **People** section within Organization Settings.

. Click the **Invite** button.

. Enter the email address of the user you wish to invite, and select the appropriate role. You may enter multiple addresses at once, if you wish to assign these users the same role. 
+
Organization administrator as well as organization contributor roles are currently available. Project-specific roles will be coming soon. For more information on roles and permissions, refer to the next section.

. An invited user will receive an email notification (sent from `noreply@circleci.com`), containing a link to accept the invite.
+
If they do not currently have a CircleCI account, they will need to sign up. If they already have a CircleCI account, they are added to the organization, and if they are logged in, they will see the organization as an option in the organization switcher in the top left corner of the web app. 

====== About roles and permissions

User access and roles within CircleCI are independent of roles within GitLab. 

Each user can have one organization role: either an _admin_ or _contributor_. 

Org contributors cannot edit organization settings such as contexts or plans. They can, however, invite users, change user roles, view contexts, and create and view projects. 

* Org Administrator: For those managing CircleCI as a whole—managing users, managing plans, updating billing information, and managing contexts. 

* Org Contributor: For users that might manage multiple projects and/or need to create and administer projects within CircleCI. 

* Org Viewer: For users such as those in support roles that do not contribute code but need to see reports, know the status of projects, or validate plan usage. 

* Project Administrator (coming soon): For ensuring teams only have access to individual projects and not all projects across the organization. Project administrators, typically the team manager or lead, will have access to project settings.

* Project Contributor (coming soon): For individual team members who are not required to manage project settings.

* Project Viewer (coming soon): For users that might need to know the status of an individual project, but are not committing changes.

==== Contexts

Contexts do not support “restricted access” at this time. We are working on restriction options and you can learn more about that in the future section below. More information about using contexts within CircleCI can be found here. 

==== Self-Hosted Runners

Self-hosted runners are not supported in the GitLab preview at this time. We will be adding support for self-hosted runners in the near future. 

== Known issues 

=== SSH Rerun is not working

We currently don’t have support for SSH rerun but we are working on resolving this issue in a future release. 

=== Additional SSH Keys only

Deploy Key and User Key are not being used at this time. All SSH keys generated for a project will be stored under Additional SSH keys. In coming updates this will become more clear. 

=== Project Configurations aren’t applicable

The current project configuration options under project settings don't work as expected. Your triggers source determines what configuration is going to be used to build and run a pipeline. We look for a .circleci/config.yml in the root of the repo we received the trigger from. In a coming update configuration location will be managed independently of the trigger. Please use the Create Project button from the projects tab to setup your projects. 

=== User Account Integrations don’t include GitLab 

The page User >  Account Integrations doesn’t include GitLab as a choice. At this time your VCS connection is configured through new project creation or project settings for triggers and configuration. 

=== No restricted contexts

There is no support for restricted contexts. Contexts can be created by all organizational users that have an admin or collaborator role. Any users that can trigger a build at the source will be able to use these secrets. 

=== Project > Advanced 

Settings for free and open source don’t work. 
Previous available settings for forked PRs and merge requests are not available. 

=== Project > Overview 

Stop Building doesn't work. The recommendation is to delete your webhooks in your Gitlab repo if you no longer want a CircleCI pipeline to run. 

=== Plans and Usage 

Plans pages don’t include the organization name just the UUID. 
Usage pages don’t include the project name under projects. 
Active users only count users that created a project in CircleCI and trigger a build. 

== What’s Coming Next 

=== Updated Project Settings for Triggers and Configurations

Customers will be able to independently manage their triggers and configuration. Allowing for a trigger from one repository to kick off a pipeline that’s defined by a configuration existing in another repository. 

Users will be able to set up a project manually through a project’s trigger and configuration settings. At this time all users must use the new project creation screen to successfully setup a GitLab project. 

=== Trigger Rules

Want a pipeline to run only on merge requests or other attributes of the event from the VCS? Trigger rules give you the ability to determine when an event should or shouldn’t trigger a pipeline build.

=== Project Roles and View Only Roles 

We allow organizations to limit user access to a project or projects and not require an organization level role. This gives greater control over who has access to projects across the organization and limits access to organization settings or creating new projects. 

=== Restricted Contexts 

Restricted contexts are not supported at this time. That means anyone within your organization can create triggers and any users that can trigger builds from the source can use those contexts. In the future it will be possible to limit contexts access (restricted contexts) by project and/or branch, giving your organization greater control and ensuring individual users only have access to the contexts they require.  

=== User > Account Integrations 

As mentioned in known issues, there is no method to manage your account integrations with GitLab. We are working on including GitLab in the options listed there. 





