---
version:
- Cloud
- Server v4.x
- Server v3.x
- Server v2.x
---
= Glossary
:page-layout: classic-docs
:page-liquid:
:page-description: A glossary of terms used for the CircleCI product.
:icons: font
:toc: macro
:toc-title:

[#authentication]
== Authentication

Authentication of CircleCI projects using the hosted application is handled by the VCS, or Google OAuth. Sessions last for 14 days. See the <<gh-bb-integration#permissions-overview,Permissions Overview>> section of the VCS Integration document for additional details.

User authentication may use LDAP for an instance of the CircleCI application that is installed on your private server or cloud. See the <<authentication#,Authentication>> document for setup instructions.

[#circleci-administrator]
== CircleCI Administrator

The first user to log into a private installation of CircleCI. Administrators have the ability to add and remove users.

[#container]
== Container

A container is a running instance of an image.

== Context

<<contexts#,Contexts>> provide a mechanism for securing and sharing environment variables across projects. The environment variables are defined as name/value pairs and are injected at runtime. After a context has been created, you can use the context key in the workflows section of a project `.circleci/config.yml` file to give any job(s) access to the environment variables associated with the context.

[#docker-layer-caching]
== Docker Layer Caching

The CircleCI Docker Layer Caching feature allows builds to reuse Docker image layers from previous builds. Image layers are stored in separate volumes in the cloud, and are not shared between projects. Layers may only be used by builds from the same project. For additional information about how the secure environment is created, see the <<docker-layer-caching#,Docker Layer Caching>> and <<building-docker-images#,Running Docker Commands>> documents. 

[#environment-variables]
== Environment Variables

<<env-vars#,Environment variables>> store customer data that is used by a project. Only project administrators and owners are allowed to view or modify environment variables. The values are transmitted using secure protocols, for example, HTTPS and SSH, encrypted at rest, and hashed/salted to prevent CircleCI employees from viewing them.

[#executor]
== Executor

<<executor-intro#,Executors>> define the underlying technology to run a job. Can be either `docker` to run your job inside a Docker container with a specified image, or `machine` to run your job inside a full virtual machine.

[#image]
== Image

An image is a packaged system that includes instructions for creating a running container. The primary container is defined by the first image listed in a `.circleci/config.yml` file. This is where commands are executed for jobs, using the Docker or machine executor. Visit the https://circleci.com/developer/images[CircleCI Developer Hub] to see available convenience and machine images.

[#job-space]
== Job Space

All the containers being run by an <<#executor,executor>> for the current job.

[#job]
== Job

<<jobs-steps#,Jobs>> are collections of steps, which run commands/scripts as required. Each job must declare an executor that is either docker, machine, windows, or macos.

[#orbs]
== Orbs

<<orb-concepts#,Orbs>> are reusable snippets of code that help automate repeated processes, accelerate project setup, and make it easy to integrate with third-party tools. Visit the https://circleci.com/developer/orbs[Orbs Registry] on the CircleCI Developer Hub to search for orbs to help simplify your config.

[#owner]
== Owner

The owner of the team's VCS organization.

[#pipeline]
== Pipeline

A <<pipelines#,CircleCI pipeline>> is the full set of processes you run when you trigger work on your projects. Pipelines encompass your workflows, which in turn coordinate your jobs. Pipelines are defined in your project '.circleci/config.yml.' file. _Pipelines are not available on CircleCI server v2.x._

[#primary-container]
== Primary Container

The first image listed in `.circleci/config.yml`. This is where commands are executed for jobs using the Docker executor.

[#project-administrator]
== Project Administrator

The user who adds a repository in the VCS to CircleCI as a project.

[#project]
== Project

A CircleCI project shares the name of the code repository for which it automates workflows, tests, and deployment. It is visible on the **Projects** page of the https://app.circleci.com/[CircleCI web app] and must be added with the **Set Up Project** button. After a project is added, it is possible to configure settings, contexts, environment variables, and team members who may follow the project. Following a project enables you to subscribe to email notifications for the project's build status, and adds the project to your CircleCI dashboard.

[#remote-docker]
== Remote Docker

A feature that enables building, running, and pushing images to Docker registries from within a Docker <<#executor,executor>> job. Visit the <<building-docker-images#,Runner Docker Commands>> page to learn more.

[#step]
== Step

A step is a collection of executable commands. Visit the <<sample-config#,Sample Configuration>> page to learn more.

[#user]
== User

An individual user within an organization. A CircleCI user is anyone who can log in to the CircleCI platform with a username and password. Users must be added to a VCS organization to view or follow associated CircleCI projects. Users may **not** view project data that is stored in environment variables.

[#workflow]
== Workflow

<<workflows#,Workflows>> define a list of jobs and their run order. It is possible to run jobs concurrently, sequentially, on a schedule, or with a manual gate using an approval job.

[#workspace]
== Workspace

A <<workspaces#,workspace>> is a workflows-aware storage mechanism. A workspace stores data unique to the job, which may be needed in downstream jobs.