[#orb-development-kit]
== Orb development kit

The <<orb-author#orb-development-kit,orb development kit>> refers to a suite of tools that work together to simplify the orb development process, with automatic testing and deployment on CircleCI. Two CLI commands are included in the orb development kit: link:https://circleci-public.github.io/circleci-cli/circleci_orb_init.html[`circleci orb init`] and link:https://circleci-public.github.io/circleci-cli/circleci_orb_pack.html[`circleci orb pack`]. For more information on the orb packing, see the <<orb-concepts#orb-packing,Orbs Concepts>> guide.

[#validate-an-orb-in-your-config]
=== Validate an orb in your config
If you are working with link:https://circleci.com/orbs[Orbs] you can also validate your orb:

```shell
circleci orb validate /tmp/my_orb.yml
```

Where the above command will look for an orb called `my_orb.yml` in the `/tmp` folder of the directory in which you ran the command.

[#packing-a-config]
== Packing a config

The CLI provides a `circleci config pack` command (separate to `circleci orb pack` described above), allowing you to create a single YAML file from several separate files. The `pack` command implements link:https://github.com/CircleCI-Public/fyaml[FYAML], a scheme for breaking YAML documents across files in a directory tree. This is particularly useful for breaking up source code for large orbs and allows custom organization of your orbs' YAML configuration. `circleci config pack` converts a filesystem tree into a single YAML file based on directory structure and file contents. How you **name** and **organize** your files when using the `pack` command will determine the final outputted `orb.yml`. Consider the following example folder structure:

```shell
$ tree
.
└── your-orb-source
    ├── @orb.yml
    ├── commands
    │   └── foo.yml
    └── jobs
        └── bar.yml

3 directories, 3 files
```

The unix `tree` command is great for printing out folder structures. In the example tree structure above, the `pack` command will  map the folder names and file names to **YAML keys**  and the file contents as the **values** to those keys. Let's `pack` up the example folder from above:

```shell
$ circleci config pack your-orb-source
```

```yaml
# Contents of @orb.yml appear here
commands:
  foo:
    # contents of foo.yml appear here
jobs:
  bar:
    # contents of bar.yml appear here
```

[#other-config-packing-capabilities]
=== Other config packing capabilities

A file beginning with `@` will have its contents merged into its parent folder level. This can be useful at the top level of an orb, when one might want generic `orb.yml` to contain metadata, but not to map into an `orb` key-value pair.

Thus:

```shell
$ cat foo/bar/@baz.yml
{baz: qux}
```

Is mapped to:

```yaml
bar:
  baz: qux
```

[#an-example-packed-configyml]
=== An example packed config.yml

See the link:https://github.com/search?q=topic%3Acircleci-orbs+org%3ACircleCI-Public&type=Repositories[CircleCI Orbs GitHub topic tag] to see examples of orbs written using multiple YAML source files. `circleci config pack` is typically run as part of these projects' CI/CD workflows, to prepare orb source code for publishing.

[#processing-a-config]
== Processing a config

Running `circleci config process` validates your config, but will also display expanded source configuration alongside your original config (useful if you are using orbs).

Consider the following example configuration that uses the link:https://circleci.com/developer/orbs/orb/circleci/node[`node`] orb:

```yml
version: 2.1

orbs:
  node: circleci/node@4.7.0

workflows:
  version: 2
  example-workflow:
      jobs:
        - node/test
```

Running `circleci config process .circleci/config.yml` will output the following (which is a mix of the expanded source and the original config commented out).

```yml
# Orb 'circleci/node@4.7.0' resolved to 'circleci/node@4.7.0'
version: 2
jobs:
  node/test:
    docker:
    - image: cimg/node:13.11.0
    steps:
    - checkout
    - run:
        command: |
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json
        working_directory: ~/project
    - run:
        command: |
          if [ -f "package-lock.json" ]; then
            echo "Found package-lock.json file, assuming lockfile"
            ln package-lock.json /tmp/node-project-lockfile
          elif [ -f "npm-shrinkwrap.json" ]; then
            echo "Found npm-shrinkwrap.json file, assuming lockfile"
            ln npm-shrinkwrap.json /tmp/node-project-lockfile
          elif [ -f "yarn.lock" ]; then
            echo "Found yarn.lock file, assuming lockfile"
            ln yarn.lock /tmp/node-project-lockfile
          fi
          ln package.json /tmp/node-project-package.json
        name: Determine lockfile
        working_directory: ~/project
    - restore_cache:
        keys:
        - node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-{{ checksum "/tmp/node-project-lockfile" }}
        - node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-
        - node-deps-{{ arch }}-v1-{{ .Branch }}-
    - run:
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
        name: Installing NPM packages
        working_directory: ~/project
    - save_cache:
        key: node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-{{ checksum "/tmp/node-project-lockfile" }}
        paths:
        - ~/.npm
    - run:
        command: npm run test
        name: Run NPM Tests
        working_directory: ~/project
workflows:
  version: 2
  example-workflow:
    jobs:
    - node/test

# Original config.yml file:
# version: 2.1
#
# orbs:
#   node: circleci/node@4.7.0
#
# workflows:
#   version: 2
#   example-workflow:
#       jobs:
#         - node/test
```

[#run-a-job-in-a-container-on-your-machine]
== Run a job in a container on your machine

The CLI enables you to run jobs in your config via Docker. This can be useful to run tests before pushing config changes or debugging your build process without impacting your build queue.

[#prerequisites]
=== Prerequisites

You will need to have link:https://www.docker.com/products/docker-desktop[Docker] installed on your system and have installed the most recent version of the CLI tool. You will also need to have a project with a valid `.circleci/config.yml` file in it.

[#running-a-job]
=== Running a job

The CLI allows you to run a single job from CircleCI on your desktop using Docker.

```shell
$ circleci local execute --job JOB_NAME
```

If your CircleCI config is set to version 2.1 or greater, you must first export your config to `process.yml`, and specify it when executing:

```shell
circleci config process .circleci/config.yml > process.yml
circleci local execute -c process.yml --job JOB_NAME
```

Let's run an example build on our local machine on one of CircleCI's demo applications:

```shell
git clone https://github.com/CircleCI-Public/circleci-demo-go.git
cd circleci-demo-go
circleci local execute --job build
```

The commands above will run the entire _build_ job (only jobs, not workflows, can be run locally). The CLI will use Docker to pull down the requirements for the build and will then execute your CI steps locally. In this case, Golang and Postgres docker images are pulled down, allowing the build to install dependencies, run the unit tests, test the service is running and so on.

[#limitations-of-running-jobs-locally]
=== Limitations of running jobs locally

Although running jobs locally with `circleci` is very helpful, there are some limitations.

**Machine Executor**

You cannot use the machine executor in local jobs. This is because the machine executor requires an extra VM to run its jobs.

**Add SSH Keys**

It is currently not possible to add SSH keys using the `add_ssh_keys` CLI command.

**Workflows**

The CLI tool does not provide support for running workflows. By nature, workflows leverage running jobs concurrently on multiple machines allowing you to achieve faster, more complex builds. Because the CLI is only running on your machine, it can only run single **jobs** (which make up parts of a workflow).

**Caching and Online-only Commands**

Caching is not currently supported in local jobs. When you have either a `save_cache` or `restore_cache` step in your config, `circleci` will skip them and display a warning.

Further, not all commands may work on your local machine as they do online. For example, the Golang build reference above runs a `store_artifacts` step, however, local builds won't upload artifacts. If a step is not available on a local build you will see an error in the console.

**Environment Variables**

For security reasons, encrypted environment variables configured in the UI will not be imported into local builds. As an alternative, you can specify env vars to the CLI with the `-e` flag. See the output of `circleci help build` for more information. If you have multiple environment variables, you must use the flag for each variable, for example, `circleci build -e VAR1=FOO -e VAR2=BAR`.

[#test-splitting]
== Test splitting

The CircleCI CLI is also used for some advanced features during job runs, for example <<parallelism-faster-jobs#using-the-circleci-cli-to-split-tests,test splitting>> for build time optimization.

[#context-management]
== Context management

<<contexts#,Contexts>> provide a mechanism for securing and sharing environment variables across projects. While contexts have been traditionally managed on the CircleCI web application, the CircleCI CLI provides an alternative method for managing the usage of contexts in your projects. With the CLI, you can execute several context-oriented commands:

- *create* - Create a new context
- *delete* - Delete the named context
- *list* - List all contexts
- *remove-secret* - Remove an environment variable from the named context
- *show* - Show a context
- *store-secret* - Store a new environment variable in the named context. The
  value is read from stdin.

The above list are "sub-commands" in the CLI, which would be executed like so:

```shell
circleci context create

# Returns the following:
List all contexts

Usage:
  circleci context list <vcs-type> <org-name> [flags]
```

Many commands will require that you include additional information as indicated by the parameters delimited by `< >`.

As with most of the CLI's commands, you will need to have properly authenticated your version of the CLI with a token to enable performing context related actions.