---
contentTags:
  platform:
  - Cloud
---
= Install machine runner 3.0 on Linux
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to install CircleCI's self-hosted machine runner (3.0) on Linux.
:icons: font
:experimental:
:machine:
:linux:

This page describes how to install CircleCI's machine runner 3.0 on Linux.

[#prerequisites]
== Prerequisites

{% include snippets/runner/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

{% include snippets/runner/install-with-cli-steps.adoc %}

[#install-circleci-runner]
== 2. Install CircleCI runner
[.tab.machine-runner-package-installation.debian]
--
{% include snippets/runner/machine-runner-deb-package-install.adoc %}
--
[.tab.machine-runner-package-installation.rpm]
--
{% include snippets/runner/machine-runner-rpm-package-install.adoc %}
--

{% include snippets/machine-runner-example.adoc %}

The job will then execute using your self-hosted runner when you push the `.circleci/config.yml` to your VCS provider.

[#troubleshooting]
== Troubleshooting

Refer to the <<troubleshoot-self-hosted-runner#troubleshoot-machine-runner,Troubleshoot Machine Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running machine runner on Linux.
