---
contentTags:
  platform:
  - Cloud
---
= Install machine runner 3.0 on macOS - Open preview
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to install CircleCI's self-hosted machine runner (3.0) on macOS.
:icons: font
:experimental:
:machine:
:macOS:

NOTE: Machine runner 3.0 is currently in open preview

This page describes how to install CircleCI's machine runner 3.0 on macOS.

[#prerequisites]
== Prerequisites

{% include snippets/runner/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

{% include snippets/runner/install-with-cli-steps.adoc %}

[#install-circleci-runner]
== 2. Install CircleCI runner on macOS


The easiest way to install runner on macOS is to use link:http://brew.sh/[Homebrew].

On the target macOS machine with homebrew installed, run the following command to add the CircleCI repository:

```shell
brew tap circleci-public/circleci
```

Next, install the circleci-runner package by running the following command:


Note: You may see an expected notification indicating a background item for Circle Internet Services Inc. has been added.

```shell
brew install circleci-runner
```

Next, open the runner config.yaml file with the text editor of your choice, and modify the `[[RUNNER_NAME]]` and `[[RESOURCE_CLASS_TOKEN]]` template values.

```shell
nano $HOME/Library/Preferences/com.circleci.runner/config.yaml
```

```
runner:
  name: "my-osx-runner"
  working_directory: "/Users/yourusername/Library/com.circleci.runner/workdir"
  cleanup_working_directory: true
api:
  auth_token: "your-auth-token"
```

. Replace `[[RESOURCE_CLASS_TOKEN]]` with the token generated in the steps above, and choose a name for your runner.

=== Migrating Existing Configuration Files
If you are migrating an existing configuration from a previous runner installation, you may move the existing launch agent file from its current path to the new path.

*Please Note*: this will overwrite the default config file installed via brew and replace it with your existing config file.

```shell
mv /Library/Preferences/com.circleci.runner/launch-agent-config.yaml $HOME/Library/Preferences/com.circleci.runner/config.yaml

```

After copying the file, you may remove the logging block to send logs to the default location for machine runner 3.0 (specified below):

```yaml
# remove this block from your existing config
logging:
  file: /Library/Logs/com.circleci.runner.log
```


[#reviewing-accepting-apple-signature-notarization]
== 3. Reviewing & Accepting the Apple Signature Notarization

Because the self-hosted runner is not compiled from source during installation, the binary must be approved to run on your macOS system. This can be done via the UI by accepting the macOS pop-up asking if you wish to run the binary from the internet, or programmatically.

You can first verify the signature and notarization with this command:

```shell
spctl -a -vvv -t install "$(brew --prefix)/bin/circleci-runner"
```

It should return an output that looks like this:
```
/opt/homebrew/bin/circleci-runner: accepted
source=Notarized Developer ID
origin=Developer ID Application: Circle Internet Services Inc.
```

When ready, run the command to accept the notarization. You will need to enter the macOS system password.

```shell
sudo xattr -r -d com.apple.quarantine "$(brew --prefix)/bin/circleci-runner"
```

[#starting-macos-machine-runner]
== 4. Starting macOS machine runner 3.0
To start the macOS machine runner 3.0 for the first time, run the following commands to bootstrap and load the plist file:

```shell
launchctl bootstrap gui/`stat -f %u` $HOME/Library/LaunchAgents/com.circleci.runner.plist
launchctl load $HOME/Library/LaunchAgents/com.circleci.runner.plist
```

[#stopping-macos-machine-runner]
== 5. Stopping macOS machine runner 3.0
To stop the machine runner service, run the following command to unload the plist file:
```shell
launchctl unload $HOME/Library/LaunchAgents/com.circleci.runner.plist
```


{% include snippets/machine-runner-example.adoc %}

The job will then execute using your self-hosted runner when you push the `.circleci/config.yml` to your VCS provider.



[#uninstall-machine-runner-macos]
== Uninstall machine runner 3.0 on macOS
To uninstall machine runner from your macOS device, follow these steps.



[#pre-uninstall-stop-macos-machine-runner]
=== 1. Stop the service
First, stop the machine runner service by using the following command to unload the plist file.
```shell
launchctl unload $HOME/Library/LaunchAgents/com.circleci.runner.plist
```

[#install-circleci-runner]
=== 2. Uninstall CircleCI runner
[.tab.machine-runner-uninstall-macos.keep-logs-and-configuration]
--
To uninstall without purging logs and configuration files, run the following command.

```shell
brew uninstall --cask circleci-public/homebrew-circleci/circleci-runner
```
--
[.tab.machine-runner-uninstall-macos.purge-logs-and-configuration]
--

This command will *purge all logs and configuration files*.

To uninstall and purge all logs and configuration files, run the following command.

```shell
brew uninstall --cask --zap circleci-public/homebrew-circleci/circleci-runner
```
--


== Accessing Runner Logs
On your macOS machine, logs from circleci-runner are located in the following directory by default.

```shell
$HOME/Library/Logs/com.circleci.runner/runner.log
```
