= Installation Overview
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

[.serveronly]_This document is intended for system administrators of self-hosted installations of CircleCI Server._

The following sections provide planning information, system requirements and step-by-step instructions for installing CircleCI Server on Amazon Web Services (AWS) with Terraform.

Refer to the https://https://circleci.com/docs/2.0/v.2.18-overview[What's New] page for full details of what's new and fixed in this release.

If you are looking to update an existing installation, see our guide to <<updating-server#upgrading-a-server-installation,Upgrading a Server Installation>>.

toc::[]

== Support Packages

CircleCI 2.0 may be installed without a support package, on AWS, using the examples and instructions in this document. Alternatively, if you do decide to go ahead with a support package, there are a number of benefits, as detailed below:

=== Non-AWS Platform Support

With a Platinum CircleCI support package it is possible to install and configure CircleCI on Azure or any other platform used in your organization. Contact https://support.circleci.com/hc/en-us/requests/new[CircleCI support] or your account representative to get started.

=== Externalization

With a Platinum support agreement, it is possible to improve performance and resilience by configuring the following services to run externally to the Services machine:

- PostgreSQL
- MongoDB
- Vault
- Rabbitmq
- Redis
- Nomad

Contact https://support.circleci.com/hc/en-us/requests/new[CircleCI support] or your account representative to evaluate your installation against the current requirements for running external services.
