---
contentTags:
  platform:
  - Cloud
  - Server v4+
---
= Configure a Go application on CircleCI
:description: Set up CI/CD for a Go project on CircleCI using orbs
:experimental:
:icons: font
:page-layout: classic-docs


This quickstart guide covers integrating a Go project with CircleCI. This guide is designed to help you create a basic CircleCI configuration file to build, test, and deploy your Go project. After completing this quickstart you can edit and optimize the config to fit the requirements of your project.

[#prerequisites]
== Prerequisites

* xref:first-steps#[A CircleCI account]
* A Go project located in a supported VCS

[#configuration-walkthrough-new]
== Configuration walkthrough

Every CircleCI project requires a configuration file called xref:configuration-reference#[`.circleci/config.yml`]. Follow the steps below to create a working `config.yml` file.

[#specify-a-version-new]
=== 1. Specify a version

Every CircleCI config.yml starts with the version key. This key is used to issue warnings about breaking changes.

[,yaml]
----
version: 2.1
----

`2.1` is the latest CircleCI version, and it ensures you have access to all our latest features and improvements.

[#use-the-go-orb]
=== 2. Use the Go orb

The Go link:https://circleci.com/developer/orbs/orb/circleci/go[orb] contains a set of prepackaged CircleCI configurations you can use to perform common CircleCI tasks for the Go programming language. It supports Linux x86_64, macOS x86_64, and Arm64. Learn more about xref:orb-intro#[orbs].

To add the orb to your config, insert:

[,yaml]
----
orbs:
  go: circleci/go@1.7.3
----

NOTE: When using an orb, it is a good idea to check the link:https://circleci.com/developer/orbs[Orb Registry] to ensure you are using the most recent version, or the version that fits best with your specific project.

[#create-jobs]
=== 3. Create jobs

Jobs are the building blocks of your config. Jobs are collections of steps, which run commands/scripts as required. All of the steps in the job are executed in a single unit, either within a fresh container or virtual machine. Learn more about jobs on the xref:jobs-steps#[Jobs and Steps] page.

A common ask from developers who are getting started with CircleCI is to perform three basic tasks: `build`, `test` and `deploy`. This section guides you through each of the config changes needed. Because we are using the official Go orb, we can use commands that are built into the orb to keep our config simple and succinct.

[#build-and-test-the-app]
==== a. Build and test the app

For this step, we use commands that come preconfigured in the Go link:https://circleci.com/developer/orbs/orb/circleci/go[orb]. Go modules are downloaded and cached and tests are run.

[,yaml]
----
jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.19.2' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .
----

[#deploy-the-app]
==== b. Deploy the app

In this quickstart guide, we will deploy to link:https://www.heroku.com/[Heroku]. We can do this using the official Heroku orb by adding a new line into our orb section. The Heroku orb contains a set of prepackaged CircleCI configurations you can use to deploy applications to Heroku. Learn more about the link:https://circleci.com/developer/orbs/orb/circleci/heroku[Heroku orb].

[,yaml]
----
orbs:
  go: circleci/go@1.7.3
  heroku: circleci/heroku@1.2.6
----

We then need to add a job to our list to take care of the deploy step:

[,yaml]
----
jobs:
  # ...previous job(s)...
  deploy: # this can be any name you choose
    executor: heroku/default # use the default executor defined within the orb
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
----

NOTE: Environment variables containing the necessary secrets such as `HEROKU_API_KEY` and `HEROKU_APP_NAME` can be set up in the CircleCI web app. Learn more about xref:set-environment-variable#set-an-environment-variable-in-a-project[environment variables].

[#create-a-workflow]
=== 4. Create a workflow

A workflow is a set of rules for defining a collection of jobs and their run order. Workflows support complex job orchestration using a set of configuration keys to help you resolve failures sooner. Inside the workflow, you define the jobs you want to run. CircleCI will run this workflow on every commit. Learn more about xref:configuration-reference#workflows[workflow configuration].

[,yaml]
----
workflows:
  build_test_deploy: # this can be any name you choose
----

[#add-jobs-to-the-workflow]
=== 5. Add jobs to the workflow

Now that we have our workflow, `build_test_deploy`, we can use it to orchestrate the running of our `build_and_test` and `deploy` jobs. Refer to the xref:workflows#[Using Workflows to Orchestrate Jobs] page for more details about orchestrating jobs with concurrent, sequential, and manual approval workflows.

[,yaml]
----
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
----

[#conclusion]
=== 6. Conclusion

You just set up a Go app to build on CircleCI, and deploy to Heroku. Check out your project's link:{{site.baseurl}}/pipelines/[pipeline page] to see how this looks when building on CircleCI.

NOTE: *Deploy options?* For alternative deployment targets, search the link:https://circleci.com/developer/orbs[orb registry], where you will find integrations such as link:https://circleci.com/developer/orbs/orb/circleci/kubernetes[Kubernetes], link:https://circleci.com/developer/orbs/orb/circleci/aws-ecs[AWS ECS], link:https://circleci.com/developer/orbs/orb/circleci/gcp-gke[GCP GKE], and more.

[#full-configuration-file-new]
== Full configuration file

[,yaml]
----
version: 2.1
orbs:
  go: circleci/go@1.7.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.19.2' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .

  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
----

[#see-also-new]
== See also

* xref:rerun-failed-tests#configure-a-job-running-go-tests[Test splitting and rerun failed tests for Go]
* link:https://circleci.com/blog/continuous-integration-for-go-applications/[Continuous integration for Go applications]
* Tutorial: xref:test-splitting-tutorial#[Test splitting to speed up your pipelines]
