---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= CircleCI Linux CUDA images support policy
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI Linux CUDA images release, update, and deprecation policy
:icons: font
:toc: macro
:toc-title:

{% include snippets/linux-cuda-deprecation-brownout.adoc %}

[#overview]
== Overview

This document outlines the xref:using-gpu#linux-gpu[CircleCI Linux CUDA image] release, update, and deprecation policy and applies to our Linux CUDA images.

[#release-policy]
== Release policy

The CircleCI CUDA images are based on our Linux VM machine images for the purpose of providing an image that can leverage the additional processing capabilities of CircleCI’s GPU executor.

We aim to support the three most recent minor versions (or three most recent even numbered minor versions, if minor version >= `6`) of the two most recent and supported major CUDA releases. We closely track Nvidia’s own release cycle and aim to release our images within a week of the CUDA release.

Please note that this is not an SLA (service level agreement). We can not, and do not, provide an official SLA turnaround time for new CUDA images.

[#tagging]
== Tagging

The following tags are available for the CircleCI Linux CUDA images:

* Date-based: `linux-cuda-<CUDA-version>:<year.month.patch>`
** For example, `linux-cuda-11:2023.02.1`
** The “default” slugs point to the latest version of the image, on a rolling basis.
*** For example, `linux-cuda-11:default` or `linux-cuda-12:default`
* Edge: `linux-cuda-<CUDA-version>:edge`
** `edge` images incorporate any new changes, if you want the latest version as fast as possible. The `edge` tag becomes available a week prior to general releases.


[#critical-cve-patches]
== Critical CVE patches

When critical CVEs are disclosed that affect the versions of the operating system or software stack in either Linux or Windows images, we will investigate the impact that this has on our images being used across CircleCI execution environments.

In most cases, due to the ephemeral and isolated nature of the environment, it is not necessary to patch these images. We will always communicate our stance on these disclosures via our link:https://discuss.circleci.com/[Discuss Forum].

[#bug-reports-issues-and-prs]
== Bug reports, issues, and PRs

Please file a link:https://support.circleci.com/hc/en-us/requests/new[support ticket] with CircleCI Support for any issues or bugs found with the CircleCI Linux CUDA images. Our support team will be able to escalate issues internally to the correct engineering team and provide updates on the issue.

[#image-lifespan-eol]
== Image lifespan / EOL

Image lifespan will generally follow Nvidia’s CUDA release cycle.

Once a new major version of CUDA is released, we will begin the deprecation process of the oldest major version that we support and schedule it to be removed. This allows us to maintain two major versions of CUDA effectively.

=== Examples

A major version release -- CUDA 12.0:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Version
| Support

| CUDA 12
| `linux-cuda-12` image added

| CUDA 11
| No change

| CUDA 10
| `linux-cuda-10` image deprecated
|===

A minor version release -- CUDA 11.8:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Version
| Support

| CUDA 11.8
| Added to `linux-cuda-11`

| CUDA 11.6
| Remains in the image

| CUDA 11.4
| Remains in the image; becomes “oldest”

| CUDA 11.2
| Removed from `linux-cuda-11`
|===

Once a new even numbered minor version is released, that version will be added and the oldest existing version will be removed, provided that more than 3 minor versions exist.

When an image is selected for deprecation and removal, we will create an announcement on our Discuss forum, along with reaching out via email to developers who have requested one of the deprecated images in their recent jobs. We will also plan brownouts to help ensure you are aware of the approaching removal of deprecated images.

[#exceptions]
== Exceptions

​​At any time, we reserve the right to work outside of the information in this document if the circumstances require. In the event that we are required to make an exception to the policy, we will aim to provide as much notice and clarity as possible. In these cases, an announcement will be posted on our Discuss Forum, along with additional outreach, such as an email notice, where possible.
