---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= CircleCI Linux VM images support policy
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI Linux VM (Machine) Images release, update, and deprecation policy.
:icons: font
:toc: macro
:toc-title:

[#overview]
== Overview

This document outlines the xref:using-linuxvm#[CircleCI Linux VM (machine) images] release, update, and deprecation policy.

This policy applies to all CircleCI Linux VM (machine) images built for the machine executor.

[#release-policy]
== Release policy

The CircleCI Linux VM images are all based on Ubuntu and we support both arm64 and amd64 architectures. We aim to maintain, support, and release the two most recent LTS versions of Ubuntu. 

We also aim to release a beta version of any upcoming LTS before Canonical’s GA release, and a GA version within six months of the Ubuntu release date.

Linux images are released on a quarterly basis, with any security issues or critical updates resulting in a patch for that quarterly release. Generally speaking, these updates will include the latest versions of software at the time of creation; however, this can vary with regards to stability and compatibility. In these cases, the latest stable version will typically be used.

We always aim to release a monthly image within the first week of the month.

[#tagging]
== Tagging

Tags are separated into distinct types of tags: `edge` tags, dated tags, and aliases.

* `edge` tags are reserved for previews of new releases, which will initially point to this tag. The `edge` tags may include incremental updates to the current monthly image release, which may change without notice, and should not be used for production CI workloads.
+
After a couple of days to allow for testing and ensure stability, `current`, `default`, and `dated` tags are then updated to point to the latest release.
 
* The date-based tagging conventions take the format of `<year>.<month>.<patch>`, such as `2023.04.1`.
+
The Ubuntu LTS-based images have the image slug format of: `ubuntu-<LTS version>:<year>.<month>.<patch>`, such as `ubuntu-2204:2023.04.2`.

* `current` and `default` are aliases that may point to the same release, but can potentially differ and can change without notice. We advise customers to use date-based tags for deterministic workflows.

[#critical-cve-patches]
== Critical CVE patches

When critical CVEs are disclosed that affect the versions of the operating system or software stack in our Linux images, we will investigate the impact that this has on our images being used within the CircleCI execution environment. 

In most cases, due to the ephemeral and isolated nature of the containers in the environment, it is not necessary to patch these images. We will always communicate our stance on these disclosures via our https://discuss.circleci.com/[Discuss Forum].

[#bug-reports-and-issues]
== Bug reports and issues

Please file a https://support.circleci.com/hc/en-us/requests/new[support ticket] with CircleCI Support for any issues or bugs found with the Linux VM (machine) images. Our Support Team will be able to escalate issues internally to the correct engineering team and provide updates on the issue.

[#image-lifespan-eol]
== Image lifespan / EOL

Image lifespan will generally follow the support status of Ubuntu by Canonical. Once a new Ubuntu LTS is released, we will begin the deprecation process of the oldest version that we support and schedule it to be removed. This allows us to maintain our aim of two LTS Ubuntu versions effectively.

Example: When Ubuntu 24.04 LTS is released:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Version
| Support

| Ubuntu 18.04 LTS
| Deprecated and removed entirely

| Ubuntu 22.04 LTS
| Quarterly images built and retained. Other monthly releases deprecated and removed

| Ubuntu 24.04 LTS
| Monthly images built and retained
|===

When an image is selected for deprecation and removal, we will create an announcement on our Discuss forum, along with reaching out via email to developers who have requested one of the deprecated images in their recent jobs. We will also plan brownouts to ensure users are aware of the approaching removal of deprecated images.

[#exceptions]
== Exceptions

​​At any time, we reserve the right to work outside of the information in this document if the circumstances require. In the event that we are required to make an exception to the policy, we will aim to provide as much notice and clarity as possible. In these cases, an announcement will be posted on our Discuss Forum, along with additional outreach, such as an email notice, where possible.

[#addendum]
== Addendum

Remote Dockers are images that enable the use of remote Docker. Support for these are tied to: 1) Docker official support for the version, and 2) image lifespan of the corresponding quarterly Linux image that enables them.
