---
contentTags:
  platform:
  - Cloud
  - Server v4.4+
---
= Machine runner 3.0 manual installation
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to manually start CircleCI's self-hosted machine runner 3.0 on macOS and Linux.
:icons: font
:experimental:
:machine:
:macOS:
:linux:

This page describes how to manually start CircleCI's machine runner 3.0 on macOS and Linux.

CAUTION: We recommend installing and using CircleCI machine runner 3.0 with xref:install-machine-runner-3-on-macos.adoc[the Homebrew package] on macOS and xref:install-machine-runner-3-on-linux.adoc[the Linux packages] on Linux. The manual method described on this page is an optional alternative.

WARNING: If you follow this manual installation method, CircleCI machine runner 3.0 will not automatically update.

[#prerequisites]
== Prerequisites

To install machine runners and run jobs, you will need to have root access, and have the following utilities and tools installed on your system:

* https://www.gnu.org/software/coreutils/[Coreutils] - Linux only

* https://brew.sh/[Homebrew] - macOS only

* https://curl.se/[curl] (installed by default on macOS)

* sha256sum (if not pre-installed):
** `brew install coreutils`
** `sudo apt install coreutils` for Ubuntu/Debain
** `sudo yum install coreutils` for Red Hat

* https://www.gnu.org/software/tar/[tar]

* https://www.gnu.org/software/gzip/[Gzip] - Linux only

* `sepolicy` (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] only) - Linux only
* `rpmbuild` (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] only) - Linux only

* The xref:local-cli#[CircleCI CLI] if you wish to install runners from the command line

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

{% include snippets/runner/install-with-cli-steps.adoc %}

[#download-circleci-runner]

[#download-machine-runner]
== 2. Download the CircleCI machine runner

NOTE: The current CircleCI machine runner binary can always be found by using `current` as the version. To install a specific previous version of the CircleCI runner the `$RUNNER_VERSION` environment variable can be changed from the value of `current` to the specific preferred version.

[,shell]
----
export RUNNERVERSION='current'
export CPUARCH=$(/usr/bin/arch | grep 'x86_64' >/dev/null 2>/dev/null && echo 'amd64' || echo 'arm64')
export OSTARGET=$(uname -s | tr '[:upper:]' '[:lower:]')
curl -s -L "https://circleci-binary-releases.s3.amazonaws.com/circleci-runner/${RUNNERVERSION}/circleci-runner_${OSTARGET}_${CPUARCH}.tar.gz" -o $HOME/circleci-runner.tar.gz && tar -zxvf $HOME/circleci-runner.tar.gz
----

[#mark-machine-runner-as-executable]
== 3. Mark the CircleCI machine runner as executable

Update permissions for your CircleCI machine runner to enable running its binary:

[,shell]
----
chmod +x $HOME/circleci-runner
----

[#create-configuration-and-working-directory]
== 4. Create the CircleCI machine runner configuration and working directory

. Create the directory in which CircleCI machine runner jobs will start:
+
[,shell]
----
mkdir $HOME/circleci
----

. Create a CircleCI runner configuration file:
+
[,shell]
----
touch $HOME/circleci-runner-config.yaml
----

. Populate the newly created file with the configuration for your runner. An example can be seen below.
+
NOTE: You will need to change the `auth_token` value from `"your-auth-token"` to the resource class token created in step 1.
+
[,shell]
----
nano $HOME/circleci-runner-config.yaml
----
+
[,shell]
----
runner:
  name: "my-macos-runner"
  working_directory: "$HOME/circleci"
  cleanup_working_directory: true
api:
  auth_token: "your-auth-token"
----
. If you are using CircleCI server you will need to provide the URL for your install. You can do this by adding the URL to `$HOME/circleci-runner-config.yaml` using text editor of your choice.
+
```yaml
api:
  auth_token: "your-auth-token"
  # On server, set url to the hostname of your server installation.
  url: https://runner.circleci.com
```

[#start-machine-runner]
== 5. Start the CircleCI machine runner

[,shell]
----
$HOME/circleci-runner machine --config $HOME/circleci-runner-config.yaml
----

[#additional-resources]
== Additional resources

- xref:install-machine-runner-3-on-linux.adoc[Machine runner 3.0 Linux package installation]
- xref:install-machine-runner-3-on-macos.adoc[Machine runner 3.0 macOS Homebrew installation]
- xref:install-machine-runner-3-on-docker.adoc[Machine runner 3.0 Docker installation]
- xref:install-machine-runner-3-on-windows.adoc[Machine runner 3.0 Windows installation]
- xref:machine-runner-3-configuration-reference.adoc[Machine runner 3.0 configuration reference]
