---
contentTags:
  platform:
  - Cloud
---
= Machine runner 3.0 manual installation for Windows
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to manually start CircleCI's self-hosted machine runner 3.0 on Windows.
:icons: font
:machine:
:Windows:

This page describes how to manually run CircleCI's machine runner 3.0 on Windows Server.

[#prerequisites]
== Prerequisites

{% include snippets/runner/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

{% include snippets/runner/install-with-cli-steps.adoc %}

[#download-machine-runner]
== 2. Download the CircleCI machine runner
. Using PowerShell download the current version of CircleCI machine runner and verify the download.

NOTE: The current CircleCI machine runner binary can always be found by using `current` as the version. To install a specific previous version of the CircleCI runner the `$runnerVersion` variable can be changed from the value of `current` to the specific preferred version.

[,shell]
----
$runnerVersion = "current"
$availableAgents = (Invoke-WebRequest "https://circleci-binary-releases.s3.amazonaws.com/circleci-runner/manifest.json" -UseBasicParsing).Content.Trim() | ConvertFrom-Json
$agentURL = $availableAgents.releases.$runnerVersion.windows.amd64.url
$agentHash = $availableAgents.releases.$runnerVersion.windows.amd64.sha256
$agentFile = $agentURL.Split("/")[-1]

Invoke-WebRequest $agentURL -OutFile $agentFile -UseBasicParsing
if ((Get-FileHash "$agentFile" -Algorithm SHA256).Hash.ToLower() -ne $agentHash.ToLower()) {
    throw "Invalid checksum for CircleCI Machine Runner, please try download again"
}

tar -zxvf $agentFile
del $agentFile
----

[#create-configuration-and-working-directory]
3. Create the CircleCI machine runner configuration and working directory
. Using PowerShell create the CircleCI machine runner configuration file and working directory.

NOTE: The runner token created in #create-namespace-and-resource-class will need to be substituted in for the auth_token

[,shell]
----
New-Item -Name Workdir -ItemType Directory
@"
api:
  auth_token: "1e8e5665db675aa30abab7218e3c10ffbaaa1b52aaa86dcfbacb9bbbaece306ed66c6d7f181145d8"
  url: https://runner.circleci.com
runner:
  name: "$env:COMPUTERNAME"
  mode: single-task
  working_directory: "./Workdir"
  cleanup_working_directory: true
logging:
  file: circleci-runner.log
"@ -replace "([^`r])`n", "`$1`r`n" | Out-File machine-runner-config.yaml -Encoding ascii

----

[#start-machine-runner]
== 4. Start the CircleCI machine runner
[,shell]
----
./circleci-runner.exe machine --config machine-runner-config.yaml
----

[#additional-resources]
== Additional resources

xref:machine-runner-3-configuration-reference.adoc[Machine runner 3.0 configuration reference]
