---
contentTags:
  platform:
  - Cloud
---
= Migrate from launch agent to machine runner 3.0 on Windows - Open preview
:page-layout: classic-docs
:page-liquid:
:page-description: Steps to migrate from using launch agent to the machine runner 3.0 preview on Windows
:icons: font
:toc: macro
:toc-title:
:machine:
:Windows:

This page describes how to migrate an existing launch agent installation to machine runner 3.0. Machine runner 3.0 on Windows.

Migrating from launch agent to machine runner 3.0 is a straightforward process. The prerequisites remain the same. First, uninstall and remove launch agent, then, install the machine runner 3.0 agent. The configuration file is 1:1 compatible between the agents so no modifications are needed during the migration

[#uninstall-launch-agent]
1. Uninstall launch agent
The first step is to uninstall launch agent. 

. Download the https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install[`Uninstall-CircleCIRunner.ps1` script] from GitHub to an easily accessible location.
. Open PowerShell as an administrator and navigate to the directory where you placed the script file.

. Run the following in your PowerShell:
+
```
./Uninstall-CircleCIRunner.ps1
```

[#copy-current-runner-configuration]
3. Copy current launch agent configuration

. Machine runner 3.0 is backwards compatible with the launch-agent configuration file. Using PowerShell copy the existing launch-agent config for use with the machine runner 3.0 installation.

[,shell]
----
$desktopDir = [Environment]::GetFolderPath("Desktop")
copy "$env:ProgramFiles\CircleCI\runner-agent-config.yaml" "$desktopDir/runner-agent-config.yaml"
----

[#install-machine-runner]
2. Install machine runner 3.0

. Download the https://github.com/CircleCI-Public/runner-installation-files/tree/main/windows-install/circleci-runner[`Install-CircleCIRunner.ps1` script] from GitHub to an easily accessible location.

. Open PowerShell as an administrator and navigate to the directory where you placed the script file.

. Run the following in your PowerShell:
+
[,shell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
./Install-CircleCIRunner.ps1
----
+
The installation will be output into your PowerShell interface.

. As part of the installation, the configuration file for the machine runner (`launch-agent-config.yaml`) will open in Notepad. Please fill the file out with the information from the previous configuration file copied in the [copy current runner configuration step](#copy-current-runner-configuration). The configuration file is located in the installation directory, `C:\Program Files\CircleCI`, by default.

After setup completes, the machine runner starts automatically and begins looking for jobs to process.

{% include snippets/machine-runner-example.adoc %}
