---
version:
- Cloud
- Server 3.x
---
= Migrate from GitLab
:page-layout: classic-docs
:page-liquid:
:page-description: An overview of how to migrate from GitLab to CircleCI.
:icons: font
:toc: macro
:toc-title:

This document provides an overview of how to migrate from GitLab to CircleCI.

NOTE: **Tips provided by ImagineX Consulting**

[#source-control-setup]
== Source control setup

If you are using GitLab's SCM, you will first need to migrate your source code to GitHub or BitBucket. See the following for details on how to import your code:

* https://help.github.com/en/articles/importing-a-repository-with-github-importer[Import into GitHub]
* https://confluence.atlassian.com/get-started-with-bitbucket/import-a-repository-861178561.html[Import into BitBucket]

[#github-enterprise]
=== GitHub Enterprise

Following are the steps required for using the git command line tool to import your GitLab repo into GitHub Enterprise:

. Create an empty repository on your GitHub Enterprise instance.
. Create a bare clone of your GitLab.com repository on your local machine, fetching all remote tags (refs/tags/\*) and copying all remote branch heads (refs/heads/\*) directly to their corresponding local branch heads:
+
```shell
git clone git@gitlab.com:[owner]/[repo-name].git --bare
```
. Add your GitHub Enterprise repository as a remote reference in your local clone:
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. Push all local references (refs/\*) up to your remote GitHub Enterprise repository:
+
```shell
git push enterprise --mirror
```

If you need to export other GitLab artifacts, follow the GitLab documentation on https://docs.gitlab.com/ee/user/project/settings/import_export.html#exporting-a-project-and-its-data[exporting a project].

Once you have imported your code into GitHub or BitBucket, you can start creating a project in CircleCI using the https://circleci.com/docs/2.0/getting-started/[Getting Started guide].

[#build-configuration]
== Build configuration

If you are using GitLab's CI/CD, you will need to migrate your build configuration. On GitLab, the build configuration is defined in a file called `.gitlab-ci.yml` in the root directory of your source code repository. If you use shell scripts to perform your build, you can reuse those scripts in CircleCI.

First, create a CircleCI build configuration file. In the root directory of your source code repository, create a folder named `.circleci` and create a file in that folder named `config.yml`. Next, follow the CircleCI documentation https://circleci.com/docs/2.0/config-intro/[here] to learn how to configure the `.config.yml` file.

The GitLab and CircleCI configurations will be different. It may be helpful to have both GitLab and CircleCI reference documentation open side-by-side to help with the conversion of the build steps:

* https://docs.gitlab.com/ee/ci/yaml/[GitLab YML Reference]

* https://circleci.com/docs/2.0/configuration-reference/[CircleCI YML Reference]

[#configuration-comparison]
== Configuration comparison

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
| GitLab | CircleCI

2+| Defining a job that executes a single build step
a|
[source, yaml]
----
job1:
  script: "execute-script-for-job1"
----

a|
[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"
----

2+| Specify a Docker image to use for a job.

a|
[source, yaml]
----
job1:
  image: node:10
----

a|
[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10
----

2+| Define a multi-stage build pipeline. Job1 and Job2 run concurrently. Once they’re done, Job3 runs. Once Job3 is done, Job4 runs.

a|
[source, yaml]
----
job1:
  stage: build
  script: make build dependencies

job2:
  stage: build
  script: make build artifacts

job3:
  stage: test
  script: make test

job4:
  stage: deploy
  script: make deploy

stages:
  - build
  - test
  - deploy
----

a|
[source, yaml]
----
version: 2
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  version: 2
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----



2+| Execute jobs on multiple platforms. GitLab uses tags to identify build runners. CircleCI provides all major OSes and Docker and must explicitly set in config. See our https://circleci.com/docs/2.0/executor-intro/#section=configuration[execution environments documentation] for more information.

a|
[source, yaml]
----
ubuntu job:
  tags:
    - ubuntu
  script:
    - echo "Hello, $USER!"

osx job:
  tags:
    - osx
  script:
    - echo "Hello, $USER!"
----

a|
[source, yaml]
----
jobs:
  ubuntu-job:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osx-job:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----


2+| Cache Dependencies.

a|
[source, yaml]
----
image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

test_async:
  script:
    - node ./specs/start.js
----

a|
[source, yaml]
----
{% raw %}
jobs:
  test_async:
    steps:
      - restore_cache:
          key: source-v1-{{ checksum "package.json" }}
      - checkout
      - run: npm install
      - save_cache:
          key: source-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: node ./specs/start.js
{% endraw %}
----
|===

For larger and more complex build files, we recommend moving over the build steps in phases until you get comfortable with the CircleCI platform. We recommend this order:

. https://circleci.com/docs/2.0/executor-intro/[Pick your executor]
. https://circleci.com/docs/2.0/configuration-reference/#checkout[Checkout code]
. https://circleci.com/docs/2.0/env-vars/[Environment variables] and https://circleci.com/docs/2.0/contexts/[Contexts]
. Install dependencies, also see https://circleci.com/docs/2.0/caching/[Cache dependencies]
. https://circleci.com/docs/2.0/configuration-reference/#docker[Service containers]
. Run testing commands
. https://circleci.com/docs/2.0/custom-images/[Custom convenience images]
. https://circleci.com/docs/2.0/configuration-reference/#resource_class[Resource classes]
. https://circleci.com/docs/2.0/workflows/[Workflows]
. https://circleci.com/docs/2.0/collect-test-data/[Test results] / test splitting / https://circleci.com/docs/2.0/parallelism-faster-jobs/[parallelism]
. https://circleci.com/docs/2.0/artifacts/[Artifacts]
