---
contentTags:
  platform:
  - Cloud
  - Server v4+
---
= Migrate from GitHub Actions
:page-layout: classic-docs
:page-description: An overview of how to migrate from GitHub Actions to CircleCI.
:icons: font
:experimental:

This document provides an overview of how to migrate from GitHub Actions to CircleCI.

TIP: The link:https://circleci.com/developer/tools/configTranslator[CircleCI configuration translator] provides a way to convert your GitHub Actions or GitLab config into a CircleCI `config.yml` file. The configuration translator is currently in open preview.

[#concepts]
== Concepts

[#jobs-and-workflows]
=== Jobs and workflows

Both GitHub Actions and CircleCI share similar concepts around "jobs" and "workflows". A workflow is an end-to-end flow of connected jobs, which in turn consist of commands to achieve an atomic task (for example, "run unit tests" or "build a Docker image").

CircleCI differs primarily in configuration syntax, setting up workflow and job dependencies in a separate section as opposed to inline in the job.

[.table.table-striped.table-migrating-page.table-no-background]
[cols=2*, options="header", stripes=even]
[cols="50%,50%"]
|===
| GitHub | CircleCI

a|
[source, yaml]
----
name: My GitHub Actions Workflow

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      # job steps
  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      # job steps
----

a|
[source, yaml]
----
jobs:
  job_1:
    executor: my-ubuntu-exec
    steps:
      # job steps
  job_2:
    executor: my-ubuntu-exec
    steps:
      # job steps

workflows:
  my_workflow:
    jobs:
      - job_1
      - job_2:
          requires:
            - job_1
----
|===

[#actions-vs-orbs]
=== Actions vs. orbs
"Actions" in GitHub are reusable commands or tasks to run inside a job. However, they are written for execution inside a Docker container or coded as individual steps using JavaScript. This adds additional work and limits the scope in which they can be applied.

CircleCI offers similar functionality in our xref:orb-intro#[orbs]. The primary difference is that CircleCI orbs are just packaged, reusable YAML, so you can create orbs with reusable jobs, executors, or commands, and use them however you see fit in any of your jobs or workflows.

GitHub offers browsing of Actions in their Marketplace; CircleCI has an https://circleci.com/developer/orbs[Orb Registry] as well as an https://circleci.com/integrations/[Integrations Page] containing numerous Certified, Partner, and community orbs / integrations.

[#runners-vs-executors]
=== Runners vs. executors
In GitHub, you can specify your builds to run in Linux, macOS, and Windows environments via a `runs-on` key in the YAML, and if you want to run anything in a container, you specify an additional `container` key.

In CircleCI, you have the same choice of environments (called Executors), with additional options and features for Docker.

For each of the https://circleci.com/docs/executor-intro/[executor types], you have a choice of different versions which will subsequently have various versions of base software installed.

See the table in the next section to compare configuration.

[#configuration-comparison]
== Configuration comparison

include::../_includes/partials/notes/docker-auth.adoc[]

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
| GitHub Config | CircleCI Config

2+| Specifying execution environment. While container execution is specified separately in GitHub, +
`docker` is its https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor[own class of executor] in CircleCI.

a|
[source, yaml]
----
# Choosing an Operating System
runs-on: ubuntu-latest # or windows, etc.

# If running steps on a container
container:
  image: openjdk:17.0-jdk
----

a|
[source, yaml]
----
# Docker (container) Executor
docker:
  - image: cimg/openjdk:17.0

# Linux Ubuntu Executor
machine:
  image: ubuntu-2004:202010-01

# macOS Executor
macos:
  xcode: 14.2.0

# Windows Executor
machine:
  image: 'windows-server-2022-gui:current'
resource_class: windows.medium # can be medium, large, xlarge, 2xlarge
----

2+| Specifying dependencies/services. All images specified after the first in CircleCI are treated https://circleci.com/docs/configuration-reference/#docker[as dependencies].

a|
[source, yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest

    # Main container
    container:
      image: openjdk:17.0-jdk

    # Dependency Service(s)
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
----

a|
[source, yaml]
----
jobs:
  build:
    docker:
      # Primary Executor
      - image: cimg/openjdk:17.0
      # Dependency Service(s)
      - image: postgres:10.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
----

2+| Specifying steps to https://circleci.com/docs/configuration-reference/#run[run] in a job. Similar functionality, different syntax.

a|
[source, yaml]
----
jobs:
  build:
    # runner config here

    steps:
      - name: Build with Gradle
        run: ./gradlew build
----

a|
[source, yaml]
----
jobs:
  build:
    # executor config here

    steps:
      - run:
          name: Build with Gradle
          command: ./gradlew build
----

2+| Using shared tasks (Actions for GitHub, orbs for CircleCI). In CircleCI, you declare orbs at the top level +
and then https://circleci.com/docs/configuration-reference/#orbs[refer to them by name in config], similar in concept to Python or JavaScript imports.

a|
[source, yaml]
----
jobs:
  build:
    # runner config here

    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v1.0.0
        env:
          SLACK_COLOR: '#32788D'
          SLACK_MESSAGE: 'Tests passed'
          SLACK_TITLE: Slack Notify GA
          SLACK_USERNAME: Bobby
          SLACK_WEBHOOK: # WEBHOOK
----

a|
[source, yaml]
----
orbs:
  slack-orb: circleci/slack@3.4.0

jobs:
  build:
    # executor config here

    steps:
      - slack-orb/notify:
          color: '#32788D'
          message: Tests passed
          title: Testing Slack Orb
          author_name: Bobby
          webhook: # WEBHOOK
----

2+a| Using conditional steps in the workflow. CircleCI offers the following:

* xref:configuration-reference#the-when-attribute[Basic conditions on steps, using the `when` attribute] (for example, `on_success` [default], +
`always`, `on_failure`).
* https://circleci.com/docs/configuration-reference/#the-when-step[Conditional steps] based on parameters.
* https://circleci.com/docs/reusing-config/#using-the-parameters-declaration[Conditional jobs].
* Conditional, parameterized xref:workflows#use-conditional-logic-in-workflows[workflows].

a|
[source, yaml]
----
jobs:
  build:
    # environment config here

    steps:
      - name: My Failure Step
        run: echo "Failed step"
        if: failure()
      - name: My Always Step
        run: echo "Always step"
        if: always()
----

a|
[source, yaml]
----
jobs:
  build:
    # executor config here

    steps:
      - run:
          name: My Failure Step
          command: echo "Failed step"
          when: on_fail
      - run:
          name: My Always Step
          command: echo "Always step"
          when: always
----
|===

For more configuration examples on CircleCI, visit our <<examples-and-guides-overview#,Examples and Guides Overview>> and <<example-configs#,Example Projects>> pages.

Since the configuration between GitHub Actions and CircleCI is similar, it should be fairly trivial to migrate your jobs and workflows. However, for best chances of success, we recommend migrating over items in the following order:

. https://circleci.com/docs/concepts/#section=getting-started[Jobs, Steps, and Workflows]
. https://circleci.com/docs/workflows/[More Advanced Workflow and Job Dependency Configuration]
. https://circleci.com/docs/orb-intro/[Actions to Orbs]. Our registry can be found https://circleci.com/developer/orbs?filterBy=all[here].
. https://circleci.com/docs/optimizations/#section=projects[Optimizations like caching, workspaces, and parallelism]
