---
version:
- Cloud
- Server 3
---

= Migrating from Buildkite
:page-layout: classic-docs
:page-liquid:
:page-description: An overview of how to migrate from Buildkite to CircleCI.
:icons: font
:toc: macro
:toc-title:

This document provides an overview of how to migrate from Buildkite to CircleCI.

NOTE: **Tips provided by ImagineX Consulting**

[#source-control-setup]
== Source control setup
First you will need to ensure your source code is located in either to GitHub or BitBucket. See the following for details on how to import your code:

* https://help.github.com/en/articles/importing-a-repository-with-github-importer[GitHub]
* https://help.github.com/en/articles/importing-a-repository-with-github-importer[BitBucket]

[#github-enterprise]
=== GitHub Enterprise

Following are the steps required for using the git command line tool to import your code into GitHub Enterprise:

. Create an empty repository on your GitHub Enterprise instance.
. Create a bare clone of your external repository on your local machine, fetching all remote tags (refs/tags/\*) and copying all remote branch heads (refs/heads/\*) directly to their corresponding local branch heads.
+
```shell
git clone https://external-host.com/extuser/repo.git --bare
```
. Add your GitHub Enterprise repository as a remote reference in your local clone.
+
```shell
cd [repo-name]
git remote add enterprise git@[hostname]:[owner]/[repo-name].git
```
. Push all local references (refs/*) up to your remote GitHub Enterprise repository.
+
```shell
git push enterprise --mirror
```

Once you have imported your code into GitHub or BitBucket, you can start creating a project in CircleCI using the https://circleci.com/docs/2.0/getting-started/[Getting Started guide].

[#build-configuration]
== Build configuration

Next, you will need to migrate your build configuration. On Buildkite, the build configuration is either defined in the web interface or in a file called `.pipeline.yml` in the root directory of your source code repository. If you use shell scripts to perform your build, you can reuse those scripts in CircleCI.

First, create a CircleCI build configuration file. In the root directory of your source code repository, create a folder named .circleci and create a file in that folder named config.yml. Next, follow the CircleCI documentation here to learn how to configure the .config.yml file.

The Buildkite and CircleCI configurations will be different. It may be helpful to have both Buildkite and CircleCI reference documentation open side-by-side to help with the conversion of the build steps:

* https://buildkite.com/docs/pipelines/defining-steps[Buildkite Pipeline Reference]

* https://circleci.com/docs/2.0/configuration-reference/[CircleCI YML Reference]

[#configuration-comparison]
== Configuration comparison

[.table.table-striped.table-migrating-page]
[cols=2*, options="header,unbreakable,autowidth", stripes=even]
[cols="5,5"]
|===
| Buildkite | CircleCI

2+| Define a job that executes a single build step.

a|
[source, yaml]
----
steps:
  - command: 'execute-script-for-job1.sh'
----

a|
[source, yaml]
----
jobs:
  job1:
    steps:
      - checkout
      - run: "execute-script-for-job1"
----

2+| Specify a docker image to use for a job.

a|
[source, yaml]
----
steps:
  - label: 'job1'
    plugins:
      - docker#v3.2.0:
          image: 'node:10'

----

a|
[source, yaml]
----
jobs:
  job1:
    docker:
      - image: node:10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

----

2+| Define a multi-stage build pipeline. Job1 and Job2 run concurrently. Once they are done, Job3 runs. Once Job3 is done, Job4 runs.

a|
[source, yaml]
----
steps:
  - label: 'job1'
    command: 'make build dependencies'

  - label: 'job2'
    command: 'make build artifacts'

  - wait

  - label: 'job3'
    command: 'make test'

  - wait

  - label: 'job4'
    command: 'make deploy'
----

a|
[source, yaml]
----
version: 2
jobs:
  job1:
    steps:
      - checkout
      - run: make build dependencies
  job2:
    steps:
      - run: make build artifacts
  job3:
    steps:
      - run: make test
  job4:
    steps:
      - run: make deploy

workflows:
  version: 2
  jobs:
    - job1
    - job2
    - job3:
        requires:
          - job1
          - job2
    - job4:
        requires:
          - job3
----

2+| Execute jobs on multiple platforms. Buildkite uses tags to identify build agents. CircleCI provides executors for docker, Linux and MacOS.

a|
[source, yaml]
----
steps:
  - label: 'ubuntuJob'
    agents:
      ubuntu: '16.04'
    command: 'echo "Hello, $USER!"'

  - label: 'osxJob'
    agents:
      osx: 'true'
    command: 'echo "Hello, $USER!"'

----

a|
[source, yaml]
----
jobs:
  ubuntuJob:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: echo "Hello, $USER!"
  osxJob:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "Hello, $USER!"
----
|===

For larger and more complex build files, we recommend moving over the build steps in phases until you get comfortable with the CircleCI platform. We recommend this order:

. Execution of shell scripts and Docker compose files
. https://circleci.com/docs/2.0/workflows/[Workflows]
. https://circleci.com/docs/2.0/artifacts/[Artifacts]
. https://circleci.com/docs/2.0/caching/[Caching]
. https://circleci.com/docs/2.0/triggers/#section=jobs[Triggers]
. https://circleci.com/docs/2.0/optimizations/#section=projects[Performance options]
