---
contentTags:
  platform:
  - Cloud
  - Server v3.x
---
= New Relic integration
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes how to track and visualize analytical data across all of your jobs on CircleCI with New Relic.
:icons: font
:toc: macro

This page describes how to connect Insights data with link:https://newrelic.com/[New Relic].

[#overview]
== Overview
The [New Relic CircleCI integration](https://newrelic.com/instant-observability/circleci) allows you to view analytical data about their CircleCI jobs within the New Relic monitoring stack.

[#integration]
== Integration

Complete the following steps to set up a CircleCI webhook to forward your logs to New Relic. For more information see For more information, refer to the New Relic CircleCI link:https://docs.newrelic.com/docs/logs/forward-logs/circleci-logs/[installation docs].

. Log in to the (https://app.circleci.com/projects)[CircleCI web app]

. Access one of your CircleCI projects

. Open **Project settings**

. In the project settings sidebar, click **Webhooks**

. Click **Add webhook**.

. Name your webhook.

. Enter New Relic's **Logs endpoint** in the **Receiver URL** field. Use the region you set for your New Relic account.
+
Replace `YOUR_LICENSE_KEY` with your New Relic license key, which you can link:https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#manage-license-key)[retrieve from the UI or API].
+
**US**: `https://log-api.newrelic.com/log/v1?Api-Key=YOUR_LICENSE_KEY`
+
**EU**: `https://log-api.eu.newrelic.com/log/v1?Api-Key=YOUR_LICENSE_KEY`

. Select either **Workflow** or **Job**, depending on the type of event you want to trigger the logpush

. If you have set up your receiving API or third-party service, click **Test ping event** to create a test event.