---
contentTags:
  platform:
  - Cloud
  - Server v4+
---
= Introduction to authoring orbs
:page-description: Starting point for how to author an orb
:experimental:
:icons: font
:page-layout: classic-docs


[#quick-start]
== Quick start

Orbs take xref:orb-concepts#orb-configuration-elements[reusable configuration] and package it in a way that can be published to the link:https://circleci.com/developer/orbs[Orb Registry] and imported into multiple configuration files. If you manage multiple, similar projects, consider abstracting out your config with orbs.

Before authoring an orb, it is recommended that you become familiar with the xref:config-intro#[CircleCI config] and authoring xref:reusing-config#[parameterized reusable config elements] pages.

Orbs consist of three main elements:

* xref:orb-concepts#commands[Commands]
* xref:orb-concepts#jobs[Jobs]
* xref:orb-concepts#executors[Executors]

Practice with xref:reusing-config#writing-inline-orbs[inline orbs]. Inline orbs can be defined within a single config file for testing.

NOTE: Orb authors automatically agree to the CircleCI link:https://circleci.com/legal/code-sharing-terms/[Code Sharing Terms of Service]. All publicly published orbs are made available on the Orb Registry under the link:https://opensource.org/licenses/MIT[MIT License agreement]. For more information, see link:https://circleci.com/developer/orbs/licensing[Orb Licensing].

CAUTION: Once an orb is created it cannot be deleted. Orbs are link:https://semver.org/[SemVer compliant], and each published version is immutable. Publicly released orbs are potential dependencies for other projects. Therefore, allowing orb deletion would make users susceptible to unexpected loss of functionality.

[#getting-started]
== Getting started

[#orb-cli]
=== Orb CLI

To begin creating orbs, you will need to xref:local-cli#installation[set up the CircleCI CLI] on your local machine, with a link:https://app.circleci.com/settings/user/tokens[personal access token]. For a full list of orb-related commands inside the CircleCI CLI, visit link:https://circleci-public.github.io/circleci-cli/circleci_orb.html[CircleCI CLI help].

[#permissions-matrix]
=== Permissions matrix

Orb CLI commands are scoped to different user permission levels, set by your VCS. You are the owner of your own organization. If you are authoring or publishing orbs for a namespace owned by another organization, you may require assistance from your organization admin:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Orb Command | Permission Scope

| `circleci namespace create`
| Owner

| `circleci orb init`
| Owner

| `circleci orb create`
| Owner

| `circleci orb publish` development version
| Member

| `circleci orb publish` production version
| Owner
|===

[#register-a-namespace]
=== Register a namespace

Every organization registered on CircleCI is able to claim *one* unique xref:orb-concepts#namespaces[namespace]. This includes your personal organization and any organization you are a member of. As each organization or user account is limited to a single namespace, in order to register the namespace for an organization you must be the _owner_ of the organization.

Enter the following command to claim your namespace, if you have not yet claimed one:

[,shell]
----
circleci namespace create <name> --org-id <your-organization-id>
----

NOTE: If you need help finding your organization ID, visit the xref:introduction-to-the-circleci-web-app#[Introduction to the CircleCI Web App] page.

[#next-steps]
== Next steps

* Continue on to the xref:orb-author#[Orb Authoring Process] guide for information on developing your orb.
* Alternatively, to find out more about orbs read the xref:orb-concepts#[Orb Concepts] page.
