---
contentTags:
  platform:
  - Cloud
---
= Scale Plan
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Scale Plan available to developers on CircleCI.
:icons: font
:experimental:

This document describes the CircleCI Scale Plan.

[#scale-plan]
== Scale Plan
The Scale Plan grows with your team and your business, and offers a wide range of customizations. The Scale Plan offers custom credit options that can be used across all CircleCI resource classes, per month, depending on your build configuration and execution environment. This plan provides access to the highest amount of network and storage usage that CircleCI offers.

The Scale Plan offers several improvements over the Free and Performance Plans:

[#access-to-ip-ranges]
=== Access to IP ranges
Configure IP-based access to restricted environments with IP ranges. Jobs that have the IP ranges feature enabled have traffic routed through one of the defined IP address ranges during job execution. The IP ranges feature is the same on the Performance and Scale Plans.

For more information about this features, refer to the xref:ip-ranges#[IP ranges] page.

[#access-to-all-resource-classes]
=== Access to all resource classes
Access to all of the machine sizes on Docker, Linux, Windows, and macOS. The additional resource classes on the compute type/execution environment give you access to higher CPU and memory limits.

For more information about these resources, refer to the xref:executor-intro#[Executors and images] page.

[#custom-concurrency]
=== Custom concurrency
Customize the amount of jobs you need to run concurrently. This customization is available on all build configurations and execution environments. See <<#concurrency,Concurrency>> below for more information.

[#custom-user-seat-count]
=== Custom user seat count
Customize the amount of active users based on your needs.

[#unlimited-self-hosted-runners]
=== Unlimited self-hosted runners
Unlimited self-hosted runners, allowing you to run more jobs on your own infrastructure. See <<#self-hosted-runners,Self-hosted Runners>> below for more information.

[#custom-storage-retention]
=== Custom storage retention
The link:https://app.circleci.com/[CircleCI web app] allows for the customization of the storage retention periods of artifact, workspace, and cache objects. This allows you to determine how to store each of these objects types in a way that best suits your project. Lowering storage retention periods can also reduce your monthly bill.

[#additional-support-options]
=== Additional support options
Additional support through expanded SLAs, an available account team, training and onboarding options, all of which are expandable with available support package add-ons. The Scale Plan also has access to the link:https://discuss.circleci.com/[community forums], link:https://support.circleci.com/hc/en-us[support portal], and our link:https://support.circleci.com/hc/en-us/requests/new[global ticket-based system].

[#circleci-features]
== CircleCI features
In addition to the upgraded features listed above, the Scale Plan also has access to the features listed below. Refer to the link:https://circleci.com/pricing/[Pricing] page for more detailed information on credit amounts, included resource classes, key features, and support. Refer to the link:https://circleci.com/product/features/resource-classes/[Resource class features] page for details on CPU, memory, network and storage, and credit usage for compute type/execution environment. The following features are available across all of CircleCI's plans.

include::../_includes/snippets/features-of-circleci.adoc[]