---
contentTags:
  platform:
  - Cloud
---
= Free Plan
:page-layout: classic-docs
:page-liquid:
:page-description: This document describes the Free Plan available to developers on CircleCI.
:icons: font
:experimental:
:orbs:

This page describes the CircleCI Free Plan.

[#free-plan]
== Free Plan

The Free Plan offers premium features that allow your team to be productive, efficient, and fast.

The Free Plan includes a set number of credits across a variety of resource classes, per month. You can customize how you use your credits depending on your build configuration and execution environment. A small number of credits are charged per minute. There is no limit on user seats.

The Free Plan offers *5* link:https://support.circleci.com/hc/en-us/articles/360034783154-What-is-an-Active-User[active users].

Below are the features you can use on the Free Plan. Refer to the link:https://circleci.com/pricing/[Pricing] page for more detailed information on credit amounts, included resource classes, key features, and support. Refer to the link:https://circleci.com/product/features/resource-classes/[Resource classes] features page for details on CPU, memory, network and storage, and credit usage for available compute types.

[#available-resource-classes]
=== Available resource classes

A wide array of resource classes on Docker, Arm, Linux, Windows, and macOS are available. To view examples, or find more information about these executors, refer to the xref:executor-intro#[Execution environments overview] page.

{% include snippets/features-of-circleci.adoc %}

=== Releases

Visualise and control your deployments with CircleCI releases. Deployments to Kubernetes and SageMaker are supported.

On the Free Plan, you get **three components**. Each release is **250 credits**.

* A _component_ in CircleCI is a collection of code and configuration that is deployed and released as a single unit.

* A _release_ is the act of updating a component to a new version in a specific environment, causing it to become available to an audience of users and other services. A release can happen when an existing component is updated or when the first version for a new component is deployed.

Start with the xref:release/releases-overview#[Releases overview] for more information on the feature.

[#support]
=== Support

Support is available through the link:https://discuss.circleci.com/[community forums], link:https://support.circleci.com/hc/en-us[support portal], and our link:https://support.circleci.com/hc/en-us/requests/new[global ticket-based system].
