---
contentTags:
  platform:
  - Cloud
---
= Prevent unregistered users from spending credits
:page-layout: classic-docs
:page-liquid:
:page-description: A how to guide to configuring your org so that unregistered users will not be able to perform actions that spend credits
:icons: font
:experimental:

It is possible for _unregistered_ users to trigger pipelines, and therefore, spend credits. Use the **Prevent unregistered user spend** option to only allow registered users the ability to trigger work that consumes credits. For a full breakdown of the various ways pipelines can be triggered, see the xref:triggers-overview[Triggers overview].

[NOTE]
====
An _unregistered_ user is how CircleCI tracks users who have triggered builds but have not signed up for a CircleCI account. Unregistered user activity within an org is mapped to, and counts as, a single link:https://support.circleci.com/hc/en-us/articles/360034783154[active user].

For more information about unregistered users, see this link:https://support.circleci.com/hc/en-us/articles/360037744473-What-is-an-Unregistered-User-[support article]
====

[#prerequisites]
== Prerequisites

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free]
* You must be on the link:https://circleci.com/pricing/[Performance or Scale plan]
* You must be an org admin

[#steps]
== Steps

Follow these steps to prevent unregistered users from triggering work that consumes credits:

. In the CircleCI web app, click btn:[Plan] in the sidebar
. Select the **Usage Controls** tab. If you do not see this option you might be on the Free plan, or you may not be an org admin, in which case this guide does not apply to you.
. Click the switch for the **Prevent unregistered user spend** option to "On"

To disable this feature you can toggle this switch "Off" at any time.

With this option enabled, any unregistered users, that is, users who do not have a CircleCI account, and who are not associated with your org, will see the following if they attempt to trigger a pipeline:

* The pipeline will fail to start
* The `block-unregistered-user` error will be displayed in a banner on the dashboard
