---
contentTags:
  platform:
  - Cloud
  - Server v4+
---
= Publish packages to Packagecloud
:description: How to publish packages to Packagecloud using CircleCI.
:experimental:
:icons: font
:page-layout: classic-docs


In this how-to guide, you will learn how to configure CircleCI to publish packages to Packagecloud.

[#introduction]
== Introduction

link:https://packagecloud.io[Packagecloud] is a hosted package repository service. It allows users to host npm, Java/Maven, Python, apt, yum and RubyGem repositories without any pre-configuration.

[#configure-environment-variables]
== 1. Configure environment variables

Under project settings in CircleCI, create an environment variable with the name `PACKAGECLOUD_TOKEN`, containing the value of a packagecloud API token. This environment variable will be used to authenticate with the packagecloud API directly, or using the packagecloud CLI.

The packagecloud CLI will automatically read this environment variable from the system when interacting with repositories.

[#set-the-packagecloudurl-for-packagecloud-enterprise]
== 2. Set the $PACKAGECLOUD_URL for packagecloud:enterprise

Only set the `$PACKAGECLOUD_URL` if you are a packagecloud:enterprise customer.

NOTE: This setting is only for packagecloud:enterprise customers. Under project settings in CircleCI, set the `$PACKAGECLOUD_URL` environment variable to the URL of the packagecloud:enterprise installation.

[#install-the-packagecloud-cli]
== 3. Install the packagecloud CLI

To use the packagecloud CLI from CircleCI, install it using RubyGems by adding the following `run` step to your `.circleci/config.yml` under the job that is configured to deploy the package:

[,yml]
----
- run:
   name: Install packagecloud CLI
   command: gem install package_cloud
----

The CLI will automatically use the `$PACKAGECLOUD_TOKEN` environment variable to authenticate against the packagecloud service.

[#use-dependency-caching]
== 4. Use dependency caching

If you want to cache this dependency between builds, you can add the `package_cloud` gem to a `Gemfile` and follow CircleCI's guide for xref:caching#[Caching dependencies].

[#push-packages-with-the-packagecloud-cli]
== 5. Push packages with the packagecloud CLI

The build processes for package types will vary, but pushing them into a packagecloud repository is quite simple. To add packages to a repository from your CircleCI builds, add a step in your `deploy` configuration that uses the packagecloud CLI.

The following is a full example `.circleci/config.yml` that will checkout a git repository, run a `make` task (this command can be anything configured to build your package), then deploy the package to a packagecloud repo.

include::../_includes/snippets/docker-auth.adoc[]

[,yaml]
----
version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/ruby:3.1.2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build the package
          command: make
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install packagecloud CLI
          command: gem install package_cloud
      - run:
          name: Push deb package
          command: package_cloud push example-user/example-repo/debian/jessie debs/packagecloud-test_1.1-2_amd64.deb
workflows:
  package-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
----

[#deploy-npm-packages]
== 6. Deploy npm packages

CircleCI users can deploy packages directly to npm registries hosted on Packagecloud.

[#configure-the-test-job]
=== a. Configure the test job

This job will retrieve the project code, install its dependencies and run any tests in the NodeJS project:

[,yaml]
----
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-.
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - persist_to_workspace:
          root: ~/repo
          paths: .
----

[#configure-the-deploy-job]
=== b. Configure the deploy job

The next job configured is the deploy job. This job will authenticate and publish to the packagecloud npm registry:

[,yaml]
----
jobs:
...
  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Set registry URL
          command: npm set registry https://packagecloud.io/example-user/example-repo/npm/

      - run:
          name: Authenticate with registry
          command: echo "//packagecloud.io/example-user/example-repo/npm/:_authToken=$PACKAGECLOUD_TOKEN" > ~/repo/.npmrc

- run:
          name: Publish package
          command: npm publish
----

* _Set registry URL_ : This command sets the registry to URL that will be used by the `npm` CLI.
* _Authenticate with the registry_ : This command will set the `authToken` to be used by the `npm` CLI to the environment variable configured in the project settings.
* _Publish package_ : Publish the package to the configured npm registry on packagecloud.

The packagecloud npm registry URL is in the following format:

[,shell]
----
https://packagecloud.io/:username/:repo_name/npm/
----

The full `.circleci/config.yml` should look something like this:

[,yaml]
----
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:19.0.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-.
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set registry URL
          command: npm set registry https://packagecloud.io/example-user/example-repo/npm/
      - run:
          name: Authenticate with registry
          command: echo "//packagecloud.io/example-user/example-repo/npm/:_authToken=$PACKAGECLOUD_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
----

The workflows section will tie together both the `test` and `deploy` jobs into sequential steps in the build process.

You can read more about publishing npm packages to packagecloud on the CircleCI blog post: link:https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/[Publishing npm Packages Using CircleCI]

[#use-the-packagecloud-api]
== Use the Packagecloud API

Packagecloud also provides a robust API to manage package repositories. You can read more about the link:https://packagecloud.io/docs/api[Packagecloud API] and how to upload, delete, and promote packages across repositories.

[#see-also]
== See also

* xref:artifacts#[Storing and accessing artifacts]
