---
contentTags:
  platform:
  - Cloud
---
= Rename organizations and repositories
:page-layout: classic-docs
:page-liquid:
:page-description: This how-to guide goes over changing the names of organizations and repositories.
:icons: font
:experimental:

NOTE: The content on this page is only relevant to GitHub and Bitbucket. Due to the standalone nature of GitLab accounts in CircleCI, no changes are required when orgs or repos are renamed.

If you need to rename a **GitHub** or **Bitbucket** organization or repository that you have previously connected to CircleCI, best practice is to follow the steps listed below. If you do not follow this process, it is possible you may lose access to your organization or repository settings, including **environment variables** and **contexts**.

[#rename-organizations-and-repositories]
== Steps to rename organizations and repositories

1. Rename organization or repository in your VCS
2. Go to the CircleCI web app using the new org/repo name, for example: `app.circleci.com/pipelines/<VCS>/<new-org-name>/<project-name>`
3. Confirm that your plan, projects, and settings have been transferred successfully
4. If desired, you are now free to create a new org/repo with the previously-used name in your VCS

[#see-also]
== See also

* xref:contexts.adoc[Contexts]
* xref:env-vars.adoc[Environment variables]