---
contentTags:
  platform:
  - Cloud
---
= Roles and permissions
:page-layout: classic-docs
:page-liquid:
:page-description: An overview of the various project and orgnization roles in CircleCI and the permissions associated with each role.
:icons: font
:experimental:

NOTE: If you authenticated your CircleCI account with xref:gitlab-integration#[GitLab] or the CircleCI xref:github-apps-integration#[GitHub App], the content on this page applies to you.

Manage user access to organizations and projects with CircleCI roles and associated permissions. By default, users can access projects based on roles set at an organization level. For more granular control, you can assign roles at the project level.

[#quickstart]
== Quickstart

For instructions on managing roles and permissions, see the xref:manage-roles-and-permissions#[Manage roles and permissions] page.

[#organization-role-permissions-matrix]
== Organization role permissions matrix

The table below shows the permissions associated with each CircleCI organization role:

[.table.table-striped]
[cols=4*, options="header"]
|===
| ACTIONS

3+^| ORGANIZATION ROLES

|
| *Admin*
| *Contributor*
| *Viewer*

| *Organization*
|
|
|

^| Create namespace
^| icon:check-circle[]
^|
^|

^| Manage namespace
^| icon:check-circle[]
^|
^|

^| View org settings
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage org settings
^| icon:check-circle[]
^|
^|

^| View org access
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage org access
^| icon:check-circle[]
^|
^|

^| View org credentials
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| View org policies
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage org policies
^| icon:check-circle[]
^|
^|

^| View org connections
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage org connections
^| icon:check-circle[]
^|
^|

^| View org releases
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage org credentials
^| icon:check-circle[]
^|
^|

^| View org audit logs
^| icon:check-circle[]
^|
^|

^| View plan
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage plan
^| icon:check-circle[]
^|
^|

| *Insights*
|
|
|

^| View org insights
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

| *Runner*
|
|
|

^| View runners
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage runners
^| icon:check-circle[]
^|
^|

| *Projects*
|
|
|

^| View projects
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Create projects
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage project settings
^| icon:check-circle[]
^|
^|

| *Contexts*
|
|
|

^| View contexts
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Use contexts
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Edit context variables
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage contexts
^| icon:check-circle[]
^|
^|

| *Orbs*
|
|
|

^| Create/update orb
^| icon:check-circle[]
^|
^|

^| View private orb
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Publish dev orb
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Publish orb
^| icon:check-circle[]
^|
^|

| *Webhooks*
|
|
|

^| View org webhooks
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage org webhooks
^| icon:check-circle[]
^|
^|

^| View project webhooks
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Manage project webhooks
^| icon:check-circle[]
^|
^|

| *Schedule*
|
|
|

^| View schedule
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Edit schedule
^| icon:check-circle[]
^|
^|

| *Triggers*
|
|
|

^| View triggers
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Trigger build
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Edit triggers
^| icon:check-circle[]
^|
^|

| *Config sources*
|
|
|

^| View config sources
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Edit config sources
^| icon:check-circle[]
^|
^|

|===


[#project-role-permissions-matrix]
=== Project role permissions matrix

The table below shows the permissions associated with each CircleCI project role:

[.table.table-striped]
[cols=4*, options="header"]
|===
| ACTIONS

3+^| PROJECT ROLES

|
| *Admin*
| *Contributor*
| *Viewer*

| *Projects*
|
|
|

^| View projects
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| View project access
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| View project credentials
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage project
^| icon:check-circle[]
^|
^|

| *Webhooks*
|
|
|

^| View project webhooks
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Manage project webhooks
^| icon:check-circle[]
^|
^|

| *Schedule*
|
|
|

^| View schedule
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Edit schedule
^| icon:check-circle[]
^|
^|

| *Triggers*
|
|
|

^| View triggers
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Trigger build
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Edit triggers
^| icon:check-circle[]
^|
^|

| *Contexts*
|
|
|

^| View contexts
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Use contexts
^| icon:check-circle[]
^| icon:check-circle[]
^|

^| Edit context variables
^|
^|
^|

^| Manage contexts
^|
^|
^|

| *Config sources*
|
|
|

^| View config sources
^| icon:check-circle[]
^| icon:check-circle[]
^| icon:check-circle[]

^| Edit config sources
^| icon:check-circle[]
^|
^|

|===

[#permissions-scope]
== Permissions scope

Your CircleCI roles and associated permissions are **not** derived from the permissions set in your version control system (VCS). Your CircleCI role permissions do **not** allow you to bypass permissions in the VCS.

For example, you may be an _Organization Administrator_ within CircleCI, which gives you access to view and modify organization and project settings _within your CircleCI organization_. However, you will not be able to edit a project’s `.circleci/config.yml` hosted in your VCS without your user also having the write permissions _within that VCS's repository project_. Your CircleCI user’s VCS permissions are determined by its associated VCS identity.

[#next-steps]
== Next steps

* xref:manage-roles-and-permissions#[Manage roles and permissions]