---
contentTags: 
  platform:
  - Server v4.x
  - Server v3.x
---
= Upgrading the CircleCI's self-hosted runner on server
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:


This page describes how to update the CircleCI's **machine runner** on CircleCI server installations.

toc::[]

[#self-hosted-runner-for-server-compatibility]
== Machine runner on server compatibility

Refer to the xref:runner-installation.adoc#runner-for-server-compatibility[server compatibility chart] to find the runner version you need for your installation.

[#upgrading-self-hosted-runner-on-server]
== Upgrading machine runner on server

Unlike CircleCI cloud, server does not automatically update the `circleci-launch-agent`, and requires manual intervention. The following sections detail how to upgrade machine runners in your server installation across all environments.

[#upgrading-self-hosted-runner-in-a-containerized-environment]
=== Upgrading machine runner in a containerized environment

This section details how to upgrade self-hosted runner in containerized environments: Kubernetes and Docker.

[#upgrading-self-hosted-runner-for-kubernetes]
==== Upgrading machine runner for Kubernetes

Refer to the xref:runner-on-kubernetes.adoc[Kubernetes Installation Instructions].

[#upgrading-self-hosted-runner-for-docker]
==== Upgrading machine runner in Docker

. Stop any currently running self-hosted runner containers:
+
```shell
docker stop <container-name>
```
. Remove the self-hosted runner containers:
+
```shell
docker stop <container-name>; docker rm <container-name>;
```
. Start a new machine runner Docker container:
+
```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> docker run --env agent_version --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```
+
NOTE: When starting the docker container on server, the `agent_version` environment variable will need to be passed in using the `--env` flag.

[#upgrading-self-hosted-runner-in-a-non-containerized-environment]
=== Upgrading machine runner in a non-containerized environment

The process for manually updating the `circleci-launch-agent` binary can be broken down into three steps for non containerized environments. These steps are expanded upon in the sections below.

. Replace existing `circleci-launch-agent` binary with the new version.
. Stop currently running `circleci-launch-agent` processes.
. Start the new version of the `circleci-launch-agent` binary.

[#replace-the-circleci-launch-agent-binary-with-the-new-version]
==== 1. Replace the `circleci-launch-agent-binary` with the new version

Following the same process as in the xref:runner-installation-cli.adoc#continued-for-linux-macos-and-server[Download the launch-agent binary] instructions, update the `agent_version` environment variable to the correct version from the xref:runner-installation-cli.adoc#self-hosted-runners-for-server-compatibility[Self-hosted runners for server compatibility chart].

```shell
export agent_version="<launch-agent-version>"
```

Then, following the xref:runner-installation.adoc#platform-specific-instructions[platform specific installation instructions], replace the old binary with the newly updated version that was just downloaded.

[#stop-the-currently-running-machine-runner]
==== 2. Stop the currently running machine runner

The currently running `circleci-launch-agent` process will need to be halted before starting the newly updated binary. Platform-specific instructions for this are given below.

[#stopping-the-machine-runner-on-linux]
===== Stopping the machine runner on Linux

Run the following commands:

```shell
sudo systemctl stop circleci.service
sudo systemctl disable circleci.service
```

[#stopping-the-machine-runner-on-mac]
===== Stopping the machine runner on Mac

Run the following commands:

```shell
sudo launchctl unload '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#stopping-the-machine-runner-on-windows]
===== Stopping the machine runner on Windows

Run the following command:

``` powershell
Stop-ScheduledTask -TaskName "CircleCI Launch Agent"
```

[#start-the-new-machine-runner]
==== 3. Start the new machine runner

Platform-specific instructions are given below.

[#starting-on-linux]
===== Starting on Linux

Run the following commands:

```shell
sudo systemctl reload circleci.service
sudo systemctl enable circleci.service
sudo systemctl start circleci.service
```

[#starting-on-mac]
===== Starting on Mac

Run the following command:

```shell
sudo launchctl load '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#starting-on-windows]
===== Starting on Windows

Run the following commands:

``` powershell
Start-ScheduledTask -TaskName "CircleCI Launch Agent"
```

[#additional-resources]
=== Additional resources
- xref:runner-installation.adoc[Installing the CircleCI Runner]
- xref:runner-on-kubernetes.adoc[Kubernetes Installation Instructions]


