---
version:
- Cloud
- Server v4.x
- Server v3.x
---
= CircleCI's machine runner installation with Docker
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This page describes how to install CircleCI self-hosted runner with Docker using a Machine execution environment.

NOTE: CircleCI has a more scalable, container-friendly <<container-runner#,container runner>> in open preview.  It is a more intuitive way to run arbitrary containers for your self-hosted CI jobs.

This page describes how to install CircleCI's machine runner with the Docker executor. If you are looking to set up self-hosted runners in a private Kubernetes cluster, please visit the <<container-runner#,Container runner>> page.

{% include snippets/runner-platform-prerequisites.adoc %}

[#additional-prerequisites]
== Additional prerequisites

The host needs to have Docker installed. Once the `runner` container is started, the container will immediately attempt to start running jobs. The container will be reused to run more jobs indefinitely until it is stopped.

The number of containers running in parallel on the host is constrained by the host's available resources and your jobs' performance requirements.

[#create-a-dockerfile-that-extends-the-circleci-self-hosted-runner-image]
== Create a Dockerfile that extends the CircleCI's self-hosted runner image

Create a `Dockerfile.runner.extended` file. In this example, Python 3 is installed on top of the base image.

```dockerfile
FROM circleci/runner:launch-agent
RUN sudo apt-get update; \
    sudo apt-get install --no-install-recommends -y \
        python3
```

[#build-the-docker-image]
== Build the Docker image

```shell
docker build --file ./Dockerfile.runner.extended .
```

[#start-the-docker-container]
== Start the Docker container

NOTE: The environment variable values are not available to the `docker` command, so these environment variables are not visible in `ps` output.

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> docker run --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

When the container starts, it will immediately attempt to start running jobs.

[#start-the-docker-container-on-server]
=== Start the Docker container on server

When starting the docker container on server, the `agent_version` and `LAUNCH_AGENT_API_URL` environment variables will need to be passed in using the `--env` flag.

```shell
CIRCLECI_RESOURCE_CLASS=<resource-class> CIRCLECI_API_TOKEN=<runner-token> agent_version=<agent_version_for_server> LAUNCH_AGENT_API_URL=<server_host_name> docker run --env agent_version --env LAUNCH_AGENT_API_URL --env CIRCLECI_API_TOKEN --env CIRCLECI_RESOURCE_CLASS --name <container-name> <image-id-from-previous-step>
```

[#stopping-the-docker-container]
== Stopping the Docker container

```shell
docker stop <container-name>
```

[#remove-the-docker-container]
== Remove the Docker container

In some cases you might need to fully remove a stopped self-hosted runner container from the system, such as when recreating a container using the same name.

```shell
docker stop <container-name>; docker rm <container-name>;
```
