---
contentTags: 
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Installing Self-Hosted Runners with the CLI
:page-layout: classic-docs
:page-liquid:
:page-description: Find resources to install CircleCI's self-hosted runners on Linux, macOS, Windows and Docker platforms.
:icons: font
:toc: macro
:toc-title:

This page describes how to install **machine self-hosted runners** through the CLI. If you are interested in container runner on Kubernetes, please see the <<container-runner#,Container runner>> page.

NOTE: Installing self-hosted runners is available directly in the https://app.circleci.com/[CircleCI web app] for Linux, macOS, Docker, and Windows. You will need to agree to the <<#self-hosted-runner-terms-agreement,Runner Terms>> before this option is available to you in the UI.

[#prerequisites]
== Prerequisites

To install and run jobs, you will need to have root access, and have the following utilities and tools installed on your system:

* <<local-cli#,CircleCI CLI>>. If you are installing **runner for server**, the CircleCI CLI needs to be configured using a server API key. Run `circleci setup` to configure the CLI and access the option to supply a new API token if required.
* https://www.gnu.org/software/coreutils/[coreutils] (Linux only)
* https://curl.se/[curl] (installed by default on macOS)
* sha256sum (if not pre-installed):
  - `brew install coreutils` for macOS (requires https://brew.sh/[Homebrew])
  - `sudo apt install coreutils` for Ubuntu/Debain
  - `sudo yum install coreutils` for Red Hat
* https://www.gnu.org/software/tar/[tar]
* https://www.gnu.org/software/gzip/[gzip]
* sepolicy (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] only)
* rpmbuild (https://www.redhat.com/en/enterprise-linux-8/details[RHEL 8] only)

[self-hosted-runner-terms-agreement]
== Self-hosted runner Terms Agreement

If you are installing and using self-hosted runners through the CLI, you are agreeing to the https://circleci.com/legal/runner-terms/[CircleCI Runner Terms].

[#command-line-installation]
== Command line installation

NOTE: If you are installing **self-hosted runners for server**, the CircleCI CLI needs to be configured using your server API key. Run `circleci setup` to configure the CLI and access the option to supply a new API token if required.

In order to install self-hosted runners, you will need to create a namespace and authentication token by performing the steps listed below. Please note that to create resource classes and tokens you need to be an organization administrator in the VCS provider.

You can view your runners on the inventory page, by clicking *Self-Hosted Runners* on the left navigation.

. Create a namespace for your organization's self-hosted runners. Please note, CircleCI will autogenerate a namespace based on your organization's name. Verify this is the namespace you want to use. *Each organization can only create a single namespace*. We suggest using a lowercase representation of your CircleCI organization's account name. If you already use orbs, this namespace should be the same namespace orbs use.
+
If you receive an error creating a namespace, check to see if you have an existing one, and move on to step 2 below, using your existing namespace.
+
It is recommended to use the following command to create a namespace:
+
```
circleci namespace create <name> --org-id <your-organization-id>
```
+

. Create a resource class for your self-hosted runner's namespace using the following command:
+
```
circleci runner resource-class create <namespace>/<resource-class> <description> --generate-token
```
+
*Your namespace is required in the command to create your resource class.*
Example: `circleci runner resource-class create my-namespace/my-resource-class my-description --generate-token`.
+

CAUTION: The token cannot be retrieved again, so be sure to store it safely.

*If you are using Linux, macOS, or Server, continue with the directions below.* Otherwise, skip to the <<#platform-specific-instructions, Platform-specific installation>> instructions.

[#continued-for-linux-macos-and-server]
=== Continued for Linux, macOS, and Server

Be sure to complete the steps in the <<#command-line-installation, Command line installation>> section before moving on to the steps below.

. Save the script below as `download-launch-agent.sh` in the root of your project. When run (see the next step) the script will download the launch-agent binary, verify the checksum, and set the `circleci-launch-agent` version. 
+
Self-hosted runners on cloud auto-update to the latest supported versions. For server, specific self-hosted runner versions are validated for interoperability, and self-hosted runners do not auto-update.
+
```shell
#!/usr/bin/env sh

set -eu pipefail

echo "Installing CircleCI Runner for ${platform}"

base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
if [ -z ${agent_version+x} ]; then
  agent_version=$(curl "${base_url}/release.txt")
fi

# Set up runner directory
echo "Setting up CircleCI Runner directory"
prefix=/var/opt/circleci
sudo mkdir -p "${prefix}/workdir"

# Downloading launch-agent (machine runner)
echo "Using CircleCI Launch Agent version ${agent_version}"
echo "Downloading and verifying CircleCI Launch Agent Binary"
curl -sSL "${base_url}/${agent_version}/checksums.txt" -o checksums.txt
file="$(grep -F "${platform}" checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')"
mkdir -p "${platform}"
echo "Downloading CircleCI Launch Agent: ${file}"
curl --compressed -L "${base_url}/${agent_version}/${file}" -o "${file}"

# Verifying download
echo "Verifying CircleCI Launch Agent download"
grep "${file}" checksums.txt | sha256sum --check && chmod +x "${file}"
sudo cp "${file}" "${prefix}/circleci-launch-agent" || echo "Invalid checksum for CircleCI Launch Agent, please try download again"
```
+
. Set your platform and run the `download-launch-agent.sh` script to download, verify, and install the binary. If you are using **cloud**, use the table below to find your platform variable:
+
[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Installation Target
| Variable

| For Linux x86_64
| `platform=linux/amd64`

| For Linux ARM64
| `platform=linux/arm64`

| For macOS x86_64
| `platform=darwin/amd64`

| For macOS M1
| `platform=darwin/arm64`
|===
+
For example, on **cloud**, to set your platform for macOS M1 and run the `download-launch-agent.sh` script, run the following:
+
```shell
export platform=darwin/arm64 && sh ./download-launch-agent.sh
```
+
For *server v3.1.0 and up*, use the table below to find the compatible machine runner launch-agent version for the version of server you are running:
+
[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Server version
| Launch agent version

| 3.0
| Runner not supported

| 3.1
| 1.0.11147-881b608

| 3.2
| 1.0.19813-e9e1cd9

| 3.3
| 1.0.29477-605777e

| 3.4
| 1.0.33818-051c2fc
|===
+
Substitute `<launch-agent-version>` with your launch-agent version for server and run the following:
+
```shell
export agent_version="<launch-agent-version>" && sh ./download-launch-agent.sh
```
+
**Note:** Once your runner is successfully set up, you can delete the `download-launch-agent.sh` file.
+ 
. Continue with the platform-specific instructions in the next section.

[#platform-specific-instructions]
=== Platform-specific instructions

Please continue with the platform-specific installation instructions below. This should be done only after you have created your namespace and resource class, and run the `download-launch-agent.sh` script from the previous section.

* xref:runner-installation-linux.adoc[Linux]
* xref:runner-installation-mac.adoc[macOS]
* xref:runner-installation-windows.adoc[Windows]
* xref:runner-installation-docker.adoc[Docker]
* xref:container-runner.adoc[Container runner] (currently in open preview)

For platform compatibility specifics, see the <<runner-overview#available-self-hosted-runner-platforms,Runner overview>> page for more information.

[#referencing-your-self-hosted-runner-on-a-job]
== Referencing your self-hosted runner on a job

After setting up your self-hosted runner, you will need to reference it on a job by setting some fields in your `.circleci/config.yml` file. The fields you must set for a specific job to run using your self-hosted runners are:

{% include snippets/runner-config-reference.adoc %}

[#self-hosted-runners-for-server-compatibility]
== Self-hosted runners for server compatibility
_CircleCI runner is available from server v3.1.0_

Each minor version of server is compatible with a specific version of `circleci-launch-agent`. The table below lists which version of `circleci-launch-agent` to use when installing self-hosted runners, depending on your version of server.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Server version
| Launch agent version

| 3.0
| Runner not supported

| 3.1
| 1.0.11147-881b608

| 3.2
| 1.0.19813-e9e1cd9

| 3.3
| 1.0.29477-605777e

| 3.4
| 1.0.33818-051c2fc

| 4.0
| 1.0.33818-051c2fc
|===

[#additional-resources]
== Additional Resources 

- https://hub.docker.com/r/circleci/runner[CircleCI Runner Image on Docker Hub]
- https://github.com/CircleCI-Public/circleci-runner-docker[CircleCI Runner Image on Github]
- https://circleci.com/docs/[CircleCI Docs - The official CircleCI Documentation website]
- https://docs.docker.com/[Docker Docs]
