---
contentTags:
  platform:
  - Cloud
---
= Upgrading the CircleCI machine runner on cloud
:page-layout: classic-docs
:page-liquid:
:page-description: How to manually upgrade the CircleCI machine runner on Linux, Windows, or macOS.
:icons: font
:toc: macro:
:toc-tittle:

This page describes how to update the CircleCI **machine runner** on CircleCI cloud.

toc::[]

[#check-current-version]
== Checking current machine runner version

The machine runner version can be checked by using the `--version` flag with the  binary. The default installation directory for the CircleCI machine runner binary is `/opt/circleci/circleci-launch-agent` on Linux as well as macOS, and `C:\Program Files\CircleCI\circleci-launch-agent.exe` on Windows.

[#enable-auto-update]
== Enabling auto update

The most straightforward way to upgrade an existing CircleCI machine runner is to enable auto update in the configuration file and restart the runner instance. Auto update can be enabled by removing the `disable_auto_update` option from the machine runner configuration file, or by setting `runner.disable_auto_update` to false, then restarting machine runner instance either manually or by the process management used to manage the CircleCI machine runner agent. More details on configuring machine runner can be found in the xref:runner-config-reference[runner configuration reference] documentation.

In some cases an environment variable may have been used to disable the auto update functionality. If the machine runner installation is not updated after enabling the auto update functionality in the configuration file, the environment variable `LAUNCH_AGENT_RUNNER_DISABLE_AUTO_UPDATE` should be set to have a value of `false`, or unset entirely, and the machine runner instance restarted again. 

=== Linux 
```shell
sudo systemctl restart circleci.service
```

=== macOS
```shell
sudo launchctl stop '/Library/LaunchDaemons/com.circleci.runner.plist'
sudo launchctl start '/Library/LaunchDaemons/com.circleci.runner.plist'
```

=== Windows
```shell
Stop-ScheduledTask -TaskName "CircleCI Launch Agent"
Start ScheduledTask -TaskName "CircleCI Launch Agent"
```

[#manually-download-updated-binary]
== Manually download the updated machine runner binary

For machine runners where auto update is unable to be used, the machine runner binary, also sometimes known as the launch-agent binary,  can be manually downloaded and used to replace the existing version.

[#manually-download-mac-or-linux-binary]
=== Manually downloading the Linux or macOS machine runner agent

As with the xref:runner-installation-linux.adoc[Linux] and xref:runner-installation-mac.adoc[macOS] installation process, the environment variable `platform` will need to be set to an appropriate value for the target installation system. 

```shell
# for Linux x86_64
export platform=linux/amd64
```
```shell
# for Linux ARM64
export platform=linux/arm64
```
```shell
# for Linux s390x
export platform=linux/s390x
```
```shell
# for Linux ppc64le
export platform=linux/ppc64le
```
```shell
# for macOS ARM64 (M1+ chips)
export platform=darwin/arm64
```
```shell
# for macOS x86_64
export platform=darwin/amd64
```

```shell
# Download the new version of the CircleCI Agent manually on macOS, and Linux with bash

base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
agent_version=$(curl "${base_url}/release.txt")
curl -sSL "${base_url}/${agent_version}/checksums.txt" -o checksums.txt
mkdir -p "${platform}"
file="$(grep -F "${platform}" checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')"
curl --compressed -L "${base_url}/${agent_version}/${file}" -o "${file}"
grep "${file}" checksums.txt | sha256sum --check || echo "Failed to download the CircleCI machine runner binary, please try again"
chmod +x $file
```

[#manually-download-windows-binary]
=== Manually downloading the windows machine runner

```shell
# Download the new version of the CircleCI Agent manually on Windows with PowerShell
$Env:platform = "windows/amd64"
mkdir $Env:platform
$Env:baseURL =  "https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
$Env:agentVersion = $(curl "$Env:baseURL/release.txt")
$Env:agentVersion = "$Env:agentVersion".Trim()
curl "$Env:baseURL/$Env:agentVersion/checksums.txt" -o checksums.txt
$Env:fileName = $(Select-String $Env:platform checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')
$Env:fileName = $Env:fileName.Trim()
curl "$Env:baseURL/$Env:agentVersion/$Env:fileName" -o $Env:fileName
$Env:fileHash = $(Get-FileHash $Env:fileName -Algorithm "SHA256" | select -expand "Hash")
$Env:expectedHash = "$(grep $Env:filename checksums.txt)".Split(" ")[0]
if ($Env:expectedHash -ne $Env:fileHash) { Write-Output "CircleCI machine runner binary download failed, please try again"}else{Write-Output "CircleCI machine runner binary successfully downloaded to $CWD/$Env:fileName"}
```

== Manually replacing the machine runner binary
Once the new binary has been successfully downloaded, the machine runner instance will need to be stopped, have the currently installed binary overwritten with the newly downloaded binary, and then be started again.

[#manually-replace-linux-binary]
=== Linux 
```shell
sudo systemctl stop circleci.service
# Replace the current binary with the newly downloaded binary, by default the machine runner binary is installed to `/opt/circleci/circleci-launch-agent`
sudo systemctl start circleci.service
```

[#manually-replace=macos-binary]
=== macOS
```shell
sudo launchctl stop '/Library/LaunchDaemons/com.circleci.runner.plist'
# Replace the current binary with the newly downloaded binary, by default the machine runner binary is installed to `/opt/circleci/circleci-launch-agent`
sudo launchctl start '/Library/LaunchDaemons/com.circleci.runner.plist'
```

[#manually-replace-windows-binary]
=== Windows
```shell
Stop-ScheduledTask -TaskName "CircleCI Launch Agent"
# Replace the current binary with the newly downloaded binary, this will require renaming or deleting the existing binary
Start-ScheduledTask -TaskName "CircleCI Launch Agent"
```

If process management is not being used to manage the machine runner, the process will need to be manually stopped using `kill -9` on macOS and Linux systems, or the Task Manager on Windows systems, and then manually restarted.  
