---
version:
- Cloud
- Server v3.x
---
= Installing the CircleCI Runner
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

NOTE: CircleCI runner is available on the https://circleci.com/pricing[Scale
plan] and with https://circleci.com/pricing/server/[server]. Please reach out
to your sales representative (or https://circleci.com/contact-us/?cloud[contact
us]) for information on how to sign up for the Scale plan or server.

// This page describes how to install CircleCI runner on Linux, macOS, Docker, and Windows platforms. For other platforms, see xref:runner-overview.adoc#available-circleci-runner-platforms[Available CircleCI runner platforms] for more information.

toc::[]

== Prerequisites

The installation process assumes you have installed the following utilities on your system:

* <<local-cli#installation,CircleCI CLI>>
* curl (installed by default on macOS)
* sha256sum (installed as part of coreutils on Linux apt/yum, macOS via brew)
* systemd version 235+ (Linux only)
* sepolicy (RHEL 8 only)
* rpmbuild (RHEL 8 only)
* permissions to create a user, and create directories under /opt.

Running jobs requires you have the following tools available on your machine:

* tar
* gzip
* coreutils (Linux only)
* git (recommended, but not required)

== Authentication

NOTE: These commands can only be run by an owner/admin of your organization.

In order to complete this process you will need to create a namespace and authentication token by performing the steps listed below:

. Create a namespace for your organization's runner resources.
+
NOTE: Each organization can only create a single namespace. If you already use orbs, this namespace will be the same namespace as the orbs use. 
+ 
Use the following command: 
+
```
circleci namespace create <name> <vcs-type> <org-name>
```
+
For example, if your GitHub URL is `https://github.com/circleci`, then use: `circleci namespace create my-namespace github circleci`.
. Create a resource class for your runner for your namespace using the following command:
+ 
```
circleci runner resource-class create <resource-class> <description> --generate-token
``` 
+
For example, `circleci runner resource-class create my-namespace/my-resource-class my-description --generate-token`.
+
NOTE: To create resource classes and tokens you need to be an organization administrator in the VCS provider.
+
CAUTION: The default token cannot be retrieved again, so be sure to store it safely.

== Installation

=== Download the launch agent binary and verify the checksum
[[download]]
The launch agent can be installed using the following script, which will use `opt/circleci` as the base install location.

First, set one of these variables as appropriate for for your installation target.

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Installation Target
| Variable

| For Linux x86_64
| `platform=linux/amd64`

| For Linux ARM64
| `platform=linux/arm64`

| For macOS x86_64
| `platform=darwin/amd64`

| For macOS M1
| `platform=darwin/arm64`
|===

Next, set the `circleci-launch-agent` version. Runners on cloud auto-update to the latest supported versions. For server, specific runner versions are validated for interoperability and runners do not auto-update. A table of server `circleci-launch-agent` versions can be found <<runner-for-server-compatibility,here>>.

For cloud, you can run the following:
```bash
export base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
export agent_version=$(curl "${base_url}/release.txt")
```

For server v3.1.0 and up, run the following, substituting `<launch-agent-version>` with the correct launch agent version for the version of server you are running (see <<runner-for-server-compatibility>> to find the correct version):
```bash
export agent_version="<launch-agent-version>"
```

Finally, run the following script to download, verify and install the binary.
```bash
# Set up runner directory
prefix=/opt/circleci
sudo mkdir -p "$prefix/workdir"

# Downloading launch agent
echo "Using CircleCI Launch Agent version $agent_version"
echo "Downloading and verifying CircleCI Launch Agent Binary"
base_url="https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent"
curl -sSL "$base_url/$agent_version/checksums.txt" -o checksums.txt
file="$(grep -F "$platform" checksums.txt | cut -d ' ' -f 2 | sed 's/^.//')"
mkdir -p "$platform"
echo "Downloading CircleCI Launch Agent: $file"
curl --compressed -L "$base_url/$agent_version/$file" -o "$file"

# Verifying download
echo "Verifying CircleCI Launch Agent download"
grep "$file" checksums.txt | sha256sum --check && chmod +x "$file"; sudo cp "$file" "$prefix/circleci-launch-agent" || echo "Invalid checksum for CircleCI Launch Agent, please try download again"
```

=== Platform-specific instructions

Please refer to the platform-specific installation instructions:

* https://circleci.com/docs/2.0/runner-installation-linux[Linux]
* https://circleci.com/docs/2.0/runner-installation-macos[macOS]
* https://circleci.com/docs/2.0/runner-installation-windows[Windows]
* https://circleci.com/docs/2.0/runner-installation-docker[Docker]
* https://circleci.com/docs/2.0/runner-on-kubernetes/[Kubernetes]

== Configuration reference

A YAML file is used to configure the launch agent, how it communicates with our servers and how it will launch the task agent.

The configuration file uses the following format with the various parameters explained in more detail below:

```sh
api:
  auth_token: AUTH_TOKEN
runner:
  name: RUNNER_NAME
```

NOTE: The launch agent can also be configured via environment variables. These will be prioritized over the YAML file, if set.

=== runner.name
`$LAUNCH_AGENT_RUNNER_NAME`

`RUNNER_NAME` is a unique name assigned to this particular running launch agent. CircleCI recommends using the hostname of the machine so that it can be used to identify the agent when viewing statuses and job results in the CircleCI UI.

=== api.auth_token
`$LAUNCH_AGENT_API_AUTH_TOKEN`

This is a token used to identify the launch agent to CircleCI and can be generated by the CircleCI CLI. An existing token may be shared among many installations, but this token only allows a particular `resource_class` to be specified.

=== runner.command_prefix
`$LAUNCH_AGENT_RUNNER_COMMAND_PREFIX`

This prefix enables you to customize how the task agent process is launched. Using a custom script here can allow you to execute arbitrary commands before and after the task runner. You should take care to ensure the supplied arguments are executed, and the correct exit code is returned from the script upon completion.

=== runner.working_directory
`$LAUNCH_AGENT_RUNNER_WORK_DIR`

This directory allows you to control the default working directory used by each job. If the directory already exists, task agent will need permissions to write to the directory. If the directory does not exist, then the task agent will need permissions to create the directory. If `%s` is present in the value, this value will be replaced with a different value for each job. Note that these directories will not be automatically removed.

=== runner.cleanup_working_directory
`$LAUNCH_AGENT_RUNNER_CLEANUP_WORK_DIR`

This directory enables you to control the working directory cleanup after each job. The default value is `false`.

=== runner.mode
`$LAUNCH_AGENT_RUNNER_MODE`

This parameter allows you to specify whether you want to terminate this runner instance upon completion of a job (single-task) or to continuously poll for new available jobs.

The possible values are:

* continuous
* single-task

NOTE: The default value is continuous.

=== runner.max_run_time
`$LAUNCH_AGENT_RUNNER_MAX_RUN_TIME`

This value can be used to override the default maximum duration the task agent will run each job. Note that the value is a string with the following unit identifiers `h`, `m` or `s` for hour minute and seconds respectively:

Here are a few valid examples:

* `72h` - 3 days
* `1h30m` - 1 hour 30 minutes
* `30s` - 30 seconds
* `50m` - 50 minutes
* `1h30m20s` - An overly specific (yet still valid) duration.

NOTE: The default value is 5 hours.

==== Customizing job timeouts and drain timeouts

If you would like to customize the job timeout setting, you can "drain" the job by sending the Launch Agent a termination (TERM) signal, which then causes the Launch Agent to attempt to gracefully shutdown. When this TERM signal is received, the launch agent enters 'draining' mode, preventing the Launch Agent from accepting any new jobs, but still allowing any current active job to be completed. At the end of "draining," the Launch Agent then signals the Task Agent to cancel any active job (by sending it a TERM signal).

NOTE: If the Task Agent does not exit a brief period after the TERM, the Launch Agent will manually kill it by sending it a KILL signal.

Draining can end in one of two ways:

* The task has been in the draining state for longer than the configured `max_run_time`.
* An additional TERM signal is received by the Launch Agent during "draining".

=== runner.idle_timeout
`$LAUNCH_AGENT_RUNNER_IDLE_TIMEOUT`

This timeout will enable a launch agent to terminate if no task has been claimed within the given time period. The value is a string with the following unit identifiers: `h`, `m` or `s` for hours, minutes and seconds, respectively (e.g., `5m` is 5 minutes).

NOTE: The default behaviour is to never time out due to inactivity.

=== runner.ssh.advertise_addr
`$LAUNCH_AGENT_RUNNER_SSH_ADVERTISE_ADDR`

This parameter enables the 'Rerun job with SSH' feature. Before enabling this feature, there are xref:runner-installation.adoc#considerations-before-enabling-ssh-debugging[*important considerations that should be made*].

The address is of the form `*host:port*` and is displayed in the 'Enable SSH' and 'Wait for SSH' sections for a job that is rerun.

NOTE: While the presence of the `runner.ssh.advertise_addr` variable enables the 'Rerun job with SSH' feature, the value it holds is for publishing purposes only in the web UI. The address does not need to match the actual host and port of the machine that the runner is installed on and can be a proxy configuration.

==== Considerations before enabling SSH debugging

Task agent runs an embedded SSH server and agent on a dedicated port when the 'Rerun job with SSH' option is activated. This feature will not affect any other SSH servers or agents on the system that the runner is installed on.

* The host port used by the SSH server is currently fixed to `*54782*`. Ensure this port is unblocked and available for SSH connections. A port conflict can occur if multiple launch agents are installed on the same host.
* The SSH server will inherit the same user privileges and associated access authorizations as task agent as defined by the xref:runner-installation.adoc#runner-command_prefix[runner.command_prefix parameter].
* The SSH server is configured for public key authentication. Anyone with permission to initiate a job can rerun it with SSH, but only the user who initiated the rerun will have their SSH public keys added to the server for the duration of the SSH session.
* Rerunning a job with SSH will hold the job open for *two hours* if a connection is made to the SSH server, or *ten minutes* if no connection is made, unless cancelled. While in this state, the job is counted against an organization’s concurrency limit, and the task agent will be unavailable to handle other jobs. Therefore, it is recommended to cancel an SSH rerun job explicitly (through the web UI or CLI) when finished debugging.

== Runner for Server Compatibility
_CircleCI Runner is available from server v3.1.0_

Each minor version of server is compatible with a specific version of
`circleci-launch-agent`. The table below lists which version of `circleci-launch-agent` to use when installing runner,
depending on your version of server:

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
| Server version  
| Launch Agent Version

| 3.0             
| Runner not supported

| 3.1            
| 1.0.11147-881b608
|===

== Additional Resources

- https://github.com/CircleCI-Public/runner-preview-docs/[CircleCI Runner Image on Docker Hub]
- https://github.com/CircleCI-Public/circleci-runner-docker[CircleCI Runner Image on Github]
- https://circleci.com/docs/[CircleCI Docs - The official CircleCI Documentation website]
- https://docs.docker.com/[Docker Docs]
