---
version:
- Cloud
- Server v3.x
---
= Runner Configuration reference
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

toc::[]

== Runner configuration reference

A YAML file is used to configure the launch agent, how it communicates with our servers and how it will launch the task agent.

The configuration file uses the following format with the various parameters explained in more detail below:

```sh
api:
  auth_token: AUTH_TOKEN
runner:
  name: RUNNER_NAME
```

NOTE: The launch agent can also be configured via environment variables. These will be prioritized over the YAML file, if set.

=== api.auth_token
`$LAUNCH_AGENT_API_AUTH_TOKEN`

This is a token used to identify the launch agent to CircleCI and can be generated by the CircleCI CLI. An existing token may be shared among many installations, but this token only allows a particular `resource_class` to be specified.

=== api.url
`$LAUNCH_AGENT_API_URL`

This is the URL used by runner to communicate with CircleCI. This variable is only required for runners installed for the 3.2 version of server.

=== runner.name
`$LAUNCH_AGENT_RUNNER_NAME`

`RUNNER_NAME` is a unique name assigned to this particular running launch agent. CircleCI recommends using the hostname of the machine so that it can be used to identify the agent when viewing statuses and job results in the CircleCI UI.

=== logging.file
This controls the file where the launch-agent and task-agent logs will go. See xref:runner-overview.adoc#circleci-runner-operation[CircleCI runner operation] for more information on the launch-agent and the task-agent.

Example:

```sh
logging:
  file: /Library/Logs/com.circleci.runner.log
```

=== runner.command_prefix
`$LAUNCH_AGENT_RUNNER_COMMAND_PREFIX`

This prefix enables you to customize how the task agent process is launched. Using a custom script here can allow you to execute arbitrary commands before and after the task runner. You should take care to ensure the supplied arguments are executed, and the correct exit code is returned from the script upon completion.

=== runner.working_directory
`$LAUNCH_AGENT_RUNNER_WORK_DIR`

This directory allows you to control the default working directory used by each job. If the directory already exists, task agent will need permissions to write to the directory. If the directory does not exist, then the task agent will need permissions to create the directory. If `%s` is present in the value, this value will be replaced with a different value for each job. Note that these directories will not be automatically removed.

=== runner.cleanup_working_directory
`$LAUNCH_AGENT_RUNNER_CLEANUP_WORK_DIR`

This directory enables you to control the working directory cleanup after each job. The default value is `false`.

=== runner.mode
`$LAUNCH_AGENT_RUNNER_MODE`

This parameter allows you to specify whether you want to terminate this runner instance upon completion of a job (single-task) or to continuously poll for new available jobs.

The possible values are:

* continuous
* single-task

NOTE: The default value is continuous.

=== runner.max_run_time
`$LAUNCH_AGENT_RUNNER_MAX_RUN_TIME`

This value can be used to override the default maximum duration the task agent will run each job. Note that the value is a string with the following unit identifiers `h`, `m` or `s` for hour minute and seconds respectively:

Here are a few valid examples:

* `72h` - 3 days
* `1h30m` - 1 hour 30 minutes
* `30s` - 30 seconds
* `50m` - 50 minutes
* `1h30m20s` - An overly specific (yet still valid) duration.

NOTE: The default value is 5 hours.

==== Customizing job timeouts and drain timeouts

If you would like to customize the job timeout setting, you can "drain" the job by sending the Launch Agent a termination (TERM) signal, which then causes the Launch Agent to attempt to gracefully shutdown. When this TERM signal is received, the launch agent enters 'draining' mode, preventing the Launch Agent from accepting any new jobs, but still allowing any current active job to be completed. At the end of "draining," the Launch Agent then signals the Task Agent to cancel any active job (by sending it a TERM signal).

NOTE: If the Task Agent does not exit a brief period after the TERM, the Launch Agent will manually kill it by sending it a KILL signal.

Draining can end in one of two ways:

* The task has been in the draining state for longer than the configured `max_run_time`.
* An additional TERM signal is received by the Launch Agent during "draining".

=== runner.idle_timeout
`$LAUNCH_AGENT_RUNNER_IDLE_TIMEOUT`

This timeout will enable a launch agent to terminate if no task has been claimed within the given time period. The value is a string with the following unit identifiers: `h`, `m` or `s` for hours, minutes and seconds, respectively (e.g., `5m` is 5 minutes).

NOTE: The default behaviour is to never time out due to inactivity.

=== runner.ssh.advertise_addr
`$LAUNCH_AGENT_RUNNER_SSH_ADVERTISE_ADDR`

This parameter enables the 'Rerun job with SSH' feature. Before enabling this feature, there are xref:runner-installation.adoc#considerations-before-enabling-ssh-debugging[*important considerations that should be made*].

The address is of the form `*host:port*` and is displayed in the 'Enable SSH' and 'Wait for SSH' sections for a job that is rerun.

NOTE: While the presence of the `runner.ssh.advertise_addr` variable enables the 'Rerun job with SSH' feature, the value it holds is for publishing purposes only in the web UI. The address does not need to match the actual host and port of the machine that the runner is installed on and can be a proxy configuration.

==== Considerations before enabling SSH debugging

Task agent runs an embedded SSH server and agent on a dedicated port when the 'Rerun job with SSH' option is activated. This feature will not affect any other SSH servers or agents on the system that the runner is installed on.

* The host port used by the SSH server is currently fixed to `*54782*`. Ensure this port is unblocked and available for SSH connections. A port conflict can occur if multiple launch agents are installed on the same host.
* The SSH server will inherit the same user privileges and associated access authorizations as task agent as defined by the xref:runner-installation.adoc#runner-command_prefix[runner.command_prefix parameter].
* The SSH server is configured for public key authentication. Anyone with permission to initiate a job can rerun it with SSH, but only the user who initiated the rerun will have their SSH public keys added to the server for the duration of the SSH session.
* Rerunning a job with SSH will hold the job open for *two hours* if a connection is made to the SSH server, or *ten minutes* if no connection is made, unless cancelled. While in this state, the job is counted against an organization’s concurrency limit, and the task agent will be unavailable to handle other jobs. Therefore, it is recommended to cancel an SSH rerun job explicitly (through the web UI or CLI) when finished debugging.