---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Machine runner installation on Linux
:page-layout: classic-docs
:page-liquid:
:page-description: Instructions on how to install CircleCI's self-hosted runner on Linux.
:icons: font
:experimental:
:machine:
:linux:

This page describes how to install CircleCI's machine runner on Linux.

[#prerequisites]
== Prerequisites

{% include snippets/runner/machine-runner-prereq.adoc %}

[#self-hosted-runner-terms-agreement]
== Self-hosted runner terms agreement

{% include snippets/runner/terms.adoc %}

[#create-namespace-and-resource-class]
== 1. Create namespace and resource class

[.tab.machine-runner.Web_app_installation]
--
{% include snippets/runner/install-with-web-app-steps.adoc %}
--
[.tab.machine-runner.CLI_installation]
--
{% include snippets/runner/install-with-cli-steps.adoc %}

--


[#install-circleci-runner]
== 2. Install circleci-runner

[.tab.machine-runner-package-installation.debian]
--
{% include snippets/runner/machine-runner-deb-package-install.adoc %}
--
[.tab.machine-runner-package-installation.rpm]
--
{% include snippets/runner/machine-runner-rpm-package-install.adoc %}
--
[.tab.machine-runner-package-installation.manual_installation]
--
{% include snippets/runner/machine-runner-manual-install.adoc %}

--


[#troubleshooting]
== Troubleshooting

Refer to the <<troubleshoot-self-hosted-runner#troubleshoot-machine-runner,Troubleshoot Machine Runner section>> of the Troubleshoot Self-hosted Runner guide if you encounter issues installing or running machine runner on Linux.
