---
version:
- Cloud
- Server v3.x
---
= CircleCI Self-hosted Runner Installation on Linux
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This page describes how to install CircleCI self-hosted runner on Linux.

{% include snippets/runner-platform-prerequisites.adoc %}

toc::[]

[#download-the-launch-agent-script]
== Download the launch agent script

Save the link:https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/download-launch-agent.sh[launch-agent.sh] script file to an easily accessible location. From that location, install the launch agent binary for your target platform, either x86_64, or ARM64:

```shell
curl https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/download-launch-agent.sh --output ./download-launch-agent.sh
```

```shell
chmod +x ./download-launch-agent.sh
```

```shell
# For Linux x86_64:
export platform=linux/amd64 && sh ./download-launch-agent.sh
```

```shell
# For Linux ARM64:
export platform=linux/arm64 && sh ./download-launch-agent.sh
```

After successful installation, the download-launch-agent.sh file can be deleted.

[#create-the-circleci-user-and-working-directory]
== Create the `circleci` user and working directory

These will be used when executing the task agent. These commands must be run as a user with permissions to create other users (e.g. `root`). For information about GECOS, see the https://en.wikipedia.org/wiki/Gecos_field[wiki page].

[#ubuntu-debian]
=== Ubuntu/Debian

```shell
id -u circleci &>/dev/null || sudo adduser --disabled-password --gecos GECOS circleci
```

[#centos-rhel]
=== CentOS/RHEL

```shell
id -u circleci &>/dev/null || sudo adduser -c GECOS circleci
```

[#create-the-working-directory]
=== Create the working directory and set permissions

```shell
sudo mkdir -p /var/opt/circleci
```

```shell
sudo chmod 0750 /var/opt/circleci
```

```shell
sudo chown -R circleci /var/opt/circleci /opt/circleci/circleci-launch-agent
```

Consider running the following additional command if you would like to use certified orbs that work on Cloud on your self-hosted runner, without errors. Note that this enables code to execute root commands on your machine, and changes to the system may persist after the job is run.

```shell
echo "circleci ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
```

[#create-the-circleci-self-hosted-runner-configuration]
== Create the CircleCI self-hosted runner configuration

Create a `launch-agent-config.yaml` file with a path of `/etc/opt/circleci/launch-agent-config.yaml`, owned by `circleci`, with permissions `600`. Use the following commands:

```shell
sudo mkdir -p /etc/opt/circleci && sudo touch /etc/opt/circleci/launch-agent-config.yaml
```

```shell
sudo chown circleci: /etc/opt/circleci/launch-agent-config.yaml
```

```shell
sudo chmod 600 /etc/opt/circleci/launch-agent-config.yaml
```

Copy the following to the new `/etc/opt/circleci/launch-agent-config.yaml` file:

```yaml
api:
  auth_token: AUTH_TOKEN
  # On server, set url to the hostname of your server installation. For example,
  # url: https://circleci.example.com

runner:
  name: RUNNER_NAME
  working_directory: /var/opt/circleci/workdir
  cleanup_working_directory: true
```

- Replace `AUTH_TOKEN` with the resource class token created in the xref:runner-installation.adoc#authentication[Authentication] step.
- Replace `RUNNER_NAME` with the name you would like for your self-hosted runner. `RUNNER_NAME` is unique to the the machine that is installing the runner. `RUNNER_NAME` can be any value you would like, and it does not need to include any part of your namespace or resource class name.

[#configure-selinux-policy]
== Configure SELinux policy (RHEL 8)

An SELinux policy is required for self-hosted runner to accept and launch jobs on RHEL 8 systems (earlier versions of RHEL are unsupported). Note that this policy does not add any permissions to the ones that may be required by individual jobs on this self-hosted runner install.

Create directory `/etc/opt/circleci/policy` and generate the initial policy module:

```shell
sudo mkdir -p /etc/opt/circleci/policy
```

```shell
# Install sepolicy and rpmbuild if you haven't already
sudo yum install -y policycoreutils-devel rpm-build
```

```shell
sudo sepolicy generate --path /etc/opt/circleci/policy --init /opt/circleci/circleci-launch-agent
```

Download the following type enforcing file https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/rhel8-install/circleci_launch_agent.te[`circleci_launch_agent.te`] and install the policy:

```shell
sudo curl https://raw.githubusercontent.com/CircleCI-Public/runner-installation-files/main/rhel8-install/circleci_launch_agent.te --output /etc/opt/circleci/policy/circleci_launch_agent.te
```

```shell
sudo /etc/opt/circleci/policy/circleci_launch_agent.sh
```

[#start-launch-agent]
== Start launch agent

You can now start launch agent as follows:

```shell
sudo /opt/circleci/circleci-launch-agent --config /etc/opt/circleci/launch-agent-config.yaml
```

You can also optionally run launch agent <<#enable-the-systemd-unit,as a systemd service>>.

{% include snippets/runner-config-reference.adoc %}

[#enable-the-systemd-unit]
== Enable the `systemd` unit

NOTE: This step is optional.

You will need to have https://systemd.io/[systemd] version 235+ installed for this optional step.

Create `/usr/lib/systemd/system/circleci.service` owned by `root` with permissions `755`.

```shell
sudo touch /usr/lib/systemd/system/circleci.service
```

```shell
sudo chown root: /usr/lib/systemd/system/circleci.service
```

```shell
sudo chmod 755 /usr/lib/systemd/system/circleci.service
```

You must ensure that `TimeoutStopSec` is greater than the total amount of time a task will run for - which defaults to 5 hours.

If you want to configure the CircleCI self-hosted runner installation to start on boot, it is important to note that the launch agent will attempt to consume and start jobs as soon as it starts, so it should be configured appropriately before starting. The launch agent may be configured as a service and be managed by `systemd` with the following scripts:

```
[Unit]
Description=CircleCI Runner
After=network.target
[Service]
ExecStart=/opt/circleci/circleci-launch-agent --config /etc/opt/circleci/launch-agent-config.yaml
Restart=always
User=circleci
NotifyAccess=exec
TimeoutStopSec=18300
[Install]
WantedBy = multi-user.target
```

Unlike the task agent, which uses the environment of the `circleci` user, the launch agent will need to have any required environment variables (e.g., proxy settings) explicitly defined in the unit configuration file. These can be set by `Environment=` or `EnvironmentFile=`. https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment[Please visit the `systemd` documentation for more information].

You can now enable the service:

```shell
sudo systemctl enable circleci.service
```

[#start-the-service]
=== Start the service

When the CircleCI self-hosted runner service starts, it will immediately attempt to start running jobs, so it should be fully configured before the first start of the service.

```shell
sudo systemctl start circleci.service
```

[#verify-the-service-is-running]
=== Verify the service is running

The system reports a very basic health status through the `status` field in `systemctl`. This will report **Healthy** or **Unhealthy** based on connectivity to the CircleCI APIs.

You can see the status of the agent by running:

```shell
systemctl status circleci.service --no-pager
```

Which should produce output similar to:

```
circleci.service - CircleCI Runner
   Loaded: loaded (/var/opt/circleci/circleci.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-29 14:33:31 UTC; 18min ago
 Main PID: 5592 (circleci-launch)
   Status: "Healthy"
    Tasks: 8 (limit: 2287)
   CGroup: /system.slice/circleci.service
           └─5592 /opt/circleci/circleci-launch-agent --config /etc/opt/circleci/launch-agent-config.yaml
```

You can also see the logs for the system by running:

```shell
journalctl -u circleci
```
