---
contentTags:
  platform:
  - Cloud
---
= Scheduled pipelines
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about scheduled pipelines for your CircleCI projects.
:icons: font
:experimental:

include::../_includes/partials/notes/standalone-unsupported.adoc[This feature is not supported for GitLab, GitHub App or Bitbucket Data Center]

Scheduled pipelines allow you to trigger pipelines periodically based on a schedule. Scheduled pipelines retain all the features of pipelines:

- Control the actor (yourself, or the scheduling system) associated with the pipeline, which can enable the use of xref:contexts#project-restrictions[Restricted contexts].
- Use xref:dynamic-config#[Dynamic configuration] via setup workflows.
- Modify the schedule without having to edit `.circleci/config.yml`.
- Take advantage of xref:skip-build#auto-cancel[auto-cancelling].
- Specify xref:pipeline-variables#pipeline-parameters-in-configuration[Pipeline parameters] associated with a schedule.
- Manage common schedules, for example, across workflows.

Scheduled pipelines are configured through the API, or through the project settings in the CircleCI web app.

NOTE: A scheduled pipeline can only be configured for one branch. If you need to schedule for two branches, you would need to set up two schedules.

[#introduction]
== Introduction

Scheduled pipelines allow you to trigger pipelines periodically based on a schedule. Schedules can range from daily, weekly, monthly, or on a very specific timetable. To set up basic scheduled pipelines, you do not need any extra configuration in your `.circleci/config.yml` file. However, more advanced usage of the feature will require extra `.circleci/config.yml` configuration (for example, workflow filtering, or using parameters).

Pipeline parameters are typed pipeline variables in the form of a string, integer, or boolean. Adding a parameter to a scheduled pipeline can be done in the web app in the triggers form while setting up a schedule. Any parameters set up in this manner must be added to your configuration file using the `parameters` key.

Scheduled pipelines are set to run by an "actor", either the CircleCI scheduling system, or a specific user (for example, yourself). The scheduling actor is important to consider if making use of restricted contexts in workflows. If the user (actor) running the workflow does not have access to the context, the workflow will fail with the `Unauthorized` status.

You can find a basic how-to guide on the xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline] page, and more advanced examples on the xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows] pages.

[#get-started-with-scheduled-pipelines]
== Get started with scheduled pipelines

To get started with scheduled pipelines, you have the option of using the API, or using the CircleCI web app. Both methods are described below.

[#use-project-settings]
=== Use project settings in the web app

include::../_includes/partials/pipelines-and-triggers/scheduled-pipeline-setup.adoc[Setting up a scheduled pipeline using the CircleCI web app]

[#use-the-api]
=== Use the API

If your project has no scheduled workflows, and you would like to try out scheduled pipelines:

. Have your CircleCI token ready, or create a new token by following the steps on the xref:managing-api-tokens#[Managing API tokens] page.
. Create a new schedule link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[using the API]. For example:
+
```shell
curl --location --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
--header "circle-token: <PERSONAL_API_KEY>" \
--header "Content-Type: application/json" \
--data-raw '{
    "name": "my schedule name",
    "description": "some description",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
      <additional pipeline parameters can be added here>
    },
    "timetable": {
        "per-hour": 3,
        "hours-of-day": [1,15],
        "days-of-week": ["MON", "WED"]
    }
}'
```

include::../_includes/partials/tips/find-project-slug.adoc[]

For additional information, refer to the **Schedule** section under the link:https://circleci.com/docs/api/v2[API v2 docs]. Also see the xref:api-developers-guide#getting-started-with-the-api[Getting started with the API] section of the API Developer's Guide for more guidance on making requests.

[#migrate-scheduled-workflows-to-scheduled-pipelines]
== Migrate scheduled workflows to scheduled pipelines

If you have existing scheduled workflows you need to migrate to scheduled pipelines, use the xref:migrate-scheduled-workflows-to-scheduled-pipelines#[Scheduled pipelines migration] guide.

[#scheduled-pipelines-video-tutorial]
== Scheduled pipelines video tutorial

The video offers a short tutorial for the following scenarios:

- Set a schedule in the web app
- Set a schedule with the API
- Migrate from scheduled workflows to scheduled pipelines

++++
<div class="video-wrapper">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/x3ruGpx6SEI" title="Scheduled pipelines tutorial" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
++++

For the documentation for these scenarios, visit the following pages:
- xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline]
- xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows]

[#scheduled-pipelines-faqs]
== FAQs

include::../_includes/partials/faq/scheduled-pipelines-faq-snip.adoc[]

[#next-steps]
== Next steps

- xref:migrate-scheduled-workflows-to-scheduled-pipelines#[Migrate scheduled workflows to scheduled pipelines]
- xref:schedule-pipelines-with-multiple-workflows#[Schedule pipelines with multiple workflows]
- xref:set-a-nightly-scheduled-pipeline#[Set a nightly scheduled pipeline]
