---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Configuring a Proxy
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

WHY USE A PROXY?

toc::[]

== Configuring your proxy

== Known limitations

* The JVM only accepts proxies that run over HTTP not HTTPS and therefore proxy URIs must be of the form http://user:password@host:port rather than https://user:password@host:port.
* When using GitHub.com we cannot run in an environment were the only network egress is through the HTTP proxy. This is because SSH connections to GitHub.com will break and therefore we can't do code checkout or init the known-hosts in dispatcher [WAITING FOR MORE INFO ON THIS ONE]
* The load balancer endpoints must be added to the no-proxy list for the following services: `output processor` and `vm-service`. This is because the no-proxy list is shared between the application and build-agent. The application and build-agent are assumed to be behind the same firewall and therefore cannot have a proxy between them.
* The KOTS admin console cannot be upgraded if proxy setting were set. The proxy settings will be deleted and cause the Kots admin console to break.
* Often, a custom image is needed for VM service that has proxy configured! (Check with Makoto Mizukami   about this and how customers have set this up before)
* If object storage is outside the proxy no job features that use object storage will work. This includes:
** Artifacts
** Test-results
** Cache save and restore
** Workspaces
+
This is because all of these involve build-agent inner uploading to object storage, but the environment variables from schedulerer are only passed to build-agent outer (and hence it can pull task configs etc, but inner can't do anything). Users need to get around this by setting environment variables on their job like so:
+
```yml
jobname:
  docker:
  - image: ubuntu:latest
    environment:
      HTTP_PROXY: http://proxy.example.com:3128
      HTTPS_PROXY: http://proxy.example.com:3128
      NO_PROXY: whatever.internal,10.0.1.2
```
+
It is extremely important that these environment variables are set in this particular location because its the only location that propagates to build-agent inner.