---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Installation Phase 4
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Before you begin with the CircleCI server v3.x post installation phase, ensure you have run through xref:server-3-install-prerequisites.adoc[Phase 1 – Prerequisites], xref:server-3-install.adoc[Phase 2 - Core services installation] and xref:server-3-install-build-services.adoc[Phase 3 - Build services installation].

toc::[]

== Phase 4: Post installation

=== Orbs 

Server installations include their own local orb registry. This registry is private to the server installation. All orbs referenced in project configs reference the orbs in the _server_ orb registry. You are responsible for maintaining orbs. This includes: 

* Copying orbs from the public registry 
* Updating orbs that may have been copied prior 
* Registering your company's private orbs if they exist

For more information, and steps to complete these tasks see the https://circleci.com/docs/2.0/server-3-operator-orbs/[Orbs on Server guide].

=== Email Notifications 

Build notifications are sent via email. Access the KOTS admin console. Get to the KOTS admin console by running the following, substituting your namespace: `kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>` and locate the *Email Notifications* section in *Settings* and fill in the following details to configure email notifications for your installation.

* *Email Submission server hostname (required)* - Host name of the submission server (e.g., for Sendgrid use smtp.sendgrid.net).

* *Username (required)* - Username to authenticate to submission server. This is commonly the same as the user’s e-mail address.

* *Password (required)* - Password to authenticate to submission server.

* *Port (optional)* - Port of the submission server. This is usually either 25 or 587. While port 465 is also commonly used for email submission, it is often used with implicit TLS instead of StartTLS. Server only supports StartTLS for encrypted submission. 
+
NOTE: Outbound connections on port 25 are blocked on most cloud providers. Should you select this port, be aware that your notifications may fail to send
Enable StartTLS: Enabling this will encrypt mail submission. 

* *Email from address (required)* - The from address for the email.  

NOTE: StartTLS is used to encrypt mail by default, and you should only disable this if you can otherwise guarantee the confidentiality of traffic.

Click the *Save config* button to update your installation and re-deploy server.

ifndef::pdf[]
## What to read next

* https://circleci.com/docs/2.0/server-3-install-hardening-your-cluster[Hardening Your Cluster]
* https://circleci.com/docs/2.0/server-3-install-migration[Server 3.x Migration]
endif::[]