---
description: "This document lists the steps required to upgrade a CircleCI server v3.x installation."
version:
- Server v3.x
- Server Admin
---
= CircleCI server v3.x upgrade guide
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Upgrading your server v3.x installation requires that you have access to the Kubernetes cluster in which server is installed, and have an instance of KOTS Admin Console running. 

Before upgrading, ensure you have set up https://circleci.com/docs/server-3-operator-backup-and-restore[Backup and Restore]. 

A successful deployment will update the UI. Unless noted in the release notes, updates are rolling updates and there is no downtime. 

NOTE: We recommend that you do not skip releases.

== Upgrade server v3.x

. Enter the KOTS Admin Console. To do this, run the following, substituting your CircleCI server namespace: 
+
----
kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>
----

. Log in to the Admin Console with the password you created during the installation process.

. Select the **Snapshots** tab and take a snapshot of your installation. For more information, see the https://circleci.com/docs/server-3-operator-backup-and-restore/#creating-backups[Backup and Restore] guide.

. Select the **Version History** tab. Click **Check for Updates** before proceeding. 

. Once you have the most recent versions visible, run through the following checklist before selecting **Deploy** for the version you would like to upgrade to.
+
* Check the https://circleci.com/server/changelog/[change log] and make sure there are no actions you need to take before deploying a new version. 
* Check the config for the version you are deploying and make sure there are no new fields or features you may be interested in deploying (the gears next to the deploy button will take you to the config specific to that version). 

. Deploy and run https://github.com/circleci/realitycheck[`reality check`] in your test environment to ensure your installation is fully operational.







