---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x User Accounts
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This section provides information to help operators manage user accounts. For an overview of user accounts, view the
Admin settings overview from the CircleCI app by clicking on your profile in the top right corner and selecting Admin.

toc::[]

## Suspending Accounts
This section covers how to suspend new, active, or inactive accounts.

### New Accounts

Any user associated with your GitHub organization can create a user account for your CircleCI Server installation. In
order to control who has access, you can choose to automatically suspend all new users, requiring an administrator to
activate them before they can log in. To access this feature:

. Navigate to your CircleCI Admin Settings
. Select System Settings from the Admin Settings menu
. Set Suspend New Users to True

### Active Accounts
When an account is no longer required, you can suspend the account so it will no longer be active and will not count
against your license quota. To suspend an account:

. Navigate to your CircleCI Admin Settings
. Select Users from the Admin Settings menu
. Scroll to locate the account in either the Active or Inactive window
. Click Suspend next to the account name and the account will appear in the Suspended window

### Inactive Accounts
Inactive accounts are those that have been approved by the administrator of the server installation but have not logged
into the system successfully. These accounts do not count against your server seats available.

## Reactivating Accounts
This section covers how to reactivate new or previously active accounts.

### New Accounts
To activate a new account that was automatically suspended and allow the associated user access to your installation of
CircleCI Server:

. Navigate to your CircleCI Admin Settings
. Select Users from the Admin Settings menu
. View the Suspended New Users window
. Click on Activate next to the User you wish to grant access and the account will appear in the Active
Window

### Previously Active Accounts
To reactivate an account that has been suspended:

. Navigate to your CircleCI Admin Settings
. Select Users from the Admin Settings menu
. View the Suspended window
. Click on Activate next to the User you wish to grant access and the account will appear in the Active window.

## Limiting Registration by GitHub Organization
When using github.com, you can limit who can register with your CircleCI install to people with some connection to your
approved organizations list. To access this feature:

. Navigate to your CircleCI Admin Settings page
. Select System Settings from the Admin Setting menu
. Scroll down to Required Org Membership List
. Enter the organization(s) you wish to approve. If entering more than one organization, use a comma delimited string.

## Using the CircleCI CLI

This section covers how to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to list or delete users.

### List Users
To view a full list of users for your CircleCI Server installation, first SSH into your Services machine, and run:

[source,bash]
----
circleci dev-console
(circle.model.user/where { :$and [{:sign_in_count {:$gte 0}}, {:login {:$ne nil}}]} :only [:login])
----

### Delete User
If you need to remove a user from your installation of CircleCI Server, you will need to SSH into the services machine
first and then delete using the following command, substituting the user’s GitHub username:

[source,bash]
----
circleci dev-console
(circle.http.api.admin-commands.user/delete-by-login-vcs-type! "github-username-of-user" :github)
----