---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x What's New
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Server 3.0 is now generally available. The newest version of server offers the ability to scale under heavy workloads,
all within your own Kubernetes cluster and private network, while still enjoying the full CircleCI cloud experience.
Server 3.0 includes the latest CircleCI features, such as orbs, scheduled workflows, matrix jobs, and more. For existing
customers interested in migrating from 2.19 to 3.x, contact your customer success manager. Server 3.0 will receive monthly
patch releases and quarterly feature releases.

== New Features

* New UI
* Orbs for Server
* Pipelines
* Config 2.1
* API 2.0
* Scheduled Workflows
* Matrix Jobs
* And much more...

== Known Issues

* No support for external data stores (Postgres, Mongo, Vault). This feature will be implemented in a future release.
* It is currently possible for multiple organizations under the same CircleCI server account to have contexts with
identical names. This should be avoided as doing so could lead to errors and unexpected behavior.

// TO DO: Add links
//To learn more about server 3.0 installation, migration, or operations please see our documentation.



