---
description: "Server 3.x is now generally available. Server 3.x includes the latest CircleCI features, such as orbs, scheduled workflows, matrix jobs, and more."
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x What's New
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Server 3.x is now generally available. The newest version of server offers the ability to scale under heavy workloads, all within your own Kubernetes cluster and private network, while still enjoying the full CircleCI cloud experience.

Server 3.x includes the latest CircleCI features, such as orbs, scheduled workflows, matrix jobs, and more. For existing customers interested in migrating from 2.19 to 3.x, contact your customer success manager. Server 3.x will receive monthly patch releases and quarterly feature releases.

toc::[]

== Release 3.4.1

=== Upgrade notes

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* Run `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`
* Deploy the app from the KOTS Admin Console

=== Fixes

* Kong resource limits have been increased. The previous limits were affecting the stability of some server installations.
* Fixed a bug that was preventing distributor-external from running in certain environments.
* The KOTS config has been updated to allow private loadbalancers when ACM is in use.

=== Known issues

* The CircleCI Build Agent can now be pulled from a custom Docker registry if required. For more information contact customer support.
* You can now use Amazon Certificate Manager (ACM) to manage your TLS certificates. For more information see the https://circleci.com/docs/2.0/server-3-install/#frontend-settings[Server v3.x Installation Guide].
* Kubernetes v1.16 - v1.23 are now supported.
* Workload Identities for installations on GCP are now supported. Workload Identities can be used as an alternative to static credentials. For more information see the https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[Server v3.x Installation Guide]

== Release 3.4.0

=== Upgrade notes

Before upgrading to v3.4.x, delete the deployment named `circleci-server-kube-state-metrics`:

* Run `kubectl delete deployment/circleci-server-kube-state-metrics --cascade=orphan`
* Deploy the app from the KOTS Admin Console

=== New Features

* Android images for the machine executor are now available. For more information, see the https://circleci.com/docs/2.0/android-machine-image/[Using Android Images with the Machine Executor] guide.
* The CircleCI Build Agent can now be pulled from a custom Docker registry if required. For more information contact customer support.
* You can now use Amazon Certificate Manager (ACM) to manage your TLS certificates. For more information see the https://circleci.com/docs/2.0/server-3-install/#frontend-settings[Server v3.x Installation Guide].
* Kubernetes v1.16 - v1.23 are now supported.
* Workload Identities for installations on GCP are now supported. Workload Identities can be used as an alternative to static credentials. For more information see the https://circleci.com/docs/2.0/server-3-install-prerequisites/#enable-workload-identities-in-gke-optional[Server v3.x Installation Guide]

=== Fixes

* Fixed a bug that was causing the jobs page and step output access to run very slow in the CircleCI web app.
* Fixed a bug that was causing the workflows conductor pod to crash and cause issues with StatsD metrics.

=== Known Issues

* Prometheus is broken in KOTS versions 1.65.0 - 1.67.0. If you rely on this feature, do not upgrade your KOTS version until this issue has been resolved.
* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised. For example, by using a VPN into your VPC.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the
application to indicate the cause of the issue. If a build is run on your installation and does not show up in the
CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration
and get details of the possible cause of the issue.
* The KOTS admin console cannot be upgraded if your installation is set up to be behind a proxy. The proxy settings will be deleted and cause the KOTS admin console to break.
* Config files will now be stored in the https://circleci.com/docs/2.0/server-3-install-prerequisites/#object-storage-and-permissions[chosen object store] (e.g., AWS S3, Google Cloud Storage or Minio). Users can run into errors accessing certain pipelines, if these config files are deleted due to retention policies (e.g., AWS S3 Lifecycle).

== Release 3.3.1

=== Fixes

* CircleCI runner can now be used when server is installed behind a proxy.
* Fixed a bug that was causing some intermittent broken dependency caches.
* Removed outdated cert trust stores from some images. They were found to be causing access issues to some server installations.
* Self-signed certificates or private certificate authorities are now supported when using GitHub Enterprise.
* Fixed a bug that was affecting runner updates.
* SSH reruns now work when server is installed behind a proxy.
* Replaced deprecated GitHub API endoint for `teams`.

=== Known issues

* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. The proxy settings will be deleted and cause the KOTS Admin Console to break.

== Release 3.3.0

=== New features

* Nomad Autoscaler can now be used to scale Nomad clients. For more information see the https://circleci.com/docs/2.0/server-3-install-build-services/#nomad-autoscaler[execution environments installation docs].
* https://circleci.com/docs/2.0/webhooks/[Webhooks] are now available.
* The Insights dashboard is now available.
* IRSA (AWS) can now be used as an alternative to keys for object storage authentication.
* The email address from which build notifications are sent is now configurable from the KOTS Admin Console.
* We have replaced https://github.com/traefik/traefik-helm-chart[Traefik] with https://github.com/Kong/charts[Kong] as our reverse proxy. However, in order to minimize disruption when upgrading, we chose not to rename the service used by kong. Therefore, you will see a service named `circleci-server-traefik`, however, this service is actually for Kong.

=== Fixes

* Upgraded Python to v3 in Vault container.
* https://circleci.com/docs/2.0/server-3-operator-vm-service/#google-cloud-platform[Docs improvements] on using the shared VPC architecture in GCP.
* The JVM heap size has been updated so that `output-processor` can use up to 80% of the pod memory limit.

=== Known issues

* Updating GitHub Enterprise with a modified Let's Encrypt certificate is unsupported.
* Let's Encrypt's new root certificate `isrgrootx1` is not trusted.
* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. The proxy settings will be deleted and cause the KOTS Admin Console to break.
* Runner cannot be used when server is installed behind a proxy.

== Release 3.2.2

=== Upgrade notes

* The https://circleci.com/docs/api/v2/#operation/rerunWorkflow[rerun workflow] endpoint now returns workflow ID rather than the message `accepted`.

=== Fixes

* TLS is terminated outside of `frontend` so the SSL server has been completely removed from the `frontend` container.
* Moved the default certificate logic from KOTS to Helm.
* Fixed the build agent image version used in server v3.x. The image used previously was causing problems with runner.

=== Known issues

* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. The proxy settings will be deleted and cause the KOTS Admin Console to break.
* Runner cannot be used when server is installed behind a proxy.
* Let's Encrypt certificate generation does not work. You need to provide your own certificates or use the default certificates provided.

== Release 3.2.1

=== Upgrade notes

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

See <<Upgrade notes>> before upgrading from v3.1.x to v3.2.x.

=== New features
* Private VMs are now supported for installations on GCP.

=== Fixes
* mTLS is now disabled by default.
* SSH timeout for VMs has been increased to 10 minutes.
* Private VMs now request private IPs.

=== Known issues

* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations, but for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.
* The KOTS Admin Console cannot be upgraded if your installation is set up behind a proxy. The proxy settings will be deleted and cause the KOTS Admin Console to break.
* Runner cannot be used when server is installed behind a proxy.
* Let's Encrypt certificate generation does not work. You need to provide your own certificates or use the default certificates provided.

== Release 3.2.0

=== Upgrade notes

From the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.2.0.

When upgrading from server 3.1.x to 3.2, there will be some downtime due to a change to the PostgreSQL pod. There are two issues you could run into with this update, which are covered in the following sections.

==== PostgreSQL pod stuck in `pending`
If you find that the PostgreSQL pod is stuck in a `pending` state after upgrading, scale down the pods to 0 and then scale up again by following the steps below.

To check if your PostgreSQL pod is stuck in `pending`, use the following command:

```shell
$ kubectl get pod -l app.kubernetes.io/name=postgresql
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Pending   0          3m
```

The following command will scale down pods to 0 and terminate the application pods without any data loss:

```shell
kubectl scale deployment -l layer=application --replicas 0
```

Once all the application-layer pods have finished terminating, do *one* of the following:

* *either* redeploy the update from the KOTS Admin Console
* *or* run the following two commands to redeploy the pods and return server to a functional state:
+
```shell
kubectl scale deployment -l layer=application --replicas 1
```
+
Then scale `output-processor` up with the following command:
+
```shell
kubectl scale deployment output-processor --replicas 2
```

==== Traefik pod fails to schedule
If you find that there are two Traefik pods after upgrading, you need to locate the older pod and remove it to allow the new pod to schedule correctly.

To see the status of your Traefik pod, use the following command:

```shell
$ kubectl get pod -l app=traefik
NAME                                      READY   STATUS    RESTARTS   AGE
circleci-server-traefik-9d6b86fd8-f7n2x   1/1     Running   0          24d
circleci-server-traefik-cf7d4d7f6-6mb5g   1/1     Error     0          3m
```

Remove the older Traefik pod with the following command:

```shell
kubectl delete pod circleci-server-traefik-<older pod hash>
```

The new Traefik pod will then start to schedule correctly.

=== New features

* Customers who require a fully private installation can now access a setting in the KOTS Admin Console to ensure public IPs are not assigned to VMs. Note that with this non-public IP setting enabled, a workaround will be needed if SSH access to running jobs is required, for example, by using a VPN into your VPC.
* Customers who manage outbound traffic through a proxy can now configure proxy settings through the KOTS Admin Console. Please see our documentation for specifics on https://circleci.com/docs/2.0/server-3-operator-proxy/[proxy support for server].
* We have expanded the machine execution environment options available to include additional resource classes, sizes, and executors. You now have access to Arm (medium, large), Linux (medium, large, X large, and XX large), and Windows (medium, large, XX large) resource classes.
* The https://circleci.com/docs/2.0/insights/[insights API] is now available to all server customers. Leverage build and other data to better understand the performance of teams and the health of your build and testing efforts.
* We have revamped the admin UI, and updated our installation instructions, making it easier to set up and manage server.
* You can now supply a custom Linux AMI for VM service.
* SSL termination can now be disabled. If you have put server login behind a firewall, this will enable SSL termination at the firewall.
* You can now control the size of persistent volumes. For larger customers, the initial persistent volume size was too small, by default. You can now set this at install time, providing an easier migration for those customers that require it. For further information see the https://circleci.com/docs/2.0/server-3-operator-extending-internal-volumes/[Internal Database Volume Expansion doc].
* We have added an auto-scaling example to the https://github.com/CircleCI-Public/server-terraform/blob/main/nomad-aws/main.tf[nomad client terraform].
* You can now choose to serve 'unsafe' build artifacts. Previously this option was hidden, meaning potentially unsafe artifacts were rendered as plain text. For more information see the https://circleci.com/docs/2.0/server-3-operator-build-artifacts/[Build Artifacts doc].

=== Fixes

* The default windows executor was not as documented. We have increased the size to align with documentation and cloud.

=== Known issues

* KOTS admin configuration incorrectly selects the Nomad mTLS as `enabled` during setup. It should be set to mTLS `disabled` until after Nomad clients have been deployed.
* Retry with SSH for jobs using the machine executor advertises a private IP address. For this reason, retry with SSH for jobs using the machine executor. Works as standard for private installations. However, for public installs you would need to ensure that you can access the private IP advertised, for example, by using a VPN into your VPC.
* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration
and get details of the possible cause of the issue.
* The KOTS Admin Console cannot be upgraded if your installation is set up to be behind a proxy. The proxy settings will be deleted and cause the KOTS Admin Console to break.
* Runner cannot be used when server is installed behind a proxy.
* Let's Encrypt certificate generation does not work. You need to provide your own certificates or use the default certificates provided.

== Release 3.1.0

=== Upgrade notes

IMPORTANT: With this release, the `frontend-external` load balancer has been removed. The `traefik` load balancer now handles all incoming traffic. When updating from a previous server 3.x version, you need to update the DNS record that was pointing to the `frontend-external` load balancer and point it to the `circleci-server-traefik` load balancer instead. Remember, you can retrieve the external IP address or DNS name of your Traefik load balancer by typing `kubectl get svc/circleci-server-traefik` in a terminal that has access to the cluster.

To update your DNS record and upgrade your server installation, follow these steps:

. Retrieve the external IP or DNS name for the Traefik load balancer as described, or by looking the DNS A record for `app.<your domain name>` - this should already point to your Traefik load balancer.
. Locate the DNS A record that points to the domain name of your server installation (not the one pointing to the `app.` subdomain).
. Edit the A record so that it points to the Traefik load balancer, the same as the `app.` subdomain record. Your changes might need a couple of minutes to take effect, depending on your DNS service.

Next, from the KOTS Admin Console, select *Version History* from the menu bar and click **Deploy** for server v3.1.0.

=== New features

* Telegraf plugins can now be added to server and customized to use third-party monitoring solutions, for example, Datadog. For more information, see the https://circleci.com/docs/2.0/server-3-operator-metrics-and-monitoring/[Metrics and Monitoring] doc.
* The option to use only private load balancers has been introduced for customers who want a fully private installation. For more information, see the https://circleci.com/docs/2.0/server-3-operator-load-balancers/[Load Balancers] guide.
* Server 3.x hosts build artifacts, test results, and other state in object storage. We support any S3-compatible storage and Google Cloud Storage. For more information, see the https://circleci.com/docs/2.0/server-3-install/[Installation guide].
* Dynamic config via setup workflows is now available on server installations. For more information, see our https://circleci.com/blog/introducing-dynamic-config-via-setup-workflows/[blog post] and the https://circleci.com/docs/2.0/dynamic-config/[Dynamic Configuration docs page].
* Runner is now available on server. For further information, including installation steps, see the https://circleci.com/docs/2.0/runner-overview/?section=executors-and-images[Runner docs]. Runner allows the use of the macOS executor in server installations and VM service functionality for customers with server installed in a private data centre.
* The frontend load balancer from v3.0 has been removed and replaced with an Ingress resource and the Traefik Ingress controller. This is a breaking change requiring you to reconfigure your DNS. See the https://circleci.com/docs/2.0/server-3-whats-new/#release-3-1-0[What's New in server docs] for further information and guidance.
* The following services can now be externalized. For setup information, see the https://circleci.com/docs/2.0/server-3-install/[server v3.x installation guide]:
** Postgres
** MongoDB
** Vault
* Backup and restore functionality is now available. For more information see the https://circleci.com/docs/2.0/server-3-operator-backup-and-restore/[Backup and Restore] guide.
* Prometheus is now deployed by default with server to monitor your cluster health and usage. Prometheus can be managed and configured from the KOTS Admin Console. For further information, see the https://circleci.com/docs/2.0/server-3-operator-metrics-and-monitoring/[Metrics and Monitoring] doc.
* Server now supports the 2XL resource class. The Nomad cluster needs to be large enough to account for larger resource classes.
* The lifecycle of build artifacts and test results can now be configured from the KOTS Admin Console under **Storage Object Expiry**, including the option to disable the expiration and retain artifacts and test results indefinitely.

=== Fixes

* Resolved a collection of bugs that were leaking sensitive information into CircleCI support bundles:
  ** Instances of faulty and partial redactions of secrets were detected, in part due to 3rd party bugs.
  ** PostgreSQL leaking sensitive information to STDOUT.
  ** Several CircleCI services were logging secrets.
* Tightened network security in the Nomad Terraform module.
* Terraform v0.15.0 and up are now supported.
* Updated installation scripts to use functions supported by most recent versions of Terraform.
* Resolved a bug that was causing machine large builds to be run on the wrong machine type. Machine large builds now correctly use four vCPUs and 16GB of RAM.
* Resolved a bug that caused contexts-service to fail on expiration of Vault client tokens.
* Resolved a bug that was causing `legacy-notifier` to report readiness prematurely.
* The JVM heap size parameter has been removed for all services. The heap size is set to be half of the memory limit.
* Changes to networking config and certs are now picked up automatically by Traefik. Previously, a restart would have been required.
* Minimum requirements for CPU and memory have changed. For the new values, see the https://circleci.com/docs/2.0/server-3-install-prerequisites/[Installation Prerequisites] doc.

=== Known issues

* It is currently possible for multiple organizations under the same CircleCI server account to create contexts with identical names. This should be avoided, as it could cause errors and unexpected behavior.
* CircleCI 1.0 builds are not supported. If an attempt is made to run a 1.0 build, no feedback will be available in the application to indicate the cause of the issue. If a build is run on your installation and does not show up in the CircleCI application, users should be directed to use the https://circleci.com/docs/2.0/local-cli/[CircleCI CLI] to validate the project configuration and get details of the possible cause of the issue.

== Release 3.0.2

- Resolved a bug relating to artifacts disappearing after 30 days. The default settings for the artifact retention period have been updated to unlimited, and can be adjusted from the KOTS Admin Console.
- Resolved a bug that made Traefik "unaware" of TLS certificate updates without requiring a manual restart of the Traefik pod. The Traefik pod now restarts automatically after any TLS certificate updates go into effect after the initial post-KOTS deployment.
- Resolved a bug in `builds-service` that was causing pods to crash as a result of running out of memory.

== Release 3.0.1

- `build_agent` `version` value updated, as the previous version was relying on a vulnerable version of PsExec.
- Due to an issue that was causing duplicated checks in GitHub, environment variables for `output-processor` were reconfigured.
- Adjusted deployment configuration for `vm-service` to handle out-of-order database migrations managed by Flyway.

ifndef::pdf[]
== What to read next
To learn more about Server v3.x, see the following:

* https://circleci.com/docs/2.0/server-3-overview[Server 3.x Overview]
* https://circleci.com/docs/2.0/server-3-install-prerequisites[Server 3.x Installation]
* https://circleci.com/docs/2.0/server-3-install-migration[Server 3.x Migration]
* https://circleci.com/docs/2.0/server-3-operator-overview[Server 3.x Operations]
endif::pdf[]
