---
contentTags: 
  platform:
  - Server v3.x
  - Server Admin
---
= CircleCI Server v3.x Troubleshooting and Support
:page-layout: classic-docs
:page-liquid:
:page-description: Use this document to find troubleshooting steps if you are having problems with your CircleCI server v3.x installation.
:icons: font
:toc: macro
:toc-title:

This document describes an initial set of troubleshooting steps to take if you are experiencing problems with your CircleCI Server v3.x installation. If your issue is not addressed below, you can generate a support bundle or contact your CircleCI account team.

toc::[]

## Start KOTS Admin Console

To restart the KOTS Admin Console, run the following command:

[source,bash]
----
kubectl kots admin-console -n <YOUR_CIRCLECI_NAMESPACE>
----

Open your browser and access http://localhost:8800 to see the Admin Console.

## Generate Support Bundle
A support bundle is used by CircleCI engineers to diagnose and fix any issues you are experiencing. They are typically requested when you open a ticket.

To download a support bundle for CircleCI support, select the *Troubleshoot* tab from the Admin Console menu bar, and then click *Analyze CircleCI Server*.

## Managing Pods

### Verify Pod Readiness and Status
NOTE: Check the `READY` column as well as `STATUS`. Even if the `STATUS` is `Running`, pods are not ready to serve user requests. Some pods may take some time to become ready.

[source,bash]
----
kubectl get pods -n <namespace>
NAME READY STATUS RESTARTS AGE
api-service-5c8f557548-zjbsj 1/1 Running 0 6d20h
audit-log-service-77c478f9d5-5dfzv 1/1 Running 0 6d20h
builds-service-v1-5f8568c7f5-62h8n 1/1 Running 0 6d20h
circleci-mongodb-0 1/1 Running 0 6d20h
circleci-nomad-0 1/1 Running 6 6d20h
…
----

To show only pods with a status besides `Running`, you can use the `--field-selector` option.

[source,bash]
----
kubectl get pods --field-selector status.phase!=Running -n <namespace>
NAME READY STATUS RESTARTS AGE
nomad-server 0/1 Error 0 5d22h
----

### Verify Pod Settings and Status
To show detailed settings and status of pods, use the following command:

[source,bash]
----
kubectl describe pods <pod-name> -n <namespace>
----

### Get Pod Logs
To show logs of pods, use the following command:

[source,bash]
----
kubectl logs <pod-name> -n <namespace>
----

### Restart Pods
To restart specific pods, the easiest way is remove the pod. Kubernetes automatically recreates the pod:

[source,bash]
----
kubectl delete pod <pod-name> -n <name-space> --now
----

## Debug Queuing Builds
For troubleshooting information on debugging queued builds, see the Server 2.x
https://circleci.com/docs/troubleshooting/?section=server-administration#debug-queuing-builds[troubleshooting] Guide.
