---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Metrics and Monitoring
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Metrics such as CPU or memory usage and internal metrics are useful in:

* Quickly detecting incidents and abnormal behavior
* Dynamically scaling compute resources
* Retroactively understanding infrastructure-wide issues

toc::[]

== Metrics Collection

=== Scope
Your CircleCI server installation collects a number of metrics and logs by default, which can be useful in monitoring
the health of your system and debug issues with your installation.


NOTE: Data is retained for a maximum of 15 days.

NOTE: Prometheus Server is not limited to only scrape metrics from your CircleCI server install. It will scrape metrics
from your entire cluster by default. You may disable prometheus from within the kots admin console config if needed.

=== Prometheus
https://prometheus.io/[Prometheus] is a leading monitoring and alerting system for Kubernetes. Server 3.x ships with basic
implementation of monitoring common performance metrics.

=== Kots Admin - Metrics Graphs
By default, an instance of Prometheus is deployed with your CircleCI server install. Once deployed, you may provide the 
address for your Prometheus instance to the kots admin dashboard. Kots will use this address to generate graph data for 
the cpu and memory usage of containers in your cluster.

The default Prometheus address is `http://prometheus-server`

From the kots dashboard, select "configure graphs". Then enter `http://prometheus-server` and kots will generate resource
usage graphs.


=== Telegraf
Most services running on server will report StatsD metrics to the https://www.influxdata.com/time-series-platform/telegraf/[Telegraf] pod running in server.
The configuration is fully customizable, so you can forward your metrics from Telegraf to any output that is supported
by Telegraf via https://docs.influxdata.com/telegraf/v1.17/plugins/#output-plugins[output plugins]. By default, it will provide a
metrics endpoint for Prometheus to scrape.
