---
contentTags:
  platform:
  - Cloud
---
= Set up multiple configuration files for a project
:page-layout: classic-docs
:page-liquid:
:page-description: A step by step guide for setting up multiple configuration files for a project in CircleCI.
:icons: font
:experimental:

NOTE: This feature is generally available for orgs that integrate with CircleCI's GitHub App and is available in "Preview" for orgs that integrate with GitHub via the xref:github-integration#[CircleCI GitHub OAuth App]. See our link:https://discuss.circleci.com/t/product-update-multiple-configuration-files-per-project/50637[community forum] for details on the "Preview".  To find out which GitHub account type you have, see the xref:github-apps-integration#[GitHub App integration] page.

You can use multiple configuration files in a CircleCI project and set up separate triggers for each one. Each configuration triggers a separate pipeline on a trigger event. If your existing configuration file is getting too large to manage, consider splitting it into multiple files.

[#prerequisites]
== Prerequisites

To use multiple configuration files for a project in CircleCI, you will need to meet the following prerequisites:

* A CircleCI account connected to your code in GitHub, integrated through our xref:github-apps-integration#[GitHub App]. You can link:https://circleci.com/signup/[sign up for free]. 
* A project set up in CircleCI that you want to configure with multiple configuration files. See the xref:create-project#[Create a project in CircleCI] page for steps.

[#add-additional-config-file]
== 1. Add an additional configuration file to your project repository

NOTE: **Splitting up an existing configuration?** If you are following these steps because you have an existing project building on CircleCI and you want to split your configuration into multiple files, you can create a new file in the `.circleci/` directory and move over some parts of your existing configuration file to your new YAML files.

In the GitHub repository for your project add a new CircleCI configuration file in the `.circleci/` directory. Your new configuration file must use the `.yml` extension but can have any name. Add your required configuration to the file and commit it to your repository.

As your repository is set up as a project in CircleCI, a `config.yml` file will exist already. If you do not see `.circleci/config.yml`, check which branch you are on. You may have set this up on a non-default branch during the set up process.

Each configuration file will trigger a separate pipeline so it is important that each configuration file is complete with all necessary elements for the pipeline, for example, `version`, `jobs`, `workflows`, `commands`, `executors`, `orbs` etc.

== 2. Set up a pipeline

Next, add a new pipeline in your CircleCI project settings.

. In the link:https://app.circleci.com/[CircleCI web app] select **Projects** in the sidebar
. Find your project in the list, select the ellipsis (icon:ellipsis-h[]) next to it and select **Project Settings**
. Select **Pipelines** in the sidebar
+
. Select btn:[Add Pipeline] (or btn:[Set Up Pipeline] for GitHub OAuth app integrations)
. Complete the required form fields:
** Give your pipeline a descriptive name
** Ensure **GitHub App** is selected under **Pipeline**
** If you see a btn:[Connect] button, select it and follow instructions to install the GitHub App for your org.
** Select the same repository as the project you are building
. Select btn:[Save]

[#create-a-new-trigger]
== 3. Create a new trigger

Next, create a trigger for your pipeline.

. Following from the previous step, select **Triggers** in the sidebar
+
. Select btn:[Add Trigger]
. Select **GitHub App** in the dropdown menu
. Select btn:[Next]
. Complete the required form fields:
** Give your trigger a descriptive name
** Select your project repository from the dropdown
** Choose your new pipeline from the "Choose config to run" menu
. Select btn:[Save]

[#conclusion]
== Conclusion

You have now successfully set up multiple configuration files for your project on CircleCI. Each configuration file will trigger a separate pipeline on the configured trigger events. Push a commit to your code to test this out. You should see both pipelines trigger in the CircleCI web app Pipelines page.

NOTE: **GitHub OAuth preview** If you use the btn:[Trigger Pipeline] in the CircleCI web app, you will only trigger your original GitHub OAuth app pipeline, not the second GitHub App integrated pipeline you created by following the steps on this page. To trigger both you will need to push to your code repository.
