= Using the Linux VM execution environment
:contentTags: {"platform"=>["Cloud", "Server v4.x", "Server v3.x"]}
:description: Learn how to configure a your jobs to run in the Linux VM execution environment using the machine executor.
:experimental:
:icons: font
:page-layout: classic-docs
:page-liquid:

You can run your jobs in the Linux VM (virtual machine) execution environment by using the machine executor and specifying a Linux image. Using the machine executor runs your jobs in a dedicated, ephemeral VM.

Using the machine executor gives your application full access to OS resources and provides you with full control over the job environment. This control can be useful in situations where you need full access to the network stack, for example, to listen on a network interface, or to modify the system with `sysctl` commands.

To use the machine executor, use the xref:configuration-reference#machine[`machine` key] in your job configuration and specify an image:

[NOTE]
====
The use of `machine: true` is deprecated when using **CircleCI cloud**. You must specify an image to use.

`machine: true` **is** supported when using:

* Self-hosted runners
* When using the machine executor on CircleCI server
====

[.tab.machineblock.Cloud]
--
[,yaml]
----
version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    resource_class: large
----
--

[.tab.machineblock.Server]
--
[,yaml]
----
version: 2.1
jobs:
  my-job:
    machine: true
    resource_class: large
----
--

You can view the list of available images xref:configuration-reference#available-linux-machine-images[in the docs Configuration Reference], or on the link:https://circleci.com/developer/images?imageType=machine[Developer Hub]. If you are working on an installation of CircleCI server, you will notice in the example above the syntax is slightly different, and the available Linux images are managed by your system administrator.

[#available-linuxvm-resource-classes]
== Available LinuxVM resource classes

{% include snippets/machine-resource-table.adoc %}

[#view-resource-usage]
=== View resource usage

{% include snippets/resource-class-view.adoc %}

[#pre-installed-software]
== Pre-installed software

The most up to date list of pre-installed software can be found on the link:https://discuss.circleci.com/tag/machine-images[Discuss] page.

If you are already using an image and would like to verify the all the packages that come pre-installed, you can run the `apt list --installed` command as a step, like in the example below:

[,yaml]
----
version: 2.1
...
jobs:
  whats-installed:
    machine: # executor type
      image: ubuntu-2004:2022.07.1
    steps:
      - run: apt list --installed
...
----

Additional packages can be installed with `sudo apt-get install <package>`. If the package in question is not found, `sudo apt-get update` may be required before installing it.

[#use-machine-with-docker]
== Use machine with Docker

Using the machine executor also means that you get full access to the Docker process. This allows you to run privileged Docker containers and build new Docker images.

The following example uses an image and enables xref:docker-layer-caching#[Docker layer caching] (DLC) which is useful when you are building Docker images during your jobs.

[,yaml]
----
machine:
  image: ubuntu-2004:202104-01
  docker_layer_caching: true    # default - false
----

[#using-machine-and-ip-ranges]
== Using machine and IP ranges

The IP range `192.168.53.0/24` is reserved by CircleCI for internal use on the machine executor. This range should not be used in your jobs.

[#next-steps]
== Next steps

To find out about migrating a project from using the Docker executor to using `machine`, see the xref:docker-to-machine#[Executor Migration from Docker to Machine] document.
