---
description: "A how to guide for using CircleCI dynamic configuration."
contentTags:
  platform:
    - Cloud
    - Server v4.x
    - Server v3.x
  document-type:
    - How-to
---
= Using dynamic configuration
:page-layout: classic-docs
:page-liquid:
:icons: font
:experimental:

This page covers the configuration requirements for some basic dynamic configuration examples. The following examples are provided below:

- <<a-basic-example>>. In this example, a script is used to generate a YAML configuration file. The continuation orb is used to continue the pipeline using the generated configuration.
- <<execute-specific-workflows-or-steps-based-on-which-files-are-modified>>

== Prerequisites

* This section assumes you have already read the xref:dynamic-config#[Dynamic Configuration] page
* If your project was created before December 1st 2023, enable dynamic configuration in your xref:dynamic-config#enable-dynamic-config[project settings]

[#a-basic-example]
== Continue a pipeline with a dynamically generated configuration file

The following is a basic example using CircleCI's dynamic configuration feature.

In this example, we assume that a `generate-config` script already exists. The script outputs a new configuration YAML based on some type of work it performs, for example, inspecting `git` history or pipeline values that get passed to it, or anything else you might do from inside a xref:configuration-reference#jobs[`job`].

[source,yaml]
----
version: 2.1

# define this file as the setup phase of your dynamic configuration
setup: true

# invoke the continuation orb to make the continuation/continue command available
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run command to run script to generate YAML config
          name: Generate config
          command: |
            ./generate-config > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue the pipeline

workflows:
  my-setup-workflow:
    jobs:
      - setup
----

In the above configuration, we:

* **Line 4**: Add the line `setup: true` to the top-level of our config, to designate it for use of CircleCI's dynamic configuration feature.
* **Line 8**: Invoke the `continuation` orb so we can use it.
* **Lines 11-20**: Define a job called `setup` that uses the default xref:executor-intro#[`executor`] provided by the `continuation` orb as an . This job:
** Calls the xref:configuration-reference#checkout[`checkout`] step to checkout code from the configured repository.
** Calls the xref:configuration-reference#run[`run`] step to execute the existing `generate-config` script, so we can pass its output to the `continue` job of the `continuation` orb.
** Continues running the pipeline based on what configuration is provided to the required `configuration_path`.
* **Line 25**: We call the `setup` job defined above as a part of our `workflow`.

CAUTION: Only one workflow that includes a continuation is allowed per pipeline. To adhere to this you can either only configure a single continuation workflow, or you can use xref:configuration-reference#using-when-in-workflows[conditional logic] to ensure only one will run in a pipeline. This setup-workflow has access to a one-time-use token to create more workflows. The setup process does not cascade, therefore subsequent workflows in the pipeline cannot launch their own continuations.

For a more in-depth explanation of what the `continuation` orb does, review the orb's source code in the link:https://circleci.com/developer/orbs/orb/circleci/continuation?version=0.1.2[CircleCI developer hub].

[#execute-specific-workflows-or-steps-based-on-which-files-are-modified]
== Execute specific `workflows` or `steps` based on which files are modified

Your project may benefit from the ability to conditionally run some configuration based upon changes made to a specific set of files. Dynamically deciding the work to do in a pipeline based on the location of changes is beneficial when your code/microservices are stored in a monorepo, or a single repository. Without this ability, using _static_ configuration, each time a change is made to any file, all jobs and workflows would run even if they are unrelated to the actual change being made.

Use the link:https://circleci.com/developer/orbs/orb/circleci/path-filtering[path filtering orb] to help simplify the process of using dynamic configuration based on the paths to changed files.

Consider a monorepo structure, as follows:

[source,shell]
----
.
├── .circleci
│   ├── config.yml
│   └── continue_config.yml
├── service1
│   ├── Service1.java
├── service2
│   ├── Service2.java
├── tests
│   ├── IntegrationTests.java
----

An example implementation of CircleCI's dynamic configuration for this structure is provided in the following `config.yml` and `continue_config.yml`:

[#config]
=== config.yml

Your `config.yml` file defines the initial setup phase of the dynamic configuration. In this example the path filtering orb is used to map file paths with pipeline parameters. If a change is made to a file matching a path regex, the corresponding parameter is set to the given value. These pipeline parameters are then passed to the continuation configuration and are used in the workflows conditional logic setup to determine which jobs should run.

The path filtering orb uses the link:https://circleci.com/developer/orbs/orb/circleci/continuation[continuation orb] under the hood to continue the pipeline with the modified parameters. The configuration passed using the continuation orb is described in the next section.

[source,yaml]
----
version: 2.1

# define this file as the setup phase of your dynamic configuration
setup: true

# use the path-filtering orb to continue a pipeline based on
# the path of an updated set of files
orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  always-run:
    jobs:
      # the path-filtering/filter job determines which pipeline
      # parameters to update.
      - path-filtering/filter:
          name: check-updated-files
          # 3-column, whitespace-delimited mapping. One mapping per
          # line:
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            service1/.* run-build-service-1-job true
            service2/.* run-build-service-2-job true
          base-revision: main
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete.
          config-path: .circleci/continue_config.yml # this is the default so not actually required but left in to illustrate options
----

[#continueconfig]
=== continue_config.yml

This configuration file is our _continuation configuration_ that is run once the initial `config.yml` finishes executing the `path-filtering/filter` job. The continuation configuration takes the updated pipeline parameters, which were changed based on the path to any changes in a commit, and uses them to conditionally run workflows.

[source,yaml]
----
version: 2.1

orbs:
  maven: circleci/maven@1.2.0

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-service-1-job:
    type: boolean
    default: false
  run-build-service-2-job:
    type: boolean
    default: false

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job. In this example all jobs are preconfigured in the Maven orb
workflows:
  # when pipeline parameter run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  service-1:
    when: << pipeline.parameters.run-build-service-1-job >>
    jobs:
      - maven/test:
          name: build-service-1
          command: 'install -DskipTests'
          app_src_directory: 'service1'
  # when pipeline parameter run-build-service-2-job is true, the
  # build-service-2 job is triggered.
  service-2:
    when: << pipeline.parameters.run-build-service-2-job >>
    jobs:
      - maven/test:
          name: build-service-2
          command: 'install -DskipTests'
          app_src_directory: 'service2'
  # when pipeline parameter, run-build-service-1-job OR
  # run-build-service-2-job is true, run-integration-tests job is
  # triggered. see:
  # https://circleci.com/docs/configuration-reference/#logic-statements
  # for more information.
  run-integration-tests:
    when:
      or: [<< pipeline.parameters.run-build-service-1-job >>, << pipeline.parameters.run-build-service-2-job >>]
    jobs:
      - maven/test:
          name: run-integration-tests
          command: '-X verify'
          app_src_directory: 'tests'
----

In the above configuration, we:

* **Line 4**: Invoke the Maven orb so we can use it's preconfigured jobs
* **Lines 8-14**: Define our two boolean pipeline parameters, the same parameters we have defined in the setup phase: `run-build-service-1-job` and `run-build-service-2-job`
* Define three separate workflows to be conditionally executed based on the pipeline parameter values:
** **Lines 22-28**: The `service-1` workflow triggers the `maven/test` job on the `service-1` directory, when the pipeline parameter value mapped to run-build-service-1-job is set to `true`. This will only happen if a change was made in the `serivce-1` directory in the commit, as determined based on the path filtering in the setup phase (`config.yml`).
** **Lines 31-37**: The `service-2` workflow triggers the `maven/test` job on the `service-2` directory, when the pipeline parameter value mapped to run-build-service-2-job is set to `true`. This will only happen if a change was made in the `serivce-2` directory in the commit, as determined based on the path filtering in the setup phase (`config.yml`).
** **Lines 43-50**: The `run-integration-tests` workflow will run if the `run-build-service-1-job` or `run-build-service-2-job` pipeline parameters have been updated to `true` based on the results of the path filtering. This runs the `maven/test` job on the `tests` directory to run integration tests against the built services.
