= CircleCI Server v2.19.x What's New
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

This document provides a summary of features and product notes for the release of CircleCI Server v{serverversion}. For a full list of changes, including patch releases, refer to the https://circleci.com/server/changelog[changelog]. For a step by step guide to **upgrading** your CircleCI Server installation to v{serverversion}, see our <<updating-server#nomad-launch-configuration,upgrade guide>>.

## Requirements for Upgrading

WARNING: For AWS installs, *before upgrading* to v2.19.x, follow <<update-nomad-clients#important,this guide>> to update your nomad launch configuration.

CAUTION: If at any time your organization name has been changed, there is a <<updating-server#org-rename-script,script>> that *must* be run before stating the upgrade process. If you are already running v2.18.x, you will have run this already.

## Notes and Best Practices

* We now require a minimum 32GB of RAM for the Services Machine. 
* We made some changes to our Redis configuration in v2.18. If you have externalized Redis then you’ll need to update your configuration. Please contact your Customer Success Manager if you are upgrading from pre v2.18 to v2.19.
* We have made changes to our Postgres version and require at least postgreSQL v9.5.16. If you have externalized postgreSQL then please update to at least that version in 2.17.x before upgrading to {serverversion}.

## What's New in v2.19.02

* In the LDAP login flow we now use an anonymous form to `POST` LDAP auth state, rather than sending it as a `GET` parameter. Previously, when a user authenticated using LDAP, their username and password were sent in plaintext as part of a query parameter in a `GET` request. As requests are over HTTPS, this left usernames and passwords in request logs, etc. This issue is now fixed. 

* Optimizely and Zendesk are now removed from Server release images.

* Fixed an issue in which setting `CIRCLE_ADMIN_SERVER_HTTP_THREADS` or `CIRCLE_PUBLIC_FACING_SERVER_HTTP_THREADS` too high would prevent the frontend container from starting.

* Due to changes in the GitHub API we have removed the use of `?client_id=x&client_secret=y` for GitHub, and GHE versions 2.17 and later.

* Fixed an issue that was causing intermittent failures to spin up VMs with DLC in use.

* Fixed an issue that was preventing the customization of proxy settings for Docker containers. See the https://circleci.com/docs/2.0/proxy/#nomad-client-proxy-setup[Nomad Client Proxy] and https://circleci.com/docs/2.0/customizations/#service-configuration-overrides[Service Configuration Overrides] guides for more infomation.

* Fixed a bug that was preventing job steps for non-failing builds being logged when proxy settings were used for the job container.

* Removed legacy TLS versions 1.0 and 1.1.

* Fixed a `statsd` configuration issue that meant some services were not emitting Telegraf metrics.

## What's New in v2.19.01

* Fixed a bug that was preventing some customers from upgrading due to a schema change in one of our library dependencies.

* Fixed a bug that was preventing some customers from inspecting builds via SSH due to a logic change in our build agent.

## What's New in v2.19

* You can now customize resource classes for your installation to provide developers with https://circleci.com/docs/2.0/optimizations#resource-class[CPU/RAM options] for the Jobs they configure. For more information https://circleci.com/docs/2.0/customizations#resource-classes[see our guide to customizing resource classes in Server v2.19].

* CircleCI Server installations on AWS can now be https://github.com/circleci/enterprise-setup#configuration[configured to work on GovCloud].

* The image used to run the RabbitMQ server has been updated to fix vulnerabilities.

## Known Issues

* **If you are using an HTTP proxy for your installation, upgrade to v2.19.02**. We had a known issue around job step logging and docker commands customization that made pre-2.19.2 releases incompatible with an HTTP proxy setup of CircleCI Server.

* The first user to access a CircleCI Server installation should be granted admin access. Currently, there is an issue preventing this from happening when LDAP authentication is in use. Follow https://circleci.com/docs/2.0/authentication#grant-admin-access-to-user[this guide] for a workaround.

* If any changes have been made to your networking configuration you may need to run the following steps to ensure you can use SSH to inspect your builds:
** On the Services Machine, create `/etc/circleci/public-ipv4`
** This file should contain the private IP of the nomad client
