---
contentTags:
  platform:
  - Cloud
  - Server v4.x
  - Server v3.x
---
= Project values and variables
:description: A list of all built-in variables for your CircleCI projects.
:page-layout: classic-docs
:page-liquid:
:icons: font
:experimental:

This page is a reference for all built-in values available for use in your CircleCI projects.

[#built-in-environment-variables]
== Built-in environment variables

The following built-in environment variables are available for CircleCI projects. A few environment variables are available for GitHub and Bitbucket projects that have been deprecated for GitLab SaaS support. If you must continue to use those as environment variables in your GitLab pipelines, refer to the workaround described after the list below.

Environment variables are scoped at the job level. They can be used within the context of a job but do not exist at a pipeline level, therefore they cannot be used for any logic at the pipeline or workflow level.

NOTE: You cannot use a built-in environment variable to define another environment variable. Instead, you must use a `run` step to export the new environment variables using `BASH_ENV`. For more details, see xref:set-environment-variable#set-an-environment-variable-in-a-shell-command[Setting an Environment Variable in a Shell Command].

include::../_includes/snippets/built-in-env-vars.adoc[]

[#pipeline-values]
== Pipeline values

Pipeline values are available to all pipeline configurations and can be used without previous declaration. Pipeline values are scoped at the pipeline level. They are interpolated at compilation time, not workflow/job runtime.

NOTE: For GitHub users, refer to the xref:github-apps-integration#[GitHub App integration] or xref:github-integration#[GitHub OAuth app integration] guides to check which integration type applies to you.

include::../_includes/snippets/pipeline-values.adoc[]

For example:

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: ~/main
    steps:
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL
```

When using the above method to set the variables in the `environment` key, note that if the pipeline variable is empty it will be set to `<nil>`. If you need an empty string instead, xref:set-environment-variable#set-an-environment-variable-in-a-shell-command[set the variable in a shell command].
