---
version:
- Server v4.x
- Server Admin
---
= Phase 4 - Configuring Nomad Clients
:page-layout: classic-docs
:page-liquid:
:page-description: How to configure Nomad clients to run with CircleCI Server in an air-gapped environment.
:icons: font
:toc: macro
:toc-title:

CircleCI Server uses Nomad clients to perform container-based build actions. These machines will need to exist within the air-gapped environment to communicate with the CircleCI Server helm deployment.

NOTE: In the following sections, replace any sections indicated by `< >` with your details.

[#download-nomad-release]
== 1. Download the latest nomad release
Download the latest nomad release to your local machine.


[source, bash]
----
wget https://releases.hashicorp.com/nomad/1.1.2/nomad_1.1.2_linux_amd64.zip
----

== 2. Prepare the nomad binary
Unzip the downloaded file and make it executable.
[source, bash]
----
unzip nomad_1.1.2_linux_amd64.zip
chmod +x nomad
----

== 3. Copy the nomad binary
Copy the nomad binary to your air-gapped environment, and place it on each machine designated to be a Nomad client.


== 4. Configure the nomad binary on nomad clients
For each nomad client, move the binary into the `/usr/local/bin` directory, and start the nomad service.

[source, bash]
----
sudo mv nomad /var/usr/local/bin/nomad
sudo systemctl start nomad
----
