---

contentTags:
  platform:
    - Server v4.x
    - サーバー管理者
---
= 外部サービスの設定
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは、CircleCI Server 4.x で使用する以下の外部サービスの設定方法について説明します。
:icons: font
:toc: macro

:toc-title:

このページでは、CircleCI Server 4.x で使用する以下の外部サービスの設定方法について説明します。

toc::[]

[#postgresql]
== PostgreSQL

[#best-practices-for-your-postgresql]
=== PostgreSQL のベストプラクティス

NOTE: Your externalized PostgreSQL instance needs to be version 12.1 or higher.

プライマリで障害が発生した場合の復旧や、バックアップのために、PostgreSQL レプリカは 2 つ以上実行することをお勧めします。 推奨される PostgreSQL マシンの仕様は以下のとおりです。

[.table.table-striped]
[cols=6*, options="header", stripes=even]
|===
|1 日のアクティブ ユーザー数
|PostgreSQL レプリカ数
|CPU
|RAM
|ディスク
|NIC 速度

|50 名未満
|2
|8 コア
|1Gbps
|100 GB
|1 Gbps

|50 ～ 250 名
|2
|8 コア
|1Gbps
|200 GB
|1 Gbps

|250 ～ 1000 名
|3
|8 コア
|32 GB
|500 GB
|10 Gbps

|1000 ～ 5000 名
|3
|8 コア
|32 GB
|1 TB
|10 Gbps

|5000名以上
|3
|8 コア
|32 GB
|1 TB
|10 Gbps
|===

[#migrating-from-internal-postgres]
=== Migrating from an internal PostgreSQL to an externalized source

{% include snippets/server/migrate-internal-postgres-to-external.adoc %}

[#connecting-your-external-postgres]
=== Connecting your external PostgreSQL instance to CircleCI server

Once you have set up your external PostgreSQL instance, add the following to your `values.yaml` file so that your CircleCI server instance can access it.

[source,yaml]
----
postgresql:
  internal: false
  postgresqlHost: <domain> # The domain or IP address of your PostgreSQL instance
  postgresqlPort: <port> # The port of your PostgreSQL instance
----

NOTE: `postgresql.internal: false` will remove any previously deployed Postgres instance deployed internally

[tab.postgres.Create_secret_yourself]
--
シークレットを作成し、`values.yaml` に以下の値を追加します。

[source,shell]
----
kubectl create secret generic postgresql \
  --from-literal=postgres-password=<postgres-password>
----

[source,yaml]
----
postgresql:
  ...
  auth:
    username: <username>
    existingSecret: postgresql
----
--

[tab.postgres.CircleCI_creates_secret]
--
以下の内容を `values.yaml` ファイルに追加します。 CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
postgresql:
  ...
  auth:
    username: <username> # A user with the appropriate privileges to access your PostgreSQL instance.

    password: <password> # The password of the user account used to access your PostgreSQL instance.
----
--

The changes will take effect upon running `helm install/upgrade`. If you are completing a migration to an externalized Postgres instance then when you perform `helm upgrade`, the scaled down pods will be scaled back to their replica numbers as defined by your `values.yaml`.

[#backing-up-postgresql]
=== Back up PostgreSQL

PostgreSQL provides official documentation for backing up and restoring your PostgreSQL 12 install, which can be found link:https://www.postgresql.org/docs/12/backup.html[here].

CircleCI では、以下を行っていただくよう強くお勧めしています。

* Take daily backups
* Keep at least 30 days of backups
* Use encrypted storage for backups as databases might contain sensitive information
* Perform a backup before each upgrade of CircleCI server

[#mongodb]
== MongoDB

NOTE: ご自身の Mongo DB インスタンスを使用する場合は、バージョン 3.6 以上である必要があります。

[#migrating-from-internal-mongodb]
=== Migrating from an internal MongoDB to an externalized source

{% include snippets/server/migrate-internal-mongo-to-external.adoc %}

[#connecting-your-external-mongodb]
=== Connecting your external MongoDB instance to CircleCI server

Once you have configured your external MongoDB instance, add the following to your `values.yaml` file to connect your CircleCI server instance.

[source,yaml]
----
mongodb:
  internal: false
  hosts: <hostname:port> # this can be a comma-separated list of multiple hosts for sharded instances
  ssl: <ssl-enabled>
  # If using an SSL connection with custom CA or self-signed certs, set this
  # to true
  tlsInsecure: false
  # Any other options you'd like to append to the MongoDB connection string.
  # Format as query string (key=value pairs, separated by &, special characters
  # need to be URL encoded)
  options: <additional-options>
  auth:
    database: <authentication-source-database
    mechanism: SCRAM-SHA-1
----

[tab.mongo.Create_secret_yourself]
--
シークレットを作成し、`values.yaml` に以下の値を追加します。

[source,shell]
----
kubectl create secret generic mongodb \
--from-literal=mongodb-root-password=<root-password> \
--from-literal=mongodb-password=dontmatter
----

[source,yaml]
----
mongodb:
  ...
  auth:
    ...
    username: <username>
    existingSecret: mongodb
----
--

[tab.mongo.CircleCI_creates_secret]
--
以下の内容を `values.yaml` ファイルに追加します。 CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
mongodb:
  ...
  auth:
    ...
    username: <username>
    rootPassword: <root-password>
    password: <password>
----
--

The changes will take effect upon running `helm install/upgrade`. If you are completing a migration to an externalized MongoDB instance then when you perform `helm upgrade`, the scaled down pods will be scaled back to their replica numbers as defined by your `values.yaml`.