---

version:
- Server v4.x
- サーバー管理者
---
= 内部データベースのボリューム拡張
:page-layout: classic-docs
:imagesdir: ../assets/img/docs/
:page-liquid:
:icons: font
:toc: macro

:toc-title:

toc::[]

[#overview]
== 概要

If you have chosen to deploy either of the CircleCI databases (MongoDB or PostgreSQL) within the cluster, rather than externally provisioning these databases, there may come a point at which the storage space initially made available to these databases is no longer sufficient. Kubernetes クラスタの内部データベースでは、永続的なストレージとして https://kubernetes.io/docs/concepts/storage/persistent-volumes/[永続ボリューム] を使用しています。 ボリュームのサイズは、PVC（永続ボリューム要求）によって決定されます。 この PVC は、クラスタ内の Node に使用できる容量に基づいてストレージスペースを要求します。

ここでは、内部でデプロイしたデータベース用のスペースを増やすために PVC を増やす手順を説明します。 この操作には、データベースポッドを再起動する必要がない限り、ダウンタイムは生じません。

NOTE: 永続ボリュームを拡張しても、Node に接続されているストレージのサイズには影響しません。 Node ストレージの拡張は、ご使用のクラウドプロバイダーの制限範囲内で可能です。 クラスタの Node に接続されたストレージを拡張する方法の詳細については、ご使用のクラウドプロバイダーのドキュメントを参照してください。

[#resizing-persistent-volume-claims]
== 永続ボリューム要求のサイズ変更

Below are the steps detailing how to resize the persistent volume claims for PostgreSQL and MongoDB. この操作の前後で、要求のサイズやデータベースに利用できるディスク容量を確認します。

NOTE: As a precaution, it is always a good idea to link:/docs/server/operator/backup-and-restore/[create a backup of your cluster] first.

[#step-0-confirm-current-volume-size]
=== ステップ 0: 現在のボリュームサイズの確認

デフォルトでは、内部のデータベースが使用する永続ボリューム要求の容量は 8Gi です。 ただし、この初期値は最初のデプロイ時に helm-value ファイルから設定できます。 `kubectl get pvc <pvc-name>` コマンドにより、永続ボリューム要求のサイズを確認することができます。

For PostgreSQL:

[source,bash]
----
circleci-user ~ $ kubectl get pvc data-postgresql-0
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-postgresql-0   Bound    pvc-c2a2d97b-2b7d-47d3-ac77-d07c76c995a3   8Gi        RWO            gp2            1d
----

MongoDB の場合:

[source,bash]
----
circleci-user ~ $ kubectl get pvc datadir-mongodb-0
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-mongodb-0   Bound    pvc-58a2274c-31c0-487a-b329-0062426b5535   8Gi        RWO            gp2            1d
----

データベースのデータディレクトリのサイズを確認することで、この容量が確保されているかも確認できます。

For PostgreSQL, the directory is `/bitnami/postgresql`. 以下のコマンドでサイズの確認ができます。

[source,bash]
----
circleci-user ~ $ kubectl exec postgresql-0 -- df -h /bitnami/postgresql
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme4n1    7.8G  404M  7.4G   3% /bitnami/postgresql
----

MongoDB の場合、ディレクトリは `/bitnami/mongodb` です。

[source,bash]
----
circleci-user ~ $ kubectl exec mongodb-0 -- df -h /bitnami/mongodb
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme1n1    7.8G  441M  7.4G   3% /bitnami/mongodb
----

上記の例では、容量は 8Gi のままです。 次のステップで、これを 10 Gi に増やす方法を紹介します。

[#step-1-confirm-volume-expansion-is-allowed]
=== ステップ 1: ボリュームの拡張が可能かどうかを確認する

まず、クラスタでボリューム拡張が許可されていることを確認します。

[source,bash]
----
circleci-user ~ $ kubectl get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  1d
----

ご覧の通り、デフォルトのストレージクラスではボリュームの拡張ができません。 しかし、 `kubectl patch` コマンドでこれを変更することができます。

[source,bash]
----
circleci-user ~ $ kubectl patch sc gp2 -p '{"allowVolumeExpansion": true}'
storageclass.storage.k8s.io/gp2 patched
circleci-user ~ $ kubectl get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                  1d
----

ここからは、ボリュームを増やしていきましょう。

[#step-2-delete-the-databases-stateful-set]
=== ステップ 2: データベースのステートフルセットを削除する

このステップでは、データベースポッドを制御するステートフルセットを削除します。 以下のコマンドは、ポッドを削除することなく、参照されるデータベースのステートフルセットを削除します。 ポッド自体を削除してしまうとダウンタイムが発生してしまうので、お勧めしません。 次のステップでは、ステートフルセットを再びデプロイします。 ボリュームを拡張するデータベースによって、どちらか一方または両方のステートフルセットを削除します。 ここでは、 `--cascade=orphan` フラグが最も重要です。

For PostgreSQL:

[source,bash]
----
kubectl delete sts postgresql --cascade=orphan
----

MongoDB の場合:

[source,bash]
----
kubectl delete sts mongodb --cascade=orphan
----

[#step-3-update-the-size-of-the-databases-pvc]
=== ステップ 3: データベースの PVC サイズを更新する

ステートフルセットが削除されたので、永続ボリューム要求のサイズを 10Gi に増やすことができます。

For PostgreSQL:

[source,bash]
----
kubectl patch pvc data-postgresql-0 -p '{"spec": {"resources": {"requests": {"storage": "10Gi"}}}}'
----

MongoDB の場合:

[source,bash]
----
kubectl patch pvc datadir-mongodb-0 -p '{"spec": {"resources": {"requests": {"storage": "10Gi"}}}}'
----

[#step-4-update-kots-admin-console-with-the-new-pvc-size]
=== ステップ 4: helm-value ファイルを新しい PVC サイズに更新する

Now you need to upgrade the server installation by modifying the PVC size in the helm-value file to persist your changes. In the helm-value file, you will update the values for your PVC size to 10Gi as shown below.

* **PostgreSQL**
+
[source,yaml]
----
postgresql:
  persistence:
    size: 10Gi
----
* **MongoDB**
+
[source,yaml]
----
mongodb:
  persistence:
    size: 10Gi
----

変更内容を保存し、デプロイします。 これにより、先ほど削除したステートフルセットが再び作成されますが、次のリリースまで継続される新しい PVC サイズに変わっています。

[source,yaml]
----
helm upgrade <release-name> -n <namespace> -f < helm-value-file> <chart-dictectory>
----

[#step-5-validate-new-volume-size]
=== ステップ 5: 新しいボリュームサイズを検証する

デプロイ後にデータベースに割り当てられたデータディレクトリのサイズを検証することができます。

For PostgreSQL the directory is `/bitnami/postgresql`.

[source,bash]
----
circleci-user ~ $ kubectl exec postgresql-0 -- df -h /bitnami/postgresql
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme4n1    9.8G  404M  9.4G   5% /bitnami/postgresql
----

MongoDB の場合、ディレクトリは `/bitnami/mongodb` です。

[source,bash]
----
circleci-user ~ $ kubectl exec mongodb-0 -- df -h /bitnami/mongodb
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme1n1    9.8G  441M  9.3G   5% /bitnami/mongodb
----

ご覧のように、ディレクトリのサイズが拡張されています。

これらの手順を完了する際、新しいポッドでサイズ変更されたボリュームが期待通りに表示された場合は、下記の `kubectl describe` コマンドで確認することをお勧めします。 サイズ変更に失敗する場合がありますが、`kubectl describe` からの出力でイベントを表示する方法しかありません。

For PostgreSQL:

[source,bash]
----
kubectl describe pvc data-postgresql-0
----

MongoDB の場合:

[source,bash]
----
kubectl describe pvc datadir-mongodb-0
----

成功すると、以下の例のように出力されます。

[source,shell]
----
Events:
Type    Reason                      Age   From     Message

Normal  FileSystemResizeSuccessful  19m   kubelet  MountVolume.NodeExpandVolume succeeded for volume "pvc-b3382dd7-3ecc-45b0-aeff-45edc31f48aa"
----

失敗すると、以下の例のように出力されます。

[source,shell]
----
Warning  VolumeResizeFailed  58m   volume_expand  error expanding volume "circleci-server/datadir-mongodb-0" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-08d0861715c313887 with VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
status code: 400, request id: 3bd43d1e-0420-4807-9c33-df26a4ca3f23
Normal   FileSystemResizeSuccessful  55m (x2 over 81m)  kubelet        MountVolume.NodeExpandVolume succeeded for volume "pvc-29456ce2-c7ff-492b-add4-fcf11872589f"
----

[#troubleshooting]
== トラブルシューティング

これらのステップを実行しても、データディレクトリに割り当てられたディスクサイズが拡張しない場合は、データベースポッドを再起動する必要があります。 この場合、データベースの再起動に伴い 1～5分程度のダウンタイムが発生します。 以下のコマンドでデータベースを再起動することができます。

For PostgreSQL:

[source,bash]
----
kubectl rollout restart sts postgresql
----

MongoDB の場合:

[source,bash]
----
kubectl rollout restart sts mongodb
----