---

contentTags:
  platform:
    - Server v4.x
    - サーバー管理者
---
= VM サービスを使った仮想マシンの管理
:page-layout: classic-docs
:page-liquid: CircleCI Server の VM サービスにより、Machine Executor (Linux および Windows イメージ) とリモート Docker のジョブの実行方法を制御できます。
:page-description:
:icons: font
:toc: macro

:toc-title:

VM サービスにより、 https://circleci.com/docs/configuration-reference/#machine[`Machine`] Executor と https://circleci.com/docs/building-docker-images[リモート Docker] ジョブの実行方法を制御できます。

このセクションでは、VM サービスで設定可能なオプションについて説明します。 仮想マシンを事前に拡張する方法の詳細については、デフォルトの `values.yaml` ファイルを参照してください。

toc::[]

CAUTION: CircleCI Server のコアサービスとビルドサービスの設定と検証が完了するまで、これらのオプションはデフォルトのままにしておくことをお勧めします。 VM サービスの設定手順は、 link:/docs/server/installation/phase-3-execution-environments/#aws-vm-service[AWS]と link:/docs/server/installation/phase-3-execution-environments/#gcp-authentication[GCP] のインストールガイドに記載されています。

[#vm-provider]
== VM プロバイダー

下記は、AWS または GCP の VM プロバイダー用の設定オプションです。

[#aws]
=== AWS

`values.yaml` ファイルに、AWS EC2 と連携するように VM サービスを設定するセクションがあります。 インストールの間に、セキュリティグループと認証のセットアップを行います。 詳細については、link:/docs/server/installation/phase-3-execution-environments/#aws-vm-service[インストールステップ 3: 実行環境] を参照してください。

ここではインストール後の VM サービスの設定オプションについて説明します。

[#windows-image-aws]
==== Windows イメージ

Windows Executor が必要な場合は、`values.yaml` ファイルに AMI ID を記述します。 Windows イメージの作成には、link:https://github.com/CircleCI-Public/circleci-server-windows-image-builder[CircleCI Server Windows イメージビルダー] を使用します。

[source,yaml]
----
vm_service:
  providers:
    ec2:
      ...
      windowsAMI: "<my-windows-ami>"
----

[#linux-image-aws]
==== 代替の Linux VM イメージ

Linux Machine Executor にカスタム AMI を指定する場合、`values.yaml` ファイルに AMI ID を記述します。 Linux イメージの作成には、link:https://github.com/CircleCI-Public/circleci-server-linux-image-builder[CircleCI Server Windows イメージビルダー] を使用します。

[source,yaml]
----
vm_service:
  providers:
    ec2:
      ...
      linuxAMI: "<my-linux-ami>"
----

[#default-aws-ami-lists]
==== デフォルトの AWS AMI リスト

デフォルトの Server v4.x 用の AMI は Ubuntu 22.04 に基づいています。

[#x86-ami-list]
===== x86 AMI リスト

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|地域
|AMI

|`us-east-1`
|`ami-03dc54f7559144972`

|`eu-central-1`
|`ami-0575d605472840942`

|`ap-south-1`
|`ami-047ef6196620f56ca`

|`ap-southeast-2`
|`ami-0521f8d70ef9dbd24`

|`ap-southeast-1`
|`ami-0ef0354f4eb3b7428`

|`eu-central-1`
|`ami-0a8286fff7b5ed33a`

|`eu-west-1`
|`ami-093618a1d0185f9e8`

|`eu-west-2`
|`ami-08f00d41b17d3ea0a`

|`sa-east-1`
|`ami-064b0bfe97e6ec04c`

|`us-east-2`
|`ami-068cb131f91632f12`

|`us-west-1`
|`ami-0a4b7cf088a798be3`

|`us-west-2`
|`ami-018e05f98628cf5e5`

|`ap-northeast-1`
|`ami-06f32ec6aeecbeaa6`

|`ap-northeast-2`
|`ami-084c1abb1e8dabffd`

|`eu-west-3`
|`ami-09b3e24bccae3252f`

|`us-east-1`
|`ami-0de525cac9ac9bea8`

|`us-gov-west-1`
|`ami-02abf947586cae56b`
|===

[#arm-ami-list]
===== Arm AMI リスト

[.table.table-striped]
[cols=2*, options="header", stripes=even]
|===
|地域
|AMI

|`us-east-1`
|`ami-0b11ce74f44e45578`

|`eu-central-1`
|`ami-07400e987dd82901d`

|`ap-south-1`
|`ami-072fe819d7b94b095`

|`ap-southeast-2`
|`ami-0510826f7f3a83b3e`

|`ap-southeast-1`
|`ami-0e5b703665f3e4517`

|`eu-central-1`
|`ami-045ea67b0f35ef1ef`

|`eu-west-1`
|`ami-044ac39c87438d89d`

|`eu-west-2`
|`ami-0a399817fbbb240e4`

|`sa-east-1`
|`ami-0ebc0e64fb943e191`

|`us-east-2`
|`ami-01f7dc2f8590b1611`

|`us-west-1`
|`ami-085fb1dd323aa02c7`

|`us-west-2`
|`ami-0e5ea38c131f05c8f`

|`ap-northeast-1`
|`ami-02c8fac0dbbbad74f`

|`ap-northeast-2`
|`ami-022e2eacee7328cca`

|`us-east-1`
|`ami-0bb797dcfa52ce04d`

|`us-gov-west-1`
|`ami-0ab175883ff460b17`
|===

[#gcp]
=== GCP

`values.yaml` ファイルに、GCP と連携するように VM サービスを設定するセクションがあります。 インストールの間に、セキュリティグループと認証のセットアップを行います。 詳細については、link:/docs/server/installation/phase-3-execution-environments/#aws-vm-service[インストールステップ 3: 実行環境] を参照してください。

ここではインストール後の VM サービスの設定オプションについて説明します。

[#windows-image-gcp]
==== Windows イメージ

Windows Executor が必要な場合は、`values.yaml` ファイルに AMI ID を記述します。 Windows イメージの作成には、link:https://github.com/CircleCI-Public/circleci-server-windows-image-builder[CircleCI Server Windows イメージビルダー] を使用します。

[source,yaml]
----
vm_service:
  providers:
    gcp:
      ...
      windowsImage: "<my-windows-image>"
----

[#linux-image-gcp]
==== 代替の Linux VM イメージ

Linux Machine Executor にカスタム AMI を指定する場合、`values.yaml` ファイルに AMI ID を記述します。 Linux イメージの作成には、link:https://github.com/CircleCI-Public/circleci-server-linux-image-builder[CircleCI Server Windows イメージビルダー] を使用します。

[source,yaml]
----
vm_service:
  providers:
    gcp:
      ...
      linuxImage: "<my-linux-image>"
----

[#instance-preallocation]
== インスタンスの事前割り当て

WARNING: https://circleci.com/docs/docker-layer-caching/[Docker レイヤーキャッシュ (DLC)] を使用する場合、VM サービスインスタンスをオンデマンドでスピンアップする必要があります。 これを実現する方法は 2 つあります。 **1 つは**、事前割り当てインスタンスを使用中にする、**もう 1 つは**、リモート Docker と `マシン` 用の事前割り当てインスタンスのフィールドの両方を 0 に設定する方法です。

CAUTION: 事前割り当てインスタンスを使用する場合、インスタンスが動作不可能状態にならないように、それらのインスタンスを 1 日に 1 回切り替えるように cron ジョブがスケジュールされていることに注意してください。

常にインスタンスが事前に割り当てられるようにサーバーを設定するには、以下の `values.yaml` サンプルに示されているキーを使用します。

NOTE: オプションの全リストは、link:/docs/server/installation/installation-reference/#all-values-yaml-options[インストールのリファレンス] のページをご覧ください。

[source,yaml]
----
vm_scaler:
  # -- Number of replicas to deploy for the vm-scaler deployment.
  replicas: 1
  # -- Configuration options for, and numbers of, prescaled instances for remote Docker jobs.
  prescaled:
    - type: l1.medium
      image: docker-default
      docker-engine: true # remote Docker environment
      cron: ""
      count: 2
----

[source,yaml]
----
vm_scaler:
  # -- Number of replicas to deploy for the vm-scaler deployment.
  replicas: 1
  # -- Configuration options for, and numbers of, prescaled instances for remote Docker jobs.
  prescaled:
    - type: l1.medium
      image: default
      docker-engine: false # machine execution environment
      cron: ""
      count: 2
----

[#apply-changes]
== 変更の適用

`values.yaml` ファイルへの変更を適用します。

[source,shell,subs=attributes+]
----
namespace=<your-namespace>
helm upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version {serverversion4} -f <path-to-values.yaml>
----