---

version:
- Server v4.x
- Server Admin
---
= Managing load balancers
:page-layout: classic-docs
:page-liquid:
:page-description: Use this guide to make the frontend load balancer private.
:icons: font
:toc: macro

:toc-title:

CircleCI server uses a load balancer to manage network traffic entering and leaving the Kubernetes cluster.

The load balancer manages all traffic coming into the application. The load balancer is public by default, but can be made private.

[#make-the-frontend-load-balancer-private]
== フロントエンド ロード バランサーを非公開にする

[WARNING]
====
**Webhooks:** If you choose to make the frontend load balancer private, the following conditions must be met, depending on your VCS, for webhooks to work:

* **GitHub Enterprise** – your CircleCI server installation must be in the same internal network as GHE.
* **GitHub.com** – set up a proxy for incoming webhooks and set it as override for the webhook host URL. This setting can be found in the CircleCI app UI under **Admin Settings** > **System Settings** > **Override webhook host URL**.
====

NOTE: プライベート ロード バランサー オプションは、GKE または EKS 上の CircleCI Server でのみ使用できます。

In your values.yaml override file, set the following parameter to true. The parameter is false (public) by default.

[source,yaml]
----
nginx:
    private_load_balancers: false
----

NOTE: CircleCI Server の初回デプロイ後にこの設定を変更する場合は、Kubernetes のリクエストが新しい設定に従って新しいロード バランサーに送信されるよう古いパブリックロードバランサーの削除が必要な場合があります。