---

description: "CircleCI Server’s VM service controls how machine executor (Linux and Windows images) and Remote Docker jobs are run."
version:
- Server v4.x
- Server Admin
---
= Manage virtual machines with VM Service
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

VM service controls how https://circleci.com/docs/2.0/configuration-reference/#machine[`machine`] executor and https://circleci.com/docs/2.0/building-docker-images[Remote Docker] jobs are run.

このセクションでは、VM サービスで利用可能な設定オプションについて説明します。 Refer to the default `values.yaml` file for details on how to pre-scale virtual machines.

toc::[]

CAUTION: CircleCI Server のコアサービスとビルドサービスの設定と検証が完了するまで、これらのオプションはデフォルトのままにしておくことをお勧めします。 Steps to set up VM service are provided in the installation guide for https://circleci.com/docs/2.0/server/installation/phase-3-execution-environments/#aws[AWS] and https://circleci.com/docs/2.0/server/installation/phase-3-execution-environments/#gcp[GCP].

WARNING: If https://circleci.com/docs/2.0/docker-layer-caching/[Docker Layer Caching (DLC)] is used, VM Service instances need to be spun up on demand. For this to happen, **either** ensure any preallocated instances are in use, **or** set both remote Docker and `machine` preallocated instance fields to `0`.

CAUTION: 事前割り当てインスタンスを使用する場合、インスタンスが動作不可能状態にならないように、それらのインスタンスを 1 日に 1 回切り替えるように cron ジョブがスケジュールされていることに注意してください。

[#vm-provider]
== VM プロバイダー

下記は、AWS または GCP の VM プロバイダー用の設定オプションです。

[#aws]
=== AWS

You will need to add a section to your `values.yaml` file to configure VM Service to work with AWS EC2.

[#aws-authentication]
==== 認証

One of the following options is required:

* Either, select "IAM Keys" and provide:
** *Access Key ID* (required): https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Access Key ID] for EC2 access.
** *Secret Key* (required): https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Secret Key] for EC2 access.
+
NOTE: The Access Key and Secret Key used by VM Service differs from the policy used by object storage in the previous section.
* Or, select "IAM role" and provide:
** *Role ARN* (required):
+
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html[Role ARN for Service Accounts] (Amazon Resource Name) for EC2 access.

[source,yaml]
----
vm_service:
  providers:
    ec2:
      enabled: true
      region: <region>
      # Subnets must be in the same availability zone
      subnets:
      - <subnet-id>
      securityGroupId: <security-group-id>

      # Authenticate with IAM access keys
      accessKey: <access-key>
      secretKey: <secret-key>
      # or IRSA (IAM roles for service accounts)
      irsaRole: <role-arn>
----

[#default-aws-ami-list]
==== デフォルトの AWS AMI リスト

The default AMIs for server v4.x are based on Ubuntu 20.04.

----
"us-east-1" "ami-04f249339fa8afc90"
"ca-central-1" "ami-002f61fb4f6cd4f04"
"ap-south-1" "ami-0309e6438340ff3f5"
"ap-southeast-2" "ami-03ac956e1d298b76a"
"ap-southeast-1" "ami-0272b002478c96552"
"eu-central-1" "ami-07266a91e4ef7e3e8"
"eu-west-1" "ami-0bc8a965f9ae82e44"
"eu-west-2" "ami-0bcbed1cffe3866c2"
"sa-east-1" "ami-05291e231356c0387"
"us-east-2" "ami-08735066168c5c8e9"
"us-west-1" "ami-035e0e862838fcb21"
"us-west-2" "ami-0b4970c467d8baaef"
"ap-northeast-1" "ami-0b9233227f60abc2c"
"ap-northeast-2" "ami-08e7a9df6ab2f6b9d"
"eu-west-3" "ami-07f0d51c7621f0c39"
"us-gov-east-1" "ami-0f68718afd37587ae"
"us-gov-west-1" "ami-8e2106ef"
----

[#gcp]
=== GCP

You will need to add a section to your `values.yaml` file to configure VM Service to work with Google Cloud Platform (GCP).

[#gcp-authentication]
==== 認証

TIP: VM サービス専用の一意のサービス アカウントを作成することをお勧めします。 コンピューティング インスタンス管理者 (ベータ版) ロールは、VM サービスを運用するための広範な権限を持っています。 If you wish to make permissions more granular, you can use the
https://cloud.google.com/compute/docs/access/iam#compute.instanceAdmin[Compute Instance Admin (beta) role] documentation as reference.

Choose one of the following options:

* If you choose to use *GCP IAM Workload Identity*, use the VM service account email address (`service-account-name`@`project-id`.iam.gserviceaccount.com ) which you created link:/docs/server/installation/phase-3-execution-environments[here] in point 2 and 3 for the `workloadIdentity` field below.
* If you choose to use a *GCP Service Account JSON file*, use the contents of your https://cloud.google.com/iam/docs/service-accounts[service account JSON file] for `service-account` below.

[source,yaml]
----
vm_service:
  enabled: true
  replicas: 1
  providers:
    gcp:
      enabled: false
      project_id: <project-id>
      network_tags:
      - circleci-vm
      - <your-network>
      zone: <zone>
      network: <network>
      subnetwork: <subnetwork>

      service_account: <service-account-json>
      # OR
      workloadIdentity: ""  # Leave blank if using JSON keys of service account else service account email address
----