---

version:
- Server v4.x
- Server Admin
---
= Operator overview
:page-layout: classic-docs
:page-liquid:
:page-description: Learn about the various tasks and tools involved in administering an installation of CircleCI server.
:icons: font
:toc: macro

:toc-title:

This guide contains information for CircleCI server operators, or those responsible for ensuring CircleCI server is running properly through maintenance and monitoring. Before reading this operator guide, ensure you have read the https://circleci.com/docs/2.0/server/overview/circleci-server-v4-overview[CircleCI Server v4.x Overview].

CircleCI server schedules CI/CD jobs using the https://www.nomadproject.io/[Nomad] scheduler. The Nomad Server (control plane) runs inside the Kubernetes cluster, while Nomad clients are provisioned outside the cluster. Nomad クライアントが、Nomad コントロールプレーン、出力プロセッサ、VM サービスにアクセスできる必要があります。

CircleCI server can run Docker jobs on the Nomad clients, and also in dedicated virtual machines. These VM jobs are controlled by the Nomad clients, therefore the Nomad clients must be able to access the VMs on port 22 for SSH and port 2376 for link:https://circleci.com/docs/configuration-reference#setupremotedocker[remote Docker jobs].

ジョブのアーティファクトと出力は、Nomad ジョブからオブジェクト ストレージ (S3、GCS、またはその他のサポートされているオプション) に直接送信されます。

オブジェクト ストレージには、監査ログやアプリケーションのその他のアイテムも保存されます。そのため、Kubernetes クラスタと Nomad クライアントの両方がオブジェクト ストレージにアクセスできる必要があります。

toc::[]

[#execution-environment]
== 実行環境

CircleCI server v4.x uses Nomad as the primary job scheduler. Refer to our <<introduction-to-nomad-cluster-operation#,Introduction to Nomad Cluster Operation>>
to learn more about the job scheduler and how to perform basic client and cluster operations.

CircleCI Nomad clients automatically provision compute resources according to the executors configured for each job in a project’s `.circleci/config.yml` file.

[#nomad-clients]
=== Nomad クライアント

Nomadクライアントは実行後に状態を保持しないため、必要に応じてコンテナ数を増減することができます。

すべてのビルドを処理できる十分な数の Nomad クライアントが確実に実行されるようにするには、キューに入っているビルドを追跡し、必要に応じて Nomad クライアントマシンの数を増やして負荷を分散させます。 For more on tracking metrics see the <<using-metrics#,Using Metrics>> section.

If a job's resource class requires more resources than the Nomad client's instance type has available, it will remain in a pending state. Nomad クライアントのインスタンスタイプを小さいものにすればコストを削減できますが、CircleCI で使用できる Docker リソースクラスが制限されます。 Review the https://circleci.com/docs/2.0/configuration-reference#resourceclass[available resource classes] to decide what is best for you. The default instance type will run up to `xlarge` resource classes.

See the https://www.nomadproject.io/docs/install/production/requirements#resources-ram-cpu-etc[Nomad Documentation] for options for optimizing the resource usage of Nomad clients.

NOTE: Nomad クライアント マシンの最大サイズは RAM 128GB/64 CPUです。 使用する Nomad クライアントマシンのサイズを大きくしたい場合は、CircleCI のアカウント担当者にお問い合わせください。

For more information on Nomad port requirements, see the
https://circleci.com/docs/2.0/server/installation/hardening-your-cluster/[Hardening Your Cluster]
guide.

[#github]
=== GitHub

CircleCI では、GitHub または GitHub Enterprise を ID プロバイダーとして使用しています。 GitHub Enterprise can, in turn, use
https://docs.github.com/en/github-ae@latest/admin/authentication/about-identity-and-access-management-for-your-enterprise[SAML or SCIM]
to manage users from an external identity provider.

NOTE: CircleCI では、セットアップ後の URL やバックエンドの GitHub インスタンスの変更には対応していません。

以下の表に、GitHub を実行するマシンでサービス および Nomad クライアントインスタンスと通信する際に使用されるポートを示します。

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
|ソース
|ポート
|用途

|Services
|22
|Git アクセス

|Services
|80 または 443
|API アクセス

|Nomad クライアント
|22
|Git アクセス

|Nomad クライアント
|80 または 443
|API アクセス
|===

ifndef::pdf[]

[#next-steps]
== 次のステップ

* Read the <<introduction-to-nomad-cluster-operation#,Introduction to Nomad Cluster Operation>>.
+
endif::[]