---

version:
- Server v4.x
- Server Admin
---
= Troubleshooting and support
:page-layout: classic-docs
:page-liquid:
:page-description: Use this document to find troubleshooting steps if you are having problems with your CircleCI server v4.x installation.
:icons: font
:toc: macro

:toc-title:

This document describes an initial set of troubleshooting steps to take if you are experiencing problems with your CircleCI server v4.x installation. 以下の説明で問題を解決できなかった場合は、サポート バンドルを生成するか、CircleCI アカウント チームにお問い合わせください。

toc::[]

[#generate-support-bundle]
== Generate support bundle

サポート バンドルは、発生している問題を CircleCI エンジニアが診断、修正するためのものです。 通常、サポート チケットを作成する場合、サポート バンドルを提出するように求められます。

To generate a support bundle, follow the steps below.

=== 前提条件

. First, make sure circleci-server is deployed and you have access to the cluster/namespace through kubectl.

[source,bash]
----
# To check if you have access to cluster/namespace
kubectl -n <namespace> get pods
----

. Next, install link:https://krew.sigs.k8s.io/docs/user-guide/setup/install/[krew].
. Install link:https://github.com/replicatedhq/troubleshoot#support-bundle[support-bundle (kubectl plugin)] to your local development machine.

[source,bash]
----
# To install support-bundle plugin
kubectl krew install support-bundle
----

=== Generating support bundle

When ready, run the support bundle from the current directory and wait for it to finish.

[source,bash]
----
kubectl support-bundle https://raw.githubusercontent.com/CircleCI-Public/server-scripts/main/support/support-bundle.yaml
----

[#managing-pods]
== Managing pods

[verify-pod-readiness-and-status]
=== Verify pod readiness and status

NOTE: Check the `READY` column as well as `STATUS`. Even if the `STATUS` is `Running`, pods are not ready to serve user requests. 一部の Pod は、準備ができるまで多少の時間を要する場合があります。

[source,bash]
----
kubectl get pods -n <namespace>
NAME READY STATUS RESTARTS AGE
api-service-5c8f557548-zjbsj 1/1 Running 0 6d20h
audit-log-service-77c478f9d5-5dfzv 1/1 Running 0 6d20h
builds-service-v1-5f8568c7f5-62h8n 1/1 Running 0 6d20h
circleci-mongodb-0 1/1 Running 0 6d20h
circleci-nomad-0 1/1 Running 6 6d20h
----

To show only pods with a status besides `Running`, you can use the `--field-selector` option.

[source,bash]
----
kubectl get pods --field-selector status.phase!=Running -n <namespace>
NAME READY STATUS RESTARTS AGE
nomad-server 0/1 Error 0 5d22h
----

[#verify-pod-settings-and-status]
=== Verify pod settings and status

Pod の詳細な設定とステータスを確認するには、以下のコマンドを実行します。

[source,bash]
----
kubectl describe pods <pod-name> -n <namespace>
----

[#get-pod-logs]
=== Get pod logs

Pod のログを表示するには、以下のコマンドを実行します。

[source,bash]
----
kubectl logs <pod-name> -n <namespace>
----

[#restart-pods]
=== Restart pods

特定の Pod を再起動する最も簡単な方法は、その Pod を削除することです。 削除した Pod は、Kubernetes によって自動的に再作成されます。

[source,bash]
----
kubectl delete pod <pod-name> -n <name-space> --now
----

[#debug-queuing-builds]
== Debug queuing builds

For troubleshooting information on debugging queued builds, see the Server 2.x
https://circleci.com/docs/2.0/troubleshooting/?section=server-administration#debug-queuing-builds[troubleshooting] Guide.