---

version:
- Server v4.x
- サーバー管理者
---
= CircleCI Server v3 から v4.x への移行
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI Server v3.x から v4.x. に移行する方法をご確認ください。
:icons: font
:toc: macro

:toc-title:

CircleCI Server v3.x から v4.x への移行は _インプレース_ 移行です。 helm-value ファイルを生成し、そのファイルを helm コマンドで使用して CircleCI Server v3.x から v4.x へのアップグレードを行います。

移行プロセスは、まずステージング環境で試してから、本番環境で行うことをお勧めします。 ステージング環境を挟むことで、移行プロセスに対する理解を深められ、また移行完了にかかる時間を確認できます。

toc::[]

[#prerequisites]
== 前提条件

* 現在インストールされている CircleCI Server が v3.x である。
* link:/docs/ja/server/operator/backup-and-restore[バックアップと復元] ガイドの手順に従って v3.x のインスタンスのバックアップが作成してある。
** 外部データストアを使用している場合は、それらを個別にバックアップする必要があります。
** 内部データストアを使用している場合は、上記リンクに記載されているバックアッププロセスでバックアップが作成されています。
* 移行スクリプトは、インストールされている以下のツールを使ってマシンから実行する必要があります。
** CircleCI Server 3.x のインスタンス用に設定された link:https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
** link:https://github.com/mikefarah/yq#install/[yq]
** link:https://github.com/helm/helm#install[helm]
** link:https://github.com/databus23/helm-diff#install[helm-diff]

[#migration]
== 移行

CircleCI Server をv3.x から v4.x にインプレースアップグレードするには、以下のタスクを行う移行スクリプトを実行します。

* KOTS 設定の YAML ファイルへのエクスポート
* エクスポートされた YAML ファイルを、v4.x への移行に向け `helm` と一緒に使用するように変更
* すべての Kubernetes リソースに `helm` の注釈を付与
* Postgres DB  の `ドメイン` の移行を実行
* すべての KOTS 関連リソースを削除するクリーンアップステップの実行
* 「次のステップ」を含む出力メッセージの表示

IMPORTANT: CircleCI server v4.x では、ワークフローデータの保存方法が変更されました。 以前は、Postgres にワークフローデータを保存していましたが、 このデータをストレージバケットに移動しました (GCS/S3/MinIO)。 移行後、ワークフローデータが使用できない期間が発生します。 これは既存のワークフローデータがストレージバケットに転送されているためです。 所要時間は既存のワークフローデータの量によって異なりますが、移行を行う `workflow-conductor` ポッドをスケールして、このプロセスを高速化することができます。 クラスタで許可される範囲でスケールできます。 ポッドのスケール方法については後述します。

kots-exporter スクリプトでは必要に応じて以下の機能を実行できます。

* 注釈ステップのみを再実行 (`-f annotate`)
* kots-annotation cleanup ジョブの実行 (`-f kots_cleanup`)
* 出力メッセージの表示 (`-f message`)
* PostgreSQL データーベースの移行の再実行 (`-f flyway`)

[#create-docker-secret-for-circleci-image-registry]
=== 1. CircleCI イメージのレジストリ用 Docker シークレットを作成します

この移行スクリプトには、移行機能を実行するために CircleCI イメージレジストリへのアクセス権が必要です。 このイメージのレジストリは、CircleCI Server v4.x のインストール環境でも使用されます。 CircleCI Server がインストールされている同じ名前空間に `docker-registry` シークレットを作成します。 イメージレジストリの認証情報が CircleCI の担当者から提供されます。

ターミナルで `< >` で示されているすべての値を置き換えて、以下を実行します。

[source,shell]
----
kubectl -n <namespace> create secret docker-registry regcred \
  --docker-server=https://cciserver.azurecr.io \
  --docker-username=<image-registry-username> \
  --docker-password=<image-registry-token> \
  --docker-email=<notification-email-id>
----

[#clone-the-repository-and-run-the-kots-exporter-script]
=== 2. リポジトリをクローンし、 kots-exporter スクリプトを実行します

下記では、KOTS exporter スクリプトを含むリポジトリのクローンについて説明します。 このスクリプトにより、CircleCI Server 4.x の `helm-value` ファイルが生成されます。

. `git clone \https://github.com/CircleCI-Public/server-scripts` を実行します。
. `kots-exporter` ディレクトリを `cd server-scripts/kots-exporter` に変更します。
. 移行スクリプト、`./kots-exporter.sh` を実行します。
. 以下の情報を入力するよう求められます。
** CircleCI Server 3.x のリリース名、`circleci-server`
** CircleCI Server 3.x の Kubernetes 名前空間
** サーバー 4.x のライセンス文字列。CircleCI の担当者から提供されます。
. スクリプトが完成すると、実行する次のステップの詳細についての下記のようなメッセージが表示されます。

[source,shell]
----
############ Upgrade Commands ################
Before upgrading to 4.0, follow below steps:

Your helm values file with your installation config is here:
- <path>/kots-exporter/output/helm-values.yaml
-------------------------------------------------------------------------
## Progres Chart Upgrade Preparation
Upgrading to CircleCI server v4.x includes upgrading the Postgres chart.
Before upgrading, we need to prepare your Postgres instance.
This is only needed if your Postgres instance is not externalized.

# Collect your postgres user's password and the PVC attached to your postgres instance
export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace <namespace> postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
export POSTGRESQL_PVC=$(kubectl get pvc --namespace <namespace> -l app.kubernetes.io/instance=circleci-server,role=primary -o jsonpath="{.items[0].metadata.name}")
# remove the postgres statefulset without terminating your postgres instance
kubectl delete statefulsets.apps postgresql --namespace <namespace> --cascade=orphan
# remove the existing secret containing your postgres password. This will get recreated during upgrade.
kubectl delete secret postgresql --namespace <namespace>
-------------------------------------------------------------------------
## Helm Diff
The Helm Diff tool is used to verify that the changes between your current install and the upgrade are expected

# diff command
helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --context 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.0
-------------------------------------------------------------------------
## Helm Upgrade CircleCI Server
helm upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version <version-to-upgrade-to> --force

NOTE: After server 3.x to 4.x migration, You must rerun the Nomad terraform with modified value of 'server_endpoint' variable
It should be - <domain-name>:4647
----

IMPORTANT: Postgres インスタンスを外部化していない場合、CircleCI Server v4.0 にアップグレードすると、Postgres Chart もアップグレードされます。
上記の Helm アップグレードを実行する前に必要なコマンドを確認してください。


[#validate-your-helm-value-file]
=== 3. helm-value ファイルを検証します

移行スクリプトが完了したら、既存の CircleCI Server 3.x の設定ファイルで `helm-values.yaml` が生成されます。 このファイルにはお客様が以前 KOTS で入力した設定データが格納されています。 今後このファイルを標準の Helm プラクティスとして使用して、CircleCI Server の更新および設定を行います。

[#generate-helm-diff-output]
=== 4.  helm-diff 出力を生成します

次に、helm-diff コマンドを作成し、出力をレビューします。

[source,shell]
----
helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --contexts 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.0
----

`helm-diff` コマンドにより生成された出力を下記を使ってレビューします。

* `黄色` に強調表示されている文字列:  `changed`、`added` などの Kubernetes リソースのステータスです。
* `赤色` に強調表示されている文字列: `image` などの削除された文字列です。
* `緑色` に強調表示されている文字列:  `imagePullSecret` などの追加された文字列です。

以下は  `helm-diff` の出力に見られる変更点です。

* すべての Kubernetes リソースに `imagePullSecrets` が追加
* コンテナイメージの更新
* API トークンや署名キーなどのシークレット環境変数が Kubernetes シークレットを参照
* RabbitMQ  と MongoDB の URI の環境変数の変更
* VM、OUTPUT、NOMAD サービスの URI の環境変数が `<domain_name>:<service_port>` を参照
* VM、OUTPUT、NOMAD サービスリソースからの注釈を削除
* Github のチェックサムが注釈として追加
* `distributor-*` のデプロイのシークレットや注釈が削除
* アップストリームチャートの `postgresql` が更新
* アップストリームチャートの再作成 (削除と作成)
** Prometheus (circleci-server-kube-state-metrics、node-exporter、prometheus-server)
** MongoDB
** RabbitMQ
** Redis (redis-master、redis-slave)

[#upgrading-circleci-server-3]
=== 5. CircleCI Server 3.x をアップグレードします

helm-value ファイルの検証が完了したら、以下のコマンドを実行し、CircleCI Server を v4.x にアップグレードします。

Helm レジストリは Azure プライベートレジストリに保存されます。 そのレジストリにアクセスするためのユーザー名とトークンが提供されます。

[source,shell]
----
USER_NAME=<token-username>
PASSWORD=<token>
namespace=<your-install-namespace>
helm upgrade circleci-server -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version 4.0.0 --force --username $USER_NAME --password $PASSWORD
----

[#check-upgrade-status]
=== 6. アップグレードステータスを確認します

以下のコマンドを実行し、すべてのポッドが起動し実行されていることをことを確認します。

[source,shell]
----
kubectl -n <namespace> get pods
----

[#update-dns-setting]
=== 7. DNS 設定を更新します

Server 4.x への移行は、DNS 設定に破壊的な変更を加えます。 Server 4.x では、これまで必要だった 4 つのロードバランサーと 5 つの DNS レコードが `circleci-proxy` や `circleci-proxy-acm` という名前の 1 つの `load-balancer/external-ip` サービスに置き換えられます。 このロードバランサーは <your-domain> とアプリの <your-domain> の 2 つの DNS レコードを介してルーティングする必要があります。 vm-service、output-processer 、Nomad のそれぞれ異なるドメインは不要になりました。 外部 IP/ ロードバランサーを取得して、DNS レコードを適宜アップデートしてください。 

[source,shell]
----
kubectl -n <namespace> get svc circleci-proxy

# AWS Provider: XXXXX.elb.XXXXX.amazonaws.com
# GCP Provider: XXX.XXX.XXX.XXX
----

以下の Kubernetes サービスオブジェクトは、名前が変更されています。

* circleci-server-traefik (LoadBalancer) -> kong (ClusterIP)
* nomad-server-external (LoadBalancer) -> nomad-server (ClusterIP)
* output-processor (LoadBalancer) -> output-processor (ClusterIP)
* vm-service (LoadBalancer) -> vm-service (ClusterIP)

以下の Kubernetes サービスオブジェクトが追加されています。

* circleci-proxy or circleci-proxy-acm (LoadBalancer)

[#execute-nomad-terraform]
=== 8. Nomad Terraform を実行します

link:https://github.com/CircleCI-Public/server-terraform[Nomad Terraform] を実行し、Nomad クライアントを再作成し、`server_endpoint` を `<domain>:4647` に設定します。 link:/docs/ja/server/installation/phase-3-execution-environments#nomad-clients[こちら] に記載されている手順に従ってください。
Nomad Sever-Client の通信用に生成された証明書とキー (base64 エンコード) を使用して、helm 値のファイルを更新します。

[#validate-your-migration-to-server-4]
=== 9. CircleCI Server v4.x への移行を検証します

新しいコミットをプッシュして、新しい CircleCI Server 4.x 環境で https://support.circleci.com/hc/en-us/articles/360011235534-Using-realitycheck-to-validate-your-CircleCI-installation[realitycheck] を再実行します。

[#update-your-team]
=== 10. 最新情報をチームで共有します

https://support.circleci.com/hc/en-us/articles/360011235534-Using-realitycheck-to-validate-your-CircleCI-installation[realitycheck] の実行が正常に完了したら、 このアップグレードについてチームに連絡します。

ifndef::pdf[]

[#next-steps]
== 次のステップ

* link:/docs/ja/server/installation/hardening-your-cluster/[クラスタのハードニング]
* link:/docs/ja/server/operator/operator-overview[Server 4.x オペレーターの概要]
+
endif::[]