---

contentTags:
  platform:
  - Server v2.x
  - Server v4.x
  - Server Admin
---
= CircleCI Server v2.19 to v4.0 Migration
:page-layout: classic-docs
:page-liquid:
:page-description: Learn now to migrate from CircleCI server 2.19.x to 4.0.
:icons: font
:toc: macro

:toc-title:

Migrating from v2.19.x to v4.0 requires you to back up your v2.19 instance data (including Mongo, Postgres, and Vault), and then restore that data in a waiting server v4.0 instance. If you experience problems, you can fall back to your v2.19 instance. Migration requires an operational server v4.0 installation.

移行には、データストアのサイズにより数分～数時間かかります。 Using a staging environment before completing this process in a production environment is recommended. Using a staging environment not only allows you to gain a better understanding of the migration process, but also gives you an idea of how long the migration will take to complete.

[#prerequisites]
== 前提条件

. Your current CircleCI server installation is v2.19x
. You have taken a backup of your v2.19 instance. 外部データストアを使用している場合は、それらを個別にバックアップする必要があります。
. Datastores:
.. If using **externalized** datastores, Postgres must be updated to version 12.
.. If your datastores are **internal**, ensure that the volume sizes allocated to Mongodb, Postgres, and Redis in your v4.0 installation are at least the same or greater than the volumes allocated to the Mongodb, Postgres, and Redis instances in your v2.19 install. You may resize your 4.x datastore volumes following link:/docs/server/operator/expanding-internal-database-volumes/[these instructions].
. You have a new CircleCI server v4.0 link:/docs/server/installation/phase-1-prerequisites[installation].
. You have successfully run link:https://github.com/circleci/realitycheck[realitycheck] with contexts before starting.
. 移行スクリプトを実行するマシンに以下を準備する。
- `kubectl` configured for the server v4.0 instance
- `ssh` access to the v2.19 services machine

[#migration]
== 移行

WARNING: Migrating to server v4.0 will shut down your v2.19 application. Your v2.19 application will not be restarted, although you may manually restart it using the replicated Admin Console. Running server v2.19 and server v4.0 at the same time can cause issues with your 2.19 build data. Server v2.19 should NOT be restarted if server v4.0 is running.

WARNING: 移行プロセスを開始するとダウンタイムが発生します。 Scheduling a maintenance window is recommended.

The instructions below will clone the repository containing the server v2.19.x to server v4.0 migration script.

この移行スクリプトで行われる処理は、以下のとおりです。

* v2.19.x アプリケーションを停止させる。
* Perform preflight checks to confirm namespace and datastores for v2.19.x.
* Create a tarball of your v2.19.x application's PostgreSQL and Mongo databases.
* Vault の既存のアプリケーション データと CircleCI の暗号化/署名キーをアーカイブする。
* Export the v2.19.x tarball to your v4.0 installation. Exported data stores are stored in a directory named `circleci_export`, located relative to wherever the migration script is run from. これはデバッグに役立ちます。
* Perform preflight checks to confirm namespace and datastores for your v4.0 instance.
* Scale v4.0 application deployments down to zero.
* Import the data from the previously exported tarball to your new v4.0 instance.
* Scale v4.0 application deployments up to one.

[#clone-the-repository-and-run-the-migration-script]
=== 1.  Clone the repository and run the migration script

ターミナルで以下を実行します。

. `git clone \https://github.com/CircleCI-Public/server-scripts` を実行します。
. Change into the `migrate` directory: `cd server-scripts/migrate`.
. Run the migration script: `./migrate.sh --server4`.
NOTE: If you have externalized services, you can run `bash migrate.sh --server4 -v -p -m`. These `-v -p -m` flags will skip the migration of Vault, Postgres, and Mongo, respectively. Skipping all three will copy your keys from `/data/circle/circleci-encryption-keys` on the v2.19.x services machine, allowing you to `cat` these files and upload their contents to the v4.0 configuration page.
. 以下の情報を入力するよう求められます。
* CircleCI Server 2.19 のユーザー名
* CircleCI Server 2.19 のホスト名
* CircleCI Server 2.19.x の SSH キー ファイルのパス
* Kubernetes namespace of your server 4.0 installation
. After the script has completed, the Signing and Encryption keys from the 2.19 instance will need to be added to the new 4.0 instance via helm values file or updating the secret used for your 4.0 encryption keys. The keys will be located in `circleci_export/circle-data`.
. The 4.0 instance will either need to be updated to point at the same storage bucket that the 2.19 instance used, or the data needs to be copied over to a new bucket. 後者の方法では、2.19 インスタンスが引き続き正常に動作します。そのため、この移行をテストの一貫として行う場合には後者のアプローチをお勧めします。

NOTE: If a different hostname is being used in the 4.0 environment, the GitHub webhooks will still be pointing to the hostname used in the 2.19 environment. The easiest way to update this is to click *Stop Building* and then *Set Up Project*. これを行った後も、プロジェクトに関連するコンテキストと環境変数は引き続き保持されます。

[#validate-your-migration-to-server-v4]
=== 2.  Validate your migration to server v4.0

Re-run https://github.com/circleci/realitycheck[realitycheck]
with contexts on your new server 4.0 environment by pushing a fresh commit.

[#update-your-team]
=== 3.  最新情報をチームで共有する

Once you have successfully run https://github.com/circleci/realitycheck[realitycheck],
notify your team of the new CircleCI UI and URL, if it has changed.

[#frequently-asked-questions]
== よく寄せられるご質問

[#where-did-all-my-job-and-build-history-go?]
=== 過去のジョブとビルドの履歴がありません。どこに移動されたのですか？

* 既存のジョブとビルドの履歴はすべて、[Legacy Jobs (レガシージョブ)] ビューに移動されます。 ジョブの全履歴は、以下のいずれかの方法で表示できます。
** Selecting Projects -> PROJECT_NAME and selecting the `legacy jobs view` link at the bottom of the project's build history
** Using the following URL pattern: `\https://<APP_DOMAIN>/pipelines/github/<ORG>/<PROJECT>/jobs`
** For a specific job, append a job number to the URL: `\https://<APP_DOMAIN>/pipelines/github/<ORG>/<PROJECT>/jobs/<JOB_NUMBER>`

[#why-does-nothing-happen-when-i-select-start-building]
=== 移行後にプロジェクトで [Start Building (ビルドの開始)] を選択しても何も起こりません。なぜですか？

* デフォルトでは、新しく追加されたプロジェクト (1 回もフォローされていないプロジェクト) は、初めてフォローされた後に自動的にビルドがトリガーされます。 プロジェクトが 2.19 または 4.0 でフォローされたことがある場合、そのプロジェクトは新しいプロジェクトや最初のビルドとは見なされず、フォロー後にビルドはトリガーされません。 ビルドをトリガーするには、新しいコミットやブランチのプッシュなど、GitHub Web フックをトリガーするアクティビティを実行してください。

[#i-got-an-error]
=== I got an error: "Error from server (NotFound):"

* 移行スクリプトでは、Postgres および MongoDB の命名規則が特定のパターンに従っているものと想定しています。 このエラーが表示される場合、インストール環境が標準と異なっているか、DB が移行されていないなどの問題があります。 このエラーが表示された場合は、サポートバンドルと、移行スクリプトの出力を添えてサポートにお問い合わせ下さい。

[#transitioning-to-pipelines]
== トラブルシューティング

When migrating from a server v2.x to a v4.0 installation you will have project configurations made before the introduction of pipelines. Pipelines are automatically enabled for server v4.0 installations so all you need to do is change your project configurations (`.circleci/_config.yml`) to `version: 2.1` to access all CircleCI features available for server v4.

[#what-to-read-next]
== 次に読む

* https://circleci.com/docs/server/installation/hardening-your-cluster[Hardening Your Cluster]
* https://circleci.com/docs/server/operator/operator-overview[Server 4.0 Operator Guide]