---

version:
- Server v4.x
- サーバー管理者
---
= CircleCI Server v4.x のアップグレード
:page-layout: classic-docs
:page-liquid:
:page-description: このドキュメントでは CircleCI Server v4.x のアップグレードに必要な手順を説明します。
:icons: font
:toc: macro

:toc-title:

This page describes the steps needed to upgrade you CircleCI server v4.x installation.

A successful deployment will update the web app. リリースノートに記載されていない限り、アップデートはローリングアップデートでありダウンタイムはありません。

NOTE: We recommend that you do not skip releases when upgrading.

[#prerequisites]
== 前提条件

* Ensure you have access to the Kubernetes cluster in which server is installed.
* Ensure you have set up link:/docs/server/operator/backup-and-restore[Backup and Restore].
* Ensure there is a recent backup. For more information, see the link:/docs/server/opertor/backup-and-restore#creating-backups[Backup and Restore] guide.

[#upgrade-steps]
== Upgrade steps

. https://circleci.com/ja/server/changelog/[更新履歴] をチェックし、新しいバージョンをデプロイする前に実行しなければならないアクションがないことを確認します。
. Optionally, confirm what the update is going to do using https://github.com/databus23/helm-diff[Helm Diff]:
+
[source,shell]
helm diff upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD
. Perform the upgrade:
+
[source,shell]
helm upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD
. テスト環境で https://github.com/circleci/realitycheck[`reality check`] をデプロイして実行し、インストールした CircleCI Server が完全に動作していることを確認します。