= Custom webhooks
:page-platform: Cloud, Server v4+
:page-description: Use webhooks to integrate with third-party services and subscribe to CircleCI events
:experimental:

Setting up an inbound webhook (as a **custom webhook** trigger) on CircleCI enables a third party service to trigger a CircleCI pipeline. Any service that can send a webhook or make a `curl` request can trigger a CircleCI pipeline.

== Introduction

NOTE: Custom webhooks are available for projects integrated via the GitHub App. Custom webhooks are not available on CircleCI server.

Use **custom webhooks** to trigger a pipeline from anywhere that can emit a webhook or run a curl command.

TIP: Custom webhooks are inbound to CircleCI and are used to trigger pipelines from other services. If you are looking for a way to have a CircleCI pipeline trigger a service, use an xref:integration:outbound-webhooks.adoc[outbound webhook].

== Quickstart


Follow these steps to set up and test a custom webhook trigger. Trigger from anywhere that can emit a webhook or run a curl command:

include::ROOT:partial$pipelines-and-triggers/custom-webhook-setup.adoc[]

. You can now test your custom webhook trigger with `curl`. To trigger your pipeline, copy and paste the following sample request and replace `<your-URL>` and `<your-secret>` with the URL and secret that you generated in the previous step:
+
NOTE: When triggering via `curl`, you must use a `POST` request with `content-type: application/json`.
+
[,shell]
----
curl -X POST -H "content-type: application/json" '<your-URL>?secret=<your-secret>'
----

See our link:https://discuss.circleci.com/t/trigger-pipelines-from-anywhere-inbound-webhooks-now-in-preview/49864[community forum] for more details or how to use this functionality with a link:https://discuss.circleci.com/t/re-build-automatically-when-new-image-is-available-on-dockerhub/50350[3rd party service like DockerHub].

NOTE: Custom webhooks will not work with xref:security:contexts.adoc#security-group-restrictions[security group restrictions].  Additionally, the configuration file that is used for pipelines triggered by a custom webhook will only be visible in the CircleCI web app if the configuration file path is `.circleci/config.yml`.


== Example: Trigger one pipeline from another

Use a custom webhook to configure one pipeline to trigger a second pipeline. For example, you might need to run a set of integration tests on a repository after you have made a change to a separate repository.

For this example, assume you have two projects in separate repositories:

TIP: You can also use this method to trigger one pipeline from another within the _same_ project.

* Project A
* Project B

When a change is made to Project A, we want the full Project A configuration to be run, and then the Project B pipeline should be triggered. To achieve this, follow these steps:

=== 1. Set up a custom webhook trigger in Project B

Navigate to Project B in the CircleCI web app and set up a custom webhook by following these steps:

include::ROOT:partial$pipelines-and-triggers/custom-webhook-setup.adoc[]

=== 2. Configure Project A to trigger a pipeline in Project B

Navigate to Project A in the CircleCI web app and set up an environment variable. The value of the environment variable will be the secret from the custom webhook you just set up for Project B.

TIP: As an alternative, you can add an environment variable using a xref:security:contexts.adoc[context].

. In the link:https://app.circleci.com/[CircleCI web app] select your organization.
. Select **Projects** in the sidebar.
. Find your project in the list, select the ellipsis image:guides:ROOT:icons/more.svg[more icon, role="no-border"], and select **Project Settings**.
. Select **Environment Variables** from the sidebar.
. Select btn:[Add Environment Variable].
. Give your environment variable a name, for example, `WEBHOOK_SECRET`.
. Update your Project A configuration file with a step that will trigger a pipeline for Project B, for example (lines 13-16):
+
[,yaml]
----
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: example
          command: echo "one step"

      - run:
          name: Kick off new pipeline
          command: |
              curl -X POST -H "content-type: application/json" "https://internal.circleci.com/private/soc/e/6ccfca1c-5ed6-4dcf-96ca-374969d6edcb?secret=${WEBHOOK_SECRET}"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
----

== Example: Extract custom webhook payload data

The custom webhook body is available by using the `pipeline.trigger_parameters.webhook.body` xref:reference:ROOT:variables.adoc#pipeline-values[pipeline value].

The following example shows how you can use `jq` to extract values from the webhook payload into environment variables when you want to use them in your configuration.

In this example the webhook body contains a property called `branch`. `jq` is installed and used to extract the `branch` value into an environment variable named `WEBHOOK_BRANCH`, which is then used in a GitHub clone command.

TIP: The xref:reference:ROOT:configuration-reference.adoc#commands[command] configured in this example uses commands from the link:https://circleci.com/developer/orbs/orb/circleci/jq[jq] and link:https://circleci.com/developer/orbs/orb/circleci/github-cli[GitHub CLI] orbs.

[,yaml]
----
commands:
  shallow_clone:
    description: Shallow Git Clone
    steps:
      - gh/setup:
          token: "GITHUB_TOKEN"
      - jq/install
      - run:
          name: Shallow Clone
          command: |
            WEBHOOK_BRANCH=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq '.branch')
            gh repo clone << pipeline.trigger_parameters.github_app.repo_url >> . -- --depth 10 --branch "$WEBHOOK_BRANCH"
----
