= Schedule triggers
:page-platform: Cloud
:page-description: Learn about schedule triggers for your CircleCI projects.
:experimental:
:page-aliases: scheduled-pipelines.adoc

NOTE: This feature is not supported for GitLab or Bitbucket Data Center pipelines.

Schedule triggers allow you to trigger pipelines periodically based on a schedule. Schedule triggers retain all the features of pipelines:

- Control the actor (yourself, or the scheduling system) associated with the pipeline, which can enable the use of xref:security:contexts.adoc#project-restrictions[Restricted contexts].
- Use xref:dynamic-config.adoc[Dynamic configuration] via setup workflows.
- Modify the schedule without having to edit `.circleci/config.yml`.
- Take advantage of xref:skip-build.adoc#auto-cancel[auto-cancelling] (only applicable to GitHub OAuth and Bitbucket Cloud pipelines. GitHub App schedule triggers are never auto-cancelled by design)
- Specify xref:pipeline-variables.adoc#pipeline-parameters-in-configuration[Pipeline parameters] associated with a schedule.
- Manage common schedules, for example, across workflows.

Schedule triggers are configured through the API, or through the project settings in the CircleCI web app.

NOTE: A schedule trigger can only be configured for one branch. If you need to schedule for two branches, you would need to set up two schedules.

[#introduction]
== Introduction

Schedule triggers allow you to trigger pipelines periodically based on a schedule. Schedules can range from daily, weekly, monthly, or on a very specific timetable. To set up basic schedule triggers, you do not need any extra configuration in your `.circleci/config.yml` file. However, more advanced usage of the feature will require extra `.circleci/config.yml` configuration (for example, workflow filtering, or using parameters).

Pipeline parameters are typed pipeline variables in the form of a string, integer, or boolean. Adding a parameter to a schedule trigger can be done in the web app in the triggers form while setting up a schedule. Any parameters set up in this manner must be added to your configuration file using the `parameters` key.

Schedule triggers are set to run by an "actor", either the CircleCI scheduling system, or a specific user (for example, yourself). The scheduling actor is important to consider if making use of restricted contexts in workflows. If the user (actor) running the workflow does not have access to the context, the workflow will fail with the `Unauthorized` status.

You can find a basic how-to guide on the xref:set-a-nightly-schedule-trigger.adoc[Set a nightly schedule trigger] page, and more advanced examples on the xref:schedule-triggers-with-multiple-workflows.adoc[Schedule pipelines with multiple workflows] pages.

NOTE: Schedule triggers were previously named "scheduled pipelines".

[#get-started-with-schedule-triggers]
== Get started with schedule triggers

To get started with schedule triggers, you have the option of using the API, or using the CircleCI web app. Both methods are described below. Select the tab for the pipeline type you are using:

[tabs]
====
GitHub App::
+
--
include::ROOT:partial$app-navigation/steps-to-project-settings.adoc[]

. Select **Project Setup** in the sidebar.
Locate your pipeline and select btn:[Schedule +].
. Complete the schedule trigger form:
** Give your trigger a descriptive name.
** Select a branch to tell CircleCI which code to checkout and where to find your config file.
** Under Pipeline attribution, select the actor to initiate the trigger. You can choose yourself, one of your team, or the scheduling system if you want the trigger to be independent from individual users.
** Enter any pipeline parameters you have configured in your project config file. If you enter any new pipeline parameters make sure to also add them to your config file. You can select btn:[Populate from config] to automatically populate the parameters from your config file.
** Select a trigger frequency and repeat options.
+
[options="header",cols="1,2"]
|===
|Field |Options

|Repeats
|Weekly, Monthly

|Days of the week
| Radio buttons for each or select all

|Months
| Radio buttons for each or select all

|Start time (UTC)
| Radio buttons for each hour or select all

| Times per hour
a|* 1 (once per hour)
* 2 (every 30 minutes)
* 3 (every 20 minutes)
* 4 (every 15 minutes)
* 5 (every 12 minutes)
* 6 (every 10 minutes)
* 7 (every 8.6 minutes)
* 8 (every 7.5 minutes)
* 9 (every 6.7 minutes)
* 10 (every 6 minutes)
* 11 (every 5.5 minutes)
* 12 (every 5 minutes)
|===

. Enable the trigger and select btn:[Save].
--
GitHub OAuth::
+
--
include::ROOT:partial$app-navigation/steps-to-project-settings.adoc[]

. Select **Triggers** in the sidebar.
. Select btn:[Add Trigger].
** Give your trigger a descriptive name.
** Enter an optional trigger description.
** Select the pipeline to run.
** Select a release frequencies (weekly/monthly, which days/months/time etc.).
** Enter a branch or tag name to determine when to trigger the pipeline.
** Optionally, enter pipeline parameters. If you declare pipeline parameters in the form, you need to make sure they are configured in your project's `.circleci/config.yml`. See the xref:guides:orchestrate:pipeline-variables.adoc#pipeline-parameters-in-configuration[Pipeline values and parameters] page for more information.
** Select an actor to initiate the trigger.
. Define the new schedule by filling out the form, then select **Save Trigger**.
--
Bitbucket Cloud::
+
--
include::ROOT:partial$app-navigation/steps-to-project-settings.adoc[]

. Select **Triggers** in the sidebar.
. Select btn:[Add Trigger].
** Give your trigger a descriptive name.
** Enter an optional trigger description.
** Select the pipeline to run.
** Select a release frequencies (weekly/monthly, which days/months/time etc.).
** Enter a branch or tag name to determine when to trigger the pipeline.
** Optionally, enter pipeline parameters. If you declare pipeline parameters in the form, you need to make sure they are configured in your project's `.circleci/config.yml`. See the xref:guides:orchestrate:pipeline-variables.adoc#pipeline-parameters-in-configuration[Pipeline values and parameters] page for more information.
** Select an actor to initiate the trigger.
. Define the new schedule by filling out the form, then select **Save Trigger**.
--
====

If you would like to manage common schedules for multiple workflows, you will need to manually set this in your `.circleci/config.yml` file. See the xref:guides:orchestrate:schedule-pipelines-with-multiple-workflows.adoc[Schedule pipelines with multiple workflows] page for examples.

[#use-the-api]
=== Use the API

NOTE: Setting up schedule trigger via the API is not yet available for GitHub App pipelines.

If your project has no scheduled workflows, and you would like to try out schedule triggers:

. Have your CircleCI token ready, or create a new token by following the steps on the xref:toolkit:managing-api-tokens.adoc[Managing API tokens] page.
. Create a new schedule link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[using the API]. For example:
+
```shell
curl --location --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
--header "circle-token: <PERSONAL_API_KEY>" \
--header "Content-Type: application/json" \
--data-raw '{
    "name": "my schedule name",
    "description": "some description",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
      <additional pipeline parameters can be added here>
    },
    "timetable": {
        "per-hour": 3,
        "hours-of-day": [1,15],
        "days-of-week": ["MON", "WED"]
    }
}'
```

include::ROOT:partial$tips/find-project-slug.adoc[]

For additional information, refer to the **Schedule** section under the link:https://circleci.com/docs/api/v2/[API v2 docs]. Also see the xref:toolkit:api-developers-guide.adoc#getting-started-with-the-api[Getting started with the API] section of the API Developer's Guide for more guidance on making requests.

== Migrate scheduled workflows to schedule triggers

If you have existing scheduled workflows you need to migrate to schedule triggers, use the xref:migrate-scheduled-workflows-to-schedule-triggers.adoc[Schedule triggers migration] guide.

== Schedule triggers video tutorial

The video offers a short tutorial for the following scenarios:

- Set a schedule in the web app
- Set a schedule with the API
- Migrate from scheduled workflows to schedule triggers

++++
<div class="video-wrapper">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/x3ruGpx6SEI" title="Schedule triggers tutorial" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
++++

For the documentation for these scenarios, visit the following pages:
- xref:set-a-nightly-schedule-trigger.adoc[Set a nightly schedule trigger]
- xref:schedule-triggers-with-multiple-workflows.adoc[Schedule pipelines with multiple workflows]

[#scheduled-pipelines-faqs]
== FAQs

include::ROOT:partial$faq/schedule-trigger-faq-snip.adoc[]

[#next-steps]
== Next steps

- xref:migrate-scheduled-workflows-to-schedule-triggers.adoc[Migrate scheduled workflows to schedule triggers]
- xref:schedule-triggers-with-multiple-workflows.adoc[Schedule pipelines with multiple workflows]
- xref:set-a-nightly-schedule-trigger.adoc[Set a nightly schedule trigger]
