= Schedule triggers
:page-platform: Cloud
:page-vcs: github, github-enterprise, bitbucket, cursor-origin
:page-plan: Free, Performance, Scale
:page-audience: developer
:page-description: Use schedule triggers to run pipelines in your CircleCI projects periodically, and configure them in the web app or with the API.
:experimental:
:page-aliases: scheduled-pipelines.adoc

NOTE: This feature is not supported for GitLab pipelines.

Schedule triggers allow you to trigger pipelines periodically based on a schedule. Schedule triggers retain all the features of pipelines:

- Control the actor (yourself, or the scheduling system) associated with the pipeline, which can enable the use of xref:security:contexts.adoc#project-restrictions[Restricted Contexts].
- Use xref:dynamic-config.adoc[Dynamic Configuration] via setup workflows.
- Modify the schedule without having to edit `.circleci/config.yml`.
- Take advantage of xref:skip-build.adoc#auto-cancel[Auto-Cancelling] (only applicable to GitHub OAuth and Bitbucket Cloud pipelines. GitHub App schedule triggers are never auto-cancelled by design)
- Specify xref:pipeline-variables.adoc#pipeline-parameters-in-configuration[Pipeline Parameters] associated with a schedule.
- Manage common schedules, for example, across workflows.

Configure schedule triggers from menu:Project Settings[Project Setup] or menu:Project Settings[Triggers] in the web app, or via the API.

NOTE: A schedule trigger can only be configured for one branch. If you need to schedule for two branches, you would need to set up two schedules.

[#introduction]
== Introduction

Schedule triggers allow you to trigger pipelines periodically based on a schedule. Schedules can range from daily, weekly, monthly, or on a very specific timetable. To set up basic schedule triggers, you do not need any extra configuration in your `.circleci/config.yml` file. However, more advanced usage of the feature will require extra `.circleci/config.yml` configuration (for example, workflow filtering, or using parameters).

Pipeline parameters are typed pipeline variables in the form of a string, integer, or boolean. Adding a parameter to a schedule trigger can be done in the web app in the triggers form while setting up a schedule. Any parameters set up in this manner must be added to your configuration file using the `parameters` key.

Schedule triggers are set to run by an "actor", either the CircleCI scheduling system, or a specific user (for example, yourself). The scheduling actor is important to consider if making use of restricted contexts in workflows. If the user (actor) running the workflow does not have access to the context, the workflow will fail with the `Unauthorized` status. Using the Scheduling system to be the actor will not count towards your organization's active user quota.

You can find a basic how-to guide on the xref:set-a-nightly-schedule-trigger.adoc[Set a Nightly Schedule Trigger] page, and more advanced examples on the xref:schedule-triggers-with-multiple-workflows.adoc[Schedule Pipelines With Multiple Workflows] pages.

NOTE: Schedule triggers are the new name for what was previously known as "scheduled pipelines".

[#get-started-with-schedule-triggers]
== Get started with schedule triggers

To get started with schedule triggers, you have the option of using the API, or using the CircleCI web app. Both methods are described below. Select the tab for the pipeline type you are using:

include::ROOT:partial$pipelines-and-triggers/set-up-schedule-trigger.adoc[]

If you would like to manage common schedules for multiple workflows, you will need to manually set this in your `.circleci/config.yml` file. See the xref:guides:orchestrate:schedule-pipelines-with-multiple-workflows.adoc[Schedule Pipelines With Multiple Workflows] page for examples.

[#use-the-api]
=== Use the API

If your project has no scheduled workflows, and you would like to try out schedule triggers, select the tab for your pipeline type:

[tabs]
====
GitHub App and Cursor Origin::
+
--
. Have your CircleCI token ready, or create a new token by following the steps on the xref:toolkit:managing-api-tokens.adoc[Managing API Tokens] page.
. Find your project ID. See xref:toolkit:api-v3-developers-guide.adoc#getting-started-with-api-v3[Getting Started With API V3] for steps to list your organizations and projects and retrieve your project ID.
. Get your pipeline definition ID. Replace `<PROJECT_ID>` with your project ID:
+
[source,console]
----
$ curl -g \
  --url "https://circleci.com/api/v3/pipelines?filter[project_id]=<PROJECT_ID>" \
  --header "Authorization: Bearer $CIRCLE_TOKEN"
----
+
Locate your pipeline in the response and copy its `id` value.
. Create a new schedule trigger. Replace `<PIPELINE_ID>` with your pipeline definition ID, and update `config.ref` and `checkout.ref` with your target branch:
+
[source,console]
----
$ curl --request POST \
  --url https://circleci.com/api/v3/triggers \
  --header "Authorization: Bearer $CIRCLE_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "data": {
      "attributes": {
        "config":   { "ref": "main" },
        "checkout": { "ref": "main" },
        "event": {
          "type": "schedule",
          "schedule": {
            "name": "nightly-build",
            "cron_expression": "0 2 * * *",
            "attribution_actor": "current"
          }
        }
      },
      "references": {
        "pipeline": { "id": "<PIPELINE_ID>" }
      }
    }
  }'
----
+
A successful call returns a `201 Created` response:
+
[source,json]
----
{
  "data": {
    "id": "<TRIGGER_ID>",
    "attributes": {
      "is_disabled": false,
      "created_at": "2026-10-01T11:39:37.619Z",
      "event": {
        "type": "schedule",
        "schedule": {
          "name": "nightly-build",
          "cron_expression": "0 2 * * *",
          "attribution_actor": { "id": "<YOUR_USER_ID>" }
        }
      },
      "config":   { "ref": "main" },
      "checkout": { "ref": "main" }
    },
    "references": {
      "project":  { "id": "<PROJECT_ID>" },
      "pipeline": { "id": "<PIPELINE_ID>" }
    }
  }
}
----

All the following fields must be present. The API returns a `400` if any are missing:

- `config.ref`: The branch or tag to use as the config source.
- `checkout.ref`: The branch or tag to check out.
- `schedule.name`: A unique name for the schedule.
- `schedule.cron_expression`: A 5-field cron expression. The API rejects a wildcard in the minute field, such as `* * * * *`.
- `schedule.attribution_actor`: Use `"current"` to run pipelines as the token owner, or `"system"` for the scheduling system. The API rejects user UUIDs.

Optional fields:

- `attributes.is_disabled`: Set to `true` to create the schedule in a disabled state.
- `attributes.parameters`: Pipeline parameters to pass when the schedule triggers.

For additional information, refer to the link:https://circleci.com/docs/api/v3#tag/triggers/POST/api/v3/triggers[API v3 Triggers Reference].
--
GitHub OAuth and Bitbucket Cloud::
+
--
. Have your CircleCI token ready, or create a new token by following the steps on the xref:toolkit:managing-api-tokens.adoc[Managing API Tokens] page.
. Create a new schedule using the link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[API v2 Create Schedule] endpoint. Replace `<project-slug>` with your project slug:
+
[source,console]
----
$ curl --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
  --header "Circle-Token: $CIRCLE_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "name": "my schedule name",
    "description": "some description",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
    },
    "timetable": {
      "per-hour": 3,
      "hours-of-day": [1,15],
      "days-of-week": ["MON", "WED"]
    }
}'
----

include::ROOT:partial$tips/find-project-slug.adoc[]

For additional information, refer to the **Schedule** section under the link:https://circleci.com/docs/api/v2/[API v2 Reference].
--
====

Also see the xref:toolkit:api-developers-guide.adoc#getting-started-with-the-api[Getting Started With the API] section of the API Developer's Guide for more guidance on making requests.

== Migrate scheduled workflows to schedule triggers

If you have existing scheduled workflows you need to migrate to schedule triggers, use the xref:migrate-scheduled-workflows-to-schedule-triggers.adoc[Schedule Triggers Migration] guide.

[#scheduled-pipelines-faqs]
== FAQs

include::ROOT:partial$faq/schedule-trigger-faq-snip.adoc[]

[#next-steps]
== Next steps

- xref:migrate-scheduled-workflows-to-schedule-triggers.adoc[Migrate Scheduled Workflows to Schedule Triggers]
- xref:schedule-triggers-with-multiple-workflows.adoc[Schedule Pipelines With Multiple Workflows]
- xref:set-a-nightly-schedule-trigger.adoc[Set a Nightly Schedule Trigger]
