= Set a nightly schedule trigger
:page-platform: Cloud
:page-vcs: github, github-enterprise, bitbucket, cursor-origin
:page-plan: Free, Performance, Scale
:page-audience: developer
:page-description: Create a schedule trigger that runs your pipeline at midnight every night. You can set the schedule in the CircleCI web app or with the API.
:experimental:
:page-aliases: set-a-nightly-scheduled-pipeline.adoc

NOTE: Schedule triggers are not currently available for GitLab projects.

A common scenario you might want to set up is to trigger a pipeline overnight. The examples below show how to schedule a pipeline to run at midnight every night. You can set a schedule right from the link:https://app.circleci.com/[CircleCI web app], or you can set one using the API.

[#set-a-in-the-web-app]
== Set a schedule in the web app

To access the form for specifying a schedule for a trigger, follow the steps below for your pipeline type.

For a nightly schedule, you will need to take into account that the form uses UTC (coordinated universal time). For example, if you would like your pipeline to trigger at midnight (0:00) in eastern standard time (EST), you would need to find the difference from UTC. In this scenario, 0:00 EST is 5:00 UTC.

include::ROOT:partial$pipelines-and-triggers/set-up-schedule-trigger.adoc[]

[#set-a-schedule-with-the-api]
== Set a schedule with the API

To set a schedule with the API, you will need your CircleCI personal API token. Select the tab for your pipeline type:

[tabs]
====
GitHub App and Cursor Origin::
+
--
. Find your project ID. See xref:toolkit:api-v3-developers-guide.adoc#getting-started-with-api-v3[Getting Started With API V3] for steps to list your organizations and projects and retrieve your project ID.
. Get your pipeline definition ID. Replace `<PROJECT_ID>` with your project ID:
+
[source,console]
----
$ curl -g \
  --url "https://circleci.com/api/v3/pipelines?filter[project_id]=<PROJECT_ID>" \
  --header "Authorization: Bearer $CIRCLE_TOKEN"
----
+
Locate your pipeline in the response and copy its `id` value.
. Create the nightly schedule trigger. Replace `<PIPELINE_ID>` with your pipeline definition ID:
+
[source,console]
----
$ curl --request POST \
  --url https://circleci.com/api/v3/triggers \
  --header "Authorization: Bearer $CIRCLE_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "data": {
      "attributes": {
        "config":   { "ref": "main" },
        "checkout": { "ref": "main" },
        "event": {
          "type": "schedule",
          "schedule": {
            "name": "nightly-build",
            "cron_expression": "0 0 * * *",
            "attribution_actor": "current"
          }
        }
      },
      "references": {
        "pipeline": { "id": "<PIPELINE_ID>" }
      }
    }
  }'
----

The cron expression `0 0 * * *` runs at midnight UTC every day. Update `config.ref` and `checkout.ref` to point to your target branch. For more information, see the xref:schedule-triggers.adoc#use-the-api[Schedule Triggers] page.
--
GitHub OAuth and Bitbucket Cloud::
+
--
. Create a nightly schedule using the link:https://circleci.com/docs/api/v2/index.html#operation/createSchedule[API v2 Create Schedule] endpoint. Replace `<project-slug>` with your project slug:
+
[source,console]
----
$ curl --request POST "https://circleci.com/api/v2/project/<project-slug>/schedule" \
  --header "Circle-Token: $CIRCLE_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "name": "nightly-build",
    "description": "Runs the pipeline at midnight UTC every night.",
    "attribution-actor": "system",
    "parameters": {
      "branch": "main"
    },
    "timetable": {
      "per-hour": 1,
      "hours-of-day": [0],
      "days-of-week": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
    }
}'
----

include::ROOT:partial$tips/find-project-slug.adoc[]

For more information, refer to the **Schedule** section under the link:https://circleci.com/docs/api/v2/[API v2 Reference].
--
====

[#next-steps]
== Next steps

- xref:migrate-scheduled-workflows-to-schedule-triggers.adoc[Migrate Scheduled Workflows to Schedule Triggers]
- xref:schedule-pipelines-with-multiple-workflows.adoc[Schedule Pipelines With Multiple Workflows]
