= Prevent unregistered users from spending credits
:page-platform: Cloud
:page-description: A how to guide to configuring your org so that unregistered users will not be able to perform actions that spend credits
:experimental:

Unregistered users trigger pipelines, spend credits and count towards your plan usage. You can choose to use the **Prevent unregistered user spend** option to only allow registered (users with a CircleCI account) users the ability to trigger work that consumes credits. For a full breakdown of the various ways pipelines can be triggered, see the xref:orchestrate:triggers-overview.adoc[Triggers overview].

****
*Unregistered users* are how CircleCI track users who have triggered builds but have not signed up for a CircleCI account. Each unregistered user within an org is mapped to, and counts as, a single link:https://support.circleci.com/hc/en-us/articles/360034783154[active user]. Unregistered users count towards your plan usage.

For more information about unregistered users, see this link:https://support.circleci.com/hc/en-us/articles/360037744473-What-is-an-Unregistered-User-[support article]
****

[#prerequisites]
== Prerequisites

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free].
* You must be on the link:https://circleci.com/pricing/[Performance or Scale Plan].
* You must be an org admin.

[#steps]
== Steps

Follow these steps to prevent unregistered users from triggering work that consumes credits:

. In the link:https://app.circleci.com/[CircleCI web app], select *Plan* in the sidebar.
. Select the **Usage Controls** tab. If you do not see this option you might be on the Free Plan, or you may not be an org admin, in which case this guide does not apply to you.
. Select **Prevent unregistered user spend** option to switch it to "On".

To disable this feature you can toggle this switch "Off" at any time.

Once enabled, any unregistered users, that is, users who do not have a CircleCI account, will see the following if they attempt to trigger a pipeline:

* The pipeline will fail to start.
* The `block-unregistered-user` error will be displayed in a banner on the dashboard
