= Create an organization
:page-platform: Cloud
:page-description: Create a new organization in CircleCI.
:experimental:

This guide covers creating a new organization in CircleCI.

The following organization types are available in CircleCI:

* `circleci`: This org type lets you connect to GitHub, GitLab, or Bitbucket Data Center.
* `github`: This org type is created automatically when you log in using your GitHub login.
* `bitbucket`: This org type is created automatically when you log in using your Bitbucket login.

For a guide to organization types, see the xref:permissions-authentication:users-organizations-and-integrations-guide.adoc#organizations[Users, Organizations, and Integrations Guide].

== Create a circleci organization

To create a `circleci` organization, follow these steps:

. Navigate to your user homepage in the link:https://app.circleci.com/home/[CircleCI web app].
. Select the btn:[+ Create organization] button.
. Give your organization a name and select btn:[Let's Go].

After you create your new organization, invite your team and create a project:

* xref:invite-your-team.adoc#invite-teammates[Invite Your Team].
* xref:create-project.adoc#create-a-project[Create a Project].

== Create a github organization

CircleCI creates a `github` organization when you log in using your _social_ GitHub login. `github` organizations use an OAuth app connection with CircleCI. If you have logged in to CircleCI using a method other than your GitHub login, you can still create a `github` organization by following these steps:

. Navigate to your link:https://app.circleci.com/settings/user[User settings] page.
. Select **Account Integrations** from the sidebar.
. At the bottom of the page, select the link that reads `Received instructions from the CircleCI Support team to authorize a GitHub OAuth app?`.
. Follow the instructions to create a `github` organization.

Once CircleCI creates your `github` organization, you can invite your team and set up projects:

* xref:invite-your-team.adoc#invite-teammates[Invite Your Team].
* xref:create-project.adoc#set-up-a-project[Set up a Project].

== Create a bitbucket organization

CircleCI creates a `bitbucket` organization when you log in using your _social_ Bitbucket login. `bitbucket` organizations use an OAuth app connection with CircleCI. If you have logged in to CircleCI using a method other than your Bitbucket login, you can still create a `bitbucket` organization by following these steps:

. Navigate to your link:https://app.circleci.com/settings/user[User settings] page.
. Select the **Account Integrations** from the sidebar.
. Select btn:[Connect] next to Bitbucket.
. Follow the instructions to authorize the Bitbucket OAuth app.

Once CircleCI creates your `bitbucket` organization, you can invite your team and set up projects:

* xref:invite-your-team.adoc#invite-teammates[Invite Your Team].
* xref:create-project.adoc#set-up-a-project[Set up a Project].
