= Cross references and links

This page covers how to create links and cross references in CircleCI docs.

[#cross-references]
== Cross references
* Make cross references (links between docs pages) by using the resource ID of the destination page and section, in the following form:
+
[source,adoc]
----
xref:guides:integration:github-integration.adoc#user-keys-and-deploy-keys[User Keys and Deploy Keys]
----
+
See the link:https://docs.antora.org/antora/latest/page/resource-id-coordinates/[Resource ID coordinates] page in the Antora docs for more information.

* Cross references should explicitly name the document or section to which they are linking.
** **Good:** Refer to the xref:guides:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[Setting an environment variable in a project] section of the Environment Variables document.
** **Bad:** For more information on adding project-level environment variables head xref:guides:security:set-environment-variable.adoc#set-an-environment-variable-in-a-project[here].

[#links]
== Links

* Links to third party sites should be in the following form in AsciiDoc content:
+
[source,adoc]
----
link:https://circleci.com[CircleCI]
----
