[.table.table-striped]
[cols=5*, options="header", stripes=even]
|===
| Class | vCPUs | RAM | Cloud | Server

| medium
| 4 @ 2.7 GHz
| 8GB
| icon:check[]
| icon:times[]

| macos.x86.medium.gen2
| 4 @ 3.2 GHz
| 8GB
| icon:check[]
| icon:times[]

| large
| 8 @ 2.7 GHz
| 16GB
| icon:check[]
| icon:times[]

| macos.m1.medium.gen1
| 4 @ 3.2 GHz
| 6GB
| icon:check[]
| icon:times[]

| macos.m1.large.gen1
| 8 @ 3.2 GHz
| 12GB
| icon:check[]
| icon:times[]

| macos.x86.metal.gen1
| 12 @ 3.2 GHz
| 32GB
| icon:check[]
| icon:times[]
|===

WARNING: The `medium` and `large` resource classes are being deprecated on October 2, 2023. Xcode v14.2 is the latest version that will be supported by these macOS resources. See our https://discuss.circleci.com/t/macos-resource-deprecation-update/46891[announcement] for more details.

[NOTE]
====
The `macos.x86.metal.gen1` resource requires a minimum 24-hour lease. See the link:{{ site.baseurl }}/dedicated-hosts-macos[Dedicated Host for macOS] page to learn more about this resource class.

The `large` resource class is only available for customers with an annual contract. https://support.circleci.com/hc/en-us/requests/new[Open a support ticket] if you would like to learn more about our annual plans.
====
