= Benefits of CircleCI
:page-platform: Cloud, Server v4+
:page-description: Benefits of choosing CircleCI for CI/CD
:experimental:


[#benefits-of-circleci]
== Benefits of CircleCI

Organizations choose CircleCI because jobs run fast and builds can be optimized for speed. CircleCI can be configured to run very complex pipelines efficiently with sophisticated xref:optimize:caching.adoc[Caching], xref:optimize:docker-layer-caching.adoc[Docker Layer Caching], and xref:optimize:optimizations.adoc#resource-class[Resource Classes] for running on faster machines.

As a developer using CircleCI you can:

- xref:execution-managed:ssh-access-jobs.adoc[SSH Into Any Job] to debug your build issues.
- Set up xref:optimize:parallelism-faster-jobs.adoc[Parallelism] in your `.circleci/config.yml` file to run test jobs faster.
- Configure xref:optimize:caching.adoc[Caching] with two simple keys to reuse data from previous jobs in your xref:orchestrate:workflows.adoc[Workflow].
- Configure self-hosted xref:execution-runner:runner-overview.adoc[Runners] for unique platform support.
- Access xref:execution-managed:using-arm.adoc[Arm VM Resources] and xref:execution-managed:using-docker.adoc#arm[Arm on Docker].
- Use xref:orbs:use:orb-intro.adoc[Orbs], reusable packages of configuration, to integrate with third parties.
- Use pre-built Docker xref:execution-managed:circleci-images.adoc[Images] in a variety of languages.
- Use the link:https://www.circleci.com/docs/api/v2/[API] to retrieve information about jobs and workflows.
- Use the xref:toolkit:local-cli.adoc[CLI] to access advanced tools locally.
- Get flaky test detection with xref:insights:insights-tests.adoc[Test Insights].

As an operator or administrator of CircleCI installed on your own servers, CircleCI provides monitoring and insights into your builds and uses link:https://www.nomadproject.io/[Nomad] for scheduling.

See the xref:server-admin:overview:circleci-server-overview.adoc[CircleCI Server Overview] for server documentation.

[#pricing-options]
== Pricing options

Visit CircleCI's link:https://circleci.com/pricing[Pricing page] to view free and paid options.

You can link:https://circleci.com/signup[sign up] for free to get access to unlimited projects on CircleCI's fully-hosted cloud platform.

Organizations on the Free Plan are given free credits to use on open source projects. Visit the xref:integration:oss.adoc[Building Open Source Projects] page for more information about free containers for public open source projects.

[#next-steps]
== Next steps

- xref:getting-started:first-steps.adoc[Sign up and Try]
