= Open source acknowledgments
:page-platform: Cloud, Server v4+
:page-description: List and acknowledgements for open-source projects and libraries that are used in CircleCI products and services.
:experimental:

This page provides the details of 3rd-party open source components used in CircleCI products.

[tabs]
====
Release agent::
+
--
The following 3rd-party open source components are used in the CircleCI release agent. The release agent is used to integrate CircleCI with Kubernetes clusters for release management. For more information, see the xref:deploy:deployment-overview.adoc[Deploys docs].

[cols=2*, options="header", format=csv]
|===
include::guides:ROOT:attachment$release-agent.csv[]
|===
--
GOAT::
+
--
The following 3rd-party open source components are used in the CircleCI General Orchestration Agent (GOAT). GOAT is an agent used by self-hosted container runners for managing the container environment. For more information, see the xref:execution-runner:container-runner.adoc[Container Runner docs].

[cols=2*, options="header", format=csv]
|===
include::guides:ROOT:attachment$runner-init.csv[]
|===
--
CircleCI runner::
+
--
The following 3rd-party open source components are used in the CircleCI self-hosted runner. The CircleCI runner is a utility used to run CirlceCI jobs on self-hosted infrastructure. For more information, see the xref:execution-runner:runner-overview.adoc[self-hosted runner overview docs].

[cols=2*, options="header", format=csv]
|===
include::guides:ROOT:attachment$circleci-runner.csv[]
|===
--
====
