---

contentTags:
  platform:
  - Server v4.1
  - Server Admin
---
= Phase 2 - Core services
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI Server v4.x のインストール手順と前提条件をご確認ください。
:icons: font
:toc: macro

:toc-title:

// This doc uses ifdef and ifndef directives to display or hide content specific to Google Cloud Storage (env-gcp) and AWS (env-aws). Currently, this affects only the generated PDFs. To ensure compatability with the Jekyll version, the directives test for logical opposites. For example, if the attribute is NOT env-aws, display this content. For more information, see https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/.

Before you begin with the CircleCI server v4.x core services installation phase, ensure all xref:phase-1-prerequisites#[prerequisites] are met.

NOTE: 以下のセクションでは、 `< >` で示されている箇所にご自身の詳細情報を入力してください。

[#create-a-namespace]
== 1.  名前空間を作成します

アプリケーションをインストールする名前空間を作成します。

[source,shell]
----
kubectl create ns <namespace>
----

TIP: 名前空間を作成したら、以下のコマンド: `kubectl config set-context --current --namespace <namespace>` で、`kubectl` コンテキストも設定することをお勧めします。

[#pull-images]
== 2. イメージをプルします

CircleCI のイメージレジストリからイメージをプルするための認証情報は、このセットアッププロセスの一部としてお客様に提供されます。 Azure Container Registry (ACR) からのイメージのプルには、 `docker-registry` Kubernetes のシークレットを使用します。 パブリックインターネットへのアクセスが可能かどうかにより、 2 つのオプションがあります。

[.tab.pullimage.Public]
--
**オプション 1:** アプリケーションのパブリックインターネットへのアクセスが可能な場合

次の例では、CircleCI のイメージレジストリからイメージをプルするためのデプロイを有効化するために Kubernetes シークレットを作成します。 `docker-registry` Kubernetes シークレットは以下のようになります。

[source,shell]
----
kubectl create secret docker-registry regcred \
  --docker-server=cciserver.azurecr.io \
  --docker-username=<your-username> \
  --docker-password="<provided-token>" \
  --docker-email=<your-contact-email>
----
--

[.tab.pullimage.Private]
--
**オプション 2:** アプリケーションのパブリックインターネットへのアクセスが不可能な場合

提供された認証情報により、イメージのコピーをローカルにプルし、保存することができます。 イメージを使用可能な任意の Docker リポジトリにプルし、保存します。 `docker-registry` Kubernetes シークレットは以下のようになります。

[source,shell]
----
kubectl create secret docker-registry regcred \
  --docker-server=<your-docker-image-repo> \
  --docker-username=<your-username> \
  --docker-password=<your-access-token> \
  --docker-email=<your-email>
----
--

[#create-helm-values]
== 3. Helm 値を作成します

CircleCI をインストールする前に、インストール専用の `values.yaml` ファイルを新たに作成することをお勧めします。 xref:installation-reference#example-manifests[The Installation Reference section] contains some example `values.yaml` files that are a good place to start. 以下は、`values.yaml` に含める必要がある最小限の値です。 更にカスタマイズすることも可能です。利用できるオプションについては提供されている `values.yaml` を参照してください。

シークレットについては 2 つのオプションがあります。

* `values.yaml` ファイルに追加する
* Kubernetes シークレットとして直接追加する

お好きな方法で柔軟に Kubernetes シークレットを管理していただけます。 どちらのオプションを選んでも、シークレットは CircleCI 内に Kubernetes シークレットとして保存されます。

NOTE: このインストールプロセスでは、コマンド `cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c <num-of-chars>` を使ってランダムな英数字の値を適宜生成できます。 このコマンドはすべての *nix ベースのシステムで動作します。

[#api-token]
=== a.  API トークン

このアプリケーションでは API トークンを含む Kubernetes シークレットが必要です。 この API トークンは、API サービスへの API 内部通信を簡易化するために使用されます。 ランダムな文字列を使って安全に保存してください。紛失した場合、復元することはできません。 この Kubernetes シークレットの作成には 2 つのオプションがあり、ご自身で作成することも、CircleCI がお客様のシークレットを作成することも可能です。

[.tab.apitoken.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic api-token \
  --from-literal=api-token=<your-super-secret-random-value>
----
--

[.tab.apitoken.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

値を `values.yaml` に追加します。 CircleCI が自動的に Kubernetes シークレットを作成します。

[source,yaml]
----
apiToken: "<your-super-secret-random-value>"
----
--

[#session-cookie]
=== b.  セッション Cookies

このアプリケーションでは、セッション Cookie に署名する際に使用するセッション Cookie キーの Kubernetes シークレットが必要です。 このシークレットは 16 文字にする必要があります。 ランダムな文字列を使って安全に保存してください。紛失した場合、復元することはできません。 この Kubernetes シークレットの作成には 2 つのオプションがあり、ご自身で作成することも、CircleCI がお客様のシークレットを作成することも可能です。

[.tab.sessioncookie.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic session-cookie \
--from-literal=session-cookie-key=<your-secret-key-16-chars>
----
--

[.tab.sessioncookie.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

値を `values.yaml` に追加します。  CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
sessionCookieKey: "<your-secret-key-16-chars>"
----
--

[#encryption]
=== c.  暗号化

このアプリケーションでは、署名と暗号化のキーセットを含む Kubernetes シークレットが必要です。 CircleCI で生成されるアーティファクトの暗号化と署名には、キーセットを使用します。 These keys were created during the xref:phase-1-prerequisites#encryption-signing-keys[prerequisites phase]. 値を紛失した場合、復元できません。 Kubernetes シークレットの管理方法には、2 つのオプションがあります。

[.tab.encryption.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic signing-keys \
  --from-literal=signing-key=<your-generated-signing-key> \
  --from-literal=encryption-key=<your-generated-encryption-key>
----
--

[.tab.encryption.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

値を `values.yaml` に追加します。 CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
keyset:
  signing: '<your-generated-signing-key>'
  encryption: '<your-generated-encryption-key>'
----
--

[#postgres]
=== d. Postgres

[#postgres-credentials]
==== 認証情報

このアプリケーションでは、Postgres 認証情報を含む Kubernetes シークレットが必要です。  これは、Postgres の内部インスタンス (デフォルト) または外部ホストインスタンスのいずれかを使用する場合に当てはまります。 値を紛失した場合、復元できません。 Kubernetes シークレットの管理方法には、2 つのオプションがあります。

[.tab.postgres.You_create_Secret]
--
**オプション 1:** ご自身でシークレットを作成する

[source,shell]
----
kubectl create secret generic postgresql \
  --from-literal=postgres-password=<postgres-password>
----

下記を `values.yaml` ファイルに追加します。

[source,yaml]
----
postgresql:
  auth:
    existingSecret: postgresql
----
--

[.tab.postgres.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

認証情報を `values.yaml` に追加します。CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
postgresql:
  auth:
    postgresPassword: "<postgres-password>"
----
--

[#postgres-tls]
==== TLS

Postgres は TLS 暗号化トラフィックを使用するように拡張できます。 内部でデプロイした場合、このオプションはデフォルトでは無効になっていますが、`values.yaml` の postgresql のブロックに以下を追加することにより有効化できます。

[source,yaml]
----
postgresql:
  ...
  tls:
    enabled: true
    autoGenerated: true # Generate automatically self-signed TLS certificates
----

証明書ファイルは、自動作成するのではなく提供することもできます。 その場合、必要な TLC 証明書とキーを含むシークレットを作成します。 

[source,yaml]
----
kubectl create secret generic postgres-tls-secret --from-file=./cert.pem --from-file=./cert.key --from-file=./ca.pem
----

すると、`values.yaml` の postgresql のブロックに以下の内容が含まれます。

[source,yaml]
----
postgresql:
  ...
  tls:
    enabled: true
    certificatesSecret: "postgres-tls-secret" # Name of an existing secret that contains the certificates
    certFilename: "cert.pem" # Certificate filename
    certKeyFilename: "cert.key" # Certificate key filename
    certCAFilename: "ca.pem" # CA Certificate filename
----

=== e. MongoDB 認証情報

このアプリケーションでは、Postgres 認証情報を含む Kubernetes シークレットが必要です。 これは、MongoDB の内部インスタンス (デフォルト) または外部ホストインスタンスのいずれかを使用する場合に当てはまります。 値を紛失した場合、復元できません。 Kubernetes シークレットの管理方法には、2 つのオプションがあります。

[.tab.mongo.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic mongodb-credentials \
  --from-literal=mongodb-root-password=<root-password> \
  --from-literal=mongodb-password=<user-password>
----

下記を `values.yaml` ファイルに追加します。

[source,yaml]
----
mongodb:
  auth:
    existingSecret: mongodb-credentials
----
--

[.tab.mongo.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

認証情報を `values.yaml` に追加します。CircleCI が自動的にシークレットを作成します。

[source,yaml]
----
mongodb:
  auth:
    rootPassword: "<root-password>"
    password: "<user-password>"
----
--

[#rabbinmq-configurations-and-auth-secrets]
=== f. RabbitMQ の設定と Auth シークレット

RabbitMQ のインストールには 2 つのランダムな英数字の文字列が必要です。 値を紛失した場合、復元できません。 Kubernetes シークレットの管理方法には、2 つのオプションがあります。

[.tab.rabbit.You_create_Secret]
--
**オプション 1:** ご自身でシークレットを作成する

[source,shell]
----
kubectl create secret generic rabbitmq-key \
--from-literal=rabbitmq-password=<secret-alphanumeric-password> \
--from-literal=rabbitmq-erlang-cookie=<secret-alphanumeric-key>
----

下記を `values.yaml` ファイルに追加します。

[source,yaml]
----
rabbitmq:
  auth:
    existingPasswordSecret: rabbitmq-key
    existingErlangSecret: rabbitmq-key
----
--

[.tab.rabbit.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

値を `values.yaml` に追加します。CircleCI が自動的に Kubernetes シークレットを作成します。

[source,yaml]
----
rabbitmq:
  auth:
    password: "<secret-alphanumeric-password>"
    erlangCookie: "<secret-alphanumeric-key>"
----
--

[#pusher-kubernetes-secret]
=== g. Pusher 用の Kubernetes シークレット

このアプリケーションでは Pusher 用の Kubernetes シークレットが必要です。 値を紛失した場合、復元できません。 Kubernetes シークレットの管理方法には、2 つのオプションがあります。

[.tab.pusher.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic pusher \
--from-literal=secret=<pusher-secret>
----
--

[.tab.pusher.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

値を `values.yaml` に追加します。CircleCI が自動的に Kubernetes シークレットを作成します。

[source,yaml]
----
pusher:
  secret: "<pusher-secret>"
----
--

[#global]
=== h. Global

このセクションでの値はすべて `values.yaml` の `global` の子です。

[#circleci-domain-name]
==== CircleCI ドメイン名 (必須)

Enter the domain name you specified when creating your xref:phase-1-prerequisites#frontend-tls-certificates[Frontend TLS key and certificate].

[source,yaml]
----
global:
  ...
  domainName: "<full-domain-name-of-your-install>"
----

[#license]
==== ライセンス

CircleCI からライセンスが提供されます。そのライセンスを `values.yaml` に追加します。

[source,yaml]
----
global:
  ...
  license: '<license>'
----

[#Registry]
==== レジストリ

イメージをプルするレジストリが既に提供されている、またはお客様がホストしているレジストリにイメージを追加している場合があります。 そのレジストリを `values.yaml` に追加します。

[source,yaml]
----
global:
  ...
  container:
    registry: <registry-domain eg: cciserver.azurecr.io >
    org: <your-org-if-applicable>
----

[#static-ips]
=== i. 静的 IP アドレス

前提条件のセクションで静的 IP アドレス (GCP) または Elastic IP アドレス (AWS) をプロビジョニングした場合、ここで nginx ブロックの下に値を追加します。

ifndef::env-gcp[]

[#gcp-add-static-ip]
==== GCP: 静的 IP アドレスを追加

GCP の場合は、プロビジョニングした IPv4 アドレスを nginx ブロックの `loadBalancerIp` フィールドの下に追加します。

[source,yaml]
----
nginx:
  ...
  loadBalancerIp: "<gcp-provisioned-ipv4-address>"

----

endif::env-gcp[]

ifndef::env-aws[]

[#aws-add-elastic-ip]
==== AWS: Elastoc IP アドレスを追加

AWS の場合は、`service.beta.kubernetes.io/aws-load-balancer-eip-allocations` の注釈とコンマ区切りのリストとして生成された `AllocationId` の各値を nginx の注釈の下に追加します。 `AllocationId` の数はロードバランサーがデプロイされるサブネットの数と一致している必要があるのでご注意ください (デフォルト設定は 3)。

[source,yaml]
----
nginx:
  ...
  annotations:
    ...
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: <eip-id-1>,<eip-id-2>,<eip-id-3>
----

endif::env-aws[]

[#tls]
=== j. TLS

TLS では 4 つのオプションがあります。

[.tab.tls.Do_nothing]
--
*何もしない* 

何もしません。 自己署名証明書は、自動的に生成されます。  このオプションは試用版には適していますが、本番環境では推奨されません。

NOTE: また、これらの自己署名証明書は、ブラウザによって信頼されません。  アプリケーションにアクセスするには、ブラウザに例外を追加する必要があります。 アップデートがプッシュされると、証明書は新しい自己署名証明書に更新されます。
--

[.tab.tls.Lets_Encrypt]
--
*Let's Encrypt*

https://letsencrypt.org/[Let's Encrypt] が自動的に証明書のリクエストと管理を行います。  ロードバランサーが一般に公開されている場合に有効なオプションです。 以下のスニペット（自分のメールを使用）を `values.yaml` に追加することができます。

[source,yaml]
----
kong:
  acme:
    enabled: true
    email: contact@example.com
----

NOTE: Let's Encryptは、ブラウザに反映されるまでに最大30分程度かかる場合があります。
--

[.tab.tls.Supply_private_key_and_certificate]
--
*プライベートキーと証明書を指定する*

前提条件のステップで作成したプライベートキーと証明書を指定できます。 キーと証明書は Base64 エンコードされている必要があります。 以下のコマンドで取得およびエンコードできます。

[source,bash]
----
cat /etc/letsencrypt/live/<CIRCLECI_SERVER_DOMAIN>/privkey.pem | base64
cat /etc/letsencrypt/live/<CIRCLECI_SERVER_DOMAIN>/fullchain.pem | base64
----

これらを `values.yaml` に追加します。

[source,yaml]
----
tls:
  certificate: '<full-chain>'
  privateKey: '<private-key>'
----
--

[.tab.tls.Use_AWS_Certificate_Manager]
--
*ACM を使用する*

Have link:https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html[AWS Certificate Manager (ACM)] automatically request and manage certificates for you. Follow the link:https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html[ACM documentation] for instructions on how to generate ACM certificates.

`aws_acm` を有効にし、`service.beta.kubernetes.io/aws-load-balancer-ssl-cert` 注釈が ACM ARN を参照するように追加します。

[source,yaml]
----
nginx:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <acm-arn>
  aws_acm:
    enabled: false
----

[WARNING]
====
CircleCI Server をデプロイ済みの場合は、ACM の有効化はロードバランサーに破壊的な変更を加えます。 ACM 証明書の使用を許可するようサービスを再生成し、関連するロードバランサーも再生成する必要があります。
CircleCI Server を再デプロイした場合、DNS レコードを更新する必要があります。
====
--

[.tab.tls.Terminate_TLS_upstream]
--
*CircleCI 内で TLS を無効にする*

CircleCI 内での TLS の終了を無効にすることができます。 システムには HTTPS 経由でのアクセスが必要なため、CircleCI のアップストリームで TLS の終了が求められます。 上記の最初のオプション (何もしない) に従ってこれを実行し、CircleCI ロードバランサーに下記のポートを転送します。


* フロントエンド / API Gateway/ [TCP 80, 443]
* VM サービス [TCP 3000]
* Nomad サーバー[TCP 4647]
* 出力プロセッサ  [gRPC 8585]
--

[#github-integration]
=== k. GitHub との連携

GitHub を CircleCI で設定する場合、デプロイに認証情報を提供する方法が 2 つあります。 GitHub と GitHub Enterprise (GHE) の手順は、次の 2 つのセクションで説明します。

[#github]
==== GitHub

下記は GitHub Enterprise **ではなく** GitHub.com の場合の説明です。 Use the client ID and secret you created with your Github OAuth application in the xref:phase-1-prerequisites#create-a-new-github-oauth-app[prerequisites phase].

[.tab.github.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic github-secret \
  --from-literal=clientId=<client-id> \
  --from-literal=clientSecret=<client-secret>
----
--

[.tab.github.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

`values.yaml` ファイルにクライアント ID とシークレットを追加します。 CircleCI が自動的に Kubernetes シークレットを作成します。

[source,yaml]
----
github:
  clientId: "<client-id>"
  clientSecret: "<client-secret>"
----
--

[#github-enterprise-integration]
==== GitHub Enterprise

GitHub Enterprise の場合も同様の手順ですが、Enterprise を有効化し、必要なデフォルトのトークンを作成するための追加手順がいくつかあります。

In the case of GitHub Enterprise add the `defaultToken` created in the xref:phase-1-prerequisites#create-a-new-github-oauth-app[prerequisite phase] to the `GitHub` section. ホスト名には、`github.exampleorg.com` などのプロトコルを含めないでください。


[.tab.ghe.You_create_Secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

[source,shell]
----
kubectl create secret generic github-secret \
  --from-literal=clientId=<client-id> \
  --from-literal=clientSecret=<client-secret> \
  --from-literal=defaultToken=<default-token>
----

下記を `values.yaml` ファイルに追加します。

[source,yaml]
----
github:
  enterprise: true
  hostname: "<github-enterprise-hostname>"
----
--

[.tab.ghe.CircleCI_creates_Secret]
--
**オプション 2:** CircleCI がお客様の Kubernetes シークレットを作成する

`clientID`、`clientSecret`、 `defaultToken` を `values.yaml` ファイルに追加します。 `enterprise` を `true` に設定し、Enterprise GitHub の `hostname` を指定します。 CircleCI が自動的に Kubernetes シークレットを作成します。

[source,yaml]
----
github:
  ...
  clientId: "<client-id>"
  clientSecret: "<client-secret>"
  enterprise: true
  hostname: "<github-enterprise-hostname>"
  defaultToken: "<token>"
----
--

[#object-storage]
=== l. オブジェクトストレージ

Regardless of your storage provider, the bucket name you created during the xref:phase-1-prerequisites#object-storage-and-permissions[prerequisites phase] will need to be included.

[source,yaml]
----
object_storage:
  bucketName: "<bucket-name>"
----

// Don't include this section in the GCP PDF.

ifndef::env-gcp[]

[#s3-compatible]
==== S3 互換

`s3` のセクションを `object_storage` の子として追加します。 The `endpoint` in the case of AWS S3 is the link:https://docs.aws.amazon.com/general/latest/gr/rande.html[regional endpoint], it is of the form `https://s3.<region>.amazonaws.com`. それ以外の場合は、オブジェクトストレージサーバーの API エンドポイントです。

[source,yaml]
----
object_storage:
  ...
  s3:
    enabled: true
    endpoint: "<storage-server-or-s3-endpoint>"
----

`object_storage.s3` の配下に、前提条件のステップで作成した `accessKey` 、 `secretKey` 、`irsaRole` のいずれかを指定します。 または何も指定しません。

[.tab.s3compatible.Use_IAM_keys]
--
**オプション 1:** IAM キーを使用する

NOTE: このオプションは、パイプラインに 5GB を超えるアーティファクトが保存されている場合は推奨しません。 MinIO バックエンドの制限により、IAM キーを使用した 5GB を超えるオブジェクトの S3 へのアップロードは失敗します。 5GB 以上のオブジェクトの場合は、下記の IRSA を使用してください。

以下を `object_storage.s3` セクションに追加します。

[source,yaml]
----
object_storage:
  ...
  s3:
    ...
    accessKey: "<access-key>"
    secretKey: "<secret-key>"
----
--

[.tab.s3compatible.Use_IRSA]
--
**オプション 2:** IRSA を使用する

認証情報を使って Kubernetes シークレットが自動的に作成されます。

以下を `object_storage.s3` セクションに追加します。

[source,yaml]
----
object_storage:
  ...
  s3:
    ...
    region: "<role-region>"
    irsaRole: "<irsa-arn>"
----
--

[.tab.s3compatible.You_create_Secret]
--
**オプション 3:** ご自身で Kubernetes シークレットを作成する

AWS アクセスキーとシークレットキーの認証情報を `values.yaml` ファイルに指定する代わりに、ご自身で Kubernetes シークレットを作成することも可能です。

[source,shell]
----
kubectl create secret generic object-storage-secret \
  --from-literal=s3AccessKey=<access-key> \
  --from-literal=s3SecretKey=<secret-key>
----
--

CircleCI Server は S3 への認証で提供されたロールを使用します。

// Stop hiding from GCP PDF:

endif::env-gcp[]

// Don't include this section in the AWS PDF:

ifndef::env-aws[]

[#google-cloud-storage-object-storage]
==== Google Cloud Storage

`object_storage` の配下に以下を追加します。

[source,yaml]
----
gcs:
    enabled: true
----

`object_storage.gcs` の配下に `service_account` か `workloadIdentity` のいずれかを追加します。またはどちらも追加しません。 キーとロールは前提条件のステップで作成しています。

[.tab.gcs.Use_service_account]
--
**オプション 1:** サービスアカウントを使用する

サービスアカウントの JSON キーを追加してバケットへのアクセスに使用します。  以下を `object_storage.gcs` セクションに追加します。

[source,yaml]
----
service_account: "<service-account>"
----
--

[.tab.gcs.Use_Workload_Identity]
--
**オプション 2:** Workload Identity を使用する

Workload Identity のサービスアカウントのメールを追加します。  以下を `object_storage.gcs` セクションに追加します。

[source,yaml]
----
workloadIdentity: "<workload-identity-service-account-email>"
----
--

[.tab.gcs.You_create_Secret]
--
**オプション 3:** ご自身で Kubernetes シークレットを作成する

サービスアカウントを `values.yaml` ファイルに保存する代わりに、ご自身で Kubernetes シークレットを作成することもできます。 

[source,shell]
----
kubectl create secret generic object-storage-secret \
  --from-literal=gcs_sa.json=<service-account>
----
--

// Stop hiding from AWS PDF

endif::env-aws[]

=== m. プロキシ経由でのインストール

セキュリティ要件に応じて、CircleCI Server をプロキシ経由でインストールすることも可能です。 プロキシ経由で設定することにより、お客様のインストール環境とインターネット全体のアクセスを監視・制御することができます。 For further information including limitations of installation behind a proxy, see the xref:installing-server-behind-a-proxy#[Installing server behind a proxy] guide.

以下のフィールドを `values.yaml` に設定する必要があります。

* `proxy.enabled` を `"1"` に切り替えます。
* `proxy.http.host` と `proxy.https.host` の詳細を関連付けられているポートと共に入力します。 これらの値は同じでも構いませんが、両方とも設定する必要があります。
* 認証用に `proxy.http.auth.enabled` と `proxy.https.auth.enabled` を `"1"` に設定する必要があります。 HTTP と HTTPS の両方にそれぞれユーザー名とパスワードを設定する必要があります。
* `no_proxy` ホストとサブネットを設定します。 This should include localhost, your GitHub Enterprise host (optional), the hostname of your CircleCI installation (see xref:installing-server-behind-a-proxy#known-limitations[Known Limitations] for an explanation), and the CIDRs of both vm-service and Nomad.

[source,yaml]
----
proxy:
  enabled: "1"
  http:
    host: "<proxy.example.internal>"
    port: "3128"
    auth:
      enabled: "1"
      username: "<proxy-user>"
      password: "<proxy-password>"
  https:
    host: "<proxy.example.internal>"
    port: "3128"
    auth:
      enabled: "1"
      username: "<proxy-user>"
      password: "<proxy-password>"
  no_proxy:
    - localhost
    - 127.0.0.1
    - "<github.example.internal>"
    - "<circleci.example.internal>"
    - "<nomad-subnet-cidr>"
    - "<vm-service-cidr>"
    - "<vpc-or-subnet-cidr>"   # VPC or subnets to exclude from the proxy (optional)
----

=== n. Encrypting Environment Variables

All environment variables stored in contexts are encrypted using either https://www.vaultproject.io/[Hashicorp Vault] or  https://developers.google.com/tink[Google Tink]. By Default, CircleCI server 4.x will use Vault to generate and store encryption keys.

==== Use Tink (optional)

The following steps cover using Tink as an alternative to Vault:

. Enable Tink in your `values.yaml`:
+
[source,yaml]
----
tink:
  enabled: false
  keyset: ""
----
+
When `tink.enabled` is true, Vault will not be deployed.
+
WARNING: Tink or Vault must be set once during installation, and cannot be changed after deployment.
. Generate a link:https://developers.google.com/tink/design/keysets[keyset], which Tink uses to manage key rotation. The easiest way to do this is to use Google's link:https://developers.google.com/tink/tinkey-overview[Tinkey] CLI utility. Once https://developers.google.com/tink/install-tinkey[installed], use the following command:
+
[source,shell]
----
tinkey create-keyset --key-template XCHACHA20_POLY1305
----
. CircleCI server will store your generated keyset in a Kubernetes secret. You may generate this secret in either of the following ways:
+
[.tab.tink.you_create_secret]
--
**オプション 1:** ご自身で Kubernetes シークレットを作成する

Following the example below, create a Kubernetes secret with the name `tink` and a key `keyset`. Apply this secret to the namespace of your CircleCI server installation.

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: tink
data:
  keyset: <your-keyset>
----
--
+
[.tab.tink.circleci_creates_secret]
--
**Option 2:** CircleCI Server will create the Kubernetes Secret

You may add the keyset to your `values.yaml` under `tink` as in the example below. CircleCI will generate the required secret to store your keyset.

[source,yaml]
----
tink:
  enabled: false
  keyset: "<your-keyset>"
----
--

WARNING: If your Tink keyset is somehow lost, you will need to generate a new keyset and then recreate your contexts and their associated secrets.

[#deploy]
== 4. デプロイ

上記項目の設定が完了したら、いよいよ CircleCI のコアサービスのデプロイです。

[source,shell,subs=attributes+]
----
USERNAME=<provided-username>
PASSWORD=<token>
namespace=<your-namespace>
helm registry login cciserver.azurecr.io/circleci-server -u $USERNAME -p $PASSWORD
helm install circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version {serverversion41} -f <path-to-values.yaml>
----

[#create-dns-entry]
== 5. DNS エントリーを作成します

NGINX  ロードバランサー の DNS エントリを作成します (例: `circleci.your.domain.com`  と `app.circleci.your.domain.com` )。
 この DNS エントリは、前提条件のステップで TLS 証明書とGitHub OAuth アプリケーションを作成する際に使用した DNS 名と一致している必要があります。 すべてのトラフィックは、この DNS レコードを介してルーティングされます。

IP アドレスが必要です。AWS を使用している場合は、NGINX ロードバランサーの DNS 名が必要です。 以下のコマンドで情報を入手します。

[source,shell]
----
kubectl get service circleci-proxy
----

[#validation]
== 6. バリデーション

これで、CircleCI Server に移動し、アプリケーションに正常にログインできます。

次は、サービスのビルドを行います。 すべてのサービスが立ち上がるまで時間がかかる場合があります。 次のコマンドを実行して定期的に確認します (ステータスが `running` の `frontend` Pod を探し、**ready** には  1/1 と表示されいてる必要があります）。

[source,shell]
----
kubectl get pods -n <YOUR_CIRCLECI_NAMESPACE>
----

NOTE: この段階では VM サービスと Nomad サーバーのポッドは失敗します。 次のインストールステップで実行環境を設定します。

ifndef::pdf[]

[#next-steps]
== 次のステップ

* xref:phase-3-execution-environments#[Phase 3: Execution Environments Installation]
+
endif::[]