---

description: CircleCI Server 4.x の各リリースに含まれる新機能の詳細
version:
- Server v4.x
- サーバー管理者
---
= CircleCI Server v4.x リリースノート
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro

:toc-title:

Server v4.x offers the following:

* Greatly improved security handling, installation, and update processes.
* Installed using Helm charts and images that can be pulled ahead of time to comply with your security processes.
* Installation processes can use artifacts pulled from customer-managed registries.
* Improved use of Kubernetes secrets and removes the requirement to grant permissions and network access to third-party tools.

== Migrate from v3.x to v4.x

既存の CircleCI Server v3.x から v4.x への移行、または v2.x から v4.x への移行をご希望のお客様は、担当のカスタマーサクセスマネージャーにお問い合わせください。 CircleCI Server 4.x では、毎月のパッチリリースと四半期ごとの機能リリースを予定しています。

Find information about migration in the link:/docs/server/installation/migrate-from-server-3-to-server-4[Migrate From Server v3 to v4 Guide].

[#upgrade]
== Upgrade

For upgrade steps see the link:/docs/server/installation/upgrade-server-4[Upgrade Server v4 Guide].

[#release-4-0-1]
== リリース 4.0.1

[#changelog-4-0-1]
=== 更新履歴

For full details of this release see the https://circleci.com/server/changelog/#release-4-0-1[changelog].

[#release-4-0-0]
== リリース 4.0.0

[#changelog-4-0-0]
=== 更新履歴

このリリースの詳細は、 https://circleci.com/ja/server/changelog/#release-4-0-0[更新履歴] を参照して下さい。