---

contentTags:
  platform:
  - Server v4.1
  - サーバー管理者
---
= フェーズ 5 - インストールのテスト
:page-layout: classic-docs
:page-liquid:
:page-description: エアギャップ環境にインストールした CircleCI Server をテストする方法について説明します。
:icons: font
:toc: macro
:toc-title:

CircleCI の Reality Check プロジェクトを使用して、エアギャップ環境にインストールした CircleCI Server をテストします。

[#copy-reality-check]
== 1.  CircleCI Server Reality Check をコピーする

link:https://github.com/circleci/realitycheck[CircleCI Server Reality Check リポジトリ]を、エアギャップ環境の GitHub Enterprise インスタンスにコピーします。

[#setup-reality-check]
== 2. CircleCI Server Reality Check を設定する

link:https://github.com/circleci/realitycheck#installation[README の説明]に従って CircleCI Server Reality Check を設定します。

CAUTION: `CIRCLE_CLOUD_PROVIDER` 環境変数は `other` に設定してください。

[#modify-reality-check]
== 3.  Reality Check のソースコードを編集する

.circleci/config.yml で参照されている Docker イメージを、内部 Docker レジストリに変更します。

たとえば、このレジストリが GitHub Enterprise インスタンス内にある場合は、以下のように変更します。

[source, yaml]
----
  ...
  artifacts_test_results:
    docker:
      - image: python:3.6.0
----

[source, yaml]
----
  ...
  artifacts_test_results:
    docker:
      - image: <your-internal-registry-hostname-and-port>/python:3.6.0
----

NOTE: "machine" キーの image 値は変更しないでください。 変更するのは docker キーの image 値のみです。

[#run-reality-check]
== 4.  Reality Check を実行する

GitHub Enterprise インスタンスに変更内容をプッシュして、Reality Check を実行します。

NOTE: `CIRCLE_CLOUD_PROVIDER` 環境変数を `other` に設定しているため、`aws_jobs` と `gcp_jobs` の各ワークフローは自動的にキャンセルされます。