= Stop building a project on CircleCI
:page-platform: Cloud, Server v4+
:page-description: Learn how to remove a project from your CircleCI account
:experimental:

[#introduction]
== Introduction
This page outlines how to stop builds for a project on CircleCI.

For how this option fits together with **Block all new work**, cancelling running workflows, and follower behavior during an incident, see xref:orchestrate:pause-pipelines-during-an-incident.adoc[Pause or stop pipelines during an incident].

[#stop-building-a-project]
== Stop building a project

CAUTION: The **Stop Building** option does not automatically remove all project data from the CircleCI databases. To remove all project data from CircleCI, see the xref:security:delete-organizations-and-projects.adoc#delete-a-project[Delete a project] documentation.

include::ROOT:partial$notes/standalone-unsupported.adoc[This feature is not supported for GitLab, GitHub App or Bitbucket Data Center]

NOTE: **Stop Building** unfollows all project followers, cancels all running workflows in the background, and removes VCS integration (webhook and deploy key). If you only want to prevent **new** pipelines while keeping the project connected and letting in-progress workflows finish, use xref:orchestrate:skip-build.adoc#enable-block-new-work-for-a-project[Block all new work] in Advanced project settings instead.

If you are using the GitHub OAuth App or Bitbucket Cloud, to stop building one of your projects on CircleCI, follow these steps:

. Go to the **Project Settings** page in the CircleCI web app for the project you want to stop.
. Scroll to the bottom of the Overview page and select **Stop Building**. You will need to reconfirm your choice in the popup.

NOTE: If you want to start building this project again, just go to the **Projects** page in the web app and select **Set Up Project** and follow the set up steps.
