== Applications

In Vamp, an application is a collection of microservices sharing the same Kubernetes namespace.

You can view your applications under the _Applications_ tab. Click the *+* sign to display which versions of each service are currently deployed for the application and their status.

// Screenshot - circle the + sign

=== Creating an application

To create a new application, click the *+Create Application* button on the Applications page.

include::../includes/applications.adoc[]

Once you have finished adding the details for your application, click **Create application** in the bottom left-hand corner. You will see a pop-up message to confirm that your application has been created.

// Add content on Ingress and services here?

=== Editing an application

To edit an application, click *Details* next to its name in the list under the _Applications_ tab.

// screenshot

When you have finished editing the details, click the *Update application* button in the bottom left-hand corner. You will see a pop-up message to confirm that your application details have been updated.

=== Deleting an application

To delete an application, click *Details* next to its name in the list under the _Applications_ tab.

Click the red *Delete application* button in the bottom left-hand corner. You will be asked to confirm the deletion by typing the application name in a pop-up box. You can then click the red *Delete* button.

// add screenshot

You will see a pop-up message to confirm that your application has been deleted.