== Custom Metrics

To view your current custom metrics, click _Metrics_ under the _Policies_ tab.

// screenshot

=== Creating a custom metric

To create a custom metric, click *+Create Metric* in the top right-hand corner of the Metrics page.

==== Step 1 - Name

Name - enter a distinctive name for the metric. This name will be displayed wherever the metric is used, for example, in alerts.

Description - an optional description to help other users understand how to use the metric.

==== Step 2 - Data Source

Type - time-based or event-based

Data Source

// this is greyed out - presumably because there's no alternative to Prometheus?

Time Window Type

Rolling time interval - a time window where the end time is now and the start time is always in the past.

Fixed time interval

// This option is greyed out

Default time window (in seconds, e.g. 60s) - the duration of the time window used to calculate the SLO. This can be overriden in a policy.

// link to policies?

When you have finished configuring the data source for your custom metric, click the blue *Next* button.

==== Step 3 - Query

Data Source - has to be Prometheus

Query - An expression written in the Prometheus Query Language. The result of the expression should be a scalar value.

// need to signpost PQL

Purpose - ingress traffic metric or other

==== Step 4 - Budget

Type - Define Global Default / Define in Every Policy

Choose whether to set a default baseline or require a baseline to be set in each policy. The default can be overridden in a policy.

Threshold - The baseline threshold. This value should be a scalar expressed in the same units query. For example, a maximum of 20 test metrics per time window.


When you have finished configuring your custom metric, click the blue *Create* button. You will see a pop-up message to confirm that your custom metric has been created.

Alternatively, you can click *Previous* to edit any of the previous steps.

=== Editing a custom metric

To edit a custom metric, click on it in the Metrics list (accessible under the _Policies_ tab).

When you have finished configuring your custom metric, click the blue *Create* button. You will see a pop-up message to confirm that your custom metric has been updated.

Alternatively, to cancel your changes, click the *x* in the top right-hand corner.

=== Deleting a custom metric

IMPORTANT: You cannot delete a custom metric that is in use by a policy applied to an application.

// check this and make the wording clearer.