== Releases

=== Blue/Green Release

A blue/green release uses two identical environments called _blue_ and _green_. The current live version is _blue_; the new version is _green_.

A blue/green release policy includes only one step that targets all your users. At the start of the step, all users are switched from the live _blue_ version to the new _green_ version.

The Release Agent monitors the performance of the new version. If everything is released successfully, the policy completes with the _green_ version becoming the live version.

If the new version does not meet all the conditions specified in the release policy, the Release Agent immediate rolls back by switching all users to the _blue_ version.

=== Canary Release

A canary release uses a subset of users to identify any issues before a new version is rolled out to all users.

A canary release policy typically includes three or more steps that  target progressively larger subsets of users. A step can target a percentage of your users, or it can target a specific user segment.

The Release Agent monitors the performance of the new version. If everything is released successfully, the policy completes with all users receiving the new version.

If the new version does not meet all the conditions specified in the release policy, the Release Agent immediately rolls back by switching all users to the current, live version.