= New Relic integration
:page-platform: Cloud, Server v4+
:page-description: This document describes how to track and visualize analytical data across all of your jobs on CircleCI with New Relic.

This page describes how to connect Insights data with link:https://newrelic.com/[New Relic].

[#overview]
== Overview
The link:https://newrelic.com/instant-observability/circleci[New Relic CircleCI integration] allows you to view analytical data about their CircleCI jobs within the New Relic monitoring stack.

[#integration]
== Integration

Complete the following steps to set up a CircleCI webhook to forward your logs to New Relic. For more information, refer to the New Relic CircleCI link:https://docs.newrelic.com/docs/logs/forward-logs/circleci-logs/[installation docs].

. Log in to the link:https://app.circleci.com)[CircleCI web app].

. Access one of your CircleCI projects.

. Open **Project settings**.

. In the project settings sidebar, select **Webhooks**.

. Select **Add webhook**.

. Complete the following fields:
** **Webhook name**: give your webhook an identifiable name, for example, `New Relic CI Visibility`
** **Receiver URL**: Use New Relic's **Logs endpoint**. Use the region you set for your New Relic account.
+
Replace `YOUR_LICENSE_KEY` with your New Relic license key, which you can link:https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#manage-license-key[retrieve from the UI or API].
+
**US**: `https://log-api.newrelic.com/log/v1?Api-Key=YOUR_LICENSE_KEY`
+
**EU**: `https://log-api.eu.newrelic.com/log/v1?Api-Key=YOUR_LICENSE_KEY`
** **Events**: Select **Workflow Completed** or **Job Completed**, depending on the type of event you want to trigger the logpush
** Enable the check: **Certificate verifications**

. Select **Add Webhook** to save the new webhook.

. If you have set up your receiving API or third-party service, click **Test ping event** to create a test event.
