---
title: Job status
---
%%{init: {'theme':'base', 'themeVariables': {'primaryBorderColor': '#00DB74', 'lineColor': '#00DB74', 'primaryColor': '#2E3C52', 'primaryTextColor': '#00DB74', 'secondaryColor': '#00DB74', 'tertiaryColor': '#f00', 'fontSize': '18px', 'fontFamily': 'Inter'}}}%%
stateDiagram-v2
    [*] --> blocked

    blocked --> unauthorized: Trying to use a context without permission

    blocked --> pending
    pending --> blocked

    pending --> skipped
    pending --> running
    pending --> terminatedUnknown

    running --> success
    running --> failed
    running --> cancelled
    running --> terminatedUnknown