= Manage groups
:page-platform: cloud
:page-vcs: all
:page-audience: developer
:page-description: How-to guides for setting up and assigning groups in CircleCI to manage roles and permissions across projects.
:experimental:

If you have a `circleci` type organization, the content on this page applies to you.

include::ROOT:partial$tips/check-org-type.adoc[]

Use groups to manage access to projects and features. Create groups based on teams or roles within your organization. Then, add a user to a group to give them access to all required projects, such as mobile or DevOps projects. For more information about the roles available and their associated permissions, see the xref:roles-and-permissions-overview.adoc[Roles and Permissions] overview page.

The how-to guides on this page provide steps for some common group management tasks.

[#prerequisites]
== Prerequisites

* A CircleCI account connected to your code. You can link:https://circleci.com/signup/[sign up for free].
* At least one project created in your organization. See the xref:getting-started:create-project.adoc[Create a Project] page for instructions.

[#create-a-group]
== Create a group

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Org** in the sidebar.
. Select **Groups** from the sidebar.
. Select btn:[Create Group].
. Enter a name and description (optional) for your group.
. Select btn:[Create Group].

View your new group in the groups list. Click on the group name to view details. You can now <<add-people-to-a-group,add people to the group>>.

[#add-people-to-a-group]
== Add people to a group

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Org** in the sidebar.
. Select **Groups** from the sidebar.
. Select on the name of the group you want to add people to.
. On the group page, click btn:[Add members].
. In the popup, search or scroll for users to add to your group. You can select multiple users on one session. When you have made your selection, click btn:[Save].

[#add-a-group-to-a-project]
== Add a group to a project

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Projects** in the sidebar.
. Select on the ellipsis next to your project icon:more[Ellipsis menu icon] and then select **Project Settings**.
. Select **Groups** from the sidebar.
. Select btn:[Add Groups].
. Select the group name and then use the dropdown to assign a project role (Admin/Contributor/Viewer).

[#assign-a-new-project-role-to-a-group]
== Assign a new project role to a group

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Projects** in the sidebar.
. Select on the ellipsis next to your project icon:more[Ellipsis menu icon] and then select **Project Settings**.
. Select **Groups** from the sidebar.
. Locate the group in the list and open up the "Project Grant" dropdown to access all role options.
. Select the new role you wish to assign to the group for this project. You will see a notification to confirm when the change is complete.

[#delete-a-group]
== Delete a group

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Org** in the sidebar.
. Select **Groups** from the sidebar.
. Select on the name of the group in the list to view the group details page.
. Select btn:[Delete group].

[#remove-a-user-from-a-group]
== Remove a user from a group

NOTE: To do this, you must have the _Organization Admin_ role.

. In the CircleCI web app, click on **Org** in the sidebar.
. Select **Groups** from the sidebar.
. Select on the name of the group in the list.
. Select on the checkbox next to the user you want to remove from the group, and click btn:[Remove Members].
