= Sign in to an SSO-enabled organization
:page-platform: Cloud
:page-description: Instructions outlining how to sign in as an SSO user
:experimental:

NOTE: SAML single sign-on for CircleCI is available for Scale Plan customers. See xref:sso-overview.adoc#prerequisites-and-limitations[Prerequisites and Limitations]
for further details.
[#join-an-organization]
== Join an organization

To join an SSO-enabled CircleCI organization, you need an active CircleCI account. Log in with an email and password, or with social logins like GitHub or Bitbucket. For more information on creating a CircleCI account, see the xref:getting-started:first-steps.adoc[Sign up and Try] page.

NOTE: If you use OAuth/social login to join CircleCI, it is important to SSO authorize in GitHub/Bitbucket as well as in CircleCI.

Once you have a CircleCI account you can join an SSO-enabled CircleCI organization in one of the following ways:

* Get xref:manage-roles-and-permissions.adoc#add-people-to-your-organization[An Invite].
* Visit the CircleCI link:https://app.circleci.com/home/[home page]. Select the **Join Organization** dropdown, and then select the option to **Join via SSO**.
* Via your organization's Identity Provider (IdP).

[#log-in-to-an-organization]
== Authenticate with SSO for an organization

You must be logged in to your CircleCI account in order to authenticate with SSO for an organization.

If your SSO session has expired, the next time you access your organization's resources, your organization's IdP will prompt you to authenticate again.

When your session expires, you will be prompted to re-authenticate.
