---

contentTags:
  platform:
    - Server v4.1
    - Server Admin
---
= Operator overview
:page-layout: classic-docs
:page-liquid:
:page-description: CircleCI Server のインストールの管理における様々なタスクとツールについて説明します。
:icons: font
:toc: macro

:toc-title:

このガイドでは、CircleCI Server x の保守や監視を行う CircleCI Server のオペレーターの皆さんに役立つ情報を紹介します。 Before reading this operator guide, ensure you have read the xref:../overview/circleci-server-overview#[CircleCI server v4.1 overview].

CircleCI server schedules CI/CD jobs using the link:https://www.nomadproject.io/[Nomad] scheduler. Nomad サーバー (コントロールプレーン) が Kubernetes クラスタ内で動作するのに対し、Nomad クライアントはクラスタ外部にプロビジョニングされます。 The Nomad clients need access to the Nomad control plane, output processor, and VM service.

CircleCI Server では、Nomad クライアントまたは専用の仮想マシンで Docker ジョブを実行できます。 These VM jobs are controlled by the Nomad clients, therefore the Nomad clients must be able to access the VMs on port 22 for SSH and port 2376 for xref:../../../configuration-reference#setupremotedocker[remote Docker jobs].

ジョブのアーティファクトと出力は、Nomad ジョブからオブジェクトストレージ (S3、GCS、またはその他のサポートされているオプション) に直接送信されます。

オブジェクトストレージには、監査ログやアプリケーションのその他のアイテムも保存されます。そのため、Kubernetes クラスタと Nomad クライアントの両方がオブジェクトストレージにアクセスできる必要があります。

[#execution-environment]
== 実行環境

CircleCI Server v4.x では、プライマリジョブスケジューラとして Nomad を使用します。 Refer to our xref:introduction-to-nomad-cluster-operation#[Introduction to Nomad Cluster Operation] to learn more about the job scheduler and how to perform basic client and cluster operations.

CircleCI の Nomad クライアントは、プロジェクトの `.circleci/config.yml` ファイルでジョブごとに設定されている Executor に従って、コンピューティングリソースを自動的にプロビジョニングします。

[#nomad-clients]
=== Nomad クライアント

Nomadクライアントは実行後に状態を保持しないため、必要に応じてコンテナ数を増減することができます。

ジョブのリソースクラスで必要なリソースが Nomad クライアントのインスタンスタイプで利用可能な量を超える場合、ジョブは保留状態のままになります。 Nomad クライアントのインスタンスタイプを小さいものにするとコストを削減できますが、使用できる Docker リソースクラスが制限されます。 Review the xref:../../../configuration-reference#resourceclass[available resource classes] to decide what is best for you. デフォルトのインスタンスタイプでは、最大で `xlarge` のリソースクラスを実行できます。

See the link:https://www.nomadproject.io/docs/install/production/requirements#resources-ram-cpu-etc[Nomad Documentation] for options for optimizing the resource usage of Nomad clients.

NOTE: Nomad クライアントマシンの最大サイズは RAM 128GB/64 CPUです。 使用する Nomad クライアントマシンのサイズを大きくしたい場合は、CircleCI のアカウント担当者にお問い合わせください。

Nomad ポートの要件に関する詳細は、 https://circleci.com/docs/server/installation/hardening-your-cluster/[クラスタのハードニング]を参照してください。

[#github]
=== GitHub

CircleCI では、GitHub または GitHub Enterprise を ID プロバイダーとして使用しています。 また GitHub Enterprise では代わりに、 https://docs.github.com/en/github-ae@latest/admin/authentication/about-identity-and-access-management-for-your-enterprise[SAML または SCIM] を使って、外部の ID プロバイダーでユーザーを管理することができます。

NOTE: CircleCI では、セットアップ後の URL やバックエンドの GitHub インスタンスの変更には対応していません。

以下の表に、GitHub を実行するマシンでサービス および Nomad クライアントインスタンスと通信する際に使用されるポートを示します。

[.table.table-striped]
[cols=3*, options="header", stripes=even]
|===
|ソース
|ポート
|用途

|サービス
|22
|Git access

|サービス
|80 or 443
|API access

|Nomad Client
|22
|Git access

|Nomad Client
|80 or 443
|API access
|===

ifndef::pdf[]

[#next-steps]
== 次のステップ

* <<introduction-to-nomad-cluster-operation#,Nomad クラスタの運用ガイド>> をお読みください。
+
endif::[]