---
description: "Details of the new features included in each CircleCI server 4.x release."
version:
- Server v4.x
- Server Admin
---
= CircleCI server v4.x release notes
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

Server v4.x offers the following:

* Greatly improved security handling, installation, and update processes. 
* Installed using Helm charts and images that can be pulled ahead of time to comply with your security processes. 
* Installation processes can use artifacts pulled from customer-managed registries. 
* Improved use of Kubernetes secrets and removes the requirement to grant permissions and network access to third-party tools. 

== Migrate from v3.x to v4.x

For existing customers interested in migrating from v3.x to v4.x, or v2.x to v4.x contact your customer success manager. Server v4.x will receive monthly patch releases and quarterly feature releases.

Find information about migration in the link:../server/installation/migrate-from-server-3-to-server-4[Migrate From Server v3 to v4 Guide].

[#upgrade]
== Upgrade
For upgrade steps see the link:../server/installation/upgrade-server-4[Upgrade Server v4 Guide]. 

[#release-4]
== Release 4.0.1

[#changelog]
=== Changelog

For full details of this release see the https://circleci.com/server/changelog/#release-4-0-1[changelog].

[#release-4]
== Release 4.0.0

[#changelog]
=== Changelog

For full details of this release see the https://circleci.com/server/changelog/#release-4-0-0[changelog].