[#operating-systems-circleci-20-support]
=== CircleCI  がサポートする OS は？

- xref:using-linuxvm#[Linux]
- xref:android-machine-image#[Android]
- xref:using-macos#[macOS]
- xref:testing-ios#[iOS]
- xref:using-windows#[Windows]

[#cpu-architecture-circleci-support]
=== CircleCI ではどの CPU アーキテクチャをサポートしていますか?

Docker ジョブでは amd64を、マシンジョブでは amd64 と xref:using-arm#[ARM リソース] をサポートしています。

[#ipv6-in-tests]
=== テストで IPv6 を利用できますか?

IPv6 によるローカル通信のテストでは、xref:configuration-reference#machine [Machine Executor] を利用できます。 残念ながら、WAN における IPv6 通信はサポートしていません。CircleCI が使用しているクラウドサービスの全てが IPv6 をサポートしているわけではないためです。

Machine Executor で実行しているホストは、`eth0` や `lo` といったネットワークインターフェースに対して IPv6 アドレスが割り当てられます。

IPv6 環境のサービスをテストするために、コンテナに IPv6 アドレスを割り当てるように Docker を構成することも可能です。  下記のように Docker デーモンを設定することでグローバル設定を有効にできます。

[source,yaml]
----
jobs:
  ipv6_tests:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: enable ipv6
          command: |
            cat <<'EOF' | sudo tee /etc/docker/daemon.json
            {
              "ipv6": true,
              "fixed-cidr-v6": "2001:db8:1::/64"
            }
            EOF
            sudo service docker restart
----

Docker に IPv6 アドレスを割り当てる手法はいくつかあります。1 つは上記のように link:https://docs.docker.com/config/daemon/ipv6/[デーモンを設定する方法]、2 つ目は link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create` command] コマンドを用いる方法、そして link:https://docs.docker.com/compose/compose-file/#enable_ipv6[`docker-compose`] を利用する方法です。