[#operating-systems-circleci-20-support]
=== CircleCI  がサポートする OS は？

- xref:using-linuxvm#[Linux]
- xref:android-machine-image#[Android]
- xref:using-macos#[macOS]
- xref:testing-ios#[iOS]
- xref:using-windows#[Windows]

[#cpu-architecture-circleci-support]
=== CircleCI 2.0 ではどの OS をサポートしていますか?

CircleCI supports `amd64` for Docker jobs, and both `amd64` and xref:using-arm#[Arm resources] for machine jobs.

[#ipv6-in-tests]
=== コンテナベース プラン

You can use the xref:configuration-reference#machine[Machine executor] for testing local IPv6 traffic. 残念ながら、WAN における IPv6 通信はサポートしていません。CircleCI が使用しているクラウドサービスの全てが IPv6 をサポートしているわけではないためです。

Hosts running with machine executor are configured with IPv6 addresses for `eth0` and `lo` network interfaces.

IPv6 環境のサービスをテストするために、コンテナに IPv6 アドレスを割り当てるように Docker を構成することも可能です。  下記のように Docker デーモンを設定することでグローバル設定を有効にできます。

[source,yaml]
----
jobs:
  ipv6_tests:
    machine:
      # The image uses the current tag, which always points to the most recent
      # supported release. If stability and determinism are crucial for your CI
      # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: enable ipv6
          command: |
            cat <<'EOF' | sudo tee /etc/docker/daemon.json
            {
              "ipv6": true,
              "fixed-cidr-v6": "2001:db8:1::/64"
            }
            EOF
            sudo service docker restart
----

Docker allows enabling IPv6 at different levels: link:https://docs.docker.com/engine/userguide/networking/default_network/ipv6/[globally via daemon config like above], with link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create` command], and with link:https://docs.docker.com/compose/compose-file/#enable_ipv6[`docker-compose`].