[#what-are-credits]
=== クレジットとは何ですか？

クレジットは、マシンのタイプとサイズに基づく使用料の支払いに充てられます。 また、Docker レイヤー キャッシュなどの有料機能を使用したときにも消費されます。

たとえば、毎分 10 クレジットのレートで Docker または Linux の Medium コンピューティングオプションを利用する場合、25,000 クレジットのパッケージでは 2,500 分のビルドが可能です。 CircleCI ではパフォーマンス (開発者の生産性の向上) と価値を備えた最適なビルドを行なっていただけるよう複数のコンピューティングサイズを提供しています。

必要に応じて、並列実行を使用するとビルド時間をさらに短縮できます。並列実行により、ジョブを複数のテストに分割し、同時に実行できます。 2 倍の並列実行により、通常 2,500 分で実行されるビルドが 1,250 分で実行できるため、開発者の生産性がさらに向上します。 2つの Executor がそれぞれ 1,250 分間並行して実行している場合、合計ビルド時間は 2,500 分になります。

[#buy-credits-in-any-increments]
=== クレジットを購入するには？ 必要な分だけ購入することは可能ですか?

選択したクレジットパッケージの料金が、毎月初めに請求されます。

[#what-do-i-pay-for]
=== 支払う料金の内訳はどのようになっていますか?

プレミアム機能を利用するアクティブユーザーの人数分の料金、コンピューティングに対する料金のほか、Premium サポートを利用している場合はその料金も含まれます。

* マシンサイズを選べる機能などを利用するには、１アクティブ ユーザーあたり月額 25,000 クレジット (税抜) が必要です。
* コンピューティングの月額料金は、マシンのサイズと使用時間に基づいて、クレジットで支払われます。
** 25,000 クレジットで 1 パッケージとなっており、1 パッケージは 15 ドル (税抜) です。
** クレジットは毎月持ち越され、1 年後に失効します。
* Docker レイヤー キャッシュ (DLC) の料金は、コンピューティングと同じく、使用量に基づいてクレジットで支払われます。

[#run-out-of-credits]
=== クレジットを使い切るとどうなりますか?

Performance プランでは、0 クレジットになると、25% のクレジットサブスクリプション (最低 25,000 クレジット) が補充されます。 たとえば、毎月のパッケージ サイズが 100,000 クレジットの場合には、残りが 2,000 クレジットになると、25,000 クレジットが自動的にチャージされます (1 クレジットあたり税抜 0.0006 ドル)。

アカウントで補充が繰り返し行われている場合は、 CircleCI ウェブアプリにログインし、`Plan` > `Plan Usage` をクリックしクレジットの使用量を確認してください。 多くの場合、クレジットパッケージを増やすことにより補充の繰り返しを最小限に抑えることができます。 プランを管理するには、 `Plan Overview` をクリックしてください。

Free プランでは、クレジットがなくなるとジョブの実行に失敗します。

[#do-credits-expire]
=== クレジットに有効期限はありますか？

Performance プランのクレジットは、購入後 1 年で失効します。 アカウントのサブスクリプションを停止した場合も、未使用のクレジットは失効します。

[#how-do-i-pay]
=== 支払い方法は？

毎月の料金は CircleCI アプリ内で支払えます。

[#when-do-i-pay]
=== 支払いのスケジュールは？

Performance プランでは、請求サイクルの初日に、Premium サポートの料金と毎月のクレジットパッケージの料金が請求されます。 その月の間にクレジットが補充された場合 (利用可能なクレジットがが0になったときに25%で自動補充する場合など) は、補充時に支払いが行われます。

[#what-is-prepaid-billing]
=== プリペイド課金とは何ですか？

プリペイド課金は、Performance プランのお客様向けの支払いオプションです。 プリペイド課金では、クレジットを一括購入し、前払いすることができ、購入量に応じたクレジットの割引価格を得ることができます。

[#how-can-i-get-on-prepaid-billing]
=== プリペイド課金にするにはどうしたらいいのですか？

すべての Performance プランをご利用のお客様の皆様には、CircleCIウェブアプリからプリペイド課金にすることを選択できます。 このオプションにアクセスするには、次の手順に従います：

. CircleCI の Web アプリで **Plan** を選択する
. **Manage** タブを選択します
. プリペイド課金への切り替えを開始するには、**Set up and switch**を選択します

[#i-still-have-credits-from-my-monthly-subscription]
=== 月額課金のクレジットが残っていますが、今からプリペイド課金にするとどうなりますか？

以前に購入されたクレジットは引き続き利用でき、12ヶ月の有効期限も残ります。

[#i-selected-prepaid-billing-but-i-didnt-receive-a-discount]
=== プリペイド課金を選択したが、割引が適応されていません。 どうしてでしょうか？

プリペイド課金の割引は、購入数量が500万クレジットから開始されます。

[#what-happens-when-i-run-out-of-all-my-prepaid-billing-credits]
=== プリペイドクレジットを使い切った場合はどうなりますか？

現在の Performance プランと同様に、クレジットが不足すると、クレジットパッケージは選択した購入レベルで自動的に更新されます。

[#when-will-i-be-charged-for-my-prepaid-billing-purchase]
=== プリペイド課金の購入代金はいつ請求されますか？

プリペイド方式を選択した場合、クレジットカードに即時課金され、その後、 クレジットが不足した場合、再度クレジットカードに課金され、補充されます。

[#i-want-to-change-my-upcoming-prepaid-billing-refill]
=== 今後予定しているプリペイド課金リフィルを変更したいのですが、どうすればよいですか？

適用するには以下の手順を実行します。

. CircleCI の Web アプリで **Plan** を選択する
. **Manage** タブを選択します
. 自動リフィルレートを編集するには、**Credits**セクションの鉛筆アイコンをクリックします。

[#do-i-still-get-bonus-credits-and-5-free-seats]
=== プリペイド課金でもボーナス 30,000 クレジットと無料の5のユーザーシートはもらえるのでしょうか？

はい、プリペイド課金のお客様には、毎月30,000クレジットと5つの無料ユーザーシートの特典を引き続きご提供いたします。

[#share-plans-across-organizations-billed-centrally]
=== 複数の組織で契約プランを共有できますか？ その場合、請求を 1 箇所にまとめることは？

もちろん可能です。CircleCI アプリのサイドバーから `Plan` を選択し、`Share & Transfer` をクリックします。

Free プラン以外のプランでは、`Add Shared Organization` (共有組織の追加オプション) を使用して、管理者アクセス権を持つフリープランの組織とプランを共有することができます。 プランを共有するすべての組織が「Share & Transfer」のページに記載され、子組織のすべてのクレジットとその他の利用料金が親組織に請求されます。

Free プラン以外のプランでは、`Transfer Plan` オプションによりお客様が管理者としてのアクセス権を持つ他の Free プランの組織にお客様のプランを譲渡することができます。 有料プランを別の組織に譲渡した場合、お客様の組織は Free プランにダウングレードされます。

[#container-used-for-under-one-minute-pay-for-a-full-minute]
=== コンテナの使用時間が 1 分未満でも、1 分間分の料金が計上されますか?

はい、その場合でも 1 分間分の料金をお支払いいただく必要があります。 1 分未満の秒単位は切り上げてクレジットを計算します。

[#calculate-monthly-storage-and-network-costs]
=== 1ヶ月のストレージ使用料金とネットワーク料金の計算方法は？

link:https://app.circleci.com/[CircleCI アプリ]で Plan &#062; Plan Usage に移動して、お客様のストレージとネットワークの使用状況を確認し、毎月のストレージとネットワークの料金を計算します。

[#storage]
==== ストレージ

日々の使用量から 1ヶ月のストレージ料金を計算するには、 *Storage* タブをクリックし、組織の月間の割り当て GB を超過していないかを確認します。 超過分（GB-Months/TB-Months）に 420 クレジットを乗じることで、1ヶ月の料金を見積もることができます。 計算例：2 GB-Months の超過 x 420 クレジット = 840 クレジット (0.5 ドル)。

[#network]
==== ネットワーク

ネットワークの使用に対する課金は、CircleCI からセルフホストランナーへのトラフィックに対してのみ適用されます。 詳しくは、xref:persist-data#overview-of-network and-storage-transfer[データの永続化の概要]のページをご覧ください。

超過分（GB/TB）に 420 クレジットを乗じることで、その月の料金を見積もることができます。 計算例：2 GB-Months の超過 x 420 クレジット = 840 クレジット (0.5 ドル)。

[#calculate-monthly-IP-ranges-costs]
=== 1ヶ月の IP アドレスの範囲機能料金の計算方法は？

1ヶ月の IP アドレスの範囲機能の料金は、link:https://app.circleci.com/[CircleCI アプリ]で Plan &#062; Plan Usage に移動し、IP アドレスの範囲機能の利用状況を確認して計算します。

IP アドレスの範囲機能の使用状況 のサマリーに加えて、 IP Ranges タブに移動するとお客様のデータ使用状況の詳細を確認できます。 このタブでは、IP アドレスの範囲機能の使用量の値は、 IP アドレスの範囲機能が有効なジョブの実行中の Docker コンテナ内外の未加工のバイト数を表します。

このバイト数には、ジョブの全体のネットワーク通信および Docker コンテナの送受信に使われるバイトも含まれます。 IP アドレスの範囲機能が有効なジョブにおいて、ジョブの実行の開始前に Docker イメージをコンテナにプルするために使用されるデータに対しては料金は発生しません 。

この機能は、IP アドレスの範囲機能が有効なジョブで使用されるデータ 1 GB ごとに、お客様のアカウントから 450 クレジットを消費します。 *Job Details* UI ページの *Resources* タブで各ジョブの IP アドレスの範囲機能の使用状況の詳細をご覧いただけます。 詳しくは、xref:ip-ranges#pricing[IP アドレスの範囲機能]のページをご覧ください。

[#predict-monthly-IP-ranges-cost-without-enabling-feature-first]
=== 有効化する前に 1ヶ月の IP アドレスの範囲機能の料金を見積もるにはどうすれば良いですか？

Job Details の UI ページの **Resources** タブから、すべての Docker ジョブ (リモート Docker を除く) の概算ネットワーク通信量を確認できます。 GB になっていない場合は GB に変換し、450 クレジットを乗じて Docker ジョブで IP アドレスの範囲機能を有効にする場合の概算コストをお見積もりください。

[#per-active-user-pricing]
=== アクティブユーザー単位の料金が設定されているのはなぜですか?

クレジットは、コンピューティングの利用に対して消費されます。 CircleCI は、できるだけコストを抑えながら、CI の基本的な推奨事項である「頻繁なジョブ実行」を行っていただくことを目指しています。 アクティブユーザー単位で設定しているのは、プラットフォーム機能とジョブオーケストレーションの利用に対する料金です。 たとえば、依存関係のキャッシュ、アーティファクトのキャッシュ、ワークスペースなどがあり、いずれの機能も追加のコンピューティングコストをかけずにビルド時間を短縮するのに役立ちます。

[#what-constitutes-an-active-user]
=== アクティブユーザーの定義を教えてください。

アクティブユーザー（`active user`）とは、非 OSS プロジェクトでコンピューティングリソースの使用をトリガーするユーザーのことです。 次のようなアクティビティが含まれます。

- ビルドをトリガーするユーザーからのコミット (PR マージ コミットを含む)
- CircleCI の Web アプリケーションでのジョブの再実行 (xref:ssh-access-jobs#[SSH デバッグ]を含む)
- xref:workflows#holding-a-workflow-for-a-manual-approval[手動承認後に処理を続行するワークフロー]ジョブの手動承認 (承認者はすべてのダウンストリームジョブの実行者と見なされる)
- スケジュールされたワークフローの使用
- マシンユーザー

NOTE: プロジェクトが xref:oss#[オープンソース]の場合は、アクティブ ユーザーとは見なされません。

アクティブ ユーザーの一覧は、CircleCI の Web アプリケーションにログインし、[Settings (設定)] > [Plan Usage (プランの使用状況)] の順に移動して、[Users (ユーザー)] タブで確認できます。

[#charged-job-is-queued-or-preparing]
=== ジョブが「Queued」または「Preparing」の場合、課金されますか？

いいえ。 ジョブが "queued (キューイング中)"と通知された場合、ジョブがプランや同時実行の制限により待機状態になっていることを意味しています。 ジョブが "preparing (準備中)" の場合は、CircleCI がセットアップを行っているか、ジョブの実行を 開始 しようとしているため間もなく実行される可能性があります。

[#other-renewal-dates]
=== 有料プランの更新日はいつですか?

CircleCI からの請求が発生する以下の日付に加え、有料プランへのアップグレードや別の有料プランへの変更をして初めてクレジットカードで決済した日付が、更新日として設定されます。

- 月間プランでは、毎月の月額料金の請求日が更新日になります。
- 年間プランでは、年に一度の年額料金の請求日が更新日になります。
- 年間プランをご利用中でも、ユーザーの追加やクレジットの補充によって未払い残高が発生した場合は、その月の最終日が更新日になります。
- Performance プランでは、クレジットの残りが設定された最小値を下回った場合、自動的にクレジットが購入されます。

[#credit-plans-for-open-source-projects]
=== オープンソースプロジェクト向けのクレジットベースプランはありますか?

Free プランを利用されているオープンソースの組織には、Linux オープンソースプロジェクトに使用できる 400,000 クレジットが毎月無料で付与されます。  使用できるオープンソースクレジットの量や制限は、UI 画面上では確認できません。

CircleCI の Free プランを使用して macOS でビルドを行っている組織にも、毎月 25,000 クレジットが無料で付与され、macOS オープンソースプロジェクトのビルドに利用できます。 希望される場合は、billing@circleci.com までお問い合わせください。 macOS オープンソースのビルド用の無料クレジットは、1 組織あたり最大 2 件のジョブの同時実行に使用できます。

[#discounts-for-open-source-performance-plan]
=== Performance プランのオープンソースプロジェクトで割引を受けるにはどうすればよいですか?

現在、Performance プランでオープンソースをご利用のお客様への割引は行っていません。

[#charge-for-docker-layer-caching]
=== Docker レイヤー キャッシュの利用に料金が発生するのはなぜですか?

Docker レイヤー キャッシュ (DLC) は、変更のあった Docker レイヤーのみを再ビルドすることで、Docker イメージをビルドするパイプラインでのビルド時間を削減する機能です (DLC の詳細はxref:docker-layer-caching#[こちら])。 DLC は 1 回のジョブ実行につき 200 クレジットを消費します。

お客様に DLC を安心してご利用いただくために、CircleCI ではいくつかの処理を行っています。 ソリッドステートドライブを使用し、キャッシュをゾーン間で複製し、DLC を利用可能な状態にします。

DLC のご利用金額を見積もるには、設定ファイル内の Docker レイヤーキャッシュが有効になっているジョブと、それらのジョブでビルドしている Docker イメージの数を確認してください。 設定ファイルにジョブが 1 度だけ記述されている場合でも、たとえば並列実行を有効にした場合は、そのジョブがパイプラインで複数回実行される場合もあります。
