[#pipeline-parameters-api]
=== パイプラインパラメーターは API でしか使用できないのではありませんか？

以前は、パイプラインパラメーターは API でしか使用できませんでしたが、 今では、ダイナミックコンフィグ機能を使用すると、パイプラインが実行される (API または Webhook のいずれかからトリガーされる、つまり VCS へのプッシュイベント) 前に、パイプラインパラメーターを動的に設定できるようになりました。

[#can-i-use-a-custom-executor]
=== Can I use a custom executor?

Custom executors can be used, but require certain dependencies to be installed for the continuation step to work (currently: `curl`, `jq`).

[#what-is-the-continuation-orb]
=== What is the continuation orb?

The `continuation` orb assists you in managing the pipeline continuation process. The
`continuation` orb wraps an API call to link:https://circleci.com/docs/api/v2/#operation/continuePipeline[`continuePipeline`]. Refer to the link:https://circleci.com/developer/orbs/orb/circleci/continuation[`continuation`] orb documentation for more information.

[#possible-to-not-use-continuation-orb]
=== Is it possible to not use the continuation orb?

If you have special requirements not covered by the continuation orb, you can implement the same functionality in other ways. Refer to the link:https://circleci.com/developer/orbs/orb/circleci/continuation#orb-source[orb source code] to learn how the continuation functionality is implemented with the orb.