[#does-circleci-look-at-my-code]
=== CircleCI のスタッフにプログラムコードを見られる可能性はありますか？

CircleCI のスタッフがお客様の許可を得ずにコードを見ることはありません。 お客様が問題解決のサポートを希望される際は、事前に許可を得たうえで、サポートエンジニアがコードを確認させていただく場合があります。

詳しくは CircleCI の xref:security#[セキュリティポリシー]をご覧ください。

[#use-circleci-without-creating-base-images]
=== 基本イメージを作成していなくても、CircleCI  を使用できますか?

はい、CircleCI では Docker Executor で使用する多数の「CircleCI イメージ」を提供しています。 イメージの使用方法および全リストは、link:https://circleci.com/ja/developer/images[CircleCI Developer Hub] および xref:circleci-images#[CircleCI イメージのガイド]をご覧ください。

For the `machine` executor, see the xref:configuration-reference#available-linux-machine-images[available machine images] list.

For an introduction to execution environments and images, see the xref:executor-intro#[Introduction to execution environments].

[#request-new-features]
=== 新機能のリクエストは可能ですか？

Yes, you can visit CircleCI's link:https://circleci.canny.io/[Ideas] page to request new features, or view features that have already been requested. To request a new feature, you will first need to select a category from the *Give Feedback* section.

When viewing requested features, you can sort by *Trending*, *Top*, and *New*, as well as filter by the following:

- *Under Review*: CirlceCI is considering these feature requests.
- *Planned*: CircleCI has planned to work on these feature requests in the future.
- *In Progress*: CircleCI is currently working on these feature requests.
- *Complete*: CircleCI has added these feature requests to its current offerings.