[#can-orbs-be-private]
=== Can orbs be made private?

xref:orb-intro#private-orbs[Private orbs] are available on any of our link:https://circleci.com/pricing[current plans].

[#difference-between-commands-and-jobs]
=== What is the difference between commands and jobs?

Both xref:reusing-config#the-commands-key[commands] and xref:reusing-config#authoring-parameterized-jobs[jobs] are elements that can be used within orbs.

_Commands_ contain one or many xref:configuration-reference#steps[steps], which contain the logic of the orb. コマンドは多くの場合、シェルコード (バッシュ) を実行します。

_Jobs_ are a definition of what steps/commands to run and the xref:reusing-config#the-executors-key[executor] to run them in. _Jobs_ invoke commands, and are orchestrated using xref:workflows#workflows-configuration-examples[workflows].

[#orbs-on-private-installation-server]
=== Can orbs be used on a private installation of CircleCI server?

Orbs can be used with installations of CircleCI server v3. For information on importing and using orbs for server, see the xref:server-3-operator-orbs#[CircleCI Server v3.x orbs guide].

CircleCI Server v2.19.x では Orb は使用できませんが、コミットの前に設定を処理すると、Orb を変換して使用できます。 Follow this guide on using git pre-commit hooks to link:https://discuss.circleci.com/t/orbs-on-server-solution/36264[use orbs on server].

[#report-an-issue-with-a-public-orb]
=== How can I report a bug or issue with a public orb?

All public orbs are open source projects. 問題やバグのレポートだけでなく、プルリクエストも Orb の Git リポジトリに対して行えます。 Public orb authors may opt to include a link to the git repo on the orb registry. Git リポジトリへのリンクがない場合は、サポートまでご連絡ください。作成者に連絡いたします。 または、その Orb をフォークして、独自のバージョンをパブリッシュすることもできます。

[#how-to-use-the-latest-version-of-an-orb]
=== How do I use the latest version of an orb?

Orbs use semantic versioning, meaning if you set the _major_ version (example: `3`), you will receive all _minor_ and _patch_ updates, where if you statically set the version (example: `3.0.0`), no updates will apply, this is the most deterministic and recommended method.

WARNING: NOT RECOMMENDED - It is possible to use `@volatile` to receive the last published version of an orb. これは互換性を損なう変更が含まれる場合があるため推奨していません。