[#can-orbs-be-private]
=== Orb をプライベートにすることはできますか？

xref:orb-intro#public-or-private[プライベート Orb] は、link:https://circleci.com/pricing[当社が提供しているすべてのご利用プラン]で利用可能です。

[#difference-between-commands-and-jobs]
=== コマンドとジョブの違いは何ですか？

xref:reusing-config#the-commands-key[commands] と xref:reusing-config#authoring-parameterized-jobs[jobs] はいずれも orbs 内で使用可能な要素です。

コマンド には、Orb のロジックを含む一つまたは複数のxref:configuration-reference#steps[ステップ]が含まれます。 コマンドは多くの場合、シェルコード (bash) を実行します。

ジョブ は、実行するステップやコマンドの定義であり、 かつ、 ステップやコマンドを実行する xref:reusing-config#the-executors-key[Executor] です。 ジョブはコマンドを呼び出し、xref:workflows#workflows-configuration-examples[ワークフロー]を用いてオーケストレーションされています。

[#orbs-on-private-installation-server]
=== Orb はプライベートなインストール環境で使用できますか？

Orb は、CircleCI Server v3 でご利用いただけます。 CircleCI Server での Orb のインポートと使用に関しては、xref:server-3-operator-orbs#[CircleCI Server v3.x の Orb ガイド]を参照して下さい。

CircleCI Server v2.19.x では Orb は使用できませんが、コミットの前に設定を処理すると、Orb を変換して使用できます。 コミット前の Git Hook の使用については、link:https://discuss.circleci.com/t/orbs-on-server-solution/36264[サーバーでの Orb の使用]を参照して下さい。

[#report-an-issue-with-a-public-orb]
=== パブリック Orb  に関するバグや問題をレポートする方法は？

すべての Orb はオープンソースプロジェクトです。 問題やバグのレポートだけでなく、プルリクエストも Orb の Git リポジトリに対して行えます。 パブリック Orb 作成者は、Orb レジストリ上で Git リポジトリへのリンクを含めるか選択できます。 Git リポジトリへのリンクがない場合は、サポートまでご連絡ください。作成者に連絡いたします。 または、その Orb をフォークして、独自のバージョンをパブリッシュすることもできます。

[#how-to-use-the-latest-version-of-an-orb]
=== Orb の最新バージョンを使うにはどうすればいいですか？

Orb にはセマンティックバージョニングが使用されています。つまり、メジャーバージョンを設定すると (例:3 )、マイナーとパッチのすべてのアップデートを受け取ります。静的にバージョンを設定すると(例:3.0.0 )、アップデートは適用されません。これが最も決定論的で推奨される方法です。

WARNING: **注: 非推奨** `@volatile`  を使って最新バージョンの Orb を受け取ることも可能です。 これは互換性を損なう変更が含まれる場合があるため推奨していません。