[#split-config-into-different-files]
=== Is it possible to split the `.circleci/config.yml` into different files?

Splitting your `.circleci/config.yml` into multiple files is not supported. If you would like more information on this, you can view this link:https://support.circleci.com/hc/en-us/articles/360056463852-Can-I-split-a-config-into-multiple-files[support article].

設定ファイルの分割機能は提供していませんが、CircleCI ではダイナミックコンフィグ機能を提供しています。この機能により、特定のパイプラインやパスに基づき設定ファイルを作成することができます。 See the xref:dynamic-config#[Dynamic configuration] page for more information.

[#build-forked-prs-using-pipelines]
=== パイプラインを使ってフォークされた PR をトリガーできますか？

You can trigger pipelines to build PRs from forked repositories with CircleCI link:https://circleci.com/docs/api/v2/[API v2]. しかしデフォルトでは、フォークされたリポジトリからの PR をビルドしません。 If you would like to turn this feature on, navigate to menu:Project Settings[Advanced] in the web app. If you would like more information, you can view this link:https://support.circleci.com/hc/en-us/articles/360049841151-Trigger-pipelines-on-forked-pull-requests-with-CircleCI-API-v2[support article].