---
version:
- Server v4.x
- Server Admin
---
= Upgrade server v4.x
:page-layout: classic-docs
:page-liquid:
:page-description: "This document lists the steps required to upgrade a CircleCI server v4.x installation."
:icons: font
:toc: macro
:toc-title:

This page describes the steps needed to upgrade you CircleCI server v4.x installation.

A successful deployment will update the web app. Unless noted in the release notes, updates are rolling updates and there is no downtime.

NOTE: We recommend that you do not skip releases when upgrading.

[#prerequisites]
== Prerequisites

* Ensure you have access to the Kubernetes cluster in which server is installed.
* Ensure you have set up link:/docs/server/operator/backup-and-restore[Backup and Restore].
* Ensure there is a recent backup. For more information, see the link:/docs/server/opertor/backup-and-restore#creating-backups[Backup and Restore] guide.

[#upgrade-steps]
== Upgrade steps

. Check the https://circleci.com/server/changelog/[change log] and make sure there are no actions you need to take before deploying a new version.

. Optionally, confirm what the update is going to do using https://github.com/databus23/helm-diff[Helm Diff]:
+
[source,shell]
helm diff upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD

. Perform the upgrade:
+
[source,shell]
helm upgrade circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version <version> -f <path-to-values.yaml> --username $USERNAME --password $PASSWORD

. Deploy and run https://github.com/circleci/realitycheck[`reality check`] in your test environment to ensure your installation is fully operational.
