= Server docs release process
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

== Patch Release



== Feature Release

* Start a new branch with a name starting `server/`.
* Set the release version within the PDF build script (`$VERSION`) and also within the Jekyll `_config.yml` under both asciidoc attributes called `serverversion`.
* Make operational changes required for the release.
* If anything has changed about the installation or upgrade process, point these out in the relevant docs.
* Create a new What's New in vx.y.z page.
* Check the comment is `FINAL` in the build script once all changes are made.
* Commit and push your changes up to open a PR. New PDFs will be built in the job `build_server_pdfs` and the new docs appear as artifacts.
* Locally, rename the current PDFs with the previous version name so they do not get overridden.
* Download the new PDF versions to the `jekyll/_cci2` folder.
* Add a new PDF section for the version in `jekyll/_data/sidenav.yml`.
