---
version:
- Server v4.x
- Server Admin
---
= CircleCI Server v4.x Migration
:page-layout: classic-docs
:page-liquid:
:page-description: Learn now to migrate from CircleCI server 3.x to 4.x.
:icons: font
:toc: macro
:toc-title:

Migrating from 3.x to 4.x is in-place migration which requires you to generate helm-value file which will be used in helm command to upgrade the CircleCI Server 3.x to v4.x.

We recommend using a staging environment before completing this process in a production environment. This will not only allow you to gain a better understanding of the migration process, but also give you an idea of how long the migration will take to complete.

toc::[]

## Prerequisites

. Your current CircleCI Server installation is 3.x.
. You have taken a backup of the 3.x instance. If you are using external datastores, they need to be backed up separately.
. You dont need a new CircleCI Server 4.x as it is an in-place migration.
. The migration script must be run from a machine with below tools:
- link:https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl] configured for the server 3.x instance
- link:https://github.com/mikefarah/yq#install[yq]
- link:https://github.com/helm/helm#install[helm]
- link:https://github.com/databus23/helm-diff#install[helm-diff]

### External Datastores Only
. Backups have been taken of all external data stores.

### Internal Datastore Only
. You have taken a backup of the 3.x instance.
. Follow the instruction link:https://circleci.com/docs/2.0/server-3-operator-backup-and-restore[here] 

## Migration

To do in-place upgrade of CircleCI Server 3.x to 4.x, You have to execute a migration script which will perform below task:

* Export the kots config values into a yaml file
* Modify the exported yaml file to be use with `helm` for server 4.x
* Annotate all the kubernetes resource for helm
* Execute postgres db `domain` migration
* Display output message with the next steps

The kots-exporter script can also perform below functions if required:

* Rerun the annotation step only (`-f annotate`)
* Run the kots-annotation cleanup job (`-f kots_cleanup`)
* Display the output message (`-f message`)
* Rerun the postgresql database migration (`-f flyway`)

### Step 1 - Create docker secret for CircleCI image registry
Migration script will require access to CircleCI image registry to run the migration function as well as utilize in CircleCI Server 4.x, so you have to create the `docker-registry` secret in the same kubernetes namespace where CircleCI is installed. Image Registry credential will be provided by your CircleCI point of contact. 

In a terminal:

```
kubectl -n <namespace> create secret docker-registry regcred \
  --docker-server=<image-registry-hostname> \
  --docker-username=<image-registry-username> \
  --docker-password=<image-registry-password> \
  --docker-email=<notification-email-id>
```

### Step 2 - Clone the repository and run the kots-exporter script
The instructions below will clone the repository containing the kots exporter script which will generate the `helm-value` file for server 4.x.

. Run `git clone \https://github.com/CircleCI-Public/server-scripts`.
. Change into the `server-kots-exporter` directory: `cd server-scripts/server-kots-exporter`.
. Run the migration script: `./kots-exporter.sh`.
. You will be prompted for the following information:
  * Release Name of your server 3.x installation - `circleci-server`
  * Kubernetes namespace of your server 3.x installation
  * License String for Server 4.x, It will be provided by your CircleCI point of contact.

. After the script has completed, It will display a message for the next steps to perform. Message will be like below -

```
############ HELM Commands ################
Output file is here - <path>/server-kots-exporter/output/helm-values.yaml

To upgrade Postgres Chart(v11.6.0), follow below steps -
-------------------------------------------------------------------------
export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace <namespace> postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode)
export POSTGRESQL_PVC=$(kubectl get pvc --namespace <namespace> -l app.kubernetes.io/instance=circleci-server,role=primary -o jsonpath="{.items[0].metadata.name}")
kubectl delete statefulsets.apps postgresql --namespace <namespace> --cascade=orphan
kubectl delete secret postgresql --namespace <namespace>
-------------------------------------------------------------------------

Helm Diff command (only changes) - - helm diff upgrade <release-name> -n <namespace> -f <path>/server-kots-exporter/output/helm-values.yaml --show-secrets --context 10 <chart>
Helm Diff command (complete) - - helm diff upgrade <release-name> -n <namespace> -f <path>/server-kots-exporter/output/helm-values.yaml  --show-secrets <chart>
Helm upgrade command - helm upgrade <release-name> -n <namespace> --wait -f <path>/server-kots-exporter/output/helm-values.yaml <chart>
```

NOTE: With Server 4.x, Postgres chart is also being migrated hence, you must execute the commands mentioned in output message.

### Step 3 - Validate your helm-value file
Validate the generated helm value file for values and modify as required.

### Step 4 - Generate helm-diff output
Next, execute the helm-diff command and review the output -

```
 helm diff upgrade <release-name> -n <namespace> -f <path>/server-kots-exporter/output/helm-values.yaml --show-secrets --contexts 10 <chart-directory>
```

Review the output generated from above command with below legends -

* line display in `Yellow` - Kubernetes resources status i.e. - changed, added
* line displayed in `Red`    - Deletion  i.e. - image  
* line displayed in `Green`  - Addition i.e. - imagePullSecret


Below are the changes you exptect to see in helm-diff output -

* `imagePullSecrets` is added into all the kubernetes resources
* Container images are updated
* Secret Environment variables (i.e - api-token, signing-keys) are now referencing to kubernetes Secrets
* Environment variables for RabbitMQ & MongoDB URIs are changing
* Environment variables for VM, OUTPUT & NOMAD service uri are refrecing to `<domain_name>:<service_port>`
* Annotations from VM, OUTPUT & NOMAD service resources are deleted.
* Github checksum is added as annotations
* Secret and annotation for `distributor-*` deployments are deleted
* Upstream chart `postgresql` is updated.
* Upsteam charts will be recreated (delete & create) -
  - prometheus (circleci-server-kube-state-metrics, node-exporter,prometheus-server)
  - mongodb
  - rabbitmq
  - redis (redis-master, redis-slave)

### Step 5 - Upgrading CircleCI Server 3.x
Once, helm-value file is verified, Run the below command to upgrade the CircleCI Server 3.x to 4.x
```
helm upgrade <release-name> -n <namespace> --wait -f <path>/server-kots-exporter/output/helm-values.yaml <chart>
```

### Step 6 - Check upgrade status
Run below command to check if all pods are up and running 
```
kubectl -n <namespace> get pods
```

### Step 7 - Update DNS setting
Server 4.x migration is destructive change for your DNS configuration. There is only one load-balancer/external-ip which you have to update in DNS configuration.
```
kubectl -n <namespace> get svc circleci-proxy
```
Below kubernetes service objects are renamed/changed - 

- circleci-server-traefik (LoadBalancer) -> kong (ClusterIP)
- nomad-server-external (LoadBalancer) -> nomad-server (ClusterIP)
- output-processor (LoadBalancer) -> output-processor (ClusterIP)
- vm-service (LoadBalancer) -> vm-service (ClusterIP)

Below kubernetes service object is added -

- circleci-proxy (LoadBalancer)

### Step 8 - Validate your migration to Server 4.0  
Re-run https://support.circleci.com/hc/en-us/articles/360011235534-Using-realitycheck-to-validate-your-CircleCI-installation[realitycheck] on your new server 4.x environment by pushing a fresh commit.

### Step 9 - Execute Cleanup Step
Execute the cleanup step as below to remove the `kots` annotation and pod (Note: Do not execute this step if you face any issues in above steps) -
```
cd server-scripts/server-kots-exporter
./kots-exporter.sh -f kots_cleanup
```

### Step 10 - Update your team
Once you have successfully run https://support.circleci.com/hc/en-us/articles/360011235534-Using-realitycheck-to-validate-your-CircleCI-installation[realitycheck],
notify your team about the upgrade.

ifndef::pdf[]
## What to read next
* https://circleci.com/docs/2.0/server-3-install-hardening-your-cluster[Hardening Your Cluster]
* https://circleci.com/docs/2.0/server-4-operator-overview[Server 4.x Operator Guide]
endif::[]
