---
contentTags:
  platform:
    - Server v4.3
    - Server Admin
---
= CircleCI server v4.3 release notes
:page-layout: classic-docs
:page-liquid:
:page-description: Details of the new features included in each CircleCI server v4.3 release.
:icons: font
:toc: macro
:toc-title:

[#overview]
== Overview

The v4.3 release introduces upgraded execution architecture. Previously, VM service was responsible for creating virtual machines for `machine` and remote Docker jobs. This has been replaced with machine provisioner. The new architecture has improved efficiency and stability. This upgrade also brings server inline with CircleCI cloud execution, meaning server will benefit from future updates faster. Some specific benefits include:

* A new UI for step output, which is better at handling larger output and colour.
* New systems for processing job output (step data, caches, artifacts etc.) is much more efficient.
* `machine` and remote Docker jobs no longer run through Nomad so compute costs are cut down significantly.
* You do not need to run a Nomad cluster if you just want to run machine (and/or remote Docker jobs) on your server instance.
* DLC is now configured to run through S3, which is cheaper than running on SSD volumes, and there is no longer a limit on the amount of DLC jobs that can be run in parallel. DLC stays more consistent with better pruning and is shared between all jobs in a project instead of each cache being different.
* VM service could fall back to another region/zone, but machine provisioner can handle gaps in availability through:
** Distributing load across availability zones through round-robining
** Sending a percentage of traffic to a different zone
** Instance type fallbacks based on deficits and success

[#upgrade]
== Upgrade
For upgrade steps see the xref:../installation/upgrade-server#[Upgrade server v4.3 guide]. There is a background database migration job that is run on install/upgrade to server 4.3. When upgrading to 4.3 you **must ensure this job completes**.

https://circleci.com/changelog/server-release-4-3-5/

[#release-4-3-5]
== Release 4.3.5

[#changelog-4-3-5]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-3-5/[changelog].

[#release-4-3-4]
== Release 4.3.4

[#changelog-4-3-4]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-4-3-4/[changelog].

[#release-4-3-3]
== Release 4.3.3

[#changelog-4-3-3]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-3-3/[changelog].

[#release-4-3-2]
== Release 4.3.2

[#changelog-4-3-2]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-3-2/[changelog].

[#release-4-3-1]
== Release 4.3.1

[#changelog-4-3-1]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-3-1/[changelog].

[#release-4-3-0]
== Release 4.3.0

[#changelog-4-3-0]
=== Changelog

For full details of this release see the link:https://circleci.com/changelog/server-release-4-3/[changelog].
