= Glossary
:page-platform: Cloud, Server v4+
:page-description: A glossary of terms used for the CircleCI product.
:experimental:

[#circleci-administrator]
== CircleCI administrator

The first user to log into a private installation of CircleCI. Administrators have the ability to add and remove users.

[#container]
== Container

A container is a running instance of an image.

== Context

xref:guides:security:contexts.adoc[Contexts] provide a mechanism for securing and sharing environment variables across projects. The environment variables are defined as name/value pairs and are injected at runtime. After a context has been created, you can use the context key in the workflows section of a project `.circleci/config.yml` file to give any job(s) access to the environment variables associated with the context.

[#docker-layer-caching]
== Docker layer caching

The CircleCI Docker Layer Caching (DLC) feature allows builds to reuse Docker image layers from previous builds. Use DLC to speed up workflows. Jobs that are configured to build Docker images run in a shorter time on subsequent runs. Layers may only be used by builds from the same project. For more information and usage examples, see the xref:guides:optimize:docker-layer-caching.adoc[Docker Layer Caching] and xref:guides:execution-managed:building-docker-images.adoc[Running Docker Commands] pages.

[#environment-variables]
== Environment variables

xref:guides:security:env-vars.adoc[Environment variables] store customer data that is used by a project. Only project administrators and owners are allowed to view or modify environment variables. The values are transmitted using secure protocols, for example, HTTPS and SSH, encrypted at rest, and hashed/salted to prevent CircleCI employees from viewing them.

[#executor]
== Executor

xref:guides:execution-managed:executor-intro.adoc[Executors] define the underlying technology to run a job. Can be either `docker` to run your job inside a Docker container with a specified image, or `machine` to run your job inside a full virtual machine.

[#image]
== Image

An image is a packaged system that includes instructions for creating a running container. The primary container is defined by the first image listed in a `.circleci/config.yml` file. This is where commands are executed for jobs, using the Docker or machine executor. Visit the https://circleci.com/developer/images[CircleCI Developer Hub] to see available convenience and machine images.

[#job-space]
== Job space

All the containers being run by an <<executor>> for the current job.

[#job]
== Job

xref:guides:orchestrate:jobs-steps.adoc[Jobs] are collections of steps, which run commands/scripts as required. Each job must declare an executor that is either `docker`, `machine`, `windows`, or `macos`.

[#orbs]
== Orbs

xref:orbs:author:orb-concepts.adoc[Orbs] are reusable snippets of code that help automate repeated processes, accelerate project setup, and make it straight forward to integrate with third-party tools. Visit the https://circleci.com/developer/orbs[Orbs Registry] on the CircleCI Developer Hub to search for orbs to help simplify your config.

[#owner]
== Owner

The owner of the team's VCS organization.

[#pipeline]
== Pipeline

A xref:guides:orchestrate:pipelines.adoc[CircleCI pipeline] is the full set of processes you run when you trigger work on your projects. Pipelines encompass your workflows, which in turn coordinate your jobs. Pipelines are defined in your project `.circleci/config.yml` file.

[#primary-container]
== Primary container

The first image listed in `.circleci/config.yml`. This is where commands are executed for jobs using the Docker executor.

[#project-administrator]
== Project administrator

The user who adds a repository in the VCS to CircleCI as a project.

[#project]
== Project

For xref:guides:integration:github-integration.adoc[GitHub OAuth app] and xref:guides:integration:bitbucket-integration.adoc[Bitbucket Cloud] accounts, a CircleCI project shares the name of the code repository for which it automates workflows, tests, and deployment. A project is visible on the **Projects** page of the https://app.circleci.com/[CircleCI web app] and must be added with the **Set Up Project** button.

For xref:guides:integration:github-apps-integration.adoc[GitHub App], xref:guides:integration:gitlab-integration.adoc[GitLab] and xref:guides:integration:bitbucket-data-center-integration.adoc[Bitbucket Data Center] accounts, a CircleCI project is a standalone entity that you first create, and then associate with a code repository. You can create projects and connect your code in the link:https://app.circleci.com/[CircleCI web app].

After a project is set up or created, it is possible to configure settings, contexts, environment variables, and team members who may follow the project. Following a project enables you to subscribe to email notifications for the project's build status, and adds the project to your CircleCI dashboard.

[#remote-docker]
== Remote Docker

A feature that enables building, running, and pushing images to Docker registries from within a Docker <<executor>> job. Visit the xref:guides:execution-managed:building-docker-images.adoc[Runner Docker Commands] page to learn more.

[#resource-class]
== Resource class
A configuration option for specifying compute resource sizing for a job. Also used as a label to identify a pool of self-hosted runners and to configure a job to run on a self-hosted runner from that pool. Read more on the xref:guides:execution-managed:resource-class-overview.adoc[resource class overview] page.

[#step]
== Step

A step is a collection of executable commands. Visit the xref:guides:toolkit:sample-config.adoc[Sample Configuration] page to learn more.

[#user]
== User

An individual user within an organization. A CircleCI user is anyone who can log in to the CircleCI platform with a username and password. Users must be added to a VCS organization to view or follow associated CircleCI projects. Users may **not** view project data that is stored in environment variables.

[#workflow]
== Workflow

xref:guides:orchestrate:workflows.adoc[Workflows] define a list of jobs and their run order. It is possible to run jobs concurrently, sequentially, on a schedule, or with a manual gate using an approval job.

[#workspace]
== Workspace

A xref:guides:orchestrate:workspaces.adoc[workspace] is a workflows-aware storage mechanism. A workspace stores data unique to the job, which may be needed in downstream jobs.
