= Migration Assistance Service
:page-platform: Premium Support, Advisory Services
:page-description: Migration Assistance Service

Migration assistance is a collection of engagements where your field engineer will ensure your projects are migrated onto CircleCI smoothly. Your field engineer will work with you to plan out a customized migration journey assisting with configuration translations, best practice implementation, training your developers, and more.

== Benefits

Teams that work with their field engineer to migrate their projects:

* Migrate onto CircleCI faster using their field engineer's expert knowledge.
* Start with a more centralized approach to managing CircleCI.
* Can lean on their field engineer to research how to implement CircleCI for their use case.
* Better understand how CircleCI works for their organization and the data it provides.

== Intended Audience

Teams that are new to CircleCI who would like expert assistance to plan and action on their migration to CircleCI.