= Optimization assistance service
:page-description: Optimization assistance service

Optimization assistance is a collection of engagements where your field engineer helps your projects run optimally on CircleCI. Your field engineer works with your team on an optimization journey tailored to your goals. Over the course of this journey, your field engineer performs configuration reviews, trains your team, and ensures you have the data you need.

== Benefits

Teams that work with their field engineer to optimize their projects:

* Achieve their DevOps goals faster using their field engineer's expert knowledge.
* Run more efficient builds for their developers.
* Operate CircleCI more efficiently.
* Better understand how CircleCI works for their organization and the data it provides.

== Intended audience

Teams that already use CircleCI and want expert assistance to plan and execute their DevOps optimization goals.

For more information, contact your CircleCI Account Team or our link:https://circleci.com/contact/[Sales team].