= Server Migration Service
:page-platform: Advanced Support, Premium Support, Advisory Services
:page-description: Server Migration Service

The server migration service is an engagement through which your field engineer will provides a seamless and efficient process for organizations when upgrading major/minor versions, migrating cloud providers or installing a new instance of CircleCI Server.

== Benefits

Teams that engage in a server migration service receive:

* A thorough analysis of the current setup and requirements.
* A customized migration plan to minimize downtime and potential disruptions.
* Data backup and transfer to ensure data integrity and continuity.
* Configuration of the new Server environment to match unique specifications.
* Rigorous testing to validate the successful migration and identify any issues promptly.
* Post-migration support and assistance to address any unforeseen challenges.

== Intended Audience

This service in intended to assist server administrators with setting up a migrating instance of CircleCI Server.