In this example you will create a deploy key with write access to a GitHub repository. The GitHub repository is `\https://github.com/you/test-repo`, and the CircleCI project is `\https://app.circleci.com/pipelines/github/you/test-repo`.

. Create an SSH key-pair by following the link:https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/[GitHub instructions]. When prompted to enter a passphrase, do **not** enter one (below is one example command to generate a key on macOS):
+
[source,console]
----
$ ssh-keygen -t ed25519 -C "your_email@example.com"
----

. Go to `\https://github.com/you/test-repo/settings/keys`, and select **Add Deploy Key**. Enter a title in the "Title" field, then copy and paste the public key you created in step 1. Check **Allow write access**, then select **Add key**.

. Go to your project settings in the CircleCI app, select **SSH Keys**, and **Add SSH key**. In the "hostname" field, enter `github.com` and add the private key you created in step 1. Then select **Add SSH Key**.

. In your `.circleci/config.yml` file, add the fingerprint to a job using the `add_ssh_keys` key:
+
```yaml
  version: 2.1

  jobs:
    deploy-job:
      steps:
        - add_ssh_keys:
            fingerprints:
              - "SO:ME:FIN:G:ER:PR:IN:T"
```

When you push to your GitHub repository from a job, CircleCI will use the SSH key you added.
